const assert=require('node:assert/strict');
const fs=require('node:fs');fs.mkdirSync('tmp/shock-house/polish',{recursive:true});
const {chromium}=require('C:/Users/Jennings/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){
 const p=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 const act=(a,id)=>p.locator(`button[data-action="${a}"]${id?'[data-id="'+id+'"]':''}:not([inert] *):visible`).first().click();
 await p.goto('http://127.0.0.1:4179/games/the-shock-house/');
 const saved=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('mastery-quests.shock-house.v1')));
 const leave=async()=>{while(await p.locator('[data-action="back"]').count())await act('back');};
 const camera=async room=>{await leave();for(let i=0;i<5&&(await saved()).currentRoom!==room;i++)await act('pan','right');};
 const shot=async name=>{await p.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode().catch(()=>{}))));await p.screenshot({path:`tmp/shock-house/polish/${name}-${width}.png`});};
 await p.evaluate(async()=>{const {newState}=await import('./engine.js');const s=newState();s.currentRoom='workshop';s.invoices=['early','late','middle'];s.inspectedObjects=['pay','food','bills'];s.householdPattern=[1,1,-1];localStorage.setItem('mastery-quests.shock-house.v1',JSON.stringify(s));});
 await p.reload();await act('continue');await act('open','cost');assert(await p.locator('[data-action="solve"][data-id="cost"]').isDisabled());assert.equal(await p.locator('[data-drag="invoices"]').count(),0);
 await camera('residence');await act('search','desk');await act('open','budget');await act('solve','budget');
 assert.equal(await p.locator('[data-action="drawer-preview"]').count(),3);assert.deepEqual((await saved()).inventory,[]);await shot('drawer');
 await act('drawer-preview','badge');assert(await p.locator('.physical-badge').isVisible());await act('back');assert.equal(await p.locator('[data-action="drawer-preview"]').count(),3);
 await act('drawer-preview','date');assert(await p.getByText('MARCH 14',{exact:true}).isVisible());await act('drawer-collect','date');assert.equal(await p.locator('[data-action="drawer-preview"]').count(),2);
 await p.reload();await act('continue');await act('search','desk');await act('open','budget');assert.equal(await p.locator('[data-action="drawer-preview"]').count(),2);
 for(const id of ['badge','household']){await act('drawer-preview',id);await act('drawer-collect',id);}assert.equal(await p.locator('[data-action="drawer-preview"]').count(),0);
 await camera('residence');await act('search','bag');await act('move','jar');await act('move','bread');const receipts=await p.locator('.sprite-receipt').evaluateAll(xs=>xs.map(x=>({top:x.style.top,left:parseFloat(x.style.left)})));assert.equal(receipts[0].top,receipts[1].top);assert(receipts[1].left-receipts[0].left<=20);await shot('receipts');
 await camera('workshop');await act('open','production');assert(await p.locator('.counter-readings').isVisible());assert.equal(await p.locator('.counter-readings dd').last().innerText(),'900');await shot('counter');await act('back');assert.equal(await p.locator('.inspection-layer').count(),0,'Counter opened in one click');
 await act('search','schedule');assert.equal(await p.locator('.worker-card.withdrawn').count(),3);await shot('staffing');await act('back');assert.equal(await p.locator('.inspection-layer').count(),0,'Rack opened in one click');
 await act('open','cost');assert(await p.locator('[data-action="solve"][data-id="cost"]').isDisabled());await act('use-badge');await act('solve','cost');assert((await p.locator('.room-notice').innerText()).includes('not in chronological order'));
 await act('reorder','invoices:1:1');assert.deepEqual(await p.locator('.cost-tag h3').allTextContents(),['March 12','March 16','March 21']);await shot('cost');await act('solve','cost');
 const state=await saved();assert(state.solvedPuzzles.includes('cost'));assert(!state.inspectedObjects.includes('invoices'),'No visit to hidden cost display required');
 await p.reload();await act('continue');await act('search','bin');await act('move','bin-lid');await act('open','stock');assert((await p.locator('.stock-label').innerText()).includes('$18 per measure'));assert(await p.locator('.stock-label').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=16));await shot('stock');await leave();
 await act('open','orders');assert(!(await p.locator('[data-action="job"][data-id="A"]').isDisabled()));assert.equal(await p.locator('.press-control-art img').count(),1);await p.locator('.press-lever').scrollIntoViewIfNeeded();await shot('press');await act('job','A');await act('job','C');await act('solve','orders');assert((await saved()).solvedPuzzles.includes('orders'));
 assert.deepEqual(errors,[]);await p.close();
}console.log(JSON.stringify({passed:true,widths:[1440,390],checks:['individual drawer previews and collection','partial reload','direct machine targets','readable stock','worker reduction','strict dates','badge required','no hidden visit gate','press unlock and solve']}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
