const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('C:/Users/Jennings/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const url='http://127.0.0.1:4179/games/the-shock-house/';fs.mkdirSync('tmp/shock-house/finish',{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){
 const p=await browser.newPage({viewport:{width,height:1000},reducedMotion:'no-preference'}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 const act=async(a,id)=>{await p.locator(`button[data-action="${a}"]${id?'[data-id="'+id+'"]':''}:not([inert] *):visible`).first().click();if(['search','open'].includes(a))await p.locator('.inspection-object.type-'+(a==='search'?'search-':'')+id).waitFor();};
 const saved=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('mastery-quests.shock-house.v1')));
 const leave=async()=>{while(await p.locator('[data-action="back"]').count())await act('back');};
 const camera=async room=>{await leave();for(let i=0;i<5&&(await saved()).currentRoom!==room;i++){await act('pan','right');await p.locator('.departing-scene').waitFor({state:'detached'});}};
 const shot=async name=>{await p.locator('.dial-needle').evaluateAll(xs=>Promise.all(xs.flatMap(e=>e.getAnimations()).map(a=>a.finished.catch(()=>{}))));await p.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode().catch(()=>{}))));await p.screenshot({path:`tmp/shock-house/finish/${name}-${width}.png`});};
 await p.goto(url);await p.evaluate(async()=>{const e=await import('./engine.js');const s=e.newState();s.householdPattern=[1,1,-1];s.inspectedObjects=['pay','food','bills','stock','output-read','work-read','prices-read'];e.complete(s,'budget');for(const id of ['badge','date','household']){e.inspect(s,'drawer:'+id);e.collectDrawerItem(s,id);}e.inspect(s,'badge-used');s.invoices=['early','middle','late'];e.complete(s,'cost');s.jobs=['A','C'];e.complete(s,'orders');s.currentRoom='archive';localStorage.setItem('mastery-quests.shock-house.v1',JSON.stringify(s));});
 await p.reload();await act('continue');await act('search','receiver');await act('search','service');assert((await saved()).inspectedObjects.includes('index'));assert.equal(await p.locator('[data-action="open"][data-id="index"]').count(),0,'No duplicate instruction click');assert(await p.locator('.radio-service-card').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=17));await shot('service');
 await leave();await act('search','television');for(let i=0;i<3;i++){await act('tv-channel','next');assert(await p.locator('.news-story strong').isVisible());await shot('news-'+i);}await leave();
 await act('search','records');await act('search','register');await act('open','indicators');for(const id of ['household','costs','staffing'])await act('connect',id);
 // Changing a dial must not recreate, move, or animate the connected documents.
 await p.locator('.record-socket').first().evaluate(e=>{window.fixedSocket=e;window.fixedBox=e.getBoundingClientRect().toJSON();});
 const dial=p.locator('[data-action="gauge"][data-id="indicators:0"]');await dial.click();await dial.click();await act('gauge','indicators:1');await act('gauge','indicators:2');
 assert(await p.locator('.record-socket').first().evaluate(e=>e===window.fixedSocket));assert.equal(await p.locator('.record-socket .artifact-thumb').first().evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await p.locator('.calibrated-gauge').count(),3);await shot('register');await act('solve','indicators');
 await camera('workshop');await act('search','tray');await act('move','catalogue');await act('search','files');assert((await saved()).inspectedObjects.includes('shipping-date'));await shot('shipping');await leave();await act('search','schedule');await leave();await act('open','orders');await shot('production');
 await camera('archive');await act('search','receiver');await act('open','radio');assert.equal(await p.locator('.illustrated-radio').count(),1);await p.locator('[data-knob]').press('Home');for(let i=0;i<3;i++)await p.locator('[data-knob]').press('ArrowRight');assert.equal((await saved()).frequency,270);await shot('radio');
 for(const date of ['March 14','March 16','March 21']){await p.selectOption('#date',date);await act('tune');await act('record-dispatch');}await act('solve','radio');assert((await saved()).solvedPuzzles.includes('radio'));
 await camera('policy');await act('search','utility');await act('open','policy');const range=p.locator('[data-input="policy"]');await range.press('Home');assert.equal(await p.locator('#inflation-reading').innerText(),'4 / 10');await range.press('End');await shot('policy');await act('seal','prices');await act('seal','work');await act('solve','policy');
 await camera('hall');await act('open','exit');for(const id of ['broadcast','costs','staffing','indicators','tradeoff'])await act('place-final',id);await shot('exit');await act('solve','exit');assert.equal(await p.locator('.illustrated-exit').count(),0);assert.equal(await p.locator('img[data-asset="panorama_exit_open"]').count(),1);await shot('open-door');assert.deepEqual(errors,[]);await p.close();
}console.log(JSON.stringify({passed:true,widths:[1440,390],checks:['single readable radio clue','news channels','stable documents with motion enabled','calibrated gauges','shipping auto-record','radio knobs and dates','policy needles','illustrated exit']}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
