const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('C:/Users/Jennings/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const url='http://127.0.0.1:4179/games/the-shock-house/',key='mastery-quests.shock-house.v1';
fs.mkdirSync('tmp/shock-house/materials',{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const act=async(action,id)=>{await page.locator(`button[data-action="${action}"]${id?'[data-id="'+id+'"]':''}:visible:not([inert] *)`).first().click();if(['search','open'].includes(action))await page.locator('.inspection-object.type-'+(action==='search'?'search-':'')+id).waitFor();};
 const leave=async()=>{while(await page.locator('[data-action="back"]').count())await act('back');};
 const shot=async name=>{await page.locator('img').evaluateAll(xs=>Promise.all(xs.map(i=>i.decode().catch(()=>{}))));await page.screenshot({path:`tmp/shock-house/materials/${name}-${width}.png`,fullPage:true});};
 await page.goto(url);await page.evaluate(async key=>{const e=await import('./engine.js'),s=e.newState();s.householdPattern=[1,1,-1];s.inspectedObjects=['pay','food','bills'];e.complete(s,'budget');for(const id of ['badge','date','household']){e.inspect(s,'drawer:'+id);e.collectDrawerItem(s,id);}e.inspect(s,'badge-used');s.invoices=['early','middle','late'];e.complete(s,'cost');s.currentRoom='workshop';localStorage.setItem(key,JSON.stringify(s));},key);await page.reload();await act('continue');
 await act('search','bin');await act('move','bin-lid');assert.equal(await page.locator('.bin-materials .material-token').count(),6);await shot('bin');await act('open','stock');assert.equal(await page.locator('.stock-blanks .material-token').count(),6);assert.match(await page.locator('.stock-label').innerText(),/raw steel/);await shot('stock');
 const paperFits=async selector=>assert(await page.locator(selector).evaluate(e=>{const b=e.getBoundingClientRect();return [...e.querySelectorAll('h3,header,dt,dd,p,footer,.worker-card')].every(x=>{const r=x.getBoundingClientRect();return r.left>=b.left+b.width*.07&&r.right<=b.right-b.width*.07&&r.top>=b.top&&r.bottom<=b.bottom;});}),'Content lies inside the paper safe area');await paperFits('.stock-label');
 await leave();await act('search','schedule');await paperFits('.staffing-comparison');await shot('staffing');await leave();await act('open','orders');assert.equal(await page.locator('.material-store .material-token').count(),6);await shot('orders');await act('job','A');await act('job','C');assert.equal(await page.locator('.material-store .material-token').count(),2);assert.equal(await page.locator('.allocation-sockets .material-token').count(),4);await shot('allocated');await leave();await act('search','bin');assert.equal(await page.locator('.bin-materials .material-token').count(),2);await act('open','stock');assert.equal(await page.locator('.stock-blanks .material-token').count(),2);await page.reload();await act('continue');await leave();await act('open','orders');assert.equal(await page.locator('.material-store .material-token').count(),2);await act('job','A');assert.equal(await page.locator('.material-store .material-token').count(),4);await act('job','A');await act('solve','orders');assert.match(await page.locator('.production-result').innerText(),/2 of 6 steel blanks/);
 await leave();await act('search','bin');await act('open','stock');assert.equal(await page.locator('.stock-blanks .material-token').count(),2);await shot('returned');assert.equal(await page.locator('.sprite-spools').count(),0);assert.deepEqual(errors,[]);await page.close();
}console.log(JSON.stringify({passed:true,widths:[1440,390],checks:['paper safe areas','six individual steel blanks','allocation and return counts','unchanged successful production plan']}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
