import assert from 'node:assert/strict';
import {newRecovery,recoveryAction as act,validRecovery,RECOVERY_CHAIN} from '../../game/games/the-shock-house/recovery-state.js';
import {newState,restore} from '../../game/games/the-shock-house/engine.js';
const r=newRecovery();assert(validRecovery(r));
act(r,'finish');assert(!r.complete);act(r,'photo-open');assert(!r.flags.includes('photo-open'));
act(r,'date','14 MAR');act(r,'trial');assert(!r.flags.includes('trial'));
for(const a of ['left-pocket','coin','right-pocket','ticket','ticket-back','photo-back','photo-open','book-open','trial'])act(r,a);
assert(r.flags.includes('trial'));assert(validRecovery(r));
act(r,'ticket-back');assert(!r.ticketFace);assert(r.flags.includes('ticket-back'));
act(r,'costs');assert(!r.flags.includes('costs'));act(r,'cost','15');act(r,'costs');assert(validRecovery(r));
act(r,'national');assert(!r.flags.includes('national'));for(let i=0;i<3;i++)act(r,'channel','next');
act(r,'pattern','0');act(r,'pattern','1');act(r,'pattern','1');act(r,'national');assert(r.flags.includes('national'));
act(r,'place','outcome');act(r,'finish');assert(!r.complete);act(r,'clear');for(const key of RECOVERY_CHAIN)act(r,'place',key);
act(r,'direction','0');act(r,'direction','1');act(r,'direction','2');act(r,'direction','2');act(r,'finish');assert(r.complete);assert(validRecovery(r));
const before=JSON.stringify(r);act(r,'clear');assert.equal(JSON.stringify(r),before,'Completed case cannot be mutated');
for(const patch of [{flags:['trial']},{date:'99 MAY'},{cost:-1},{channel:12},{directions:[1]},{hintLevel:4},{complete:true,chain:[]},{ticketFace:'yes'}])assert(!validRecovery({...r,...patch}));
const old=newState();delete old.recovery;assert.equal(restore(old).recovery,null,'Version-1 saves migrate');
assert.equal(restore({...newState(),recovery:newRecovery()}),null,'Second case cannot unlock before first exit');
console.log(JSON.stringify({passed:true,checks:['dependency gates','wrong answers','all evidence used','ticket flip','solved states','malformed recovery rejected','old-save migration','first-case prerequisite']}));
