const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Jennings/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const width=Number(process.env.SHOCK_HOUSE_WIDTH)||1440,url=process.env.SHOCK_HOUSE_URL||'http://127.0.0.1:4179/games/the-shock-house/';
const out=`tmp/shock-house/recovery-${width}`;fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width,height:960},reducedMotion:'reduce'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const act=(action,id)=>page.locator(`button[data-action="${action}"]${id===undefined?'':`[data-id="${id}"]`}:not([inert] *):visible`).first().click();
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('mastery-quests.shock-house.v1')));
 const leave=async()=>{while(await page.locator('[data-action="back"]').count())await act('back');};
 const camera=async room=>{await leave();for(let i=0;i<5&&(await saved()).currentRoom!==room;i++)await act('pan','right');assert.equal((await saved()).currentRoom,room);};
 const shot=async name=>{await page.locator('.mini-scene .asset-plate').evaluateAll(imgs=>Promise.all(imgs.map(img=>img.decode())));await page.screenshot({path:`${out}/${name}.png`});};
 await page.goto(url);await act('begin');assert.equal(await page.locator('[data-action="recovery-start"],[data-id="coat"],[data-id="frame"]').count(),0);
 await camera('residence');await act('search','ledger');assert.equal(await page.locator('[data-id="gardening"]').count(),0);
 // Completed legacy case unlocks the next mission without replay or imported object flags.
 await page.evaluate(async()=>{const {newState,complete,FINAL_ORDER}=await import('./engine.js');const s=newState();s.inspectedObjects=['pay','food','bills','notebook','invoices','production','stock','national','badge-used','collected:tram','moved:gardening'];s.budget={march:[3000,1400,600,200],april:[3200,1500,800,500]};complete(s,'budget');s.invoices=['early','middle','late'];complete(s,'cost');s.jobs=['A','C'];complete(s,'orders');s.connected=['household','costs','staffing'];s.indicators=[-1,1,1];complete(s,'indicators');s.broadcastSequence=['March 14','March 16','March 21'];complete(s,'radio');s.policyTried=['tight','loose'];s.seals=['prices','work'];complete(s,'policy');s.finalSequence=[...FINAL_ORDER];complete(s,'exit');s.visitedRooms=['hall','residence','workshop','archive','policy'];s.inventory=[];s.stage='reveal';delete s.recovery;localStorage.setItem('mastery-quests.shock-house.v1',JSON.stringify(s));});
 await page.reload();await act('continue');await act('recovery-start');assert.deepEqual((await saved()).recovery.flags,[]);await act('back');
 await act('search','frame');await act('r-photo-back');await act('r-photo-open');assert(!(await saved()).recovery.flags.includes('photo-open'));await leave();
 await act('search','coat');await act('r-left-pocket');await act('r-coin');await act('r-right-pocket');await act('r-ticket');await act('r-ticket-back');assert((await page.locator('.ticket-ink').innerText()).includes('14 MAR'));await shot('ticket');await leave();
 await act('search','frame');await act('r-photo-open');await shot('photograph');await page.reload();await act('continue');assert((await saved()).recovery.flags.includes('photo-open'));
 await camera('residence');await act('search','ledger');await act('search','gardening');await act('r-book-open');await act('r-trial');assert(!(await saved()).recovery.flags.includes('trial'));await act('r-date','14 MAR');await act('r-trial');assert((await saved()).recovery.flags.includes('trial'));await shot('trial');
 await camera('workshop');await act('search','machine');await act('r-costs');assert(!(await saved()).recovery.flags.includes('costs'));await act('r-cost','15');await act('r-costs');await shot('costs');
 await camera('archive');await act('search','television');for(let i=0;i<3;i++)await act('r-channel','next');await shot('bulletin');await act('search','comparison');await act('r-national');assert(!(await saved()).recovery.flags.includes('national'));await act('r-pattern','0');await act('r-pattern','1');await act('r-pattern','1');await act('r-national');await shot('comparison');
 await camera('hall');await act('open','exit');for(const key of ['outcome','costs','technology','supply'])await act('r-place',key);for(const i of ['0','1','2','2'])await act('r-direction',i);await act('r-finish');assert.equal((await saved()).stage,'recovery');await act('r-clear');for(const key of ['technology','costs'])await act('r-place',key);
 await page.reload();await act('continue');await act('open','exit');assert.deepEqual((await saved()).recovery.chain,['technology','costs']);for(const key of ['supply','outcome'])await act('r-place',key);await shot('final');await act('r-finish');assert.equal((await saved()).stage,'recovery-results');assert(await page.getByRole('heading',{name:'You reconstructed a positive aggregate supply shock.'}).isVisible());await shot('results');
 await page.reload();await act('continue');assert.equal((await saved()).stage,'recovery-results');await act('reveal');assert(await page.getByRole('heading',{name:'You reconstructed a negative aggregate supply shock.'}).isVisible());assert.equal((await saved()).solvedPuzzles.length,7);await act('recovery-start');assert.equal((await saved()).stage,'recovery-results');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,width,checks:['first-case cleanup','legacy unlock','coin opens photograph','ticket date opens journal','cost calculation','national evidence','causal sequence','wrong attempts','partial reload','completed reload','first-case preserved']}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
