const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Jennings/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const config=JSON.parse(fs.readFileSync('audit_tools/econ_rpg/signal-house-release.json','utf8'));
const origin=process.env.SIGNAL_HOUSE_ORIGIN||'http://127.0.0.1:4180',url=origin+config.previewRoute,key='mastery-quests.shock-house.v1';
const out='tmp/signal-house-release/'+(origin.startsWith('https:')?'live':'local');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const results=[];
 for(const [width,height] of [[1440,1000],[390,844],[844,390],[768,1024]]){
 const p=await browser.newPage({viewport:{width,height},hasTouch:true,reducedMotion:'reduce'}),errors=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 const act=async(a,id)=>{await p.locator(`button[data-action="${a}"]${id?'[data-id="'+id+'"]':''}:visible:not([inert] *)`).first().click();if(['open','search'].includes(a))await p.locator('.inspection-object.type-'+(a==='search'?'search-':'')+id).waitFor();};
 const saved=()=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
 const betaHub=origin+new URL(config.returnToGames).pathname;
 if(!origin.startsWith('https:'))await p.route(config.returnToGames,route=>route.fulfill({status:302,headers:{location:betaHub}}));
 const response=await p.goto(url);assert.equal(response.status(),200);assert.equal(await p.title(),'Signal House · Mastery Quests');assert.equal(await p.locator('meta[name=robots]').getAttribute('content'),'noindex,nofollow');if(origin.startsWith('https:'))assert.match(response.headers()['x-robots-tag'],/noindex/);
 assert.equal(await p.locator('h1').innerText(),'SIGNAL HOUSE');assert.equal(await p.locator('.subtitle').innerText(),'An Economic Escape');assert.match(await p.locator('.mission-title').innerText(),/THE BROKEN SIGNAL/);assert(!(await p.locator('body').innerText()).includes('Shock House'));
 await p.locator('img').evaluateAll(xs=>Promise.all(xs.map(i=>i.decode())));await p.screenshot({path:`${out}/title-${width}x${height}.png`,fullPage:true});assert(await p.locator('[data-return-games]').evaluate(e=>e.getBoundingClientRect().height>=44));
 await act('begin');assert.equal((await saved()).currentRoom,'hall');assert.equal(await p.locator('[data-return-games]:visible').count(),0);
 // Dispatch a real touch gesture through Chromium's input pipeline.
 const scene=await p.locator('.scene').first().boundingBox(),session=await p.context().newCDPSession(p);const y=Math.max(110,Math.min(height-120,scene.y+scene.height*.65)),x=Math.min(width-60,scene.x+scene.width*.75);
 await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(const dx of [30,60,100,150])await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-dx,y}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).currentRoom==='residence',key);
 // The game deliberately suppresses synthetic clicks for 400 ms after a swipe.
 await p.waitForTimeout(450);
 const controls=await p.locator('.room-tools button,.pocket-access,.pan-controls button').evaluateAll(xs=>xs.map(e=>({label:e.textContent,b:e.getBoundingClientRect().toJSON()})).filter(x=>x.b.width&&x.b.height));for(let i=0;i<controls.length;i++)for(let j=i+1;j<controls.length;j++){const a=controls[i].b,b=controls[j].b;assert(!(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top),'Controls overlap: '+controls[i].label+'/'+controls[j].label);}
 await act('search','desk');await act('open','pay');assert((await saved()).inspectedObjects.includes('pay'));await p.screenshot({path:`${out}/pay-${width}x${height}.png`});while(await p.locator('[data-action=back]').count())await act('back');await act('satchel');await act('satchel');await act('hint');await act('menu');assert(await p.locator('dialog [data-return-games]').evaluate(e=>e.getBoundingClientRect().height>=44));await p.screenshot({path:`${out}/menu-${width}x${height}.png`});assert.equal(await p.locator('dialog [data-return-games]').getAttribute('href'),config.returnToGames);await p.locator('dialog [data-return-games]').click();await p.waitForURL(betaHub);assert.equal(await p.locator('[data-game=signal-house]').count(),1);assert.equal(await p.locator('[data-game=signal-house] a').getAttribute('href'),'./signal-house/?experience=illustrated');assert((await saved()).inspectedObjects.includes('pay'));await p.screenshot({path:`${out}/public-games-${width}x${height}.png`,fullPage:true});
 await p.goto(url);await act('continue');assert.equal((await saved()).currentRoom,'residence');assert((await saved()).inspectedObjects.includes('pay'));
 // This deliberately uses the historical key and original version shape.
 await p.evaluate(async({key,route})=>{const {newState,complete,inspect,collectDrawerItem,FINAL_ORDER}=await import(route+'engine.js');const s=newState();s.inspectedObjects=['pay','food','bills','notebook','invoices','production','stock','output-read','work-read','prices-read','badge-used','collected:tram','moved:gardening'];s.householdPattern=[1,1,-1];s.inspectedObjects.push('index','shipping-date','search:schedule');s.budget={march:[3000,1400,600,200],april:[3200,1500,800,500]};complete(s,'budget');for(const item of ['badge','date','household']){inspect(s,'drawer:'+item);collectDrawerItem(s,item);}s.invoices=['early','middle','late'];complete(s,'cost');s.jobs=['A','C'];complete(s,'orders');s.connected=['household','costs','staffing'];s.indicators=[-1,1,1];complete(s,'indicators');s.broadcastSequence=['March 14','March 16','March 21'];complete(s,'radio');s.policyTried=['tight','loose'];s.seals=['prices','work'];complete(s,'policy');s.finalSequence=[...FINAL_ORDER];complete(s,'exit');s.visitedRooms=['hall','residence','workshop','archive','policy'];s.inventory=[];s.stage='reveal';delete s.recovery;delete s.branchRevision;localStorage.setItem(key,JSON.stringify(s));},{key,route:config.previewRoute});await p.reload();await act('continue');assert.match(await p.locator('.debrief').innerText(),/THE BROKEN SIGNAL/);assert.match(await p.locator('.debrief').innerText(),/negative aggregate supply shock/);assert.match(await p.locator('.recovery-unlock').innerText(),/THE SECOND HARVEST/);await act('recovery-start');assert.equal((await saved()).stage,'recovery');await p.reload();await act('continue');assert.equal((await saved()).stage,'recovery');assert.deepEqual(errors,[]);results.push({width,height,newSave:true,legacySave:true,mission2:true,touchSwipe:true,returnToGames:true,noOverlap:true});await p.close();
 }
 // Every shipped local asset resolves, including Mission 2 and fallback artwork.
 const assets=[];const base=path.join('dist',config.previewRoute);function scan(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);e.isDirectory()?scan(f):assets.push(path.relative(base,f).replaceAll('\\','/'));}}scan(base);
 const request=await browser.newContext();for(let i=0;i<assets.length;i+=8)await Promise.all(assets.slice(i,i+8).map(async file=>{const r=await request.request.get(url+file);assert.equal(r.status(),200,file);}));await request.close();
 fs.writeFileSync(out+'/results.json',JSON.stringify({url,results,assets:assets.length},null,2));console.log(JSON.stringify({passed:true,url,results,assets:assets.length}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
