import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
import {api,query,state,save,name,out} from './control.mjs';
import {generateCapability,hashCapability} from '../../../server/anonymous-telemetry-poc/capabilities.mjs';
import {PHASE} from '../../../server/anonymous-telemetry-poc/telemetry-core.mjs';
const log=fs.readFileSync(path.join(out,'deploy.log'),'utf8');const base=log.match(/https:\/\/masteryquests-telemetry-redaction-staging\.[a-z0-9-]+\.workers\.dev/)?.[0],version=log.match(/Current Version ID: ([a-f0-9-]+)/)?.[1];if(!base||!version)throw Error('Staging deployment identity missing');save({...state(),url:base,version,workerDeployed:true});
const origin='https://masteryquests.org',url=base+'/v1/events',raw=generateCapability(),unknown=generateCapability(),hash=await hashCapability(raw),capId=crypto.randomUUID(),raws=[raw,unknown],hashes=[hash],secrets=[...raws,...hashes];
const scope={gameId:'faculty-composer',buildId:'composer-'+createHash('sha256').update(crypto.randomUUID()).digest('hex'),buildVersion:createHash('sha256').update(crypto.randomUUID()).digest('hex'),schemaVersion:3};
const clean=s=>secrets.reduce((text,value)=>text.replaceAll(value,'[REMOVED]'),String(s));
const tables=['telemetry_events','telemetry_runs','telemetry_ingest_batches','telemetry_rate_limits','telemetry_build_policies','telemetry_build_capabilities','telemetry_scope_windows'];
async function snapshot(){const rows=await query(tables.map(t=>'SELECT * FROM '+t+' ORDER BY rowid').join(';'));return{digest:createHash('sha256').update(JSON.stringify(rows.map(x=>x.results))).digest('hex'),counts:Object.fromEntries(tables.map((t,i)=>[t,rows[i].results.length]))};}
const beforeSeed=await snapshot();await query('INSERT INTO telemetry_build_policies(game_id,build_id,created_at) VALUES(?,?,unixepoch())',[scope.gameId,scope.buildId]);await query('INSERT INTO telemetry_build_capabilities(capability_id,capability_hash,game_id,build_id,build_version,schema_version,issued_at,expires_at,issuance_request_id,activation_digest) VALUES(?,?,?,?,?,3,unixepoch(),unixepoch()+3600,?,?)',[capId,hash,scope.gameId,scope.buildId,scope.buildVersion,crypto.randomUUID(),'0'.repeat(64)]);
function event(patch={}){return{...scope,eventId:crypto.randomUUID(),runId:crypto.randomUUID(),anonymousClientId:crypto.randomUUID(),phase:PHASE,mode:'standard',eventType:'run_started',sequenceNumber:1,eventTimestamp:new Date().toISOString(),synthetic:true,contractID:'mq-measurement/1',manifestID:null,provenanceStatus:'unresolved',...patch};}
const body=e=>JSON.stringify({phase:PHASE,events:[e]});
const results=[],functional=[],negative=[],sanity=[],cors=[];
const tailProof={events:0,rawTokenMatches:0,rawHashMatches:0,partialTokenMatches:0,consoleRawMatches:0,exceptionRawMatches:0,adminTokenMatches:0,maintenanceTokenMatches:0,providerFieldPath:'event.request.headers.x-mq-ingest-token',headerStates:{},markers:[],newHeaderObservations:0};
let browser,socket,tailId,persisted={status:'NOT_INSPECTED'},failure;
function forbidden(text){return secrets.some(x=>text.includes(x));}
function write(file,value){const text=JSON.stringify(value,null,2)+'\n';assert(!forbidden(text));assert(!text.includes('mqic1_'));fs.writeFileSync(path.join(out,file),text);const disk=fs.readFileSync(path.join(out,file),'utf8');assert(!forbidden(disk));}
async function call(e,options={}){const headers={origin,'content-type':'application/json',...(options.token===null?{}:{'x-mq-ingest-token':options.token??raw}),...options.headers};const response=await fetch(url+(options.query||''),{method:'POST',headers,body:options.body??body(e),redirect:'error',signal:AbortSignal.timeout(15000)});const text=await response.text();assert(!forbidden(text));return{status:response.status,headers:Object.fromEntries(response.headers),json:JSON.parse(text)};}
async function valid(label,e=event(),options={}){const r=await call(e,options);assert.equal(r.status,202);assert.equal(r.json.accepted,1);const row=(await query('SELECT e.event_id,e.game_id,e.build_id,e.build_version,e.schema_version,r.event_count,b.capability_id FROM telemetry_events e JOIN telemetry_runs r ON r.run_id=e.run_id JOIN telemetry_ingest_batches b ON b.batch_id=? WHERE e.event_id=?',[r.json.batchId,e.eventId]))[0].results[0];assert(row);for(const [col,value]of Object.entries({game_id:scope.gameId,build_id:scope.buildId,build_version:scope.buildVersion,schema_version:3,event_count:1,capability_id:capId}))assert.equal(row[col],value);functional.push({label,status:202,accepted:1,tupleAndRowsVerified:true,receiptAttributed:true});return e;}
async function denied(label,e=event(),options={}){const before=await snapshot(),r=await call(e,options),after=await snapshot();assert(r.status>=400);assert.equal(before.digest,after.digest);negative.push({label,status:r.status,error:r.json.error,noWrites:true,before,after});}
async function acceptedSnapshot(){const values=await query("SELECT * FROM telemetry_events ORDER BY rowid; SELECT * FROM telemetry_runs ORDER BY rowid; SELECT accepted_event_count,accepted_bytes FROM telemetry_build_capabilities ORDER BY rowid; SELECT accepted_event_count,accepted_bytes FROM telemetry_build_policies ORDER BY rowid; SELECT event_count,byte_count FROM telemetry_scope_windows WHERE window_seconds=0 ORDER BY rowid");return JSON.stringify(values.map(x=>x.results));}
try{
 const tail=await api('/workers/scripts/'+name+'/tails','POST',{});tailId=tail.id;save({...state(),tailId});socket=new WebSocket(tail.url,'trace-v1');socket.binaryType='arraybuffer';
 socket.addEventListener('message',message=>{const text=typeof message.data==='string'?message.data:new TextDecoder().decode(message.data);let value;try{value=JSON.parse(text);}catch{return;}tailProof.events++;tailProof.rawTokenMatches+=raws.filter(x=>text.includes(x)).length;tailProof.rawHashMatches+=hashes.filter(x=>text.includes(x)).length;for(const token of raws)for(let i=6;i+16<=token.length;i+=8)if(text.includes(token.slice(i,i+16)))tailProof.partialTokenMatches++;
  const consoleText=JSON.stringify(value.logs||[]),exceptionText=JSON.stringify(value.exceptions||[]);if(forbidden(consoleText))tailProof.consoleRawMatches++;if(forbidden(exceptionText))tailProof.exceptionRawMatches++;
  const headers=value.event?.request?.headers||{};const key=Object.keys(headers).find(k=>k.toLowerCase()==='x-mq-ingest-token');if(key){tailProof.newHeaderObservations++;const v=String(headers[key]);const state=forbidden(v)?'raw-exposure':/redact|mask/i.test(v)?'redacted':'unrecognized-replacement';tailProof.headerStates[state]=(tailProof.headerStates[state]||0)+1;if(state==='redacted'&&v.length<80&&!tailProof.markers.includes(v))tailProof.markers.push(v);}else tailProof.headerStates.omitted=(tailProof.headerStates.omitted||0)+1;
 });
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Tail connection deadline')),15000);socket.addEventListener('open',()=>{clearTimeout(timer);socket.send(JSON.stringify({debug:false}));resolve();},{once:true});});
 const first=await valid('initial');const beforeDuplicate=await acceptedSnapshot(),duplicate=await call(first);assert.equal(duplicate.status,202);assert.equal(duplicate.json.accepted,0);assert(duplicate.json.acknowledgedEventIds.includes(first.eventId));assert.equal(await acceptedSnapshot(),beforeDuplicate);results.push({case:'exact-duplicate',status:'PASS',accepted:0,noEventRunOrAcceptedCounterInflation:true,submittedWorkCountersMayCharge:true});
 await denied('missing token',event(),{token:null});await denied('malformed token',event(),{token:'malformed'});await denied('random token',event(),{token:unknown});
 const original=(await query('SELECT issued_at,expires_at FROM telemetry_build_capabilities WHERE capability_id=?',[capId]))[0].results[0];
 await query('UPDATE telemetry_build_capabilities SET issued_at=unixepoch()-2,expires_at=unixepoch()-1 WHERE capability_id=?',[capId]);await denied('expired token');await query('UPDATE telemetry_build_capabilities SET issued_at=?,expires_at=? WHERE capability_id=?',[original.issued_at,original.expires_at,capId]);
 await query('UPDATE telemetry_build_capabilities SET revoked_at=issued_at WHERE capability_id=?',[capId]);await denied('revoked token');await query('UPDATE telemetry_build_capabilities SET revoked_at=NULL WHERE capability_id=?',[capId]);
 await query('UPDATE telemetry_build_policies SET blocked_at=created_at');await denied('blocked build');await query('UPDATE telemetry_build_policies SET blocked_at=NULL');
 for(const [label,patch]of [['wrong build',{buildId:'composer-'+'c'.repeat(64)}],['wrong game',{gameId:'other'}],['wrong version',{buildVersion:'c'.repeat(64)}],['wrong schema',{schemaVersion:2}]])await denied(label,event(patch));
 // Keep live issued credentials in the canonical header. Rejected carriers use nonsecret markers;
 // local header tests additionally use real fixture credentials in retired/alternate carriers.
 await denied('old header only',event(),{token:null,headers:{'x-mq-ingest-capability':'retired-transport-marker'}});
 await denied('both old and new',event(),{headers:{'x-mq-ingest-capability':'retired-transport-marker'}});
 await denied('Authorization instead',event(),{token:null,headers:{authorization:'Bearer rejected-transport-marker'}});
 await denied('query instead',event(),{token:null,query:'?token=rejected-transport-marker'});
 await denied('JSON instead',event(),{token:null,body:JSON.stringify({events:[event()],token:'rejected-transport-marker'})});
 await denied('cookie instead',event(),{token:null,headers:{cookie:'token=rejected-transport-marker'}});
 await denied('operator capabilityId instead',event(),{token:capId});
 for(const requested of ['x-mq-ingest-token','x-mq-ingest-capability','x-mq-ingest-token,x-mq-ingest-capability']){const r=await fetch(url,{method:'OPTIONS',headers:{origin,'access-control-request-method':'POST','access-control-request-headers':requested},redirect:'error'});assert.equal(r.status,requested==='x-mq-ingest-token'?204:403);assert.equal(r.headers.get('access-control-allow-headers'),'content-type,x-telemetry-phase,x-mq-ingest-token');assert(!r.headers.has('access-control-allow-credentials'));cors.push({requested,status:r.status,allowed:r.headers.get('access-control-allow-headers')});}
 const exact=event(),text=body(exact);await valid('exact 131072 bytes',exact,{body:text+' '.repeat(131072-Buffer.byteLength(text))});
 for(const multibyte of [false,true]){const e=event({artifact:multibyte?'é':'x'}),text=body(e),before=await snapshot(),r=await call(e,{body:text+' '.repeat(131073-Buffer.byteLength(text))}),after=await snapshot();assert.equal(r.status,413);assert.equal(r.json.error,'request_too_large');assert.equal(r.headers['access-control-allow-origin'],origin);assert.equal(r.headers.vary,'Origin');assert.equal(r.headers['cache-control'],'no-store');assert.equal(before.digest,after.digest);sanity.push({case:multibyte?'multibyte oversized':'oversized',status:413,readable:true,noWrites:true});}
 const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE);browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.fulfill({contentType:'text/html',body:'<!doctype html><title>Redaction staging</title>'}):new URL(route.request().url()).origin===base?route.continue():route.abort());const page=await context.newPage();await page.goto(origin+'/fixture');const before=await snapshot();const browserResult=await page.evaluate(async({url,token})=>{const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-mq-ingest-token':token},body:'x'.repeat(131073)});return{status:response.status,json:await response.json(),cacheControl:response.headers.get('cache-control')};},{url,token:raw});assert.equal(browserResult.status,413);assert.equal(browserResult.json.error,'request_too_large');assert.equal(browserResult.cacheControl,'no-store');assert.equal((await snapshot()).digest,before.digest);sanity.push({case:'Edge oversized',status:413,readable:true,noWrites:true,browser:browser.version()});
 for(let i=0;i<3;i++)await valid('final health '+i);const telemetry=await query('SELECT * FROM telemetry_events;SELECT * FROM telemetry_runs;SELECT * FROM telemetry_ingest_batches');assert(!forbidden(JSON.stringify(telemetry)));results.push({case:'telemetry-secret-scan',status:'PASS'});
 for(let i=0;i<20&&tailProof.events<negative.length+functional.length+4;i++)await new Promise(r=>setTimeout(r,500));assert(tailProof.events>0);assert(tailProof.newHeaderObservations>0);
 try{const data=await api('/workers/observability/telemetry/query','POST',{queryId:crypto.randomUUID(),timeframe:{from:Date.parse(state().createdAt),to:Date.now()},view:'events',limit:1000,parameters:{filterCombination:'and',filters:[{key:'$workers.scriptName',operation:'eq',type:'string',value:name}]}});const text=JSON.stringify(data);persisted={status:'QUERIED',rawTokenMatches:raws.filter(x=>text.includes(x)).length,rawHashMatches:hashes.filter(x=>text.includes(x)).length,resultKeys:Object.keys(data),rawDataPersisted:false};let eventCount=0;function count(value){if(value&&typeof value==='object'){if(value.$workers?.scriptName){assert.equal(value.$workers.scriptName,name);eventCount++;}for(const v of Object.values(value))count(v);}}count(data);persisted.eventsInspected=eventCount;if(!eventCount)persisted.status='INCONCLUSIVE_NO_EVENTS';}catch(e){persisted={status:'UNAVAILABLE',limitation:clean(e.message)};}
 write('staging-results.json',{canonicalHeader:'X-MQ-Ingest-Token',beforeSeed,after:await snapshot(),functional,negative,results,cors,sanity,tail:tailProof,applicationLogs:{rawMatches:tailProof.consoleRawMatches,exceptionMatches:tailProof.exceptionRawMatches},persistedLogs:persisted,productionSecretsPresent:false,noncanonicalCarriers:'Nonsecret markers in staging; local tests use real fixture credentials',providerInputUnmodified:true});
 // Inspect all already-written artifacts while the exact ephemeral values still exist in memory.
 let scanned=0;function scan(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())scan(file);else{const text=fs.readFileSync(file).toString();assert(!forbidden(text));assert(!/mqic1_[A-Za-z0-9_-]{43}/.test(text));scanned++;}}}scan(out);write('in-memory-evidence-scan.json',{scannedFiles:scanned,exactRawMatches:0,exactHashMatches:0,rawCapabilityPatternMatches:0});
 console.log(JSON.stringify({functional: functional.length,negative:negative.length,tail:tailProof,persistedLogs:persisted}));
}catch(e){failure=clean(e.message);write('staging-failure.json',{failure,tail:tailProof,functional,negative,sanity,persistedLogs:persisted});console.error(failure);}
finally{if(browser)await browser.close();if(socket)socket.close();if(tailId){await api(`/workers/scripts/${name}/tails/${tailId}`,'DELETE');save({...state(),tailClosed:true});}}
process.exit(failure||tailProof.rawTokenMatches||tailProof.rawHashMatches||tailProof.partialTokenMatches||tailProof.consoleRawMatches?1:0);
