from pathlib import Path
import json,re
HERE=Path(__file__).parent
read=lambda n:json.loads((HERE/n).read_text(encoding='utf-8'))
families=read('families.json'); originals=read('originals.json'); drafts=read('drafts.json')
def stem(n,text):
    for q in families[n]:drafts[str(q['id'])]['q']=text(q) if callable(text) else text
def sub(n,old,new,field='q'):
    for q in families[n]:
        d=drafts[str(q['id'])]
        if field=='options':d[field]=[v.replace(old,new) for v in d[field]]
        else:
            assert old in d[field],(n,field,old)
            d[field]=d[field].replace(old,new)
def opts(n,values):
    assert len(families[n])==1
    drafts[str(families[n][0]['id'])]['options']=values
def feedback(n,text):
    for q in families[n]:drafts[str(q['id'])]['feedback']=text(q) if callable(text) else text

stem(0,'Refer to the AD-AS graph with points A, B, C, and D. The economy begins at A. A supply disruption shifts AS0 to AS1 and moves the economy to D. The disruption persists, so AS1 stays fixed. Compare two fiscal-policy goals: restoring the original output and restoring the original price level. What would each goal require? Use the straight AS1 line, extending it if needed.')
sub(1,'a $','a $')
sub(1,'A purchases increase of','An increase in government purchases of')
sub(1,'can arrive immediately, or the same program can arrive','can take effect immediately, or the same program can take effect')
sub(1,'Which assessment combines diagnosis, size and timing?','Would the program close the recessionary gap if it took effect immediately, and what risk would it create if it took effect after recovery?')
sub(1,'arrival-time demand injection','increase in spending when the program takes effect','feedback')
stem(2,'Nominal GDP rises 5% while the GDP deflator rises 7%. A report calls this a real expansion because total dollar spending increased. What actually happened to real GDP?')
stem(3,'Nominal GDP rises 10% and the GDP deflator rises 10%. Employment rises 2% while hours per worker fall 2%. What happens to real GDP, total hours worked, and output per hour? Use exact percentage changes.')
stem(4,'Use π = πe − (u − 5) + s, where π is actual inflation, πe is expected inflation, u is unemployment, and s is the number of percentage points a temporary supply shock adds to inflation. Rates are in percent. Actual inflation is 6% and unemployment is 5%. One analyst estimates πe = 6 and s = 0; another estimates πe = 4 and s = 2. Expected inflation remains at each analyst\'s estimated rate next year, while the temporary supply shock ends and unemployment stays at its natural rate. What additional information would help determine which inflation forecast is appropriate?')
sub(4,'after supply relief','after the supply shock ends','options')
feedback(4,'At unemployment of 5%, both explanations satisfy 6 = πe + s. After the temporary supply shock ends, inflation equals the unchanged expected inflation rate. Independent evidence about expectations is needed to choose between the forecasts of 6% and 4%.')
stem(5,'An adverse supply shock moves the economy from AD1-AS2 to AD1-AS1 in the graph. The supply curve stays at AS1. Compared with leaving demand at AD1, how would expanding demand to AD2 affect output and the price level relative to their levels before the shock?')
sub(6,'arrives after recovery. At arrival,','takes effect after recovery. At the same time,')
sub(6,'Which policy evaluation recognizes why the original direction need not remain appropriate?','Why might expanding demand no longer be appropriate under these conditions?')
stem(7,'Refer to the first aggregate demand graph. At a price level of 50, which value is closest to the difference in the quantity of real GDP demanded on AD0 and AD1?')
stem(8,'Refer to the second aggregate demand graph. At a price level of 45, which value is closest to the difference in the quantity of real GDP demanded on AD0 and AD1?')
stem(9,'A tariff is imposed while national saving and domestic investment remain unchanged. In the textbook open-economy model, what happens to net exports after the economy adjusts?')
sub(10,'which correction is admissible, and is its location identified?','how could the trade figures be corrected, and can we tell which figure is wrong?')
stem(11,'A bank makes a loan by crediting the borrower\'s checking account. The borrower then pays a supplier at another bank, so reserves are transferred between the banks. How does making the loan change the first bank\'s balance sheet, and how does the later payment change it?')
sub(11,'Origination','Making the loan','options');sub(11,'settlement','the later payment','options');sub(11,'originating bank','bank that made the loan','options')
sub(12,'Which conclusion can be defended without response magnitudes?','Can we conclude that total aggregate demand fell without knowing the sizes of these changes?')
sub(13,'Why need the rounded entries not subtract exactly?','Why might subtracting the displayed revenues from the displayed outlays not give the displayed deficit?')
stem(14,'At the original interest rate, an increase in risk leads domestic residents to plan $140 billion more in purchases of foreign assets and foreigners to plan $60 billion less in purchases of domestic assets. After the interest rate adjusts, net capital outflow has risen by $125 billion. How much must the interest-rate change have reduced that increase, and which changes in asset purchases could explain the reduction?')
sub(14,'Feedback lowers NCO','The interest-rate change lowers NCO by','options');sub(14,'Feedback raises NCO','The interest-rate change raises NCO by','options');sub(14,'relative to the shifted schedule','relative to their plans before the interest rate adjusted','options')
stem(15,'Let e be foreign currency per unit of domestic currency and let the real exchange rate be ε = eP/P*, where P and P* are the domestic and foreign basket prices. The domestic basket price rises from 250 to 270 domestic currency units, the foreign basket price rises from 400 to 408 foreign currency units, and e falls from 1.60 to 1.50. Would keeping the domestic basket price at 250 instead of 270 make the real depreciation larger or smaller?')
sub(15,'falls 1.00 to','falls from 1.00 to','options')
stem(16,'The exchange rate rises from 1.60 to 1.84 foreign currency units per unit of domestic currency. A domestic exporter keeps its domestic-currency price fixed. By what percentages do the domestic currency\'s value and the reciprocal exchange rate change, and how does the exporter\'s price change for foreign buyers?')
sub(17,'tighten underwriting','become more selective about approving loans')
sub(18,'How does the price-volume decomposition bear on that claim?','Considering both the dollar price per unit and the number of units sold, is the analyst\'s claim correct?')
sub(19,'while the statistical basket still spends','while the price index still records spending of')
sub(19,'Which inference respects both the new-goods limitation and the continued use of CPI?','How does the delayed inclusion of the new product limit what the CPI tells us?')
stem(20,'A household grant rises from $2,000 to $2,160 as the CPI rises from 125 to 135. Nominal GDP rises 8% and the GDP deflator rises 4%. A report uses the 8% consumer-price increase to adjust both the grant and GDP for inflation, concluding that both real values are unchanged. Which conclusion is correct, and which is mistaken?')
stem(21,'Aggregate demand would rise by $200 billion before crowding out. If crowding out reduces that increase by $50 billion, how much does aggregate demand rise overall?')
feedback(21,'Subtract the reduction caused by crowding out from the increase before crowding out: $200 − $50 = $150 billion.')
sub(22,'A purchase increase of','An increase in government purchases of');sub(22,'Which inferred MPC and limitation are valid?','What MPC does this imply, and does it determine how much aggregate demand will rise after crowding out?')
sub(22,'the gross effect leaves later crowding out unresolved.','the increase before crowding out does not establish the final increase.','options')
sub(22,'the gross effect establishes an identical realized net effect.','the increase before crowding out establishes the same final increase.','options')
feedback(22,'The spending multiplier is 4 = 1/(1 − MPC), so MPC = 0.75. This gives the demand increase before crowding out. Later crowding out can reduce the final increase.')
stem(23,lambda q:re.sub(r'Two governments each add \$(\d+) to purchases\. A has MPC 0.8 and total AD crowding out \$(\d+); B has MPC 0.5 and no crowding out\. Which comparison follows\?',r'Two governments each increase purchases by $\1. Economy A has an MPC of 0.8, and crowding out reduces its total increase in aggregate demand by $\2. Economy B has an MPC of 0.5 and no crowding out. How do the final increases in aggregate demand compare?',q['q']))
sub(23,'Gross response rankings need not be net response rankings when offsets differ.','A larger increase before crowding out need not mean a larger increase afterward.','feedback')
stem(24,'Refer to the multiplier graph. The direct increase in government purchases shifts AD1 to AD2. Additional spending induced by that increase would move demand to AD3 if there were no crowding out. Crowding out reduces the total increase in aggregate demand by a positive amount. How small must that reduction be for the final demand curve to lie strictly between AD2 and AD3?')
sub(24,'The total offset','The total reduction from crowding out','options')
sub(24,'A positive offset','A positive reduction from crowding out','feedback')
sub(25,'a simple maximum suggests deposits of','the simple model predicts a maximum deposit increase of');sub(25,'actual deposits grow','actual deposits increase by')
sub(25,'Rates fall, but firms also cut expected project returns. Which assessment combines banking and spending constraints?','Interest rates fall, but firms also expect lower returns on their projects. Why might both deposit growth and investment spending be smaller than the simple model predicts?')
stem(26,'Use the foreign-exchange model in which net capital outflow determines a vertical supply curve for domestic currency. The domestic real interest rate rises, while a separate increase in risk makes investors want to send more funds abroad at each interest rate. The final currency-supply curve lies to the right of its original position. With domestic and foreign price levels fixed and demand for domestic currency unchanged, what does this tell us about the two effects on net capital outflow and the exchange rate?')
feedback(26,'A vertical currency-supply curve fixes the quantity supplied for a given level of net capital outflow, not when that level changes. The rightward shift means the increase caused by risk exceeds the decrease caused by the higher interest rate. With currency demand unchanged, the domestic currency depreciates. The final shift alone does not reveal the size of each separate effect.')
sub(26,'The risk shift dominates the rate feedback','The effect of risk exceeds the effect of higher interest rates','options')
stem(27,'Two studies estimate opposite effects of a policy. One uses a credible natural experiment; the other compares groups whose members chose whether to participate. What should matter most when evaluating the conflicting results?')
sub(27,'Differences in causal identification.','How well each study separates the policy\'s effect from other differences between the groups.','options')
stem(28,'A survey classifies people as employed, unemployed, or not in the labor force. Whose difficulty finding enough work is least likely to be captured by the official unemployment rate?')
stem(29,'The prices of consumer baskets in two countries remain different even after they are converted to the same currency. What does this suggest about purchasing-power parity?')
sub(30,'Which additional comparison would resolve the claim while allowing an independent trade-account check?','What additional comparisons would let us check this claim using both saving and investment and the export and import figures?')
stem(31,'An unexpected increase in aggregate demand moves the economy up and to the left along its short-run Phillips curve. Workers and employers then revise expected inflation upward when setting wages. How does that change affect the Phillips curve?')
stem(32,'Use inflation = expected inflation − (unemployment − 5) + s, where s is the number of percentage points a temporary supply shock adds to inflation. Rates are in percent. Unemployment is 6%, actual inflation is 4%, and s is independently measured as +2 percentage points. What can we infer about expected inflation with this measurement, and what could we infer without it?')
sub(32,'offset measurement','measurement of s','options');sub(32,'plus the offset','plus s','options');sub(32,'gap and offset','gap and s','options')
feedback(32,'Substituting the measurements gives 4 = πe − 1 + 2, so expected inflation is 3%. Without a separate measurement of s, the data establish only πe + s = 5. Actual inflation and unemployment cannot by themselves separate expected inflation from the supply shock\'s effect.')
stem(33,'Officials propose changing the policy interest rate and increasing government purchases. Which institution is responsible for each decision?')
sub(34,'Which long-run risk is most consistent with the course logic?','What long-run risk does this political pressure create?')
stem(35,'Before an election, elected officials demand an immediate interest-rate cut while inflation remains above the central bank\'s target. The bank is free to choose its policy tools but must pursue publicly established goals and explain its decisions. How may the bank respond to the demand for a rate cut?')
sub(35,'serves the mandate','serves its assigned goals','options');sub(35,'without regard to its mandate','without regard to its assigned goals','options')
feedback(35,'The bank can choose its policy tools rather than follow an election-driven demand, but it must explain how its decision serves its publicly established goals. This freedom does not give it the power to set taxes or disregard those goals.')
sub(36,'what initial entry and total demand effect follow','how do government purchases and consumption initially change, and what is the total effect on aggregate demand')
stem(37,'Households have an MPC of 0.75. One policy cuts taxes by $60 billion; an alternative raises government purchases by $45 billion. With the same spending multiplier and no crowding out, how do the policies\' effects on aggregate demand and their budget costs compare?')
sub(38,'The immediate consumption channel equals:','How much of the rebate immediately increases consumption?')
sub(39,'Which model-use caution is justified?','How should the smaller initial consumption response affect the use of the spending multiplier?')
sub(39,'The consumption response assumption changed; use the observed or justified initial response before applying induced rounds','Use the consumption response supported by the evidence before calculating the additional spending it induces','options')
feedback(39,'The multiplier calculation depends on how consumption initially responds. If expectations change that response, use the response supported by the evidence. A budget identity does not determine how much households change their spending.')
sub(40,'Use exact gross returns.','Use exact inflation-adjusted returns rather than subtracting inflation from the nominal rate.')
sub(41,'Which pair best evaluates average material output and hourly productivity, to one decimal place?','How do real GDP per person and output per hour change, to one decimal place?')
sub(42,'A stated goal automatically determines the behavioral margin','Announcing a goal automatically determines how agencies respond to the reward','options')
sub(43,'including unintended margins of adjustment','including responses the university did not intend','options')
stem(44,'An office awards contracts to the lowest bidder but later faces frequent requests for costly changes to the work. How could it change its selection rule to address this incentive problem?')
sub(44,'later change orders','later changes to the work','options');sub(44,'Ignore change orders','Ignore later requests for changes','options')
sub(45,'The same reward can change different margins for different consumers','The same reward can change how much one customer travels and which card another uses','options')
stem(46,'A household keeps a fixed $720 cash balance while the price of a representative basket of goods rises from $1.20 to $1.50 during money-financed government spending. How many fewer baskets can the household buy with that unchanged cash balance?')
sub(46,'units.','baskets.','options');sub(46,'No units','No baskets','options')
feedback(46,'The cash initially buys 720/1.20 = 600 baskets and later buys 720/1.50 = 480 baskets. The loss is 120 baskets. An unchanged cash balance need not preserve purchasing power.')
stem(47,'A government finances purchases by creating money. Expected inflation rises, and nominal interest rates rise. Which economic concepts explain how these events are connected?')
stem(48,'At the start of this year, the price index is 100. Inflation falls from 8% last year to 3% this year. A fixed nominal debt remains $103. At the end of this year, what is the debt\'s real value measured at prices from the start of the year?')
stem(49,'A government finances $240 in purchases by creating money. With stable velocity and fixed long-run real output, how does this give the government purchasing power, and who bears the cost?')
stem(50,'Use the foreign-exchange model in which net capital outflow determines a vertical supply curve for domestic currency. A tariff and capital flight occur together. At the original exchange rate, the tariff increases currency demand by 40 units. After interest rates adjust, the final increase in net capital outflow adds 65 units to currency supply. Prices and other factors affecting demand stay fixed. What happens to the exchange rate and net exports, and what more would we need to know to calculate the size of the exchange-rate change?')
stem(51,'A higher price level shifts money demand right while money supply is fixed, so the equilibrium interest rate rises. How does the higher interest rate then affect investment and aggregate demand?')
stem(52,'Compared with free trade, how does the tariff in the graph change consumer surplus, producer surplus, government revenue, and total welfare?')
sub(53,'Which national accounting is correct?','What is the net effect on national welfare after including all of these gains and costs?')
stem(54,'Compared with free trade, how does the quota in the graph change consumer surplus, producer surplus, quota rents, and total welfare? Assume domestic license holders receive the quota rents.')
sub(55,'at $60 million of real consumer and downstream efficiency cost','at a real efficiency cost of $60 million to consumers and firms that use the protected product')
sub(55,'Which comparison informs the employment goal?','How do the two policies compare in cost per worker helped and number of workers helped?')
stem(56,lambda q:re.sub(r'In an adult population of (\d+), employment is (\d+) and active-search unemployment is (\d+)\.',r'Of \1 adults, \2 are employed and \3 are unemployed and actively looking for work.',q['q']).replace('Which correction to a report counting all jobless people as unemployed is needed?','A report counts all jobless people as unemployed. How should the unemployment rate and labor-force participation rate be calculated instead?'))
sub(57,'Which evaluation addresses both margins?','What do these wage and employment changes tell us about workers\' total earnings?')
opts(58,['The firm can retain more workers while offering fewer jobs; an efficiency wage above the market-clearing wage can leave some willing workers without jobs.','Lower turnover proves employment increased; retaining existing workers and hiring new workers measure the same change.','Fewer jobs prove a union imposed the wage; a firm cannot voluntarily choose to pay an efficiency wage.','Lower turnover eliminates job shortages; an efficiency wage necessarily brings labor supply and labor demand into balance.'])
sub(58,'lower hiring is a separate margin in the policy evaluation','the effect on hiring must also be considered','feedback')
# Instructor clarified that weak borrowers means weak demand for loans.
stem(59,'The Fed lowers reserve requirements, but few households or firms want to borrow and banks are cautious about lending. Why might the actual increase in the money supply be smaller than the simple model predicts?')
stem(60,'The money supply expands, but the interest rate rises instead of falling. What change in money demand could explain this result?')
stem(61,'After capital is destroyed, output is 40 units below its old potential level. A commentator expects wage and price adjustments, as after a fall in aggregate demand, to restore output to the old level without rebuilding. Why might that prediction be wrong?')
stem(62,'Actual unemployment is 4% when the natural rate is 5%. Expected inflation is temporarily below actual inflation. If the factors determining the natural rate stay unchanged, what could happen to unemployment as inflation expectations catch up?')
sub(63,"the reform's benchmark change","the reform's effect on the natural rate of unemployment",'options');sub(63,'the natural benchmark','the natural rate of unemployment','options')
sub(64,'What is the best discrete choice?','How many additional batches should the retailer buy?')
sub(65,'End the policy because $30 million is less costly than an $80 million negative continuation margin.','End the policy: ending costs $30 million, while continuing would cost $80 million more than it provides in benefits.','options')
sub(66,'next sprint','next round of development work');sub(66,'sprint cost','development cost','options')
stem(67,'A simple model forecasts regional employment with a 5% error on data that were not used to build it. It recommends policy A across a plausible range of numerical assumptions. A more complex model reduces that error to 4.8%, but small, plausible changes in its assumptions reverse whether it recommends A or B. The policy would be costly and difficult to reverse. What should policymakers do before choosing a policy?')
sub(67,'test sensitive parameters','test the assumptions that change the recommendation','options');sub(67,'robust enough','reliable enough','options');sub(67,'without examining parameters','without examining the assumptions','options');sub(67,'structural uncertainty','uncertainty about how the models represent the economy','options')
feedback(67,'Forecast accuracy and the reliability of a policy recommendation are different concerns. A small improvement in forecast accuracy may not justify a costly, hard-to-reverse decision when reasonable changes in assumptions reverse the recommendation. Policymakers should test those assumptions and explain the uncertainty.')
stem(68,'In a hypothetical banking system, banks initially hold exactly their required reserves. The reserve ratio stays at 10%. Banks lend all excess reserves, every loan payment is fully redeposited, and there is no currency drain or other lending constraint. The public deposits $50 million in currency it previously held. Including this initial deposit, what is the maximum total increase in deposits?')
stem(69,'In a hypothetical banking system, banks initially hold exactly their required reserves. The reserve ratio stays at 15%. Banks lend all excess reserves, every loan payment is fully redeposited, and there is no currency drain or other lending constraint. The public deposits $30 million in currency it previously held. Including this initial deposit, what is the maximum total increase in deposits?')
stem(70,lambda q:re.sub(r'In the standard short-run model, monetary easing lowers rates but pessimistic sales expectations offset the incentive to invest \$(\d+)\. Which missing link explains weak AD transmission\?',r'In the standard short-run model, monetary easing lowers interest rates, making $\1 in investment more attractive. However, weaker expected sales offset that incentive. Why might aggregate demand respond only weakly to the monetary easing?',q['q']))
opts_map={71:'buys',72:'sells'}
for n,verb in opts_map.items():
    sub(n,'what is the next directional step, other things equal?','what happens next to the equilibrium interest rate, other things equal?')
sub(73,'wants to contract broad deposits by','wants to reduce bank deposits by');sub(73,'Which reserve operation matches the estimate?','How should it change reserves to achieve that reduction using the estimated multiplier?')
stem(74,'Banks receive $140 in new reserves. The required reserve ratio is 10%, which would give a simple deposit multiplier of 10 if banks held no excess reserves. Banks also choose to hold excess reserves equal to 10% of deposits. With no currency leakage, what is the maximum deposit increase supported by the new reserves?')
sub(75,'real productive resources remain','real productive resources stay fixed at');sub(75,'Under the stated long-run quantity-theory/neutrality assumptions with stable velocity, which distinction is correct?','Assume monetary neutrality in the long run and stable velocity. Using the quantity theory of money, how does a permanent increase in money growth differ from a one-time increase in the money supply?')
stem(76,'A firm owns a machine that can produce Product X, earning $75,000 in revenue after variable costs, or Product Y, earning $92,000 after variable costs. Converting it to Product Z would earn $100,000 after variable costs but requires an additional $15,000 conversion cost. If the firm chooses Z, what is its net benefit compared with the next-best alternative?')
stem(77,'Aggregate demand expands unexpectedly, raising output and the price level. What short-run change in unemployment and inflation does the Phillips-curve model predict?')
stem(78,'Refer to the graph with SRPC0, SRPC1, A, and B. Use inflation = expected inflation − 0.6 × (unemployment − 5) + s, where s is the number of percentage points a supply shock adds to inflation. Rates are in percent and differences are in percentage points. At B, s is independently measured as +1.1 percentage points. What expected inflation is consistent with B, and could we determine it from the graph alone without knowing s?')
sub(78,'without the offset','without knowing s','options');sub(78,'plus the supply offset','plus s','options')
feedback(78,'At B, unemployment is 6% and actual inflation is 6%. Thus 6 = expected inflation − 0.6 + 1.1, giving expected inflation of 5.5%. Without knowing the supply shock\'s contribution s, the graph determines only expected inflation + s = 6.6. The higher curve alone does not show how much expectations changed.')
sub(79,'any removed supply offset','the inflation effect of the supply disruption ending','options');sub(79,'the expectations rise versus the removed supply offset','the rise in expected inflation compared with the inflation effect of the disruption ending','options')
feedback(79,'Neither the supply disruption nor the higher expected inflation affected the original curve. The final curve reflects only the higher expected inflation, so it remains above the original curve. Comparing the final curve with the curve during the disruption requires comparing the sizes of those two effects; observed inflation alone does not establish them.')
stem(80,'Use π = πe − (u − 5) + s, where π is actual inflation, πe is expected inflation, u is unemployment, and s is the number of percentage points a supply shock adds to inflation. Rates are in percent. Actual inflation is 4% and unemployment is 6%. Without knowing s, a student reports expected inflation as exactly 5%. What assumption does this answer require, and how would a positive value of s change the answer?')
sub(80,'A positive supply offset','A positive value of s','options');sub(80,'a positive supply offset','a positive value of s','options');sub(80,'every supply offset','every value of s','options')
feedback(80,'Rearranging gives πe = 4 + (6 − 5) − s = 5 − s. Expected inflation is 5% only if s = 0. A positive contribution from the supply shock means lower expected inflation at the same actual inflation and unemployment.')
stem(81,'A binding rent ceiling reduces the number of apartments rented, eliminating the gains from some mutually beneficial rentals. Which way of allocating the remaining apartments would cause an additional loss of total surplus?')
sub(82,'Which accounting change and behavioral pressure follow?','How does national saving change, and what pressure does that put on the real interest rate?')
stem(83,'When calculating private saving as Y − T − C and public saving as T − G, what must T mean for the two formulas to be consistent?')
sub(84,'Which assessment separates average material output from output per worker?','How do real GDP per person and output per worker change?')
sub(85,'In GROWTH-01','In the production graph');sub(86,'Using GROWTH-01','Using the production graph')
sub(87,'private agents','households and firms');sub(87,'Which memo is strongest?','How might their doubts affect the output cost of reducing inflation?')
sub(88,'Which joint AD-AS/Phillips correction is needed?','As expectations adjust, how do the short-run aggregate supply and Phillips curves change, and what happens to output and unemployment?')
sub(88,'beyond natural benchmarks','above potential output and below the natural rate of unemployment','options');sub(88,'toward natural benchmarks','toward potential output and the natural rate of unemployment, respectively','options')
sub(88,'new natural benchmarks','a new potential output level or natural rate of unemployment','feedback')
stem(89,'Policymakers will accept a cumulative output loss of at most 6% of annual output to reduce inflation. Plan A has a sacrifice ratio of 3; Plan B has a ratio of 2. Both ratios are treated as constant. Which plan can reduce inflation by 3 percentage points without exceeding the limit?')
stem(90,'Annual output gaps are −2%, −1%, and −1%, each measured against the same benchmark annual output of $260. Inflation falls from 7% to 5%. Policymakers will accept a total cumulative output loss of at most 6% of that benchmark output. They expect the observed sacrifice ratio to apply to further reductions in inflation. Can they lower inflation to 3% without exceeding the total loss limit?')
sub(90,'counts against the budget','counts toward the loss limit','options');sub(90,'All 6% of the budget has already been spent','The entire permitted 6% loss has already occurred','options');sub(90,'only 2% of the loss budget remains','only an additional 2% output loss is permitted','options')
feedback(90,'Cumulative output loss is 4% and inflation fell by 2 percentage points, so the sacrifice ratio is 2. Only 2% more output loss is permitted. At the same ratio, that allows one more percentage-point reduction in inflation, to 4%. Reaching 3% would require 4% more output loss and exceed the limit.')
stem(91,'Policymakers planned to reduce inflation by 3 percentage points at a sacrifice ratio of 2, accepting a maximum cumulative output loss of 6%. The first percentage-point reduction unexpectedly costs 4% of annual output. If each further percentage-point reduction costs 2% of annual output, how much further can inflation fall within the loss limit, and what would achieving the original target cost?')
sub(91,'fits the remaining 2% budget','fits within the additional 2% output loss permitted','options')
feedback(91,'The remaining permitted loss is 6% − 4% = 2%. At an output cost of 2% per percentage point, inflation can fall by one more percentage point. Completing the original target would require two more percentage points, costing another 4% of output for a total loss of 8%.')
stem(92,'An anticipated increase in aggregate demand raises actual and expected inflation together, with no supply shock or labor-market reform. Can we conclude that unemployment initially falls below its natural rate, as it might after an unexpected increase in demand?')
sub(93,'A second ledger reports','Another report lists');sub(93,'what correction and trade-balance implication follow under NX=NCO?','what should the reported foreign purchases be, and does NX = NCO imply a trade surplus or deficit?')
sub(94,'A supplied monetary-policy effect raises','Monetary policy raises')
sub(95,'A separate purchases bill is enacted later.','Lawmakers later pass a separate increase in government purchases.');sub(95,'the bill takes effect','the spending increase takes effect');sub(95,'Which parts can reverse with recovery without another policy vote?','Which of these changes can reverse during recovery without another vote by lawmakers?')
sub(95,'its institutional origin','how it was authorized','feedback')
sub(96,'is supplied as reducing','reduces');sub(96,'The supplied investment fall','The investment decline','feedback')
stem(97,'Use inflation = expected inflation − (unemployment − 5) + s, where s is the number of percentage points a temporary supply shock adds to inflation. Rates are in percent. With s = +2 and unemployment at 6%, actual inflation is 6%. Before the shock ends, expected inflation rises by 1 percentage point and stays at that higher rate. What was expected inflation initially, and what will inflation be after the shock ends and unemployment returns to its natural rate of 5%?')
sub(97,'the offset ends','the supply shock ends','options');sub(97,'final natural-rate inflation','inflation at the natural unemployment rate','options');sub(97,'temporary offset persists','temporary supply shock persists','options');sub(97,'the removed offset is added again','the ended supply shock is added again','options')
feedback(97,'Initially, 6 = πe − 1 + 2, so expected inflation is 5%. Expectations then rise to 6%. After the supply shock ends and unemployment returns to 5%, inflation equals expected inflation, or 6%. Ending the supply shock does not necessarily return expectations to their original rate.')
stem(98,'A jobless worker has actively applied for jobs this week after voluntarily leaving a suitable job. Is this worker officially counted as unemployed, and which type of unemployment best describes the situation?')

# Focused reread refinements; no records beyond the frozen 128-ID set.
for q in families[1]:
    d=drafts[str(q['id'])]
    if '$80 recessionary' in d['q']:d['q']=d['q'].replace('a $80 recessionary','an $80 recessionary')
    d['feedback']=d['feedback'].replace('A correct initial size does not make the same increase in spending when the program takes effect appropriate after recovery.','An increase sized correctly for the original recession may create excess demand if it takes effect after recovery.')
opts(11,['Making the loan adds a loan asset and a deposit liability; the later payment reduces the first bank\'s reserves and the borrower\'s deposit.','Making the loan reduces reserves; the later payment creates the loan and increases bank capital.','Making the loan adds reserves and a deposit; the later payment leaves both banks\' reserves unchanged.','Making the loan reduces deposits; the later payment cancels the first bank\'s loan asset.'])
sub(25,'With rr=10%','With a required reserve ratio of 10%')
sub(26,'the graph alone does not measure either component','the final curve alone does not show the size of either effect','options')
sub(26,'the graph is impossible','the stated curve change is impossible','options')
sub(26,'The risk shift and rate feedback cancel exactly','The effects of risk and the higher interest rate cancel exactly','options')
sub(26,'The effect of risk exceeds the effect of higher interest rates; the currency depreciates, but the final curve alone does not show the size of either effect','Risk outweighs higher interest rates; the currency depreciates, but neither effect\'s size can be determined separately','options')
sub(27,"How well each study separates the policy's effect from other differences between the groups.",'How convincingly each study establishes cause and effect.','options')
sub(40,'Preserving the original gross real return','Preserving the original expected real return','feedback')
sub(44,'Ignore later requests for changes because the initial metric improved','Ignore later requests for changes because the opening bid was lower','options')
feedback(44,'Considering total cost and performance reduces the incentive to submit an artificially low opening bid and recover the difference through later changes.')
opts(57,['Wages rise for workers who keep their jobs, but fewer people work; total earnings depend on the sizes of both changes.','Wages rise for workers who keep their jobs, and fewer people work; total earnings rise by the same percentage as wages.','Wages rise for workers who keep their jobs, and fewer people work; total earnings fall by the same percentage as employment.','Wages rise and more people work; the higher wage shows that labor demand increased.'])
sub(58,'Which evaluation separates the intended mechanism from the employment tradeoff?','What do lower turnover and lower hiring tell us about the effects of the higher wage?')
sub(61,'the relevant potential benchmark may have changed','potential output itself may have changed','feedback')
sub(65,'What is the best marginal choice?','Should the policy continue for another year or end now?')
for a,b in [('Policy-to-rate transmission failed despite the observed interest-rate decline.','Monetary easing failed to lower interest rates, despite the observed decline.'),('Investment-to-AD transmission fails because capital spending is excluded from AD.','Investment cannot affect aggregate demand because capital spending is excluded from it.'),('Rate-to-investment transmission weakens when expected sales deteriorate.','Weaker expected sales can reduce investment despite lower interest rates.'),('Reserve-to-credit transmission tightened through an unstated increase in reserve requirements.','An unreported increase in reserve requirements restricted lending despite the monetary easing.')]:sub(70,a,b,'options')
feedback(70,'Lower interest rates affect aggregate demand only if spending responds. Weaker expected sales can make firms reluctant to invest even when borrowing becomes cheaper.')
sub(75,'real productive resources stay fixed at','real productive resources, measured by an index, stay fixed at')
sub(75,'index units.','on that index.')
sub(79,'It remains above its original position, but its position relative to the disruption-period curve depends on the rise in expected inflation compared with the inflation effect of the disruption ending.','It remains above the original curve; its position relative to the curve during the disruption depends on the sizes of the two effects.','options')
sub(88,'A proposal treats the initial low unemployment as a new permanent benchmark.','A proposal assumes this lower unemployment rate can last permanently.')
sub(88,'output and unemployment remain above potential output and below the natural rate of unemployment.','output remains above potential and unemployment below its natural rate.','options')
sub(88,'output and unemployment return toward potential output and the natural rate of unemployment, respectively.','output returns toward potential and unemployment toward its natural rate.','options')
sub(97,'because the ended supply shock is added again','because it still includes the former supply shock\'s effect','options')
assert set(drafts)==set(originals)
unchanged=[i for i,d in drafts.items() if all(d[k]==originals[i].get(k) for k in ['q','options','feedback'])]
assert not unchanged,unchanged
(HERE/'patches.json').write_text(json.dumps(drafts,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Authored',len(drafts),'records in',len(families),'families')
