import json,hashlib,unicodedata
from pathlib import Path
W=Path(__file__).resolve().parent
b=json.loads((W/'inventory-before.json').read_text('utf8'))['records'];s={}
def norm(x):return ' '.join(unicodedata.normalize('NFKC',x).lower().split())
def oldopts(i):
 q=b[i];a=next(o for o in q['options'] if hashlib.sha256(norm(o).encode()).hexdigest()==q['aHash']);return [a]+[o for o in q['options'] if o!=a]
def put(i,q,options,feedback,reason,numeric=False):
 assert i in b and i not in s
 s[i]=dict(q=q,options=options,feedback=feedback,reason=reason,numeric=numeric)
def tweak(i,q,feedback,reason,numeric=False):put(i,q,oldopts(i),feedback,reason,numeric)
offsets={'LG-Q-275':(300,80),'LG-Q-373':(200,60),'P52B-S4-FMCO-B2-002':(120,25),'LG-B-6023':(300,80)}
for i,(gross,offset) in offsets.items():
 tweak(i,f'A fiscal package produces a gross ${gross} billion rightward AD shift in a simplified expenditure model. Crowding out produces a total ${offset} billion leftward AD offset, including all induced spending effects of the displaced investment. What net AD increase should policy analysis use?',f'The two magnitudes are both total AD changes: {gross} − {offset} = ${gross-offset} billion. Do not multiply the stated total offset again. This is an AD shift, not a guaranteed equal increase in equilibrium GDP.','Clarify total AD offset versus raw autonomous investment reduction; prevent mixing pre- and post-multiplier magnitudes.',True)
for i,g,mpc,offset in [('LG-Q-376',60,'0.75',50),('LG-Q-4011',80,'0.75',70),('LG-Q-9073',100,'0.6',75),('LG-Q-9133',90,'0.8',180)]:
 prompt=f'Government purchases increase by ${g} billion. MPC = {mpc}; use the simple spending multiplier, with no other leakages. Crowding out produces a total ${offset} billion AD offset, including its induced spending effects. '
 prompt+='Which sequence separates the direct purchases, gross multiplier prediction, and net AD shift?' if i in ['LG-Q-9073','LG-Q-9133'] else 'What is the net rightward AD shift?'
 tweak(i,prompt,b[i]['feedback']+' The offset is already a total AD change and is subtracted after multiplication; the sequence is an analytical decomposition, not a claim about separate calendar stages.','Specify the level at which crowding out enters the multiplier calculation.',True)
for i,g,gap,mpc,offset in [('LG-Q-9069',50,250,'0.75',40),('LG-Q-9139',100,600,'0.8',150)]:
 tweak(i,f'At a fixed reference price level, desired spending is ${gap} billion below the policy target. Government purchases rise by ${g} billion and MPC = {mpc}. Use the simple spending multiplier with no other leakages. Crowding out produces a total ${offset} billion AD offset, including its induced spending effects. Which decomposition gives the net AD shift and remaining shortfall at that reference price?',b[i]['feedback']+' These are horizontal AD distances at the reference price, not actual equilibrium GDP changes; the total offset is not multiplied again.','Separate horizontal AD shortfall from equilibrium output gap and define total crowding-out offset.',True)
put('LG-Q-4014','At a fixed reference price, AD must shift right by $500 billion to meet the policy target. A supplied monetary-policy effect raises autonomous investment by $50 billion, government purchases rise by $60 billion, and fiscal crowding out reduces autonomous investment by $40 billion. MPC = 0.75; apply the same simple multiplier to each autonomous change, with no other leakages. What AD shortfall remains?',
 ['$220 billion remains.','$100 billion remains.','$60 billion remains.','$460 billion remains.'],
 'Net autonomous spending rises by 50 + 60 − 40 = $70 billion. The multiplier is 1/(1 − 0.75) = 4, so AD shifts $280 billion and the remaining horizontal shortfall is 500 − 280 = $220 billion. Subtracting only $40 billion after multiplying the gross impulse would omit the lost induced spending.',
 'Correct raw investment displacement arithmetic; monetary transmission is supplied rather than re-audited.',True)
put('LG-Q-9070','At a fixed reference price level, desired spending already exceeds the policy target by $180 billion. Purchases rise by $30 billion and MPC = 0.8. With the simple spending multiplier and no offsets, which interpretation of the policy is correct?',
 ['The direct $30 billion increase becomes a $150 billion AD shift, raising excess desired spending to $330 billion at the reference price.','The policy shifts AD left by $150 billion, reducing excess desired spending to $30 billion.','Only the direct $30 billion enters AD, raising excess desired spending to $210 billion.','The $150 billion AD shift exactly removes the existing $180 billion excess.'],
 'The multiplier is 5, so desired spending at the reference price rises by $150 billion. The excess becomes 180 + 150 = $330 billion. An upward-sloping SRAS would divide the equilibrium response between output and prices; these AD distances do not determine the GDP gap.',
 'Remove unjustified one-for-one addition of an AD shift to an equilibrium output gap.',True)
tweak('LG-Q-9074','At a fixed reference price, desired spending is $400 billion below the policy target. Government purchases rise by $100 billion and MPC = 0.75. Using the simple spending multiplier and ignoring crowding out and other leakages, which decomposition gives the AD shift and remaining horizontal AD gap?',
 'The multiplier is 4. Direct purchases of $100 billion imply a total $400 billion AD shift, closing the stated horizontal AD gap. Without an SRAS relationship, this does not identify an equal equilibrium GDP increase.',
 'Define the gap as a horizontal AD distance instead of equating multiplier spending with realized output.',True)
tweak('LG-Q-9136','At a fixed reference price, desired spending exceeds the policy target by $360 billion. Contractionary monetary policy is supplied as reducing autonomous investment by $50 billion. MPC = 0.8; use the simple spending multiplier with no other leakages. What excess desired spending remains at that reference price?',
 'The supplied investment fall shifts AD left by 50/(1 − 0.8) = $250 billion. Excess desired spending falls to 360 − 250 = $110 billion. This is an AD-distance calculation, not a claim that the equilibrium GDP gap falls one-for-one.',
 'Supply the monetary effect, remove the nonexistent graph cue, and separate AD distances from output gaps.',True)
put('PM2D2-STAB-L-002','A government authorizes $75 billion of extra purchases when the required rightward AD shift is $300 billion. Before payment, the required shift at the same reference price falls to $100 billion. The simple spending multiplier is 4; no crowding out or other leakages apply. One third of the authorized purchases must now occur, while the rest can still be cancelled. Which implementation decision meets the revised target without overshooting?',
 ['Cancel the remaining $50 billion; the unavoidable $25 billion already produces the required $100 billion AD shift.','Pay the entire remaining $50 billion; the original authorization still matches the revised target.','Pay another $25 billion and cancel $25 billion; the unmultiplied purchases must equal the revised target.','Cancel all $75 billion; a revision of the target eliminates the unavoidable payment.'],
 'The unavoidable purchases are 75/3 = $25 billion, producing 25 × 4 = $100 billion of AD. The remaining authorization is $50 billion and should be cancelled under the stated target. Full implementation would create a $300 billion shift and a $200 billion overshoot. Policy must be evaluated when it takes effect.',
 'Replace direct overshoot arithmetic with an inverse implementation decision under revised data and an unavoidable commitment.',True)
put('ECON-SP-ELITE-320','Refer to the multiplier graph. Direct purchases shift AD1 to AD2; induced spending makes the gross prediction AD3. Crowding out creates a positive total AD offset. Which additional restriction is needed to conclude that the final AD curve lies strictly between AD2 and AD3?',
 ['The total offset must be smaller than the horizontal AD2-to-AD3 distance at the reference price.','The total offset must be smaller than the full AD1-to-AD3 distance, with no further restriction.','The total offset must equal the full AD1-to-AD3 distance.','The total offset must exceed the AD2-to-AD3 distance but remain below the AD1-to-AD3 distance.'],
 'To finish to the right of AD2, subtract less than the extra induced-spending distance from AD2 to AD3. A positive offset puts the result left of AD3. Merely retaining some net stimulus relative to AD1 does not guarantee finishing beyond AD2.',
 'Correct unsupported location inference from partial crowding out and add an identification condition.')
put('ECON-SP-HARD-228','Refer to the AD multiplier graph. For this application, assign Y1 = $500 billion, Y2 = $560 billion, and Y3 = $620 billion at the marked price P. Starting on AD1, purchases increase by $40 billion and MPC = 0.5. Use the simple spending multiplier. Crowding out creates a total $20 billion AD offset, already including induced spending effects. Which drawn AD curve represents the net result at P?',
 ['AD2, because the net rightward shift is $60 billion.','AD3, because the net rightward shift is $120 billion.','AD1, because the $20 billion offset cancels all induced spending and direct purchases.','No drawn curve, because $80 billion is the net shift after crowding out.'],
 'The multiplier is 2. Gross AD increases by $80 billion; subtract the already-total $20 billion offset to obtain $60 billion. At P, desired output is therefore 500 + 60 = $560 billion, on AD2. The diagram does not contain an SRAS curve, so this locates demand at P rather than a final macro equilibrium.',
 'Resolve the local Hard graph-integration gap through multiplier arithmetic, an explicit total offset, and curve mapping; no exam graph or scenario is copied.',True)
put('ECON-SP-HARD-212','Refer to the graph. The economy begins at AD1-AS1. Higher planned spending moves demand to AD2 while lower production costs move short-run supply to AS2. Compared with the starting equilibrium, what happens to output and the price level?',
 ['Output rises from Y3 to Y2 while the price level stays at P2.','Output stays at Y1 while the price level rises from P1 to P3.','Output falls from Y2 to Y3 while the price level stays at P2.','Output rises from Y3 to Y1 while the price level falls from P2 to P1.'],
 'The starting AD1-AS1 intersection is Y3/P2 and the ending AD2-AS2 intersection is Y2/P2. The two rightward shifts reinforce output and offset in the price level in this particular drawing.',
 'Repair impossible starting-curve transition and require both macro outcomes from the actual intersections.')
for i in ['P52A-AS-H-003','P52A-AS-B3-001']:
 put(i,'A permanent labor-force increase raises productive capacity and tends to expand short-run supply. A simultaneous temporary energy-price spike tends to reduce short-run supply. No relative magnitudes are given. What can be concluded about LRAS and the net SRAS shift?',
 ['LRAS shifts right; the net SRAS direction is not determined.','LRAS shifts right; SRAS necessarily shifts left.','LRAS shifts left; SRAS necessarily shifts right.','LRAS stays fixed; SRAS necessarily shifts right.'],
 'The labor-force increase raises potential output, shifting LRAS right. The two events exert opposing pressures on SRAS, so their relative effects are needed to determine its net direction. A temporary energy-price spike does not by itself remove productive capacity.',
 'Remove the hidden assumption that energy costs dominate the labor-force contribution to SRAS.')
put('P52A-AS-L-003','For this capacity calculation only, potential output equals usable capital multiplied by output per unit of usable capital; other inputs are sufficient and unchanged. Usable capital falls by 5 percent while output per unit rises by 8 percent. A planner claims that any productivity gain above 5 percent would restore the original LRAS position. Which assessment is correct?',
 ['Potential output rises by 2.6 percent, but exactly restoring it would require a productivity gain of about 5.26 percent.','Potential output rises by 3 percent, and a 5 percent productivity gain would exactly restore it.','Potential output falls by 2.6 percent, and an 8 percent productivity gain cannot offset the capital loss.','Potential output is unchanged because the two percentage changes cancel exactly.'],
 'Capacity becomes 0.95 × 1.08 = 1.026 times its original value, a 2.6 percent increase and a rightward LRAS shift. The break-even productivity factor is 1/0.95, or a gain of approximately 5.26 percent. Percentages with different bases cannot simply be subtracted.',
 'Specify the missing production relationship and replace ambiguous percentages with a capacity-and-threshold inference.',True)
tweak('P52B-S1-LRADJ-L-001',b['P52B-S1-LRADJ-L-001']['q'].replace('A temporary negative aggregate-demand shock','A one-time aggregate-demand decline that remains in place'),b['P52B-S1-LRADJ-L-001']['feedback'],'Remove a temporary-shock assumption inconsistent with the fixed post-shock AD long-run endpoint.')
tweak('PM2D1-LRADJ-M-001',b['PM2D1-LRADJ-M-001']['q'].replace('A temporary demand boom','An increase in demand that remains in place'),b['PM2D1-LRADJ-M-001']['feedback'],'State that AD remains at its new position during endogenous wage adjustment.')
for i,q,fb in [
 ('PG3-AD-H-001','Refer to the first AD graph. At a price level of 50, which value is closest to the horizontal real-GDP-demanded gap between AD0 and AD1?','The hand-drawn lines imply roughly 100 on AD0 and about 155 on AD1. The gap is about 55 units, so 50 is the closest offered estimate; the drawing does not justify an exact 50-unit claim.'),
 ('PG3-AD-H-002','Refer to the second AD graph. At a price level of 45, which value is closest to the horizontal real-GDP-demanded gap between AD0 and AD1?','The curves show approximately 150 on AD0 and 100 on AD1 at this price level, so 50 units is the closest offered estimate.'),
 ('PG3-AS-H-001','Refer to the first AS graph. At real GDP of 150, which value is closest to the vertical price-level gap between AS0 and AS1?','The hand-drawn curves lie near price levels 150 and 190 at GDP 150. Their gap is roughly 40–45 price-level units, so 40 is the closest offered estimate; the graph does not support exact coordinate arithmetic.'),
 ('PG3-AS-H-002','Refer to the second AS graph. At real GDP of 150, which value is closest to the vertical price-level gap between AS0 and AS1?','The curves lie near price levels 150 and 110 at GDP 150. Their separation is approximately 40 price-level units, the closest offered estimate.')]:
 tweak(i,q,fb,'Replace unsupported exact precision with a closest-estimate reading of the actual raster graph.',True)
put('PM2D2-FISCAD-L-001','A $120 billion refundable tax credit can be allocated between two household groups, with MPCs of 0.90 and 0.40. The government wants a first-round consumption increase of $84 billion, before any induced spending. How should the credit be allocated, and why would the same $120 billion of government purchases have a different first-round AD effect?',
 ['$72 billion to the higher-MPC group and $48 billion to the other; purchases enter AD directly, whereas some credit is saved.','$48 billion to the higher-MPC group and $72 billion to the other; purchases and credits enter AD directly in full.','$60 billion to each group; averaging MPCs guarantees the target regardless of allocation.','$84 billion to the higher-MPC group and $36 billion to the other; each dollar of credit is a dollar of purchases.'],
 'Let x go to the higher-MPC group. Then 0.90x + 0.40(120 − x) = 84, giving x = $72 billion and $48 billion to the other group. Their consumption responses are $64.8 billion and $19.2 billion. Government purchases would directly add $120 billion to AD; a credit affects disposable income and only the spent portion enters first-round consumption.',
 'Replace forward weighted arithmetic with reverse allocation under a fiscal target and distinguish purchases from tax credits.',True)
put('P52A-FISCAD-L-005','A government wants to reduce aggregate demand while expanding targeted transfers. Under a simple closed-economy expenditure model, MPC = 0.6 for all households, taxes stay fixed, and no crowding-out or price feedback occurs. Transfers rise by $30 billion. What minimum purchases cut produces a $45 billion leftward AD shift rather than merely cancelling the transfer stimulus?',
 ['$36 billion: offset $18 billion of induced first-round consumption and add $18 billion of net autonomous contraction.','$18 billion: cancelling the first-round transfer consumption also provides the full target contraction.','$45 billion: the target AD shift is itself the required purchases cut.','$75 billion: add the full transfer amount to the desired AD reduction.'],
 'Transfers first add 0.6 × 30 = $18 billion of consumption. The spending multiplier is 2.5, so a $45 billion AD reduction requires $18 billion of net autonomous contraction. Purchases must fall by 18 + 18 = $36 billion. The transfer is not itself a government purchase.',
 'Replace basic contractionary direction recognition with a constrained package that accommodates an expansionary transfer.',True)
put('P52A-FISCAD-L-004','Two equal-cost fiscal packages provide either a targeted transfer or a broad tax rebate. Recipients of the transfer have the higher MPC, but most transfer payments arrive after a planned stabilization deadline, while the rebates arrive before it. A minister concludes that the transfer must create more AD by the deadline. Which additional comparison is needed?',
 ['Compare each package’s amount actually received and spent by the deadline, including induced spending completed by then.','Compare only the recipients’ MPCs; the timing of payment cannot affect AD by the deadline.','Count every transfer dollar as purchases immediately, then compare that total with rebate consumption.','Compare the eventual multipliers only; completion of spending rounds before the deadline is irrelevant.'],
 'A higher MPC raises consumption from each dollar received, other things equal, but it does not guarantee a larger effect by a date when fewer dollars have been paid. Timely receipts, consumption and induced rounds jointly determine the relevant short-run AD effect.',
 'Add timing and an evidence requirement to a repeated higher-MPC recognition item.')
put('PG3-AD-L-001','Refer to the first AD graph. Purchases rise, private investment partly falls, and the combined spending changes leave the economy on AD1 instead of AD0. The equilibrium price level also rises. Which conclusion separates what the diagram establishes from what still requires evidence?',
 ['Net desired spending rose at a common price; the equilibrium GDP increase needs the SRAS relationship and cannot be read as the whole horizontal AD shift.','The price increase alone shifted AD0 to AD1; SRAS is unnecessary for identifying equilibrium GDP.','The investment decline proves net AD fell; the rightward curve is only movement along AD0.','The horizontal AD0-to-AD1 distance equals the equilibrium GDP increase even when SRAS slopes upward.'],
 'The rightward shift records a positive net demand change despite an offsetting investment effect. A price change moves along a demand curve. The final intersection and split between price and output responses require supply information absent from this AD-only diagram.',
 'Replace Legendary curve-definition repetition with offset, movement-versus-shift and equilibrium-identification synthesis.')
put('PG3-AD-L-002','Refer to the second AD graph. An economy moves from AD0 to AD1. Falling confidence reduces consumption, while an enacted purchases increase pushes spending in the opposite direction. A lower price level subsequently raises quantity demanded along AD1. Which conclusion is supported, and what remains unidentified?',
 ['The confidence-related demand reduction outweighs the fiscal expansion at a common price; the diagram does not separately measure the two gross effects.','The fiscal expansion outweighs the confidence decline; the lower price level causes the leftward AD shift.','The lower price level reverses the confidence shock, so the final demand curve must be AD0.','Each gross spending effect equals the net distance between AD0 and AD1, because the shifts have opposite signs.'],
 'AD1 lies left of AD0, so the net demand change is negative at a common price. This identifies which opposing effect dominates, not their individual sizes. A lower price increases quantity demanded along the new curve and does not itself restore the old demand schedule.',
 'Deepen the upper-tier graph item through opposing determinants and limits on identifying gross effects.')
put('PG3-AS-L-001','Refer to the first AS graph, treating AS0 and AS1 as short-run supply. A temporary energy bottleneck and a permanent loss of productive equipment could each help explain the shift to AS1. After energy costs normalize, which evidence is needed to predict whether wage adjustment restores the old potential-output level?',
 ['Whether productive capacity was restored and LRAS retained its old position; the SRAS-only drawing does not establish that.','Whether the price level initially rose; any price rise proves that LRAS stayed fixed.','Whether actual GDP fell; any actual output loss permanently lowers potential output by the same amount.','Whether demand policy can raise spending; a rightward AD shift by itself restores lost productive capacity.'],
 'The drawing establishes a reduction in short-run supply, but contains no LRAS line. Temporary costs may reverse while destroyed capital leaves lower potential output. Wage adjustment returns output toward the applicable capacity level, so the old long-run anchor must be verified.',
 'Replace direct SRAS recognition with a temporary-versus-permanent diagnosis and a required-evidence test.')
put('PG3-AS-L-002','Refer to the second AS graph, treating AS0 and AS1 as short-run supply. Both lower expected prices and a lasting productivity gain could contribute to the shift to AS1. If expected prices later return to their original level but the productivity gain remains, which prediction is justified?',
 ['Some rightward supply effect can remain, and potential output can be higher; the exact final SRAS position needs the sizes of the two original contributions.','SRAS must return exactly to AS0 and LRAS must remain fixed because expected prices returned.','SRAS must stay exactly at AS1 because a permanent productivity change prevents any expectations effect.','LRAS must shift left because returning expected prices erase the productive-capacity gain.'],
 'Restoring expected prices reverses that contribution to SRAS, while improved productivity still supports supply and raises potential output. The graph records only their combined initial effect; without a decomposition it does not locate the final SRAS precisely.',
 'Add partial reversal, long-run capacity, and identification limits to a repeated upper-tier graph definition.')
put('PG3-MEQ-L-004','Refer to the ADAS graph with points A, B, C and D. The economy begins at A. A supply disruption moves AS0 to AS1, giving D, and remains in place. Compare two fiscal targets while AS1 stays fixed: restore the original output, or restore the original price level. Which comparison follows from the drawn straight AS1 line, extended if needed?',
 ['Restoring output gives C at GDP 75 and price 150; restoring price 100 instead gives GDP 25 and requires a further AD contraction from D.','Restoring output gives B at GDP 100 and price 125; restoring price 100 also restores GDP 75.','Both targets give A because fiscal expansion returns AS1 to AS0.','Restoring output gives C at GDP 75 and price 150; restoring price 100 instead raises GDP to 125.'],
 'A is (75,100) and D is (50,125). With AS1 fixed, output 75 requires C at price 150. AS1 passes through D (50,125) and C (75,150), so its equation is P = Y + 75; at P = 100, Y = 25. Moving from D to that lower-price point requires lower AD and further output loss. Fiscal demand policy does not remove the supply disruption.',
 'Replace a repeated simultaneous-shift claim with an inverse output-versus-price stabilization comparison using actual graph geometry.',True)
put('ECON-SP-LEGENDARY-9003','Refer to the graph with LRAS. Starting at AD1-AS2, a lasting demand expansion moves AD to AD2. Wage adjustment then moves SRAS all the way to AS1. Only after this adjustment does a delayed fiscal contraction return AD to AD1. With wages slow to change again, why does this delayed action fail to restore the original equilibrium immediately?',
 ['It leaves the economy at Y3/P2, below potential; restoring the original Y1/P1 with AD1 requires SRAS to move back to AS2.','It leaves the economy at Y1/P1 immediately, because restoring AD always restores the original equilibrium.','It leaves the economy at Y2/P2, because wage adjustment shifted LRAS to Y2.','It leaves the economy at Y1/P3, because a contraction cannot change output once wages have adjusted.'],
 'The sequence is AD1-AS2 at Y1/P1, AD2-AS2 at Y2/P2, AD2-AS1 at Y1/P3, then AD1-AS1 at Y3/P2. After wages adjusted to the demand expansion, simply restoring old demand creates a new recessionary gap. Subsequent lower wage and expected-price pressures can return SRAS toward AS2.',
 'Deepen repeated self-correction recognition into a delayed-policy reversal after completed wage adjustment.')
put('ECON-SP-LEGENDARY-9004','Refer to the graph with LRAS. The economy starts at AD1-AS1, below potential. Two separate counterfactuals restore Y1: leave AD fixed and allow SRAS to reach AS2, or hold AS1 fixed and expand AD to AD2. If policymakers implement the full demand expansion after SRAS has already reached AS2, what happens and why?',
 ['Output reaches Y2/P2, above potential, because each full remedy was sized for the original gap rather than the already-adjusted economy.','Output remains Y1/P1 because self-correction prevents fiscal policy from changing demand.','Output remains Y1/P3 because a policy calibrated to the original gap automatically shrinks as wages adjust.','Output falls to Y3/P2 because combining two output-restoring changes reverses both shifts.'],
 'Self-correction alone gives AD1-AS2 at Y1/P1; the policy alone gives AD2-AS1 at Y1/P3. Combining both full changes gives AD2-AS2 at Y2/P2. A policy appropriate before cost adjustment can be excessive after the gap has closed.',
 'Integrate alternative stabilization paths, price outcomes and policy timing in an existing Legendary record.')
for i,high in [('ECON-SP-ELITE-314',True),('ECON-SP-ELITE-315',False)]:
 put(i,('Output initially exceeds potential after a lasting AD expansion.' if high else 'Output initially lies below potential after a lasting AD decline.')+' Compare two separate responses, each sufficient to restore potential output: a demand policy with SRAS held fixed, or wage/expectation adjustment with AD held fixed. How do their price-level effects compare with the initial short-run equilibrium?',
 [ ('Contractionary policy lowers the price level; wage adjustment raises it.' if high else 'Expansionary policy raises the price level; wage adjustment lowers it.'),
 ('Both responses lower the price level because both reduce output.' if high else 'Both responses raise the price level because both raise output.'),
 ('Contractionary policy raises the price level; wage adjustment lowers it.' if high else 'Expansionary policy lowers the price level; wage adjustment raises it.'),
 'Neither response changes the price level because both restore potential output.'],
 ('AD contraction moves down along fixed SRAS, lowering output and price. Rising wages shift SRAS left, lowering output but raising price along fixed AD.' if high else 'AD expansion moves up along fixed SRAS, raising output and price. Falling wages shift SRAS right, raising output but lowering price along fixed AD.')+' The two paths share an output target, not a price outcome.',
 'Replace unspecified same-direction adjustment with a comparison of output-restoring paths and opposite price effects.')
s['LG-B-6023']['q']='A stabilization analyst receives two model estimates: a $300 billion gross rightward AD shift from fiscal expansion and a total $80 billion AD reduction from displaced investment, including its induced spending effects. Which AD impulse should the analyst carry into the stabilization forecast?'
s['P52A-AS-B3-001']['q']='A larger permanent labor force adds productive capacity and supports short-run supply, but a temporary oil-price spike pushes short-run supply in the opposite direction. Before their relative sizes are known, which conclusion should an AD-AS analysis carry forward?'
(W/'revisions.json').write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n','utf8')
print(json.dumps({'contentRevisions':len(s),'numericRevisions':sum(x['numeric'] for x in s.values())}))
