import json,hashlib,copy,re,unicodedata
from pathlib import Path
from collections import Counter
W=Path(__file__).resolve().parent;R=Path(r'C:\Users\Jennings\Documents\GitHub\masteryquests-website\build\faculty-build-composer');REPO=R.parent.parent
def rd(n):return json.loads((W/n).read_text('utf8'))
def wr(n,x):(W/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n','utf8')
def sha(x):return hashlib.sha256(x).hexdigest()
def norm(s):return ' '.join(unicodedata.normalize('NFKC',s).lower().split())
def key(q):return next(o for o in q['options'] if sha(norm(o).encode())==q['aHash'])
def loc(m):return [(p,q) for p,qs in m['questions'].items() for q in qs]+[(p,q) for p in ['repairQuestions','repairSeedQuestions','bridgeQuestions'] for q in m.get(p,[])]
b=rd('inventory-before.json');a=rd('inventory-after.json');v=rd('validation.json');acc=rd('accounting.json');s=rd('revisions.json');ch=rd('changes.json');before=rd('quality-before.json');after=rd('quality-after.json');browser=rd('browser-validation.json');obj=rd('objective-findings-before.json');old=rd('library-baseline.json');new=rd('library-after.json');overlap=rd('overlap-mask.json');actions=rd('record-actions.json');inspection=rd('accessibility-inspection.json')
deferred=set(overlap['selectedPhillipsDeferredConcepts']);deferredIds=set(overlap['selectedPhillipsDeferredIds']);core=set(b['views'])-deferred
for c in old['concepts']:
 if c not in core:assert old['concepts'][c]==new['concepts'][c],c
permittedGlobal={'concepts','assetInventory','librarySha256','registry'}
assert {k:x for k,x in old.items() if k not in permittedGlobal}=={k:x for k,x in new.items() if k not in permittedGlobal}
assert {k:x for k,x in old['registry'].items() if k!='librarySha256'}=={k:x for k,x in new['registry'].items() if k!='librarySha256'}
def stripAccess(x):return [{k:v for k,v in a.items() if k not in ['imageAlt','graphDescription']} for a in x]
assert stripAccess(old['assetInventory'])==stripAccess(new['assetInventory'])
for name in ['composer_registry.json','composer_library_manifest.json']:
 x=json.loads((R/'data'/name).read_text('utf8'));y=rd('staged/'+name)
 for z in [x,y]:
  z.pop('librarySha256')
  if 'assets' in z:z['assets']=stripAccess(z['assets'])
 assert x==y,name
nohash=copy.deepcopy(new);del nohash['librarySha256'];del nohash['registry']['librarySha256'];semantic=sha(json.dumps(nohash,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode());assert semantic==new['librarySha256']
wr('semantic-validation.json',dict(before=old['librarySha256'],after=semantic,independentlyRecomputed=True,sidecarsSynchronized=True,unrelatedGlobalDataUnchanged=True))
arch=rd('architecture-validation.json');review=[]
for x in b['conceptReview']['assets']:
 assert sha((R/x['sourcePath']).read_bytes())==x['sha256'];review.append({**x,'bytesVerified':True})
arch.update(reviewAssets=review,reviewRuntimeIndex=b['conceptReview']['runtimeIndex'],reviewGlobalWarningsRetained=b['conceptReview']['warnings'])
for p,h in b['sourceFiles'].items():assert sha((R/p).read_bytes())==h,'Changed since baseline: '+p
priorFolders=['money_banking_monetary_system_assessment_audit_2026_09_08','saving_investment_loanable_funds_assessment_audit_2026_09_09']
arch['priorAuditArtifactFilesBeforeApply']={}
for folder in priorFolders:
 prior=REPO/'validation_artifacts'/folder;arch['priorAuditArtifactFilesBeforeApply'][folder]={str(x.relative_to(prior)):sha(x.read_bytes()) for x in prior.rglob('*') if x.is_file()}
for mask in overlap['priorAudits']:
 assert not mask['sharedAuthoritativeIds'] and all(old['concepts'][c]==new['concepts'][c] for c in mask['protectedConcepts'])
arch.update(all20PriorAuditedModulesPreserved=True,allFivePhillipsDefinitionsPreserved=True,all140DefinitionsOutsideContentAuditUnchanged=True)
wr('architecture-validation.json',arch)
def graphOK(x):return all(x[k] for k in ['loaded','zoomOK','description','embeddedImages','text'])
graphs=browser['graphChecks'];coreGraphs=[x for x in graphs if x['concept'] in core];deferredGraphs=[x for x in graphs if x['concept'] in deferred];failed=[x for x in graphs if not graphOK(x)]
assert len(graphs)==161 and len(coreGraphs)==95 and all(graphOK(x) for x in coreGraphs)
assert len(failed)==42 and all(x['concept'] in deferred for x in failed)
for x in failed:assert b['records'][x['id']]==a['records'][x['id']]
wr('graph-validation.json',dict(registeredAssetsInspected=inspection,graphEligibilityBeforeAfter=dict(linked=[161,161],trialGraph=[72,72]),all95CoreGraphRecordsRenderedAndEnlarged=True,fullPresetSuccessfulGraphRecords=sum(map(graphOK,graphs)),deferredPhillipsGraphFailures=failed,allFailedRecordsIdenticalToBaseline=True,imageReferencesCorrected=47,imageBytesChanged=0,newAssets=0,checks=graphs,limitation='42 protected Phillips records retain legacy unresolved image references and empty delivered descriptions in the local generated quest. They are a documented preexisting delivery defect for the later Phillips audit, not a newly found AD-AS integration exception. All 95 core graphs pass; no full-preset all-graphs-pass claim is made.'))
wr('phillips-deferred-followup.json',dict(protectedRecords=262,fullDefinitionsUnchanged=True,integrationScan='Inspected supplied AD shocks, supply-shock transfer, and fiscal/contractionary bridge consistency; no new AD-AS economic integration defect found.',localGraphFailures=failed,registeredGraphsVisuallyInspected=True,action='Repair legacy image references and review inline accessibility as part of the user-directed later Phillips audit. No repair or new audit was scheduled automatically.'))
# Every before/final flag gets its own record, exact stem/key and actual rule disposition.
bf={(x['questionId'],x['rule']):x for x in before['findings']};af={(x['questionId'],x['rule']):x for x in after['findings']};disp=[]
for k in sorted(bf.keys()|af.keys()):
 i,rule=k;f=af.get(k,bf.get(k));q=a['records'][i];status='retained' if k in bf and k in af else 'newly-reported' if k in af else 'no-longer-reported';protected=i in deferredIds
 if protected:
  reason='Deferred under the explicit Phillips boundary; the exact record is unchanged. This flag is inventoried, not declared a false positive or remediated.'
  if i in {x['id'] for x in failed}:reason+=' Local rendering confirms an unresolved legacy image reference; see phillips-deferred-followup.json.'
 elif status=='no-longer-reported':reason='The targeted content or accessibility correction changed the flagged condition. '+s.get(i,{}).get('reason','Shared graph evidence now matches the inspected asset.')
 elif rule=='graph-question-evidence-mismatch':reason='Auditor false positive: the equilibrium-family regex requires standalone D-number and S-number labels, while this macro image correctly uses AD0/AD1 and AS0/AS1. The contract gives all four intersections; do not rename the actual curves to satisfy the regex.'
 elif rule=='curve-label-metadata-mismatch':reason='Auditor false positive: MPC means marginal propensity to consume in this fiscal question, not a marginal-private-cost curve. MPC is a supplied scalar and is not printed on this AD graph; no missing curve evidence exists.'
 elif rule=='graph-prompt-missing-cue':reason='The item is delivered with its required graph and refers to labeled points or a graph transition. A more explicit refer-to-graph cue would be a minor clarity improvement, but the current evidence is identifiable and all core graph delivery checks pass. Retained as a nonblocking wording limitation.'
 elif rule=='image-without-graph-required':reason='The existing graph-required/eligibility flag is false despite an image reference. The diagram renders after path normalization where needed; the record retains its existing eligibility. This conservative routing means the item is not promoted into Trial by Graph during this content audit.'
 elif rule=='missing-terminal-punctuation':reason='The stem intentionally leads into its answer alternatives. Missing terminal punctuation is a retained editorial issue; it does not change the economic key or prevent the sentence from being completed by an option.'
 elif rule=='repeated-feedback':reason='The shared feedback states the relevant mechanism for this record but is less tailored than a unique worked explanation. Retain the valid response and support-route continuity; repetition remains a nonblocking feedback-quality limitation.'
 elif rule=='approved-cross-role-stem-reuse':reason='Intentional approved cross-role reuse: main/checkpoint and Repair records share this foundational expected-price/SRAS prompt. Preserve their distinct IDs, roles and routes; do not create cosmetic wording solely to remove the flag.'
 elif rule=='near-duplicate-stem':reason='The token-set comparison loses ordered curve direction. Medium ECON-SP-MEDIUM-129 moves AS2 to AS1, while Hard ECON-SP-HARD-211 moves AS1 to AS2, producing opposite outcomes. These remain closely related practice grammars, not identical tasks; retain and disclose limited variety.'
 elif rule=='answer-length-outlier':reason='The key states the conditional or linked result while alternatives are shorter. This is a real test-taking cue retained as a nonblocking distractor limitation, not treated as proof of a wrong key. The specific key and alternatives below document the imbalance.'
 elif rule=='weak-absolute-distractors':reason='The alternatives overstate certainty, omit a supplied mechanism or confuse a curve with an axis variable. Some are easy to eliminate from absolute wording; this residual distractor weakness is acknowledged. Retain the economically conditional key and current pool role.'
 elif rule=='possible-difficulty-overstatement':
  if i=='ECON-SP-HARD-228':reason='Heuristic false positive: the revised Hard item requires a multiplier, total-offset subtraction, and mapping the net demand quantity onto a supplied graph scale. The rule does not recognize this quantitative integration; independent recomputation gives AD2 at 560.'
  elif i=='ECON-SP-HARD-212':reason='The revised Hard task links two supplied determinants to two curve shifts, compares both intersections and reports output plus price outcomes. It is a scaffolded exam application at the easier edge of Hard; do not retag to silence the flag.'
  else:reason='Retained calibration limitation: this is a fairly direct graph reading or short outcome classification for its tier. Stronger retained Hard applications and selected upper-tier syntheses provide the broader demand; this audit does not claim every item independently meets the top of its tier.'
 else:raise AssertionError((i,rule))
 disp.append(dict(questionId=i,concept=q['primaryConceptId'],rule=rule,severity=f['severity'],status=status,protectedPhillips=protected,contentRevised=i in s,reason=reason,finalStem=q['q'],keyedOption=key(q),options=q['options'],feedback=q['feedback'],auditorMessage=f['message']))
def flagCounts(report,protected=False):
 rows=[x for x in report['findings'] if (x['questionId'] in deferredIds)==protected];return dict(Counter(x['severity'] for x in rows))
wr('quality-dispositions.json',dict(before=before['counts'],after=after['counts'],coreBefore=flagCounts(before),coreAfter=flagCounts(after),deferredBefore=flagCounts(before,True),deferredAfter=flagCounts(after,True),method='Unmodified repository auditor over all 728 authoritative records, with individual before/final record-rule dispositions. Core content audit covers 466; 262 Phillips records are deferred and never represented as newly fully reviewed.',findings=disp))
examSource=rd('exam-source.json');assert sha(Path(examSource['path']).read_bytes())==examSource['sha256'];exam=(W.parent/'.money-work/exam-text.txt').read_text('utf8')
def grams(x,n=12):
 t=re.findall(r'[a-z]+',x.lower());return {' '.join(t[i:i+n]) for i in range(len(t)-n+1)}
examGrams=grams(exam);originality=[]
for i,sp in s.items():
 oldText=b['records'][i]['q']+' '+' '.join(b['records'][i]['options'])+' '+b['records'][i]['feedback'];newText=sp['q']+' '+' '.join(sp['options'])+' '+sp['feedback'];hits=grams(newText)&examGrams;novel=hits-grams(oldText)
 assert not novel,(i,novel)
 originality.append(dict(id=i,new12WordExamOverlap=len(novel),inherited12WordOverlap=len(hits),humanComparison='Uses the existing library graph or selected mechanism with original offset definitions, inverse constraints, timing or evidence-identification reasoning. The exam supplied cognitive calibration rather than an item template.'))
wr('originality-validation.json',dict(examSource=examSource,method='Verified identical supplied exam bytes against the previously extracted and visually inspected final exam. Screened every revised stem, option and feedback for new 12-word overlap, and compared tasks qualitatively. Q1–8 and Q22–28/Q30 calibrate ordinary application, causal chains, numerical-graph integration and stabilization; Q29 and Q31–40 set monetary/Phillips boundaries.',limitation='Lexical overlap is a screening aid, not proof. Existing library assets are retained; no exam image, option pattern or scenario was imported. The Hard multiplier graph task adds an explicit total offset and separates reference-price demand from equilibrium GDP, rather than simply revaluing the exam example.',newImageAssets=0,examImagesCopied=0,items=originality))
wr('logical-validation.json',dict(scope=728,fullContentAudit=466,protectedPhillipsIntegrationAndStructureOnly=262,allScopedOptionsNormalizedDistinct=True,allScopedOneHashMatch=True,allScopedNonemptyStemFeedback=True,revisedStemsUniqueAcrossLibrary=True,revisedRecords=[dict(id=i,reason=sp['reason'],finalStem=sp['q'],correctOption=sp['options'][0],distractors=sp['options'][1:],review='Reviewed against explicit AD-AS assumptions, fiscal definitions, timing constraints or actual graph geometry. Alternatives represent omitted induced effects, wrong shift directions, axis-variable confusion, missing supply information, or unjustified equivalence of policy targets. Independent arithmetic accompanies all 24 revised quantitative records.') for i,sp in s.items()]))
members={}
for c,m in b['views'].items():
 for p,q in loc(m):members.setdefault(q['id'],[]).append(c+':'+p)
wr('pool-memberships.json',dict(allOrderedSourcePools={c:{p:[q['id'] for pp,q in loc(m) if pp==p] for p in dict(loc(m))} for c,m in b['views'].items()},multipleMemberships={i:x for i,x in members.items() if len(x)>1},sourceMembershipCount=sum(map(len,members.values())),uniqueCount=len(members),composedCounts=b['composedCounts'],trialGraphIds=b['routes']['trialGraph'],calculationNote='Twenty calculation-pool placements feed their existing canonical difficulty banks during composition; they are not 20 additional unique records beyond the 728. Raw and composed counts are deliberately both retained.'))
hard=[i for i,q in b['records'].items() if q.get('canonicalDifficulty')=='hard' and q['primaryConceptId'] in core and i not in s]
wr('retained-hard.json',[dict(id=i,concept=b['records'][i]['primaryConceptId'],objective=b['records'][i]['objective'],stem=b['records'][i]['q'],keyedOption=key(b['records'][i]),contentUnchanged=True,accessibilityOrPathChanged=any(c['id']==i for c in ch)) for i in hard])
acc['sharedMoneyAuditIds']=0;acc['sharedSavingAuditIds']=0;acc['uniqueAccessibilityRuntimeContractsCorrected']=len({x['runtimePath'] for x in rd('asset-accessibility-changes.json')});wr('accounting.json',acc)
def table(headers,rows):return ['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(str(x).replace('|','/').replace('\n',' ') for x in row)+' |' for row in rows]
def sect(n,title,*paras):return ['',f'## {n}. {title}','',*sum(([p,''] for p in paras),[])]
lines=['# AD-AS, Fiscal Policy & Stabilization — production assessment-quality audit','',
'The live preset contains **728 unique records**. The content audit covers **466 AD-AS/fiscal records**; the **262 selected Phillips records remain unchanged** for their dedicated audit. The existing bank has substantial ordinary exam reasoning at Hard. Targeted changes comprise **39 content revisions, 39 accessibility-only revisions and 42 path-only corrections**; **608 records are unchanged**. No records were added or removed.','',
'All **24 revised numerical questions** were independently recomputed. All **95 core graph questions** render and enlarge. The broader preset retains **42 preexisting Phillips graph-delivery failures**, explicitly deferred under the user’s restriction on Phillips edits. All ten modes retain composition readiness, which does not mean all full-preset graph delivery is defect-free.','',
'Only the canonical library and its registry/manifest sidecars change in production. Prior Money/Banking and Saving/Investment modules, Phillips definitions, adaptive metadata and all image bytes remain intact. Production edits are local; no commit, push, merge or deployment was performed.']
lines+=sect(1,'Exact live preset','Discovered in `build/faculty-build-composer/composer.js`: **`stabilization-policy` — “AD-AS, Fiscal Policy & Stabilization.”** This single current quick start corresponds to the working audit label. Its actual selected IDs, library definitions, composer core, registry/manifest, graph registrations, mode readiness and Concept Review mappings were inspected before authorship. The canonical BEFORE snapshot, overlap mask, scope boundary and objective findings preceded production edits.')
lines+=sect(2,'Exact selected concepts and views','All 14 selections are direct; there are no derived views or source parents. The current runtime selection, not chapter filenames or sourceOccurrences, defines the inventory. Full question objects and all provenance/skill fields appear in both inventories.')
lines+=table(['Direct concept ID','Unique records','Review depth','Objective IDs / source counts'],[(c,x['unique'],'Deferred Phillips integration/structure' if c in deferred else 'Full content',', '.join(f'{o}: {n}' for o,n in x['objectives'].items())) for c,x in b['byConcept'].items()])
lines+=sect(3,'Actual curricular boundary','The nine core selections include AD determinants, C/I/G/NX channels, price-level movement versus shifts, sticky wages/prices and misperceptions, SRAS/LRAS, potential output and gaps, demand/supply shocks and self-correction. Fiscal work includes purchases, taxes, transfers, spending and tax multipliers, MPC, crowding-out offsets, automatic stabilization, policy lags, uncertainty and demand-versus-supply tradeoffs.','Existing exchange-rate/foreign-income and import-leakage applications remain selected; they do not authorize a new Open Economy audit. Monetary mechanisms and loanable-funds mechanics are protected by prior work; supplied changes in investment or AD can enter integration questions. The five Phillips concepts are selected but explicitly deferred. No separate rules-versus-discretion or detailed policy-institution bank was inferred as a missing objective.')
lines+=sect(4,'Both prior-audit overlap masks','`money-banking-inflation` contains 818 previously audited records across 13 modules; `macro-saving-investment-budgets-debt` contains 268 across seven. This preset shares **zero authoritative IDs with either audit**. All 20 prior definitions match the completed prior snapshots and remain identical in the final library. Independent hashes also guard both prior artifact directories. No reserve/tool/loanable-funds machinery was rebuilt. See `overlap-mask.json` and `architecture-validation.json`.')
lines+=sect(5,'Before/after accounting','Every one of the 728 IDs has a mutually exclusive disposition in `record-actions.json`. Content changes take precedence over accessibility/path changes; accessibility-only means changed evidence without content; path-only means the image reference alone changed. The 47 image-reference corrections comprise 42 path-only and five accompanying content revisions.')
lines+=table(['Disposition','Count'],[('Unique before / after','728 / 728'),('Added / removed','0 / 0'),('Content revised',39),('Accessibility only',39),('Path only',42),('Unchanged',608),('Revised numerical records',24),('Shared runtime accessibility contracts corrected',8),('Affected concept-level asset metadata entries',14)])
lines+=['']+table(['Concept','Content','Accessibility only','Path only','Unchanged'],[(c,x['content-revised'],x['accessibility-only'],x['path-only'],x['unchanged']) for c,x in acc['byConcept'].items()])
lines+=sect(6,'Difficulty counts','All source and canonical difficulty values remain unchanged, including original capitalization and repair/bridge values. Canonical “unknown” represents the 103 support records without a canonical tier; this audit does not silently assign them a difficulty. Source distributions and the distinction between raw classifications and runtime banks are preserved.')
lines+=table(['Canonical difficulty','Before = after','Content revisions'],[(d,n,acc['byCanonicalDifficulty'][d]['content-revised']) for d,n in b['difficulty'].items()])
lines+=['']+table(['Source difficulty','Before = after'],b['sourceDifficulty'].items())
lines+=sect(7,'Types and pool counts',f"There are {sum(map(len,members.values()))} raw source memberships across 728 unique IDs. The generated ordinary banks contain 478 records, ordinary checkpoint tiers 108, Legendary checkpoints 39, repair 63 and bridge 40. Twenty calculation-pool records are already assigned into canonical ordinary banks; do not add them to the unique total. Integration/challenge pools and repair seeds are empty in this selection. Type names are preserved verbatim, including descriptive graph/calculation types on records whose graph is not required.")
lines+=table(['Composed pool','Before = after'],[(p,b['composedCounts'][p]) for p in ['easy','medium','hard','elite','legendary','easyBoss','mediumBoss','finalBoss','legendaryBoss','repair','repairSeed','bridge','calculation','integration','challengeTotal']])
lines+=['']+table(['Source type','Before = after','Content revisions'],[(t,n,acc['byType'][t]['content-revised']) for t,n in b['types'].items()])
lines+=sect(8,'Objective-by-objective findings','The following preserves all 40 concept/objective pairs and their BEFORE classifications. Source aliases such as LO35.4 and 35.4 remain distinct; where no descriptive label exists, the actual code is reported as the label. C is localized to multiplier/graph integration, not a claim that every Hard record in the concept is weak. G on deferred Phillips rows means no new integration defect found; it is expressly **not a fresh full-quality certification** of those objectives.','A coverage; B robustness; C calibration; D calculation/integration; E graph use; F upper-tier synthesis; G no material gap within the stated review depth.')
lines+=table(['Concept / objective — actual label','Records','BEFORE class','Depth / finding','Content changes'],[(x['concept']+' / '+x['objective']+' — '+x['label'],x['count'],','.join(x['classifications']),x['reviewDepth']+'. '+x['finding'],sum(z['action']=='content-revised' and z['concept']==x['concept'] and z['objective']==x['objective'] for z in actions)) for x in obj])
lines+=sect(9,'True coverage gaps','No materially absent selected objective was found in the nine core concepts. No A gap, new question ID or new graph family was justified. Absent curricular subjects are boundaries, not reasons to expand the audit. Phillips content quality beyond AD-AS integration remains deferred.')
lines+=sect(10,'Robustness gaps','Repetition is concentrated in upper-tier forms that identify a shift or perform one forward multiplication. These findings are chiefly F rather than absent-coverage B. The targeted revisions add inverse allocation, missing-evidence tests, policy timing and alternative stabilization targets. Similar introductory variants and some short upper-tier applications remain; this report does not claim uniform depth or empirical item discrimination.')
lines+=sect(11,'Calibration gaps',f'Hard already includes sticky-wage applications, opposed determinants, capacity diagnosis, graph equilibrium chains, fiscal-versus-tax effects and stabilization dilemmas. {len(hard)} core canonical-Hard records retain their content; the full list is in `retained-hard.json`. Eleven canonical-Hard records receive targeted changes, including checkpoints that carry that difficulty. Ordinary-bank Hard remains at 105 for the complete preset.','The local C gap was graph-based multiplier integration. Revised ECON-SP-HARD-228 requires multiplier arithmetic, subtraction of an explicitly total AD offset, and mapping the net quantity onto the graph. It retains its ID, skill, type, tier and pool. No question was moved down from Legendary to manufacture Hard coverage.')
lines+=sect(12,'Calculation and integration gaps','All 24 revised quantitative items were recomputed independently from final stems or original-image observations using rational arithmetic where applicable. `numerical-validation.json` includes the inputs, derivation, result and all four choices. Answer-hash verification was performed separately and was not used to establish the mathematics.','Core defects were mixing raw autonomous investment with total AD changes, equating horizontal AD distances with realized GDP gaps, and imposing exact arithmetic on hand-drawn curves. Revised tasks define model assumptions, distinguish direct/induced/offset effects and require needed evidence. No hidden equilibrium-price assumption is used to turn a horizontal demand shift into an equal GDP change.')
lines+=sect(13,'AD-AS mechanics findings','The retained bank correctly distinguishes a price-level movement along AD/SRAS from determinant shifts, short-run supply from productive capacity, and current equilibrium output from potential output. The new upper AD items separate gross opposing determinants from a net observed shift and identify missing SRAS evidence. Labor-force-plus-energy questions now acknowledge opposing SRAS effects rather than silently assuming that the energy shock dominates.')
lines+=sect(14,'Demand-shock findings','Negative demand shocks lower output and price in the standard upward-sloping-SRAS model; positive shocks raise both initially. Strong existing Hard questions already use the joint outcomes and adjustment chain. Fiscal offsets and graph-only demand diagrams now explicitly avoid claiming a complete equilibrium result without supply information.')
lines+=sect(15,'Supply-shock findings','Adverse SRAS shifts raise the price level and lower output; favorable shifts reverse that pattern. ECON-SP-HARD-212 previously began on AS2 while claiming a displayed supply increase ending on AS2. It now starts at AD1-AS1 and compares both endpoints after rightward demand and supply shifts. The observed price cancellation is specific to that drawing, not a universal equal-shifts rule.','Revised PG3-MEQ-L-004 compares restoring output with restoring the initial price after a persistent supply disruption. The two targets imply different demand policies and output costs. Fiscal expansion does not shift SRAS back or eliminate the underlying disruption.')
lines+=sect(16,'Short-run to long-run adjustment','Existing Hard chains already connect a demand shock, output gap, wage/expectation pressure, SRAS movement and return toward potential. Two prompts now explicitly keep the demand change in place instead of calling it temporary while retaining a permanent post-shock AD position.','Elite 314/315 distinguish the common output target from opposite price effects of demand policy versus wage adjustment. Legendary 9003/9004 trace delayed policy after supply-side self-correction, showing how a previously suitable full remedy can create a new gap. LRAS remains a capacity anchor, not an automatic response to temporary actual GDP changes.')
lines+=sect(17,'Fiscal-policy findings','The purchases-versus-taxes/transfers distinction is sound and retained: purchases enter expenditure directly, while taxes/transfers affect disposable income and first-round consumption. Revised higher-tier tasks invert a heterogeneous-MPC tax-credit allocation, design a purchases cut while expanding transfers, and compare payment timing with MPC. Existing automatic-stabilizer questions retain the distinction between changes triggered by conditions and new discretionary legislation.')
lines+=sect(18,'Multiplier findings','The simple spending multiplier remains 1/(1−MPC), under the stated simplified model. Ten targeted items now explicitly use total AD offsets or reference-price distances so an offset is not inadvertently omitted from, or subjected twice to, multiplier rounds. Other corrected items retain their valid numerical key under clarified assumptions.','Examples: ECON-SP-HARD-228 gives gross AD 80, offset 20, net 60 and AD2 at 560. PM2D2-FISCAD-L-001 allocates 72/48 to obtain first-round consumption 84. P52A-FISCAD-L-005 requires a purchases cut of 36 while transfers rise 30. These are instructional AD calculations, not guaranteed realized GDP responses.')
lines+=sect(19,'Crowding-out integration','Crowding out is used as a limitation on fiscal expansion. LG-Q-4014 deliberately treats investment changes as autonomous: (50 + 60 − 40) × 4 = 280, leaving a horizontal AD shortfall of 220. The previous answer of 100 omitted the induced spending lost from the stated raw investment reduction. Where a supplied offset is already a total AD amount, the revision says so and subtracts it once.','Elite 320 now asks for the extra condition needed to end strictly between AD2 and AD3: the positive total offset must be smaller than the incremental AD2-to-AD3 distance. “Partial crowding out” alone does not establish that location. The separate loanable-funds question bank is untouched.')
lines+=sect(20,'Stabilization findings','Existing Hard work covers active-policy rationale, automatic stabilization, timing risk and adverse-supply tradeoffs. Revised PM2D2-STAB-L-002 combines a revised target with unavoidable disbursement: one third of authorized purchases already meets the new AD target, so the remaining 50 must be cancelled. New graph sequences likewise evaluate policy when it arrives, after wages may have adjusted. No universal preference for stimulus, contraction or passive adjustment is asserted without a target.')
lines+=sect(21,'Graph-use findings','All 27 selected asset registrations and all 20 distinct image files were visually inspected, including the protected Phillips images for integration/geometry only. The selected bank retains 161 graph-linked questions and 72 Trial-by-Graph eligible records (12 Easy, 24 Medium, 12 Hard, 12 Elite, 12 Legendary). No graph eligibility flag or image byte changed.','All 95 core graph records render, provide descriptions and open enlarged images in a locally generated quest. Of 66 protected Phillips graph records, 24 pass and 42 retain unresolved legacy references. `graph-validation.json` lists every result; `phillips-deferred-followup.json` identifies the exact deferred IDs. Correct registered image bytes alone do not establish working inline references.')
lines+=sect(22,'Upper-tier synthesis findings','Selected improvements require inverse household allocation, a fiscal package under a transfer constraint, payment-timing evidence, net-versus-gross determinant identification, temporary-versus-permanent supply diagnosis, capacity/threshold calculation, output-versus-price stabilization and delayed policy after self-correction. These deepen reasoning within the selected Principles models.','Some retained upper items remain direct: ECON-SP-ELITE-308/309, PG3-MEQ-EL-002 and PG3-AS-EL-002 are short graph applications; several Legendary offset-sequence items remain heavily scaffolded even after their assumptions were corrected. This limitation is disclosed rather than concealed by retagging or wholesale rewriting.')
examples={'P52A-AD-H-001':'Opposing consumption and investment determinants; net AD requires magnitudes.','P52A-AS-H-001':'Oil costs versus productivity; distinguish opposing SRAS effects.','P52A-AS-H-004':'Apply contracted nominal wages to unexpected product-price changes.','PM2D1-LRADJ-H-001':'Check permanent capital loss before assuming return to the old potential-output level.','PG3-MEQ-H-001':'Trace initial equilibrium, demand expansion and later SRAS adjustment.','ECON-SP-HARD-220':'Explain the output/price tradeoff of stimulus after an adverse supply shock.','P52A-FISCAD-H-005':'Compare opposing purchases and tax changes without assuming equal effects.','ECON-SP-HARD-233':'Diagnose the demand risk of spending cuts during a recession.'}
assert all(i in hard for i in examples)
lines+=sect(23,'Strong existing Hard questions retained',f'{len(hard)} core canonical-Hard records retain stems, choices, keys and feedback; graph examples can receive evidence/path corrections. These examples illustrate the existing foundation. See the complete list in `retained-hard.json`.')
lines+=table(['ID','Reason to retain'],examples.items())
lines+=sect(24,'Specific revised examples and reasons','All 39 content revisions appear below. `changes.json` preserves the exact changed fields before and after, and `record-actions.json` separately accounts for every unchanged, evidence-only or path-only record.')
lines+=table(['ID','Concept / objective','Canonical difficulty','Reason'],[(i,b['records'][i]['primaryConceptId']+' / '+b['records'][i]['objective'],b['records'][i].get('canonicalDifficulty','unknown'),x['reason']) for i,x in s.items()])
lines+=sect(25,'Economic and numerical defects corrected','LG-Q-4014 now multiplies net autonomous spending, including the investment loss. Other offset clarifications explicitly state total-AD units; gap questions define horizontal demand shortfalls rather than assuming a fixed-price realized output response. The impossible AS2-to-AS2 increase in Hard 212 is repaired. Labor-force/energy items no longer assert an unsupported net SRAS direction.','The capital/productivity item supplies a multiplicative capacity relationship: 0.95 × 1.08 = 1.026, while restoration requires about 5.26 percent productivity growth. It is a conditional capacity exercise, not a claim that every production function has that form. Demand-shock persistence is clarified. Four raster-reading tasks now ask for the closest offered estimate; their original keys remain closest, so no reversed graph key is alleged.')
lines+=sect(26,'Accessibility and path defects corrected','Eight shared runtime contracts, repeated in 14 concept-level asset metadata entries, are corrected. AD/AS raster contracts distinguish approximate readings from exact coordinates. LRAS/ADAS contracts retain axes, labels, intersections and guides while removing the assessed shock or self-correction conclusion. Valid detailed symbolic and monetary graph descriptions are preserved.','There are 39 accessibility-only records and 47 corrected image references, of which 42 are path-only. A further five path corrections accompany content revisions. Source/runtime asset registrations and image bytes remain unchanged; references are normalized to existing registered assets. The 42 protected Phillips inline failures remain explicitly deferred and are not counted as repaired.')
lines+=sect(27,'Final-exam calibration interpretation','The supplied ECO 2251 Final Exam was used as cognitive/style calibration after verifying its SHA-256. Q1–8 support ordinary short/long-run distinctions, joint shock outcomes, self-adjustment, sticky wages and AD determinants. Q22–28 and Q30 support policy diagnosis, crowding-out limitations and multiplier-plus-graph reasoning at normal exam difficulty. Q29 does not authorize renewed monetary-mechanics work; Q31–40 remain the later Phillips boundary.','No question, scenario, numerical package, answer pattern or image was imported from the exam. Existing library assets were retained. Every revised stem, option and feedback passed a new 12-word lexical-overlap screen, supplemented by task comparison. That screen is not treated as proof of originality; the revised Hard integration task adds a total offset and evidence limitation rather than merely changing the exam numbers.')
lines+=sect(28,'Mode readiness','All ten modes retain identical composition readiness and counts. Composer reports no errors and verifies one answer-hash match for each of the 728 records. Fading Fortune and Risk & Reward each retain 478 eligible records. These checks establish composition eligibility, not complete gameplay or defect-free delivery of the protected Phillips content.')
lines+=table(['Mode','Before / after composition status'],[(x['label'],'Ready / ready') for x in v['modeValidation']['modes']])
lines+=['','The local Edge smoke test verifies all 120 changed payloads, the displayed revised Legendary item and every graph record. All core graphs pass; the 42 protected failures are retained in the report. External requests were blocked. This is not an all-mode playthrough or telemetry test.']
lines+=sect(29,'Concept Review and routing integrity','All 14 selected Concept Review routes and local review-PDF byte hashes remain unchanged. IDs, source/canonical difficulty, objectives, skills, tags, subtopics, sourceChapter, sourceOccurrences/sourceHash, aliases, ordered pools, calculation placement, repair/bridge mappings, checkpoints, retest-related metadata and eligibility are preserved. All 140 concept definitions outside the nine-core content audit are identical, including the 135 nonselected definitions and five selected Phillips definitions.')
lines+=table(['Concept','Review code','Runtime route'],[(c,x['primaryReviewCode'],', '.join(y['path'] for y in x['assets'])) for c,x in b['conceptReview']['runtimeIndex']['concepts'].items()])
lines+=['',f"The review resolver retains {len(b['conceptReview']['warnings'])} preexisting global diagnostics, recorded exactly in `architecture-validation.json`; they are not new missing selected review mappings. Remote endpoints were not fetched. Engine behavior, UI, telemetry, Workers and access systems remain untouched."]
lines+=sect(30,'Remaining warnings and review flags',f"The unmodified auditor reports BEFORE **{before['counts']['errors']} errors / {before['counts']['warnings']} warnings / {before['counts']['reviews']} reviews**, AFTER **{after['counts']['errors']} errors / {after['counts']['warnings']} warnings / {after['counts']['reviews']} reviews**. Individual dispositions cover every original/final record-rule pair in `quality-dispositions.json`, including deferred Phillips flags. Counts are not a zero-warning target.",f"Within the 466 core records, final flags are {flagCounts(after)}. Within the 262 protected Phillips records, final flags are {flagCounts(after,True)}. The 42 insufficient-accessibility flags belong to the protected failures; the core has none.")
lines+=table(['Severity','Rule','Final full-preset count'],[(x['severity'],x['rule'],x['count']) for x in after['ruleCounts']])
lines+=['','Two equilibrium-evidence warnings are macro-label regex false positives: the checker expects D/S labels rather than the actual AD/AS labels. Two curve-label reviews mistake scalar MPC for a marginal-private-cost curve. The revised Hard multiplier/graph task also receives a reasoning-cue false positive. These are documented without changing the auditor or printed curve labels.','Other flags are genuine residual quality limitations: 13 long-key cues, absolute distractors, repeated feedback, terse graph prompts and some shallow upper-tier applications. The reversed-direction Medium/Hard stem pair is token-similar but asks opposite transitions. Approved main/Repair reuse and conservative graph eligibility remain intact.']
lines+=sect(31,'Remaining limitations','This completes the authorized nine-concept content audit and full-preset structural inventory. It does not complete the later Phillips content audit. The 42 protected image failures are known preexisting delivery defects that remain unresolved under the explicit restriction on Phillips edits. The complete preset must not be described as graph-delivery-clean.','Some valid records retain weak distractors, repeated feedback and direct upper-tier tasks; no empirical student-performance or item-discrimination study was performed. Approximate raster readings are suitable only for the offered nearest estimates. Models are simplified and their assumptions matter; no multiplier result guarantees equal realized GDP growth.','Validation is local: all-mode composition, all scoped answer integrity, independent revised arithmetic, unchanged architecture and core graph rendering/enlargement. It does not verify every gameplay branch, remote CDN state or telemetry session. No production deployment, commit, push or merge was performed.')
lines+=sect(32,'Final semantic library hash',f'**`{semantic}`**',f'BEFORE: `{old["librarySha256"]}`. Python independently recomputes the sorted semantic JSON SHA-256 with the two self-referential hash fields omitted; library, registry and manifest agree. The only production files changed are `build/faculty-build-composer/data/composer_library.js`, `composer_registry.json` and `composer_library_manifest.json`. The sidecars carry the required hash and asset-accessibility synchronization.')
(W/'FINAL_REPORT.md').write_text('\n'.join(lines)+'\n','utf8')
files=['FINAL_REPORT.md','BEFORE.md','OBJECTIVE_FINDINGS_BEFORE.md','inventory-before.json','inventory-after.json','summary-before.json','objective-findings-before.json','scope-boundary.json','overlap-mask.json','audit-projection-provenance.json','exam-source.json','record-actions.json','accounting.json','changes.json','revisions.json','asset-accessibility-changes.json','accessibility-spec.json','accessibility-inspection.json','quality-before.json','quality-before.md','quality-after.json','quality-after.md','quality-dispositions.json','numerical-validation.json','graph-validation.json','phillips-deferred-followup.json','architecture-validation.json','semantic-validation.json','originality-validation.json','logical-validation.json','pool-memberships.json','retained-hard.json','validation.json','browser-validation.json','browser-smoke.png','recipe.json','concepts.json','sources.json','stage.mjs','verify.py','browser.cjs','finish.py','author.py','accessibility.py','findings.py']
for p in files:assert (W/p).is_file(),p
wr('deliverables.json',files+['deliverables.json'])
print(json.dumps(dict(reportSections=len(re.findall(r'^## \d+\.',(W/'FINAL_REPORT.md').read_text('utf8'),re.M)),artifacts=len(files)+1,coreHardRetained=len(hard),quality=after['counts'],coreQuality=flagCounts(after),deferredQuality=flagCounts(after,True),individualFlagDispositions=len(disp),independentHash=semantic,coreGraphCount=len(coreGraphs),protectedGraphFailures=len(failed))))
