import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';
const repo=path.resolve(process.argv[2]||'/mnt/data/phase_M4_work'),composer=path.join(repo,'faculty-build-composer'),dataDir=path.join(composer,'data');
const libPath=path.join(dataDir,'composer_library.js'),regPath=path.join(dataDir,'composer_registry.json'),manPath=path.join(dataDir,'composer_library_manifest.json');
const PHASE='phaseM4-final-macro-release-closure-v1',STAMP=new Date().toISOString();const sha=b=>crypto.createHash('sha256').update(b).digest('hex');const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const sb={window:{}};vm.createContext(sb);vm.runInContext(fs.readFileSync(libPath,'utf8'),sb);const library=sb.window.MQ_COMPOSER_LIBRARY;const registry=JSON.parse(fs.readFileSync(regPath,'utf8')),manifest=JSON.parse(fs.readFileSync(manPath,'utf8'));
if(!library.libraryVersion.endsWith(PHASE))throw new Error('M4 version stamp missing before accessibility repair');
const concepts=['quantity-theory-of-money','monetary-neutrality','fisher-effect','inflation-costs','inflation-tax-and-deflation'];
const text={imageAlt:'Money graph with downward-sloping MD, vertical MS1 and MS2, and labeled points a, b, and c.',graphDescription:'The horizontal axis is Q_M and the vertical axis is V_M. MD slopes downward from upper left to lower right. MS1 is a vertical line at Q_M = 2,500 and MS2 is a vertical line at Q_M = 5,000. Point a lies where MS1 meets MD at V_M = 2. Point b lies where MS2 meets MD at V_M = 1.5. Point c lies on MD at Q_M = 7,500 and V_M = 1. Dashed guides mark the labeled V_M and Q_M values.'};
const changes=[];
for(const cid of concepts){const rec=(library.concepts[cid].assetMetadata||[]).find(a=>a.filename==='moneys_moneyd.webp');if(!rec)throw new Error(`Missing asset metadata ${cid}`);const before={imageAlt:rec.imageAlt||null,graphDescription:rec.graphDescription||null};rec.imageAlt=text.imageAlt;rec.graphDescription=text.graphDescription;changes.push({conceptId:cid,filename:rec.filename,before,after:text});}
for(const rec of manifest.assets||[]){if(concepts.includes(rec.conceptId)&&rec.filename==='moneys_moneyd.webp'){rec.imageAlt=text.imageAlt;rec.graphDescription=text.graphDescription;}}
library.generatedAt=STAMP;Object.assign(library.registry,{generatedAt:STAMP,libraryVersion:library.libraryVersion,canonicalQuestionCount:library.canonicalQuestionCount});Object.assign(registry,{generatedAt:STAMP,libraryVersion:library.libraryVersion,canonicalQuestionCount:library.canonicalQuestionCount});delete library.librarySha256;library.librarySha256=sha(JSON.stringify(stable(library)));registry.librarySha256=library.librarySha256;Object.assign(manifest,{generatedAt:STAMP,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,canonicalQuestionCount:library.canonicalQuestionCount});
fs.writeFileSync(libPath,`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(library)};\n`);fs.writeFileSync(regPath,JSON.stringify(registry,null,2)+'\n');fs.writeFileSync(manPath,JSON.stringify(manifest,null,2)+'\n');
const provPath=path.join(composer,`${PHASE}.json`),changePath=path.join(composer,`${PHASE}_questions.json`);const prov=JSON.parse(fs.readFileSync(provPath,'utf8')),chg=JSON.parse(fs.readFileSync(changePath,'utf8'));
prov.generatedAt=STAMP;prov.after.librarySha256=library.librarySha256;prov.assetAccessibility={metadataUpdatedCopies:5,filename:'moneys_moneyd.webp',conceptIds:concepts,newGraphAssets:0,imagePixelsChanged:false};prov.changeControl.assetMetadataRepairs=5;
chg.generatedAt=STAMP;chg.summary.assetMetadataRepairs=5;chg.summary.newGraphAssets=0;chg.assetChanges=changes;
fs.writeFileSync(provPath,JSON.stringify(prov,null,2)+'\n');fs.writeFileSync(changePath,JSON.stringify(chg,null,2)+'\n');
console.log(JSON.stringify({phase:PHASE,assetMetadataRepairs:changes.length,librarySha256:library.librarySha256,changes},null,2));
