import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const output=process.env.MQ_EVIDENCE_DIR||path.join(root,'validation_artifacts/telemetry_data_dictionary');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({channel:'msedge',headless:true});const results=[];
try{const context=await browser.newContext({reducedMotion:'reduce'});await context.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const width of [1440,390]){await page.setViewportSize({width,height:1000});await page.goto(origin+'/how-to/telemetry-data-dictionary/');assert.equal(await page.locator('[data-field]').count(),75);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Page overflow');assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('thead th:not([scope])').count(),0);await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').innerText(),'Skip to main content');await page.keyboard.press('Enter');await page.locator('#field-search').focus();await page.keyboard.type('tabSwitchCount');assert.equal(await page.locator('[data-field]:visible').count(),1);await page.locator('#field-search').fill('zznomatch');assert.equal(await page.locator('[data-field]:visible').count(),0);assert.match(await page.locator('#field-status').innerText(),/No matching/);await page.locator('#field-search').fill('');assert.equal(await page.locator('[data-field]:visible').count(),75);if(width===390){await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');}await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:path.join(output,`dictionary-${width}.png`),fullPage:false});await page.locator('#visibility-and-focus').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,`fields-${width}.png`),fullPage:false});results.push({viewport:width,layout:'PASS',search:'PASS',keyboard:'PASS',tableHeaders:'PASS'});}
const files=JSON.parse(fs.readFileSync(path.join(root,'audit_tools/telemetry_data_dictionary/navigation-files.json')));for(const file of files){await page.goto(origin+'/'+file.replace(/index.html$/,''));assert.equal(await page.locator('nav a[href="/how-to/"]').first().innerText(),'Faculty Resources');assert.equal(await page.locator('nav').filter({hasText:/How To/}).count(),0);for(const a of await page.locator('nav a[href^="/"]').evaluateAll(as=>as.map(a=>a.getAttribute('href')))){const response=await context.request.get(origin+a);assert(response.ok(),`${file}: ${a}`);}results.push({navigation:file,status:'PASS'});}
await page.goto(origin+'/how-to/');assert(await page.locator('a[href="/how-to/telemetry-data-dictionary/"]').count());for(const id of ['adaptive-engine','answer-hardening','prepare','repository','pages','lms'])assert.equal(await page.locator('#'+id).count(),1);
await context.setOffline(false);const nojs=await browser.newContext({javaScriptEnabled:false});const p=await nojs.newPage();await p.goto(origin+'/how-to/telemetry-data-dictionary/');assert.equal(await p.locator('[data-field]').count(),75);await nojs.close();assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({status:'PASS',noJavaScript:'PASS',preservedHelpAnchors:'PASS',errors,results},null,2));console.log(JSON.stringify({status:'PASS',checks:results.length,noJavaScript:'PASS',errors}));
}finally{await browser.close();server.close();}

