import fs from 'node:fs';import path from 'node:path';import https from 'node:https';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
import {api,query,state,save,name,out} from './control.mjs';
import {generateCapability,hashCapability} from '../../../server/anonymous-telemetry-poc/capabilities.mjs';
import {PHASE} from '../../../server/anonymous-telemetry-poc/telemetry-core.mjs';
const deployment=fs.readFileSync(path.join(out,'deploy.log'),'utf8');
const base=deployment.match(/https:\/\/masteryquests-telemetry-http-staging\.[a-z0-9-]+\.workers\.dev/)?.[0];
const version=deployment.match(/Current Version ID: ([a-f0-9-]+)/)?.[1];if(!base||!version)throw Error('Staging deployment identity missing');
save({...state(),workerDeployed:true,url:base,version});
const origin='https://masteryquests.org',url=base+'/v1/events';
const raw=generateCapability(),hash=await hashCapability(raw),capId=crypto.randomUUID();
const scope={gameId:'faculty-composer',buildId:'composer-'+createHash('sha256').update(crypto.randomUUID()).digest('hex'),buildVersion:createHash('sha256').update(crypto.randomUUID()).digest('hex'),schemaVersion:3};
const secrets=[raw,hash];const clean=s=>secrets.reduce((text,value)=>text.replaceAll(value,'[REDACTED]'),String(s));
const tables=['telemetry_events','telemetry_runs','telemetry_ingest_batches','telemetry_rate_limits','telemetry_build_policies','telemetry_build_capabilities','telemetry_scope_windows'];
async function snapshot(){const data=await query(tables.map(t=>'SELECT * FROM '+t+' ORDER BY rowid').join(';'));return{hash:createHash('sha256').update(JSON.stringify(data.map(x=>x.results))).digest('hex'),counts:Object.fromEntries(tables.map((t,i)=>[t,data[i].results.length]))};}
const beforeSeed=await snapshot();
await query('INSERT INTO telemetry_build_policies(game_id,build_id,created_at) VALUES(?,?,unixepoch())',[scope.gameId,scope.buildId]);
await query('INSERT INTO telemetry_build_capabilities(capability_id,capability_hash,game_id,build_id,build_version,schema_version,issued_at,expires_at,issuance_request_id,activation_digest) VALUES(?,?,?,?,?,3,unixepoch(),unixepoch()+7200,?,?)',[capId,hash,scope.gameId,scope.buildId,scope.buildVersion,crypto.randomUUID(),'0'.repeat(64)]);
const headers={'content-type':'application/json',origin,'x-mq-ingest-token':raw};
const records=[],groups=[],health=[],runtimeLogs=[],tailMetadata={events:0,credentialMatches:0,applicationLogCredentialMatches:0,exceptions:0};
let socket,browser,tailId;
function event(multibyte=false){return {...scope,eventId:crypto.randomUUID(),runId:crypto.randomUUID(),anonymousClientId:crypto.randomUUID(),phase:PHASE,mode:'standard',eventType:'run_started',sequenceNumber:1,eventTimestamp:new Date().toISOString(),synthetic:true,contractID:'mq-measurement/1',manifestID:null,provenanceStatus:'unresolved',artifact:multibyte?'é':'x'};}
function payload(bytes,multi){const text=bytes===100?JSON.stringify({events:[]}):JSON.stringify({phase:PHASE,events:[event(multi)]});if(bytes===100&&multi){const x=JSON.stringify({events:[],note:'é'});return x+' '.repeat(bytes-Buffer.byteLength(x));}return text+' '.repeat(bytes-Buffer.byteLength(text));}
async function valid(label){const e=event(),response=await fetch(url,{method:'POST',headers,body:JSON.stringify({phase:PHASE,events:[e]}),redirect:'error',signal:AbortSignal.timeout(20000)});assert.equal(response.status,202);const json=await response.json();assert.equal(json.accepted,1);const rows=await query('SELECT e.event_id,b.capability_id FROM telemetry_events e JOIN telemetry_ingest_batches b ON b.batch_id=? WHERE e.event_id=?',[json.batchId,e.eventId]);assert.equal(rows[0].results.length,1);assert.equal(rows[0].results[0].capability_id,capId);health.push({label,status:202,accepted:1,attributionVerified:true});}
async function nodeRequest(text,framing,slow=false){return new Promise(resolve=>{
 const row={status:null,readableBody:false},chunks=[];let settled=false,timer;
 const finish=()=>{if(settled)return;settled=true;clearTimeout(timer);row.elapsedMs=Date.now()-start;resolve(row);};const start=Date.now();
 const req=https.request(url,{method:'POST',agent:false,headers:{...headers,connection:'close',...(framing==='declared'?{'content-length':Buffer.byteLength(text)}:framing==='false-small'?{'content-length':'1'}:framing==='false-large'?{'content-length':Buffer.byteLength(text)+1}:{})}},res=>{
  row.status=res.statusCode;row.statusLine='HTTP/'+res.httpVersion+' '+res.statusCode+' '+res.statusMessage;row.headers=res.headers;
  res.on('data',chunk=>{if(chunks.reduce((n,x)=>n+x.length,0)<32768)chunks.push(chunk);});res.on('end',()=>{row.body=Buffer.concat(chunks).toString();row.readableBody=true;row.responseComplete=res.complete;});res.on('error',e=>{row.exception=clean(e.message);row.code=e.code;});res.on('close',()=>{row.responseComplete=res.complete;finish();});
 });req.on('socket',s=>s.on('close',bad=>{row.socketClosed=true;row.socketHadError=bad;finish();}));req.on('error',e=>{row.exception=clean(e.message);row.code=e.code;finish();});timer=setTimeout(()=>{row.timeout=true;req.destroy(Error('controlled upload deadline'));finish();},10000);
 if(slow){const bytes=Buffer.from(text);let offset=0;const send=()=>{if(settled||req.destroyed)return;if(offset>=bytes.length){req.end();return;}const end=Math.min(offset+4096,bytes.length);req.write(bytes.subarray(offset,end));offset=end;setTimeout(send,10);};send();}else{req.write(text);req.end();}
 });}
async function undiciRequest(text,framing){const row={status:null,readableBody:false};try{const upload=framing==='chunked'?new ReadableStream({start(c){c.enqueue(new TextEncoder().encode(text));c.close();}}):text;const response=await fetch(url,{method:'POST',headers:{...headers,...(framing==='false-small'?{'content-length':'1'}:framing==='false-large'?{'content-length':Buffer.byteLength(text)+1}:{})},body:upload,...(framing==='chunked'?{duplex:'half'}:{}),signal:AbortSignal.timeout(10000),redirect:'error'});row.status=response.status;row.headers=Object.fromEntries(response.headers);row.body=await response.text();row.readableBody=true;}catch(e){row.exception=clean(e.message);row.code=e.code||e.cause?.code;}return row;}
function validate(row,bytes,client){if(bytes<=131072){assert.equal(row.status,bytes===100?400:202);assert(row.readableBody);return;}assert.equal(row.status,413);assert(row.readableBody);assert.equal(JSON.parse(row.body).error,'request_too_large');assert(row.headers['content-type'].startsWith('application/json'));assert.equal(row.headers['cache-control'],'no-store');if(client!=='edge'){assert.equal(row.headers['access-control-allow-origin'],origin);assert.equal(row.headers.vary,'Origin');assert(!row.headers['access-control-allow-credentials']);}}
function persist(){const result={worker:state(),origin,beforeSeed,records,groups,health,runtimeLogs,tailMetadata,capabilityId:capId,rawCapabilityPersisted:false,canonicalSourceChanged:false};const text=JSON.stringify(result,null,2);if(secrets.some(s=>text.includes(s)))throw Error('Evidence contains credential');fs.writeFileSync(path.join(out,'deployed-results.json'),text+'\n');}
try{
 const tail=await api('/workers/scripts/'+name+'/tails','POST',{});tailId=tail.id;save({...state(),tailId});socket=new WebSocket(tail.url,'trace-v1');socket.binaryType='arraybuffer';
 socket.addEventListener('message',message=>{const text=typeof message.data==='string'?message.data:new TextDecoder().decode(message.data);let value;try{value=JSON.parse(text);}catch{return;}tailMetadata.events++;if(secrets.some(s=>text.includes(s)))tailMetadata.credentialMatches++;const logs=JSON.stringify({logs:value.logs,exceptions:value.exceptions});if(secrets.some(s=>logs.includes(s)))tailMetadata.applicationLogCredentialMatches++;tailMetadata.exceptions+=(value.exceptions||[]).length;runtimeLogs.push({outcome:value.outcome,logs:JSON.parse(clean(JSON.stringify(value.logs||[]))),exceptions:JSON.parse(clean(JSON.stringify(value.exceptions||[])))});});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Tail connection deadline')),15000);socket.addEventListener('open',()=>{clearTimeout(timer);socket.send(JSON.stringify({debug:false}));resolve();},{once:true});socket.addEventListener('error',()=>{clearTimeout(timer);reject(Error('Tail connection failed'));},{once:true});});
 const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE);browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();await context.route('**/*',route=>{const target=new URL(route.request().url());if(target.origin===origin)return route.fulfill({contentType:'text/html',body:'<!doctype html><title>Synthetic staging HTTP validation</title>'});if(target.origin===base)return route.continue();return route.abort();});const page=await context.newPage(),browserNetwork=[],pageErrors=[];page.on('pageerror',e=>pageErrors.push(clean(e.message)));page.on('response',r=>{if(r.url()===url)browserNetwork.push({status:r.status(),headers:r.headers()});});await page.goto(origin+'/staging-fixture');
 await valid('initial');
 for(const client of ['node:https','undici','edge'])for(const framing of client==='edge'?['browser-auto']:['declared','chunked'])for(const multi of [false,true])for(const bytes of [100,131072,131073,524288,2097152]){
  const before=await snapshot(),repetitions=bytes>131072?10:1,start=records.length;
  for(let trial=0;trial<repetitions;trial++){
   const text=payload(bytes,multi);let row;
   if(client==='node:https')row=await nodeRequest(text,framing);
   else if(client==='undici')row=await undiciRequest(text,framing);
   else row=await page.evaluate(async({url,text,token})=>{const row={status:null,readableBody:false};try{const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-mq-ingest-token':token},body:text,signal:AbortSignal.timeout(10000),redirect:'error'});row.status=response.status;row.headers=Object.fromEntries(response.headers);row.body=await response.text();row.readableBody=true;}catch(e){row.exception=e.message;}return row;},{url,text,token:raw});
   row={client,framing,multibyte:multi,bytes,trial,...row};try{validate(row,bytes,client);row.statusCheck='PASS';}catch(e){row.statusCheck='FAIL';row.assertion=clean(e.message);}records.push(row);
  }
  const after=await snapshot(),reject=bytes!==131072;const group={client,framing,multibyte:multi,bytes,repetitions,before,after,noWrites:reject?before.hash===after.hash:null,failures:records.slice(start).filter(x=>x.statusCheck==='FAIL').length};groups.push(group);persist();if(reject)assert.equal(after.hash,before.hash);await valid(client+'/'+framing+'/'+bytes+'/'+multi);console.log(JSON.stringify({client,framing,bytes,multibyte:multi,failures:group.failures,noWrites:group.noWrites}));
 }
 for(const framing of ['chunked','false-small','false-large']){const before=await snapshot();const row=await nodeRequest(payload(2097152,false),framing,framing==='chunked');assert.notEqual(row.status,202);const after=await snapshot();assert.equal(before.hash,after.hash);records.push({client:'node:https',special:framing==='chunked'?'slow-bounded-upload':'malformed-content-length',framing,...row,noWrites:true,before,after});await valid('after '+framing);persist();}
 for(const framing of ['false-small','false-large']){const before=await snapshot(),row=await undiciRequest(payload(131073,false),framing),after=await snapshot();assert.notEqual(row.status,202);assert.equal(before.hash,after.hash);records.push({client:'undici',special:'malformed-content-length',framing,...row,noWrites:true,before,after});await valid('after undici '+framing);persist();}
 await new Promise(r=>setTimeout(r,3000));
 for(const row of browserNetwork.filter(x=>x.status===413)){assert.equal(row.headers['access-control-allow-origin'],origin);assert.equal(row.headers.vary,'Origin');assert.equal(row.headers['cache-control'],'no-store');assert(!row.headers['access-control-allow-credentials']);}
 assert.equal(pageErrors.length,0);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({version:browser.version(),originSimulation:'Document fulfilled in memory at approved origin; actual HTTPS staging network with normal CORS; all other network blocked',network:browserNetwork,pageErrors},null,2));
 const after=await snapshot();fs.writeFileSync(path.join(out,'row-counts.json'),JSON.stringify({before:beforeSeed,after},null,2));persist();console.log(JSON.stringify({completed:true,ordinaryFailures:records.filter(x=>x.statusCheck==='FAIL').length,tailMetadata,health:health.length}));
}catch(e){persist();throw Error(clean(e.message));}
finally{if(browser)await browser.close();if(socket)socket.close();if(tailId){await api(`/workers/scripts/${name}/tails/${tailId}`,'DELETE');save({...state(),tailClosed:true});}}
// Evidence and tail teardown are complete. Do not retain native upload/socket handles.
// A strict metadata-redaction failure is a failed staging gate even when HTTP passes.
process.exit(records.some(row=>row.statusCheck==='FAIL')||tailMetadata.credentialMatches?1:0);
