import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {createWorkerHarness} from '../managerial_classroom/worker-harness.mjs';import {parseCSV,validateCSV} from './validate.mjs';
const require=createRequire(import.meta.url),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=process.env.MQ_EVIDENCE_DIR||path.join(root,'validation_artifacts/telemetry_contract_hardening/browser');fs.mkdirSync(out,{recursive:true});
const core=require(path.join(root,'build/faculty-build-composer/composer-core.js')),helpers=require(path.join(root,'build/faculty-build-composer/tests/composer-test-helpers.js'));
const built=await helpers.buildFacultyGame(core,{schemaVersion:core.RECIPE_SCHEMA_VERSION,title:'Synthetic Contract Browser',slug:'synthetic-contract-browser',supportedModes:['standard','exam'],selectedConceptIds:['aggregate-demand'],checkpointFocus:{checkpointOne:null,checkpointTwo:null,finalCheckpoint:null}},{library:helpers.loadComposerLibrary(),template:fs.readFileSync(path.join(root,'build/faculty-build-composer/template/mastery-quests-faculty-template-composer-ready.html'),'utf8')});
for(const asset of built.composition.assets){const file=path.resolve(root,'build/faculty-build-composer',asset.sourceUrl);if(!file.startsWith(path.join(root,'build/faculty-build-composer')+path.sep))throw Error('Asset outside Composer');const bytes=fs.readFileSync(file);built.composition.embeddedQuestionAssets ||= {};built.composition.embeddedQuestionAssets[asset.runtimePath]='data:image/'+(path.extname(file)==='.svg'?'svg+xml':path.extname(file).slice(1))+';base64,'+bytes.toString('base64');}
built.html=core.buildHtml(built.template,built.composition,built.config,built.metadata);
const harness=createWorkerHarness(root),requests=[],errors=[],results=[];
const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/anonymous-telemetry-poc/')){requests.push(req.url);return harness.serve(req,res);}if(req.url.startsWith('/synthetic.html')){res.setHeader('content-type','text/html');res.end(built.html);return;}try{let p=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!p.startsWith(root+path.sep))throw Error('path');if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('content-type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml'})[path.extname(p)]||'application/octet-stream');fs.createReadStream(p).pipe(res);}catch(_){res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),browser=await chromium.launch({channel:'msedge',headless:true});
async function test(name,fn){if(process.env.MQ_TEST_FILTER&&!name.includes(process.env.MQ_TEST_FILTER)&&!name.startsWith('No browser'))return;try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',detail:e.stack});}console.log(name+': '+results.at(-1).status);}
async function pageFor(url){const context=await browser.newContext({acceptDownloads:true});await context.route('**/*',route=>route.request().url().startsWith(origin)||route.request().url().startsWith('data:')?route.continue():route.abort());const page=await context.newPage();page.on('pageerror',e=>errors.push({url,error:e.message}));await page.goto(origin+url);return {page,context};}
async function start(page,mode='standard'){if(await page.locator('#playerNameInput').count())await page.locator('#playerNameInput').evaluate(el=>{el.value='SYNTHETIC_INITIALS_SENTINEL';});await page.evaluate(mode=>startSelectedMode(mode,{quizConfirmed:true}),mode);if(await page.locator('#guideIntroProceed').isVisible())await page.locator('#guideIntroProceed').click();await page.waitForFunction(()=>Boolean(currentQuestion)).catch(async e=>{throw Error(e.message+' '+JSON.stringify(await page.evaluate(()=>({preflight:validateFacultyMode(gameMode),mode:gameMode,body:document.body.innerText.slice(-1200)}))))});}
async function answer(page){return page.evaluate(async()=>{questionStartTime=Date.now()-6000;let index=0;for(;index<currentQuestion.options.length;index++)if(await isQuestionAnswerCorrect(currentQuestion,index))break;const expected=currentQuestion.telemetryOptionIndices?.[index];await answer(index);return {expected,index};});}
async function download(page,label){await page.evaluate(()=>{beginRunSession();runEnding=true;stopTimedModeClock();return showMasteryReportScreen();});const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download Game Data',exact:true}).last().click()]);const dest=path.join(out,label+'.csv');await file.saveAs(dest);return {text:fs.readFileSync(dest,'utf8'),dest};}
for(const family of ['managerial-intelligence-directorate','managerial-directorate-classroom','managerial-directorate-telemetry-poc'])for(const game of ['cost-directive','market-signal','strategy-desk','agency-protocol'])await test(family+'/'+game+' actual CSV, canonical selection, manifest and refresh',async()=>{
 const {page,context}=await pageFor('/play/'+family+'/'+game+'/?telemetrySynthetic=1'),before=requests.length;
 try{await start(page);const choice=await answer(page);const raw=await page.evaluate(()=>readLocalTelemetry().find(r=>r.event==='question'));assert.equal(raw.canonicalSelectedIndex,choice.expected);assert(raw.attemptID&&raw.presentationID);const file=await download(page,family+'-'+game);const report=validateCSV(file.text);assert.equal(report.status,'PASS',JSON.stringify(report.issues));assert.equal(report.manifestRows,1);assert.equal(report.acceptedAttempts,1);
 const table=parseCSV(file.text),header=table.shift(),manifestRow=table.find(r=>r[header.indexOf('event')]==='export_manifest'),manifest=JSON.parse(manifestRow[header.indexOf('manifestJSON')]);
 const registry=JSON.parse(fs.readFileSync(new URL('./registry.json',import.meta.url)));assert.equal(manifest.engineRevision,registry.games[game][family==='managerial-directorate-classroom'?'classroomEngineRevision':family==='managerial-directorate-telemetry-poc'?'pocEngineRevision':'engineRevision']);assert.equal(manifest.configuration.recipeSchema,null);const run=raw.runID;await page.reload();const [again]=await Promise.all([page.waitForEvent('download'),page.evaluate(run=>downloadTelemetryCsv(run),run)]);await again.saveAs(file.dest+'.refresh.csv');assert.equal(validateCSV(fs.readFileSync(file.dest+'.refresh.csv','utf8')).manifestRows,1);if(family==='managerial-intelligence-directorate'){assert.equal(requests.length,before);assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes('anonymousTelemetry'))),[]);}}
 finally{await context.close();}
});
await test('Generated Composer actual CSV, analytical recipe, no transmission',async()=>{const {page,context}=await pageFor('/synthetic.html'),before=requests.length;try{await start(page);await answer(page);const file=await download(page,'composer');const report=validateCSV(file.text);assert.equal(report.status,'PASS',JSON.stringify(report));const table=parseCSV(file.text),header=table.shift(),metadata=table.find(r=>r[header.indexOf('event')]==='export_manifest'),m=JSON.parse(metadata[header.indexOf('manifestJSON')]);assert(m.configuration.recipeSchema);assert.deepEqual(m.configuration.selectedConceptIds,['aggregate-demand']);assert(!metadata[header.indexOf('manifestJSON')].includes('Synthetic Contract Browser'));assert.equal(requests.length,before);}finally{await context.close();}});
for(const family of ['managerial-directorate-classroom','managerial-directorate-telemetry-poc'])await test(family+' real transmission control, reload, re-enable and pending cancellation',async()=>{const {page,context}=await pageFor('/play/'+family+'/cost-directive/?telemetrySynthetic=1');try{
 const control=page.locator('label').filter({hasText:'Send future anonymous gameplay events'}).locator('input');assert.equal(await control.count(),1);
 await control.evaluate(el=>el.click());await page.reload();assert.equal(await control.isChecked(),false);const before=requests.length;await start(page);await answer(page);await page.evaluate(()=>{window.dispatchEvent(new Event('online'));window.dispatchEvent(new Event('pagehide'));});await page.waitForTimeout(350);assert.equal(requests.length,before);assert((await page.evaluate(()=>readLocalTelemetry())).some(r=>r.event==='question'));
 harness.setOffline(true);await control.evaluate(el=>el.click());await page.evaluate(()=>sendGameData({event:'synthetic_queue_probe'}));await page.waitForTimeout(200);await control.evaluate(el=>el.click());const queues=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes('queue')).map(k=>JSON.parse(localStorage.getItem(k))));assert(queues.every(q=>q.length===0));harness.setOffline(false);await control.evaluate(el=>el.click());await page.evaluate(()=>sendGameData({event:'synthetic_after_reenable'}));await page.waitForTimeout(250);assert(![...harness.received.values()].some(e=>e.eventType==='synthetic_queue_probe'));
 }finally{harness.setOffline(false);await context.close();}});
await test('Public gameplay survives telemetry storage failure and exports the observed limitation',async()=>{const {page,context}=await pageFor('/play/managerial-intelligence-directorate/cost-directive/');try{await start(page);await page.evaluate(()=>{window.__storageSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(String(k).toLowerCase().includes('telemetry'))throw Error('synthetic telemetry storage failure');return window.__storageSet.call(this,k,v);};});await answer(page);assert.equal(await page.evaluate(()=>totalAttempts),1);await page.evaluate(()=>{Storage.prototype.setItem=window.__storageSet;});const file=await download(page,'storage-failure');assert(validateCSV(file.text).issues.some(i=>i.code==='OBSERVED_DELIVERY_LIMIT'));}finally{await context.close();}});
await test('No browser runtime exceptions or unexpected ingestion failures',()=>{assert.deepEqual(errors,[]);assert.deepEqual(harness.errors,[]);});
const report={passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,results,errors,workerErrors:harness.errors};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));await browser.close();server.close();harness.close();console.log(JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
