import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {createHash,webcrypto} from 'node:crypto';import {fileURLToPath} from 'node:url';
import {contractHash} from './hash.mjs';import {validateCSV,parseCSV} from './validate.mjs';import {validateManifest} from '../../server/anonymous-telemetry-poc/measurement-contract.mjs';import {validateEnvelope,PHASE} from '../../server/anonymous-telemetry-poc/telemetry-core.mjs';import {createWorkerHarness} from '../managerial_classroom/worker-harness.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=process.env.MQ_EVIDENCE_DIR||path.join(root,'validation_artifacts/telemetry_contract_hardening');fs.mkdirSync(out,{recursive:true});
const results=[];async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',detail:e.stack});}console.log(name+': '+results.at(-1).status);}
const schema=JSON.parse(fs.readFileSync(new URL('./schema.json',import.meta.url))),registry=JSON.parse(fs.readFileSync(new URL('./registry.json',import.meta.url)));
function fixture(storage=new Map(),override=registry){
 const values={runID:'synthetic-run',gameMode:'standard',room:1,TELEMETRY_PREFIX:'synthetic:',FACULTY_COMPOSITION_CONFIG:{slug:'cost-directive',title:'PRIVATE_TITLE_SENTINEL',supportedModes:['standard','exam'],selectedConceptIds:['costs']},currentQuestion:{id:1,options:['PRIVATE_ANSWER_A','PRIVATE_ANSWER_B'],a:0,telemetryOptionIndices:[1,0]},questionBanks:{easy:[{id:1,options:['PRIVATE_ANSWER_A','PRIVATE_ANSWER_B'],a:0}]}};
 const records=[];const context=vm.createContext({globalThis:{crypto:webcrypto},window:{},document:{addEventListener(){},querySelectorAll:()=>[]},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},get:(k,f)=>k in values?values[k]:f,registry:override});vm.runInContext(fs.readFileSync(new URL('./runtime.js',import.meta.url),'utf8')+'\napi=createTelemetryContract(get,registry);',context);const api=context.api;
 values.sendGameData=data=>{const row={eventID:webcrypto.randomUUID(),runID:values.runID,mode:values.gameMode,event:data.event,questionID:data.questionId||values.currentQuestion.id,room:data.room||values.room,selectedIndex:0,correct:1,responseTimeMs:100,activeResponseTimeMs:90,hiddenTimeMs:10,gameplayResponseTimeMs:100};api.stamp(row,data);records.push(row);return row;};
 return {api,values,records,storage,send:values.sendGameData};
}
const csv=(rows,id='managerial-local-contract1')=>{const header=schema.schemas.find(s=>s.id===id).columns;const escape=v=>'"'+String(v??'').replaceAll('"','""')+'"';return [header.join(','),...rows.map(r=>header.map(k=>escape(r[k])).join(','))].join('\r\n');};
let sample,rows;
await test('SHA-256 matches independent UTF-8 implementation',()=>{for(const value of ['','abc','Ω 中文'])assert.equal(contractHash(value),createHash('sha256').update(value).digest('hex'));});
await test('New manifest, privacy allowlist, immutable export and offline resolution',()=>{sample=fixture();sample.api.show();sample.send({event:'question'});rows=sample.api.exportRows(sample.records,'synthetic-run');const meta=rows.find(r=>r.event==='export_manifest');validateManifest(JSON.parse(meta.manifestJSON),meta.manifestID);assert(!JSON.stringify(rows).includes('PRIVATE_'));const text=csv(rows);fs.writeFileSync(path.join(out,'current-local.csv'),text);assert.equal(validateCSV(text).status,'PASS');assert.equal(sample.records.length,2);});
await test('Historical rows retain labels and unknown fields through current download',()=>{const legacy={eventID:'old',runID:'synthetic-run',event:'question',telemetryVersion:'CostDirective-local-telemetry-v5-engine2',responseTimeMs:777};const output=sample.api.exportRows([legacy,...sample.records],'synthetic-run');assert.deepEqual(JSON.parse(JSON.stringify(output[0])),legacy);assert(!('canonicalSelectedIndex' in output[0]));assert(validateCSV(csv(output)).limitations.some(x=>x.includes('Legacy')));fs.writeFileSync(path.join(out,'mixed-local.csv'),csv(output));});
await test('Resume preserves sequence, old manifest and establishes explicit changed-build segment',()=>{const next=JSON.parse(JSON.stringify(registry));next.trackerSourceRevision='a'.repeat(64);const resumed=fixture(sample.storage,next);resumed.send({event:'resume'});assert(resumed.records[0].localSequence>sample.records[0].localSequence);assert.notEqual(resumed.records[0].manifestID,sample.records[0].manifestID);assert.equal(resumed.records[0].provenanceStatus,'resume-segment');assert.equal(Object.keys(resumed.api.state('synthetic-run').manifests).length,2);});
await test('Exam revisit has new view, same attempt, one committed outcome and saved support',()=>{const f=fixture();f.values.gameMode='exam';f.api.show();f.send({event:'exam_answer_initial'});const a=f.records.at(-1);f.api.show();f.send({event:'exam_answer_revision'});const b=f.records.at(-1);assert.equal(a.attemptID,b.attemptID);assert.notEqual(a.presentationID,b.presentationID);f.send({event:'question',adaptiveMode:'exam-commit'});assert.equal(f.records.at(-1).attemptID,a.attemptID);assert.equal(f.records.at(-1).supportJSON,b.supportJSON);});
await test('Repeated questions and rejected guesses have distinct attempt identity',()=>{const f=fixture();f.api.show();f.send({event:'rapid_guessing'});const first=f.records.at(-1).attemptID;f.send({event:'question'});assert.notEqual(first,f.records.at(-1).attemptID);f.api.show();f.send({event:'question'});assert.equal(new Set(f.records.filter(r=>r.event==='question').map(r=>r.attemptID)).size,2);});
await test('Canonical option mapping leaves answer verification unchanged; wrong mapping detected',()=>{const f=fixture();f.api.show();f.send({event:'question'});assert.equal(f.records.at(-1).canonicalSelectedIndex,1);assert.throws(()=>assert.equal({...f.records.at(-1),canonicalSelectedIndex:0}.canonicalSelectedIndex,f.values.currentQuestion.telemetryOptionIndices[0]));});
await test('Assistance snapshot does not retroactively change earlier answer',()=>{const f=fixture();f.api.show();f.send({event:'question'});const before=f.records.at(-1).supportJSON;f.values.currentQuestionAssistance={questionId:1,removedIndexes:[1]};f.values.currentQuestion.hint='PRIVATE_HINT';f.api.show();f.send({event:'question'});assert.equal(JSON.parse(before).artifactApplied,false);assert.equal(JSON.parse(f.records.at(-1).supportJSON).artifactApplied,true);assert(!JSON.stringify(f.api.exportRows(f.records,'synthetic-run')).includes('PRIVATE_HINT'));});
await test('Stale version, wrong manifest, ambiguous join, duplicate commit, impossible timing and unknown field negatives',()=>{
 const response=rows.find(r=>r.event==='question');
 for(const [code,patch] of [['STALE_VERSION',{telemetryVersion:'old'}],['MANIFEST_UNRESOLVED',{manifestID:'a'.repeat(64)}],['ATTEMPT_MISSING',{attemptID:''}],['IMPOSSIBLE_TIMING',{hiddenTimeMs:9999}]]){const changed=rows.map(r=>r===response?{...r,...patch}:r);assert(validateCSV(csv(changed)).issues.some(i=>i.code===code),code);}
 assert(validateCSV(csv([...rows,{...response,eventID:webcrypto.randomUUID()}])).issues.some(i=>i.code==='DUPLICATE_COMMIT'));
 assert(validateCSV(csv(rows).replace('eventID,','unknownField,')).issues.some(i=>i.code==='UNKNOWN_SCHEMA'));
 const changed=rows.map(r=>r.event==='export_manifest'?{...r,manifestJSON:r.manifestJSON.replace('"quizTarget":null','"quizTarget":7')}:r);assert(validateCSV(csv(changed)).issues.some(i=>i.code==='MANIFEST_INVALID'));
});
// Reuse the existing concrete private client fixture rather than create another tracker.
const parity=fs.readFileSync(path.join(root,'audit_tools/managerial_telemetry_parity/run-parity.mjs'),'utf8');
const clientCode=parity.slice(parity.indexOf('function client(){'),parity.indexOf("await check(" ,parity.indexOf('function client(){')));
const sandbox=vm.createContext({vm,fs,path,webcrypto,root,URLSearchParams,AbortController,console,assert});vm.runInContext(clientCode+'\nmakeClient=client;',sandbox);
await test('Disable before start, pending cancellation, refresh, re-enable and no replay',async()=>{const c=sandbox.makeClient();c.api.setRemoteCollection(false);c.run("sendGameData({event:'start',runID:'s',mode:'standard'})");assert.equal(c.events().length,0);c.api.setRemoteCollection(true);c.api.emit('synthetic_test',{});const old=c.events().map(e=>e.eventId);c.api.setRemoteCollection(false);assert.equal(c.events().length,0);assert((await c.api.flush()).disabled);c.api.setRemoteCollection(true);c.api.emit('synthetic_new',{});assert(c.events().every(e=>!old.includes(e.eventId)));assert(c.api.getQuality().cancelled>0);});
await test('Permanent rejection isolates poison event and valid peer progresses',async()=>{const c=sandbox.makeClient();const bad=c.api.emit('synthetic_bad',{}),good=c.api.emit('synthetic_good',{});c.context.fetch=async(url,opts)=>{const events=JSON.parse(opts.body).events;return {ok:!events.some(e=>e.eventId===bad.eventId),status:events.some(e=>e.eventId===bad.eventId)?400:202,json:async()=>({acknowledgedEventIds:events.map(e=>e.eventId)})};};await c.api.flush();await c.api.flush();await c.api.flush();assert(!c.events().some(e=>e.eventId===good.eventId));assert.equal(c.api.getQuality().permanentlyRejected,1);});
await test('Queue bound is counted; transient retries preserve IDs',async()=>{const c=sandbox.makeClient();const m=rows.find(r=>r.event==='export_manifest'),metadata=c.api.emit('run_manifest',{__manifestID:m.manifestID,__manifest:m.manifestJSON});for(let i=0;i<2005;i++)c.api.emit('synthetic_test',{__manifestID:m.manifestID});assert.equal(c.events().length,2000);assert.equal(c.api.getQuality().overflow,6);assert(c.events().some(e=>e.eventId===metadata.eventId),'surviving events retain their queued manifest');const before=c.events().map(e=>e.eventId);c.context.fetch=async()=>{throw Error('synthetic offline');};await c.api.flush();assert.deepEqual(c.events().map(e=>e.eventId),before);});
await test('Typed private Worker ingestion/export and idempotent synthetic D1 round trip',async()=>{const h=createWorkerHarness(root),c=sandbox.makeClient();let events=[c.api.emit('synthetic_test',{})];const base=events[0],m=rows.find(r=>r.event==='export_manifest');events.push({...base,eventId:webcrypto.randomUUID(),sequenceNumber:2,eventType:'run_manifest',manifestID:m.manifestID,manifestJSON:m.manifestJSON});let r=await h.call('/v1/events',{events});assert.equal(r.status,202,await r.text());r=await h.call('/v1/events',{events});assert.equal((await r.json()).accepted,0);const output=await(await h.call('/v1/admin/export.csv?includeSynthetic=1',{admin:true})).text();assert(output.includes(m.manifestID));fs.writeFileSync(path.join(out,'current-private.csv'),output);const bad={...base,eventId:webcrypto.randomUUID(),sequenceNumber:3,supportJSON:'{"selectedText":"PRIVATE_SENTINEL"}'};assert.throws(()=>validateEnvelope({phase:PHASE,events:[bad]}));h.close();});

await test('Actual shuffle preserves choices, verification and RNG calls including duplicate text',()=>{
 const html=fs.readFileSync(path.join(root,'build/faculty-build-composer/template/mastery-quests-faculty-template-composer-ready.html'),'utf8');
 const current=html.match(/function shuffleOptions\(question\)\{[\s\S]*?\n\}/)[0];
 const before=current.replace(/        telemetryOptionIndices:[^\n]+\n/,'').replace(/        \[q.telemetryOptionIndices[^\n]+\n/,'');
 const question={options:['same','same','different','last'],a:1};
 function execute(source){let calls=0;const result=vm.runInNewContext(source+';shuffleOptions(question)',{question,Math:{floor:Math.floor,random:()=>[.8,.2,.6][calls++]}});return {result,calls};}
 const a=execute(before),b=execute(current);assert.equal(a.calls,b.calls);assert.equal(JSON.stringify(a.result.options),JSON.stringify(b.result.options));assert.equal(a.result.a,b.result.a);assert.equal(new Set(b.result.telemetryOptionIndices).size,4);b.result.options.forEach((text,i)=>assert.equal(text,question.options[b.result.telemetryOptionIndices[i]]));
});
await test('Configuration, content and asset fingerprints react only to analytical changes',()=>{
 const a=fixture(),b=fixture();b.values.FACULTY_COMPOSITION_CONFIG.title='PRIVATE_OTHER_TITLE';assert.equal(a.api.build().buildRevision,b.api.build().buildRevision);
 const c=fixture();c.values.FACULTY_COMPOSITION_CONFIG.supportedModes=['standard'];assert.notEqual(c.api.build().configurationRevision,a.api.build().configurationRevision);
 const d=fixture();d.values.questionBanks.easy[0].options[0]='DIFFERENT_AUTHORED_OPTION';assert.notEqual(d.api.build().contentRevision,a.api.build().contentRevision);
 const changed=JSON.parse(JSON.stringify(registry));changed.games['cost-directive'].assetRevision='a'.repeat(64);assert.notEqual(fixture(new Map(),changed).api.build().buildRevision,a.api.build().buildRevision);
});
await test('Malformed null queue head cannot block a valid record; stored diagnostics are allowlisted',async()=>{
 const source=clientCode.replace('const storage=new Map()', 'const storage=new Map([["anonymousTelemetry:queue:v1","[null]"],["anonymousTelemetry:quality:v1",JSON.stringify({storageFailures:2,selectedText:"PRIVATE_SENTINEL"})]])');
 const box=vm.createContext({vm,fs,path,webcrypto,root,URLSearchParams,AbortController,console,assert});vm.runInContext(source+'\nmakeClient=client;',box);const c=box.makeClient();const good=c.api.emit('synthetic_good',{});
 c.context.fetch=async(url,opts)=>{const events=JSON.parse(opts.body).events;return events.some(e=>e===null)?{ok:false,status:400}:{ok:true,status:202,json:async()=>({acknowledgedEventIds:events.map(e=>e.eventId)})};};
 assert(!JSON.stringify(c.events()).includes('PRIVATE_SENTINEL'));await c.api.flush();await c.api.flush();await c.api.flush();assert.equal(c.events().length,0);assert.equal(c.api.getQuality().permanentlyRejected,1);assert(good.eventId);
});

const report={passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,results};fs.writeFileSync(path.join(out,'targeted-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
