import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),baseline=JSON.parse(fs.readFileSync(process.argv[2],'utf8').replace(/^\uFEFF/,'')),out=process.argv[3];
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const changed=baseline.filter(item=>sha(fs.readFileSync(path.join(root,item.path))).toLowerCase()!==item.sha256.toLowerCase()).map(i=>i.path);
const protectedChanges=changed.filter(p=>!/^audit_tools\/(telemetry_data_dictionary\/browser\.mjs|anonymous_telemetry_poc\/create_private_build\.mjs|managerial_classroom\/build\.mjs|managerial_local_csv_parity\/run-browser\.mjs|managerial_telemetry_parity\/run-(parity|browser)\.mjs|published_managerial_parity\/(sync|browser)\.mjs)$/.test(p)&&!/^build\/faculty-build-composer\/(template\/mastery-quests-faculty-template-composer-ready\.html|tests\/run_(visibility_aware_telemetry|phase3a_official_theme)_validation\.js)$/.test(p)&&!/^how-to\/telemetry-data-dictionary\/(fields\.json|index\.html)$/.test(p)&&!/^play\/managerial-(intelligence-directorate|directorate-classroom|directorate-telemetry-poc)\/((cost-directive|market-signal|strategy-desk|agency-protocol)\/index\.html|local-telemetry\.js|telemetry-client\.js)$/.test(p)&&!/^server\/anonymous-telemetry-poc\/(telemetry-core|worker)\.mjs$/.test(p));
assert.deepEqual(protectedChanges,[],'Out-of-scope baseline file changes');
const normalize=s=>s.replace(/\r\n/g,'\n').replace(/<meta name="anonymous-telemetry-collection" content="[^"]*">/g,'').replace(/data-telemetry-resource="\$\{escapeHTML\(resource.id\)\}" /g,'').replace(/        telemetryOptionIndices: \[\.\.\.\(question.telemetryOptionIndices \|\| \(question.options \|\| \[\]\).map\(\(_, index\) => index\)\)\],\n/g,'').replace(/        \[q.telemetryOptionIndices\[i\], q.telemetryOptionIndices\[j\]\] = \[q.telemetryOptionIndices\[j\], q.telemetryOptionIndices\[i\]\];\n/g,'');
const engineResults=[];
for(const family of ['managerial-intelligence-directorate','managerial-directorate-classroom','managerial-directorate-telemetry-poc'])for(const game of ['cost-directive','market-signal','strategy-desk','agency-protocol']){const p=`play/${family}/${game}/index.html`;const before=execFileSync('git',['-c','safe.directory='+root.replaceAll('\\','/'),'show','HEAD:'+p],{cwd:root,encoding:'utf8',maxBuffer:5e6}),after=fs.readFileSync(path.join(root,p),'utf8');assert.equal(normalize(after),normalize(before),p+': non-telemetry engine change');engineResults.push({path:p,status:'PASS'});}
const report={status:'PASS',baselineFiles:baseline.length,changedExisting:changed.length,unchangedExisting:baseline.length-changed.length,changed,protectedChanges,engineResults};if(out)fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
