'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),work=path.join(root,'tmp/macroeconomics_exception_closure'),cdir=path.join(root,'build/faculty-build-composer');
const core=require(path.join(cdir,'composer-core.js')),h=require(path.join(cdir,'tests/composer-test-helpers.js')),contracts=require(path.join(cdir,'tests/composer-integrity-contracts.js')),approved=require(path.join(cdir,'tests/macroeconomics-exception-approved-revisions.js'));
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8')),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),b=read('audit_tools/macroeconomics_exception_closure/inputs/baseline.json'),current=h.loadComposerLibrary(),prior=approved.closureBaselineLibrary;
approved.assertCurrentLibrary(current);const integrity=contracts.assertCanonicalIntegrity(current);
const rec=lib=>new Map(contracts.questionRecords(lib).map(r=>[String(r.question.id),r.question])),now=rec(current),old=rec(prior),locations=lib=>{const m={};for(const r of contracts.questionRecords(lib))(m[String(r.question.id)]||=[]).push([r.conceptId,r.pool]);for(const a of Object.values(m))a.sort();return m},newLoc=locations(current),oldLoc=locations(prior);
const changed=[...now.keys()].filter(id=>core.stableStringify(now.get(id))!==core.stableStringify(old.get(id))||core.stableStringify(newLoc[id])!==core.stableStringify(oldLoc[id])).sort();assert.deepEqual(changed,b.targets);
const answerChecks=[];for(const[id,q]of now){const answers=q.options.map((o,i)=>sha(core.normalizeAnswerText(o))===q.aHash?i:-1).filter(i=>i>=0);assert.equal(answers.length,1,'One answer '+id);assert.equal(new Set(q.options.map(core.normalizeAnswerText)).size,4);assert(q.q.trim()&&q.feedback.trim());if(b.targets.includes(id))answerChecks.push({id,answerIndex:answers[0],key:q.options[answers[0]],hash:q.aHash,valid:true});}
for(const id of b.protectedIDs){assert.deepEqual(now.get(id),old.get(id));assert.deepEqual(newLoc[id],oldLoc[id]);}
const frozenContent=['q','options','aHash','feedback'];const difficultyIds=read('faculty_exports/audits/macroeconomics_final_verification.json').exceptions.filter(e=>e.category==='D').map(e=>e.questionID),metadataIds=['ECON-SP-LEGENDARY-9000','LG-Q-9111','LG-Q-2011','LG-Q-9113','PM2C1-FED-MB-003'];
for(const id of [...difficultyIds,...metadataIds,'LG-B-6003'])for(const field of frozenContent)assert.deepEqual(now.get(id)[field],old.get(id)[field],'Preserved substantive field '+id+'.'+field);
for(const id of difficultyIds)assert.equal(now.get(id).canonicalDifficulty,id==='ECON-NL-ELITE-355'?'easy':'medium');
for(const id of b.targets)for(const field of ['id','canonicalId','instructionalRole','challengeStage','bossStage','originalBossTier','primaryConceptId','sourceOccurrences','sourceHash','sourceType','sourcePool','originalSourcePool'])assert.deepEqual(now.get(id)[field],old.get(id)[field],'Preserved role/identity '+id+'.'+field);
const area=require(path.join(cdir,'course-area-model.js')).create(current.registry.concepts),projection={general:new Set(),micro:new Set(),macro:new Set()};for(const cid of Object.keys(current.concepts))for(const q of core.ContentScope.allQuestions(core.resolveConceptModule(current,cid)))for(const a of area.areasFor(cid))projection[a].add(String(q.id));for(const a in projection)assert.deepEqual([...projection[a]].sort(),b.areaIDs[a]);
const recipe=ids=>({schemaVersion:core.RECIPE_SCHEMA_VERSION,title:'Macro exception closure',slug:'macro-exception-closure',selectedConceptIds:ids,supportedModes:[...core.MODE_ORDER],checkpointFocus:Object.fromEntries(core.CHECKPOINT_ORDER.map(k=>[k,null]))});
const bridgeDecisions=read('audit_tools/macroeconomics_exception_closure/inputs/bridge_reviews.json'),repairChecks=[];
for(const id of [...Object.keys(bridgeDecisions),...metadataIds.filter(x=>x!=='ECON-SP-LEGENDARY-9000')]){
 const q=now.get(id),comp=core.compose(current,recipe([q.primaryConceptId])),skill=q.repairSkill;
 const refs=comp.microSkillRepairPools[skill]||comp.skillRepairSeedPools[skill]||[];assert(refs.length,'Usable runtime repair '+id+' '+skill);
 const actual=refs.map(core.idOf);const expected=bridgeDecisions[id]?.repairIDs||(q.primaryConceptId==='central-bank-and-federal-reserve'?['PM2C1-FED-M-001','PM2C1-FED-H-002']:['LG-R-5018']);for(const ref of expected)assert(actual.includes(ref),'Exact associated repair '+id+' -> '+ref);
 if(bridgeDecisions[id])assert((comp.microSkillBridgePools[skill]||[]).some(x=>core.idOf(x)===id),'Bridge is reachable under its repair skill '+id);
 repairChecks.push({id,conceptId:q.primaryConceptId,primarySkill:q.primarySkill,repairSkill:skill,repairIDs:actual,expectedRepairIDs:expected,repairs:refs.map(x=>({id:core.idOf(x),q:x.q,options:x.options,feedback:x.feedback})),bridgeRetestIDs:(comp.microSkillBridgePools[skill]||[]).map(core.idOf),singleConceptRouting:true});
}
// Frozen-baseline drift probes verify that the adapter rejects values outside its literal ledger.
const probe=structuredClone(current),outside=[...now.keys()].find(id=>!b.targets.includes(id));for(const r of contracts.questionRecords(probe))if(String(r.question.id)===outside)r.question.feedback+=' UNAUTHORIZED';assert.throws(()=>approved.assertCurrentLibrary(probe));
const targetProbe=structuredClone(current);for(const r of contracts.questionRecords(targetProbe))if(String(r.question.id)===b.targets[0])r.question.q+=' UNAPPROVED';assert.throws(()=>approved.assertCurrentLibrary(targetProbe));
// Rebuild inventories with each version's own frozen outcome policy.
const {execFileSync}=require('node:child_process'),ctx={module:{exports:{}}};vm.runInNewContext(execFileSync('git',['show',b.ref+':build/faculty-build-composer/data/faculty-outcomes.js'],{cwd:root,encoding:'utf8',maxBuffer:32e6}),ctx);const oldPolicy=JSON.parse(JSON.stringify(ctx.module.exports)),newPolicy=structuredClone(core.FacultyOutcomes.policy);
function policy(value){const p=core.FacultyOutcomes.policy;for(const k of Object.keys(p))delete p[k];Object.assign(p,structuredClone(value));}
const selections=area.conceptsForArea('macro').map(c=>({id:c.canonicalConceptId,kind:'concept',conceptIds:[c.canonicalConceptId]})),source=fs.readFileSync(path.join(cdir,'composer.js'),'utf8'),presets=vm.runInNewContext('('+source.match(/const PRESETS = (\[[\s\S]*?\n\]);/)[1]+')');selections.push(...presets.filter(p=>p.conceptIds.some(cid=>area.areasFor(cid).includes('macro'))).map(p=>({...p,kind:'preset'})));
const previousInventory=read('tmp/macroeconomics_final_verification/inventory.json'),inventory=[];const counts=c=>Object.fromEntries(['easy','medium','hard','elite','legendary','easyBoss','mediumBoss','finalBoss','legendaryBoss'].map(p=>[p,c.banks[p].length]));
for(const s of selections){policy(oldPolicy);const before=core.compose(prior,recipe(s.conceptIds));policy(newPolicy);const after=core.compose(current,recipe(s.conceptIds));const verified=previousInventory.find(x=>x.id===s.id&&x.kind===s.kind);assert.deepEqual(counts(before),verified.after,'Matches frozen verified inventory '+s.kind+':'+s.id);inventory.push({id:s.id,kind:s.kind,conceptIds:s.conceptIds,before:counts(before),after:counts(after),beforeErrors:before.errors,afterErrors:after.errors,newlyUnavailable:after.validation.modes.filter(m=>!m.ok&&before.validation.modes.find(x=>x.mode===m.mode).ok).map(m=>m.mode),newlyAvailable:after.validation.modes.filter(m=>m.ok&&!before.validation.modes.find(x=>x.mode===m.mode).ok).map(m=>m.mode),verifiedPriorEX2:verified.newlyUnavailable});}
policy(newPolicy);
const allQs=c=>[...Object.values(c.banks).flat(),...Object.values(c.challengeQuestionBanks).flat(),...c.repairQuestions,...c.bridgeQuestions,...Object.values(c.microSkillRepairPools).flat(),...Object.values(c.microSkillBridgePools).flat(),...Object.values(c.skillRepairSeedPools).flat()];
(async()=>{
 const all=area.conceptsForArea('macro').map(x=>x.canonicalConceptId),selected=all.filter(id=>!current.concepts[id].derivedFromConceptId||!all.includes(current.concepts[id].derivedFromConceptId));if(!selected.includes('integrated-macroeconomic-analysis'))selected.push('integrated-macroeconomic-analysis');
 const comp=core.compose(current,recipe(selected));assert(comp.validation.modes.length===10&&comp.validation.modes.every(x=>x.ok),'All full-Macro modes');
 const integration=now.get('ECON-SP-LEGENDARY-9000'),integrationRepairs=comp.microSkillRepairPools[integration.repairSkill]||[];assert(integrationRepairs.some(q=>core.idOf(q)==='ECON-SP-CHOOSE-STABILIZATION-RESPONSE-5063'),'Existing integrated-question direction repair');
 repairChecks.push({id:integration.id,conceptId:integration.primaryConceptId,primarySkill:integration.primarySkill,repairSkill:integration.repairSkill,repairIDs:integrationRepairs.map(core.idOf),repairs:integrationRepairs.map(q=>({id:core.idOf(q),q:q.q,feedback:q.feedback})),singleConceptRouting:false,context:'Full Macro: the integrated supplement uses the existing stabilization-policy repair.'});
 comp.embeddedQuestionAssets=Object.fromEntries(comp.assets.map(a=>[a.runtimePath,'data:image/webp;base64,'+fs.readFileSync(path.join(cdir,a.sourceUrl)).toString('base64')]));
 const game=await h.buildFacultyGame(core,recipe(selected),{library:current,composition:comp}),inlineScriptsCompiled=h.assertInlineScriptsCompile(game.html),published=allQs(game.composition),publishedIDs=new Set(published.map(core.idOf)),omitted=[...projection.macro].filter(id=>!publishedIDs.has(id)).sort();
 assert.deepEqual(omitted,['ECON-SP-MAP-AD-AS-TO-PC-5061','ECON-SP-MAP-AD-AS-TO-PC-6052']);assert.equal(publishedIDs.size,4743);
 for(const q of published)for(const field of ['q','options','aHash','feedback','type','primarySkill','repairSkill','canonicalDifficulty'])assert.deepEqual(q[field],now.get(core.idOf(q))[field],'Published parity '+q.id+'.'+field);
 for(const id of b.targets)assert(publishedIDs.has(id),'All 45 published');const answers=await core.verifyAnswers(comp);assert(answers.ok,JSON.stringify(answers));
 const result={sourceSHA256:sha(fs.readFileSync(path.join(cdir,'data/composer_library.js'))),integrity,changedIDs:changed,unauthorizedChanges:[],unchangedCanonicalIDs:now.size-changed.length,unchangedMacroIDs:4745-changed.length,sharedProtectedRecords:b.protectedIDs.length,sharedRegressions:[],counts:Object.fromEntries(Object.entries(projection).map(([k,s])=>[k,s.size])),answerChecks,repairChecks,difficultyChecks:difficultyIds.map(id=>({id,before:old.get(id).canonicalDifficulty,after:now.get(id).canonicalDifficulty,locations:newLoc[id],contentUnchanged:true})),scopeAdapterProbes:{unauthorizedRecordRejected:outside,unauthorizedTargetValueRejected:b.targets[0]},inventorySelections:inventory.length,newUnavailableCombinations:inventory.reduce((n,x)=>n+x.newlyUnavailable.length,0),newAvailableCombinations:inventory.reduce((n,x)=>n+x.newlyAvailable.length,0),publication:{canonicalMacro:4745,published:publishedIDs.size,omitted,newOmissions:[],allTargetsPresent:true,parityFailures:[],modes:comp.validation.modes,answerVerification:answers,inlineScriptsCompiled}};
 fs.writeFileSync(path.join(work,'execution_verification.json'),JSON.stringify(result,null,2));fs.writeFileSync(path.join(work,'mode_inventory.json'),JSON.stringify(inventory,null,2));fs.writeFileSync(path.join(work,'student.html'),game.html);
 console.log(JSON.stringify({...result,answerChecks:result.answerChecks.length,repairChecks:result.repairChecks.length,difficultyChecks:result.difficultyChecks.length,changedIDs:changed.length},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
