import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
const root=process.cwd(),baseline=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),out=process.argv[3];const sha=p=>createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const allowed=new Set(['audit_tools/managerial_telemetry_parity/run-parity.mjs','server/anonymous-telemetry-poc/README.md','TELEMETRY_GOVERNANCE.md','audit_tools/managerial_classroom/worker-harness.mjs','audit_tools/telemetry_governance/OWNER_DECISIONS.md','audit_tools/telemetry_governance/README.md','audit_tools/telemetry_governance/admin.mjs','audit_tools/telemetry_governance/browser.mjs','audit_tools/telemetry_governance/check.mjs','audit_tools/telemetry_governance/owner-decisions.json','audit_tools/telemetry_governance/render.mjs','server/anonymous-telemetry-poc/governance-policy.mjs','server/anonymous-telemetry-poc/governance.mjs','server/anonymous-telemetry-poc/wrangler.jsonc','how-to/responsible-telemetry-use/index.html','audit_tools/managerial_classroom/build.mjs','audit_tools/telemetry_contract/registry.json','audit_tools/telemetry_contract/validate.mjs','build/faculty-build-composer/template/mastery-quests-faculty-template-composer-ready.html','how-to/index.html','how-to/telemetry-data-dictionary/index.html','play/managerial-directorate-classroom/index.html','play/managerial-directorate-classroom/telemetry-client.js','play/managerial-directorate-telemetry-poc/telemetry-client.js','play/managerial-intelligence-directorate/local-telemetry.js','privacy/index.html','server/anonymous-telemetry-poc/worker.mjs']);
const changed=baseline.filter(x=>sha(x.path)!==x.sha256).map(x=>x.path);assert.deepEqual(changed.filter(p=>!allowed.has(p)),[],'Unrelated/frozen file changed');
const normalize=s=>s.replace(/\r\n/g,'\n').replace(/  \/\/ BEGIN MEASUREMENT CONTRACT[\s\S]*?  \/\/ END MEASUREMENT CONTRACT/,'').replace(/  function addDisclosure\(\)[\s\S]*?\n  }\n/,'');
const semanticChecks=[];
for(const p of ['build/faculty-build-composer/template/mastery-quests-faculty-template-composer-ready.html','play/managerial-intelligence-directorate/local-telemetry.js','play/managerial-directorate-classroom/telemetry-client.js','play/managerial-directorate-telemetry-poc/telemetry-client.js']){const before=execFileSync('git',['-c','safe.directory='+root.replaceAll('\\','/'),'show','HEAD:'+p],{cwd:root,encoding:'utf8',maxBuffer:8e6});assert.equal(normalize(fs.readFileSync(path.join(root,p),'utf8')),normalize(before),p+': change outside disclosure/embedded artifact registry');semanticChecks.push({path:p,status:'PASS'});}
const beforeGovernance=execFileSync('git',['-c','safe.directory='+root.replaceAll('\\','/'),'show','HEAD:server/anonymous-telemetry-poc/governance.mjs'],{cwd:root,encoding:'utf8'}).replace(/\r\n/g,'\n');const afterGovernance=fs.readFileSync(path.join(root,'server/anonymous-telemetry-poc/governance.mjs'),'utf8').replace(/\r\n/g,'\n');
for(const expression of [/selection="julianday[^\n]+/,/const statements=\[[\s\S]*?const result=await db.batch\(statements\);/]){const prior=beforeGovernance.match(expression)?.[0];assert(prior&&afterGovernance.includes(prior),'Canonical retention SQL changed');}
const report={status:'PASS',baselineFiles:baseline.length,changedExisting:changed.length,unchangedExisting:baseline.length-changed.length,changed,semanticChecks,frozenScope:'All baseline files outside the explicitly listed governance activation paths are byte-identical, including all game HTML, banks, assets, PDFs, LO data, measurement release/schema/runtime/core and applied migrations.'};if(out)fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
