import './local-network-only.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {createHash} from 'node:crypto';
import worker from '../../server/anonymous-telemetry-poc/worker.mjs';
import * as C from '../../server/anonymous-telemetry-poc/capabilities.mjs';
import {admitCapabilityRequest} from '../../server/anonymous-telemetry-poc/capability-admission.mjs';
import {PHASE} from '../../server/anonymous-telemetry-poc/telemetry-core.mjs';
import {approvedEnvironment} from '../../server/anonymous-telemetry-poc/governance-policy.mjs';
import {contractHash} from '../telemetry_contract/hash.mjs';
const out=process.env.MQ_EVIDENCE_DIR||'validation_artifacts/portable_telemetry_stage1';fs.mkdirSync(out,{recursive:true});
const results=[],secrets=[],logs=[];let maxBindings=0,maxBatch=0;
const log=console.log,errorLog=console.error;console.error=(...args)=>logs.push(args.map(String).join(' '));
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(error){results.push({name,status:'FAIL',detail:secrets.reduce((s,k)=>s.replaceAll(k,'[REDACTED]'),String(error.stack))});}log(name+': '+results.at(-1).status);}
const migrationDir='server/anonymous-telemetry-poc/migrations',migrations=fs.readdirSync(migrationDir).sort();
function fixture(migrate=true){
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');
 for(const f of migrations.slice(0,migrate?3:2))db.exec(fs.readFileSync(path.join(migrationDir,f),'utf8'));
 const clock={now:Math.floor(Date.now()/1000)};db.function('unixepoch',()=>clock.now);
 class Statement{constructor(sql){this.sql=sql;this.values=[];}bind(...values){assert(values.length<=100,'D1 bind limit');maxBindings=Math.max(maxBindings,values.length);this.values=values;return this;}
 execute(){const s=db.prepare(this.sql);if(/^\s*SELECT/i.test(this.sql))return {success:true,results:s.all(...this.values)};return {success:true,results:[],meta:{changes:Number(s.run(...this.values).changes)}};}
 async first(){return db.prepare(this.sql).get(...this.values)||null;}async all(){return this.execute();}async run(){return this.execute();}}
 const env={...approvedEnvironment(),CAPABILITY_ISSUANCE_ENABLED:'true',CAPABILITY_INGEST_ENABLED:'true',ADMIN_TOKEN:'fixture-admin-secret',MAINTENANCE_TOKEN:'fixture-maintenance-secret',ALLOWED_ORIGINS:'https://masteryquests.org,https://www.masteryquests.org',TELEMETRY_DB:{prepare:s=>new Statement(s),async batch(ss){maxBatch=Math.max(maxBatch,ss.length);db.exec('BEGIN IMMEDIATE');try{const r=ss.map(s=>s.execute());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}}};
 return {db,env,clock,close:()=>db.close()};
}
const tuple={gameId:'faculty-composer',buildId:'composer-'+'a'.repeat(64),buildVersion:'b'.repeat(64),schemaVersion:3};
function activation(patch={}){return {activationVersion:'mq-build-activation/1',issuanceRequestId:crypto.randomUUID(),allowAnonymousDataCollection:true,...tuple,measurementContract:'mq-measurement/1',governanceVersion:'mq-governance/2',disclosureVersion:'mq-disclosure/2',turnstileToken:'fixture-challenge-secret',...patch};}
const verifier=async({context})=>({success:true,action:'mq_build_activate',hostname:'masteryquests.org',cdata:context});
async function issue(f,patch={},options={}){const r=await C.issueBuildCapability(activation(patch),f.env,{verifyChallenge:verifier,...options});secrets.push(r.capability,await C.hashCapability(r.capability));return r;}
function event(patch={}){return {...tuple,eventId:crypto.randomUUID(),runId:crypto.randomUUID(),anonymousClientId:crypto.randomUUID(),phase:PHASE,mode:'standard',eventType:'run_started',sequenceNumber:1,eventTimestamp:new Date().toISOString(),synthetic:true,contractID:'mq-measurement/1',manifestID:null,provenanceStatus:'unresolved',...patch};}
function req(token,events,options={}){return new Request('http://fixture.test/v1/events',{method:'POST',headers:{'content-type':'application/json',...(token?{'x-mq-ingest-token':token}:{}),...options.headers},body:JSON.stringify({phase:PHASE,events,...options.body})});}
const admit=(f,c,events,options)=>admitCapabilityRequest(req(c.capability,events),f.env,options);
async function rejects(fn,status,code){await assert.rejects(fn,e=>e.status===status&&(!code||e.code===code));}
function snapshot(f){return JSON.stringify(f.db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all().map(({name})=>[name,f.db.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()]));}
function barrier(n=2){let count=0,release;const promise=new Promise(r=>release=r);return async({attempt})=>{if(attempt)return;if(++count===n)release();await promise;};}
function noSecrets(value){const s=typeof value==='string'?value:JSON.stringify(value);assert(!secrets.some(k=>s.includes(k)),'credential escaped allowed storage/issuance boundary');}
secrets.push('fixture-challenge-secret','fixture-admin-secret','fixture-maintenance-secret');

await test('Token uses 32 native random bytes, canonical encoding, deterministic native SHA-256 and strict parsing',async()=>{
 let size;const raw=C.generateCapability({getRandomValues(a){size=a.length;return crypto.getRandomValues(a);}});secrets.push(raw);assert.equal(size,32);assert.match(raw,/^mqic1_[A-Za-z0-9_-]{43}$/);assert.equal(C.parseCapability(raw),raw);const hash=await C.hashCapability(raw);secrets.push(hash);assert.equal(hash,createHash('sha256').update(raw).digest('hex'));assert.equal(await C.hashCapability(raw),hash);
 for(const value of [null,'',raw+'=',raw+' ',raw+','+raw,raw.slice(1),'mqic1_'+'A'.repeat(42)+'B','mqic1_'+'+'.repeat(43),crypto.randomUUID()])assert.throws(()=>C.parseCapability(value),e=>e.status===403);
 assert.throws(()=>C.generateCapability({getRandomValues(){throw Error('entropy');}}),e=>e.status===503);
});
await test('Strict flags and bounded quota config: only exact server true enables fixtures',async()=>{
 for(const value of [undefined,null,false,true,0,1,'false','TRUE',' true ','yes',{},[]])assert.deepEqual(C.featureFlags({CAPABILITY_ISSUANCE_ENABLED:value,CAPABILITY_INGEST_ENABLED:value}),{issuance:false,ingest:false});
 assert.deepEqual(C.featureFlags({CAPABILITY_ISSUANCE_ENABLED:'true',CAPABILITY_INGEST_ENABLED:'true'}),{issuance:true,ingest:true});
 for(const v of [true,false,0,-1,NaN,Infinity,1.2,' 1','1x','01','99999999999999999'])assert.equal(C.boundedInteger(v,99),99);
 const f=fixture();try{f.env.CAPABILITY_ISSUANCE_ENABLED='false';const before=snapshot(f);await rejects(()=>issue(f),404);f.env.CAPABILITY_INGEST_ENABLED='false';await rejects(()=>admitCapabilityRequest(req(null,[event()],{body:{CAPABILITY_INGEST_ENABLED:'true'},headers:{CAPABILITY_INGEST_ENABLED:'true'}}),f.env),404);assert.equal(snapshot(f),before);}finally{f.close();}
 const config=JSON.parse(fs.readFileSync('server/anonymous-telemetry-poc/wrangler.jsonc'));assert.equal(config.vars.CAPABILITY_ISSUANCE_ENABLED,'false');assert.equal(config.vars.CAPABILITY_INGEST_ENABLED,'false');
});
await test('Activation allowlist/primitives/versions/bounds and challenge success/failure/context/replay/unavailability',async()=>{
 const a=activation(),d=await C.activationDigest(a);assert.equal(d,await C.activationDigest({...a,issuanceRequestId:crypto.randomUUID(),turnstileToken:'other'}));assert.notEqual(d,await C.activationDigest({...a,buildVersion:'c'.repeat(64)}));
 for(const patch of [{title:'private'},{allowAnonymousDataCollection:'true'},{schemaVersion:'3'},{activationVersion:'old'},{measurementContract:'old'},{governanceVersion:'old'},{disclosureVersion:'old'},{turnstileToken:3},{turnstileToken:'x'.repeat(2049)},{buildId:'bad'},{gameId:'other'},{buildVersion:'B'.repeat(64)}])assert.throws(()=>C.validateActivationRequest({...a,...patch}));
 for(const result of [{success:false,'error-codes':['timeout-or-duplicate']},{success:false},{success:true,action:'wrong'},{success:true,action:'mq_build_activate',hostname:'evil',cdata:d},{success:true,action:'mq_build_activate',hostname:'masteryquests.org',cdata:'wrong'}])await rejects(()=>C.verifyActivationChallenge(a,d,async()=>result),403);
 await rejects(()=>C.verifyActivationChallenge(a,d,async()=>{throw Error('provider');}),503);await rejects(()=>C.verifyActivationChallenge(a,d),503);
 let used=false;const once=async p=>{if(used)return{success:false};used=true;return verifier(p);};await C.verifyActivationChallenge(a,d,once);await rejects(()=>C.verifyActivationChallenge(a,d,once),403);
 await rejects(()=>C.readBoundedJSON(new Request('http://fixture.test',{method:'POST',body:'x'.repeat(8193),headers:{'content-type':'application/json'}}),8192),413);
});
await test('Additive migration preserves prior schemas, historical valid/legacy/malformed JSON and NULL receipts',async()=>{
 const f=fixture(false);try{
 const e=event();for(const [i,x]of ['{"manifestID":"abc"}','{"legacy":true}','{broken'].entries())f.db.prepare(`INSERT INTO telemetry_events(event_id,run_id,anonymous_client_id,build_id,build_version,schema_version,phase,game_id,mode,event_type,sequence_number,event_timestamp,extras_json) VALUES(?,?,?,?,?,3,?,?,?,?,?,?,?)`).run(crypto.randomUUID(),e.runId,e.anonymousClientId,e.buildId,e.buildVersion,PHASE,e.gameId,'standard','run_manifest',i+1,e.eventTimestamp,x);
 f.db.prepare('INSERT INTO telemetry_ingest_batches(batch_id,anonymous_client_id,event_count,inserted_count,duplicate_count) VALUES(?,?,3,3,0)').run(crypto.randomUUID(),e.anonymousClientId);
 const rows=JSON.stringify(f.db.prepare('SELECT * FROM telemetry_events').all()),cols=JSON.stringify(f.db.prepare('PRAGMA table_info(telemetry_events)').all());
 f.db.exec(fs.readFileSync(path.join(migrationDir,migrations[2]),'utf8'));assert.equal(JSON.stringify(f.db.prepare('SELECT * FROM telemetry_events').all()),rows);assert.equal(JSON.stringify(f.db.prepare('PRAGMA table_info(telemetry_events)').all()),cols);assert.equal(f.db.prepare('SELECT capability_id FROM telemetry_ingest_batches').get().capability_id,null);assert.equal(f.db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');
 assert(f.db.prepare("SELECT name FROM sqlite_master WHERE type='index'").all().some(r=>r.name.includes('manifest')));
 }finally{f.close();}
});
await test('Isolated issuance stores digest only, one-year expiry, duplicate/conflict and fresh replacement',async()=>{
 const f=fixture();try{const a=activation(),c=await C.issueBuildCapability(a,f.env,{verifyChallenge:verifier});secrets.push(c.capability,await C.hashCapability(c.capability));const row=f.db.prepare('SELECT * FROM telemetry_build_capabilities').get();assert.equal(row.expires_at-row.issued_at,365*86400);assert.equal(row.capability_hash,await C.hashCapability(c.capability));assert(!snapshot(f).includes(c.capability));await rejects(()=>C.issueBuildCapability(a,f.env,{verifyChallenge:verifier}),409,'activation_already_issued');await rejects(()=>C.issueBuildCapability({...a,buildVersion:'c'.repeat(64)},f.env,{verifyChallenge:verifier}),409,'activation_conflict');await issue(f);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM telemetry_build_capabilities').get().n,2);}finally{f.close();}
});
await test('Concurrent duplicate issuance persists exactly one capability and one issuance window increment',async()=>{
 const f=fixture();try{const a=activation(),afterRead=barrier(),r=await Promise.allSettled([1,2].map(()=>C.issueBuildCapability(a,f.env,{verifyChallenge:verifier,afterRead})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.find(x=>x.status==='rejected').reason.status,409);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM telemetry_build_capabilities').get().n,1);assert(f.db.prepare('SELECT request_count FROM telemetry_scope_windows').all().every(r=>r.request_count===1));}finally{f.close();}
});
await test('Atomic issuance live cap, build/global quotas and blocked policy',async()=>{
 for(const setting of ['LIVE_PER_TUPLE','ISSUES_BUILD_DAY','ISSUES_GLOBAL_HOUR','ISSUES_GLOBAL_DAY']){const f=fixture();try{f.env['MQ_CAP_'+setting]='1';const afterRead=barrier(),r=await Promise.allSettled([1,2].map(()=>issue(f,{}, {afterRead})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.find(x=>x.status==='rejected').reason.status,429);}finally{f.close();}}
 const f=fixture();try{await issue(f);f.db.exec('UPDATE telemetry_build_policies SET blocked_at=created_at');await rejects(()=>issue(f),403);}finally{f.close();}
});
await test('Exact tuple admission, same-owner addition, exact retry preserves summaries and retention receipts',async()=>{
 const f=fixture();try{const c=await issue(f),e=event();assert.equal((await admit(f,c,[e])).accepted,1);const run=JSON.stringify(f.db.prepare('SELECT * FROM telemetry_runs').all()),rows=JSON.stringify(f.db.prepare('SELECT * FROM telemetry_events').all());f.clock.now+=1;const r=await admit(f,c,[e]);assert.equal(r.accepted,0);assert.deepEqual(r.acknowledgedEventIds,[e.eventId]);assert.equal(JSON.stringify(f.db.prepare('SELECT * FROM telemetry_runs').all()),run);assert.equal(JSON.stringify(f.db.prepare('SELECT * FROM telemetry_events').all()),rows);const row=f.db.prepare('SELECT * FROM telemetry_build_capabilities').get();assert.equal(row.accepted_event_count,1);assert.equal(row.accepted_request_count,2);assert.equal((await admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber:2}])).accepted,1);assert.equal(f.db.prepare('SELECT event_count FROM telemetry_runs').get().event_count,2);}finally{f.close();}
});
await test('Missing/malformed/operator-ID credentials and wrong raw tuple/schema are rejected without writes',async()=>{
 const f=fixture();try{const c=await issue(f),before=snapshot(f);for(const token of [undefined,'bad',c.capabilityId])await rejects(()=>admitCapabilityRequest(req(token,[event()]),f.env),403);
 for(const patch of [{gameId:'other'},{buildId:'composer-'+'c'.repeat(64)},{buildVersion:'c'.repeat(64)},{schemaVersion:2},{schemaVersion:'3'},{buildId:' '+tuple.buildId}])await assert.rejects(()=>admit(f,c,[event(patch)]));assert.equal(snapshot(f),before);
 }finally{f.close();}
});
await test('Expiry/revocation/block status and admission fail closed',async()=>{
 for(const state of ['expiry','revoked','blocked']){const f=fixture();try{const c=await issue(f);if(state==='expiry')f.clock.now+=365*86400;else f.db.exec(state==='revoked'?'UPDATE telemetry_build_capabilities SET revoked_at=issued_at':'UPDATE telemetry_build_policies SET blocked_at=created_at');const before=snapshot(f);await rejects(()=>admit(f,c,[event()]),403);assert.equal(snapshot(f),before);}finally{f.close();}}
});
for(const field of ['buildId','gameId','buildVersion','anonymousClientId'])await test('Immutable run ownership rejects changed '+field,async()=>{
 const f=fixture();try{const c=await issue(f),e=event();await admit(f,c,[e]);const stored={buildId:'composer-'+'c'.repeat(64),gameId:'other',buildVersion:'c'.repeat(64),anonymousClientId:crypto.randomUUID()};const snake={buildId:'build_id',gameId:'game_id',buildVersion:'build_version',anonymousClientId:'anonymous_client_id'}[field];f.db.prepare('UPDATE telemetry_runs SET '+snake+'=?').run(stored[field]);const before=snapshot(f);await rejects(()=>admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber:2}]),409);assert.equal(snapshot(f),before);}finally{f.close();}
});
await test('Historically mixed events reject even if the summary owner matches',async()=>{const f=fixture();try{const c=await issue(f),e=event();await admit(f,c,[e]);f.db.prepare('UPDATE telemetry_events SET anonymous_client_id=?').run(crypto.randomUUID());const before=snapshot(f);await rejects(()=>admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber:2}]),409);assert.equal(snapshot(f),before);}finally{f.close();}});
await test('Changed event payload and run/sequence collisions conflict; canonical extras ordering retries exactly',async()=>{const f=fixture();try{const c=await issue(f),e=event();await admit(f,c,[e]);for(const patch of [{score:1},{eventId:crypto.randomUUID()},{runId:crypto.randomUUID()}])await rejects(()=>admit(f,c,[{...e,...patch}]),409);const x=JSON.parse(f.db.prepare('SELECT extras_json FROM telemetry_events').get().extras_json);f.db.prepare('UPDATE telemetry_events SET extras_json=?').run(JSON.stringify(Object.fromEntries(Object.entries(x).reverse())));assert.equal((await admit(f,c,[e])).accepted,0);}finally{f.close();}});
for(const kind of ['identical','sequence','payload','owner'])await test('Deterministic concurrent first-write race: '+kind,async()=>{
 const f=fixture();try{const c=await issue(f),e=event(),other={...e};if(kind==='sequence')other.eventId=crypto.randomUUID();if(kind==='payload')other.score=1;if(kind==='owner'){other.anonymousClientId=crypto.randomUUID();other.eventId=crypto.randomUUID();other.sequenceNumber=2;}const afterRead=barrier(),r=await Promise.allSettled([e,other].map(e=>admit(f,c,[e],{afterRead})));const ok=r.filter(x=>x.status==='fulfilled');assert.equal(ok.length,kind==='identical'?2:1);assert.equal(ok.reduce((n,x)=>n+x.value.accepted,0),1);if(kind!=='identical')assert.equal(r.find(x=>x.status==='rejected').reason.status,409);assert.equal(f.db.prepare('SELECT event_count FROM telemetry_runs').get().event_count,1);assert.equal(f.db.prepare('SELECT accepted_event_count FROM telemetry_build_capabilities').get().accepted_event_count,1);}finally{f.close();}
});
for(const state of ['revoke','block','expiry'])await test('Admission rechecks '+state+' between lookup and transaction',async()=>{const f=fixture();try{const c=await issue(f);let before;await rejects(()=>admit(f,c,[event()],{afterRead:async({attempt})=>{if(attempt)return;if(state==='expiry')f.clock.now+=365*86400;else f.db.exec(state==='revoke'?'UPDATE telemetry_build_capabilities SET revoked_at=issued_at':'UPDATE telemetry_build_policies SET blocked_at=created_at');before=snapshot(f);}}),403);assert.equal(snapshot(f),before);}finally{f.close();}});
for(const limit of ['CAP_ACCEPTED_EVENTS','BUILD_ACCEPTED_EVENTS','CAP_EVENTS_MINUTE','BUILD_EVENTS_MINUTE','GLOBAL_EVENTS_MINUTE','GLOBAL_REQUESTS_MINUTE','CAP_REQUESTS_MINUTE'])await test('Atomic concurrent quota: '+limit,async()=>{const f=fixture();try{f.env['MQ_CAP_'+limit]='1';const c=await issue(f),afterRead=barrier(),r=await Promise.allSettled([event(),event()].map(e=>admit(f,c,[e],{afterRead})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.find(x=>x.status==='rejected').reason.status,429);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM telemetry_events').get().n,1);}finally{f.close();}});
for(const [table,operation]of [['telemetry_events','INSERT'],['telemetry_runs','UPDATE'],['telemetry_build_capabilities','UPDATE'],['telemetry_build_policies','UPDATE'],['telemetry_ingest_batches','INSERT'],['telemetry_scope_windows','UPDATE']])await test('SQL failure rolls back all dependent writes: '+table,async()=>{const f=fixture();try{const c=await issue(f),e=event();await admit(f,c,[e]);f.db.exec(`CREATE TRIGGER test_abort BEFORE ${operation} ON ${table} BEGIN SELECT RAISE(ABORT,'injected local failure'); END`);const before=snapshot(f);await rejects(()=>admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber:2}]),503);assert.equal(snapshot(f),before);}finally{f.close();}});

function manifests(){const configuration={recipeSchema:null,selectedConceptIds:[],contentScopes:{},policyFingerprint:null,samplingStrategies:{},supportedModes:['standard','exam'],dailyChallengesEnabled:null,checkpoints:{},fadingIntervals:{},startingBankroll:null,wagerRatios:[]};const base={manifestSchema:'mq-run-manifest/1',contractID:'mq-measurement/1',measurementRevision:'mq-tracker-2026.09.10-contract1',engineRevision:'a'.repeat(64),trackerSourceRevision:'b'.repeat(64),assetRevision:'c'.repeat(64),contentRevision:'d'.repeat(64),configuration,configurationRevision:contractHash(configuration)};const buildVersion=contractHash(base);return ['standard','exam'].map(mode=>({...base,buildRevision:buildVersion,mode,modeParameters:{quizTarget:null}}));}
await test('Multiple runtime manifests bind to one immutable revision; altered revisions and ID-only authority reject',async()=>{
 const ms=manifests(),t={...tuple,buildVersion:ms[0].buildRevision};for(const m of ms)C.validateRuntimeManifest(m,contractHash(m),t);assert.notEqual(contractHash(ms[0]),contractHash(ms[1]));for(const field of ['engineRevision','contentRevision','configurationRevision']){const m={...ms[0],[field]:'f'.repeat(64)};assert.throws(()=>C.validateRuntimeManifest(m,contractHash(m),t));}
 const f=fixture();try{const c=await issue(f,t);for(const m of ms){const e=event({...t,mode:m.mode,eventType:'run_manifest',manifestID:contractHash(m),manifestJSON:JSON.stringify(m),provenanceStatus:'measured-segment'});assert.equal((await admit(f,c,[e])).accepted,1);assert.equal((await admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber:2,eventType:'run_started',manifestJSON:undefined}])).accepted,1);}await rejects(()=>admit(f,c,[event({...t,manifestID:contractHash(ms[0])})]),403);}finally{f.close();}
});
await test('Null-manifest exception admits only unresolved empty-context lifecycle',async()=>{const f=fixture();try{const c=await issue(f);for(const patch of [{eventType:'answer_evaluated'},{eventType:'resource_viewed'},{questionId:'q'},{selectedResponse:1},{provenanceStatus:'measured-segment'},{presentationID:'p'}])await rejects(()=>admit(f,c,[event(patch)]),403);}finally{f.close();}});
await test('Legacy HTTP parity before/after migration with flags OFF and arbitrary capability headers; CORS unchanged',async()=>{
 const headers=[];for(const migrated of [false,true]){const f=fixture(migrated);try{f.env.CAPABILITY_INGEST_ENABLED='false';f.env.CAPABILITY_ISSUANCE_ENABLED='false';const e=event({gameId:'cost-directive',buildId:'legacy-fixture',buildVersion:'legacy',schemaVersion:1});for(const cap of [undefined,'arbitrary']){const r=await worker.fetch(req(cap,[e]),f.env);assert.equal(r.status,202);assert.equal((await r.json()).accepted,cap?0:1);}assert.equal((await worker.fetch(new Request('http://fixture.test/v1/build-capabilities',{method:'POST',body:JSON.stringify(activation())}),f.env)).status,404);
 for(const origin of ['https://masteryquests.org','https://www.masteryquests.org','null','https://other.invalid']){const r=await worker.fetch(new Request('http://fixture.test/v1/events',{method:'OPTIONS',headers:{origin,'access-control-request-headers':'x-mq-ingest-token'}}),f.env);assert.equal(r.status,origin.includes('masteryquests.org')?204:403);assert(!String(r.headers.get('access-control-allow-headers')).includes('x-mq-ingest-token'));}
 const r=await worker.fetch(new Request('http://fixture.test/v1/admin/export.csv?buildId=legacy-fixture&includeSynthetic=1',{headers:{authorization:'Bearer '+f.env.ADMIN_TOKEN}}),f.env);headers.push((await r.text()).split('\r\n')[0]);if(migrated){assert.equal(f.db.prepare('SELECT COUNT(*) n FROM telemetry_build_capabilities').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM telemetry_scope_windows').get().n,0);}
 }finally{f.close();}}assert.equal(headers[0],headers[1]);
});
await test('Ingest capability has no admin/control/issuance authority; admin plus distinct maintenance required',async()=>{
 const f=fixture();try{const c=await issue(f);for(const p of ['summary','anomalies','export.csv','runs/'+crypto.randomUUID(),'runs/'+crypto.randomUUID()+'/reconstruct','retention','cleanup','delete-run','capabilities','capabilities/revoke','builds/block']){const r=await worker.fetch(new Request('http://fixture.test/v1/admin/'+p,{headers:{authorization:'Bearer '+c.capability,'x-telemetry-maintenance':c.capability}}),f.env);assert.equal(r.status,401);noSecrets(await r.text());}
 await rejects(()=>C.issueBuildCapability(activation({turnstileToken:c.capability}),f.env),503);
 const control=()=>C.controlCapability(new Request('http://fixture.test',{headers:{authorization:'Bearer '+f.env.ADMIN_TOKEN,'x-telemetry-maintenance':f.env.MAINTENANCE_TOKEN}}),f.env,'block',tuple);
 await rejects(()=>C.controlCapability(req(c.capability,[event()]),f.env,'revoke',{capabilityId:c.capabilityId}),401);const m=f.env.MAINTENANCE_TOKEN;f.env.MAINTENANCE_TOKEN=f.env.ADMIN_TOKEN;await rejects(control,403);f.env.MAINTENANCE_TOKEN=m;await control();assert.equal(f.db.prepare('SELECT revoked_at FROM telemetry_build_capabilities').get().revoked_at,f.clock.now);
 await C.controlCapability(new Request('http://fixture.test',{headers:{authorization:'Bearer '+f.env.ADMIN_TOKEN,'x-telemetry-maintenance':m}}),f.env,'unblock',tuple);assert.notEqual(f.db.prepare('SELECT revoked_at FROM telemetry_build_capabilities').get().revoked_at,null);
 }finally{f.close();}
});
await test('Secrets absent from telemetry/receipts/CSV/errors/logs and publishable snapshots',async()=>{
 const f=fixture();try{const c=await issue(f),e=event();await admit(f,c,[e]);for(const secret of [c.capability,await C.hashCapability(c.capability),f.env.ADMIN_TOKEN,f.env.MAINTENANCE_TOKEN]){try{await admit(f,c,[{...e,questionId:secret}]);assert.fail('expected rejection');}catch(error){assert.equal(error.status,400);noSecrets(String(error));}}
 noSecrets(f.db.prepare('SELECT * FROM telemetry_events').all());noSecrets(f.db.prepare('SELECT * FROM telemetry_ingest_batches').all());const r=await worker.fetch(new Request('http://fixture.test/v1/admin/export.csv?buildId='+tuple.buildId+'&includeSynthetic=1',{headers:{authorization:'Bearer '+f.env.ADMIN_TOKEN}}),f.env);noSecrets(await r.text());
 const broken={...f.env,TELEMETRY_DB:{prepare(){throw Error(c.capability);}}};try{await admitCapabilityRequest(req(c.capability,[e]),broken);}catch(error){noSecrets(String(error));assert.equal(error.status,503);}
 noSecrets(logs);noSecrets(results);
 }finally{f.close();}
});

await test('Maximum 50-event batch commits accurate aggregates within D1 binding bounds',async()=>{const f=fixture();try{const c=await issue(f),e=event(),events=Array.from({length:50},(_,i)=>({...e,eventId:crypto.randomUUID(),sequenceNumber:i+1}));assert.equal((await admit(f,c,events)).accepted,50);assert.equal(f.db.prepare('SELECT event_count FROM telemetry_runs').get().event_count,50);assert.equal((await admit(f,c,events)).accepted,0);assert.equal(f.db.prepare('SELECT event_count FROM telemetry_runs').get().event_count,50);}finally{f.close();}});
await test('Canonical normalized byte ceilings are atomic at capability/build/global scopes',async()=>{
 for(const limit of ['CAP_ACCEPTED_BYTES','BUILD_ACCEPTED_BYTES','GLOBAL_ACCEPTED_BYTES']){const f=fixture();try{const c=await issue(f),e=event();await admit(f,c,[e]);const bytes=f.db.prepare('SELECT accepted_bytes FROM telemetry_build_capabilities').get().accepted_bytes;f.env['MQ_CAP_'+limit]=String(bytes);assert.equal((await admit(f,c,[e])).accepted,0);const before=snapshot(f);await rejects(()=>admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber:2}]),429);assert.equal(snapshot(f),before);}finally{f.close();}}
});
await test('Concurrent byte budget contenders cannot exceed one normalized row',async()=>{const f=fixture();try{const c=await issue(f),e=event();await admit(f,c,[e]);const bytes=f.db.prepare('SELECT accepted_bytes FROM telemetry_build_capabilities').get().accepted_bytes;f.env.MQ_CAP_GLOBAL_ACCEPTED_BYTES=String(bytes*2);const afterRead=barrier(),r=await Promise.allSettled([2,3].map(sequenceNumber=>admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber}],{afterRead})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.find(x=>x.status==='rejected').reason.status,429);assert.equal(f.db.prepare('SELECT accepted_bytes FROM telemetry_build_capabilities').get().accepted_bytes,bytes*2);}finally{f.close();}});
await test('Replacement tokens/revisions retain build and global cumulative budgets',async()=>{const f=fixture();try{const c=await issue(f);await admit(f,c,[event()]);const next=await issue(f,{buildVersion:'c'.repeat(64)});f.env.MQ_CAP_BUILD_ACCEPTED_EVENTS='1';await rejects(()=>admit(f,next,[event({buildVersion:'c'.repeat(64)})]),429);assert.equal(f.db.prepare('SELECT accepted_event_count FROM telemetry_build_policies').get().accepted_event_count,1);}finally{f.close();}});
await test('Existing client submitted-event limit is additional, atomic, and charges duplicates',async()=>{const f=fixture();try{f.env.MAX_EVENTS_PER_CLIENT_MINUTE='50';const c=await issue(f),e=event();await admit(f,c,[e]);const minute=Math.floor(f.clock.now/60);f.db.prepare('UPDATE telemetry_rate_limits SET event_count=49 WHERE window_minute=?').run(minute);const afterRead=barrier(),r=await Promise.allSettled([1,2].map(()=>admit(f,c,[e],{afterRead})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.find(x=>x.status==='rejected').reason.status,429);assert.equal(f.db.prepare('SELECT event_count FROM telemetry_rate_limits').get().event_count,50);assert.equal(f.db.prepare('SELECT event_count FROM telemetry_runs').get().event_count,1);}finally{f.close();}});
await test('Clock-window boundary retries under the new database window',async()=>{const f=fixture();try{const c=await issue(f);await admit(f,c,[event()],{afterRead:async({attempt})=>{if(!attempt)f.clock.now=Math.floor(f.clock.now/60)*60+60;}});assert.equal(f.db.prepare("SELECT window_start FROM telemetry_scope_windows WHERE scope_type='ingest-capability'").get().window_start,Math.floor(f.clock.now/60)*60);}finally{f.close();}});
await test('Orphaned or inflated historical summaries reject without normalization',async()=>{for(const operation of ['DELETE FROM telemetry_runs','UPDATE telemetry_runs SET event_count=7']){const f=fixture();try{const c=await issue(f),e=event();await admit(f,c,[e]);f.db.exec(operation);const before=snapshot(f);await rejects(()=>admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber:2}]),409);assert.equal(snapshot(f),before);}finally{f.close();}}});
await test('Issuance rollback covers policy, capability and window writes',async()=>{for(const table of ['telemetry_build_policies','telemetry_build_capabilities','telemetry_scope_windows']){const f=fixture();try{f.db.exec('CREATE TRIGGER issue_abort BEFORE INSERT ON '+table+" BEGIN SELECT RAISE(ABORT,'fixture SQL failure'); END");const before=snapshot(f);await rejects(()=>issue(f),503);assert.equal(snapshot(f),before);}finally{f.close();}}});
await test('Build blocked during issuance and flags flipped at commit reject all writes',async()=>{for(const kind of ['block','issuance','ingest']){const f=fixture();try{const c=await issue(f);let before;const afterRead=async({attempt})=>{if(attempt)return;if(kind==='block')f.db.exec('UPDATE telemetry_build_policies SET blocked_at=created_at');else f.env[kind==='issuance'?'CAPABILITY_ISSUANCE_ENABLED':'CAPABILITY_INGEST_ENABLED']='false';before=snapshot(f);};await rejects(()=>kind==='ingest'?admit(f,c,[event()],{afterRead}):issue(f,{}, {afterRead}),kind==='block'?403:404);assert.equal(snapshot(f),before);}finally{f.close();}}});
await test('Manifest insertion and dependent measured event commit together; changed configuration cannot rebind',async()=>{const f=fixture();try{const m=manifests()[0],t={...tuple,buildVersion:m.buildRevision},c=await issue(f,t),e=event({...t,eventType:'run_manifest',manifestID:contractHash(m),manifestJSON:JSON.stringify(m),provenanceStatus:'measured-segment'}),answer={...e,eventId:crypto.randomUUID(),eventType:'answer_evaluated',sequenceNumber:2,manifestJSON:undefined,questionId:'q',selectedResponse:0,correct:true};assert.equal((await admit(f,c,[answer,e])).accepted,2);const changed=structuredClone(m);changed.configuration.supportedModes.push('quiz');changed.configurationRevision=contractHash(changed.configuration);assert.throws(()=>C.validateRuntimeManifest(changed,contractHash(changed),t));}finally{f.close();}});
await test('Prior manifest deletion between lookup and commit invalidates the entire request',async()=>{const f=fixture();try{const m=manifests()[0],t={...tuple,buildVersion:m.buildRevision},c=await issue(f,t),e=event({...t,eventType:'run_manifest',manifestID:contractHash(m),manifestJSON:JSON.stringify(m)});await admit(f,c,[e]);let before;await rejects(()=>admit(f,c,[{...e,eventId:crypto.randomUUID(),sequenceNumber:2,eventType:'run_started',manifestJSON:undefined}],{afterRead:async({attempt})=>{if(attempt)return;f.db.exec('DELETE FROM telemetry_events');f.db.exec('DELETE FROM telemetry_runs');before=snapshot(f);}}),403);assert.equal(snapshot(f),before);}finally{f.close();}});


await test('Expiry during dependent SQL writes is caught by final permission guard and rolls back',async()=>{const f=fixture();try{const c=await issue(f);f.db.function('advance_clock',()=>{f.clock.now+=365*86400;return 1;});f.db.exec('CREATE TRIGGER expire_during_write AFTER INSERT ON telemetry_events BEGIN SELECT advance_clock(); END');const before=snapshot(f);await rejects(()=>admit(f,c,[event()]),403);assert.equal(snapshot(f),before);}finally{f.close();}});
await test('Concurrent different-build owners establish one run owner and reject global event-ID borrowing',async()=>{const f=fixture();try{const a=await issue(f),patch={buildId:'composer-'+'c'.repeat(64)},b=await issue(f,patch),e=event(),other={...e,...patch,eventId:crypto.randomUUID(),sequenceNumber:2},afterRead=barrier(),r=await Promise.allSettled([admit(f,a,[e],{afterRead}),admit(f,b,[other],{afterRead})]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.find(x=>x.status==='rejected').reason.status,409);const row=f.db.prepare('SELECT * FROM telemetry_events').get(),borrower=row.build_id===e.buildId?b:a,borrowed=event({buildId:borrower.buildId,eventId:row.event_id});await rejects(()=>admit(f,borrower,[borrowed]),409);assert.equal(f.db.prepare('SELECT event_count FROM telemetry_runs').get().event_count,1);}finally{f.close();}});
await test('Malformed JSON and deeply nested/oversized request bodies fail before admission',async()=>{const f=fixture();try{const c=await issue(f),before=snapshot(f);for(const body of ['{broken','['.repeat(33)+'0'+']'.repeat(33),'x'.repeat(131073)])await assert.rejects(()=>admitCapabilityRequest(new Request('http://fixture.test',{method:'POST',headers:{'content-type':'application/json','x-mq-ingest-token':c.capability},body}),f.env));assert.equal(snapshot(f),before);}finally{f.close();}});
await test('Flags-OFF valid legacy schemas 1/2/3 behave alike before and after additive migration',async()=>{for(const migrated of [false,true]){const f=fixture(migrated);try{delete f.env.CAPABILITY_INGEST_ENABLED;delete f.env.CAPABILITY_ISSUANCE_ENABLED;for(const schemaVersion of [1,2,3]){const e=event({schemaVersion,buildId:'legacy-build',buildVersion:'legacy',gameId:'cost-directive'});const r=await worker.fetch(req('arbitrary',[e]),f.env);assert.equal(r.status,202);assert.equal((await r.json()).accepted,1);}if(migrated)assert(f.db.prepare('SELECT capability_id FROM telemetry_ingest_batches').all().every(r=>r.capability_id===null));}finally{f.close();}}});

console.error=errorLog;const report={passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,localOnly:true,network:'external denied; no verifier network implementation',transactionFixture:'SQLite synchronous BEGIN IMMEDIATE / COMMIT in batch; no JavaScript lock or mutex; deterministic pre-batch barriers',maxBindings,maxBatch,results};fs.writeFileSync(path.join(out,'capabilities-results.json'),JSON.stringify(report,null,2)+'\n');log(JSON.stringify({passed:report.passed,failed:report.failed,maxBindings,maxBatch}));if(report.failed){for(const r of results.filter(r=>r.status==='FAIL'))log(r.detail);process.exitCode=1;}
