import fs from 'node:fs';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {randomUUID} from 'node:crypto';import {fileURLToPath} from 'node:url';import worker from '../../server/anonymous-telemetry-poc/worker.mjs';import {POLICY,approvedEnvironment,configuration,cutoffFor} from '../../server/anonymous-telemetry-poc/governance-policy.mjs';import {govern} from '../../server/anonymous-telemetry-poc/governance.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
export const now=Date.parse('2026-09-10T12:00:00.000Z'),cutoff=cutoffFor(configuration(approvedEnvironment()),now),old=new Date(Date.parse(cutoff)-30*86400000).toISOString(),recent=new Date(now-3600000).toISOString();
export function fixture(){const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync(path.join(root,'server/anonymous-telemetry-poc/migrations')).sort())db.exec(fs.readFileSync(path.join(root,'server/anonymous-telemetry-poc/migrations',f),'utf8'));
 class Statement{constructor(sql){this.sql=sql;this.values=[];}bind(...values){this.values=values;return this;}async first(){return db.prepare(this.sql).get(...this.values)||null;}async all(){return{success:true,results:db.prepare(this.sql).all(...this.values)};}async run(){return /^SELECT/i.test(this.sql.trim())?this.all():{success:true,meta:{changes:Number(db.prepare(this.sql).run(...this.values).changes)}};}}
 let tail=Promise.resolve();
 const env={...approvedEnvironment(),ADMIN_TOKEN:'synthetic-admin-fixture',MAINTENANCE_TOKEN:'synthetic-maintenance-fixture',TELEMETRY_DB:{prepare:s=>new Statement(s),batch(ss){const task=tail.then(async()=>{db.exec('BEGIN');try{const result=[];for(const s of ss)result.push(await s.run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}});tail=task.catch(()=>{});return task;}}};
 const client=randomUUID(),ids={};function run(name,times,version=3,completed=1){const id=ids[name]=randomUUID();db.prepare('INSERT INTO telemetry_runs(run_id,anonymous_client_id,build_id,build_version,game_id,mode,first_event_at,last_event_at,last_received_at,completed,synthetic) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,client,'synthetic-governance','fixture','cost-directive','standard',times[0],times.at(-1),times.at(-1),completed,1);times.forEach((time,i)=>db.prepare('INSERT INTO telemetry_events(event_id,run_id,anonymous_client_id,build_id,build_version,schema_version,phase,game_id,mode,event_type,sequence_number,event_timestamp,received_at,synthetic) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),id,client,'synthetic-governance','fixture',version,'phaseAnonymousTelemetryPOC-v1','cost-directive','standard','run_started',i+1,time,time,1));return id;}
 run('legacyOld',[old,old],1);run('straddling',[old,recent]);run('new',[recent]);run('incomplete',[old],2,0);run('boundary',[cutoff]);run('currentOld',[old]);
 for(const t of [old,recent])db.prepare('INSERT INTO telemetry_ingest_batches(batch_id,anonymous_client_id,event_count,inserted_count,duplicate_count,synthetic,received_at) VALUES(?,?,1,1,0,1,?)').run(randomUUID(),client,t);
 for(const t of [old,recent])db.prepare('INSERT INTO telemetry_rate_limits VALUES(?,?,1)').run(client,Math.floor(Date.parse(t)/60000));
 const request=body=>new Request('http://synthetic.test/v1/admin/retention',{method:'POST',body:JSON.stringify(body)});
 const call=(kind,body)=>govern(request(body),env,kind,now);
 const route=(url,body,auth=true,maintenance)=>worker.fetch(new Request('http://synthetic.test'+url,{method:body?'POST':'GET',headers:{...(auth?{authorization:'Bearer '+env.ADMIN_TOKEN}:{}),...(maintenance?{'x-telemetry-maintenance':maintenance}:{})},body:body?JSON.stringify(body):undefined}),env);
 return{db,env,ids,run,call,route,close:()=>db.close()};}
