import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright'),root=process.cwd(),out=path.resolve('validation_artifacts/free_faculty_template_parity/browser');fs.mkdirSync(out,{recursive:true});
const results=[],errors=[],requests=[],badAssets=[];
const server=http.createServer((req,res)=>{const requested=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!requested.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const file=fs.statSync(requested).isDirectory()?path.join(requested,'index.html'):requested;res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'msedge',headless:true});
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',detail:e.stack});}console.log(name+': '+results.at(-1).status);fs.writeFileSync(out+'/results.json',JSON.stringify({results,errors,requests,badAssets},null,2));}
async function open(width=1440,file='mastery-quests-faculty-starter.html'){
 const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});await context.route('**/*',r=>{const request=r.request();requests.push({url:request.url(),method:request.method(),type:request.resourceType()});return new URL(request.url()).origin===origin?r.continue():r.abort();});const page=await context.newPage();page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)badAssets.push(r.url());});await page.goto(origin+'/downloads/resources/'+file);return {page,context};
}
async function start(page,mode){await page.locator('#playerNameInput').fill('Faculty QA');await page.getByRole('button',{name:'START GAME',exact:true}).click();await page.evaluate(mode=>startSelectedMode(mode,{quizConfirmed:true,fadingFortuneConfirmed:true,riskRewardConfirmed:true,trialGraphConfirmed:true}),mode);if(await page.locator('#guideIntroProceed').isVisible())await page.locator('#guideIntroProceed').click();await page.waitForFunction(()=>Boolean(currentQuestion));if(mode==='riskReward')await page.evaluate(()=>lockRiskRewardWager(.1));await page.waitForFunction(()=>document.querySelectorAll('#answers button').length===4);}
async function correct(page){await page.evaluate(()=>{questionStartTime=Date.now()-6500;});const i=await page.evaluate(async()=>{for(let i=0;i<4;i++)if(await isQuestionAnswerCorrect(currentQuestion,i))return i;throw Error('No correct answer');});await page.locator('#answers button').nth(i).click();}
try{
 await test('Downloaded standalone file launches offline without server dependencies',async()=>{const context=await browser.newContext(),page=await context.newPage(),remote=[];try{page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>{if(/^https?:/.test(r.request().url())){remote.push(r.request().url());return r.abort();}return r.continue();});await page.goto(pathToFileURL(path.resolve('downloads/resources/mastery-quests-faculty-starter.html')).href);await start(page,'standard');await correct(page);assert(await page.evaluate(()=>totalAttempts>0));assert.deepEqual(remote,[]);}finally{await context.close();}});
 await test('Blank loads and blocks launch with missing pool guidance',async()=>{const {page,context}=await open(1440,'mastery-quests-faculty-template.html');try{const r=await page.evaluate(()=>validateFacultyMode('standard'));assert(r===false||r?.ok===false||r?.valid===false||Array.isArray(r)&&r.length);await page.screenshot({path:out+'/blank.png'});}finally{await context.close();}});
 for(const mode of ['standard','timed','exam','quiz','unlimited','legendary','score','trialGraph','fadingFortune','riskReward'])await test(mode+' launches with four answers and accepts an answer',async()=>{const {page,context}=await open();try{await start(page,mode);await correct(page);assert(await page.evaluate(mode=>mode==='exam' ? Number.isInteger(getExamRoomState(room)?.selectedIndex) : totalAttempts>0,mode));if(['standard','trialGraph'].includes(mode))await page.screenshot({path:out+'/'+mode+'.png'});}finally{await context.close();}});
 await test('Standard keyboard launch, wrong-answer feedback and adaptive route',async()=>{const {page,context}=await open();try{await page.locator('#playerNameInput').fill('Faculty QA');await page.getByRole('button',{name:'START GAME',exact:true}).focus();await page.keyboard.press('Enter');await page.locator('[data-mode="standard"]').focus();await page.keyboard.press('Enter');if(await page.locator('#guideIntroProceed').isVisible())await page.locator('#guideIntroProceed').click();await page.waitForFunction(()=>Boolean(currentQuestion));await page.evaluate(()=>{questionStartTime=Date.now()-6500;});const wrong=await page.evaluate(async()=>{for(let i=0;i<4;i++)if(!await isQuestionAnswerCorrect(currentQuestion,i))return i;});await page.locator('#answers button').nth(wrong).click();await page.waitForTimeout(1800);assert(await page.evaluate(()=>totalAttempts>0));assert((await page.locator('#message').innerText()).trim());for(let attempt=0;attempt<4 && !await page.evaluate(()=>remediationState.active);attempt++){const proceed=page.getByRole('button',{name:'Continue',exact:true});if(await proceed.isVisible())await proceed.click();await page.evaluate(()=>{questionStartTime=Date.now()-30000;});const wrongIndex=await page.evaluate(async()=>{for(let i=0;i<4;i++)if(!await isQuestionAnswerCorrect(currentQuestion,i))return i;});await page.locator('#answers button').nth(wrongIndex).click();await page.waitForTimeout(1800);}assert(await page.evaluate(()=>remediationState.active));const stages=[];for(let step=0;step<3 && await page.evaluate(()=>remediationState.active);step++){stages.push(await page.evaluate(()=>remediationState.stage));await correct(page);await page.waitForTimeout(300);}assert(stages.includes('bridge'));const state=await page.evaluate(()=>({adaptiveMode,remediationState,room}));state.testedStages=stages;fs.writeFileSync(out+'/adaptive.json',JSON.stringify(state,null,2));await page.screenshot({path:out+'/feedback.png'});}finally{await context.close();}});
 await test('Standard save refresh and resume restores progress and run identity',async()=>{const {page,context}=await open();try{await start(page,'standard');await correct(page);await page.waitForTimeout(1800);const before=await page.evaluate(()=>{saveGameState();return {room,runID,correctAnswers};});await page.reload();await page.locator('#continueRunBtn').click();if(await page.locator('#guideIntroProceed').isVisible())await page.locator('#guideIntroProceed').click();await page.waitForFunction(()=>Boolean(currentQuestion));const after=await page.evaluate(()=>({room,runID,correctAnswers}));assert.deepEqual(after,before);fs.writeFileSync(out+'/save-resume.json',JSON.stringify({before,after},null,2));}finally{await context.close();}});
 await test('Graph renders embedded asset, descriptive alt, dialog and Escape',async()=>{const {page,context}=await open(390);try{await start(page,'trialGraph');const graph=page.locator('#question img, #gameBox img.question-graph, .question-graph').first();const images=await page.locator('img').evaluateAll(nodes=>nodes.filter(n=>n.src.startsWith('data:image/svg')).map(n=>({id:n.id,alt:n.alt,loaded:n.complete&&n.naturalWidth>0})));assert(images.some(i=>i.loaded&&i.alt.includes('Bar chart')));await page.evaluate(()=>{const img=[...document.images].find(n=>n.alt.includes('Bar chart'));img.click();});await page.waitForTimeout(100);assert(await page.getByText('Group A contains 2 items.',{exact:false}).count()>0);await page.keyboard.press('Escape');await page.screenshot({path:out+'/mobile-graph.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}finally{await context.close();}});
 await test('One-question Quiz completes through answer and offers local CSV download',async()=>{const {page,context}=await open();try{await page.evaluate(()=>setQuizQuestionCount(1));await start(page,'quiz');await correct(page);await page.waitForTimeout(2300);await page.screenshot({path:out+'/completion.png'});const controls=await page.getByRole('button').allTextContents();fs.writeFileSync(out+'/completion-controls.json',JSON.stringify(controls));if(await page.getByRole('button',{name:'View Mastery Report',exact:false}).isVisible().catch(()=>false))await page.getByRole('button',{name:'View Mastery Report',exact:false}).click();const button=page.getByRole('button',{name:'Download Game Data',exact:true}).last();await button.waitFor({state:'visible'});await page.screenshot({path:out+'/completion.png'});const [download]=await Promise.all([page.waitForEvent('download'),button.click()]);await download.saveAs(out+'/manual-game-data.csv');assert(fs.readFileSync(out+'/manual-game-data.csv','utf8').includes('event'));}finally{await context.close();}});
 await test('Validator UI valid, malformed, duplicate, graph and bad index; keyboard and narrow layout',async()=>{const {page,context}=await open(390);try{await page.goto(origin+'/tools/question-bank-validator/');const sample=JSON.parse(fs.readFileSync('downloads/resources/faculty-question-package-example.json'));for(const [name,mutate,expected] of [['valid',p=>p,'No structural errors'],['bad index',p=>{p.banks.medium[0].a=4;return p;},'a/aHash'],['duplicate',p=>{p.banks.medium[0].id=p.banks.easy[0].id;return p;},'duplicate ID'],['graph accessibility',p=>{delete p.questionAssetMetadata['sample-bars.svg'].imageAlt;return p;},'imageAlt']]){await page.locator('#source').fill(JSON.stringify(mutate(structuredClone(sample))));await page.locator('#validate').focus();await page.keyboard.press('Enter');assert((await page.locator('main').innerText()).includes(expected),name);}await page.locator('#source').fill('{broken');await page.locator('#validate').click();assert((await page.locator('#status').innerText()).includes('JSON could not be read'));await page.screenshot({path:out+'/validator-invalid-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}finally{await context.close();}});
 await test('No runtime errors, bad assets or unintended telemetry requests',()=>{assert.deepEqual(errors,[]);assert.deepEqual(badAssets,[]);assert(!requests.some(r=>r.method==='POST'||new URL(r.url).origin!==origin));});
}finally{await browser.close();server.close();}
if(results.some(r=>r.status!=='PASS'))process.exitCode=1;
