import json,hashlib
from pathlib import Path
H=Path(__file__).parent
scope={r['id']:r for r in json.loads((H/'scope.json').read_text(encoding='utf-8'))};P={}
tiers={'PMOE-POL-L-004':'elite','PM2A-SRPC-EB-009':'medium','PM2B3-PROD-EB-001':'medium','ECON-NL-EASYBOSS-2013':'medium','PM2C2-ICOST-EB-002':'medium','PM2A-EXP-EB-006':'hard','LG-Q-9105':'elite','LG-Q-9102':'hard','LG-Q-9010':'hard','LG-Q-9130':'medium','PMOE-NER-LB-001':'elite','P52A-AD-L-004':'medium','P52A-AD-L-006':'hard','PM2A-LRPC-L-010':'hard','PM2A-LRPC-L-011':'elite','P77-MVM-L-020':'medium','P76-MODL-EL-003':'hard','ECON-NL-EASYBOSS-2026':'medium','ECON-SP-MEDIUMBOSS-3011':'medium','ECON-SP-FINALBOSS-4016':'hard'}
def put(i,**kw): P.setdefault(i,{}).update(kw)
for i,t in tiers.items():
 put(i,canonicalDifficulty=t)
 # Legacy boss difficulty strings encode checkpoint stage. Preserve those.
 if 'boss' not in scope[i]['q']['difficulty'].lower():put(i,difficulty=t)
 old=scope[i]['q'];stage='legendaryBoss' if old['instructionalRole']=='legendaryBoss' else old['sourcePool']
 if old['instructionalRole'] in ['boss','legendaryBoss'] and stage in ['easyBoss','mediumBoss','finalBoss','legendaryBoss'] and t!={'easyBoss':'easy','mediumBoss':'medium','finalBoss':'hard','legendaryBoss':'legendary'}[stage]:
  put(i,checkpointPool=stage)
def rewrite(i,q,key,wrong,feedback,operation,type='analysis',**kw):
 old=scope[i]['q'];idx=next(j for j,x in enumerate(old['options']) if hashlib.sha256(' '.join(x.strip().lower().split()).encode()).hexdigest()==old['aHash'])
 options=wrong.copy();options.insert(idx,key)
 put(i,q=q,options=options,feedback=feedback,type=type,commonError=operation,operation=operation,**kw)
put('PMOE-POL-L-004',commonError='Assuming opposing net-capital-outflow effects must exactly offset, or that one must dominate without their magnitudes.',q='In the short run, suppose monetary tightening raises the domestic real interest rate while political risk simultaneously rises. Assuming other determinants of net capital outflow are unchanged, what can be concluded about the domestic currency?',options=['It is unchanged because the two effects necessarily offset each other','Its direction is ambiguous because the higher real interest rate reduces NCO while greater political risk raises NCO','It appreciates because the interest-rate effect must dominate the risk effect','It depreciates because political risk affects currency demand but not capital flows'],feedback='A higher domestic real interest rate tends to reduce net capital outflow and appreciate the currency. Greater political risk tends to raise net capital outflow and depreciate it. Without the magnitudes, the net currency movement is ambiguous.')
rewrite('LG-Q-9123','Assume stable velocity, long-run monetary neutrality, and the approximation that inflation equals money growth minus real output growth. Money grows 8% and real output grows 2% annually. A two-year wage contract raises nominal wages 5% in year 1. Before year 2, money growth permanently rises to 11%, while real output growth stays 2%. The year-2 nominal raise equals year-1 inflation plus 1 percentage point. Using the approximate real-wage growth rate in each year, what happens to purchasing power, and what year-2 raise would preserve it?',
 'Real wages fall 1% in year 1 and 2% in year 2; a 9% year-2 raise would preserve purchasing power.',
 ['Real wages fall 1% in year 1 and rise 1% in year 2; a 6% year-2 raise would preserve purchasing power.','Real wages rise 5% in year 1 and 7% in year 2; any positive raise would preserve purchasing power.','Real wages fall 3% in year 1 and 4% in year 2; an 11% year-2 raise would preserve purchasing power.'],
 'Inflation is initially 8−2=6%, then 11−2=9%. The nominal raises are 5% and 6+1=7%. Approximate real-wage growth is therefore −1% and −2%. The backward-looking contract misses the inflation increase; matching year-2 inflation requires a 9% nominal raise.',
 'Confusing nominal raises with purchasing-power gains or indexing to past inflation when inflation accelerates.',type='multi-step')
rewrite('LG-Q-9107','In a hypothetical scarce-reserves system, deposits are $1,000 and reserves are $150. The required reserve ratio is 10%, and banks hold no desired excess reserves. The central bank sells $30 of bonds to banks, lowering their reserves without initially changing deposits, and cuts the required ratio to 8%. It also raises interest paid on reserves relative to unchanged loan yields. Which assessment separates the reserve constraint from the lending incentive?',
 'Excess reserves fall from $50 to $40; the ratio cut partly offsets the sale, while higher reserve interest further discourages lending.',
 ['Excess reserves fall from $50 to $40; the ratio cut partly offsets the sale, while higher reserve interest encourages more lending.','Excess reserves rise from $50 to $70; the ratio cut more than offsets the sale, while higher reserve interest discourages lending.','Excess reserves fall from $50 to $20; the ratio cut has no effect, while higher reserve interest encourages more lending.'],
 'Initially, excess reserves are 150−0.10×1,000=50. After the sale and ratio cut, they are 120−0.08×1,000=40. The ratio cut frees $20 and only partly offsets the $30 reserve drain. Higher reserve interest makes alternative lending less attractive; it does not itself remove reserve balances.',
 'Treating reserve capacity and the incentive to lend as the same channel.',type='multi-step')
rewrite('LG-Q-9122','Use MV=PY. In period 1, independently verified money is 200, velocity is 5, and real output is 500; the reported price index is 2.4. In period 2, money rises 20% and velocity falls 10%. Independently verified nominal spending is 1,080 and the price index is 2.16, while reported real output is 600. Which corrections reconcile both periods, and what is the corrected inflation rate?',
 'Period-1 price index: 2; period-2 real output: 500; inflation: 8%.',
 ['Period-1 price index: 2; period-2 real output: 600; inflation: 8%.','Period-1 price index: 2.4; period-2 real output: 500; inflation: −10%.','Period-1 price index: 2; period-2 real output: 500; inflation: 10%.'],
 'Period 1 gives P=200×5/500=2. Period 2 gives M=240 and V=4.5, so MV=1,080, agreeing with independently measured spending. Its verified P=2.16 requires Y=1,080/2.16=500. Corrected inflation is 2.16/2−1=8%; using the erroneous first price index would give a false decline.',
 'Using an inconsistent reported series as the base for a later growth calculation.',type='multi-step')
rewrite('PM2B4-UTYPE-LB-001','Demand is at its normal level. Each week, 40 qualified workers start searching for suitable existing vacancies. Average search lasts 6 weeks. A job-information service cuts that duration to 3 weeks without changing entries into search or job requirements. Another 180 job seekers lack the skills vacancies require. Assume steady flows, so the frictionally unemployed equal weekly entries times average search duration. What does the service change, and what would address the remaining mismatch?',
 'Frictional unemployment falls by 120; retraining addresses the 180 mismatched workers, while demand stimulus alone need not do so.',
 ['Frictional unemployment falls by 240; retraining addresses the 180 mismatched workers, while demand stimulus alone need not do so.','Frictional unemployment falls by 120; the information service also removes all structural unemployment without retraining.','Frictional unemployment stays unchanged; only stronger aggregate demand can shorten search when suitable vacancies already exist.'],
 'The steady search stock falls from 40×6=240 to 40×3=120. Better information reduces search time and frictional unemployment. It does not supply missing skills, so the separate structural mismatch calls for a skill response. At normal demand, an aggregate-demand increase is not a substitute for these targeted changes.',
 'Confusing shorter search spells with fewer entrants or with elimination of a skill mismatch.',type='multi-step')
rewrite('PMOE-RER-L-003','Country A has 9% inflation and Country B has 3% inflation. Let e be units of B currency per unit of A currency, and define A’s real exchange rate as e×P_A/P_B. Use the approximation that its percentage change is the percentage change in e plus A’s inflation minus B’s inflation. About how much must e fall to leave the real exchange rate unchanged? If e instead falls 2%, what happens to A’s real exchange rate and the relative price of A’s goods?',
 'A 6% fall is needed; a 2% fall means about 4% real appreciation, making A’s goods relatively dearer.',
 ['A 6% rise is needed; a 2% fall means about 4% real depreciation, making A’s goods relatively cheaper.','A 12% fall is needed; a 2% fall means about 10% real appreciation, making A’s goods relatively dearer.','A 6% fall is needed; a 2% fall means about 4% real depreciation, making A’s goods relatively cheaper.'],
 'Using percentage changes, real stability requires the nominal exchange-rate change plus 9 minus 3 to equal zero, so e must fall about 6%. With only a 2% fall, the real exchange rate rises about −2+9−3=4%. Under the stated quotation, that is real appreciation: A’s goods become more expensive relative to B’s.',
 'Reversing the exchange-rate quotation or treating nominal depreciation as sufficient for real depreciation.',type='multi-step',primarySkill='infer_nominal_change_from_real_stability',repairSkill='infer_nominal_change_from_real_stability',objective='RER.infer_nominal_change_from_real_stability',tag='real_exchange_rate')
put('PM2A-LRPC-L-011',feedback='Full anticipation makes expected inflation match actual inflation, eliminating the inflation surprise. The usual temporary unemployment decline is therefore muted or absent, leaving unemployment near its natural rate under the stated assumptions.')
put('PM2C2-NEUT-FB-004',q='Assume stable velocity, unchanged real productive capacity, and monetary neutrality in the long run. Using the quantity theory of money, how does a permanent increase in money growth differ from a one-time increase in the money supply?')
rewrite('ECON-SP-MEDIUMBOSS-3011','An expansionary monetary policy lowers firms’ borrowing rates, but investment remains unchanged because firms expect weak sales. Which link in the usual transmission chain has weakened?',
 'Lower borrowing rates have not led to more investment spending.',
 ['Higher borrowing rates have reduced investment spending.','More investment has failed to raise aggregate demand.','Higher aggregate demand has failed to increase money demand.'],
 'The rate reduction occurred, but expected weak sales kept firms from expanding investment. The weak link is from borrowing costs to investment, before any investment-driven AD increase.',
 'Assuming a lower borrowing rate guarantees investment even when expected sales weaken.',type='diagnostic',primarySkill='monetary_policy_transmission',repairSkill='monetary_policy_transmission',objective='LO35.2',tag='monetary_policy')
rewrite('ECON-SP-FINALBOSS-4016','In a textbook banking model, a reserve injection supports less deposit expansion than the no-leakage maximum because banks keep additional reserves. At the same time, government borrowing puts upward pressure on interest rates, partly offsetting the downward rate pressure from monetary expansion. Why can investment rise less than a prediction that ignores both effects?',
 'Additional reserve holding limits deposit expansion, and government borrowing weakens the fall in rates that would encourage investment.',
 ['Additional reserve holding raises the deposit multiplier, while government borrowing weakens the fall in rates that would encourage investment.','Additional reserve holding limits deposit expansion, while government borrowing reinforces the fall in rates and crowds investment in.','Both effects operate only after investment rises, so neither can weaken the transmission from monetary policy to spending.'],
 'Reserve retention weakens the reserve-to-deposit link. Government borrowing can crowd out investment by pushing rates up relative to the monetary-expansion-only case. These constraints affect different steps, so the simple prediction overstates the investment response.',
 'Treating deposit leakage and crowding out as one mechanism or reversing either effect.',tag='crowding_out')
rewrite('ECON-SP-LEGENDARYBOSS-9110','A central bank plans a $600 deposit contraction using a textbook multiplier of 10. Later evidence puts the actual multiplier at 4, with no change in that estimate. Under the actual multiplier, how many reserves must it remove in total? Suppose the resulting disinflation lowers inflation from 6% to 4% and produces output losses of 2% and 1% of annual potential GDP in successive years. What sacrifice ratio follows, and would an equal reserve removal through a different tool alone guarantee a lower output cost?',
 '$150; a sacrifice ratio of 1.5; no, a different tool alone does not establish a cheaper transmission path.',
 ['$60; a sacrifice ratio of 1.5; yes, the original multiplier guarantees the same contraction with less output loss.','$150; a sacrifice ratio of 0.67; no, a different tool alone does not establish a cheaper transmission path.','$240; a sacrifice ratio of 3; yes, matching reserve removal guarantees a lower output cost.'],
 'At multiplier 4, the reserve removal is 600/4=150, rather than the initially planned 60. Cumulative output loss is 2+1=3% of annual potential GDP; inflation falls 2 points, so the sacrifice ratio is 3/2=1.5. Equal reserve changes do not independently establish equal transmission or a lower real cost under another tool.',
 'Using a maximum multiplier as the actual response or confusing cumulative output loss with the sacrifice ratio.',type='multi-step')
rewrite('ECON-NL-MEDIUMBOSS-3016','With workers’ skills and technology fixed, successive identical machines add 120 and then 60 units of output. The firm now trains its workers without adding another machine. Which distinction is correct?',
 'The machine increments show diminishing returns; training adds human capital and can raise output from the existing equipment.',
 ['The machine increments show falling total output; training adds physical capital by increasing the machine count.','The machine increments show constant returns; training cannot affect output unless the firm buys another machine.','The machine increments show technological progress; training necessarily eliminates diminishing returns to machines.'],
 'Both machine increments are positive, but the second is smaller: marginal product diminishes. Training changes workers’ human capital, so the fixed-skill comparison does not imply that training cannot improve production.',
 'Confusing diminishing returns to additional physical capital with the effect of changing human capital.')
rewrite('ECON-EC-FINALBOSS-19011','Two economies use the same technology and have unchanged workforces and skills. Adding 20 units of capital per worker raises output per worker by 60 in the capital-poor economy and 30 in the capital-rich economy. A proposal predicts that repeating these additions will produce those same gains forever. Which comparison and criticism are justified?',
 'The gains are 3 versus 1.5 per added capital unit; the poorer economy initially catches up faster, but diminishing returns undermine constant-gain extrapolation.',
 ['The gains are 1.5 versus 3 per added capital unit; the richer economy initially catches up faster, so the gains should continue indefinitely.','The gains are 3 versus 1.5 per added capital unit; the poorer economy’s higher initial gain proves permanent growth at that rate.','The gains are 60 versus 30 per added capital unit; diminishing returns mean both economies must lose total output after the addition.'],
 'Marginal contributions over the interval are 60/20=3 and 30/20=1.5. Scarce capital can yield larger gains, supporting catch-up. As capital accumulates with other determinants fixed, those gains diminish; the first interval cannot be extended unchanged forever.',
 'Extrapolating an initial catch-up gain as a permanent growth rate.',type='multi-step')
rewrite('ECON-NL-LEGENDARYBOSS-9121','Economy A has 10 workers and output 120; B has 20 workers and output 400. With skills and technology fixed, one additional unit of capital per worker raises total output by 40 in each economy. A proposal repeats that capital addition each year and predicts a constant closing of the productivity gap. What happens to output per worker and the gap after this first addition, and what limits the proposal’s prediction?',
 'A reaches 16 and B reaches 22; the gap falls from 8 to 6, but later marginal gains need not repeat as capital deepens.',
 ['A reaches 16 and B reaches 22; the gap falls from 8 to 6, proving it will disappear after three more additions.','A reaches 52 and B reaches 60; the gap stays 8, because equal total gains imply equal gains per worker.','A reaches 14 and B reaches 24; the gap rises from 8 to 10, because capital deepening must favor the larger workforce.'],
 'Initially output per worker is 120/10=12 and 400/20=20. Afterward it is 160/10=16 and 440/20=22, so the gap narrows from 8 to 6. Equal total gains differ per worker. The first observed closing does not establish a fixed convergence date: diminishing returns change later marginal gains at fixed skills and technology.',
 'Confusing equal total output gains with equal productivity gains or extrapolating one catch-up interval indefinitely.',type='multi-step')
rewrite('ECON-NL-MEDIUMBOSS-3021','A workshop has 10 workers. With one machine, output is 100 units; with two machines it is 160; with three it is 200. Workers, hours, and technology stay fixed. What are the extra output from the third machine and output per worker with three machines?',
 '40 units of extra output; 20 units per worker.',
 ['100 units of extra output; 20 units per worker.','40 units of extra output; 4 units per worker.','60 units of extra output; 200 units per worker.'],
 'The third machine adds 200−160=40 units. With three machines, output per worker is 200/10=20. A marginal addition and the average output per worker use different denominators.',
 'Confusing marginal output with average output per worker.',type='calculation')
# Retain ECON-NL-MEDIUMBOSS-3026 as the one basic physical-capital diagnosis.
rewrite('ECON-EC-FINALBOSS-19012','Automation removes routine jobs while creating technical vacancies. Aggregate spending and total vacancies remain strong, but displaced workers lack the required certification. A wage subsidy for the old jobs ends after six months; a training program leads to recognized certification. Which policy addresses the persistent unemployment mechanism, and why might the subsidy’s effect fade?',
 'Training addresses the skill mismatch; the temporary subsidy may postpone displacement without qualifying workers for the new vacancies.',
 ['The subsidy addresses cyclical unemployment permanently; training cannot affect employability while vacancies remain strong.','Training only speeds frictional search; the subsidy permanently restores the old demand for routine tasks.','Both policies permanently remove the mismatch because any temporary employment creates the required certification.'],
 'The obstacle is the changed demand for skills, not weak aggregate spending. Certification targets that structural mismatch. A temporary subsidy may support employment while it operates without changing workers’ qualifications for the new jobs.',
 'Treating temporary job retention as a permanent repair of a technology-driven skill mismatch.')
rewrite('ECON-NL-FINALBOSS-4016','Unemployment rises from its estimated natural rate of 5% to 8% during a recession. After demand recovers, it returns to 5%, with skills and labor-market institutions unchanged. What portion of the recession unemployment rate was cyclical, and what does the remaining 5% imply for policy?',
 'About 3 percentage points were cyclical; eliminating the rest requires addressing search or structural factors rather than repeating demand stimulus.',
 ['About 5 percentage points were cyclical; the remaining 3 points show that demand has not recovered.','All 8 percentage points were cyclical; a return to normal demand should therefore eliminate unemployment.','About 3 percentage points were structural; the remaining 5 points must disappear with another demand expansion.'],
 'The recession gap above the natural rate is 8−5=3 points. Returning to the natural rate removes that cyclical component. Frictional and structural unemployment can remain at normal demand, so the remaining rate is not evidence of an equal demand shortfall.',
 'Treating all observed unemployment as cyclical or treating the natural rate as zero.',type='analysis')
rewrite('ECON-NL-FINALBOSS-4041','Vacancies increase in a region, yet long-term unemployment remains high. Qualified applicants are hired quickly, but most long-term job seekers fail employers’ skill requirements. What evidence supports retraining rather than a general job-information campaign?',
 'Existing information produces quick matches for qualified applicants; the persistent unemployed lack the skills needed for the vacancies.',
 ['The rise in vacancies proves aggregate demand is too low; retraining works mainly by reducing spending.','Quick hiring of qualified applicants proves all remaining unemployment is voluntary search for better offers.','The coexistence of vacancies and unemployment proves workers need more vacancy listings regardless of their qualifications.'],
 'Fast matches among qualified applicants indicate that missing vacancy information is not the main obstacle for this group. The evidence identifies a skills mismatch among the long-term unemployed, which retraining can address.',
 'Choosing a search-information remedy when the evidence points to a qualification mismatch.')
rewrite('LG-Q-9069','At a fixed price level, policymakers want a $240 billion increase in AD. MPC is 0.75, with no other multiplier leakages. Every $1 billion of additional government purchases causes a total $1 billion crowding-out offset after all induced spending effects. How much must purchases rise? If an accompanying monetary policy instead eliminates half of that total offset, how should the purchases increase change to reach the same target?',
 '$80 billion initially; reduce it to about $68.6 billion when half the offset is eliminated.',
 ['$60 billion initially; keep it at $60 billion because the simple multiplier is unchanged.','$80 billion initially; raise it to $96 billion when half the offset is eliminated.','$120 billion initially; reduce it to $80 billion because the offset should be multiplied again.'],
 'The simple multiplier is 1/(1−0.75)=4. Initially the net effect is (4−1)ΔG, so ΔG=240/3=80. With half the total offset eliminated, the net effect is (4−0.5)ΔG and ΔG=240/3.5≈68.6. This solves for policy size under competing channels, not actual equilibrium GDP, and does not multiply the stated total offset again.',
 'Using the gross multiplier to size a net AD target or multiplying a total crowding-out offset twice.',type='multi-step')
rewrite('ECON-EC-MEDIUMBOSS-18000','A fixed-basket price index rises 8%. After switching toward relatively cheaper goods, households can maintain the same utility with 5% more spending. What does the difference indicate?',
 'The fixed basket misses cost-saving substitution and overstates this cost-of-living increase by 3 percentage points.',
 ['The fixed basket captures substitution and understates this cost-of-living increase by 3 percentage points.','The difference proves quality improvement, even though the evidence concerns a change in purchases.','The difference proves inflation is zero, because households can substitute without losing utility.'],
 'The index prices the old basket; the household comparison allows substitution at unchanged utility. The increases differ by 8−5=3 percentage points. That is evidence of substitution bias in this comparison.',
 'Confusing substitution at constant utility with no inflation or a quality change.',type='calculation')
rewrite('ECON-EC-FINALBOSS-19001','A benefit of $1,000 rises with a fixed-basket index that increases 8%. For these recipients, the minimum cost of maintaining last year’s utility rises 5% after substitution. How does the indexed benefit compare with that cost, and what follows if the adjustment instead uses 5%?',
 'It pays $30 more than the $1,050 needed; a 5% adjustment would preserve the stated utility at the new prices.',
 ['It pays $30 less than the $1,080 needed; a 5% adjustment would create an even larger shortfall.','It pays exactly the $1,080 needed; any smaller adjustment must reduce the stated utility.','It pays $80 more than the $1,000 needed; substitution means prices have no effect on the required benefit.'],
 'Indexation pays 1,000×1.08=1,080, while the stated cost is 1,000×1.05=1,050. The excess is $30. A 5% adjustment matches this recipients’ constant-utility cost increase; the conclusion uses their stated costs, not a claim about every household.',
 'Treating a fixed-basket increase as the minimum cost-of-living increase for every recipient.',type='multi-step')
rewrite('PM2B2-BIAS-FB-004','A replacement device costs 20% more but provides twice the measured service, with no other quality change. Separately, a new service gives households a cheaper way to meet a need, but the price index will not include it for several years. Which measurement treatment addresses both problems?',
 'Compare the device’s price per unit of service, which falls 40%, and account for the new service’s benefit from expanded choice.',
 ['Record 20% device inflation without adjustment, and wait to count the new service until its price has risen.','Compare the device’s price per unit of service, which rises 20%, and treat the new service as a change in the old basket’s quantities.','Record a 50% device-price decline from the quality change alone, and assume the new service cannot affect the cost of living.'],
 'The quality-adjusted relative price is 1.20/2=0.60, a 40% fall per unit of service. Delaying the new service can also miss a lower cost of achieving a given utility through expanded choice. Quality change and new-goods bias are distinct measurement problems.',
 'Confusing sticker-price inflation with quality-adjusted inflation or ignoring the benefit of new goods.',type='multi-step')
# PM2B2-BIAS-MB-002 already tests new-goods bias and is preserved exactly.
rewrite('ECON-NL-EASYBOSS-2035','A loan pays 7% nominal interest, and inflation is 4%. Using real interest ≈ nominal interest minus inflation, what is the real interest rate?',
 '3%.',['11%.','7%.','−3%.'],'The approximate real interest rate is 7−4=3%.','Adding inflation instead of subtracting it from the nominal rate.',type='calculation')
rewrite('ECON-EC-MEDIUMBOSS-18004','A fixed-rate loan pays 7% nominal interest. Expected inflation was 2%, but actual inflation is 4%. Using the usual subtraction approximation, how do its expected and realized real returns compare?',
 'Expected: 5%; realized: 3%.',['Expected: 3%; realized: 5%.','Expected: 9%; realized: 11%.','Expected: 5%; realized: 5%.'],
 'Expected real return is 7−2=5%. Realized real return uses actual inflation: 7−4=3%.','Using expected inflation again when calculating the realized return.',type='calculation')
rewrite('PM2B2-RNI-MB-003','A fixed nominal debt was agreed when inflation was expected to be 2%. Actual inflation is 5%, and the nominal repayment cannot change. Relative to what each side expected, who benefits?',
 'The borrower benefits and the lender loses because the repayment buys fewer goods than expected.',
 ['The lender benefits and the borrower loses because the nominal repayment buys more goods than expected.','Both benefit because higher inflation raises the purchasing power of every fixed nominal payment.','Neither is affected because an unchanged nominal payment has unchanged purchasing power.'],
 'Unexpected inflation lowers the real value of a fixed nominal repayment. The borrower gives up less purchasing power than expected, while the lender receives less. This is a redistribution relative to the original expectation.',
 'Treating a fixed nominal repayment as a fixed real repayment.')
# Keep the existing Hard comparison as the expected/realized ranking stage.
rewrite('PM2B2-RNI-LB-001','Two fixed-rate loans each advance $230. In economy A the nominal rate is 7% and expected inflation is 2%; in B they are 9% and 5%. Actual inflation is 4% in both economies. Using real interest ≈ nominal interest minus inflation, how do the lenders’ expected and realized rankings compare, and which borrowers benefit relative to their original expectations?',
 'A initially ranks higher (5% versus 4%), but B realizes more (5% versus 3%); borrower A gains, while borrower B loses.',
 ['A initially ranks higher (5% versus 4%), but B realizes more (5% versus 3%); borrower B gains, while borrower A loses.','B initially ranks higher (9% versus 7%) and still realizes more (5% versus 3%); both borrowers gain from positive inflation.','A initially ranks higher (5% versus 4%) and still realizes more (5% versus 3%); neither borrower is affected by forecast errors.'],
 'Expected real returns are A:7−2=5% and B:9−5=4%; realized returns are A:7−4=3% and B:9−4=5%. A’s inflation exceeds expectations, reducing its borrower’s real burden and its lender’s return relative to their bargain. B’s inflation is below expectations, increasing its borrower’s real burden and benefiting its lender. Thus the ranking reverses and the redistribution runs in opposite directions.',
 'Inferring redistribution from the level of inflation instead of its surprise relative to each contract.',type='multi-step')
for i,p in P.items():
 p['authority']='Faculty closure review '+str(next((j+1 for j,x in enumerate(list(scope)[:30]) if x==i),'family dependency'))
 p['rationale']=p.get('operation','Explicit faculty tier, wording, or feedback decision; retain the question’s structural stage.')
(H/'patches.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Authored',len(P),'changes; unchanged scoped records:',sorted(set(scope)-set(P)))
