import sceneSet from './megastar-mania-scenes.js';
import { all, any, chosen, lte, gte, marketIs, marketCondition, marketCopy, salesOutcomes } from './megastar-mania-market.js';
const p = text => ({ type: 'paragraph', text });
const expanded = any(chosen('expansion.dates'), chosen('expansion.venues'));
const breakoutOutcomes = (price, lead, revenue) => ['surplus', 'balanced', 'shortage'].map(status => ({
  when: marketCondition(m => m.status === status, { demand: 3, price }),
  consequence: `${lead} The breakout song increases demand; your price changes how many of those listeners buy tickets. ${marketCopy[status]} Your existing schedule now faces the next booking window.`,
  effects: { revenue }
}));
function breakoutNode(rebuild) {
  return { id: rebuild ? 'breakout-rebuild' : 'breakout', title: rebuild ? 'A hit after a quiet opening' : 'A song breaks through', time: 'The next booking window',
    scene: [p(rebuild ? 'The premium opening left empty seats. Then Jules Arlen’s new single catches on far beyond the original following. Demand for the next performances rises, but the early price is still your starting point.' : 'Jules Arlen’s new single reaches listeners far beyond the original following. Demand for the next performances rises. The same number of seats is available, and your opening price is still the starting point.')],
    prompt: 'What should the next ticket release cost?', choices: [
      { id: 'keep', label: 'Keep the current ticket price', detail: 'Let new listeners buy at the earlier price, with no extra seats yet.', effects: { demand: 3, momentum: 2, goodwill: -1 }, next: 'expansion',
        outcomes: breakoutOutcomes(0, 'The price stays put while interest surges. Fans appreciate the price, but missing out damages goodwill.', rebuild ? 1 : 0),
        consequence: 'Demand rises at an unchanged ticket price.', mechanism: 'Demand increase at a fixed price and supply', tradeoff: 'A familiar price preserves affordability for buyers who obtain tickets; scarcity still limits access.', whatIf: 'A price increase could reduce the queue and bring more money per ticket, while excluding some buyers on price.' },
      { id: 'moderate', label: 'Raise the price moderately', detail: 'Capture more per ticket while keeping part of the breakout gain accessible.', effects: { demand: 3, momentum: 2, goodwill: -1 }, next: 'expansion',
        outcomes: breakoutOutcomes(-1, 'A moderate increase strengthens receipts but asks fans to pay more. Its effect on access depends on your opening price.', 2),
        consequence: 'A price increase absorbs part of the new willingness to pay.', mechanism: 'Higher demand, with a movement in quantity demanded as price rises', tradeoff: 'More receipts per ticket help the tour; some listeners cannot afford the new price.', whatIf: 'Keeping the price unchanged would leave more listeners seeking the limited seats, with more scope for resale.' },
      { id: 'aggressive', label: 'Raise the price sharply', detail: 'Seek much more per ticket and risk leaving seats unfilled.', effects: { demand: 3, momentum: 2, goodwill: -2 }, next: 'expansion',
        outcomes: breakoutOutcomes(-3, 'The sharp increase brings more money per ticket, but fans object to the price. Starting from a premium opening can still leave unsold seats despite the hit.', rebuild ? 2 : 3),
        consequence: 'The price rises sharply as the audience grows.', mechanism: 'Demand growth does not support every possible price', tradeoff: 'Higher receipts per buyer come at the cost of affordability and goodwill; a high starting price makes overpricing more likely.', whatIf: 'A smaller increase would preserve more purchases, but collect less from each buyer.' }
    ] };
}
export default {
  id: 'megastar-mania', version: 1, title: 'Megastar Mania',
  role: 'Tour Manager · Jules Arlen', introTitle: 'The next ticket release', stateTitle: 'Tour conditions',
  consequenceTitle: 'Tour consequences', endingEyebrow: 'Your outcome · After the tour', duration: 'About 10–15 minutes', decisions: 6, sceneSet,
  introduction: [p('Jules Arlen is a fictional indie-pop singer with a modest following and a waterfront show to book. You manage the tour: set ticket prices, decide how far to expand, and respond when illness or public attention changes the market.'), p('Each stage follows the next booking window. Watch who can get tickets, how many seats remain available and what supports the artist’s future. The venue is a representative view of the tour; no single indicator is a score to maximize.')],
  metadata: { concept: 'Supply and demand in concert ticket markets', learningObjective: 'Distinguish price-driven changes in quantity demanded from shifts in demand and available ticket supply.', mechanism: 'Posted prices, capacity, shortages, surplus and secondary markets', misconception: 'A sellout proves the price was ideal, or more dates mean higher demand.' },
  state: {
    demand: { label: 'Ticket Demand', short: 'How strongly consumers want tickets, distinct from purchases at a particular price', min: 0, max: 8, initial: 4 },
    supply: { label: 'Ticket Supply', short: 'Seats and performances available in the current tour window', min: 0, max: 8, initial: 4 },
    revenue: { label: 'Tour Revenue', short: 'Financial strength from ticket receipts after refunds, not a profit estimate', min: 0, max: 8, initial: 4 },
    goodwill: { label: 'Fan Goodwill', short: 'How fans view the artist and touring experience', min: 0, max: 8, initial: 5 },
    momentum: { label: 'Career Momentum', short: 'Broader visibility, audience reach and prospects for future work', min: 0, max: 8, initial: 3 }
  },
  start: 'pricing', nodes: [
    { id: 'pricing', title: 'A modest following, an open calendar', time: 'Early-career tour',
      scene: [p('The waterfront venue is booked. Jules has a devoted local audience but few listeners elsewhere. An ambitious price would bring more per buyer; a lower one could bring more buyers than these seats can hold.')], prompt: 'Where should the opening ticket price sit?', choices: [
        { id: 'premium', label: 'Set a premium ticket price', detail: 'Ask more per seat while the audience is still small.', effects: { revenue: -1, goodwill: -1, momentum: -1 }, next: 'breakout-rebuild',
          consequence: 'Jules performs to rows of empty seats. At this price, tickets available exceed tickets wanted: a surplus. The higher receipt per buyer does not offset weak sales, and downward price pressure builds. Demand itself has not fallen; the price has limited purchases.', mechanism: 'High price and lower quantity demanded', tradeoff: 'More money per ticket comes with fewer buyers, weaker receipts overall and a quieter opening.', whatIf: 'A moderate opening price would have filled more seats without changing the underlying following.' },
        { id: 'moderate', label: 'Set a moderate ticket price', detail: 'Aim for a healthy turnout at a price the existing audience can support.', effects: { revenue: 1 }, next: 'breakout',
          consequence: 'The available tickets find buyers without leaving a queue of people unable to buy. Receipts strengthen and the opening feels settled. This price fits the current audience and capacity; a future hit or a larger schedule could change that balance.', mechanism: 'Quantity demanded matches available tickets at the posted price', tradeoff: 'A balanced opening avoids severe rationing, but earns less per ticket than a premium price would.', whatIf: 'A lower introductory price would invite more purchases than the current seating can accommodate.' },
        { id: 'introductory', label: 'Offer a low introductory price', detail: 'Make tickets affordable while accepting less money per buyer.', effects: { goodwill: 1, momentum: 1 }, next: 'breakout',
          consequence: 'The low price attracts more ticket requests than there are seats. Some fans get an affordable night out; others cannot buy. Resale offers appear above the official price. This shortage comes from quantity demanded at the low price, not an overnight increase in the underlying following.', mechanism: 'Low price, excess quantity demanded and secondary resale', tradeoff: 'Affordability helps successful buyers and the opening gains attention, but low receipts per ticket and rationing limit the benefit.', whatIf: 'A moderate price would reduce the excess requests; it would also ask each buyer to pay more.' }
      ] }, breakoutNode(false), breakoutNode(true),
    { id: 'expansion', title: 'How large should the tour become?', time: 'Booking the next leg',
      scene: [p('The breakout has raised interest, but the earlier price still determines how many listeners will buy. Promoters offer extra dates and bigger rooms. More capacity can serve unmet requests; it can also leave more seats to fill.')], prompt: 'How much capacity should you book?', choices: [
        { id: 'dates', label: 'Add tour dates', detail: 'Take the show to more stops, with more travel and production work.', effects: { supply: 3, goodwill: 1, momentum: 1 }, next: 'illness',
          outcomes: salesOutcomes({ supply: 3 }, 'More stops appear on the tour map. Available tickets increase; demand and price stay unchanged. Fans gain more opportunities, but the crew takes on a heavier schedule.'),
          consequence: 'Additional dates increase ticket supply.', mechanism: 'Supply expansion through more performances', tradeoff: 'More fans can attend if they want the added tickets; travel, staffing and recovery time become harder to manage.', whatIf: 'Keeping fewer dates would reduce logistical strain but leave less room for interested fans.' },
        { id: 'venues', label: 'Move to larger venues', detail: 'Offer more seats per stop without adding as many travel days.', effects: { supply: 2, goodwill: -1, momentum: 1 }, next: 'illness',
          outcomes: salesOutcomes({ supply: 2 }, 'Larger rooms increase the seats available at existing stops. Demand and price stay unchanged. More people can attend, though fans lose some of the intimate atmosphere.'),
          consequence: 'Larger venues increase ticket supply.', mechanism: 'Supply expansion through more seats', tradeoff: 'More capacity avoids extra travel days, but bigger productions and distant seats change the fan experience.', whatIf: 'Adding dates instead would reach more places while requiring more travel and performance days.' },
        { id: 'limited', label: 'Keep the schedule limited', detail: 'Protect the compact tour and accept its current capacity.', effects: {}, next: 'illness',
          outcomes: salesOutcomes({}, 'The crew keeps a manageable schedule. Neither available tickets nor demand changes, and the posted price stays in place.'),
          consequence: 'The existing supply remains available.', mechanism: 'Fixed capacity and the persistence of market pressure', tradeoff: 'A smaller operation is easier to manage, but it cannot serve additional requests if tickets are already scarce.', whatIf: 'Extra dates would add available tickets; they would not, by themselves, create more people who want them.' }
      ] },
    { id: 'illness', title: 'The voice needs a rest', time: 'An interruption to the tour',
      scene: [p('Jules develops laryngitis. The current performance cannot go ahead, and the venue closes with advance notice to ticket holders. Recovery requires time away from singing. The question is which dates leave this booking window.')], prompt: 'How should you reshape the schedule?', choices: [
        { id: 'cancel', label: 'Cancel selected dates and refund fans', detail: 'Remove a block of performances and keep the later dates under review.', effects: { supply: -2, revenue: -2, goodwill: -1, momentum: -1 }, next: 'publicity',
          consequence: 'Selected dates are canceled and refunds weaken tour receipts. The closed venue has no performance and no waiting audience. Available tickets fall while underlying demand stays unchanged. A shorter set of later shows remains after recovery.', mechanism: 'Illness causes a contraction in available ticket supply', tradeoff: 'Clear refunds settle the canceled dates, but disappointed fans lose their planned night out.', whatIf: 'Moving fewer dates beyond this window would preserve more current capacity, with more uncertainty about rebooking.' },
        { id: 'postpone', label: 'Postpone dates beyond this tour window', detail: 'Offer refunds or later bookings, with the smallest current reduction.', effects: { supply: -1, revenue: -1, goodwill: 1, momentum: -1 }, next: 'publicity',
          consequence: 'The affected performances are canceled for their current dates and moved beyond this tour window. Fans can seek refunds or wait for new bookings. Current supply and receipts fall; future dates are not counted as seats available now. Demand stays unchanged, and the closed venue has no audience.', mechanism: 'Postponement reduces current supply even if later shows are planned', tradeoff: 'Fans keep a future option, but rebooking remains uncertain and later recovery time is less protected.', whatIf: 'A longer reduction would provide more recovery time while removing more current opportunities to attend.' },
        { id: 'recovery', label: 'Cut a longer block to protect recovery', detail: 'Give up more performances and refunds now for a less hurried return.', effects: { supply: -3, revenue: -3, goodwill: 1, momentum: 1 }, next: 'publicity',
          consequence: 'A longer block leaves the calendar. Refunds weaken receipts and fewer tickets remain available, without reducing underlying demand. The canceled venue stays dark and empty. Extra recovery time supports Jules’s future work, but more fans must give up their current plans.', mechanism: 'A larger supply contraction with a longer recovery interval', tradeoff: 'Artist health and future work gain time; current receipts and opportunities to attend fall further.', whatIf: 'Canceling a smaller block would preserve more current tickets but leave a tighter recovery schedule.' }
      ] },
    { id: 'publicity', title: 'A careless interview', time: 'After recovery · remaining performances resume',
      scene: [p('Jules returns for the remaining shows; the removed dates have not been restored. In an interview, Jules jokes that longtime fans never want anything new. The clip sounds dismissive and interest weakens. Your response can soften the damage, but it cannot erase the comment.')], prompt: 'How should Jules respond?', choices: [
        { id: 'acknowledge', label: 'Acknowledge the mistake', detail: 'Apologize to longtime fans and explain the comment without excusing it.', effects: { demand: -2, goodwill: 2, momentum: -1 }, next: 'crossover',
          outcomes: salesOutcomes({ demand: -2 }, 'The apology repairs some goodwill, but interest still falls from the breakout peak. The same remaining dates, seats and price stay in place.'),
          consequence: 'An apology softens a decline in demand.', mechanism: 'A negative demand shock with unchanged supply', tradeoff: 'Repairing trust helps the existing audience, while promotion of new work loses time.', whatIf: 'Silence would save promotional time but leave more of the loss of interest unaddressed.' },
        { id: 'quiet', label: 'Let the clip pass without a response', detail: 'Keep time for rehearsals and new work instead of another interview cycle.', effects: { demand: -4, goodwill: -2, momentum: 2 }, next: 'crossover',
          outcomes: salesOutcomes({ demand: -4 }, 'Jules keeps rehearsals and new work moving, but the dismissive impression sticks. Current interest falls sharply despite progress on future work. No dates, seats or prices change.'),
          consequence: 'Unanswered criticism reduces demand further.', mechanism: 'Weaker preferences reduce demand without removing capacity', tradeoff: 'Staying quiet avoids extending the interview dispute, but leaves fans with little reason to reconsider it.', whatIf: 'Acknowledging the remark would repair more goodwill, at the cost of time and attention for new work.' },
        { id: 'image', label: 'Lean into a new musical identity', detail: 'Signal a new direction even if some longtime listeners move on.', effects: { demand: -3, goodwill: -1, momentum: 1 }, next: 'crossover',
          outcomes: salesOutcomes({ demand: -3 }, 'Jules makes the changed identity clear. Some existing listeners leave before new ones arrive, reducing current demand. The same seats and price remain; a new direction is ready for the next release.'),
          consequence: 'A changed image loses current listeners while preparing a new direction.', mechanism: 'A fall in current demand can coexist with future career prospects', tradeoff: 'The next release has a clearer identity, but current interest and goodwill suffer.', whatIf: 'An apology would retain more of the old audience but put less emphasis on a break with the past.' }
      ] },
    { id: 'crossover', title: 'Who will hear the next release?', time: 'The final booking window',
      scene: [p('A dance producer offers to work with Jules. New listeners could discover the songs, though longtime fans may prefer the original sound. Ticket prices and the remaining schedule are fixed for this window: attracting listeners will not add seats.')], prompt: 'How far should the music change?', choices: [
        { id: 'original', label: 'Focus on the original audience', detail: 'Keep the familiar sound and rebuild relationships with existing listeners.', effects: { goodwill: 1 }, next: '$end',
          outcomes: salesOutcomes({}, 'Jules keeps the original sound. Loyal listeners appreciate the continuity, but no new wave of ticket demand arrives. The earlier price and remaining capacity still shape attendance.'),
          consequence: 'The current audience remains the focus.', mechanism: 'Stable demand with an unchanged price and supply', tradeoff: 'Continuity helps core relationships while giving up the reach a crossover release could bring.', whatIf: 'A collaboration could attract new listeners, but it would not create extra performances for them.' },
        { id: 'experiment', label: 'Try a limited crossover collaboration', detail: 'Release one dance collaboration while keeping most of the familiar set.', effects: { demand: 2, momentum: 2 }, next: '$end',
          outcomes: salesOutcomes({ demand: 2 }, 'The collaboration reaches new listeners and raises demand. The familiar set keeps the change limited, with less reach than a full crossover. Available seats and the ticket price do not change.'),
          consequence: 'A collaboration brings new listeners to the existing tour.', mechanism: 'Positive demand shift with fixed capacity', tradeoff: 'The audience broadens with less disruption to the existing sound, but the launch reaches fewer new listeners than a full change.', whatIf: 'A full crossover could reach further, with more risk of alienating the core audience.' },
        { id: 'full', label: 'Pursue crossover appeal fully', detail: 'Build the new release and performance around the dance sound.', effects: { demand: 3, momentum: 3, goodwill: -2 }, next: '$end',
          outcomes: salesOutcomes({ demand: 3 }, 'New listeners discover Jules through the full crossover release. Demand and career reach grow, while some longtime fans dislike the change. Neither capacity nor the posted price increases.'),
          consequence: 'A full crossover expands demand for the remaining shows.', mechanism: 'New listeners increase demand, not supply', tradeoff: 'Broader reach costs some core-fan goodwill; a fixed schedule may prevent new enthusiasm from becoming additional ticket sales.', whatIf: 'A limited collaboration would preserve more continuity while attracting a smaller new audience.' }
      ] }
  ],
  endings: [
    { id: 'reputation', title: 'Reputation on the Ropes', when: lte('demand', 4), summary: 'Interest remains well below the breakout peak after the interview. The remaining tour still has an audience, but the next release has not restored its earlier appeal. Your price and capacity determine whether that weaker demand leaves empty seats or still exceeds a small supply. Goodwill and renewed interest will need attention.' },
    { id: 'too-big', title: 'Too Big, Too Fast', when: all(expanded, marketIs('surplus')), summary: 'You booked a wider tour, then lost dates to illness and listeners to the interview. Even after those cancellations, the remaining seats exceed what buyers want at the posted price. Expansion offered access, but did not guarantee an audience. A lower price or a different future schedule could reduce the surplus.' },
    { id: 'crossover', title: 'Crossover Superstar', when: all(chosen('crossover.full'), gte('demand', 7)), summary: 'The new sound brings a much wider audience and restores strong demand. Some original fans feel left behind. The remaining seats and your earlier price still determine sales: more listeners do not automatically mean more tickets sold or more receipts. Future bookings must weigh that new reach against the audience Jules started with.' },
    { id: 'sold-out', title: 'Sold Out Everywhere', when: marketIs('shortage'), summary: 'The remaining performances cannot serve everyone who wants a ticket at the official price. Sellouts coexist with shut-out fans and resale offers above that price. Your earlier pricing and the dates lost to illness both matter. Preserving affordability for some buyers has left others competing for access; the resale premium is not revenue for Jules.' },
    { id: 'built', title: 'Built for the Crowd', when: expanded, summary: 'The expanded tour, later cancellations and changing audience have left ticket purchases in balance with the remaining seats. More capacity helped make room for listeners, but it brought extra production demands before illness interrupted the plan. This fit belongs to the current price and audience; it is not a permanent guarantee.' },
    { id: 'intimate', title: 'Intimate by Choice', when: all(chosen('expansion.limited'), gte('demand', 6), marketCondition(m => m.wanted <= m.supply)), summary: 'Interest in Jules remains strong, and you chose to keep the tour compact instead of adding dates or larger venues. Illness later reduced the schedule further. At the retained price, the remaining seats accommodate ticket buyers, though some may stay open. A smaller tour can be a deliberate choice even with a broad audience; strong interest does not guarantee that every listener buys at this price.' },
    { id: 'niche', title: 'A Smaller Circuit', summary: 'Jules finishes with a compact tour and a core audience rather than a larger booking operation. At the retained ticket price, the remaining capacity is enough for buyers, though some paths still leave seats open. Continuity and fan relationships matter alongside receipts; a smaller circuit still needs prices that its listeners will support.' }
  ],
  debrief: [
    { title: 'Surplus and shortage', text: 'A high price can leave available seats unsold: quantity supplied exceeds quantity demanded at that price. A low price can leave more requests than seats: a shortage. Unsold seats put downward pressure on price; unfilled requests put upward pressure on it. Changing price changes how many tickets people buy, without necessarily changing their underlying interest in the artist.' },
    { title: 'Why sold out does not tell the whole story', text: 'A sellout means all tickets sold. In this tour, fans still trying to buy show that quantity demanded exceeded availability at the posted price. That does not prove the price maximized revenue, nor make an affordable price a mistake. Resale above the official price reveals additional willingness to pay that the artist does not capture. Access, receipts and goodwill can point toward different choices.' },
    { title: 'Supply changes', text: 'Extra dates and larger venues made more tickets available. Illness removed performances; postponed dates outside the current window were unavailable now even if they might return later. Neither change directly altered consumer preferences. Selling more of the same stock after a price cut is different from adding seats or shows to the schedule.' },
    { title: 'Demand changes', text: 'The hit and crossover releases drew new listeners, raising demand. The interview reduced interest while remaining performances still existed. These shifts changed how many tickets buyers wanted at a given price; they did not create or remove seats. When all remaining seats already sold, stronger demand intensified scarcity without raising ticket receipts at the fixed price.' }
  ]
};
