import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Workbook} from '@oai/artifact-tool';
const d=path.dirname(fileURLToPath(import.meta.url)),r=path.resolve(d,'../..');
const items=JSON.parse(await fs.readFile(path.join(d,'dispositions.json'),'utf8'));
const ledger=JSON.parse(await fs.readFile(path.join(d,'expectations.json'),'utf8'));
const formatOptions=q=>q.options.map((s,i)=>'ABCD'[i]+'. '+s).join('\n');
const headers=['Question ID','Course membership','Direct faculty note or related pattern','Original assessment','Original difficulty','Original stem','Revised stem','Original alternatives','Revised alternatives','Feedback before','Feedback after','Difficulty before','Difficulty after','Correct-answer position preserved','Economic content changed','Shared-course effect','Source','Reason for correction','Validation status','Disposition','Faculty pattern seed','Runtime difficulty-pool move'];
const rows=items.map(c=>[c.id,c.areas.join('; '),c.facultyResponse?.notes||c.patternSeed||'',c.facultyResponse?.assessment||'Not in independent sample',c.before.canonicalDifficulty||'unknown',c.before.q,c.after.q,formatOptions(c.before),formatOptions(c.after),c.before.feedback||'',c.after.feedback||'',c.before.canonicalDifficulty||'unknown',c.after.canonicalDifficulty||'unknown','Yes — '+'ABCD'[c.key],c.economicContentChanged?'Yes — documented repair/enhancement':'No',c.areas.length>1?'Canonical change reaches '+c.areas.join(', '):'Single course',c.source,c.reason,c.disposition==='IMPLEMENTED'?'PASS — key, content, structure, publication and exports verified':'Reviewed — no canonical change',c.disposition,c.patternSeed||'Direct faculty note',ledger.moves.filter(m=>m.id===c.id).map(m=>m.from+' → '+m.to+' ('+m.conceptId+')').join('; ')||'None']);
headers.push('Original wording flag','Original difficulty flag');
items.forEach((c,i)=>rows[i].push(c.facultyResponse?(c.facultyResponse.wordingConcern?'Yes':'No'):'Not sampled',c.facultyResponse?(c.facultyResponse.difficultyConcern?'Yes':'No'):'Not sampled'));
const wb=Workbook.create(),sheet=wb.worksheets.add('Remediation');
sheet.getRange('A1:X'+(rows.length+1)).values=[headers,...rows];
await wb.recalculate();
const matrix=sheet.getRange('A1:X'+(rows.length+1)).values;
if(JSON.stringify(matrix)!==JSON.stringify([headers,...rows]))throw Error('Ledger value round trip failed');
console.log((await wb.inspect({kind:'table',range:'Remediation!A1:D5',include:'values',tableMaxRows:5,tableMaxCols:4,maxChars:1500})).ndjson);
const csv='\ufeff'+matrix.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n')+'\r\n';
const output=path.join(r,'faculty_exports/audits/faculty_validation_remediation_20261008.csv');await fs.writeFile(output,csv);
console.log(JSON.stringify({output,rows:rows.length,columns:headers.length}));
