/* Faculty-editable instructional-resource catalog for The Stabilization Protocol. */
(function registerStabilizationProtocolResources(global) {
"use strict";
if (global.STABILIZATION_PROTOCOL_INSTRUCTIONAL_RESOURCES) return;
const V=(id,chapter,title,description,url,priority=1,type="video")=>({id,chapter,type,title,description,url,actionLabel:"Watch Video",external:true,priority});
const S=(chapter,file,description)=>({id:`chapter-${chapter}-lecture-slides`,chapter,type:"slides",title:`Chapter ${chapter} Lecture Slides`,description,url:`resources/slides/${file}`,actionLabel:"Open Slides",external:false,downloadable:true,priority:4});
const chapters={
"30":{title:"Money, the Banking System, and the Federal Reserve",fallbackResourceIds:["cTX6rqnFEl5","cTX6YlnFEcz","chapter-30-lecture-slides"],resources:[
V("cTXXbLnFHgX",30,"What is Money","Review the functions and forms of money.","https://wjbyrd.screencasthost.com/watch/cTXXbLnFHgX"),V("wLyh5fSTLLw",30,"What is the Fed","Review the structure and roles of the Federal Reserve System.","https://www.youtube.com/watch?v=wLyh5fSTLLw"),V("cTX6rqnFEl5",30,"Bank Reserves and Money Creation","Review bank reserves, money creation, and monetary control.","https://wjbyrd.screencasthost.com/watch/cTX6rqnFEl5",2),V("c0fe2vVaT9t",30,"Bank Capital and Leverage","Review bank capital, leverage, and banking constraints.","https://wjbyrd.screencasthost.com/watch/c0fe2vVaT9t",2),V("cTX6YlnFEcz",30,"Chapter 30 Worked Problems","Practice applying Chapter 30 concepts through worked problems.","https://wjbyrd.screencasthost.com/watch/cTX6YlnFEcz",3,"worked-problem"),S(30,"chapter-30-the-monetary-system.pdf","Review money, banking, and Federal Reserve policy.")]},
"31":{title:"Money Growth and Inflation",fallbackResourceIds:["crljbCV2qcO","cTXlDNnF7Dy","chapter-31-lecture-slides"],resources:[
V("cTXlFYnF7xj",31,"Money Demand and Money Supply","Review money demand and money supply.","https://wjbyrd.screencasthost.com/watch/cTXlFYnF7xj"),V("crljbCV2qcO",31,"Quantity Equation","Review the quantity theory of money and inflation.","https://wjbyrd.screencasthost.com/watch/crljbCV2qcO",2),V("cTX6YxnFEfv",31,"Interest Rates","Review nominal, real, and inflation-adjusted interest rates.","https://wjbyrd.screencasthost.com/watch/cTX6YxnFEfv"),V("78-BlZXm7wA",31,"Zimbabwe and Hyperinflation","Review policy and real-world implications of inflation.","https://www.youtube.com/watch?v=78-BlZXm7wA",2),V("c3fjIuVqEjp",31,"Costs of Inflation","Review the economic costs of inflation.","https://wjbyrd.screencasthost.com/watch/c3fjIuVqEjp",2),V("cTXlDNnF7Dy",31,"Chapter 31 Worked Problems","Practice Chapter 31 money-growth and inflation problems.","https://wjbyrd.screencasthost.com/watch/cTXlDNnF7Dy",3,"worked-problem"),S(31,"chapter-31-money-growth-and-inflation.pdf","Review money growth, inflation, and interest rates.")]},
"34":{title:"Aggregate Demand and Aggregate Supply",fallbackResourceIds:["crlVoJVIRb7","cTXfq6nFTzF","chapter-34-lecture-slides"],resources:[
V("crlicsV2IVp",34,"Aggregate Demand","Review aggregate demand and shifts of the AD curve.","https://wjbyrd.screencasthost.com/watch/crlicsV2IVp"),V("crlibBV2o4X",34,"Short-Run Aggregate Supply","Review the short-run aggregate supply curve and its determinants.","https://wjbyrd.screencasthost.com/watch/crlibBV2o4X"),V("crliqTV2oLX",34,"Long-Run Aggregate Supply","Review long-run aggregate supply and long-run equilibrium.","https://wjbyrd.screencasthost.com/watch/crliqTV2oLX",2),V("crlVoJVIRb7",34,"Aggregate Demand and Aggregate Supply","Review AD–AS shocks, output, prices, and adjustment.","https://wjbyrd.screencasthost.com/watch/crlVoJVIRb7",2),V("cTXfq6nFTzF",34,"Chapter 34 Worked Problems","Practice Chapter 34 AD–AS problems.","https://wjbyrd.screencasthost.com/watch/cTXfq6nFTzF",3,"worked-problem"),S(34,"chapter-34-aggregate-demand-and-aggregate-supply.pdf","Review aggregate demand, aggregate supply, shocks, and equilibrium.")]},
"35":{title:"The Influence of Monetary and Fiscal Policy on Aggregate Demand",fallbackResourceIds:["cTl1qAnYex7","cOVhrInroUf","chapter-35-lecture-slides"],resources:[
V("cTlf3znqSIU",35,"Theory of Liquidity Preferences","Review liquidity preference and economic shocks.","https://wjbyrd.screencasthost.com/watch/cTlf3znqSIU"),V("cTlhbTnYVl5",35,"Monetary Policy and Aggregate Demand","Review how monetary policy affects aggregate demand.","https://wjbyrd.screencasthost.com/watch/cTlhbTnYVl5"),V("cTl1qAnYex7",35,"Fiscal Policy and Aggregate Demand","Review how fiscal policy influences aggregate demand.","https://wjbyrd.screencasthost.com/watch/cTl1qAnYex7"),V("cOVebMnrXjC",35,"Fiscal Policy Effects and Aggregate Supply","Review fiscal-policy mechanisms and side effects.","https://wjbyrd.screencasthost.com/watch/cOVebMnrXjC",2),V("cOVeFcnrXQi",35,"Stabilization","Review stabilization policy choices under different economic conditions.","https://wjbyrd.screencasthost.com/watch/cOVeFcnrXQi",2),V("cOVhrInroUf",35,"Chapter 35 Worked Problems","Practice Chapter 35 policy problems.","https://wjbyrd.screencasthost.com/watch/cOVhrInroUf",3,"worked-problem"),S(35,"chapter-35-the-influence-of-monetary-and-fiscal-policy-on-aggregate-demand.pdf","Review monetary policy, fiscal policy, and stabilization.")]},
"36":{title:"The Short-Run Tradeoff Between Inflation and Unemployment",fallbackResourceIds:["cOVfr5nrlbN","cTleF5nqNuL","chapter-36-lecture-slides"],resources:[
V("ABOGxIHVHO4",36,"The Phillips Curve","Review the short-run and long-run Phillips curves.","https://www.youtube.com/watch?v=ABOGxIHVHO4"),V("cOVfr5nrlbN",36,"Adaptive vs. Rational Expectations","Review expectations, inflation dynamics, and Phillips-curve shifts.","https://wjbyrd.screencasthost.com/watch/cOVfr5nrlbN",2),V("cTleF5nqNuL",36,"Chapter 36 Worked Problems","Practice Chapter 36 Phillips-curve and disinflation problems.","https://wjbyrd.screencasthost.com/watch/cTleF5nqNuL",3,"worked-problem"),S(36,"chapter-36-short-run-tradeoff-between-Inflation-and-unemployment.pdf","Review inflation, unemployment, expectations, and the sacrifice ratio.")]}};
const M=(chapter,title,resourceIds)=>({chapter,title,resourceIds});
const objectives={
"LO30.1":M(30,"Explain the functions and forms of money.",["cTXXbLnFHgX","cTX6YlnFEcz"]),"LO30.2":M(30,"Describe the structure and roles of the Federal Reserve System.",["wLyh5fSTLLw","cTX6rqnFEl5"]),"LO30.3":M(30,"Analyze how banks create money in a fractional reserve system.",["cTX6rqnFEl5","c0fe2vVaT9t","cTX6YlnFEcz"]),"LO30.4":M(30,"Evaluate how the Federal Reserve controls the money supply.",["cTX6rqnFEl5","cTX6YlnFEcz"]),"LO30.5":M(30,"Discuss the limits of monetary control and implications for the economy.",["cTX6rqnFEl5","cTX6YlnFEcz"]),
"LO31.1":M(31,"Explain the quantity theory of money and its implications for inflation.",["crljbCV2qcO","cTXlDNnF7Dy"]),"LO31.2":M(31,"Differentiate between nominal and real variables in the classical dichotomy.",["crljbCV2qcO","cTXlDNnF7Dy"]),"LO31.3":M(31,"Apply the Fisher effect to link nominal interest rates, real interest rates, and inflation.",["cTX6YxnFEfv","cTXlDNnF7Dy"]),"LO31.4":M(31,"Identify and evaluate the economic costs of inflation.",["c3fjIuVqEjp","78-BlZXm7wA","cTXlDNnF7Dy"]),"LO31.5":M(31,"Analyze policy and real-world implications of inflation and deflation.",["78-BlZXm7wA","cTXlDNnF7Dy"]),
"LO34.1":M(34,"Explain why the aggregate-demand curve slopes downward and identify the factors that cause it to shift.",["crlicsV2IVp","crlVoJVIRb7","cTXfq6nFTzF"]),"LO34.2":M(34,"Differentiate between the short-run and long-run aggregate supply curves and explain what determines their shapes.",["crlibBV2o4X","crliqTV2oLX","cTXfq6nFTzF"]),"LO34.3":M(34,"Analyze how sticky-wage and sticky-price theories explain deviations of output from its natural level in the short run.",["crliqTV2oLX","crlVoJVIRb7","cTXfq6nFTzF"]),"LO34.4":M(34,"Evaluate how economic shocks affect output and prices using the AD–AS model.",["crlVoJVIRb7","cTXfq6nFTzF"]),"LO34.5":M(34,"Identify the economy’s long-run equilibrium and explain how it is restored after a shock.",["crliqTV2oLX","crlVoJVIRb7","cTXfq6nFTzF"]),
"LO35.1":M(35,"Analyze economic shocks using the AD–AS and liquidity-preference models.",["cTlf3znqSIU","cOVhrInroUf"]),"LO35.2":M(35,"Explain how monetary policy affects the economy.",["cTlhbTnYVl5","cOVhrInroUf"]),"LO35.3":M(35,"Explain how fiscal policy influences aggregate demand.",["cTl1qAnYex7","cOVhrInroUf"]),"LO35.4":M(35,"Evaluate the mechanisms and side effects of fiscal policy.",["cOVebMnrXjC","cOVhrInroUf"]),"LO35.5":M(35,"Determine appropriate stabilization policies for different economic conditions.",["cOVeFcnrXQi","cOVhrInroUf"]),
"LO36.1":M(36,"Analyze the short-run trade-off between inflation and unemployment using the Phillips curve and explain why no permanent trade-off exists.",["ABOGxIHVHO4","cTleF5nqNuL"]),"LO36.2":M(36,"Derive and interpret both the short-run and long-run Phillips curves using scenarios, graphs, or data, including the role of the natural rate of unemployment.",["ABOGxIHVHO4","cTleF5nqNuL"]),"LO36.3":M(36,"Explain how adaptive and rational expectations shape inflation dynamics and influence the position and slope of the Phillips curve.",["cOVfr5nrlbN","cTleF5nqNuL"]),"LO36.4":M(36,"Evaluate how changes in monetary policy affect inflation, unemployment, and the economy’s transition between short-run and long-run equilibria.",["cOVfr5nrlbN","cTleF5nqNuL"]),"LO36.5":M(36,"Calculate and interpret the sacrifice ratio in the context of disinflation, output changes, and historical movements of the Phillips curve.",["cOVfr5nrlbN","cTleF5nqNuL"])};
const catalog={version:1,gameId:"stabilization-protocol",gameTitle:"The Stabilization Protocol",settings:{maximumRecommendations:3,enableChapterFallback:true},chapters,objectives};
global.STABILIZATION_PROTOCOL_INSTRUCTIONAL_RESOURCES=catalog;
if(!global.INSTRUCTIONAL_RESOURCES) global.INSTRUCTIONAL_RESOURCES=catalog;
}(window));
