import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {api,query,state,save,name,out,root} from './control.mjs';
import {hashCapability} from '../../../server/anonymous-telemetry-poc/capabilities.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE);
const config=JSON.parse(fs.readFileSync(path.join(import.meta.dirname,'composer.staging.json')));
const origin=config.origin,base=state().workerOrigin,secrets=[],hashes=[],requests=[],results=[];
let browser,context,gameHTML='',downloads=0,activationCalls=0,challengeLoads=0,ingestMode=202,socket,tailId,failure;
const tailProof={events:0,rawMatches:0,hashMatches:0,headerObservations:0,redacted:0,unrecognized:0};
const retainedTail=[];
function write(file,value){const text=JSON.stringify(value,null,2);assert(!secrets.concat(hashes).some(s=>text.includes(s)));assert(!/mqic1_[A-Za-z0-9_-]{43}/.test(text));fs.writeFileSync(path.join(out,file),text+'\n');}
function pass(name){results.push({name,status:'PASS'});console.log(name+': PASS');write('proof-progress.json',results);}
async function forward(route,pathname){const req=route.request(),headers=await req.allHeaders();
 const body=req.postData()||'';if(pathname==='/v1/build-capabilities'){activationCalls++;try{secrets.push(JSON.parse(body).turnstileToken);}catch{}}
 if(pathname==='/v1/events'){const token=headers['x-mq-ingest-token'];assert(token);assert(!headers['x-mq-ingest-capability']);assert(!body.includes(token));assert(!req.url().includes(token));assert(!headers.referer);requests.push({body,token});}
 const response=await fetch(base+pathname,{method:'POST',headers:{origin,'content-type':'application/json',...(headers['x-mq-ingest-token']?{'x-mq-ingest-token':headers['x-mq-ingest-token']}:{})},body,redirect:'error',signal:AbortSignal.timeout(30000)});
 const text=await response.text();if(pathname==='/v1/build-capabilities'){const json=JSON.parse(text);if(json.capability){secrets.push(json.capability);hashes.push(await hashCapability(json.capability));}console.log('Real staging issuance HTTP '+response.status);}
 else assert.equal(response.status,ingestMode,'staging ingest status');
 return route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:text});}
async function createContext(){const c=await browser.newContext({acceptDownloads:true});await c.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());
 if(u.protocol==='https:'&&(u.hostname==='challenges.cloudflare.com'||u.hostname.endsWith('.challenges.cloudflare.com'))){challengeLoads++;return route.continue();}
 if(u.origin!==origin)return route.abort();
 if(u.pathname==='/api/anonymous-telemetry-poc/v1/build-capabilities')return forward(route,'/v1/build-capabilities');
 if(u.pathname==='/api/anonymous-telemetry-poc/v1/events')return forward(route,'/v1/events');
 if(u.pathname==='/stage3-game')return route.fulfill({contentType:'text/html',body:gameHTML});
 let p=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!p.startsWith(root+path.sep))return route.abort();if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p))return route.fulfill({status:404,body:''});let body=fs.readFileSync(p);if(p.endsWith('faculty-build-composer'+path.sep+'index.html'))body=body.toString().replace('</head>','<meta name="mq-turnstile-sitekey" content="'+config.publicTurnstileSitekey+'"></head>');const ext=path.extname(p);return route.fulfill({contentType:({'.html':'text/html','.js':'application/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg'})[ext]||'application/octet-stream',body});
 });return c;}
async function contents(download){const stream=await download.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);return Buffer.concat(chunks);}
function unzip(bytes){const entries={};let at=0;while(bytes.readUInt32LE(at)===0x04034b50){assert.equal(bytes.readUInt16LE(at+8),0);const size=bytes.readUInt32LE(at+18),nameLength=bytes.readUInt16LE(at+26),extra=bytes.readUInt16LE(at+28),name=bytes.subarray(at+30,at+30+nameLength).toString(),start=at+30+nameLength+extra;entries[name]=bytes.subarray(start,start+size).toString();at=start+size;}return entries;}
async function download(p,selector='#downloadPackage'){const [d]=await Promise.all([p.waitForEvent('download',{timeout:60000}),p.locator(selector).evaluate(el=>el.click())]);return unzip(await contents(d));}
async function start(p){if(await p.locator('#playerNameInput').count())await p.locator('#playerNameInput').fill('SYNTHETIC');await p.evaluate(()=>startSelectedMode('standard',{quizConfirmed:true}));if(await p.locator('#guideIntroProceed').isVisible())await p.locator('#guideIntroProceed').click();await p.waitForFunction(()=>Boolean(currentQuestion));}
async function answer(p){await p.evaluate(async()=>{questionStartTime=Date.now()-6000;let i=0;for(;i<currentQuestion.options.length;i++)if(await isQuestionAnswerCorrect(currentQuestion,i))break;await answer(i);});await p.waitForTimeout(150);}
async function csv(p){const [d]=await Promise.all([p.waitForEvent('download'),p.evaluate(()=>downloadTelemetryCsv(runID))]);const text=(await contents(d)).toString();assert(text.includes('responseTimeMs'));assert(!secrets.some(x=>text.includes(x)));return text;}

try{
 save({...state(),status:'REAL_PROVIDER_PROOF_RUNNING',ownerConfirmedSecretInstalled:true});
 const tail=await api('/workers/scripts/'+name+'/tails','POST',{});tailId=tail.id;save({...state(),tailId});socket=new WebSocket(tail.url,'trace-v1');socket.binaryType='arraybuffer';socket.addEventListener('message',event=>retainedTail.push(typeof event.data==='string'?event.data:new TextDecoder().decode(event.data)));
 await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('tail deadline')),15000);socket.addEventListener('open',()=>{clearTimeout(t);socket.send(JSON.stringify({debug:false}));resolve();},{once:true});});
 browser=await chromium.launch({channel:'msedge',headless:false});context=await createContext();const ui=await context.newPage();ui.on('console',message=>{const text=message.text();const code=text.match(/(?:Error|error)(?: code)?[^0-9]{0,10}([0-9]{5,6})/);if(code)console.log('Provider numeric error code: '+code[1]);});await ui.goto(origin+'/build/faculty-build-composer/');
 const recipe={schemaVersion:'1.6.0',title:'Stage 3 Provider Proof',slug:'stage3-provider-proof',supportedModes:['standard','exam'],selectedConceptIds:['aggregate-demand'],checkpointFocus:{checkpointOne:null,checkpointTwo:null,finalCheckpoint:null}};
 await ui.locator('#importRecipe').setInputFiles({name:'recipe.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(recipe))});await ui.waitForFunction(()=>document.getElementById('gameTitle').value==='Stage 3 Provider Proof');assert.equal(challengeLoads,0);assert.equal(activationCalls,0);pass('OFF editing has zero challenge and activation requests');
 await ui.locator('.step-nav [data-step="2"]').click();await ui.locator('#allowAnonymousDataCollection').check();await ui.locator('.step-nav [data-step="6"]').click();
 console.log('Starting real Turnstile Generate. Human interaction may be required in Edge.');
 const diagnosticTimer=setTimeout(()=>ui.screenshot({path:path.join(out,'challenge-state.png')}).catch(()=>{}),20000);
 const downloadPromise=ui.waitForEvent('download',{timeout:180000});await ui.locator('#downloadPackage').evaluate(el=>el.click());
 const outcome=await Promise.race([downloadPromise.then(d=>({d})),ui.locator('#activationFailure').waitFor({state:'visible',timeout:180000}).then(async()=>({error:await ui.locator('#activationFailureMessage').innerText()}))]);
 clearTimeout(diagnosticTimer);if(outcome.error)throw Error('Composer activation failed: '+outcome.error);const entries=unzip(await contents(outcome.d));gameHTML=entries['stage3-provider-proof.html'];const descriptor=JSON.parse(gameHTML.match(/globalThis.MQ_INGEST_ACTIVATION = ([^]*?);<\/script>/)[1]);assert.equal(activationCalls,1);for(const [file,text]of Object.entries(entries))if(!file.endsWith('.html'))assert(!secrets.some(s=>text.includes(s)));pass('Real-provider Generate returns scoped capability in playable HTML only');
 const again=await download(ui);assert(again['stage3-provider-proof.html'].includes(descriptor.capability));assert.equal(activationCalls,1);pass('Repeated Generate reuses one issued capability');
 const caps=(await query('SELECT * FROM telemetry_build_capabilities'))[0].results;assert.equal(caps.length,1);const cap=caps[0];assert.equal(cap.capability_hash,await hashCapability(descriptor.capability));assert.equal(cap.capability_id,descriptor.capabilityId);assert.equal(cap.build_id,descriptor.buildId);assert.equal(cap.build_version,descriptor.buildVersion);assert.equal(cap.game_id,descriptor.gameId);assert.equal(cap.schema_version,descriptor.schemaVersion);assert.equal(cap.expires_at-cap.issued_at,365*86400);assert(!secrets.some(s=>JSON.stringify(caps).includes(s)));pass('D1 stores only digest with exact generated tuple and 365-day expiry');
 const game=await context.newPage();await game.goto(origin+'/stage3-game');await start(game);await answer(game);await game.evaluate(()=>AnonymousTelemetryPOC.flush());await csv(game);
 const rows=(await query('SELECT * FROM telemetry_events'))[0].results,receipts=(await query('SELECT * FROM telemetry_ingest_batches'))[0].results;assert(rows.length>0);assert(rows.some(r=>r.event_type==='run_manifest'));assert(rows.every(r=>r.build_id===descriptor.buildId&&r.build_version===descriptor.buildVersion&&r.game_id===descriptor.gameId&&r.schema_version===3));assert(receipts.length>0&&receipts.every(r=>r.capability_id===descriptor.capabilityId));assert(!secrets.concat(hashes).some(s=>JSON.stringify({rows,receipts}).includes(s)));pass('Generated game sends canonical header and receives 202 with manifests and attributed receipts');
 const last=requests.at(-1),duplicate=await fetch(base+'/v1/events',{method:'POST',headers:{origin,'content-type':'application/json','x-mq-ingest-token':last.token},body:last.body,redirect:'error'});assert.equal(duplicate.status,202);assert.equal((await duplicate.json()).accepted,0);pass('Exact duplicate accepted with zero new events');
 await query('UPDATE telemetry_build_capabilities SET revoked_at=issued_at WHERE capability_id=?',[descriptor.capabilityId]);
 ingestMode=403;const cc=await createContext();const failedGame=await cc.newPage();await failedGame.goto(origin+'/stage3-game');await start(failedGame);await answer(failedGame);await failedGame.evaluate(()=>AnonymousTelemetryPOC.flush());await csv(failedGame);assert.equal(await failedGame.evaluate(()=>AnonymousTelemetryPOC.remoteEnabled()),false);assert(await failedGame.evaluate(()=>Boolean(currentQuestion)));await cc.close();pass('Local gameplay and CSV survive terminal remote failure');
 const denied=await fetch(base+'/v1/events',{method:'POST',headers:{origin,'content-type':'application/json','x-mq-ingest-token':last.token},body:last.body,redirect:'error'});assert.equal(denied.status,403);pass('Staging revocation rejects previously issued capability');
 await new Promise(r=>setTimeout(r,4000));for(const text of retainedTail){tailProof.events++;tailProof.rawMatches+=secrets.filter(s=>text.includes(s)).length;tailProof.hashMatches+=hashes.filter(s=>text.includes(s)).length;const value=JSON.parse(text),headers=value.event?.request?.headers||{},key=Object.keys(headers).find(k=>k.toLowerCase()==='x-mq-ingest-token');if(key){tailProof.headerObservations++;if(/redact|mask/i.test(String(headers[key])))tailProof.redacted++;else tailProof.unrecognized++;}}
 assert(tailProof.redacted>0);assert.equal(tailProof.rawMatches+tailProof.hashMatches+tailProof.unrecognized,0);pass('Provider live-tail redacts canonical header and contains zero raw secrets/digests');
 write('proof-results.json',{status:'PASS',results,tail:tailProof,provider:'REAL_TURNSTILE',browser:browser.version(),activationCalls,challengeLoads,ingestRequests:requests.length,productionCalls:0,rawArtifactMatches:0,firstPartyOnly:true});save({...state(),realProviderProof:'PASS',status:'PROOF_PASSED_CLEANUP_PENDING'});
}catch(e){failure=''+e.message;for(const value of secrets.concat(hashes))failure=failure.replaceAll(value,'[REDACTED]');write('proof-failure.json',{status:'FAIL',failure,results,activationCalls,challengeLoads});save({...state(),realProviderProof:'FAIL',status:'PROOF_FAILED'});console.log(failure);}
finally{if(browser)await browser.close();if(socket)socket.close();if(tailId){await api('/workers/scripts/'+name+'/tails/'+tailId,'DELETE');save({...state(),tailClosed:true});}}
process.exitCode=failure?1:0;
