// Static v2 calendar. Each row is a reviewed four-group board, ordered by difficulty.
// Editorial separation is enforced by authored ambiguity families and incompatibleWith IDs.
// No runtime assembly: these 60 rows per domain are the complete published cycle.
export const BOARDS = {
  micro: [
    ["mi-common-examples", "mi-scale-sources", "mi-revenue", "mi-tax-efficiency"], // 01
    ["mi-supply-drivers", "mi-trade-steps", "mi-free-rider", "mi-monopoly-output"], // 02
    ["mi-scarce-inputs", "mi-barriers", "mi-tariff-chain", "mi-coase"], // 03
    ["mi-private-goods", "mi-incentive-response", "mi-tax-remittance", "mi-shutdown"], // 04
    ["mi-public-examples", "mi-surplus-meaning", "mi-opportunity-trap", "mi-discrimination"], // 05
    ["mi-complements", "mi-ppf-outward", "mi-entry", "mi-corrective"], // 06
    ["mi-market-forms", "mi-negative-spillovers", "mi-incidence", "mi-marginal-average"], // 07
    ["mi-variable-inputs", "mi-positive-spillovers", "mi-collusion", "mi-binding-contrast"], // 08
    ["mi-substitutes", "mi-sunk-examples", "mi-commons-chain", "mi-advantage"], // 09
    ["mi-marginal-choices", "mi-ceiling-chain", "mi-ppf-inside", "mi-nash"], // 10
    ["mi-scarce-inputs", "mi-floor-chain", "mi-free-rider", "mi-mcomp"], // 11
    ["mi-common-examples", "mi-ppf-outward", "mi-profit-trap", "mi-simultaneous"], // 12
    ["mi-demand-drivers", "mi-negative-spillovers", "mi-diminishing-product", "mi-discrimination"], // 13
    ["mi-explicit", "mi-elastic-demand", "mi-collusion", "mi-advantage"], // 14
    ["mi-complements", "mi-barriers", "mi-commons-chain", "mi-tax-efficiency"], // 15
    ["mi-marginal-choices", "mi-ceiling-chain", "mi-ppf-inside", "mi-coase"], // 16
    ["mi-demand-drivers", "mi-positive-spillovers", "mi-diminishing-product", "mi-nash"], // 17
    ["mi-explicit", "mi-trade-steps", "mi-revenue", "mi-corrective"], // 18
    ["mi-market-forms", "mi-elastic-demand", "mi-tax-remittance", "mi-marginal-average"], // 19
    ["mi-private-goods", "mi-floor-chain", "mi-opportunity-trap", "mi-discrimination"], // 20
    ["mi-public-examples", "mi-incentive-response", "mi-entry", "mi-advantage"], // 21
    ["mi-common-examples", "mi-ppf-outward", "mi-incidence", "mi-mcomp"], // 22
    ["mi-market-forms", "mi-sunk-examples", "mi-commons-chain", "mi-binding-contrast"], // 23
    ["mi-private-goods", "mi-scale-sources", "mi-tax-remittance", "mi-simultaneous"], // 24
    ["mi-substitutes", "mi-negative-spillovers", "mi-profit-trap", "mi-tax-efficiency"], // 25
    ["mi-variable-inputs", "mi-positive-spillovers", "mi-tariff-chain", "mi-nash"], // 26
    ["mi-supply-drivers", "mi-trade-steps", "mi-commons-chain", "mi-monopoly-output"], // 27
    ["mi-public-examples", "mi-surplus-meaning", "mi-collusion", "mi-marginal-average"], // 28
    ["mi-common-examples", "mi-elastic-demand", "mi-tax-remittance", "mi-shutdown"], // 29
    ["mi-complements", "mi-barriers", "mi-ppf-inside", "mi-coase"], // 30
    ["mi-scarce-inputs", "mi-ceiling-chain", "mi-free-rider", "mi-mcomp"], // 31
    ["mi-demand-drivers", "mi-ppf-outward", "mi-entry", "mi-corrective"], // 32
    ["mi-explicit", "mi-negative-spillovers", "mi-collusion", "mi-binding-contrast"], // 33
    ["mi-marginal-choices", "mi-positive-spillovers", "mi-ppf-inside", "mi-simultaneous"], // 34
    ["mi-private-goods", "mi-trade-steps", "mi-incidence", "mi-shutdown"], // 35
    ["mi-market-forms", "mi-floor-chain", "mi-diminishing-product", "mi-coase"], // 36
    ["mi-public-examples", "mi-incentive-response", "mi-opportunity-trap", "mi-discrimination"], // 37
    ["mi-scarce-inputs", "mi-sunk-examples", "mi-revenue", "mi-corrective"], // 38
    ["mi-variable-inputs", "mi-trade-steps", "mi-free-rider", "mi-monopoly-output"], // 39
    ["mi-common-examples", "mi-surplus-meaning", "mi-profit-trap", "mi-advantage"], // 40
    ["mi-substitutes", "mi-scale-sources", "mi-commons-chain", "mi-tax-efficiency"], // 41
    ["mi-explicit", "mi-negative-spillovers", "mi-tariff-chain", "mi-nash"], // 42
    ["mi-supply-drivers", "mi-elastic-demand", "mi-collusion", "mi-coase"], // 43
    ["mi-complements", "mi-barriers", "mi-free-rider", "mi-advantage"], // 44
    ["mi-demand-drivers", "mi-positive-spillovers", "mi-diminishing-product", "mi-discrimination"], // 45
    ["mi-marginal-choices", "mi-ceiling-chain", "mi-ppf-inside", "mi-corrective"], // 46
    ["mi-market-forms", "mi-incentive-response", "mi-tax-remittance", "mi-marginal-average"], // 47
    ["mi-private-goods", "mi-floor-chain", "mi-opportunity-trap", "mi-nash"], // 48
    ["mi-public-examples", "mi-ppf-outward", "mi-incidence", "mi-mcomp"], // 49
    ["mi-scarce-inputs", "mi-sunk-examples", "mi-revenue", "mi-tax-efficiency"], // 50
    ["mi-common-examples", "mi-scale-sources", "mi-tax-remittance", "mi-simultaneous"], // 51
    ["mi-private-goods", "mi-surplus-meaning", "mi-entry", "mi-advantage"], // 52
    ["mi-public-examples", "mi-ppf-outward", "mi-profit-trap", "mi-binding-contrast"], // 53
    ["mi-substitutes", "mi-trade-steps", "mi-commons-chain", "mi-shutdown"], // 54
    ["mi-variable-inputs", "mi-negative-spillovers", "mi-tariff-chain", "mi-discrimination"], // 55
    ["mi-supply-drivers", "mi-positive-spillovers", "mi-tax-remittance", "mi-monopoly-output"], // 56
    ["mi-complements", "mi-barriers", "mi-ppf-inside", "mi-corrective"], // 57
    ["mi-demand-drivers", "mi-sunk-examples", "mi-collusion", "mi-coase"], // 58
    ["mi-market-forms", "mi-ceiling-chain", "mi-commons-chain", "mi-marginal-average"], // 59
    ["mi-explicit", "mi-negative-spillovers", "mi-incidence", "mi-nash"], // 60
  ],
  macro: [
    ["ma-gdp-parts", "ma-outside-labor", "ma-quantity-growth", "ma-bank-capital"], // 01
    ["ma-exchange-function", "ma-demand-expansion", "ma-crowding-out", "ma-unemployment-rates"], // 02
    ["ma-bank-assets", "ma-lras-drivers", "ma-deficit-debt", "ma-phillips-shift"], // 03
    ["ma-nominal", "ma-fiscal-purchases", "ma-labor-denominator", "ma-neutrality"], // 04
    ["ma-capital-investment", "ma-inflation-costs", "ma-gap-adjustment", "ma-policy-lags"], // 05
    ["ma-productivity-inputs", "ma-automatic", "ma-real-adjustment", "ma-reserve-vs-capital"], // 06
    ["ma-human-capital", "ma-monetary-expansion", "ma-cpi-bias", "ma-debt-ratio"], // 07
    ["ma-government-buying", "ma-structural", "ma-money-demand", "ma-inflation-surprise"], // 08
    ["ma-cyclical-examples", "ma-saving-channels", "ma-deficit-debt", "ma-disinflation"], // 09
    ["ma-frictional", "ma-deflator-scope", "ma-reserve-constraints", "ma-policy-lags"], // 10
    ["ma-stocks", "ma-cpi-steps", "ma-growth-level", "ma-unemployment-rates"], // 11
    ["ma-exchange-function", "ma-lras-drivers", "ma-phillips-move", "ma-gdp-exclusions"], // 12
    ["ma-productivity-inputs", "ma-outside-labor", "ma-fisher", "ma-debt-ratio"], // 13
    ["ma-unit-account", "ma-saving-channels", "ma-gap-adjustment", "ma-policy-lags"], // 14
    ["ma-exchange-function", "ma-cpi-steps", "ma-labor-denominator", "ma-saving-identity"], // 15
    ["ma-frictional", "ma-fiscal-purchases", "ma-cpi-bias", "ma-neutrality"], // 16
    ["ma-gdp-parts", "ma-structural", "ma-money-demand", "ma-inflation-surprise"], // 17
    ["ma-exchange-function", "ma-supply-shock", "ma-deficit-debt", "ma-bank-capital"], // 18
    ["ma-cyclical-examples", "ma-inflation-costs", "ma-growth-level", "ma-debt-ratio"], // 19
    ["ma-government-buying", "ma-demand-expansion", "ma-labor-denominator", "ma-reserve-vs-capital"], // 20
    ["ma-exchange-function", "ma-outside-labor", "ma-real-adjustment", "ma-multiplier-limits"], // 21
    ["ma-gdp-parts", "ma-lras-drivers", "ma-reserve-constraints", "ma-phillips-shift"], // 22
    ["ma-stocks", "ma-deflator-scope", "ma-gap-adjustment", "ma-bank-capital"], // 23
    ["ma-nominal", "ma-monetary-expansion", "ma-deficit-debt", "ma-unemployment-rates"], // 24
    ["ma-productivity-inputs", "ma-automatic", "ma-cpi-bias", "ma-reserve-vs-capital"], // 25
    ["ma-bank-assets", "ma-lras-drivers", "ma-phillips-move", "ma-debt-ratio"], // 26
    ["ma-government-buying", "ma-outside-labor", "ma-growth-level", "ma-disinflation"], // 27
    ["ma-human-capital", "ma-cpi-steps", "ma-reserve-constraints", "ma-policy-lags"], // 28
    ["ma-exchange-function", "ma-structural", "ma-real-adjustment", "ma-multiplier-limits"], // 29
    ["ma-unit-account", "ma-lras-drivers", "ma-labor-denominator", "ma-gdp-exclusions"], // 30
    ["ma-capital-investment", "ma-demand-expansion", "ma-deficit-debt", "ma-unemployment-rates"], // 31
    ["ma-government-buying", "ma-outside-labor", "ma-quantity-growth", "ma-bank-capital"], // 32
    ["ma-frictional", "ma-fiscal-purchases", "ma-real-adjustment", "ma-neutrality"], // 33
    ["ma-cyclical-examples", "ma-lras-drivers", "ma-fisher", "ma-debt-ratio"], // 34
    ["ma-gdp-parts", "ma-monetary-expansion", "ma-gap-adjustment", "ma-inflation-surprise"], // 35
    ["ma-productivity-inputs", "ma-inflation-costs", "ma-labor-denominator", "ma-gdp-exclusions"], // 36
    ["ma-stocks", "ma-saving-channels", "ma-cpi-bias", "ma-unemployment-rates"], // 37
    ["ma-exchange-function", "ma-supply-shock", "ma-growth-level", "ma-policy-lags"], // 38
    ["ma-human-capital", "ma-cpi-steps", "ma-money-demand", "ma-debt-ratio"], // 39
    ["ma-productivity-inputs", "ma-automatic", "ma-reserve-constraints", "ma-inflation-surprise"], // 40
    ["ma-bank-assets", "ma-deflator-scope", "ma-deficit-debt", "ma-unemployment-rates"], // 41
    ["ma-exchange-function", "ma-demand-expansion", "ma-labor-denominator", "ma-saving-identity"], // 42
    ["ma-gdp-parts", "ma-saving-channels", "ma-gap-adjustment", "ma-disinflation"], // 43
    ["ma-nominal", "ma-structural", "ma-reserve-constraints", "ma-policy-lags"], // 44
    ["ma-government-buying", "ma-lras-drivers", "ma-phillips-move", "ma-reserve-vs-capital"], // 45
    ["ma-exchange-function", "ma-outside-labor", "ma-crowding-out", "ma-inflation-surprise"], // 46
    ["ma-capital-investment", "ma-inflation-costs", "ma-deficit-debt", "ma-unemployment-rates"], // 47
    ["ma-stocks", "ma-structural", "ma-cpi-bias", "ma-bank-capital"], // 48
    ["ma-frictional", "ma-lras-drivers", "ma-fisher", "ma-debt-ratio"], // 49
    ["ma-exchange-function", "ma-deflator-scope", "ma-labor-denominator", "ma-multiplier-limits"], // 50
    ["ma-cyclical-examples", "ma-cpi-steps", "ma-deficit-debt", "ma-neutrality"], // 51
    ["ma-unit-account", "ma-outside-labor", "ma-growth-level", "ma-policy-lags"], // 52
    ["ma-government-buying", "ma-saving-channels", "ma-gap-adjustment", "ma-disinflation"], // 53
    ["ma-productivity-inputs", "ma-automatic", "ma-real-adjustment", "ma-bank-capital"], // 54
    ["ma-human-capital", "ma-demand-expansion", "ma-deficit-debt", "ma-reserve-vs-capital"], // 55
    ["ma-frictional", "ma-cpi-steps", "ma-money-demand", "ma-debt-ratio"], // 56
    ["ma-government-buying", "ma-lras-drivers", "ma-reserve-constraints", "ma-phillips-shift"], // 57
    ["ma-bank-assets", "ma-deflator-scope", "ma-gap-adjustment", "ma-policy-lags"], // 58
    ["ma-productivity-inputs", "ma-fiscal-purchases", "ma-labor-denominator", "ma-disinflation"], // 59
    ["ma-frictional", "ma-monetary-expansion", "ma-cpi-bias", "ma-debt-ratio"], // 60
  ],
};
