import { relationship as g } from './relationship.js';

export const MACRO_GROUPS = [
  g('ma-gdp-parts', 1, 'concept', 'The expenditure components of GDP',
    ['Household consumption', 'Gross investment', 'Government purchases', 'Exports minus imports'],
    'The expenditure identity is Y = C + I + G + NX. Financial-asset purchases and transfer payments do not directly add to these expenditures on production.', 'gdp-components', ['gdp', 'fiscal'], 'Keep separate from investment examples, GDP exclusions, and saving identities.'),
  g('ma-capital-investment', 1, 'concept', 'New production counted as investment',
    ['New factory equipment', 'New residential building', 'Added business inventories', 'New software capital'],
    'GDP investment includes new capital, residential construction, and inventory accumulation. Buying an existing stock or bond is a financial transaction instead.', 'gdp-components', ['gdp', 'finance', 'growth'], 'Exclude saving/investment and productivity groups.'),
  g('ma-frictional', 1, 'concept', 'Job search and matching unemployment',
    ['Graduate seeking first job', 'Mover seeking local work', 'Quitter seeking better fit', 'Applicant comparing offers'],
    'These people are actively searching during ordinary matching between workers and jobs. This is frictional rather than recession-driven or skill-mismatch unemployment.', 'unemployment-types', ['labor'], 'Exclude all other unemployment and participation groups.'),
  g('ma-productivity-inputs', 1, 'concept', 'Sources of output per worker',
    ['Physical capital per worker', 'Worker skills and education', 'Resources per worker', 'Production knowledge'],
    'Capital, human capital, natural resources, and technology help determine how much a worker can produce.', 'sources-of-productivity', ['growth', 'supply'], 'Keep away from investment and potential-output groups.'),
  g('ma-bank-assets', 1, 'concept', 'Commercial bank assets',
    ['Vault cash holdings', 'Central-bank reserve balance', 'Loans to customers', 'Bank-owned securities'],
    'A bank owns these assets or claims. Customer deposits are bank liabilities, and capital is the difference between assets and liabilities.', 'bank-balance-sheets-reserves-and-capital', ['bank', 'finance', 'money'], 'Exclude monetary-policy securities, bank-capital and reserve groups.'),
  g('ma-exchange-function', 1, 'concept', 'Money as a medium of exchange',
    ['Cash paid for groceries', 'Currency paid for a haircut', 'Notes paid for a taxi', 'Coins paid for parking'],
    'Money is being used to complete a purchase, rather than simply quote a price or hold purchasing power for later.', 'money-functions-and-measures', ['money'], 'Payment verbs distinguish this role from unit-of-account examples.'),
  g('ma-government-buying', 1, 'concept', 'Government purchases of current output',
    ['Public teacher salaries', 'New military equipment', 'Road construction contracts', 'Government office supplies'],
    'Government purchases pay for current goods or services. Benefits paid without receiving current production in return are transfers.', ['gdp-components', 'budget-accounting-and-public-saving'], ['gdp', 'fiscal'], 'Exclude all transfer, GDP-component, and budget-accounting groups.'),
  g('ma-nominal', 1, 'concept', 'Amounts not adjusted for inflation',
    ['Current-dollar GDP', 'Unadjusted money wage', 'Debt in face-value dollars', 'Unadjusted money income'],
    'These are nominal amounts. Their dollar changes alone do not reveal changes in purchasing power or real production.', ['real-versus-nominal-gdp', 'indexing-and-real-values'], ['prices', 'gdp'], 'Do not mix with inflation adjustment or price-level distinctions.'),
  g('ma-stocks', 1, 'concept', 'Stocks measured at a point in time',
    ['Debt outstanding today', 'Capital installed today', 'Wealth held today', 'Money balance today'],
    'Stocks are amounts at a date. Income, investment, and deficits are flows measured over an interval.', 'deficits-debt-and-government-borrowing', ['stocks', 'fiscal', 'money'], 'Date-at-a-point wording is essential; avoid money, wealth, or debt mechanism groups.'),
  g('ma-human-capital', 1, 'concept', 'Investments in human capital',
    ['Job-specific training', 'Literacy education', 'Apprenticeship practice', 'Technical certification study'],
    'These build knowledge or skills embodied in people, unlike physical machinery. Greater skill can raise productivity.', 'sources-of-productivity', ['growth', 'labor'], 'Exclude general productivity and labor-market examples.'),
  g('ma-unit-account', 1, 'concept', 'Money as the measuring unit',
    ['Menu priced in dollars', 'Invoice totaled in euros', 'Accounts recorded in yen', 'Debt quoted in pounds'],
    'Money provides a common unit for quoting and recording values. No payment or saving action is required in these examples.', 'money-functions-and-measures', ['money', 'prices'], 'Do not mix with nominal-value or debt examples.'),
  g('ma-cyclical-examples', 1, 'concept', 'Job loss caused by weak aggregate demand',
    ['Recession-related factory layoff', 'Slump-related hotel layoff', 'Downturn-related retail layoff', 'Demand-collapse construction layoff'],
    'These job losses arise from reduced economy-wide spending, the defining setting for cyclical unemployment.', 'unemployment-types', ['labor', 'demand'], 'Exclude output-gap and demand-shock chains.'),

  g('ma-cpi-steps', 2, 'concept', 'A fixed-basket price-index calculation',
    ['Choose basket quantities', 'Collect current prices', 'Price the same basket', 'Divide by base-year cost'],
    'For the basic fixed-basket CPI, the cost ratio multiplied by 100 gives the index. Inflation is the percentage change in that index.', 'cpi-and-inflation-measurement', ['prices'], 'Do not put alongside deflator, index-bias, or inflation calculations.'),
  g('ma-demand-expansion', 2, 'causal', 'A positive aggregate-demand shock',
    ['Autonomous spending increases', 'Aggregate demand shifts right', 'Short-run output increases', 'General price level rises'],
    'With upward-sloping SRAS unchanged, stronger aggregate demand raises real output and the price level in the short run.', 'aggregate-demand', ['demand', 'prices', 'supply'], 'Exclude monetary/fiscal expansion, supply adjustment, and Phillips-curve mechanisms.'),
  g('ma-supply-shock', 2, 'causal', 'An adverse short-run supply shock',
    ['Energy input costs surge', 'SRAS shifts left', 'Output falls as prices rise', 'Stagflation pressure increases'],
    'With aggregate demand unchanged, higher input costs reduce short-run supply, lowering real output while raising prices.', 'demand-and-supply-shocks', ['supply', 'prices', 'labor'], 'Do not mix with other AD–AS or Phillips-curve shocks.'),
  g('ma-monetary-expansion', 2, 'causal', 'Interest-rate monetary transmission',
    ['Policy rate is reduced', 'Borrowing becomes cheaper', 'Rate-sensitive spending grows', 'Demand stimulus reaches firms'],
    'A lower policy rate can stimulate spending through borrowing costs. Transmission takes time and depends on financial conditions.', 'monetary-policy-transmission', ['policy', 'demand', 'finance', 'bank', 'money'], 'Exclude generic AD shifts, money-growth, and liquidity-preference mechanisms.'),
  g('ma-structural', 2, 'concept', 'Obstacles to matching workers with available jobs',
    ['Skills no longer demanded', 'Vacancies require new training', 'Jobs located far from workers', 'Occupations changed by technology'],
    'Persistent mismatch between workers and available work is structural unemployment, distinct from ordinary search or a cyclical spending slump.', 'unemployment-types', ['labor', 'growth'], 'Exclude human-capital examples that could fill the same category.'),
  g('ma-inflation-costs', 2, 'concept', 'Costs associated with inflation',
    ['Frequent repricing costs', 'Cash-management effort', 'Noisier relative prices', 'Distorted nominal tax measures'],
    'Inflation can increase transaction and repricing effort and complicate price comparisons and tax treatment. Not every cost requires falling real wages.', 'inflation-costs', ['prices', 'money'], 'Exclude CPI measurement biases; those are measurement problems, not these costs.'),
  g('ma-saving-channels', 2, 'concept', 'Channels connecting saving to borrowers',
    ['Corporate bond markets', 'Equity share markets', 'Bank lending', 'Bond mutual funds'],
    'Financial markets and intermediaries can move savers’ funds toward borrowers and investment. A financial claim is distinct from physical capital itself.', 'loanable-funds-equilibrium', ['finance', 'bank', 'growth'], 'Exclude bank assets and GDP investment examples.'),
  g('ma-automatic', 2, 'causal', 'Automatic fiscal support in a downturn',
    ['Tax receipts decline', 'Jobless benefit payouts rise', 'Eligible aid payments expand', 'Disposable income is cushioned'],
    'Existing tax and benefit rules can cushion a downturn without new legislation. Effects depend on eligibility and the tax system.', 'fiscal-policy-and-aggregate-demand', ['fiscal', 'labor', 'demand'], 'Exclude fiscal expansion and multiplier chains.'),
  g('ma-deflator-scope', 2, 'concept', 'Included in the GDP deflator’s scope',
    ['Domestically produced tractors', 'New domestic houses', 'Domestic business software', 'Domestically produced exports'],
    'The GDP deflator covers domestically produced final output, including investment and exports. Imported consumer goods can affect CPI but are outside this scope.', 'cpi-versus-gdp-deflator', ['gdp', 'prices', 'growth'], 'Keep apart from GDP investment and consumer price-index groups.'),
  g('ma-lras-drivers', 2, 'concept', 'Potential-output capacity can rise through',
    ['Larger capital stock', 'More available labor', 'Higher productive efficiency', 'Improved resource access'],
    'Changes in productive resources or technology can shift LRAS right. A higher aggregate price level alone does not raise long-run potential output.', 'long-run-aggregate-supply-and-potential-output', ['growth', 'supply'], 'Exclude productivity input lists and short-run output gaps.'),
  g('ma-fiscal-purchases', 2, 'causal', 'A government-purchases stimulus',
    ['Public orders increase', 'Suppliers receive revenue', 'Recipients spend part of income', 'Further rounds of demand follow'],
    'In a simple demand-driven model, an initial increase in government purchases can generate additional spending rounds. Saving, imports, taxes, and crowding out can reduce the effect.', 'fiscal-multipliers-and-crowding-out', ['fiscal', 'demand', 'finance'], 'Exclude transfer purchases distinction and multiplier assumption groups.'),
  g('ma-outside-labor', 2, 'trap', 'Not unemployed under the active-search definition',
    ['Retiree not seeking work', 'Student not seeking work', 'Discouraged nonsearcher', 'Homemaker not seeking work'],
    'People without a job who are not actively searching are generally outside the labor force, rather than counted as unemployed. Recall-related exceptions are outside these examples.', 'unemployment-measurement', ['labor'], 'No claim that every student, retiree, or homemaker is outside the labor force.'),

  g('ma-crowding-out', 3, 'causal', 'Closed-economy deficit crowding out',
    ['Government deficit grows', 'National saving falls', 'Real borrowing rate rises', 'Private investment is displaced'],
    'In the closed-economy loanable-funds model, a larger deficit reduces saving and raises the real interest rate, other things equal.', 'crowding-out-and-capital-formation', ['fiscal', 'finance', 'growth'], 'Exclude spending multipliers and saving identities.'),
  g('ma-cpi-bias', 3, 'concept', 'Challenges for a fixed-basket cost-of-living index',
    ['Consumers substitute goods', 'New products become available', 'Product quality changes', 'Shopping outlets change'],
    'An unchanged basket can miss shifts in choices, quality, products, and outlets. Modern statistical adjustments reduce these measurement problems.', 'cpi-bias', ['prices'], 'Measurement issues, not the separate resource costs of inflation.'),
  g('ma-reserve-constraints', 3, 'trap', 'Assumptions of the simple 1/r deposit multiplier',
    ['No extra reserve holdings', 'No public currency leakage', 'Loan proceeds redeposited', 'Fixed required reserve fraction'],
    'These textbook assumptions support the simple deposit-expansion formula. Without them, 1/r is not a reliable mechanical forecast of money creation.', 'deposit-creation-and-money-multiplier', ['bank', 'money', 'finance'], 'A conditional textbook model, not a description of all present monetary systems.'),
  g('ma-labor-denominator', 3, 'trap', 'A discouraged worker stops searching',
    ['Counted unemployed decreases', 'Labor force shrinks', 'Employment stays unchanged', 'Jobless rate can fall'],
    'Moving from unemployed to outside the labor force reduces both unemployment and the labor force. The unemployment rate can fall without anyone finding work.', 'unemployment-measurement', ['labor'], 'Exclude all labor categories and denominator groups.'),
  g('ma-real-adjustment', 3, 'trap', 'Convert nominal amounts into purchasing power',
    ['Divide wage by price index', 'Deflate nominal income', 'Use constant-price output', 'Remove inflation from returns'],
    'Real measures adjust for the price level or inflation to isolate purchasing power or output. Real interest uses the nominal rate and inflation, not division by a price index.', ['indexing-and-real-values', 'real-versus-nominal-interest-rates'], ['prices', 'gdp'], 'Methods differ; the relationship is the nominal-to-real adjustment, not one shared formula.'),
  g('ma-fisher', 3, 'causal', 'The long-run Fisher effect',
    ['Expected inflation rises', 'Real rate held constant', 'Nominal interest rate rises', 'Purchasing-power yield preserved'],
    'If the equilibrium real rate is unchanged, lenders require higher nominal interest when expected inflation rises. The usual introductory relation is i ≈ r + expected inflation.', 'fisher-effect', ['prices', 'finance', 'money'], 'Expected, not an unexpected inflation surprise.'),
  g('ma-gap-adjustment', 3, 'causal', 'Long-run adjustment from a recessionary gap',
    ['Output below potential', 'Wage pressure weakens', 'Production costs ease', 'SRAS moves right over time'],
    'In the textbook self-adjustment model with no further shock, weak labor demand lowers wage and cost pressure, eventually restoring potential output.', 'long-run-macroeconomic-self-adjustment', ['supply', 'labor'], 'This is conditional long-run adjustment, not a guarantee of rapid recovery.'),
  g('ma-money-demand', 3, 'causal', 'Higher income in the liquidity-preference model',
    ['More transactions occur', 'Money demand increases', 'Money supply held fixed', 'Nominal interest rate increases'],
    'At a fixed price level and money supply, higher real income raises transaction demand for money and puts upward pressure on the equilibrium interest rate.', 'liquidity-preference-and-money-market', ['money', 'finance', 'policy', 'demand'], 'Exclude AD expansions, money-supply or policy-rate changes; supply is fixed here.'),
  g('ma-quantity-growth', 3, 'causal', 'Money growth and inflation with stable velocity',
    ['Money stock grows faster', 'Velocity growth stays zero', 'Real-output growth unchanged', 'Inflation rate rises'],
    'The growth-rate quantity equation links money, velocity, prices, and real output. With stable velocity and unchanged real growth, faster money growth raises inflation.', 'quantity-theory-of-money', ['money', 'prices', 'growth'], 'Conditional long-run prediction, not a claim about every short-run episode.'),
  g('ma-deficit-debt', 3, 'trap', 'A smaller deficit can still raise debt',
    ['Annual deficit remains positive', 'Borrowing continues', 'Debt stock still increases', 'Debt grows more slowly'],
    'Reducing a deficit does not turn it into a surplus. Ignoring valuation and other adjustments, continued deficits keep adding to debt, though at a lower rate.', 'deficits-debt-and-government-borrowing', ['fiscal', 'stocks'], 'Exclude debt-to-GDP and all fiscal-flow examples.'),
  g('ma-phillips-move', 3, 'causal', 'A short-run demand expansion on the Phillips curve',
    ['Expected inflation unchanged', 'Unemployment falls temporarily', 'Actual inflation increases', 'Move along the same SRPC'],
    'With expectations and supply conditions fixed, stronger aggregate demand can temporarily trade lower unemployment for higher inflation.', 'short-run-phillips-curve', ['labor', 'prices', 'demand', 'policy'], 'Exclude expectation shifts; this is movement along a given curve.'),
  g('ma-growth-level', 3, 'trap', 'Higher saving: a level effect is not permanent faster growth',
    ['More capital accumulates', 'Output per worker rises', 'Capital faces diminishing returns', 'Transition growth eventually slows'],
    'In the standard diminishing-returns growth model, higher saving raises the long-run level of output per worker, but does not by itself sustain faster per-worker growth forever.', 'living-standards-and-growth', ['growth', 'finance'], 'Keep separate from technology and loanable-funds chains.'),

  g('ma-gdp-exclusions', 4, 'trap', 'Not purchases of current measured production',
    ['Purchase of existing shares', 'Resale value of a used car', 'Government cash transfer', 'Unpaid household cooking'],
    'Financial transfers, previously produced goods, and unpaid household services do not directly count as current measured GDP. New brokerage or resale services do count.', 'gdp-measurement', ['gdp', 'fiscal', 'finance'], 'Not a claim that the activities have no value or associated current services.'),
  g('ma-inflation-surprise', 4, 'trap', 'Unexpected inflation with fixed nominal debt',
    ['Contract rate already fixed', 'Actual inflation exceeds forecast', 'Borrower repays cheaper dollars', 'Lender’s real return is lower'],
    'When actual inflation exceeds what a fixed nominal contract anticipated, purchasing power shifts from lender to borrower. Indexed debt is different.', 'real-versus-nominal-interest-rates', ['prices', 'stocks'], 'Do not mix with the expected-inflation Fisher effect or loan losses that also hurt lenders.'),
  g('ma-bank-capital', 4, 'trap', 'A loan loss consumes bank capital',
    ['Loan asset written down', 'Deposit liabilities unchanged', 'Equity absorbs the loss', 'Leverage amplifies equity damage'],
    'With other balance-sheet items unchanged, an asset loss reduces capital dollar for dollar. A small asset loss can be a large percentage loss of equity at high leverage.', 'bank-balance-sheets-reserves-and-capital', ['bank', 'finance'], 'Solvency and capital, not an automatic fall in reserve balances.'),
  g('ma-reserve-vs-capital', 4, 'trap', 'Reserves and capital solve different problems',
    ['Reserves are liquid assets', 'Capital is net worth', 'Liquidity is not solvency', 'Cash alone need not absorb losses'],
    'Reserves help meet payments; capital is the asset–liability buffer against losses. An institution can be illiquid yet solvent, or liquid yet insolvent.', 'bank-balance-sheets-reserves-and-capital', ['bank', 'finance', 'money'], 'Do not mix with bank-asset or multiplier lists.'),
  g('ma-phillips-shift', 4, 'causal', 'Expectations remove a permanent inflation–jobs tradeoff',
    ['Higher inflation becomes expected', 'Wage demands adjust upward', 'Short-run Phillips curve shifts up', 'Unemployment returns to natural rate'],
    'In the expectations-augmented model, an unanticipated demand expansion cannot permanently hold unemployment below its natural rate once expectations adjust.', 'phillips-curve-expectations', ['labor', 'prices', 'policy', 'demand'], 'Exclude movement along a fixed SRPC and supply-shock groups.'),
  g('ma-policy-lags', 4, 'trap', 'Late stabilization can amplify a cycle',
    ['Recession recognized with delay', 'Policy approval takes time', 'Economy begins recovering', 'Stimulus arrives after recovery'],
    'Recognition, implementation, and transmission lags can cause a policy response to reach an economy after the original gap has changed or closed.', 'stabilization-policy', ['policy', 'demand', 'fiscal'], 'Timing chain rather than a blanket argument against stabilization.'),
  g('ma-disinflation', 4, 'trap', 'Disinflation is not a falling price level',
    ['Inflation stays positive', 'Inflation rate declines', 'Prices still rise', 'Purchasing power still erodes'],
    'Disinflation means slower inflation. If inflation remains positive, the price level continues rising; deflation means a negative inflation rate.', 'disinflation-and-policy', ['prices', 'money'], 'Do not combine with nominal/real or other inflation-level chains.'),
  g('ma-saving-identity', 4, 'trap', 'Saving equals investment in a closed economy',
    ['No net exports', 'Output less consumption and G', 'National saving', 'Investment in new capital'],
    'Combining Y = C + I + G with S = Y − C − G gives S = I in a closed economy. This is an accounting identity, not a claim that each household buys capital.', 'saving-and-investment-identities', ['gdp', 'finance', 'growth', 'fiscal'], 'Exclude financial-claim and investment-example groups.'),
  g('ma-neutrality', 4, 'trap', 'Long-run monetary neutrality is not short-run neutrality',
    ['Nominal prices can adjust', 'Real capacity set by resources', 'Money does not create real inputs', 'Short-run output can still respond'],
    'The classical long-run model separates nominal money from real productive capacity. Sticky prices allow short-run real effects without contradicting that long-run claim.', 'monetary-neutrality', ['money', 'growth', 'supply', 'policy'], 'Do not mix with monetary transmission, LRAS, or quantity-theory chains.'),
  g('ma-debt-ratio', 4, 'trap', 'Debt can rise while debt-to-GDP falls',
    ['Nominal debt increases', 'Nominal GDP grows faster', 'Debt share of GDP declines', 'Debt stock is not paid off'],
    'A ratio falls when its denominator grows proportionally faster than its numerator. Lower debt-to-GDP does not require a decline in nominal debt.', 'debt-measures-burden-and-fiscal-data', ['fiscal', 'stocks', 'gdp'], 'Keep apart from deficit-reduction and nominal-GDP groups.'),
  g('ma-multiplier-limits', 4, 'trap', 'Assumptions of the simple spending multiplier',
    ['Prices held fixed', 'Spare productive capacity', 'No induced interest-rate offset', 'Constant spending propensity'],
    'The simple Keynesian spending multiplier abstracts from price responses and crowding out and assumes a stable marginal propensity to consume. Relaxing these changes its size.', 'fiscal-multipliers-and-crowding-out', ['fiscal', 'demand', 'finance', 'supply'], 'Do not confuse with the deposit multiplier or its reserve assumptions.'),
  g('ma-unemployment-rates', 4, 'trap', 'Unemployment and participation have different denominators',
    ['Jobless share of labor force', 'Labor-force share of adults', 'Discouraged workers excluded from LF', 'Lower jobless rate not enough'],
    'Unemployment uses the labor force as denominator; participation uses the relevant adult population. A lower unemployment rate alone does not establish stronger employment.', 'unemployment-measurement', ['labor'], 'All labor examples excluded to avoid mixing definition and classification groups.'),
];
