import { relationship as g } from './relationship.js';

// Difficulty depends on the economic inference, not on tile length.
export const MICRO_GROUPS = [
  g('mi-demand-drivers', 1, 'concept', 'Demand determinants other than own price',
    ['Buyer income', 'Consumer tastes', 'Buyer expectations', 'Number of buyers'],
    'These can change desired purchases at every price. The good’s own price instead causes movement along demand.', 'demand', ['demand'], 'Keep separate from related-goods, demand movements, and equilibrium chains.'),
  g('mi-supply-drivers', 1, 'concept', 'Supply determinants other than own price',
    ['Input prices', 'Production technology', 'Number of sellers', 'Producer subsidies'],
    'These change sellers’ costs or capacity and can shift the supply curve, holding other determinants fixed.', 'supply', ['supply', 'cost', 'production'], 'Do not mix with cost, productive-capacity, scale, or entry chains.'),
  g('mi-public-examples', 1, 'concept', 'Nonrival, nonexcludable public goods',
    ['National defense', 'Open scientific theorem', 'Nonexclusive flood barrier', 'Free unencrypted broadcast'],
    'Under these stated conditions, one person’s benefit does not reduce another’s and nonpayers cannot readily be excluded.', 'public-goods-and-common-resources', ['goods'], 'Conditions in the labels matter; government provision alone is not the criterion.'),
  g('mi-common-examples', 1, 'concept', 'Open-access common resources',
    ['Open-access fishery', 'Unrestricted grazing land', 'Unregulated aquifer', 'Unmanaged public forest'],
    'Access is difficult to restrict, but harvesting or using the resource leaves less for others. These are rival, unlike public goods.', 'public-goods-and-common-resources', ['goods', 'external'], 'Exclude other goods classifications and external-cost lists from the same board.'),
  g('mi-explicit', 1, 'concept', 'Explicit costs: actual payments',
    ['Employee wages paid', 'Rent paid to landlord', 'Purchased raw materials', 'Utility bills paid'],
    'These involve payments to outside resource owners. Implicit costs are forgone opportunities from using resources already owned.', 'economic-costs', ['cost'], 'Payment wording distinguishes these from implicit and sunk-cost examples.'),
  g('mi-market-forms', 1, 'concept', 'Textbook market structures',
    ['Perfect competition', 'Monopolistic competition', 'Oligopoly', 'Monopoly'],
    'These market structures differ in seller numbers, product differentiation, and barriers to entry.', ['competitive-markets', 'monopolistic-competition', 'oligopoly', 'monopoly'], ['structure'], 'Exclude firm behavior and pricing groups that could absorb a market-structure label.'),
  g('mi-marginal-choices', 1, 'concept', 'Decisions at the margin',
    ['One more study hour', 'One additional worker', 'One extra production unit', 'One further inspection'],
    'Each asks about a small change in an activity. Compare its additional benefit with its additional cost, rather than total benefits and costs.', 'marginal-analysis', ['marginal', 'cost'], 'The extra-unit wording is the shared relationship.'),
  g('mi-substitutes', 1, 'concept', 'Pairs used as substitutes',
    ['Butter / margarine', 'Bus / subway', 'Tea / coffee', 'Cinema / streaming'],
    'When buyers see these as alternatives, a price rise for one tends to increase demand for the other, other things equal.', 'demand', ['demand', 'elasticity'], 'Examples assume ordinary alternative uses; do not pair with complements.'),
  g('mi-complements', 1, 'concept', 'Pairs used together as complements',
    ['Printer / ink', 'Car / fuel', 'Console / compatible games', 'Shoes / shoelaces'],
    'When goods are consumed together, a higher price for one tends to reduce demand for the other, holding other influences constant.', 'demand', ['demand', 'elasticity'], 'The compatible-use context rules out unrelated meanings.'),
  g('mi-scarce-inputs', 1, 'concept', 'Constraints that make choice necessary',
    ['Limited worker hours', 'Limited factory space', 'Limited farmland', 'Limited equipment capacity'],
    'Finite productive resources cannot satisfy all competing uses at once. Scarcity therefore requires tradeoffs even when prices are zero.', 'scarcity-and-tradeoffs', ['scarcity', 'production'], 'Keep apart from production-capacity and opportunity-cost chains.'),
  g('mi-private-goods', 1, 'concept', 'Rival and excludable private goods',
    ['A purchased sandwich', 'A privately owned bicycle', 'A purchased winter coat', 'A privately owned laptop'],
    'Owners can exclude others, and a unit used by one person is unavailable for simultaneous competing use.', 'public-goods-and-common-resources', ['goods'], 'Ownership and individual units are explicit; no digital or uncongested-service edge cases.'),
  g('mi-variable-inputs', 1, 'concept', 'Inputs adjustable within a shift',
    ['Hourly packing labor', 'Flour used in baking', 'Fuel used in deliveries', 'Packaging used per order'],
    'In a short-run model with plant size fixed, these inputs can vary as production changes.', 'short-run-production', ['production', 'cost'], 'Contrast with plant capacity only on separate boards.'),

  g('mi-ceiling-chain', 2, 'causal', 'A binding ceiling creates a shortage',
    ['Legal price below equilibrium', 'Buyers want more units', 'Sellers offer fewer units', 'Queue-based rationing'],
    'A ceiling below the competitive equilibrium increases quantity demanded and reduces quantity supplied. Nonprice rationing can allocate the shortage.', 'binding-price-ceilings', ['controls', 'demand', 'supply'], 'Quantities move along existing curves; do not mix with shifts.'),
  g('mi-floor-chain', 2, 'causal', 'A binding floor creates a surplus',
    ['Legal price above equilibrium', 'Fewer units buyers want', 'More units sellers offer', 'Unsold excess supply'],
    'A binding floor makes quantity supplied exceed quantity demanded in the standard competitive model, absent government purchases.', 'binding-price-floors', ['controls', 'demand', 'supply'], 'No government buyer is assumed.'),
  g('mi-sunk-examples', 2, 'trap', 'Already paid and unrecoverable',
    ['Nonrefundable ticket', 'Spent advertising budget', 'Forfeited application fee', 'Unrecoverable design expense'],
    'These are sunk costs after payment. They should not influence a new decision because neither available choice can recover them.', 'sunk-avoidable-costs', ['cost', 'marginal'], 'Exclude any list of explicit costs: sunk costs can also have been explicit.'),
  g('mi-negative-spillovers', 2, 'concept', 'Uncompensated harms to third parties',
    ['Smoke harming neighbors', 'Runoff damaging fisheries', 'Noise disturbing residents', 'Emissions warming the climate'],
    'The harm falls outside the buyer–seller transaction. Private decisions can omit this external portion of social cost.', 'externalities', ['external', 'goods'], 'Exclude commons and corrective-policy groups.'),
  g('mi-positive-spillovers', 2, 'concept', 'Benefits reaching third parties',
    ['Vaccination protecting others', 'Research knowledge spillovers', 'Pollination of nearby orchards', 'Training shared with coworkers'],
    'Some benefits accrue beyond the decision-maker. If uncompensated, private incentives may produce less of the activity than is socially efficient.', 'externalities', ['external', 'goods'], 'Benefits are external under the stated uncompensated interpretation.'),
  g('mi-elastic-demand', 2, 'concept', 'Conditions favoring elastic demand',
    ['Many close substitutes', 'Large budget share', 'Narrow market definition', 'More time to adjust'],
    'These tend to make purchases more responsive to price, other things equal. Elasticity is a percentage response, not simply a curve’s slope.', 'price-elasticity-of-demand', ['elasticity', 'demand'], 'Keep apart from related-goods examples and revenue/tax incidence chains.'),
  g('mi-scale-sources', 2, 'concept', 'Sources of economies of scale',
    ['Specialized work teams', 'Bulk input purchasing', 'Indivisible large machinery', 'Spread setup costs'],
    'Over an appropriate output range, these can reduce long-run average cost as the scale of production expands.', 'long-run-average-cost-scale', ['cost', 'production', 'structure'], 'Long-run scale, not adding workers to fixed equipment.'),
  g('mi-trade-steps', 2, 'causal', 'Comparative advantage enables trade gains',
    ['Compare opportunity costs', 'Specialize by relative cost', 'Agree on beneficial terms', 'Expand consumption possibilities'],
    'In the standard two-good model, specialization and a trading price between opportunity costs can make both parties better off.', 'gains-from-trade', ['trade', 'scarcity'], 'Exclude PPF and opportunity-cost trap groups.'),
  g('mi-ppf-outward', 2, 'concept', 'Potential sources of an outward PPF shift',
    ['Additional usable land', 'Improved production methods', 'More productive capital', 'Larger skilled workforce'],
    'More resources or better technology expand feasible production. Simply using idle resources moves toward an unchanged frontier.', 'production-possibilities-frontier', ['production', 'scarcity'], 'Differentiate capacity growth from better capacity use.'),
  g('mi-barriers', 2, 'concept', 'Barriers that can protect market power',
    ['Exclusive patent rights', 'Control of key inputs', 'Exclusive operating license', 'Large scale advantage'],
    'These can obstruct entry. A scale advantage can support natural monopoly when one supplier serves the relevant market at lower cost.', 'monopoly-power-barriers', ['structure', 'pricing', 'cost'], 'Exclude other monopoly, entry, and scale groups.'),
  g('mi-incentive-response', 2, 'causal', 'A higher congestion charge',
    ['Driving becomes costlier', 'Some trips rescheduled', 'Some travelers switch modes', 'Peak traffic eases'],
    'A peak-period road charge changes the marginal incentive to drive. With responsive travelers, it can reduce congestion, other things equal.', 'incentives', ['incentives', 'external', 'demand'], 'Exclude demand and elasticity examples involving transport.'),
  g('mi-surplus-meaning', 2, 'concept', 'Consumer surplus in equivalent words',
    ['Willingness to pay less price', 'Buyer’s net benefit', 'Value beyond payment', 'Area below demand above price'],
    'Consumer surplus is the value buyers receive beyond what they pay. The area interpretation uses the standard demand-as-marginal-benefit model.', 'consumer-surplus', ['welfare', 'demand'], 'Exclude producer surplus and other wedge/area groups.'),

  g('mi-incidence', 3, 'causal', 'Less elastic demand bears more tax',
    ['Buyers have fewer alternatives', 'Purchases resist price changes', 'Buyer price rises more', 'Consumers bear the larger share'],
    'When demand is less elastic than supply, buyers bear more of a small per-unit tax. Legal responsibility for remittance does not determine the burden.', 'tax-incidence', ['tax', 'elasticity', 'demand'], 'Comparative elasticity is essential; no claim that sellers are untaxed.'),
  g('mi-tax-remittance', 3, 'trap', 'Legal payer is not economic burden',
    ['Tax remitted by sellers', 'Tax collected from buyers', 'Same per-unit tax wedge', 'Same equilibrium burden split'],
    'For the same competitive market and per-unit tax, changing who remits it leaves the equilibrium burden unchanged, absent enforcement differences.', 'statutory-versus-economic-tax-incidence', ['tax', 'welfare', 'controls'], 'Exclude price-control and tax-burden groups with shared price-wedge meanings.'),
  g('mi-entry', 3, 'causal', 'Competitive profits attract entry',
    ['Positive economic profits', 'New firms enter', 'Industry supply expands', 'Market price is pushed down'],
    'With free entry, profits attract producers. In the standard long-run competitive model, entry erodes economic profit toward zero.', 'competitive-entry-exit-long-run', ['structure', 'supply', 'cost'], 'Market supply changes; an individual price-taking firm does not choose market price.'),
  g('mi-diminishing-product', 3, 'causal', 'More workers around fixed equipment',
    ['Capital held fixed', 'Workers added successively', 'Extra output per worker falls', 'Marginal cost rises'],
    'Once diminishing marginal product sets in, each extra worker contributes less output. At a fixed wage, the cost of another unit then rises.', 'marginal-cost-production-linkages', ['production', 'cost', 'marginal'], 'Short-run conditional chain, not a claim that total output must fall.'),
  g('mi-revenue', 3, 'causal', 'A price cut with elastic demand',
    ['Price reduced slightly', 'Demand elasticity exceeds one', 'Sales rise proportionally more', 'Total revenue increases'],
    'For a small price reduction on an elastic portion of demand, the percentage gain in quantity outweighs the percentage loss in price.', 'elasticity-and-total-revenue', ['elasticity', 'demand', 'pricing'], 'Exclude demand-shift groups; the demand curve stays fixed.'),
  g('mi-commons-chain', 3, 'causal', 'Why an open-access resource is overused',
    ['Private harvest benefits', 'Depletion costs shared', 'Race to extract', 'Stock falls too quickly'],
    'Each user gains from extraction while sharing the depletion cost with others. Uncoordinated incentives can yield excessive resource use.', 'public-goods-and-common-resources', ['goods', 'external'], 'Exclude other third-party-cost groups.'),
  g('mi-profit-trap', 3, 'trap', 'Zero economic profit can sustain a firm',
    ['All opportunity costs covered', 'Normal owner return earned', 'Accounting profit may be positive', 'No extra incentive to enter'],
    'Zero economic profit includes the opportunity cost of the owner’s resources. It does not mean zero accounting profit or a reason to close.', 'profit-concepts', ['cost', 'structure'], 'Exclude entry and implicit-cost examples.'),
  g('mi-opportunity-trap', 3, 'trap', 'Opportunity cost is the next-best alternative',
    ['Best forgone option', 'Not every rejected option', 'Time can count', 'Owned resources can count'],
    'Opportunity cost is the value of the best alternative sacrificed. Adding every rejected option overstates what one choice actually gives up.', 'opportunity-cost', ['scarcity', 'cost', 'trade'], 'Use with unrelated topics; avoid implicit-cost and trade groups.'),
  g('mi-ppf-inside', 3, 'trap', 'Inside the frontier: feasible but inefficient',
    ['Unemployed productive workers', 'Idle usable machinery', 'Output below feasible capacity', 'More of both goods possible'],
    'An interior PPF point leaves productive potential unused. Better resource use can raise both outputs without shifting the frontier.', 'production-possibilities-frontier', ['production', 'scarcity'], 'No conflict with demand shortages; these are economy-wide production possibilities.'),
  g('mi-tariff-chain', 3, 'causal', 'A tariff in a small importing country',
    ['Domestic import price rises', 'Local production expands', 'Domestic purchases contract', 'Import volume shrinks'],
    'With an unchanged world price and a tariff that still permits imports, higher domestic prices raise supply and lower demand for the traded good.', 'tariffs-revenue-deadweight-loss', ['trade', 'tax', 'demand', 'supply'], 'Small-country assumption and positive remaining imports are required.'),
  g('mi-free-rider', 3, 'trap', 'Free riding can underprovide public goods',
    ['Nonpayers still benefit', 'Individual payment withheld', 'Voluntary funding falls short', 'Social value exceeds receipts'],
    'When exclusion is difficult, some beneficiaries can enjoy a public good without paying, weakening private provision incentives.', 'public-goods-and-common-resources', ['goods', 'external', 'welfare'], 'Underprovision is a tendency, not proof that private provision is impossible.'),
  g('mi-collusion', 3, 'causal', 'The incentive to cheat on a cartel',
    ['Joint output restricted', 'Industry price kept high', 'Secret extra sales tempting', 'Agreement becomes unstable'],
    'A cartel can raise joint profit by restricting output, but each member may gain from extra sales. Enforcement or repetition can change that incentive.', 'oligopoly-collusion-cartels', ['strategy', 'structure', 'pricing'], 'Exclude other strategic-action and pricing groups.'),

  g('mi-shutdown', 4, 'trap', 'Producing at a loss can beat shutting down',
    ['Price below average total cost', 'Price above average variable cost', 'Some fixed costs recovered', 'Short-run production continues'],
    'At the profit-maximizing output, a competitive firm can cover variable costs and part of fixed costs even with an economic loss. Unavoidable fixed costs remain if it shuts down.', 'competitive-shutdown', ['cost', 'structure', 'production'], 'This is the short-run shutdown distinction, not the long-run exit rule.'),
  g('mi-monopoly-output', 4, 'trap', 'A monopolist chooses quantity before reading price',
    ['Set marginal revenue equal to cost', 'Choose the associated quantity', 'Read price from demand', 'Price exceeds marginal revenue'],
    'For an interior single-price monopoly optimum with downward-sloping demand, MR = MC selects quantity. The demand curve then determines the price buyers will pay.', 'monopoly-output-price', ['structure', 'pricing', 'demand', 'marginal'], 'Exclude all market-structure and demand-mechanism groups.'),
  g('mi-coase', 4, 'concept', 'Conditions behind efficient Coase bargaining',
    ['Clear property rights', 'Low bargaining costs', 'Enforceable agreements', 'Affected parties can negotiate'],
    'Under the standard Coase conditions, parties can bargain toward efficient activity. Initial rights still affect who pays and who gains.', 'externalities', ['external', 'goods', 'welfare'], 'Conditions are jointly required; no promise that bargaining always succeeds.'),
  g('mi-discrimination', 4, 'concept', 'What makes price discrimination feasible',
    ['Seller has market power', 'Buyer valuations differ', 'Buyers can be separated', 'Resale can be limited'],
    'A seller needs market power and a way to separate buyers or induce self-selection without easy resale undoing the price differences.', 'monopoly-price-discrimination', ['structure', 'pricing', 'elasticity'], 'Do not mix with barriers, elastic demand, or market-structure lists.'),
  g('mi-tax-efficiency', 4, 'trap', 'Tax revenue is not deadweight loss',
    ['Revenue transfers purchasing power', 'Lost trades destroy surplus', 'Tax receipts can benefit others', 'Deadweight loss excludes receipts'],
    'In the standard surplus model, tax revenue is a transfer to government. Deadweight loss is the surplus lost on mutually beneficial exchanges that no longer occur.', 'tax-wedges-and-revenue', ['tax', 'welfare', 'trade'], 'Exclude tax-incidence and surplus-area groups.'),
  g('mi-nash', 4, 'trap', 'A Nash equilibrium need not maximize joint payoff',
    ['Each action is a best response', 'Unilateral deviation cannot help', 'Joint improvement may exist', 'Coordination can still fail'],
    'Nash equilibrium rules out profitable unilateral changes, not mutually beneficial coordinated changes. The prisoners’ dilemma illustrates the distinction.', 'oligopoly-game-theory-foundations', ['strategy', 'structure'], 'Keep separate from cartel incentives.'),
  g('mi-mcomp', 4, 'trap', 'Long-run monopolistic competition',
    ['Free entry erodes profits', 'Differentiation preserves a markup', 'Price equals average total cost', 'Output below minimum-cost scale'],
    'In the standard symmetric model, entry drives economic profit to zero while downward-sloping firm demand leaves a markup and excess capacity.', 'mcomp-entry-exit-long-run', ['structure', 'cost', 'pricing'], 'This is not competitive P = MC; avoid competing structure groups.'),
  g('mi-advantage', 4, 'trap', 'Absolute advantage is not comparative advantage',
    ['Fewer inputs per unit', 'Higher output per hour', 'Lower opportunity cost not assured', 'Trade gains may still exist'],
    'The first two describe absolute productivity. Comparative advantage depends on relative opportunity costs, so being more productive at everything does not rule out trade gains.', 'gains-from-trade', ['trade', 'scarcity', 'production'], 'All four qualify one distinction, not a list of comparative-advantage definitions.'),
  g('mi-marginal-average', 4, 'trap', 'Marginal below average pulls average down',
    ['Next unit below current average', 'Total cost still increases', 'Average cost decreases', 'Marginal cost may be rising'],
    'An additional unit costing less than the current average lowers average cost. Marginal cost can already be rising while remaining below average cost.', 'short-run-cost-curves', ['cost', 'marginal', 'production'], 'Distinguish a level comparison from a trend; exclude all other cost groups.'),
  g('mi-simultaneous', 4, 'trap', 'Demand and supply both increase',
    ['Demand shifts rightward', 'Supply shifts rightward', 'Equilibrium quantity must rise', 'Price direction is ambiguous'],
    'With ordinary slopes, both shifts raise equilibrium quantity. Their effects on price oppose each other, so relative shift size matters.', 'market-equilibrium', ['demand', 'supply'], 'Keep away from any other demand, supply, control, or tariff chain.'),
  g('mi-corrective', 4, 'trap', 'A corrective tax can improve efficiency',
    ['Unpriced external damage', 'Social cost exceeds private cost', 'Tax matches marginal harm', 'Overproduction is reduced'],
    'A well-calibrated Pigouvian tax can internalize an external cost and reduce an existing inefficiency. This differs from taxing an otherwise efficient market.', 'externalities', ['external', 'tax', 'welfare', 'goods'], 'Exclude ordinary tax deadweight-loss and spillover examples.'),
  g('mi-binding-contrast', 4, 'trap', 'Price controls that do not bind',
    ['Ceiling above market price', 'Floor below market price', 'Equilibrium remains legal', 'No forced quantity imbalance'],
    'A ceiling above equilibrium or floor below it imposes no active constraint in the standard model. A legal limit need not change the market outcome.', ['binding-price-ceilings', 'binding-price-floors'], ['controls', 'demand', 'supply'], 'Both controls are nonbinding; never pair with binding-control chains.'),
];
