import json
from pathlib import Path
from collections import Counter
W=Path(__file__).resolve().parent
def read(n):return json.loads((W/n).read_text('utf8'))
def write(n,x):(W/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n','utf8')
b=read('inventory-before.json');records=b['records']
notes={
'EXT.1':(['G'],'Four sign/channel combinations and private versus third-party effects are already explicit. Retain fast fundamentals.'),
'EXT.2':(['B','C'],'Negative production and consumption, private/social intersections and triangular welfare losses are present at Hard. Some Hard records are single lookups and DWL distractors use implausibly different units.'),
'EXT.3':(['B','C','F'],'Standards, flexibility, enforcement and imperfect correction are selected. Hard enforcement diagnosis and Elite graph comparison can require more than naming the stated limitation.'),
'EXT.4':(['B','C','F'],'Tax wedges, post-policy revenue, DWL and incidence are covered. Preserve strong graph calculation; improve a standalone Hard calculation and selected upper-tier linked welfare/price reasoning.'),
'EXT.5':(['G'],'Both production and consumption benefits, underprovision and Hard DWL are present. No missing positive-externality objective; one graph distractor correction is warranted.'),
'EXT.6':(['B','F'],'Subsidy direction, wedge, spending and social quantity are covered. Two Hard prompts incorrectly suggest an upper quantity limit will increase underproduction; specify an implementable expansion instrument. Elite can connect receipts to fiscal cost.'),
'EXT.7':(['B','C','D','F'],'Cap, trades, marginal abatement costs, distribution and monitoring are present. Hard can allocate reductions; Legendary cap subtraction and allocation slogans need constraints and distribution reasoning.'),
'EXT.8':(['B','D','F'],'Integration, contracts, norms, capitalization and transaction costs exist. Upper tiers often identify one mechanism or subtract two supplied values. Link capturable benefit, payment feasibility and competing contracts.'),
'EXT.9':(['B','D','F'],'Hard graph targets and explicit Coase assumptions exist. Graph Legendary records tagged coase_policy_comparison do not actually compare bargaining with policy. Integrate rights, net gains, distribution and costs.'),
'PGCR.1':(['B','C','F'],'Marginal provision and context-dependent rivalry are present. Legendary marginal-cost lookup can become reverse inference from a budget and marginal curves.'),
'PGCR.2':(['B','C','F'],'All four goods categories and vertical summation are covered. Hard individual-MB lookup and Legendary meal/signal classification are under-demanding. Link multiple dimensions and institutions.'),
'PGCR.3':(['B','F'],'Access technology and enforcement are covered. Upper-tier login recognition can compare effective exclusion, revenue and lost beneficial access.'),
'PGCR.4':(['B','F'],'Rivalry, digital capacity, timber and congestion are covered. An Elite timber definition can connect present extraction, access and future scarcity.'),
'PGCR.5':(['B','C','D','F'],'Free riding, strategic reports and graph quantity gaps are covered. Add genuine Hard contribution incentives and selected Legendary financing/benefit aggregation reasoning.'),
'PGCR.6':(['B','D','F'],'Private provision through donations, sponsorship and procurement is appropriately recognized. Legendary profitability can evaluate alternative funding arrangements without equating revenue and social value.'),
'PGCR.7':(['B','C','F'],'Cost-benefit, MSB=MC, aggregation and survey limitations exist. Strengthen a Hard policy choice and Legendary overprovision/welfare inference; retain existing marginal comparison Hard records.'),
'PGCR.8':(['B','C','D','F'],'Commons overuse, groundwater, congestion, race to extract and enforcement are covered. Hard can compare private/social trip margins; Legendary should compare actual access and compliance constraints.'),
'PGCR.9':(['G'],'Enforceability, dynamic stewardship, community rights, catch shares and practical limits already have appropriate introductory coverage. No numerical or graph expansion is required for its own sake.')}
out=[]
for c,v in b['views'].items():
 for obj,count in b['byConcept'][c]['objectives'].items():
  qs=[q for q in records.values() if q['primaryConceptId']==c and q['objective']==obj]
  if obj in notes:cats,note=notes[obj]
  elif c=='market-power':cats,note=['B','C','F'],'Definition, output restriction, entry and natural-monopoly tradeoff exist. Only one ordinary Hard and two Legendary records; revise those to test forgone trades and constrained remedy/incentive comparisons. No full monopoly chapter is imported.'
  else:cats,note=['B','F'],'Legacy umbrella objective contains relevant selected fundamentals and support records. Retain simple repair/checkpoints; strengthen selected upper-tier recognition prompts within their existing primary skill.'
  out.append(dict(concept=c,objective=obj,label=v.get('objectiveLabels',{}).get(obj,obj),count=count,categories=cats,findings=note,difficulty=dict(Counter(q.get('canonicalDifficulty','unknown') for q in qs)),evidenceIds=[q['id'] for q in qs],wholeObjectiveAbsent=False))
write('objective-findings-before.json',out)
scope=dict(preset=b['preset'],directSelections=[],derivedSelections=b['preset']['selectedConceptIds'],authoritativeSource="MQ_COMPOSER_LIBRARY.concepts['market-failures'] filtered by each derived view's subtopicFilterId through core.resolveConceptModule",included=['Negative production and consumption externalities','Positive production and consumption externalities','Corrective taxes and subsidies','Standards and command-and-control regulation','Tradable permits and abatement allocation','Coase bargaining, transaction costs and private solutions','Public goods, nonrivalry, nonexcludability, free riding','Common resources, congestion and depletion','Club/private goods and context-dependent classification','Public-good benefit aggregation and cost-benefit reasoning','Enforceable property/access rights and community institutions','Introductory market power, output restriction, entry, patent incentives and natural-monopoly pricing tradeoff'],scopeBoundaries=['Asymmetric information','Adverse selection','Moral hazard','Signaling','Screening','Principal-agent problems','Labor-market discrimination','Human capital and compensating differentials','Income distribution and poverty','Behavioral economics','Detailed monopoly/oligopoly models and legal doctrine'],evidence='Current resolved question objects and their objective/primarySkill fields. Broad inherited repair-route key names do not establish selected curriculum; historical sourceOccurrences do not establish it either.',noNewAssessmentAttached=True)
write('scope-boundary.json',scope)
lines=['# Findings documented before authoring','','All three selections are derived views of market-failures. Exact raw source and resolved objects are in inventory-before.json. No production content has been edited.','','No entire selected objective is absent. This bank has strong breadth and correct existing graph arithmetic, but tier calibration is uneven. Some normal exam calculations already occur at Hard. Many higher-tier prompts merely restate a definition or read one coordinate. No new assets or questions are planned.','','Concrete defects: positive-externality Hard questions 42047/42057 describe a quantity limit as a way to raise underprovided output; an upper cap alone cannot do that. EXTERNALITY-B/D descriptions name efficient outcomes absent from visible labels; C metadata assigns economic roles to unlabeled brackets. A descriptions omit horizontal endpoint coordinates needed to reconstruct the curves. PUBLIC-02 alt text reveals efficient provision. Preserve detailed correct public-good descriptions and all image bytes.','','Quality auditor: 362 resolved questions, 0 errors, 59 warnings, 64 review flags. The raw derived definitions produce a misleading zero-record run; the audit-only resolved projection and provenance are captured.','','| Concept / objective | Categories | Findings |','|---|---|---|']
for x in out:lines.append(f'| {x["concept"]} / {x["objective"]} | {", ".join(x["categories"])} | {x["findings"]} |')
lines+=['','A: absent selected coverage; B: robustness; C: calibration; D: calculation/integration; E: graph-use; F: upper-tier synthesis; G: no material gap. No whole-objective A or missing-asset E is established. Existing graph use is plentiful; depth and assessment-safe accessibility need targeted work. Not all examples in a flagged objective require revision.']
(W/'AUDIT_FINDINGS_BEFORE.md').write_text('\n'.join(lines)+'\n','utf8')
print('Documented',len(out),'objective/view findings before authoring.')
