import json,hashlib
from pathlib import Path
from collections import Counter
W=Path(__file__).resolve().parent;R=Path('C:/Users/Jennings/Documents/GitHub/masteryquests-website/build/faculty-build-composer')
def read(n):return json.loads((W/n).read_text('utf8'))
def write(n,x):(W/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n','utf8')
b=read('inventory-before.json');a=read('inventory-after.json');v=read('validation.json');changes=read('changes.json');content=[x for x in changes if x['contentRevised']];actions=read('record-actions.json');obj=read('objective-findings-before.json');qb=read('quality-before.json');qa=read('quality-after.json');spec=read('revisions.json');browser=read('browser-validation.json')
def locations(m):return [(p,q) for p,ls in m.get('questions',{}).items() for q in ls]+[(p,q) for p in ['repairQuestions','repairSeedQuestions','bridgeQuestions'] for q in m.get(p,[])]
parent=b['authoritativeSources']['market-failures'];parentQs={str(q['id']):q for p,q in locations(parent)};excluded={k:q for k,q in parentQs.items() if k not in b['records']}
scope=read('scope-boundary.json');scope.update(parentUniqueRecords=len(parentQs),selectedUniqueRecords=len(b['records']),unselectedParentRecordsUnchanged=len(excluded),unselectedParentEvidence=[dict(id=k,objective=q.get('objective'),subtopicIds=q.get('subtopicIds'),primarySkill=q.get('primarySkill')) for k,q in excluded.items()]);write('scope-boundary.json',scope)
reasons={
'graph-prompt-missing-cue':'The existing image is present and the generated renderer was checked for this record. Some stems refer to graph-specific quantities or curves without the auditor’s expected cue phrase. Retain as a wording warning; no asset or graph eligibility was removed to suppress it.',
'repeated-feedback':'Retained legacy feedback repeats an explanation across nearby support/variant records. This is a documented robustness limitation, not a claim of zero-warning quality.',
'possible-difficulty-overstatement':'Retained upper tiers still include direct recognition and one-step tasks. Metadata is deliberately preserved. Targeted revisions establish stronger chains without claiming every tier mismatch is resolved.',
'possible-difficulty-understatement':'An existing Easy graph comparison asks more than definition recall. It remains a calibration review flag; no tier or pool was moved.',
'answer-length-outlier':'The correct choice remains longer than some alternatives in this retained record. This is a residual distractor cue and is not asserted resolved.',
'weak-absolute-distractors':'Review flag remains: absolute claims can encode the selected misconception, but some retained alternatives are too easy to eliminate. No claim is made that all distractors are equally strong.'}
specific={
('42084','possible-difficulty-overstatement'):'Final item requires selecting the social intersection, reading both private prices and computing a full-unit subsidy budget. It is a modest Elite integration task; the heuristic flag is retained for faculty review.',
('42199','possible-difficulty-overstatement'):'Final checkpoint requires reconstructing the North-only provision decision, contrasting summed provision and integrating omitted net benefits. It is no longer a direct coordinate lookup despite the heuristic flag.',
('42156','weak-absolute-distractors'):'The alternatives represent efficiency/distribution confusion under explicit ideal Coase assumptions. Their absolute wording is a retained review limitation.',
('42189','weak-absolute-distractors'):'The alternatives use initial or final marginal cost for the whole interval and confuse gross benefit with budget cost. These are deliberate quantitative misconceptions; the wording heuristic remains.',
('P77-MFAIL-L-022','weak-absolute-distractors'):'The choices omit marginal external benefits, resource costs or implementation costs. The repeated “only” formulation remains a stylistic cue, disclosed for faculty review.',
('P52B-MFAIL-L-003','weak-absolute-distractors'):'The alternatives isolate accounting losses, break-even or subsidy transfers as sufficient welfare tests. The repeated “only” structure is a residual cue even though the economic confusions are relevant.',
('P77-MFAIL-L-020','weak-absolute-distractors'):'The alternatives ignore either current access gains or future innovation incentives. Repeated “only” wording remains a style limitation.',
('42285','weak-absolute-distractors'):'The alternatives deliberately conflate rival depletion with nonrival underfunding. Some absolute language remains easier to eliminate than the correct two-mechanism account.',
('42210','weak-absolute-distractors'):'The incorrect funding plans confuse contractor ownership, changing exclusion, rivalry and automatic cross-financing. The strongest terms remain heuristic review flags.'}
beforeKeys={(f['questionId'],f['rule']) for f in qb['findings']};afterKeys={(f['questionId'],f['rule']) for f in qa['findings']};dispositions=[]
for f in qb['findings']:
 k=f['questionId'],f['rule'];remains=k in afterKeys
 dispositions.append(dict(questionId=k[0],rule=k[1],severityBefore=f['severity'],status='retained-review' if remains else 'no-longer-reported',contentRevised=k[0] in spec,reason=specific.get(k,reasons[k[1]]) if remains else 'The final wording no longer triggers this rule; this is a heuristic change, not an assertion that all content-quality concerns disappeared.'))
for f in qa['findings']:
 k=f['questionId'],f['rule']
 if k not in beforeKeys:dispositions.append(dict(questionId=k[0],rule=k[1],severityBefore=None,status='new-review-flag',contentRevised=k[0] in spec,reason=specific.get(k,reasons[k[1]])))
write('quality-dispositions.json',dict(before=qb['counts'],after=qa['counts'],beforeQuestionCount=qb['scope']['questionCount'],afterQuestionCount=qa['scope']['questionCount'],method='Existing auditor run against exact resolved selected modules in an audit-only projection; all original and newly reported question/rule pairs accounted for. Projection provenance is separate from the source-library hash.',findings=dispositions))
# Independent file/route checks supplement the content and core validations.
reviewChecks=[]
for item in b['conceptReview']['assets']:
 p=R/item['sourcePath'];actual=hashlib.sha256(p.read_bytes()).hexdigest();assert actual==item['sha256'];reviewChecks.append(dict(code=item['code'],path=item['sourcePath'],sha256=actual,verified=True))
old=read('library-baseline.json');new=read('library-after.json')
assert all(old['concepts'][c]==new['concepts'][c] for c in old['concepts'] if c!='market-failures')
newParent={str(q['id']):q for p,q in locations(new['concepts']['market-failures'])};assert all(newParent[k]==q for k,q in excluded.items())
aliasFields=['canonicalId','sourceId','sourceGame','sourceOccurrences','sourceHash','sourcePool','sourceDifficulty','difficulty','canonicalDifficulty','primarySkill','secondarySkills','repairSkill','objective','tag','subtopicIds']
assert all({k:q.get(k) for k in aliasFields}=={k:newParent[id].get(k) for k in aliasFields} for id,q in parentQs.items())
protected={}
for file,sha in b['sourceFiles'].items():
 actual=hashlib.sha256((R/file).read_bytes()).hexdigest();assert actual==sha;protected[file]=actual
for filename in ['composer_registry.json','composer_library_manifest.json']:
 orig=json.loads((R/'data'/filename).read_text('utf8'));after=json.loads((W/'staged'/filename).read_text('utf8'));orig.pop('librarySha256');after.pop('librarySha256')
 for x in [orig,after]:
  for asset in x.get('assets',[]):asset.pop('imageAlt',None);asset.pop('graphDescription',None)
 assert orig==after
write('architecture-validation.json',dict(unselectedConceptDefinitionsUnchanged=148,unselectedParentRecordsUnchanged=25,sourceAliasAndIdentityFieldsPreserved=True,newSourceIdAliases=0,sourceAndCanonicalDifficultyPreserved=True,sourceParentPoolOrderPreserved=True,resolvedPoolOrderPreserved=True,checkpointAndRepairAndBridgeRoutingPreserved=True,modeMembershipPreserved=True,reviewAssets=reviewChecks,reviewCodes=['MICRO-54','MICRO-55','MICRO-56'],reviewRuntimeRoutesPreserved=True,protectedFileHashesBeforeApply=protected,sidecarOnlyChanges='Shared semantic hash and approved asset accessibility fields. No engine, UI, Worker, telemetry, access or other content edits.'))
countBy=lambda xs,k:dict(Counter(x[k] for x in xs))
accounting=dict(totalBefore=362,totalAfter=362,added=0,removed=0,contentRevised=48,assetMetadataOnly=102,unchanged=212,questionContentUnchanged=314,questionObjectsWithInlineAccessibilityUpdates=116,contentAndAccessibilityOverlap=14,assetsInspected=18,assetContractsCorrected=14,longDescriptionsCorrected=13,altTextsCorrected=14,numericalItemsIndependentlyChecked=36,graphLinked=147,trialGraphEligible=133)
accounting['contentRevisionsByConcept']=countBy(content,'concept');accounting['contentRevisionsByDifficulty']=countBy(content,'difficulty');accounting['contentRevisionsByType']=countBy(content,'type');accounting['contentRevisionsByObjective']=countBy(content,'objective');accounting['dispositionsByConcept']={c:countBy([x for x in actions if x['concept']==c],'disposition') for c in b['preset']['selectedConceptIds']};write('accounting.json',accounting)
lines=['# Market Failures & Public Goods — production assessment-quality audit','',
'The current preset retains **362 questions: 48 content revisions, 102 accessibility-only record revisions and 212 unchanged records**. No questions or images were added or removed. Core coverage is broad; the largest weaknesses were repetitive upper-tier recognition and some shallow Hard applications, not missing chapters. All changes are local; no commit, push, merge or deployment was performed.','',
'## 1. Exact live preset and authority','',
'The quick start in `build/faculty-build-composer/composer.js` is **`micro-market-failures-public-goods` — “Market Failures & Public Goods”**. It selects `externalities`, `public-goods-and-common-resources`, and `market-power`. All are **derived views**, not direct question containers.','',
'`composer-core.js:1048` resolves each view by filtering `MQ_COMPOSER_LIBRARY.concepts["market-failures"]` for the view’s `subtopicFilterId` in each record’s `subtopicIds`. It clones and remaps the primary concept, tag and runtime subtopic, filters route references and used assets, and retains the parent’s authoritative question identity. Only selected records within that parent were edited. Raw view definitions and all 25 excluded parent records are unchanged. The parent has 387 unique records; 362 are selected. All 148 other concept definitions are unchanged.','',
'The BEFORE inventory contains the exact raw parent, raw selected definitions, resolved question objects, ordered ordinary/checkpoint/repair/bridge collections, assets, routes, review mapping and file hashes. It was captured before authoring. Objective findings were documented before revisions. Current runtime membership determines scope; historical filenames and sourceOccurrences remain provenance only.','',
'## 2. Selected objectives and counts','',
'| Derived view | Before / after | Content revised | Metadata only | Unchanged | Objective IDs in actual records |','|---|---:|---:|---:|---:|---|']
for c,info in b['byConcept'].items():
 d=accounting['dispositionsByConcept'][c];lines.append(f'| {c} | {info["unique"]} | {d.get("content-revised",0)} | {d.get("asset-metadata-only",0)} | {d.get("unchanged",0)} | '+', '.join(info['objectives'])+' |')
lines+=['','There are 24 objective/view combinations and 20 distinct objective IDs: EXT.1–EXT.9, PGCR.1–PGCR.9, LO1.6 and GE.7.7. The last two are legacy umbrella codes that occur in multiple selected views. The source labels do not provide a descriptive GE.7.7 label; it is reported as its actual ID. Derived concept-title entries in objectiveLabels are not counted as additional zero-question objectives. Module-level sourceChapters are [1, 6]; exact record-level sourceChapter and sourceOccurrences are preserved.','',
'## 3. Curricular boundary','',
'Included: negative production and consumption externalities; positive production and consumption spillovers; private/social marginal curves; taxes, subsidies, regulation, permits and abatement; Coase, enforceability, transaction costs and private solutions; public goods, common resources, club/private goods, rivalry and exclusion; free riding, benefit aggregation, cost-benefit reasoning, commons institutions and property rights; introductory market power, restricted trades, entry, natural-monopoly financing and exclusive-right innovation incentives.','',
'**Scope boundaries, not missing coverage:** asymmetric information, adverse selection, moral hazard, signaling, screening, principal-agent problems, labor discrimination, human capital, compensating differentials, inequality/poverty, behavioral economics and detailed monopoly/oligopoly or legal doctrine. Broad inherited repair-route key names do not establish selected curriculum: their references are filtered to selected support records. `scope-boundary.json` records the actual excluded-parent evidence. No new source assessment accompanied this request, and no prior exam was imported into this audit.','',
'## 4. Exact before/after accounting','',
'362 before and after; 0 added; 0 removed; 48 content-revised; 102 asset-metadata-only; 212 wholly unchanged. The 48 content revisions overlap 14 records with accessibility updates. In total, 116 records received synchronized inline accessibility fields. Thus 314 stems/options/keys/feedback objects are unchanged, but only 212 complete question objects are unchanged. Fourteen shared asset contracts were corrected: 13 long descriptions and 14 alt texts. These asset counts are separate from the mutually exclusive question dispositions.','',
'`record-actions.json` has one disposition for every scoped ID. `changes.json` contains exact changed fields before/after, including metadata-only changes. Both inventories preserve the full resolved and authoritative objects. `accounting.json` supplies exact cross-counts.','',
'## 5. Difficulty accounting','',
'| Canonical difficulty | Before / after | Content revised |','|---|---:|---:|']
for k,n in b['difficulty'].items():lines.append(f'| {k} | {n} | {accounting["contentRevisionsByDifficulty"].get(k,0)} |')
lines+=['','The seven unknown canonical difficulties are existing auxiliary records. Source difficulty, canonical difficulty, pool placement and order are all unchanged. Easy and Medium content is retained. Fifteen existing Hard records now offer better decision/graph/calculation reasoning; ten Elite and 23 Legendary records have targeted improvements.','',
'## 6. Type and pool accounting','',
'| Canonical type | Before / after | Content revised |','|---|---:|---:|']
for k,n in b['types'].items():lines.append(f'| {k} | {n} | {accounting["contentRevisionsByType"].get(k,0)} |')
lines+=['','| Composed pool | Before / after |','|---|---:|']
for k in ['easy','medium','hard','elite','legendary','easyBoss','mediumBoss','finalBoss','legendaryBoss','repair','repairSeed','bridge','calculation','integration','challengeTotal']:lines.append(f'| {k} | {b["composedCounts"][k]} |')
lines+=['','The 325 ordinary records plus 16 regular checkpoints, six Legendary checkpoints, eight repairs and seven bridges total 362. Canonical difficulty counts include auxiliary/checkpoint records, so they differ from ordinary bank counts. Source boss pools are mapped by the existing Composer into easyBoss/mediumBoss/finalBoss. All memberships and ordering match BEFORE.','',
'There is no separate calculation pool and no source-to-Hard calculation merge in this preset. Numerical reasoning is embedded in ordinary/checkpoint records, including nine calculation-type and 48 graph-calculation-type records. There are 26 integration-type and 33 graph-integration-type records, but no separate integration/challenge pool. Empty specialized containers are reported accurately and were not filled to manufacture coverage.','',
'## 7. Objective-by-objective findings and actions','',
'A = coverage; B = robustness; C = calibration; D = calculation/integration; E = graph use; F = upper-tier synthesis; G = no material gap. The table reproduces the pre-authoring assessment and exact revision count for each selected objective/view.','',
'| View / objective | Count | Before categories | Revised | Finding |','|---|---:|---|---:|---|']
for o in obj:
 n=sum(x['concept']==o['concept'] and x['objective']==o['objective'] for x in content);lines.append(f'| {o["concept"]} / {o["objective"]} | {o["count"]} | {", ".join(o["categories"])} | {n} | {o["findings"]} |')
lines+=['','Some inherited objective labels are broader or differently organized than individual graph skills: for example 42192 has objective PGCR.4 (Rivalry) and primarySkill individual_mb_calculation. Those existing labels and commonError fields were preserved as requested; the question still uses shared-quantity benefit evidence. The findings use actual records and skills rather than treating each objective title as an exhaustive content dictionary.','',
'## 8. True coverage gaps','',
'No whole selected objective is absent. The bank already contains all four externality sign/channel combinations, private/social intersections, tax/subsidy logic, cap/trade distinctions, ideal Coase assumptions, public-good aggregation and context-sensitive goods classification. No new question or image was necessary. Absent advanced topics listed in section 3 are scope boundaries. Market Power is intentionally a small supporting view, not a complete market-structure course.','',
'## 9. Robustness findings','',
'Many variants share “identify the curve / read the quantity / state the rule” grammar. The revisions add mechanisms, feasible alternatives and independent constraints: pivotal contributions, payment intervals, enforcement probability, limited low-cost abatement, sponsorship versus exclusion, and alternative real transaction costs. Three sound Hard welfare items (42026, 42036, 42056) retain their stems and keys but replace implausibly different-unit distractors with genuine rectangle/revenue misconceptions.','',
'## 10. Hard calibration','',
'Hard was uneven rather than empty of exam reasoning. Existing graph loss calculations and context-dependent incentives were worth retaining. Revised P52B-MFAIL-H-001 computes private and social gains from a proposed trade; 42122 tests expected enforcement; 42130 selects the actual tax base; 42140 allocates abatement; 42256 tests a pivotal funding decision; 42288 distinguishes private and social congestion costs; P52B-MFAIL-H-003 identifies forgone mutually beneficial trade under market power. None was moved between tiers.','',
'## 11. Graph and integration findings','',
'Graph coverage is already substantial: 147 linked records and 18 approved assets. No missing graph family was established. Selected single-lookups now become policy choices, counterfactual intersections, surplus comparisons and fiscal accounts. The revised 42100 distinguishes the $20 thousand additional welfare gain from the $240 thousand increase in tax revenue. The revised public-good checkpoints distinguish summed willingness to pay, real funding costs and welfare areas. No graph is required for the new institutional prose cases. Existing graph references and eligibility are preserved.','',
'## 12. Upper-tier synthesis','',
'Elite now includes buyer/seller burden versus statutory payment (42066), subsidy budget and prices (42084), a partially corrected private intersection (42096), permit opportunity cost (42141), a contract payment interval (42149), changed cost/beneficiary information (42186/42196), and crowding/internal access institutions (42217/42249).','',
'Legendary now compares common targets under subsidies versus bargains (42086/42095), endogenous revenue and remaining loss (42100), scarce abatement opportunities (42147), benefit capture and costly coordination (42151), alternative contract surpluses (42153), feasible regulation versus bargaining (42159), funding institutions, capacity limits and current access versus future innovation. These are linked choices and inferences, not merely larger arithmetic. The bank still contains some direct high-tier items; this audit is targeted rather than an assertion of uniform mastery-level demand.','',
'## 13. Intentionally unchanged','',
'Retained Easy/Medium stems, keys and feedback; EXT.1 foundational distinctions; strong existing welfare and marginal comparisons; repair/bridge content and routes; PGCR.9 introductory rights/enforcement breadth; 25 unselected parent records; all 148 other concept definitions; every graph’s bytes; source aliases and occurrences; engine/UI, telemetry, classroom access and Worker code. Correct detailed PUBLIC-01/03/04/05 metadata was retained. PUBLIC-02’s detailed description was retained while its alt text was corrected. No external legal doctrine or publisher question was added.','',
'## 14. Existing Hard examples retained','',
'- 42046: derive the $125 omitted-surplus triangle from the gardens graph.\n- 42116: distinguish MPB from MSB when consumption harms outsiders.\n- 42063/42072/42081/42090: connect corrective wedges with post-policy quantity to calculate revenue or expenditure.\n- 42162: evaluate an additional siren from the graph’s marginal benefit and cost.\n- 42197/42207: interpret common quantity and vertical benefit summation.\n- 42245/42250: distinguish congestion-dependent rivalry from nonrival streaming and scarce physical uses.\n- 42304/42306: apply enforceable rights to future stock incentives and groundwater access.','',
'These retain useful ordinary exam mechanisms; they are not all equally demanding. Some remaining Hard recognition records still merit future calibration review.','',
'## 15. Specific revisions and economics','',
'42047 and 42057 correct the idea that a maximum quantity alone induces underprovided output. 42149 and 42153 separate the polluter’s reservation payment from victims’ payment ceiling after real contract costs. 42095 and 42159 compare feasible institutions rather than assuming private bargaining or government policy is universally best. 42274 separates a provider’s financial viability from social benefit; 42285 distinguishes commons overuse from public-good underfunding. The two Market Power Legendary items preserve the selected introductory natural-monopoly and innovation examples while evaluating financing or future incentives. Every exact change and reason is recorded in `changes.json`.','',
'## 16. Numerical, logical and answer-key findings','',
'No incorrect baseline numerical key was established in the reviewed selected graph calculations. The concrete economic defect was the positive-externality quantity-limit wording in two Hard records. Existing DWL distractors in three records had implausible units. Revised permit-cap calculation 42147 explicitly states unregulated emissions and available abatement capacity, removing reliance on an unstated baseline.','',
'All 36 revised numerical or quantitatively evidenced items were independently recomputed from final inputs and visually reconstructed graph endpoints with exact Fraction arithmetic. This includes graph quantities/prices, welfare integrals, tax/subsidy totals, enforcement thresholds, feasible permit allocation, contract intervals, public-good aggregation and funding choices. Final rounding does not rely on hidden source precision. All 48 final option sets were reviewed for one economically correct response; all 362 records pass the separate hash/choice structural check. `numerical-validation.json` and `logical-validation.json` explain the results.','',
'## 17. Accessibility findings','',
'All 18 images were visually inspected and decoded. EXTERNALITY-A descriptions omitted horizontal endpoint coordinates needed to reconstruct the plotted lines. EXTERNALITY-B/D text revealed “socially efficient” outcomes even though the dots carried no such labels. C alt text named optimal policy and its description assigned buyer/seller roles to an unlabeled bracket. PUBLIC-02 alt text named efficient provision.','',
'Corrected descriptions retain visible MPB/MPC/MSB/MSC labels, line geometry, exact coordinates, colored dots, dashed guides and bracket endpoints. They leave the economic inference to the learner. No visually unlabeled curve was renamed by inference; no image bytes changed. Fourteen asset registrations, global/manifest counterparts and 116 question-level copies were synchronized. Thirteen long descriptions and 14 alt texts changed. The 102 metadata-only question records are counted separately from content revisions. Runtime tests verify the new descriptions are actually displayed.','',
'## 18. Mode readiness and review routes','',
'All ten modes retain readiness: Standard Campaign, Timed Trial, Exam Drill, Quiz, Unlimited Practice, Legendary Mode, Score Attack, Trial by Graph, Fading Fortune and Risk & Reward. Trial by Graph has 133 eligible questions: 18 Easy, 45 Medium, 45 Hard, 21 Elite and four Legendary. Fading Fortune and Risk & Reward each retain 325. Readiness and eligibility match BEFORE exactly.','',
'Selected Concept Review routes remain Externalities → MICRO-54, Public Goods and Common Resources → MICRO-55, Market Power → MICRO-56. Their local PDF bytes match registered hashes. The runtime index and evidence/bundle routes are unchanged, with zero selected-resolution errors. Existing global review diagnostics (including unrelated MICRO-03 and integrated-economic-analysis metadata warnings) persist unchanged. Retest/checkpoint behavior uses the unchanged engine/template; content-level repair/bridge maps and boss coverage are exact matches.','',
'## 19. Structural and runtime integrity','',
'Every scoped record has four normalized distinct options, exactly one answer-hash match, a nonempty stem and feedback, and valid asset references/descriptions where applicable. Revised stems are unique across the entire current library. IDs, aliases, source hashes/occurrences, difficulties, objectives, tags, skills, commonError metadata, pool memberships and order remain unchanged apart from allowed content/accessibility fields. The 25 unselected parent records are exact matches.','',
f'The focused Microsoft Edge smoke test verifies all {browser["revisedRecordsVerified"]} changed record payloads, including metadata-only updates, and all 147 graph displays and click-to-enlarge views. The real question renderer shows revised Legendary question 42100 in `browser-smoke.png`. No JavaScript page errors occurred. External requests were blocked. This is a content/runtime smoke test, not an all-mode playthrough or a new production deployment.','',
'Only three production files need synchronization: `data/composer_library.js`, `data/composer_registry.json`, and `data/composer_library_manifest.json`. Shared semantic hashes agree; registry/manifest changes are limited to that hash and relevant asset metadata. `architecture-validation.json` records protected-file and review checks.','',
'## 20. Remaining limitations and quality warnings','',
f'The existing quality auditor reports **{qb["counts"]["errors"]} → {qa["counts"]["errors"]} errors, {qb["counts"]["warnings"]} → {qa["counts"]["warnings"]} warnings, and {qb["counts"]["reviews"]} → {qa["counts"]["reviews"]} review flags**. Both runs cover all 362 resolved questions. Running against raw derived definitions returns zero records, so an explicitly documented audit-only projection uses the current resolver’s selected question objects. It is not a production change or a claim that zero raw findings demonstrate quality.','',
'Remaining final rules: '+', '.join(f'{x["rule"]} ({x["count"]})' for x in qa['ruleCounts'])+'. Each baseline and newly appearing question/rule pair has a disposition in `quality-dispositions.json`. Weak-absolute flags increased because some revised alternatives explicitly express the relevant “only,” “all” or “must” misconceptions; this is reported rather than hidden. Some retained feedback repeats, some correct options are longer, graph cue wording is inconsistent, and direct high-tier questions remain.','',
'No claim is made of equal skill frequency in every tier, exhaustive web-wide originality comparison, all-mode gameplay, screen-reader user testing or empirical item-difficulty validation. Source type/objective/skill labels remain historically uneven; they were not silently normalized. Broad inherited fallback route keys and the small market-power pool remain deliberate architecture boundaries. The audit improves representative weak areas while preserving the mature bank’s functioning parts.','',
'## 21. Final semantic library hash and deliverables','',
'Final semantic SHA-256: `'+v['newLibrarySha256']+'`.','',
'Artifacts are saved under `validation_artifacts/market_failures_advanced_micro_assessment_audit_2026_09_08/`. `inventory-before.json`, `inventory-after.json`, `objective-findings-before.json`, `scope-boundary.json`, `changes.json`, `record-actions.json`, `accounting.json`, and the independent validators provide the complete audit trail. The full private working library copies and generated executable HTML are excluded from delivery. Production edits remain local for inspection.','']
(W/'FINAL_REPORT.md').write_text('\n'.join(lines),'utf8')
files=['BEFORE.md','AUDIT_FINDINGS_BEFORE.md','FINAL_REPORT.md','inventory-before.json','inventory-after.json','objective-findings-before.json','scope-boundary.json','summary-before.json','concepts.json','sources.json','recipe.json','changes.json','record-actions.json','accounting.json','numerical-validation.json','logical-validation.json','graph-validation.json','originality-validation.json','semantic-validation.json','architecture-validation.json','quality-before.json','quality-before.md','quality-after.json','quality-after.md','quality-dispositions.json','audit-projection-provenance.json','accessibility-inspection.json','accessibility-spec.json','asset-accessibility-changes.json','validation.json','browser-validation.json','browser-smoke.png','inspect.cjs','prepare.cjs','findings.py','revisions.py','revisions.json','accessibility.py','stage.mjs','verify.py','browser.cjs','finish.py']
write('deliverables.json',files)
script=(W.parent/'.trade-work/apply.ps1').read_text('utf8').replace('$trade','$failures').replace('.trade-work','.failures-work').replace('trade_welfare_assessment_audit_2026_09_07','market_failures_advanced_micro_assessment_audit_2026_09_08').replace('27 audit artifacts',str(len(files))+' audit artifacts');(W/'apply.ps1').write_text(script,'utf8')
print(json.dumps(dict(artifacts=len(files),qualityBefore=qb['counts'],qualityAfter=qa['counts'],accounting=accounting,reportWords=len(' '.join(lines).split()))))
