import json,re,hashlib,unicodedata
from pathlib import Path
W=Path(__file__).resolve().parent;inv=json.loads((W/'inventory-before.json').read_text());qs=inv['records'];S={}
def norm(x):return ' '.join(unicodedata.normalize('NFKC',x).lower().split())
def key(q):return next(o for o in q['options'] if hashlib.sha256(norm(o).encode()).hexdigest()==q['aHash'])
def put(id,q,options,feedback,reason,proof=None):
 assert id in qs and len(options)==4 and len(set(map(norm,options)))==4
 S[id]=dict(q=q,options=options,feedback=feedback,reason=reason,proof=proof or [])
def edit(id,q=None,feedback=None):
 old=qs[id];put(id,q or old['q'],[key(old)]+[o for o in old['options'] if o!=key(old)],feedback or old['feedback'],'Correct incomplete/ambiguous wording or graph evidence while preserving the assessed skill.')
def money(x):return '$'+format(abs(x),',.2f')
# Standalone profit questions: restore all inputs, state total cost explicitly, and remove hidden precision.
# Source predecessor is used only to recover the bank's own scenario, never the exam.
for id,old in qs.items():
 if not (id.startswith(('P62G-MON-LB-','P62H-MCMP-LB-','P62H-MCMP-L-')) and 'chosen output' in old['q']):continue
 prev=qs[id[:-3]+f'{int(id[-3:])-1:03d}']['q']
 a,b,c,d=map(float,re.search(r'P=(\d+(?:\.\d+)?)−(\d+(?:\.\d+)?)Q.*MC=(\d+(?:\.\d+)?)\+(\d+(?:\.\d+)?)Q',prev).groups())
 Q=(a-c)/(2*b+d);P=a-b*Q
 fmatch=re.search(r'fixed cost \$([\d,]+)',prev)
 F=float(fmatch[1].replace(',','')) if fmatch else round((float(re.search(r'ATC(?: is |=)\$([\d.]+)',old['q'])[1])-c-d*Q/2)*Q)
 profit=(a-c)*Q-(b+d/2)*Q*Q-F;vc=c*Q+d*Q*Q/2
 name=prev.split(' faces ')[0]
 s=f'{name} faces P = {a:g} - {b:g}Q, MR = {a:g} - {2*b:g}Q, and total cost TC = {F:g} + {c:g}Q + {d/2:g}Q². Fixed cost is unavoidable this period. After choosing output, which operating result follows? Keep full precision until rounding profit or loss to cents.'
 adj='; positive profit creates entry pressure' if id.startswith('P62H') else ''
 correct=f'Produce about {Q:.2f} units with an economic '+('profit' if profit>=0 else 'loss')+f' of {money(profit)}'+adj
 options=[correct,f'Shut down and incur the fixed-cost loss of {money(F)}',f'Produce about {Q:.2f} units and count {money(P*Q-vc)} as economic profit',f'Produce about {Q:.2f} units and count revenue of {money(P*Q)} as economic profit']
 fb=f'MR = MC gives Q = {Q:.6f}; demand gives P = {P:.6f}. Revenue minus the stated total cost is {profit:.6f}, so the rounded economic '+('profit' if profit>=0 else 'loss')+f' is {money(profit)}. Revenue covers variable cost; operating contributes {money(P*Q-vc)} toward fixed cost.'+(' With free entry, positive economic profit attracts rivals; it is not a long-run guarantee.' if id.startswith('P62H') else '')
 put(id,s,options,fb,'D: Restore missing standalone demand, output and cost evidence in a randomly routed profit item; recompute from explicit total cost.')
# Hard profit applications: manageable full data, balanced misconception choices.
hardcases=[('Seabrook Repair',48,39,31),('Cairn Tailoring',36,56,42),('Grove Pottery',65,28,24),('Willow Tours',28,75,54),('Ember Design',42,63,38),('North Quay Roasting',55,34,29)]
for n,(name,Q,P,A) in enumerate(hardcases):
 id=f'P62H-MCMP-H-{2*n+2:03d}';pi=(P-A)*Q
 put(id,f'{name} sells a differentiated service. Its MR and rising MC intersect at {Q} units; demand at that quantity gives a price of ${P}, and ATC is ${A}. What are its profit margin and total economic profit?',
 [f'${P-A} per unit; ${pi} total',f'${P-A} per unit; ${P*Q} total',f'${P} per unit; ${P*Q} total',f'${A} per unit; ${A*Q} total'],f'Use the MR = MC quantity, obtain price from demand, and subtract ATC: {P} - {A} = {P-A} per unit. Multiplying by {Q} gives ${pi}; revenue and total cost are not profit.','D: Supply the missing quantity and connect output, margin and profit at normal exam demand.')
# Fix cents computed from inaccessible unrounded source values in the calculation pool.
for num in range(13,20):
 id=f'P62H-MCMP-C-{num:03d}';old=qs[id]; vals=list(map(float,re.findall(r'\d+(?:\.\d+)?',old['q'])));Q,P,A=vals[:3];pi=(P-A)*Q
 put(id,old['q']+' Use the displayed values and round to the nearest cent.',
 [money(pi),money(abs(P-A)),money(P*Q),money(A*Q)],f'Total '+('loss' if pi<0 else 'profit')+f' is the absolute price–ATC gap times output: |{P} - {A}| × {Q} = {money(pi)}. The keyed amount uses only the displayed data.','D: Align cent-level key with displayed inputs rather than hidden source precision.')
put('P62E-COP-H-023','A bicycle-fitting workshop bills clients $168,000 for the year. It pays $54,000 to employees, $27,000 for supplies and $15,000 for utilities and insurance. The proprietor gives up an outside salary of $46,000 and could rent the workshop she owns for $18,000 a year. What are accounting profit and economic profit?',
 ['$72,000 accounting profit; $8,000 economic profit','$72,000 accounting profit; $26,000 economic profit','$90,000 accounting profit; $8,000 economic profit','$8,000 accounting profit; $72,000 economic profit'],
 'Explicit payments total $96,000, leaving accounting profit of $72,000. Forgone salary and rent total $64,000 in implicit costs, leaving $8,000 economic profit. Owning the workshop does not make its alternative rental use free.','C,D: Hard must classify realistic explicit and implicit costs before calculating both profit measures.')
put('PMC-COP-H-019','A repair cooperative receives $144,000 from maintenance contracts and $36,000 from parts sales. It pays $98,000 in wages and parts purchases plus $22,000 in rent and other bills. Its owner forgoes a $48,000 job and $9,000 of investment income. Which profit assessment is correct?',
 ['$60,000 accounting profit and $3,000 economic profit','$60,000 accounting profit and $12,000 economic profit','$82,000 accounting profit and $25,000 economic profit','$3,000 accounting profit and a $54,000 economic loss'],
 'Total revenue is $180,000 and explicit costs are $120,000. Accounting profit is $60,000; subtract the $57,000 return available from the owner’s next-best alternatives to obtain $3,000 economic profit.','C,D: Strengthen an existing economic-profit subtraction with classification and multiple revenue sources.')
put('P62E-COP-EL-002','A proprietor initially earns $84,000 in accounting profit, exactly covering a $60,000 outside salary and $24,000 of forgone rent. Next year accounting profit rises by $6,000 while the outside salary falls by $6,000; forgone rent is unchanged. Which assessment follows?',
 ['Economic profit becomes $12,000 because accounting profit rises while implicit cost falls','Economic profit stays zero because the two changes offset','Economic profit becomes $6,000 because only the accounting change matters','Economic profit becomes a $12,000 loss because outside earnings fall'],
 'Initially implicit costs are $84,000. They fall to $78,000 while accounting profit rises to $90,000; economic profit is $12,000. These changes reinforce each other, rather than offsetting. Normal profit is the return required to cover the owner’s alternatives.','Logical defect: The original statement reversed the sign of changing implicit cost.')
edit('P62E-COP-H-044','Refer to the graph. At the MP–AP crossing, MP changes from above AP to below AP. What does this imply about average product?')
S['P62E-COP-H-044']['options']=['AP reaches a local maximum there','AP reaches zero there','AP begins rising after the crossing','AP equals total product there']
edit('P62E-COP-H-046','Refer to the LRAC graph. If the firm expands all adjustable inputs to raise output from about 60 toward 90 units, what happens to LRAC?')
put('P62E-COP-EL-003','A ceramics firm can change staffing now but must use its current kiln until the lease expires. At renewal it can select a larger kiln. Which comparison correctly separates today’s output choice from the renewal decision?',
 ['Today labor varies around a fixed kiln; at renewal both kiln capacity and labor can be chosen','Today both inputs are fixed; at renewal only labor can be chosen','The kiln is variable today because its payment appears in total cost','The current lease payment remains a sunk cost for every future kiln choice'],
 'The short run is defined by a fixed input, not a fixed number of months. Staffing can vary today around the existing kiln. At renewal the firm can change capacity as well as staffing; a future lease payment is not the same as an unrecoverable past payment.','F: Replace time-horizon label lookup with input and planning inference.')
put('P62E-COP-L-068','A packaging plant must pay its current $24,000 lease whether it operates or closes. Next year it can renew at $24,000 or lease a larger plant for $42,000. At the planned output of 9,000 units, variable cost would be $8 per unit in the old plant or $5 in the larger plant. Which decision correctly treats the time horizon?',
 ['The current lease is unavoidable; next year the larger plant costs $9,000 less in total','The current lease is avoidable; next year the old plant costs $18,000 less in total','The current lease is sunk, so exclude both possible lease payments next year','The larger plant is cheaper at every output because its variable cost is lower'],
 'The current commitment does not disappear with shutdown. Next year total cost is $24,000 + $8 × 9,000 = $96,000 in the old plant and $42,000 + $5 × 9,000 = $87,000 in the larger one. Future capacity costs are avoidable choices. The larger plant saves $9,000 at this output, not at every output.','F: Integrate fixed/avoidable commitments, long-run input choice and plant costs.')
put('P62E-COP-L-080','A bottler can renew a compact plant with annual cost TC = 18000 + 9Q or lease an automated plant with TC = 42000 + 5Q. Both can supply either forecast: 4,000 or 8,000 units. Which long-run plan minimizes cost across those forecasts?',
 ['Use the compact plant at 4,000 and the automated plant at 8,000; the switch occurs at 6,000 units','Use the automated plant at both forecasts because its variable cost is lower','Use the compact plant at both forecasts because its fixed cost is lower','Use the compact plant at 8,000 and the automated plant at 4,000; the switch occurs at 6,000 units'],
 'Set the two total costs equal: $24,000 = $4Q, so the crossover is 6,000. At 4,000 units costs are $54,000 versus $62,000; at 8,000 they are $90,000 versus $82,000. Long-run planning selects the lower attainable cost at each output; this comparison does not infer diminishing marginal returns.','F: Make the envelope concept require comparison of actual plant alternatives.')
put('P62F-PC-H-015','A competitive market starts with each firm covering all economic costs. A rise in buyer demand raises market price before any entry, while existing firms’ cost curves remain fixed. Which immediate firm response follows on the rising-MC operating range?',
 ['Its horizontal MR line rises, it expands output along MC, and economic profit increases','Its MC shifts down, so it can expand while its MR line stays fixed','Its horizontal MR line falls because more buyers enter the market','Its output stays fixed because a price taker cannot respond to price'],
 'Market demand raises the equilibrium price. The firm takes that price as P = MR, so the higher horizontal line intersects rising MC at more output. With unchanged costs and initial zero profit, it can earn positive short-run profit before entry responds.','D: Connect market demand to firm price, output and profit without adding the upper-tier adjustment chain.')
put('PM5-PC-H-065','A competitive industry has 40 identical firms. At a price of $25, each initially supplies 12 units. Higher energy costs reduce each firm’s supply at that price to 9 units. With unchanged market demand and no entry, equilibrium price then rises to $28. At its new MR = MC quantity of 10 units, a firm has ATC $30 and AVC $21. Which assessment is correct?',
 ['Market supply shifted left; the firm operates with a $20 economic loss','Market supply shifted right; the firm earns $70 economic profit','Market supply shifted left; the firm shuts down because P is below ATC','Market supply stayed fixed; the firm earns $30 economic profit'],
 'At the original price, industry supply falls from 480 to 360 units, identifying a leftward shift. At the new optimum, profit is (28 - 30) × 10 = -$20; price still exceeds AVC, so the firm operates. A cost shock can raise market price while reducing profit; the profit result requires the stated cost comparison.','D: Link an input-cost supply shock to the representative firm with enough data to avoid a false universal profit claim.')
put('P62F-PC-H-035','Refer to the competitive-firm graph. Use P = MR and rising MC to select output, then compare price with ATC and AVC. Which operating result follows?',
 ['Produce 30 units with a $300 loss; revenue covers variable cost','Produce 30 units with a $300 profit; price exceeds AVC','Shut down because ATC exceeds price at the intersection','Produce 40 units because MC then intersects ATC'],
 'The horizontal $30 price line meets rising MC at Q = 30. ATC is $40 and AVC is $20 there. Profit is (30 - 40) × 30 = -$300, but price covers AVC, so operating limits the short-run loss.','E: Use the approved loss graph for quantity, accounting and shutdown distinctions together.')
put('P62F-PC-EL-038','Refer to the paired market and firm graph. The displayed firm earns positive profit. Under free entry, identical firms, and unchanged input prices and cost curves, which sequence moves this industry toward long-run equilibrium?',
 ['Entry shifts market supply right; price and each firm’s horizontal MR fall; firm output falls along rising MC until P = minimum ATC','Entry shifts market demand left; price and firm output fall until P = minimum AVC','Each firm cuts its own price first; market supply then shifts left until MR becomes downward sloping','Positive profit attracts entry; every firm keeps its original output and price while industry output rises'],
 'At the displayed Q = 90, price is $40 and ATC is $20, so profit attracts entry. Entry adds market supply. The lower market price lowers each firm’s horizontal MR line; with fixed cost curves its best output falls along rising MC. Under the stated benchmark assumptions entry ends at zero economic profit, P = MC = minimum ATC.','F: Replace a single output-direction step with the complete competitive adjustment mechanism.')
put('P62F-PC-L-056','A constant-cost competitive industry begins in long-run equilibrium. A permanent demand increase creates temporary profits. Later, price has returned to its old level, each identical surviving firm again produces its old quantity, and market sales are higher. Which history explains all three observations?',
 ['Demand first raised price and firm output; profit induced entry; added supply lowered firm MR and output until zero profit returned with more firms','Demand first raised price; incumbent firms then kept increasing their own output until their individual MR curves sloped downward','Entry first raised costs; higher costs then reduced firm output while preserving positive economic profit','Demand increased, but each firm’s horizontal MR stayed fixed throughout because firms take price as given'],
 'The demand shock raises price, MR and each incumbent’s output initially. Profit attracts new firms, shifting industry supply right. Unchanged input prices keep firm cost curves fixed, so price returns to minimum ATC and each firm returns to its original output. Higher final market output is supplied by more firms, with zero economic profit.','F: Reverse-infer the full short-run to long-run chain from observed firm and market outcomes.')
put('P62F-PC-L-065','Refer to the loss-making firm graph. Assume all firms are initially identical, fixed costs cannot be avoided this period, and input prices and cost curves stay unchanged as firms leave. Which sequence correctly separates present operation from eventual adjustment?',
 ['The firm operates because P exceeds AVC; persistent losses induce exit; market supply falls and survivors’ MR and output rise until losses disappear','The firm shuts down solely because P is below ATC; shutdown immediately removes all fixed costs and eliminates losses','Losses induce entry; market supply rises and each survivor’s horizontal MR rises until zero profit','Survivors raise their own selling prices first; their downward-sloping demand curves then shift right'],
 'The displayed price lies between AVC and ATC, so production covers variable cost and some unavoidable fixed cost. Persistent economic losses discourage renewal and induce exit. Reduced market supply raises price and each survivor’s horizontal MR; output rises along unchanged rising MC until the standard long-run zero-profit condition is restored.','F: Integrate loss-but-produce, exit, market supply and surviving-firm adjustment.')
put('P62G-MON-H-013','A single-price seller of specialty filters faces P = 84 - 2Q and MR = 84 - 4Q, with constant MC = $20. At its optimal output, ATC is $32. Which quantity, price and economic profit are consistent?',
 ['16 units, $52 price, $320 profit','32 units, $20 price, $384 loss','16 units, $20 price, $192 loss','16 units, $52 price, $512 profit'],
 'MR = MC gives 84 - 4Q = 20, so Q = 16. Demand then gives P = $52. The profit margin is 52 - 32 = $20; multiplying by 16 gives $320. The $512 distractor uses P - MC instead of P - ATC.','C,D: Replace unused-number rule recitation with a short complete monopoly calculation.')
put('P62G-MON-H-035','Refer to the monopoly graph. Find output at MR = MC, read price from demand and ATC at that output. What total economic result does the graph show?',
 ['40 units at $40, with a $200 economic loss','40 units at $20, with a $1,000 economic loss','About 67 units at $27, with zero economic profit','40 units at $40, with an $800 economic profit'],
 'MR intersects MC at Q = 40. The demand price is $40, while ATC is $45. Economic profit is (40 - 45) × 40 = -$200. The graph has no AVC curve, so it does not by itself establish the shutdown comparison.','E: Link monopoly output, demand price, average cost and total loss without inferring unavailable AVC.')
edit('P62G-MON-H-040','Refer to the graph. At the unregulated monopoly output where MR equals MC, how large is price minus marginal cost?')
edit('P62G-MON-H-005','Refer to the graph. The demand price P1 currently lies above ATC at Q1. Suppose a higher fixed cost raises ATC exactly to P1 without changing demand, MR or MC. The monopoly would then earn:','The higher fixed cost raises ATC without moving the MR = MC output or demand price. When ATC reaches P1 at Q1, revenue covers all economic costs and economic profit becomes zero. The original plotted curves need not already show tangency.')
put('P62G-MON-H-030','An aquarium offers a verified local-resident ticket and a higher-priced tourist ticket. Both admit buyers to the same exhibit at the same marginal cost, and tickets cannot be transferred. Which classification and pricing rationale fit?',
 ['Third-degree discrimination: identifiable groups can face different markups when their demand elasticities differ','First-degree discrimination: each visitor is charged their own exact willingness to pay','Cost-based pricing: the higher tourist ticket proves higher marginal cost','Uniform monopoly pricing: resale restrictions force both groups to pay one price'],
 'The seller separates observable groups rather than setting a unique price for every visitor. With equal marginal cost and enforceable separation, less elastic demand can support the larger markup. The ticket difference alone does not demonstrate a cost difference.','B,C: Apply the already-selected third-degree classification and elasticity mechanism in Hard.')
put('P62G-MON-L-063','A water network has demand P = 90 - Q, MR = 90 - 2Q, constant MC = $10 and fixed cost $800. ATC therefore equals 10 + 800/Q. A regulator compares unregulated pricing, P = MC, and the higher-output P = ATC solution (about Q = 68.28). Which assessment is correct?',
 ['Unregulated profit is $800; MC pricing needs an $800 subsidy; AC pricing covers cost but leaves P above MC','Unregulated profit is $1,600; MC pricing needs no subsidy; AC pricing achieves the efficient output','Unregulated profit is $800; MC pricing needs an $800 subsidy; AC pricing leaves the same output as monopoly','Unregulated profit is zero; MC pricing needs an $800 subsidy; AC pricing produces more than the efficient quantity'],
 'MR = MC gives Q = 40 and P = $50: profit is (50 - 10) × 40 - 800 = $800. MC pricing gives Q = 80 and covers only variable cost, leaving an $800 financing gap. Higher-output AC pricing gives Q about 68.28 and P about $21.72: zero profit, but P > MC and fewer trades than under MC pricing.','F: Compare all three regulatory rules, financing and efficiency in one self-contained item.')
put('P62G-MON-L-066','A district-heating network is regulated at P = ATC and earns zero economic profit. Its ATC is declining over the relevant range and exceeds MC. Officials propose P = MC with a subsidy equal to the resulting accounting shortfall in economic costs. Which appraisal best addresses the regulatory dilemma?',
 ['The rule can expand mutually beneficial service, but public financing and weak cost-control incentives under automatic cost reimbursement must be assessed','The rule necessarily covers all total costs because MC includes the average fixed infrastructure cost','The rule must reduce service because lowering price moves buyers up the demand curve','The rule is unnecessary because zero economic profit proves the original allocation maximizes total surplus'],
 'Cost-covering P = ATC leaves price above MC, excluding some positive-surplus uses. Setting P = MC can recover those uses but, with ATC > MC, leaves a cost-recovery gap. Funding that gap and designing incentives to control cost are part of the policy comparison; zero profit alone is not an efficiency test.','F: Evaluate efficiency, financial viability and the cost-incentive consequences of regulation.')
put('P62G-MON-L-096','Refer to the natural-monopoly regulation graph. Officials require the highest displayed output that covers total economic cost without a subsidy. Which rule meets that constraint, and what would change if they instead required the displayed P = MC outcome?',
 ['Choose fair-return pricing near 116 units; MC pricing adds about 24 units but needs about $700 of support','Choose unregulated output near 70 units; MC pricing adds about 46 units and needs no support','Choose MC pricing at 140 units; it already covers ATC because P equals MC','Choose fair-return pricing near 116 units; MC pricing removes 24 units and earns about $700 profit'],
 'At the higher-output demand–ATC intersection, about Q = 116 and P = $16, revenue covers economic cost. MC pricing sets P = $10 at Q = 140, where ATC is about $15. The additional 24 units leave a (15 - 10) × 140 = $700 loss to finance. The constraint selects cost recovery rather than full allocative efficiency.','F,E: Use the approved regulatory graph for a constrained choice and subsidy calculation.')
put('P62H-MCMP-L-095','Refer to the long-run monopolistic-competition graph. A proposal would force each firm to produce at minimum ATC while also pricing at MC. Which assessment uses the diagram and recognizes what it cannot establish about welfare?',
 ['The current markup is $11.50 and excess capacity is 14 units; policy evaluation must also weigh lost variety and cost recovery, which the firm diagram does not measure','The current $11.50 markup is economic profit, so eliminating it necessarily leaves every variety financially viable','Current zero profit proves efficient output, so neither the markup nor product variety belongs in welfare analysis','Excess capacity is 14 units of unsold inventory, so ordering its sale necessarily raises total consumer welfare'],
 'At Q = 36, P = ATC = $27 while MC = $15.50, giving an $11.50 markup. Minimum ATC occurs at Q = 50, so excess capacity is 14 units, not inventory. Producing more at a mandated price is not automatically feasible at zero profit. Buyers may value differentiation; the diagram alone cannot quantify the benefits of variety or the policy’s net welfare effect.','F: Integrate graphic markup/excess capacity with the course’s variety-versus-efficiency tradeoff.')
put('P62H-MCMP-EL-037','Refer to the displayed long-run firm graph. A policymaker argues that because entry has eliminated economic profit, consumers cannot gain from additional mutually beneficial trades. Which response is economically sound?',
 ['P = ATC establishes zero profit, but P > MC still signals a markup; a policy must also consider differentiated-product benefits and cost recovery','P = ATC proves P = MC, so the policymaker’s inference is sound','The firm must earn positive economic profit because output is below minimum ATC','Free entry makes the firm a price taker, so the plotted downward-sloping demand is irrelevant'],
 'The graph combines P = ATC with P > MC and output below efficient scale. Entry removes profit without eliminating markup. The markup identifies a potential allocative issue, but the graph does not quantify the value of variety or the costs of a proposed remedy.','F: Require evaluation of a flawed welfare inference instead of listing model characteristics.')
# HHI requires individual firm shares, not an unspecified fringe aggregate.
for n in range(5,9):
 id=f'P62I-OLI-H-{n:03d}';old=qs[id];edit(id,f'Refer to the market-share chart for market {n}. For this calculation, assume the bar labeled Other represents one additional firm, not several small firms. What is the HHI?','Square each individual firm’s percentage share and add. Treating Other as one firm is necessary here; if it were an unspecified collection of smaller firms, its internal shares would be needed for an exact HHI.')
# Matrix defects and synthesis: independent validator transcribes the displayed cells separately.
matrix_cases={
'P62I-OLI-L-001':('B/Y is the only pure equilibrium with total 10; A/X maximizes joint profit at 16','A/X is the only pure equilibrium with total 16; B/Y maximizes joint profit at 10','B/Y is the only pure equilibrium with total 10; A/Y maximizes joint profit at 14','A/X and B/Y are both pure equilibria and both have total 16'),
'P62I-OLI-L-004':('A/X and B/Y are pure equilibria; A/X has the larger joint total, 23 versus 21','B/Y is the only pure equilibrium because Column prefers its payoff there','A/X is the only pure equilibrium because it has the largest joint total','Neither diagonal cell is an equilibrium because the off-diagonal totals are lower'),
'P62I-OLI-L-010':('There is no pure-strategy equilibrium; all four cells tie at a joint total of 8','There are four pure-strategy equilibria because all four joint totals equal 8','A/X is the unique equilibrium because Row receives 6 there','B/Y is the joint optimum because Column receives 2 there')}
for id,ops in matrix_cases.items():
 put(id,'Refer to the payoff matrix for '+{'001':'a regional freight pricing review','004':'a port-services coordination review','010':'a rotating delivery-slot game'}[id[-3:]]+'. Payoffs are profits ordered (Row, Column). Comparing both players’ best responses with the sum of their payoffs, which conclusion is supported?',list(ops),
 {'001':'Row prefers B under either column and Column prefers Y under either row. Their unique pure equilibrium B/Y pays (5,5), total 10. Joint totals at A/X, A/Y, B/X, B/Y are 16,14,14,10, so A/X maximizes joint profit. Consumer surplus is absent, so this is not a demonstrated social optimum.',
 '004':'Against X, Row chooses A; against Y, Row chooses B. Against A, Column chooses X; against B, Column chooses Y. Both diagonal cells are equilibria, with joint totals 23 and 21. Neither player has a dominant strategy. The maximum joint-profit cell is also one equilibrium; it need not be the selected outcome.',
 '010':'Row chooses A against X and B against Y. Column chooses Y against A and X against B. Every pure cell permits a profitable deviation. Each cell totals 8, so equal joint profit does not create a pure equilibrium. A mixed-strategy equilibrium is distinct from a pure one.'}[id[-3:]],'F: Integrate all pure equilibria, best responses and joint totals without assuming a prisoner’s dilemma or total social welfare.')
for n in [2,5,8,11,14,17]:
 id=f'P62I-OLI-L-{n:03d}';old=qs[id]
 # Both contingencies, rather than a missing specified opponent action.
 data={'002':('B against X and B against Y','16 exceeds 12 against X; 7 exceeds 4 against Y'), '005':('B against X and B against Y','13 exceeds 9 against X; 6 exceeds 4 against Y'), '008':('A against X and B against Y','8 exceeds 6 against X; 5 exceeds 3 against Y'), '011':('B against X and B against Y','15 exceeds 12 against X; 6 exceeds 3 against Y'), '014':('B against X and B against Y','14 exceeds 10 against X; 7 exceeds 5 against Y'), '017':('A against X and B against Y','11 exceeds 2 against X; 7 exceeds 1 against Y')}
 correct,why=data[id[-3:]]; alternatives=['A against X and A against Y','A against X and B against Y','B against X and A against Y','B against X and B against Y']
 put(id,old['q'].split(' Refer')[0]+' Refer to the payoff matrix. Which contingent plan gives Row a best response to each possible Column action? Payoffs are ordered (Row, Column).',[correct]+[o for o in alternatives if o!=correct],why+'. Compare Row’s first payoff in each cell within each column. '+('B is strictly dominant for Row.' if correct.startswith('B against X and B') else 'The best response changes with Column’s action, so Row has no dominant strategy.'),'Logical/robustness defect: The original asked for a best response to an unspecified action. Supply both contingencies.')
put('PM8-OLI-H-066','Four paving contractors independently face the same asphalt-cost increase. An investigator then finds messages in which their managers agree on a common minimum bid for upcoming jobs. Which evidence most directly supports an antitrust concern?',
 ['The agreement among competing bidders to set a common minimum price','The asphalt-cost increase shared by all four firms','The fact that all four firms may earn positive accounting profit','The fact that the market has fewer than ten sellers'],
 'A common cost shock can explain similar independent price increases. An agreement among competing bidders to set a minimum bid is direct evidence of coordinated pricing. Concentration or profit alone does not establish such an agreement.','B: Concrete application of existing antitrust rationale, without importing statute identity or private-suit doctrine.')
for n in [3,4]:
 id=f'P62I-OLI-H-{n:03d}'
 edit(id,f'Refer to market-share chart {n}. Other combines smaller firms, each with a share below firm D. What is the four-firm concentration ratio?', 'The four largest individual firms are A, B, C and D under the stated fringe assumption. Add their shares; do not count an aggregate of smaller firms as one large firm.')
 S[id]['options']=(['82%','86%','68%','100%'] if n==3 else ['90%','92%','82%','100%'])
 S[id]['feedback']+=(' Here CR4 = 28 + 22 + 18 + 14 = 82%.' if n==3 else ' Here CR4 = 50 + 20 + 12 + 8 = 90%.')
 S[id]['reason']='Numerical defect and ambiguity: Correct the CR4 sum from the actual plotted bars and specify the fringe assumption.'
S['P62G-MON-L-066']['q']=S['P62G-MON-L-066']['q'].replace('resulting accounting shortfall in economic costs','resulting shortfall in revenue relative to total economic cost')
S['P62F-PC-H-015']['q']='Refer to the paired market and firm graph and compare the firm’s price line with ATC at the rising-MC intersection. Suppose the displayed position followed a rise in buyer demand from an initial zero-profit equilibrium, before any entry and with firm cost curves unchanged. Which transmission from the market explains the displayed firm outcome?'
for n,formula in [(5,'26² + 24² + 20² + 15² + 15² = 2,102'),(6,'38² + 32² + 12² + 9² + 9² = 2,774'),(7,'31² + 29² + 17² + 13² + 10² = 2,360'),(8,'45² + 18² + 14² + 12² + 11² = 2,810')]:
 S[f'P62I-OLI-H-{n:03d}']['feedback']='With Other specified as one firm, HHI = '+formula+'. Square individual firm shares, not an unspecified fringe total. If Other contained several firms, their separate shares would be needed for an exact HHI.'
put('P62I-OLI-LB-009','Refer to the payoff matrix. An analyst says that the joint-profit maximum must differ from every Nash equilibrium. Which assessment of this particular game is correct? Payoffs are ordered (Row, Column).',
 ['A/X and B/Y are both pure equilibria; A/X also maximizes joint profit at 18, so the analyst’s claim fails','B/Y is the only pure equilibrium; A/X maximizes joint profit at 18, so the analyst’s claim holds','A/X is the only pure equilibrium because its joint profit of 18 exceeds 14 at B/Y','Neither diagonal cell is an equilibrium because a joint-profit maximum cannot be individually stable'],
 'Row prefers A against X and B against Y; Column prefers X against A and Y against B. Both A/X and B/Y are mutual best responses. Their totals are 18 and 14; the off-diagonal totals are 5 each. Thus A/X is both a pure equilibrium and the joint-profit maximum. Neither player has a dominant strategy. Firm profits alone do not determine social welfare.','Logical defect: The original keyed a universal difference even though one of this matrix’s two equilibria is the joint optimum.')
put('P62I-OLI-EL-002','Refer to the asymmetric payoff matrix. Compare both firms’ incentives and then sum their profits. Which equilibrium-versus-joint-profit comparison follows?',
 ['B/Y is the unique pure equilibrium with total 11; A/X gives the largest total, 18','B/Y is the unique pure equilibrium with total 11; A/Y gives the largest total, 15','A/X is the unique pure equilibrium because its total of 18 is largest','B/X is the equilibrium because Row’s payoff of 12 is largest'],
 'Row prefers B in both columns (12 > 7 and 5 > 2). Column prefers Y in both rows (13 > 11 and 6 > 4). B/Y is therefore the equilibrium, totaling 11. The four totals are 18, 15, 16 and 11, so A/X maximizes joint profit. That comparison does not include consumer welfare.','F: Replace a generic claim that outcomes can differ with a matrix-specific incentive and total comparison.')
put('P62I-OLI-EL-008','Refer to the matrix with A/X payoffs (18,18). If the firms agree on A/X, what unilateral incentive threatens the agreement and how does the resulting pure equilibrium compare with their joint-profit maximum?',
 ['Either firm can raise its own payoff to 23 by deviating alone; B/Y totals 20 instead of A/X’s 36','Neither firm can improve alone; A/X is the pure equilibrium because its total is 36','Either firm gains only if both deviate; B/Y totals 36 instead of A/X’s 20','Row benefits from deviating but Column does not; the equilibrium is B/X with total 29'],
 'Holding the other firm at A or X, a unilateral switch raises the deviator’s payoff from 18 to 23. Each firm also prefers its aggressive action when the other uses it (10 > 6), so B/Y is the unique pure equilibrium. Joint profit is 20 there, versus 36 at A/X; private deviation incentives prevent the joint maximum from being a one-shot equilibrium.','F: Require deviation, dominance, equilibrium and joint-total reasoning from the actual approved matrix.')
if __name__=='__main__':
 (W/'revisions.json').write_text(json.dumps(S,ensure_ascii=False,indent=2)+'\n','utf8');print('Revised specifications:',len(S))
