import { measurementModel } from './measurement.js';
const dollars=n=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const percent=n=>`${Number(n.toFixed(1))}%`;
const action=(name,label)=>`<button type="button" class="primary" data-measurement="${name}">${label}</button>`;
const choice=(e,id,label)=>`<button type="button" data-measurement-answer="${id}" aria-pressed="${e.selected===id}" ${e.solved?'disabled':''}>${label}</button>`;
const tokens=(count,label)=>`<span class="quantity-tokens" aria-label="${count} ${label}">${Array.from({length:count},()=>'<i aria-hidden="true"></i>').join('')}<b aria-hidden="true">× ${count}</b></span>`;
const row=(label,value)=>`<div><dt>${label}</dt><dd>${value}</dd></div>`;
export function measurementView(run){
  const e=run.extension,m=measurementModel(e);
  const feedback=`<div id="extension-feedback" class="cpi-feedback ${e.feedback?'has-feedback':''}" tabindex="-1">${e.feedback?`<strong>${e.solved?'Verified':e.newStep==='opportunity'&&e.selected==='wait'?'Basket checked':'Consider the comparison'}</strong><p>${e.feedback}</p>`:''}</div>`;
  let body='';
  if(e.episode==='substitution'){
    body=`<h3>When relative prices change</h3><p>${m.s.context}</p><table class="timeline-table"><caption>Two substitute products · prices per purchase</caption><thead><tr><th scope="col">Product</th><th scope="col">Base</th><th scope="col">Next period</th></tr></thead><tbody>${m.s.goods.map((g,i)=>`<tr><th scope="row">${g}</th><td>${dollars(m.s.base[i])}</td><td>${dollars(m.s.current[i])}</td></tr>`).join('')}</tbody></table>
    <div class="comparison-grid"><section><h3>Original fixed basket</h3>${m.s.goods.map(g=>`<p>${g}${tokens(2,g)}</p>`).join('')}<dl class="extension-readouts">${row('Base cost',dollars(m.base))}${row('Next-period cost',dollars(m.fixed))}${row('Cost increase',percent(m.fixedRate))}</dl></section><section><h3>Consumer’s alternative</h3>${m.s.goods.map((g,i)=>`<p>${g}${tokens(i?2+e.shift:2-e.shift,g)}</p>`).join('')}<div class="swap-controls"><button type="button" data-shift="1" ${e.solved||e.shift===1?'disabled':''}>Move one to ${m.s.goods[1]}</button><button type="button" data-shift="0" ${e.solved||e.shift===0?'disabled':''}>Restore original mix</button></div><dl class="extension-readouts">${row('Cost of this bundle',dollars(m.shifted))}${row('Change from original base cost',percent(m.shiftedRate))}</dl></section></div><p>Relative to this acceptable substituted bundle, does the original fixed basket overstate or understate the cost increase?</p><div class="cpi-options">${choice(e,'overstate','Overstate the increase')}${choice(e,'same','Record the same increase')}${choice(e,'understate','Understate the increase')}</div>`;
  }else if(e.episode==='newGoods'){
    const revealed=e.newStep==='opportunity';
    body=`<h3>A new choice reaches the market</h3><p>${m.n.context}</p><div class="comparison-grid"><section><h3>Original basket</h3><p>${m.n.old}</p><dl class="extension-readouts">${row('Base and current price',dollars(m.n.oldPrice))}${row('Assigned quantity','1')}</dl><div class="new-product-slot">No ${m.n.product.toLowerCase()} in the base period<br><strong>Base price: unavailable</strong></div></section><section><h3>New market option</h3><p><strong>${m.n.product}</strong></p><dl class="extension-readouts">${row('Available now',dollars(m.n.price))}</dl><p>Newly available: no base-period price or original basket quantity.</p></section></div>
    ${revealed?`<div class="opportunity"><h3>A purchasing opportunity</h3><p>This household can obtain the service it needs for ${dollars(m.n.price)} instead of ${dollars(m.n.oldPrice)}: ${dollars(m.n.oldPrice-m.n.price)} less per purchase. This is an opportunity for the household, not an estimated CPI change.</p></div><p>How can the index incorporate this new option later?</p><div class="cpi-options">${choice(e,'update','Update the basket and use an appropriate linked comparison')}${choice(e,'ignore','Keep new goods outside the index permanently')}</div>`:`<p>Can you insert this new product directly into the original base-year calculation?</p><div class="cpi-options">${choice(e,'insert','Yes — use today’s price as its base price')}${choice(e,'wait','No — the original comparison lacks its base-period data')}</div>`}
    ${e.solved?'<div class="updated-basket"><strong>Later basket update</strong><p>Original products + the new option → collect comparable prices and link the updated index. Earlier base-period data remain unchanged.</p></div>':''}`;
  }else if(e.episode==='quality'){
    const field=(name,label)=>`<div class="entry-field"><label for="quality-${name}">${label}</label><input id="quality-${name}" name="${name}" type="text" inputmode="${name==='comparable'?'decimal':'text'}" required autocomplete="off" aria-describedby="quality-help extension-feedback" ${e.solved?'disabled':''} value="${e.answers?.[name]??''}"></div>`;
    body=`<h3>A better ${m.q.product.toLowerCase()} has a higher price</h3><div class="comparison-grid"><section><h3>Old ${m.q.product.toLowerCase()}</h3><p class="product-price">${dollars(m.q.oldPrice)}</p><p>Original features</p></section><section><h3>New ${m.q.product.toLowerCase()}</h3><p class="product-price">${dollars(m.q.price)}</p><p>${m.q.improvement}</p></section></div><p>Analysts estimate that <strong>${dollars(m.q.adjustment)}</strong> of the new price reflects added measurable quality. Subtract that estimate to compare like with like.</p><form id="quality-form">${field('comparable','Quality-adjusted comparable price ($)')}${field('raw','Unadjusted price change (%)')}${field('adjusted','Quality-adjusted price change (%)')}<p id="quality-help" class="cpi-help">Both percentage changes use the old price as the denominator. Use a minus sign if the comparable price falls. This is a simplified dollar adjustment, not a quality-score ratio.</p><button class="primary" type="submit" ${e.solved?'disabled':''}>COMPARE THE PRICES</button></form>${e.solved?`<dl class="extension-readouts">${row('Raw price change',percent(m.rawRate))}${row('Comparable price',dollars(m.comparable))}${row('Adjusted price change',percent(m.adjustedRate))}</dl>`:''}`;
  }else{
    body=`<h3>Why a fixed basket can overstate cost-of-living growth</h3><div class="measurement-summary"><section><h3>Substitution</h3><p class="comparison-label">Fixed basket → what changed underneath</p><p>2 ${m.s.goods[0]} + 2 ${m.s.goods[1]} → 1 + 3 purchases</p><dl class="extension-readouts">${row('Original basket',dollars(m.fixed))}${row('Substituted bundle',dollars(m.shifted))}</dl><p>Consumers can switch toward relatively cheaper goods. Original quantities do not reflect that switch.</p></section><section><h3>New goods</h3><p class="comparison-label">Old basket → expanded choice set</p><div class="new-product-slot">No base-period product → ${m.n.product}</div><p>${m.n.old}: ${dollars(m.n.oldPrice)}<br>New option: ${dollars(m.n.price)}</p><p>New choices can benefit consumers before they enter the basket.</p></section><section><h3>Quality change</h3><p class="comparison-label">Raw price → comparable price</p><dl class="extension-readouts">${row('New price',dollars(m.q.price))}${row('Less estimated quality value',dollars(m.q.adjustment))}${row('Comparable price',dollars(m.comparable))}</dl><p>Some observed price increases pay for a better product rather than the same product becoming more expensive.</p></section></div><p>CPI is not useless or “wrong.” These are measurement challenges. Statistical agencies update baskets and use quality adjustments to reduce these problems. The comparisons here illustrate possible effects; they do not calculate a “true CPI.”</p><div class="cpi-formula"><strong>Your core calculation remains the foundation</strong><span>CPI = (current basket cost ÷ base basket cost) × 100</span><span>Inflation = ((new CPI − previous CPI) ÷ previous CPI) × 100</span></div>${action('replay','EXPLORE ANOTHER COMBINATION')}`;
  }
  return `<p class="eyebrow">Optional extension${e.episode==='complete'?' · complete':` · episode ${['substitution','newGoods','quality'].indexOf(e.episode)+1} / 3`}</p><h2 id="stage-title" tabindex="-1">Behind the Index</h2><p class="extension-subtitle">Where CPI Measurement Gets Complicated</p>${body}${feedback}${e.solved?action('next',e.episode==='quality'?'COMPARE THE THREE CHALLENGES':'NEXT EPISODE'):''}<div class="actions">${action('summary','BACK TO CORE RESULTS')}${e.episode==='complete'?'<button class="primary" data-action="replay">PLAY AGAIN · CORE CPI</button><a class="button" href="/games/">RETURN TO GAMES</a>':''}</div>`;
}
