import { ANALYSIS_QUESTIONS } from './analysis.js';
import { productionGraph } from './graphs.js';
export function renderAnalysis(state) {
  if (state.phase === 'connect_graphs') return `<section class="review graph-review"><h2 id="stage-title" tabindex="-1">The two graphs tell the same story in different ways.</h2><div class="paired-graphs">${productionGraph('total', state.tested, true, 'paired-total')}${productionGraph('marginal', state.tested, true, 'paired-marginal')}</div><ul class="graph-connection"><li>Marginal product rises through Worker 3, then falls beginning with Worker 4.</li><li>It stays positive, so total product keeps rising.</li><li>Its additions get smaller, so the total-product curve becomes flatter.</li></ul><button class="primary" data-action="continue_analysis">CONTINUE TO THE PRODUCTION RECORD</button></section>`;
  const q = ANALYSIS_QUESTIONS[state.phase], answer = state.analysisAnswers[state.phase];
  const graph = true, total = state.phase === 'total_graph';
  return `<section class="review ${graph ? 'graph-review' : 'what-if'}"><h2 id="stage-title" tabindex="-1">${graph ? 'BUILD THE PRODUCTION PICTURE' : 'WHAT IF?'}</h2>
    ${graph ? `<p class="eyebrow">${total && !answer ? 'YOUR OBSERVED PRODUCTION' : 'THE COMPLETE PRODUCTION RECORD'}</p>${productionGraph(total ? 'total' : 'marginal', state.tested, !total || !!answer)}${total && state.tested.length < 4 && !answer ? '<p class="small">Your run tested fewer than four crews. For this comparison, the kitchen reference records 31, 42, 50 and 53 tacos with three, four, five and six workers.</p>' : ''}` : ''}
    <fieldset><legend>${q.prompt}</legend><div class="answer-options concept-options">${q.options.map((option, i) => `<button data-analysis-answer="${i}" ${answer ? 'disabled' : ''} ${answer?.value === i ? 'aria-pressed="true"' : ''}>${option}</button>`).join('')}</div></fieldset>
    ${answer ? `<div class="question-feedback" role="status" tabindex="-1"><p><strong>${answer.correct ? 'Yes.' : 'Here’s the connection.'}</strong> ${q.feedback}</p><button class="primary" data-action="continue_analysis">${total ? 'EXPLORE MARGINAL PRODUCT' : state.phase === 'marginal_graph' ? 'CONNECT THE TWO GRAPHS' : 'FINAL TAKEAWAY'}</button></div>` : ''}</section>`;
}
