import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const repo=path.resolve(process.argv[2]||process.cwd());
const dryRun=process.argv.includes('--dry-run');
const PHASE='phaseM2c1-money-banking-fed-family-maturation-v1';
const STAMP=new Date().toISOString();
const SOURCE='macro-m2c1-money-banking-fed-family';
const familyIds=['money-functions-and-measures','bank-money-creation','central-bank-and-federal-reserve','monetary-policy-tools','monetary-control-limits'];
const modifiedIds=[...familyIds];
const modifiedSet=new Set(modifiedIds);
const composer=path.join(repo,'build','faculty-build-composer');
const dataDir=path.join(composer,'data');
const libraryPath=path.join(dataDir,'composer_library.js');
const registryPath=path.join(dataDir,'composer_registry.json');
const manifestPath=path.join(dataDir,'composer_library_manifest.json');
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])])):value;
const answerHash=answer=>sha(String(answer).trim().replace(/\s+/g,' ').toLowerCase());
const qid=q=>String(q?.canonicalId||q?.id||q?.questionId||'');
const questionHash=q=>sha(JSON.stringify(stable({q:q.q,options:q.options,aHash:q.aHash,primaryConceptId:q.primaryConceptId,primarySkill:q.primarySkill,repairSkill:q.repairSkill,difficulty:q.difficulty,secondaryConceptIds:q.secondaryConceptIds||[],bossStage:q.bossStage||null,image:q.image||null})));
const loadLibrary=raw=>{const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(raw,sandbox,{filename:libraryPath});return sandbox.window.MQ_COMPOSER_LIBRARY;};
const rawBefore=fs.readFileSync(libraryPath,'utf8');
const library=loadLibrary(rawBefore);
const registry=JSON.parse(fs.readFileSync(registryPath,'utf8'));
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
if(!String(library.libraryVersion).endsWith('phaseM2b4-unemployment-labor-family-maturation-v1'))throw new Error('Unexpected baseline: completed M2b-4 library required.');
for(const id of familyIds)if(!library.concepts[id])throw new Error(`Missing F5 concept ${id}`);

function tagged(module){return [...Object.entries(module.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(module.repairQuestions||[]).map(question=>({pool:'repair',question})),...(module.repairSeedQuestions||[]).map(question=>({pool:'repairSeed',question})),...(module.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))];}
function unique(module){const seen=new Set();return tagged(module).filter(({question})=>{const id=qid(question);if(seen.has(id))return false;seen.add(id);return true;});}
function bankSnapshot(module){return unique(module).map(({pool,question})=>({pool,id:qid(question),question:stable(question)})).sort((a,b)=>a.id.localeCompare(b.id));}
function bankHash(module){return sha(JSON.stringify(stable(bankSnapshot(module))));}
function countModule(module){
 const boss=module.questions?.boss||[];
 return {easy:(module.questions?.easy||[]).length,medium:(module.questions?.medium||[]).length,hard:(module.questions?.hard||[]).length,elite:(module.questions?.elite||[]).length,legendary:(module.questions?.legendary||[]).length,calculation:(module.questions?.calculation||[]).length,integration:(module.questions?.integration||[]).length,easyBoss:boss.filter(q=>String(q.difficulty).toLowerCase()==='easyboss').length,mediumBoss:boss.filter(q=>String(q.difficulty).toLowerCase()==='mediumboss').length,finalBoss:boss.filter(q=>['finalboss','hardboss'].includes(String(q.difficulty).toLowerCase())).length,legendaryBoss:(module.questions?.legendaryBoss||[]).length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length,bridge:(module.bridgeQuestions||[]).length,total:unique(module).length};
}
const protectedIds=Object.keys(library.concepts).filter(id=>!modifiedSet.has(id));
const protectedBefore=Object.fromEntries(protectedIds.map(id=>[id,bankHash(library.concepts[id])]));
const beforeCounts=Object.fromEntries(familyIds.map(id=>[id,countModule(library.concepts[id])]));
const beforeTotal=library.canonicalQuestionCount;
const previousVersion=library.libraryVersion;
const changes=[];
let serial=8800000;

const lessonMap={
 central_commercial_money:['Treats commercial-bank deposits and central-bank reserves as the same liability issued by the same institution.','Commercial banks create deposit liabilities when they lend; the central bank creates reserve balances/base money used by banks.'],
 fed_treasury_distinction:['Treats the Federal Reserve and Treasury as interchangeable agencies.','The Federal Reserve conducts monetary policy and supports the banking/payments system; the Treasury manages federal finances and debt operations.'],
 liquidity_solvency:['Treats emergency central-bank liquidity as a way to erase losses at an insolvent institution.','Lender-of-last-resort support addresses temporary liquidity problems; insolvency requires losses to be recognized and capital restored through other mechanisms.'],
 reserve_supply_vs_lending:['Assumes that creating reserves automatically forces commercial banks to make loans and expand deposits.','The central bank can supply reserves, but broad deposit creation also depends on banks, borrowers, and redepositing behavior.'],
 weak_loan_demand:['Assumes banks can expand loans to the textbook maximum even when creditworthy customers do not want to borrow.','Reserve availability is only one condition for lending; weak loan demand can make broad money expand by less than a simple multiplier suggests.'],
 limits_of_monetary_control:['Treats the central bank as having mechanical one-for-one control over broad money.','The central bank controls its own balance sheet and reserve conditions more directly than broad money, which also depends on banks, borrowers, and the public.']
};
function lesson(skill){return lessonMap[skill]||['Uses a surface cue instead of distinguishing the institution, banking mechanism, policy tool, or control limit.','Identify which institution acts first, then trace what banks, borrowers, and depositors can do next.'];}
function rotate(options,answer,index){const n=index%options.length;const out=options.slice(n).concat(options.slice(0,n));if(!out.includes(answer))throw new Error(`Answer missing: ${answer}`);return out;}
function spec(stem,answer,wrong,skill,extra={}){return{stem,answer,options:[answer,...wrong],skill,...extra};}
const codeById={'central-bank-and-federal-reserve':'FED','monetary-control-limits':'MCL'};
const objectiveById={'central-bank-and-federal-reserve':'LO30.2','monetary-control-limits':'LO31.4'};
const tagById={'central-bank-and-federal-reserve':'central_banking','monetary-control-limits':'monetary_control_limits'};

function addQuestion(conceptId,pool,s,index){
 const module=library.concepts[conceptId],boss=pool==='boss',lb=pool==='legendaryBoss',tier=boss?s.tier:null;
 const canonicalDifficulty=boss?({easyBoss:'easy',mediumBoss:'medium',finalBoss:'hard'})[tier]:lb?'legendary':pool;
 const marker=boss?({easyBoss:'EB',mediumBoss:'MB',finalBoss:'FB'})[tier]:({easy:'E',medium:'M',hard:'H',legendary:'L',legendaryBoss:'LB'})[pool];
 const id=`PM2C1-${codeById[conceptId]}-${marker}-${String(index+1).padStart(3,'0')}`;
 const [commonError,feedback]=lesson(s.skill);
 const q={id,sourceGame:SOURCE,q:s.stem,options:rotate(s.options,s.answer,index),tag:tagById[conceptId],type:s.type||'application',objective:objectiveById[conceptId],difficulty:boss?tier:lb?'legendaryBoss':pool,conceptCluster:'money_banking_fed',primarySkill:s.skill,secondarySkills:s.secondarySkills||[],repairSkill:s.repairSkill||s.skill,commonError:s.commonError||commonError,feedback:s.feedback||feedback,aHash:answerHash(s.answer),canonicalId:id,sourceId:++serial,sourceChapter:[30,31],sourcePool:boss?tier:s.skill,primaryConceptId:conceptId,secondaryConceptIds:s.secondaryConceptIds||[],instructionalRole:boss?'boss':lb?'legendaryBoss':pool,canonicalDifficulty,originalSourcePool:boss?tier:s.skill,originalBossTier:boss?tier:lb?'legendaryBoss':null,sourceCurationPhase:PHASE};
 if(boss)q.boss=({easyBoss:'Checkpoint One',mediumBoss:'Checkpoint Two',finalBoss:'Final Checkpoint'})[tier];
 if(lb)q.bossStage=s.bossStage;
 q.sourceHash=questionHash(q);
 q.sourceOccurrences=[{sourceGame:SOURCE,sourceFile:`${PHASE}_questions.json`,sourceGlobal:'questions',sourcePool:q.sourcePool,routeKey:q.primarySkill,sourceRecordOrder:index,sourceId:q.sourceId,sourceHash:q.sourceHash,sourceCurationPhase:PHASE}];
 if(boss)module.questions.boss.push(q);else module.questions[pool].push(q);
 changes.push({questionId:id,canonicalConceptId:conceptId,action:'ADD',oldPool:null,newPool:boss?tier:pool,reason:s.reason||'Closes a verified F5 structural floor with a distinct money/banking/Fed task.'});
 return q;
}
function findQuestion(conceptId,id){for(const row of tagged(library.concepts[conceptId]))if(qid(row.question)===id)return row;throw new Error(`Question not found ${conceptId}/${id}`);}
function setSourceHash(q){q.sourceCurationPhase=PHASE;q.sourceHash=questionHash(q);if(Array.isArray(q.sourceOccurrences)&&q.sourceOccurrences[0]){q.sourceOccurrences[0].sourceHash=q.sourceHash;q.sourceOccurrences[0].sourceCurationPhase=PHASE;}}
function rewrite(conceptId,id,s,reason,action='QUALITY_REWRITE'){
 const {pool,question:q}=findQuestion(conceptId,id),beforeHash=questionHash(q),oldSkill=q.primarySkill,oldRepairSkill=q.repairSkill;
 q.q=s.stem;q.options=rotate(s.options,s.answer,0);q.aHash=answerHash(s.answer);q.primarySkill=s.skill||q.primarySkill;q.repairSkill=s.repairSkill||s.skill||q.repairSkill;q.secondaryConceptIds=s.secondaryConceptIds||[];q.secondarySkills=s.secondarySkills||[];q.type=s.type||q.type||'application';
 const [commonError,feedback]=lesson(q.primarySkill);q.commonError=s.commonError||commonError;q.feedback=s.feedback||feedback;setSourceHash(q);
 changes.push({questionId:id,canonicalConceptId:conceptId,action,oldPool:pool,newPool:pool,reason,beforeHash,afterHash:questionHash(q),oldSkill,newSkill:q.primarySkill,oldRepairSkill,newRepairSkill:q.repairSkill});
}
function metadataUpdate(conceptId,id,patch,reason,action='METADATA_REPAIR'){
 const {pool,question:q}=findQuestion(conceptId,id),beforeHash=questionHash(q),before={bossStage:q.bossStage,primarySkill:q.primarySkill,repairSkill:q.repairSkill,secondaryConceptIds:q.secondaryConceptIds||[]};Object.assign(q,patch);setSourceHash(q);changes.push({questionId:id,canonicalConceptId:conceptId,action,oldPool:pool,newPool:pool,reason,beforeHash,afterHash:questionHash(q),before,after:{bossStage:q.bossStage,primarySkill:q.primarySkill,repairSkill:q.repairSkill,secondaryConceptIds:q.secondaryConceptIds||[]}});
}

// -----------------------------------------------------------------------------
// A. Quality modernization in Money Functions: preserve count, replace four
// definition-like Easy tasks with concrete applications.
// -----------------------------------------------------------------------------
rewrite('money-functions-and-measures','LG-Q-1',spec('A farmer wants shoes, but the shoemaker does not want wheat. Both are willing to accept dollars. Which feature of money solves the immediate trading problem?','It serves as a medium of exchange, so the two traders do not need a double coincidence of wants',['It serves only as a store of value, so neither trader has to exchange anything','It makes every good part of M1, so barter becomes unnecessary','It guarantees that the relative price of wheat and shoes never changes'],'identify_money_functions',{repairSkill:'identify_money_functions'}),'Modernizes a definition-like Easy item into a concrete medium-of-exchange application.');
rewrite('money-functions-and-measures','LG-Q-2',spec('A repair shop compares a $450 used laptop with a $900 new laptop before deciding which to buy. Which function of money makes that comparison straightforward?','Unit of account',['Medium of exchange','Store of value','Bank reserve'],'identify_money_functions',{repairSkill:'identify_money_functions'}),'Modernizes a definition-like Easy item into a price-comparison application.');
rewrite('money-functions-and-measures','LG-Q-3',spec('A household keeps $600 in cash for emergencies. If prices rise substantially before the cash is spent, which statement is most accurate?','The cash serves as a store of value, but its purchasing power can fall',['The cash stops being money because a store of value must keep purchasing power constant','The cash is serving only as a unit of account because it is not being spent today','Inflation converts the cash from M1 into a nonmonetary financial asset'],'identify_money_functions',{repairSkill:'functions_of_money'}),'Modernizes a definition-like Easy item and adds the limitation of money as a store of value.');
rewrite('money-functions-and-measures','LG-Q-4',spec('Customers accept paper currency even though the paper itself has little intrinsic value and cannot be redeemed for a commodity. Which explanation best fits?','It is fiat money whose usefulness depends on general acceptance rather than commodity value',['It is commodity money because the paper can be physically held','It is bank capital because it supports financial transactions','It is not money unless every note is backed one-for-one by gold'],'commodity_vs_fiat_money',{repairSkill:'fiat_money_definition'}),'Modernizes a definition-like Easy fiat-money item into an applied acceptance scenario.');

// -----------------------------------------------------------------------------
// B. Repair modernization/routing. Counts are intentionally unchanged.
// -----------------------------------------------------------------------------
rewrite('money-functions-and-measures','LG-R-5000',spec('A household owns a home and stocks and earns a salary, but keeps very little currency or checking deposits. Which statement is correct?','Wealth and income can be high even when the household holds little money',['All household wealth is counted in M1 because it can eventually be sold','Salary income is automatically part of the money supply before it is paid','Only physical currency can count as money, so checking deposits are wealth instead'],'money_vs_wealth_income',{repairSkill:'money_vs_wealth_income'}),'Adds the missing money-versus-wealth/income misconception path by repurposing a duplicate function-of-money Repair.','REPAIR_REWRITE');
rewrite('bank-money-creation','LG-R-5012',spec('A bank suffers a loss because some of its loan assets lose value. Which balance-sheet item absorbs the loss first?','Bank capital',['Required reserves','Customer deposits automatically increase','New loans created after the loss'],'bank_capital_assets_liabilities',{repairSkill:'bank_leverage_risk'}),'Replaces a redundant required-reserves formula Repair with the capital-versus-reserves misconception identified in M1.','REPAIR_REWRITE');
rewrite('bank-money-creation','LG-R-5013',spec('A bank makes a new loan by crediting the borrower’s deposit account. Which statement best describes the textbook balance-sheet effect?','The bank adds a loan asset and a deposit liability; it does not hand the borrower a pile of reserves',['The bank permanently loses required reserves equal to the full loan amount','The bank creates new capital equal to the loan and leaves deposits unchanged','The central bank must approve and create each commercial-bank loan individually'],'fractional_reserve_money_creation',{repairSkill:'fractional_reserve_money_creation'}),'Adds a direct Repair route for the recurring fractional-reserve money-creation skill.','REPAIR_REWRITE');
rewrite('central-bank-and-federal-reserve','LG-R-5006',spec('A solvent bank has sound assets but cannot obtain short-term funding during a panic. Which central-bank role is designed for this situation?','Lender of last resort',['Collector of federal income taxes','Issuer of corporate stock','Manager of the congressional budget'],'fed_lender_of_last_resort',{repairSkill:'fed_lender_of_last_resort'}),'Replaces a generic Fed-definition Repair with a direct lender-of-last-resort misconception path.','REPAIR_REWRITE');
rewrite('central-bank-and-federal-reserve','LG-R-5010',spec('Elected officials establish a central bank’s mandate, while the bank chooses how to use its policy instruments and reports its decisions publicly. What principle does this arrangement illustrate?','Instrument independence combined with public accountability',['Complete independence from any publicly established mandate','Fiscal dominance because elected officials choose tax rates','Abolition of central-bank discretion over policy instruments'],'independence_accountability',{repairSkill:'independence_accountability'}),'Aligns a generic independence Repair with the recurring independence/accountability skill.','REPAIR_REWRITE');
rewrite('monetary-policy-tools','LG-R-5018',spec('If the reserve requirement is lowered, other things equal, what happens to the amount of deposits banks must hold as required reserves?','It falls, leaving more reserves potentially available for lending',['It rises, leaving fewer reserves potentially available for lending','It is unchanged because reserve requirements affect only currency','It becomes equal to total bank capital'],'reserve_requirement_effect',{repairSkill:'reserve_requirement_effect'}),'Repurposes a duplicate bond-purchase Repair to cover the heavily recurring reserve-requirement effect.','REPAIR_REWRITE');
rewrite('monetary-policy-tools','LG-R-5020',spec('If the central bank lowers the rate it charges banks for direct loans, what is the immediate textbook effect?','Borrowing from the central bank becomes less costly for banks',['Required reserves automatically rise for every bank','The Treasury must reduce government spending','The public is forced to hold less currency'],'discount_rate_effect',{repairSkill:'discount_rate_effect'}),'Repurposes a duplicate bond-sale Repair to cover the discount-rate mechanism.','REPAIR_REWRITE');
metadataUpdate('monetary-control-limits','LG-R-5023',{primarySkill:'public_currency_holdings',repairSkill:'public_currency_holdings'},'Aligns an existing currency-drain Repair with the recurring public-currency-holdings route.','REPAIR_METADATA_FIX');

// -----------------------------------------------------------------------------
// C. Genuine Bridge chain. Counts are unchanged; selected legacy same-skill
// checks are rewritten so F5 teaches Money Measures → Bank Creation → Fed →
// Tools → Limits, plus one outbound Tools → F7 Money Market bridge.
// -----------------------------------------------------------------------------
rewrite('money-functions-and-measures','ECON-SP-DISTINGUISH-M1-M2-6001',spec('Households move cash from wallets into checking accounts. The composition of M1 changes little, but what banking consequence can the shift create?','Banks receive deposits and reserves that can support lending under the banking model',['The deposits stop counting in M1 because checking accounts are not money','The central bank must create matching bank capital before any deposit can be accepted','The shift guarantees the maximum simple money multiplier regardless of bank behavior'],'connect_money_measure_to_lending',{repairSkill:'m1_m2_components',secondaryConceptIds:['bank-money-creation'],secondarySkills:['fractional_reserve_money_creation']}),'Replaces a same-skill M1/M2 Bridge with a genuine Money Measures → Bank Money Creation connection.','BRIDGE_REWRITE');
rewrite('bank-money-creation','ECON-SP-CALCULATE-MONEY-MULTIPLIER-EFFECT-6006',spec('The central bank adds reserves to the banking system through an asset purchase. Why does this not mean the central bank itself makes every new commercial loan?','The central bank supplies reserves; commercial banks and borrowers determine later lending and deposit creation',['The central bank directly selects every commercial borrower and dictates the size of each loan after the asset purchase','Commercial banks can lend only currency printed during the same transaction','Asset purchases increase bank capital rather than reserve balances'],'fractional_reserve_money_creation',{repairSkill:'fractional_reserve_money_creation',secondaryConceptIds:['central-bank-and-federal-reserve'],secondarySkills:['distinguish_base_money_from_deposit_creation']}),'Replaces a same-skill multiplier Bridge with a genuine Bank Money Creation → Central Bank connection.','BRIDGE_REWRITE');
rewrite('central-bank-and-federal-reserve','ECON-SP-FOMC-ROLE-6003',spec('The FOMC decides that monetary conditions should be easier and authorizes purchases of securities. What connection is being made?','The FOMC is choosing a monetary-policy tool that adds reserves',['The Treasury is using fiscal policy to change government purchases','A commercial bank is deciding how much capital to issue to shareholders','Households are changing M1 by moving funds from checking to savings'],'connect_fomc_to_policy',{repairSkill:'fomc_role',secondaryConceptIds:['monetary-policy-tools'],secondarySkills:['fed_buys_bonds_money_supply']}),'Rewrites a same-skill FOMC check into a Central Bank → Monetary Policy Tools Bridge.','BRIDGE_REWRITE');
rewrite('monetary-policy-tools','ECON-SP-CHOOSE-FED-TOOL-EFFECT-6007',spec('The central bank buys securities and bank reserves rise, but banks choose to hold much of the new reserves idle. What does this show about the policy chain?','The tool can increase reserves even when the resulting expansion of bank deposits is smaller than the simple model predicts',['The asset purchase failed to change reserves, so it was not a monetary-policy action','Holding excess reserves forces the money multiplier above its simple maximum','A central-bank asset purchase automatically becomes fiscal policy when banks do not lend'],'diagnose_policy_constraint',{repairSkill:'choose_fed_tool_effect',secondaryConceptIds:['monetary-control-limits'],secondarySkills:['limits_of_monetary_control']}),'Rewrites a same-skill tool check into a Monetary Policy Tools → Control Limits Bridge.','BRIDGE_REWRITE');
rewrite('monetary-policy-tools','LG-B-6006',spec('The central bank buys securities, increasing reserves and the money supply. In the liquidity-preference money-market model, what is the next directional step, other things equal?','The equilibrium interest rate tends to fall',['The equilibrium interest rate must rise because reserves increased','Aggregate supply immediately shifts left before any interest-rate change','The federal budget deficit automatically falls by the amount of the purchase'],'fed_buys_bonds_money_supply',{repairSkill:'fed_buys_bonds_money_supply',secondaryConceptIds:['liquidity-preference-and-money-market'],secondarySkills:['money_supply_shift']}),'Replaces an unrelated fiscal secondary tag with a genuine outbound F5 Tools → F7 Money Market Bridge.','BRIDGE_REWRITE');
rewrite('monetary-policy-tools','LG-B-6007',spec('The central bank sells securities, reducing reserves and the money supply. In the liquidity-preference money-market model, what is the next directional step, other things equal?','The equilibrium interest rate tends to rise',['The equilibrium interest rate must fall because reserves decreased','Aggregate supply immediately shifts right before any interest-rate change','The federal budget surplus automatically rises by the amount of the sale'],'fed_sells_bonds_money_supply',{repairSkill:'fed_sells_bonds_money_supply',secondaryConceptIds:['liquidity-preference-and-money-market'],secondarySkills:['money_supply_shift']}),'Replaces the second unrelated fiscal secondary tag with a genuine contractionary F5 Tools → F7 Money Market Bridge.','BRIDGE_REWRITE');

// -----------------------------------------------------------------------------
// D. Central Bank structural additions: +15.
// -----------------------------------------------------------------------------
const central={
 medium:[
  spec('A commercial bank approves a loan and credits the borrower’s checking account. In a separate transaction, the Federal Reserve credits a bank’s reserve account during an asset purchase. Which distinction is correct?','The commercial bank creates a deposit liability; the Fed creates central-bank reserves',['The Fed creates the borrower’s commercial-bank deposit, while the bank creates central-bank reserves','Both transactions create only physical currency held by the public','Neither transaction changes any bank liability or reserve balance'],'central_commercial_money'),
  spec('A headline says, “The Treasury raised the federal funds rate to conduct monetary policy.” What is the best correction?','Monetary policy and the federal funds rate are associated with the Federal Reserve, while the Treasury manages federal finances and debt operations',['The statement is correct because the Treasury and Federal Reserve are the same institution','The federal funds rate is set by commercial banks with no connection to Federal Reserve policy','The Treasury sets monetary policy while the Federal Reserve determines tax rates and federal spending'],'fed_treasury_distinction')
 ],
 hard:[
  spec('During a panic, a bank has valuable assets but cannot obtain enough short-term funding to meet payments. Later analysis shows another bank’s assets are worth less than its liabilities. Why should a central bank treat the two cases differently?','Liquidity can address the first bank’s funding problem, but it cannot erase the second bank’s insolvency',['Both banks should receive unlimited central-bank loans because any funding problem proves that losses and insolvency are irrelevant','The insolvent bank needs only a lower reserve requirement, while the solvent bank must be closed immediately','The central bank should finance both banks permanently because recognizing losses is a fiscal-policy function'],'liquidity_solvency'),
  spec('A central-bank asset purchase sharply increases reserve balances, yet commercial-bank lending changes little. Which statement best separates the institutions’ roles?','The central bank creates reserves; commercial-bank deposit creation still depends on lending and borrowing',['The central bank failed to create any reserve balances because commercial banks did not expand loans after the asset purchase','Commercial banks create central-bank reserves whenever they choose not to lend','Reserve balances are identical to bank capital, so unchanged lending proves capital was unchanged'],'reserve_supply_vs_lending')
 ],
 legendary:[
  spec('A crisis program has two parts: the central bank lends temporarily against sound collateral to solvent banks, while the fiscal authority injects taxpayer capital into an insolvent institution. What principle best distinguishes the two actions?','Central-bank liquidity support addresses funding; fiscal recapitalization addresses losses and solvency',['Both actions are ordinary open-market operations because each changes a financial balance sheet','The central bank is conducting fiscal policy in both cases because all emergency lending uses tax revenue','The fiscal authority is acting as lender of last resort while the central bank is collecting taxes'],'liquidity_solvency'),
  spec('The central bank expands its balance sheet and reserve balances surge. Banks, however, tighten underwriting and firms postpone borrowing because sales prospects are weak. Which conclusion is strongest?','Creating reserves does not mechanically force commercial-bank lending or deposit expansion',['The central bank did not actually create reserves because bank lending failed to rise','Weak borrowing proves that commercial banks, not the central bank, issue reserve balances','The simple multiplier guarantees the same deposit expansion regardless of banks or borrowers'],'reserve_supply_vs_lending'),
  spec('A student argues that the Federal Reserve must be part of the Treasury because its actions can affect government-security markets. Which response is most accurate?','The Fed is a distinct central bank even though its operations can involve government securities',['The Fed is legally just a Treasury checking account because both institutions handle government securities','The Treasury conducts monetary policy whenever the Fed buys a government security','Government securities cannot appear on a central-bank balance sheet unless Congress sets the policy rate directly'],'fed_treasury_distinction')
 ],
 boss:[
  {...spec('Which statement correctly distinguishes the Federal Reserve from a commercial bank?','The Fed can create reserve balances; a commercial bank creates deposits when it makes loans',['The commercial bank creates Federal Reserve reserve liabilities for the payment system, while the Fed creates private bank capital for each lender','Both institutions issue only physical currency and neither creates account balances','The Fed accepts household checking deposits in the same way as a retail bank'],'central_commercial_money'),tier:'mediumBoss'},
  {...spec('Which statement best distinguishes the Federal Reserve from the U.S. Treasury?','The Fed conducts monetary policy; the Treasury manages federal finances and debt operations',['The Treasury conducts monetary policy and determines bank reserve conditions; the Fed sets federal tax rates for Congress','The two names refer to the same institution','The Fed manages congressional spending while the Treasury supplies bank reserves'],'fed_treasury_distinction'),tier:'mediumBoss'},
  {...spec('A central-bank committee decides to change monetary conditions. Which institutional description is most accurate?','The policy-making body chooses monetary actions within the central bank’s mandate',['The committee directly approves household mortgages at commercial banks','The committee determines federal tax rates and appropriations for the entire national budget','The committee measures M1 but has no connection to monetary policy'],'fed_treasury_distinction'),tier:'mediumBoss'},
  {...spec('A solvent bank cannot obtain overnight funding during a panic, while an insolvent bank has losses larger than its capital. Which central-bank principle is most important?','Liquidity lending can help the solvent bank, but it cannot by itself restore the insolvent bank’s capital',['Both problems are identical and can be solved by unlimited reserve creation','Only the insolvent bank qualifies for lender-of-last-resort support because it has larger losses','Neither bank can receive liquidity because central banks deal only with government budgets'],'liquidity_solvency'),tier:'finalBoss'},
  {...spec('The government establishes the central bank’s mandate, but elected officials cannot order a pre-election interest-rate change. The bank must explain its decisions publicly. What does this arrangement combine?','Instrument independence with democratic accountability',['Complete independence from any public mandate','Fiscal dominance with no central-bank discretion','Commercial-bank control of the monetary-policy mandate'],'independence_accountability'),tier:'finalBoss'},
  {...spec('The central bank adds reserves through an asset purchase, but banks and borrowers do not expand credit. What can still be said with confidence?','The central bank changed reserve conditions even though broader deposit creation did not respond mechanically',['The asset purchase could not have occurred because every reserve increase must create the maximum amount of loans','Commercial banks must have created the reserve balances before the central bank could buy the asset','The lack of new lending means the action was fiscal rather than monetary'],'reserve_supply_vs_lending'),tier:'finalBoss'}
 ],
 legendaryBoss:[
  spec('A commercial bank makes a loan by crediting a deposit, while the Federal Reserve supplies reserve balances to banks. Which statement best separates the two forms of money creation?','Commercial banks create deposits; the central bank creates reserves and base money',['Commercial banks issue reserve balances; the central bank issues all checking deposits','Both institutions can create only physical currency','Neither institution can create a financial liability'],'central_commercial_money',{bossStage:'opening'}),
  spec('A bank is solvent but temporarily unable to meet payments because short-term funding markets freeze. Which central-bank response best fits the lender-of-last-resort principle?','Provide temporary liquidity against sound collateral to an otherwise solvent bank',['Use tax revenue to replace every risky bank asset permanently','Refuse all liquidity because a funding shortage proves assets are worthless','Order the Treasury to guarantee every future bank loss'],'liquidity_solvency',{bossStage:'middle'})
 ]
};

// -----------------------------------------------------------------------------
// E. Monetary Control Limits structural additions: +7.
// -----------------------------------------------------------------------------
const limits={
 medium:[
  spec('The central bank supplies ample reserves and banks are willing to lend, but households and firms become reluctant to borrow. What happens to deposit creation relative to the simple multiplier maximum?','Weak loan demand can keep deposit creation below the simple-multiplier maximum',['It must equal the maximum because reserve supply alone determines every loan','It must exceed the maximum because unborrowed reserves count twice','It becomes fiscal policy because borrowers are not requesting loans'],'weak_loan_demand')
 ],
 boss:[
  {...spec('The central bank adds reserves, but banks choose to hold much of them as excess reserves. What is the likely result?','Broad deposit creation is smaller than the simple multiplier maximum',['Deposit creation must equal the maximum because reserves increased','The money supply must fall by the amount of the reserve injection','Required reserves disappear from bank balance sheets'],'limits_of_monetary_control'),tier:'mediumBoss'},
  {...spec('Households convert part of each new bank deposit into currency rather than leaving the funds in banks. What happens to the deposit-multiplication process?','It weakens because less money is redeposited into banks for additional lending',['It strengthens because currency held by the public becomes excess reserves','It is unchanged because currency and bank reserves are identical','It guarantees a larger simple multiplier regardless of the reserve ratio'],'limits_of_monetary_control'),tier:'mediumBoss'},
  {...spec('Banks have ample reserves and are willing to lend, but creditworthy firms postpone borrowing during a severe slump. Which limitation is illustrated?','Weak loan demand can keep money creation below the textbook maximum',['The central bank has lost the legal authority to create reserves','Household currency holdings must have fallen to zero','Bank capital automatically rises whenever firms reject loans'],'weak_loan_demand'),tier:'mediumBoss'},
  {...spec('After a reserve injection, banks hold extra reserves, the public keeps some loan proceeds as currency, and firms reduce borrowing. Relative to the simple multiplier model, what should we expect?','A substantially smaller expansion because several leakages interrupt repeated lending and redepositing',['The exact simple multiplier maximum because the three effects cancel automatically','A larger expansion because every leakage creates additional bank reserves','No change in broad money because reserve injections affect only bank capital'],'limits_of_monetary_control'),tier:'finalBoss'},
  {...spec('Which statement best describes what the central bank controls most directly?','Its own balance sheet and reserve conditions, not the exact final quantity of broad money',['The exact quantity of bank loans made to every borrower','The public’s desired split between currency and deposits','The amount every commercial bank must want to lend regardless of risk'],'limits_of_monetary_control'),tier:'finalBoss'},
  {...spec('The central bank lowers a policy-related borrowing rate, but banks still see borrowers as risky and firms do not want new loans. Why can the monetary response remain weak?','Cheaper central-bank liquidity does not eliminate bank risk concerns or weak credit demand',['A lower central-bank lending rate automatically raises required reserves','The policy turns into a tax change when private borrowing is weak','Commercial banks are legally required to stop lending whenever the central bank lowers a rate'],'weak_loan_demand'),tier:'finalBoss'}
 ]
};

for(const [pool,specs] of Object.entries(central))specs.forEach((item,index)=>addQuestion('central-bank-and-federal-reserve',pool,item,index));
for(const [pool,specs] of Object.entries(limits))specs.forEach((item,index)=>addQuestion('monetary-control-limits',pool,item,index));

// -----------------------------------------------------------------------------
// F. Repair every pre-existing F5 Legendary Boss stage. Question content is
// preserved. New Central Bank LB records already carry valid stages.
// -----------------------------------------------------------------------------
const stageAssignments={
 'money-functions-and-measures':{
  'P52B-S3-MFM-LB-002':'opening','P52B-S3-MFM-LB-001':'middle','LG-Q-9110':'final'
 },
 'bank-money-creation':{
  'LG-Q-9105':'opening','LG-Q-9102':'middle','LG-Q-9112':'middle','LG-Q-9109':'final','LG-Q-9104':'final'
 },
 'central-bank-and-federal-reserve':{'LG-Q-9111':'final'},
 'monetary-policy-tools':{
  'LG-Q-9113':'opening','LG-Q-9100':'middle','LG-Q-9107':'final','LG-Q-9103':'final'
 },
 'monetary-control-limits':{
  'LG-Q-9114':'opening','LG-Q-9101':'middle','LG-Q-9106':'middle','LG-Q-9108':'final'
 }
};
for(const [conceptId,map] of Object.entries(stageAssignments))for(const [id,stage] of Object.entries(map)){
 const {pool,question:q}=findQuestion(conceptId,id);if(pool!=='legendaryBoss')throw new Error(`${id} is not legendaryBoss`);const before=q.bossStage;metadataUpdate(conceptId,id,{bossStage:stage},`Assigns semantically appropriate ${stage} stage without changing question content.`,'BOSS_STAGE_FIX');const last=changes.at(-1);last.beforeBossStage=before??null;last.afterBossStage=stage;
}

const afterCounts=Object.fromEntries(familyIds.map(id=>[id,countModule(library.concepts[id])]));
const expected={
 'money-functions-and-measures':{total:66,easy:12,medium:8,hard:6,elite:4,legendary:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:3,repair:11,bridge:4},
 'bank-money-creation':{total:90,easy:6,medium:6,hard:6,elite:13,legendary:7,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:5,repair:10,bridge:6},
 'central-bank-and-federal-reserve':{total:50,easy:7,medium:6,hard:6,elite:2,legendary:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:3,repair:8,bridge:3},
 'monetary-policy-tools':{total:60,easy:7,medium:8,hard:6,elite:8,legendary:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:4,repair:7,bridge:3},
 'monetary-control-limits':{total:60,easy:6,medium:6,hard:9,elite:9,legendary:8,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:4,repair:4,bridge:3}
};
for(const [conceptId,target] of Object.entries(expected))for(const [key,value] of Object.entries(target))if(afterCounts[conceptId][key]!==value)throw new Error(`Count mismatch ${conceptId} ${key}: ${afterCounts[conceptId][key]} != ${value}`);
const added=changes.filter(c=>c.action==='ADD').length;if(added!==22)throw new Error(`Expected 22 additions; got ${added}`);
const bossStageFixed=changes.filter(c=>c.action==='BOSS_STAGE_FIX').length;if(bossStageFixed!==17)throw new Error(`Expected 17 bossStage fixes; got ${bossStageFixed}`);

// Quality checks for introduced/reworked stems.
const changedContentIds=new Set(changes.filter(c=>['ADD','QUALITY_REWRITE','REPAIR_REWRITE','BRIDGE_REWRITE'].includes(c.action)).map(c=>c.questionId));
const allF5=familyIds.flatMap(conceptId=>unique(library.concepts[conceptId]).map(({pool,question})=>({conceptId,pool,question})));
const normalize=t=>String(t||'').toLowerCase().replace(/[^a-z0-9%]+/g,' ').replace(/\s+/g,' ').trim();
const stemMap=new Map(),templateMap=new Map(),introducedExact=[],introducedNumberSwaps=[];
for(const row of allF5){const id=qid(row.question),stem=normalize(row.question.q),tpl=stem.replace(/\b\d+(?:[.,]\d+)?%?\b/g,'#');if(stemMap.has(stem)&&(changedContentIds.has(id)||changedContentIds.has(stemMap.get(stem))))introducedExact.push([stemMap.get(stem),id]);else if(!stemMap.has(stem))stemMap.set(stem,id);if(templateMap.has(tpl)&&(changedContentIds.has(id)||changedContentIds.has(templateMap.get(tpl))))introducedNumberSwaps.push([templateMap.get(tpl),id]);else if(!templateMap.has(tpl))templateMap.set(tpl,id);}
if(introducedExact.length)throw new Error(`Introduced exact duplicates: ${JSON.stringify(introducedExact)}`);
if(introducedNumberSwaps.length)throw new Error(`Introduced number-swap templates: ${JSON.stringify(introducedNumberSwaps)}`);
function wordCount(text){return String(text||'').trim().split(/\s+/).filter(Boolean).length;}
const lengthIssues=[];
for(const conceptId of familyIds){const groups={};for(const {pool,question} of unique(library.concepts[conceptId]))if(changedContentIds.has(qid(question))){const group=pool==='boss'?question.difficulty:pool;const correct=(question.options||[]).find(option=>answerHash(option)===question.aHash),dist=(question.options||[]).filter(option=>option!==correct);(groups[group]||=[]).push({correct:wordCount(correct),dist:dist.map(wordCount)});}for(const [group,rows] of Object.entries(groups)){const longest=rows.filter(r=>r.dist.every(n=>r.correct>n)).length/rows.length,cm=rows.reduce((a,r)=>a+r.correct,0)/rows.length,dm=rows.reduce((a,r)=>a+r.dist.reduce((x,y)=>x+y,0)/r.dist.length,0)/rows.length,ratio=cm/dm;if(longest>.5||ratio>1.45)lengthIssues.push({conceptId,group,longest:Number(longest.toFixed(3)),ratio:Number(ratio.toFixed(3))});}}
if(lengthIssues.length)throw new Error(`Answer-length issue: ${JSON.stringify(lengthIssues)}`);

// Protected non-F5 integrity.
const protectedAfter=Object.fromEntries(protectedIds.map(id=>[id,bankHash(library.concepts[id])]));
const protectedMismatches=protectedIds.filter(id=>protectedAfter[id]!==protectedBefore[id]);if(protectedMismatches.length)throw new Error(`Protected non-F5 bank changed: ${protectedMismatches.join(', ')}`);

function calcLinked(q){return q.type==='calculation'||['calculate_m1_m2','calculate_m1_m2_reclassification','calculate_required_reserves','calculate_excess_reserves','calculate_money_multiplier_effect','bank_leverage_risk','solve_required_open_market_operation','calculate_new_excess_reserves','compare_simple_multiplier_to_actual_result'].includes(q.primarySkill)&&/\d/.test(String(q.q||''));}
function updateRegistryEntry(entry,module){const records=unique(module).map(item=>item.question),ordinary=['easy','medium','hard'].flatMap(pool=>module.questions[pool]||[]),boss=module.questions.boss||[];const roleCounts={boss:boss.length,bridge:(module.bridgeQuestions||[]).length,calculation:(module.questions.calculation||[]).length,elite:(module.questions.elite||[]).length,integration:(module.questions.integration||[]).length,legendary:(module.questions.legendary||[]).length,legendaryBoss:(module.questions.legendaryBoss||[]).length,main:ordinary.length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length};const diff={easy:(module.questions.easy||[]).length+boss.filter(q=>String(q.difficulty).toLowerCase()==='easyboss').length,medium:(module.questions.medium||[]).length+boss.filter(q=>String(q.difficulty).toLowerCase()==='mediumboss').length,hard:(module.questions.hard||[]).length+boss.filter(q=>['finalboss','hardboss'].includes(String(q.difficulty).toLowerCase())).length,elite:(module.questions.elite||[]).length,legendary:(module.questions.legendary||[]).length+(module.questions.legendaryBoss||[]).length,unknown:(module.repairQuestions||[]).length+(module.repairSeedQuestions||[]).length+(module.bridgeQuestions||[]).length};Object.assign(entry,{includedSkills:[...new Set(records.map(q=>q.primarySkill).filter(Boolean))].sort(),questionCountByRole:roleCounts,questionCountByDifficulty:diff,repairCoverage:{directSkillMatches:(module.repairQuestions||[]).length,mainWithUsableSkill:records.length},bridgeCoverage:{directSkillMatches:(module.bridgeQuestions||[]).length,mainWithUsableSkill:records.length},calculationCoverage:records.filter(calcLinked).length,instructionalClassification:'Engine-safe F5 Money, Banking, and Fed Operations family slice',coverageStatus:'ready-family-slice',coverageStatusLabel:'Engine-safe alone; strongest in F5 family sequence',coverageStatusNote:'Phase M2c-1 closes Central Bank and Control Limits structural floors, repairs Legendary boss stages, modernizes selected definition-heavy tasks, and creates genuine Money Measures → Banking → Fed → Tools → Limits routing.',coverageFloorVersion:PHASE,notes:'Money, Banking, and Fed Operations family slice. Large healthy banks are preserved; additions are concentrated only where measured structural gaps existed.'});}
for(const conceptId of familyIds)for(const list of [library.registry.concepts,registry.concepts]){const entry=list.find(item=>item.canonicalConceptId===conceptId);if(!entry)throw new Error(`Registry entry missing ${conceptId}`);updateRegistryEntry(entry,library.concepts[conceptId]);}

library.libraryVersion=`${previousVersion}-${PHASE}`;library.sourceCurationPhase=PHASE;library.generatedAt=STAMP;library.canonicalQuestionCount=Object.values(library.concepts).reduce((sum,module)=>sum+unique(module).length,0);
Object.assign(library.registry,{libraryVersion:library.libraryVersion,generatedAt:STAMP,canonicalQuestionCount:library.canonicalQuestionCount});Object.assign(registry,{libraryVersion:library.libraryVersion,generatedAt:STAMP,canonicalQuestionCount:library.canonicalQuestionCount});delete library.librarySha256;library.librarySha256=sha(JSON.stringify(stable(library)));registry.librarySha256=library.librarySha256;Object.assign(manifest,{canonicalQuestionCount:library.canonicalQuestionCount,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,generatedAt:STAMP});
const familyBefore=Object.values(beforeCounts).reduce((out,count)=>{for(const [key,value] of Object.entries(count))out[key]=(out[key]||0)+value;return out;},{}),familyAfter=Object.values(afterCounts).reduce((out,count)=>{for(const [key,value] of Object.entries(count))out[key]=(out[key]||0)+value;return out;},{});
if(familyBefore.total!==304||familyAfter.total!==326)throw new Error(`Unexpected F5 totals ${familyBefore.total} → ${familyAfter.total}`);
const provenance={phase:PHASE,generatedAt:STAMP,scope:{family:'F5 — Money, Banking, and Fed Operations',modifiedCanonicalConceptIds:modifiedIds,protectedCanonicalConceptIds:protectedIds},before:{libraryVersion:previousVersion,canonicalQuestionCount:beforeTotal,counts:beforeCounts,familyCounts:familyBefore},after:{libraryVersion:library.libraryVersion,canonicalQuestionCount:library.canonicalQuestionCount,librarySha256:library.librarySha256,counts:afterCounts,familyCounts:familyAfter},protectedSummary:{canonicalBanksChecked:protectedIds.length,nonF5Mismatches:protectedMismatches},quality:{introducedExact,introducedNumberSwaps,answerLengthIssues:lengthIssues}};
const sourceData={phase:PHASE,generatedAt:STAMP,scope:modifiedIds,changes,summary:{added,bossStageFixed,ordinaryRewritten:4,repairRewritten:7,repairMetadataFixed:1,bridgeRewritten:6,removed:0,relocated:0},authoringPolicy:{soloFloors:{easy:6,medium:6,hard:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendary:6,legendaryBoss:3,repair:1,bridge:1},targetRange:[326,331],actualFamilyTotal:familyAfter.total,noGraphExpansion:true,protectLargeHealthyBanks:true},quality:provenance.quality};

if(!dryRun){fs.writeFileSync(libraryPath,`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(library)};\n`);fs.writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(path.join(composer,`${PHASE}_questions.json`),JSON.stringify(sourceData,null,2)+'\n');fs.writeFileSync(path.join(composer,`${PHASE}.json`),JSON.stringify(provenance,null,2)+'\n');for(const file of [path.join(repo,'build','index.html'),path.join(composer,'index.html')])if(fs.existsSync(file)){const text=fs.readFileSync(file,'utf8').replaceAll('20260810-macro-m2b4-unemployment-v1','20260810-macro-m2c1-money-banking-fed-v1');fs.writeFileSync(file,text);}}
console.log(JSON.stringify({dryRun,phase:PHASE,beforeTotal,afterTotal:library.canonicalQuestionCount,added,bossStageFixed,beforeCounts,afterCounts,familyBefore,familyAfter,protectedMismatches,quality:{introducedExact,introducedNumberSwaps,lengthIssues},changeSummary:sourceData.summary},null,2));
