import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const repo=path.resolve(process.argv[2]||process.cwd());
const dryRun=process.argv.includes('--dry-run');
const PHASE='phaseM2c2-money-growth-inflation-neutrality-family-maturation-v1';
const STAMP=new Date().toISOString();
const SOURCE='macro-m2c2-money-growth-inflation-neutrality-family';
const familyIds=['quantity-theory-of-money','monetary-neutrality','fisher-effect','inflation-costs','inflation-tax-and-deflation'];
const modifiedIds=[...familyIds];
const modifiedSet=new Set(modifiedIds);
const composer=path.join(repo,'build','faculty-build-composer');
const dataDir=path.join(composer,'data');
const libraryPath=path.join(dataDir,'composer_library.js');
const registryPath=path.join(dataDir,'composer_registry.json');
const manifestPath=path.join(dataDir,'composer_library_manifest.json');
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])])):value;
const answerHash=answer=>sha(String(answer).trim().replace(/\s+/g,' ').toLowerCase());
const qid=q=>String(q?.canonicalId||q?.id||q?.questionId||'');
const questionHash=q=>sha(JSON.stringify(stable({q:q.q,options:q.options,aHash:q.aHash,primaryConceptId:q.primaryConceptId,primarySkill:q.primarySkill,repairSkill:q.repairSkill,difficulty:q.difficulty,secondaryConceptIds:q.secondaryConceptIds||[],bossStage:q.bossStage||null,image:q.image||null})));
const loadLibrary=raw=>{const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(raw,sandbox,{filename:libraryPath});return sandbox.window.MQ_COMPOSER_LIBRARY;};
const rawBefore=fs.readFileSync(libraryPath,'utf8');
const library=loadLibrary(rawBefore);
const registry=JSON.parse(fs.readFileSync(registryPath,'utf8'));
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
if(!String(library.libraryVersion).endsWith('phaseM2c1-money-banking-fed-family-maturation-v1'))throw new Error('Unexpected baseline: completed M2c-1 library required.');
for(const id of familyIds)if(!library.concepts[id])throw new Error(`Missing F6 concept ${id}`);

function tagged(module){return [...Object.entries(module.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(module.repairQuestions||[]).map(question=>({pool:'repair',question})),...(module.repairSeedQuestions||[]).map(question=>({pool:'repairSeed',question})),...(module.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))];}
function unique(module){const seen=new Set();return tagged(module).filter(({question})=>{const id=qid(question);if(seen.has(id))return false;seen.add(id);return true;});}
function bankSnapshot(module){return unique(module).map(({pool,question})=>({pool,id:qid(question),question:stable(question)})).sort((a,b)=>a.id.localeCompare(b.id));}
function bankHash(module){return sha(JSON.stringify(stable(bankSnapshot(module))));}
function countModule(module){const boss=module.questions?.boss||[];return{easy:(module.questions?.easy||[]).length,medium:(module.questions?.medium||[]).length,hard:(module.questions?.hard||[]).length,elite:(module.questions?.elite||[]).length,legendary:(module.questions?.legendary||[]).length,calculation:(module.questions?.calculation||[]).length,integration:(module.questions?.integration||[]).length,easyBoss:boss.filter(q=>String(q.difficulty).toLowerCase()==='easyboss').length,mediumBoss:boss.filter(q=>String(q.difficulty).toLowerCase()==='mediumboss').length,finalBoss:boss.filter(q=>['finalboss','hardboss'].includes(String(q.difficulty).toLowerCase())).length,legendaryBoss:(module.questions?.legendaryBoss||[]).length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length,bridge:(module.bridgeQuestions||[]).length,total:unique(module).length};}
const protectedIds=Object.keys(library.concepts).filter(id=>!modifiedSet.has(id));
const protectedBefore=Object.fromEntries(protectedIds.map(id=>[id,bankHash(library.concepts[id])]));
const beforeCounts=Object.fromEntries(familyIds.map(id=>[id,countModule(library.concepts[id])]));
const beforeTotal=library.canonicalQuestionCount;
const previousVersion=library.libraryVersion;
const changes=[];
let serial=8900000;

const meta={
 'quantity-theory-of-money':{code:'QTM',tag:'quantity_theory',objective:'LO31.1',chapter:[31,1],cluster:'inflation_money_growth'},
 'monetary-neutrality':{code:'NEUT',tag:'real_nominal_variables',objective:'LO31.2',chapter:[31,2],cluster:'inflation_money_growth'},
 'fisher-effect':{code:'FISH',tag:'fisher_effect',objective:'LO31.3',chapter:[31],cluster:'inflation_money_growth'},
 'inflation-costs':{code:'ICOST',tag:'inflation_costs',objective:'LO31.4',chapter:[31,4],cluster:'inflation_money_growth'},
 'inflation-tax-and-deflation':{code:'ITAX',tag:'inflation_policy',objective:'31.5',chapter:[31],cluster:'inflation_policy_implications'}
};
const lessonMap={
 long_run_neutrality_boundary:['Treats monetary neutrality as a claim that money can never affect real activity.','Monetary neutrality is a long-run proposition: nominal variables can change while real output and other real variables return to levels determined by real factors.'],
 nominal_real_adjustment:['Compares dollar values without adjusting for the price level.','Separate nominal from real variables. A proportional change in nominal wages and prices can leave purchasing power unchanged.'],
 neutrality_level_vs_growth:['Treats a one-time nominal level change as permanent real growth.','A one-time monetary expansion can raise nominal levels; long-run real growth requires changes in real productive capacity.'],
 fisher_expected_inflation:['Uses actual inflation instead of expected inflation when applying the Fisher effect.','The Fisher effect links expected inflation to the nominal interest rate, holding the underlying real interest rate constant in the long-run comparison.'],
 fisher_holding_real_rate:['Assumes nominal rates must move one-for-one with expected inflation even when the real rate also changes.','The one-for-one Fisher prediction requires holding the real interest rate fixed; if the real rate changes too, combine both changes.'],
 fisher_ex_ante_contract:['Uses realized inflation to explain a nominal rate chosen before the loan was made.','The nominal rate written into a contract reflects expected inflation at the time the contract is set; realized inflation determines the ex post real return.'],
 expected_inflation_costs:['Assumes perfectly anticipated inflation has no resource cost.','Expected inflation can still create shoeleather, menu, tax-system, and relative-price costs even when debtor-creditor redistribution is reduced.'],
 unexpected_inflation_redistribution:['Ignores that unexpected inflation changes the realized real value of fixed nominal payments.','Unexpected inflation redistributes purchasing power between parties to fixed nominal contracts because the realized price level differs from what they expected.'],
 inflation_cost_mechanism:['Labels inflation as costly without identifying the mechanism.','Identify the channel: cash-management effort, repricing, relative-price confusion, tax distortions, or unexpected redistribution.'],
 inflation_tax_mechanism:['Treats the inflation tax as a statutory tax bill.','Money-financed government spending can erode the purchasing power of existing money balances; that loss is called the inflation tax.'],
 disinflation_vs_deflation:['Confuses a slower increase in prices with an actual decline in the price level.','Disinflation means the inflation rate falls while remaining positive; deflation means the overall price level is falling.'],
 deflation_debt_burden:['Assumes falling prices reduce the real burden of fixed nominal debt.','Deflation raises the purchasing power of each dollar, increasing the real burden of fixed nominal debt and favoring creditors relative to debtors.'],
 seigniorage_feedback:['Treats money creation as a costless financing source regardless of public money demand.','Heavy money finance can raise inflation expectations and reduce desired real money balances, making continued reliance on seigniorage increasingly disruptive.'],
 bridge_quantity_neutrality:['Stops after predicting the price-level effect and does not separate nominal from real outcomes.','Use the quantity-theory result for nominal spending/prices, then apply long-run neutrality to ask which real variables need not rise permanently.'],
 bridge_neutrality_fisher:['Recognizes nominal neutrality but does not connect expected inflation to nominal interest rates.','Once long-run real and nominal variables are separated, the Fisher effect explains why higher expected inflation is reflected in higher nominal interest rates.']
};
function lesson(skill){return lessonMap[skill]||['Uses a memorized label without tracing the long-run money, inflation, interest-rate, or purchasing-power mechanism.','Identify the expected versus actual change, separate nominal from real variables, and trace the mechanism before choosing the answer.'];}
function rotate(options,answer,index){const n=index%options.length;const out=options.slice(n).concat(options.slice(0,n));if(!out.includes(answer))throw new Error(`Answer missing: ${answer}`);return out;}
function spec(stem,answer,wrong,skill,extra={}){return{stem,answer,options:[answer,...wrong],skill,...extra};}
function addQuestion(conceptId,pool,s,index){const module=library.concepts[conceptId],boss=pool==='boss',lb=pool==='legendaryBoss',tier=boss?s.tier:null,canonicalDifficulty=boss?({easyBoss:'easy',mediumBoss:'medium',finalBoss:'hard'})[tier]:lb?'legendary':pool,marker=boss?({easyBoss:'EB',mediumBoss:'MB',finalBoss:'FB'})[tier]:({easy:'E',medium:'M',hard:'H',legendary:'L',legendaryBoss:'LB'})[pool],m=meta[conceptId];const id=`PM2C2-${m.code}-${marker}-${String(index+1).padStart(3,'0')}`;const [commonError,feedback]=lesson(s.skill);const q={id,sourceGame:SOURCE,q:s.stem,options:rotate(s.options,s.answer,index),tag:m.tag,type:s.type||'application',objective:m.objective,difficulty:boss?tier:lb?'legendaryBoss':pool,conceptCluster:m.cluster,primarySkill:s.skill,secondarySkills:s.secondarySkills||[],repairSkill:s.repairSkill||s.skill,commonError:s.commonError||commonError,feedback:s.feedback||feedback,aHash:answerHash(s.answer),canonicalId:id,sourceId:++serial,sourceChapter:m.chapter,sourcePool:boss?tier:s.skill,primaryConceptId:conceptId,secondaryConceptIds:s.secondaryConceptIds||[],instructionalRole:boss?'boss':lb?'legendaryBoss':pool,canonicalDifficulty,originalSourcePool:boss?tier:s.skill,originalBossTier:boss?tier:lb?'legendaryBoss':null,sourceCurationPhase:PHASE};if(boss)q.boss=({easyBoss:'Checkpoint One',mediumBoss:'Checkpoint Two',finalBoss:'Final Checkpoint'})[tier];if(lb)q.bossStage=s.bossStage;q.sourceHash=questionHash(q);q.sourceOccurrences=[{sourceGame:SOURCE,sourceFile:`${PHASE}_questions.json`,sourceGlobal:'questions',sourcePool:q.sourcePool,routeKey:q.primarySkill,sourceRecordOrder:index,sourceId:q.sourceId,sourceHash:q.sourceHash,sourceCurationPhase:PHASE}];if(boss)module.questions.boss.push(q);else module.questions[pool].push(q);changes.push({questionId:id,canonicalConceptId:conceptId,action:'ADD',oldPool:null,newPool:boss?tier:pool,reason:s.reason||'Closes a verified F6 structural gap with a distinct long-run money/inflation task.'});return q;}
function addBridge(conceptId,s,index){const module=library.concepts[conceptId],m=meta[conceptId],id=`PM2C2-${m.code}-BR-${String(index+1).padStart(3,'0')}`,[commonError,feedback]=lesson(s.skill);const q={id,sourceGame:SOURCE,q:s.stem,options:rotate(s.options,s.answer,index),tag:m.tag,type:s.type||'application',objective:m.objective,difficulty:'elite',conceptCluster:m.cluster,primarySkill:s.skill,secondarySkills:s.secondarySkills||[],repairSkill:s.repairSkill||s.skill,commonError:s.commonError||commonError,feedback:s.feedback||feedback,aHash:answerHash(s.answer),canonicalId:id,sourceId:++serial,sourceChapter:m.chapter,sourcePool:s.skill,primaryConceptId:conceptId,secondaryConceptIds:s.secondaryConceptIds||[],instructionalRole:'bridge',canonicalDifficulty:'elite',originalSourcePool:s.skill,originalBossTier:null,sourceCurationPhase:PHASE};q.sourceHash=questionHash(q);q.sourceOccurrences=[{sourceGame:SOURCE,sourceFile:`${PHASE}_questions.json`,sourceGlobal:'questions',sourcePool:q.sourcePool,routeKey:q.primarySkill,sourceRecordOrder:index,sourceId:q.sourceId,sourceHash:q.sourceHash,sourceCurationPhase:PHASE}];module.bridgeQuestions.push(q);module.microSkillBridgePools ||= {};const routeKey=q.repairSkill||q.primarySkill;(module.microSkillBridgePools[routeKey] ||= []).push(q.id);changes.push({questionId:id,canonicalConceptId:conceptId,action:'ADD',oldPool:null,newPool:'bridge',reason:'Adds a genuine cross-concept F6 recovery connection.'});return q;}
function findQuestion(conceptId,id){for(const row of tagged(library.concepts[conceptId]))if(qid(row.question)===id)return row;throw new Error(`Question not found ${conceptId}/${id}`);}
function setSourceHash(q){q.sourceCurationPhase=PHASE;q.sourceHash=questionHash(q);if(Array.isArray(q.sourceOccurrences)&&q.sourceOccurrences[0]){q.sourceOccurrences[0].sourceHash=q.sourceHash;q.sourceOccurrences[0].sourceCurationPhase=PHASE;}}
function rewrite(conceptId,id,s,reason,action='QUALITY_REWRITE'){const {pool,question:q}=findQuestion(conceptId,id),beforeHash=questionHash(q),oldSkill=q.primarySkill,oldRepairSkill=q.repairSkill;q.q=s.stem;q.options=rotate(s.options,s.answer,0);q.aHash=answerHash(s.answer);q.primarySkill=s.skill||q.primarySkill;q.repairSkill=s.repairSkill||s.skill||q.repairSkill;q.secondaryConceptIds=s.secondaryConceptIds||[];q.secondarySkills=s.secondarySkills||[];q.type=s.type||q.type||'application';const [commonError,feedback]=lesson(q.primarySkill);q.commonError=s.commonError||commonError;q.feedback=s.feedback||feedback;setSourceHash(q);changes.push({questionId:id,canonicalConceptId:conceptId,action,oldPool:pool,newPool:pool,reason,beforeHash,afterHash:questionHash(q),oldSkill,newSkill:q.primarySkill,oldRepairSkill,newRepairSkill:q.repairSkill});}
function metadataUpdate(conceptId,id,patch,reason,action='METADATA_FIX'){const {pool,question:q}=findQuestion(conceptId,id),beforeHash=questionHash(q);Object.assign(q,patch);setSourceHash(q);changes.push({questionId:id,canonicalConceptId:conceptId,action,oldPool:pool,newPool:pool,reason,beforeHash,afterHash:questionHash(q)});}

// Targeted Repair rewrites. Quantity Theory is content-protected.
rewrite('monetary-neutrality','ECON-SP-MONETARY-NEUTRALITY-5019',spec('A student says, “If money is neutral, monetary policy can never affect real output.” What is the best correction?','Neutrality is a long-run claim; short-run real effects can occur even if long-run real output returns to a level set by real factors.',['Neutrality means money changes only real output and never prices at any horizon, so even temporary short-run changes in prices, spending, or production cannot occur.','Neutrality applies only during recessions, not in long-run comparisons of nominal and real economic variables.','Neutrality means every monetary-policy action has exactly zero effect on prices, output, employment, and interest rates at every horizon.'],'long_run_neutrality_boundary'),'Clarifies the long-run neutrality boundary instead of rewarding a memorized definition.','REPAIR_REWRITE');
rewrite('fisher-effect','ECON-SP-FISHER-EFFECT-5020',spec('A borrower says the Fisher effect is found by subtracting this year’s actual inflation from a loan rate set last year. What is the key mistake?','The Fisher effect concerns expected inflation when the nominal rate is set, not merely realized inflation afterward.',['The Fisher effect uses only the unemployment rate when a loan is made, so expected inflation has no role in nominal-rate setting.','The Fisher effect requires nominal rates to stay fixed when expected inflation changes.','The Fisher effect says actual inflation and expected inflation must always be identical.'],'fisher_expected_inflation'),'Repairs the expected-versus-actual inflation misconception at the core of the Fisher effect.','REPAIR_REWRITE');
rewrite('inflation-costs','LG-R-5036',spec('A student says, “If everyone correctly expects 6 percent inflation, inflation has no economic costs.” Which response is best?','Anticipation reduces some redistribution, but cash-management, repricing, tax, and relative-price costs can remain.',['Correct; expected inflation removes every resource and information cost.','Correct; only unexpected deflation can create economic costs.','Incorrect only because expected inflation always lowers real GDP by exactly 6 percent and therefore creates a predictable recession every year.'],'expected_inflation_costs'),'Repairs the misconception that anticipated inflation is automatically costless.','REPAIR_REWRITE');
rewrite('inflation-tax-and-deflation','ECON-SP-INFLATION-TAX-5023',spec('A student looks for an “inflation tax” line on a tax return. What is the best correction?','The inflation tax is the loss of purchasing power on money balances when money-financed spending contributes to inflation.',['It is a statutory percentage surcharge collected only from commercial banks whenever the central bank expands the money supply to finance government spending.','It is the interest payment the Treasury makes on government bonds.','It is the fall in real debt burdens caused by unexpected deflation.'],'inflation_tax_mechanism'),'Clarifies that the inflation tax is an erosion of real money balances rather than a statutory tax bill.','REPAIR_REWRITE');

// Strengthen an existing Inflation Tax bridge into a genuine Costs → Inflation Tax connection.
rewrite('inflation-tax-and-deflation','LG-B-6016',spec('A government relies heavily on money creation. Inflation rises, households reduce cash balances, and they make more frequent transfers to avoid holding money. Which connection is most accurate?','Money finance creates an inflation-tax burden on money balances and also generates shoeleather costs.',['Money finance eliminates the inflation tax because households hold less cash.','Shoeleather costs occur only during deflation, so the two effects cannot occur together.','The policy changes only real output and has no effect on nominal money balances, cash-management decisions, or the purchasing power of money.'],'inflation_tax_mechanism',{secondaryConceptIds:['inflation-costs']}),'Creates a genuine Inflation Costs ↔ Inflation Tax conceptual bridge.','BRIDGE_REWRITE');

// Monetary Neutrality additions: +3 ordinary, +6 ordinary bosses, +1 LB.
const neutrality={
 easy:[
  spec('Over the long run, all dollar wages and prices are twice as high while output per worker and hours worked are unchanged. Which interpretation best fits monetary neutrality?','Nominal variables changed, but the listed real variables did not.',['Real variables doubled because every dollar price doubled.','Output per worker must have doubled because wages doubled.','The price level is a real variable, so nothing nominal changed.'],'nominal_real_adjustment')
 ],
 medium:[
  spec('After a sustained monetary expansion, the long-run price level is higher and nominal wages are higher by roughly the same proportion. What happens to the real wage if productivity is unchanged?','It can return to about its previous level because both the wage and price level rose together.',['It must rise in the same proportion as the nominal wage because a larger dollar wage always guarantees more purchasing power.','It must fall to zero because money growth raises prices.','It becomes equal to the money-supply growth rate.'],'nominal_real_adjustment')
 ],
 hard:[
  spec('A monetary expansion raises output temporarily, but years later output returns to its prior real trend while the price level remains permanently higher. Why is this consistent with monetary neutrality?','Neutrality describes the long-run separation of nominal changes from real output, not the absence of short-run real effects.',['Neutrality requires the price level to return fully to its original level after every monetary expansion, even in the long run.','Neutrality means real output must remain permanently above trend after money growth.','Neutrality applies only when both output and prices are unchanged at every horizon.'],'long_run_neutrality_boundary')
 ],
 boss:[
  {...spec('Which outcome is most consistent with long-run monetary neutrality after a one-time increase in the money supply?','A higher price level with real output determined by real productive factors.',['Permanently higher real output with no change in nominal prices.','Permanently lower prices because more money makes each dollar more valuable.','A permanently higher real wage solely because the number of dollars increased.'],'long_run_neutrality_boundary'),tier:'easyBoss'},
  {...spec('A worker’s nominal wage and the price level both rise 10 percent while productivity is unchanged. What happens to the worker’s real wage approximately?','It is roughly unchanged.',['It rises about 20 percent.','It rises exactly 10 percent.','It falls exactly 10 percent.'],'nominal_real_adjustment'),tier:'easyBoss'},
  {...spec('Which variable is nominal rather than real?','The dollar price of a haircut.',['The quantity of haircuts produced.','Hours of labor used to produce haircuts.','Haircuts produced per worker.'],'nominal_real_adjustment'),tier:'easyBoss'},
  {...spec('Money growth accelerates for several years. In the long-run neutrality framework, which comparison is most defensible?','Nominal prices can be persistently higher even though money growth does not permanently raise productive capacity.',['Productive capacity must rise one-for-one with the price level.','A higher price level proves long-run real output rose by the same percentage.','Neutrality requires money growth to leave every nominal price and wage unchanged in the long run.'],'neutrality_level_vs_growth'),tier:'finalBoss'},
  {...spec('A country redenominates so every old 100-unit price becomes 1 new unit, with contracts and wages converted proportionally. What has changed economically?','The nominal unit of account changed, while real quantities and relative prices need not change.',['Real output fell by 99 percent because smaller numbers on price tags necessarily mean less production.','Productivity rose because fewer currency units are needed per transaction.','The natural rate of unemployment must fall because nominal wages were converted.'],'nominal_real_adjustment'),tier:'finalBoss'},
  {...spec('The central bank unexpectedly expands money, real activity rises for a time, and later output returns to potential while nominal prices remain higher. Which statement best reconciles the episode?','Short-run real effects can coexist with long-run monetary neutrality.',['Long-run neutrality is disproved whenever any short-run real effect occurs.','Neutrality requires output to remain permanently above potential.','The episode can be neutral only if the price level eventually falls below its starting point.'],'long_run_neutrality_boundary'),tier:'finalBoss'}
 ],
 legendaryBoss:[
  spec('A country doubles the number of currency units used to quote every wage and price, while production technology, labor, and relative prices are unchanged. What is the best first inference?','The change is nominal; the economy has not doubled its real productive capacity.',['Real productive capacity doubled because every nominal amount doubled.','The natural rate of unemployment doubled because the currency unit changed.','The country necessarily experienced a permanent doubling of output per worker because every quoted nominal price and wage also doubled.'],'long_run_neutrality_boundary',{bossStage:'opening'})
 ]
};

// Fisher Effect additions: +10 ordinary, +2 Legendary, +6 ordinary bosses.
const fisher={
 easy:[
  spec('Lenders begin expecting inflation to be 4 percentage points higher, while the long-run real interest rate is unchanged. What does the Fisher effect predict?','Nominal interest rates tend to rise by about 4 percentage points.',['Nominal interest rates tend to fall by about 4 percentage points.','Real interest rates must rise by exactly 4 percentage points.','Actual inflation must immediately equal the new nominal interest rate.'],'fisher_expected_inflation'),
  spec('A bank sets a fixed nominal loan rate today for next year. Which inflation concept is most relevant to the Fisher effect when that rate is chosen?','Expected inflation over the loan period.',['Only inflation that has already occurred.','The current unemployment rate by itself.','Only the realized inflation rate known after repayment.'],'fisher_ex_ante_contract')
 ],
 medium:[
  spec('Two otherwise similar economies have the same long-run real interest rate, but expected inflation is 2 percent in one and 7 percent in the other. What should differ under the Fisher effect?','The second economy should tend to have a nominal interest rate about 5 percentage points higher.',['The first economy should have a nominal interest rate about 5 percentage points higher instead because lower expected inflation raises nominal rates.','Both nominal rates must be identical because real rates match.','The second economy must have a real rate 5 points higher.'],'fisher_expected_inflation'),
  spec('Expected inflation falls from 6 percent to 2 percent while the long-run real interest rate remains 3 percent. What nominal-rate change is predicted?','The nominal rate falls from about 9 percent to about 5 percent.',['The nominal rate rises from about 5 percent to about 9 percent.','The real rate falls from 3 percent to negative 1 percent automatically.','The nominal rate stays at 9 percent because only actual inflation matters.'],'fisher_expected_inflation'),
  spec('A one-year loan is priced when inflation is expected to be 3 percent. Actual inflation later turns out to be 8 percent. Which statement separates the Fisher effect from the realized return?','The nominal rate reflected expected inflation when set; the unexpectedly high actual inflation changes the ex post real return.',['The nominal rate must be rewritten after actual inflation is observed so the original expected rate no longer matters.','The Fisher effect uses actual inflation only and ignores expectations.','Unexpected inflation raises both parties’ realized real returns by the same amount.'],'fisher_ex_ante_contract')
 ],
 hard:[
  spec('Expected inflation rises 6 percentage points while the equilibrium real interest rate falls 2 percentage points. What happens to the nominal interest rate approximately?','It rises about 4 percentage points because both expected inflation and the real rate matter.',['It rises exactly 6 percentage points because the Fisher effect requires the real rate to remain fixed in every comparison.','It falls about 8 percentage points because expected inflation lowers nominal rates.','It is unchanged because the two components must always offset completely.'],'fisher_holding_real_rate'),
  spec('Country A has expected inflation of 8 percent and a real interest rate of 1 percent. Country B has expected inflation of 3 percent and a real interest rate of 5 percent. Which statement is correct?','A one-for-one comparison of nominal rates cannot use expected inflation alone because the real rates differ too.',['Country A must have a nominal rate exactly 5 points above Country B.','Country B must have the lower nominal interest rate because lower expected inflation always dominates any real-rate difference.','The Fisher effect says real interest rates are always identical across countries.'],'fisher_holding_real_rate'),
  spec('Expected inflation falls sharply after a credible long-run policy change, but productive opportunities and saving behavior leave the real rate roughly unchanged. What does the Fisher effect predict?','Nominal interest rates should fall as the inflation premium falls.',['Nominal interest rates should rise because lower expected inflation raises the inflation premium.','Real interest rates must fall by exactly the same amount as expected inflation.','Nominal rates should stay fixed because only realized inflation affects contracts.'],'fisher_expected_inflation'),
  spec('A lender receives a 10 percent nominal rate that was set when expected inflation was 4 percent. Actual inflation is later 9 percent. Which statement is most accurate?','The ex ante pricing reflected roughly a 6 percent real return, but the realized real return is much lower.',['The Fisher effect predicted a 1 percent real return when the loan was made.','The nominal rate automatically rises to 15 percent after inflation is observed because fixed-rate contracts always adjust retroactively after the fact.','Expected inflation is irrelevant once a fixed nominal rate has been written.'],'fisher_ex_ante_contract'),
  spec('Nominal interest rates rise from 7 to 11 percent at the same time expected inflation rises from 3 to 8 percent. Can we conclude the real rate was unchanged?','No. The nominal rate rose 4 points while expected inflation rose 5, so the implied real rate actually fell about 1 point.',['Yes. Any rise in nominal rates alongside expected inflation proves the real rate is unchanged.','Yes. The Fisher effect requires nominal rates to rise exactly half as much as expected inflation regardless of changes in real rates.','No. The implied real rate rose about 9 percentage points.'],'fisher_holding_real_rate')
 ],
 legendary:[
  spec('A country establishes a credible low-inflation regime. Expected inflation falls from 9 percent to 3 percent, while saving and investment conditions leave the long-run real interest rate near 2 percent. Which outcome best fits the Fisher effect?','The nominal interest rate tends to fall from about 11 percent to about 5 percent.',['The nominal interest rate tends to rise from about 5 percent to about 11 percent.','The real interest rate must fall from 2 percent to negative 4 percent.','The nominal interest rate should stay near 11 percent because credibility affects only actual inflation.'],'fisher_expected_inflation'),
  spec('Two long-run episodes have identical expected inflation, but the equilibrium real interest rate is higher in the second because investment demand is stronger. What should happen to the nominal rate?','It should also be higher, showing that Fisher comparisons must account for the real-rate component as well as expected inflation.',['It must be unchanged because identical expected inflation always forces identical nominal interest rates even when real saving and investment conditions differ.','It must be lower because stronger investment demand reduces nominal rates.','It must equal expected inflation because real rates disappear in the long run.'],'fisher_holding_real_rate')
 ],
 boss:[
  {...spec('If expected inflation rises while the long-run real interest rate is unchanged, the Fisher effect predicts that the nominal interest rate will:','Rise.',['Fall.','Remain fixed by definition.','Become equal to real GDP growth.'],'fisher_expected_inflation'),tier:'easyBoss'},
  {...spec('Which inflation rate matters when lenders set a nominal rate today for a future loan period?','Expected inflation.',['Only last year’s inflation.','Only inflation observed after repayment.','The unemployment rate instead of inflation.'],'fisher_ex_ante_contract'),tier:'easyBoss'},
  {...spec('The real interest rate is 3 percent and expected inflation is 5 percent. The Fisher approximation gives a nominal rate near:','8 percent.',['2 percent.','3 percent.','15 percent.'],'fisher_expected_inflation'),tier:'easyBoss'},
  {...spec('Expected inflation rises from 4 to 10 percent while the equilibrium real rate falls from 3 to 1 percent. What happens to the nominal rate approximately?','It rises from about 7 to about 11 percent.',['It rises from about 7 to about 13 percent because the real-rate change is irrelevant.','It falls from about 7 to about 5 percent.','It remains at about 7 percent because expected inflation and real rates always offset.'],'fisher_holding_real_rate'),tier:'finalBoss'},
  {...spec('A fixed-rate loan was written when expected inflation was 2 percent, but actual inflation turns out to be 8 percent. Which statement is correct?','Expected inflation helped determine the original nominal rate; the surprise changes the realized real return.',['The Fisher effect requires the bank to retroactively reset the nominal rate to actual inflation.','Unexpected inflation leaves the realized real return unchanged on a fixed-rate contract.','The nominal rate was based only on actual inflation, which was already known.'],'fisher_ex_ante_contract'),tier:'finalBoss'},
  {...spec('Nominal interest rates rise 3 percentage points while expected inflation rises 5 points. What does the Fisher decomposition imply about the real-rate component?','It fell by about 2 percentage points.',['It rose by about 8 percentage points.','It rose by exactly 5 percentage points.','It must have remained unchanged because nominal rates increased.'],'fisher_holding_real_rate'),tier:'finalBoss'}
 ]
};

// Inflation Costs additions: +2 ordinary, +1 Legendary, +6 ordinary bosses.
const costs={
 medium:[
  spec('Inflation is fully anticipated, so fixed-rate contracts are written with the expected inflation built in. Which cost can still remain?','Firms may still spend resources changing posted prices more often.',['Unexpected borrower-creditor redistribution must become larger even though the inflation rate was correctly anticipated by both sides.','The nominal interest rate must become zero.','All relative prices become permanently fixed.'],'expected_inflation_costs')
 ],
 hard:[
  spec('A fixed-rate lender expected 3 percent inflation, but actual inflation is 8 percent. At the same time firms repeatedly update prices. Which statement separates the two costs?','The inflation surprise redistributes toward the borrower, while repricing uses real resources even if inflation had been anticipated.',['Both effects are examples only of shoeleather costs.','The surprise benefits the lender, while repricing raises real output automatically.','Neither effect is an inflation cost unless the price level actually falls, because rising prices cannot redistribute purchasing power or use real resources.'],'unexpected_inflation_redistribution')
 ],
 legendary:[
  spec('A country perfectly indexes many long-term contracts to the price level, greatly reducing unexpected debtor-creditor redistribution. Inflation nevertheless remains high and predictable. Which conclusion is strongest?','Indexation can reduce redistribution without eliminating costs such as frequent repricing, cash management, or tax distortions.',['Once contracts are indexed, high expected inflation becomes economically costless.','Indexation guarantees the price level stops rising because once nominal contracts are indexed, firms and households no longer face any inflation-related decisions.','Indexation converts inflation into deflation by raising the real value of money.'],'expected_inflation_costs')
 ],
 boss:[
  {...spec('A store must repeatedly change price labels because the overall price level is rising. This is primarily a:','Menu cost.',['Shoeleather cost.','Natural-rate effect.','Money-multiplier effect.'],'inflation_cost_mechanism'),tier:'easyBoss'},
  {...spec('People make more frequent transfers so they can hold smaller cash balances during inflation. This is primarily a:','Shoeleather cost.',['Menu cost.','Fisher-effect premium.','Reserve requirement.'],'inflation_cost_mechanism'),tier:'easyBoss'},
  {...spec('Unexpected inflation is higher than lenders anticipated on fixed-rate loans. Who tends to gain?','Borrowers, because repayment dollars have less purchasing power than expected.',['Lenders, because inflation always raises realized real returns.','Both sides equally, because unexpected inflation cannot redistribute purchasing power.','Only the central bank, because private contracts are unaffected by inflation.'],'unexpected_inflation_redistribution'),tier:'easyBoss'},
  {...spec('Inflation is anticipated and nominal interest rates adjust, but firms still reprice frequently and households economize on cash balances. What does this show?','Expected inflation can still impose menu and shoeleather costs even when some redistribution is avoided.',['Expected inflation is costless whenever nominal interest rates adjust.','Menu and shoeleather costs occur only when inflation is unexpected.','Anticipated inflation necessarily increases real output enough to offset every menu, cash-management, and redistribution cost.'],'expected_inflation_costs'),tier:'finalBoss'},
  {...spec('A pension is fixed in nominal dollars and inflation is unexpectedly high. Which mechanism is most important?','The pension’s real purchasing power falls because the nominal payment buys less than expected.',['The pension automatically rises one-for-one because every fixed nominal contract is indexed against unexpected inflation.','The price level falls, increasing the pension’s real value.','The inflation surprise affects only banks, not recipients of fixed nominal payments.'],'unexpected_inflation_redistribution'),tier:'finalBoss'},
  {...spec('High inflation causes firms to reprice at different times, making it harder to distinguish relative-price changes from changes in the overall price level. Which cost is being described?','Relative-price variability and signal confusion.',['A larger money multiplier.','A lower natural unemployment rate by definition.','A statutory inflation-tax payment collected on a tax return.'],'inflation_cost_mechanism'),tier:'finalBoss'}
 ]
};

// Inflation Tax and Deflation additions: +3 ordinary, +3 Legendary, +6 ordinary bosses, +1 LB.
const taxdef={
 easy:[
  spec('A government creates money to finance purchases, the price level rises, and households’ existing cash buys less. What burden is illustrated?','The real purchasing power of money balances is being eroded by the inflation tax.',['A statutory income-tax rate automatically rose on every household.','Deflation increased the real value of cash balances.','The natural rate of unemployment fell permanently because the government created more money and raised the overall price level.'],'inflation_tax_mechanism')
 ],
 medium:[
  spec('Inflation falls from 7 percent to 2 percent, but the overall price level is still rising. Which description is correct?','The economy is experiencing disinflation, not deflation.',['The economy is experiencing deflation because inflation is lower.','The economy is experiencing hyperinflation because prices are still rising.','The price level must be falling by 5 percent.'],'disinflation_vs_deflation')
 ],
 hard:[
  spec('An economy enters unexpected deflation while households carry fixed nominal mortgage debt. What happens to the real debt burden, other things equal?','It rises because each repayment dollar has greater purchasing power.',['It falls because lower prices make nominal debts shrink automatically.','It is unchanged because the price level cannot affect fixed nominal contracts.','It disappears because deflation forces lenders to cancel nominal debt.'],'deflation_debt_burden')
 ],
 legendary:[
  spec('A government increasingly finances deficits by creating money. As inflation expectations rise, households try to hold smaller real money balances. Why can continued reliance on seigniorage become increasingly disruptive?','The shrinking demand to hold real balances can require still more money creation to extract a given amount of real resources, worsening inflation pressure.',['Lower money demand guarantees the government can finance the same amount of real spending with progressively less money creation and steadily less inflation forever.','Seigniorage becomes costless once households expect inflation.','The quantity theory implies real output must rise one-for-one with the extra money creation.'],'seigniorage_feedback'),
  spec('A heavily indebted economy experiences an unexpected 6 percent fall in the overall price level while nominal debts are fixed. Which balance-sheet effect is most likely?','Debtors face a higher real repayment burden, which can weaken spending and financial positions.',['Debtors receive an automatic reduction in the nominal face value of their debts.','Creditors lose because every repayment dollar is worth less in real terms.','The fall in the price level is disinflation and therefore cannot affect real debt burdens.'],'deflation_debt_burden'),
  spec('Inflation drops from 12 percent to 4 percent after a stabilization program, but the price level continues to rise. A student calls this deflation. What is the best evaluation?','The student is wrong: inflation slowed, but deflation requires the overall price level to fall.',['The student is correct because any decline in the inflation rate means the overall price level must also be falling.','The student is correct only if nominal interest rates also fall.','The student is wrong because disinflation requires inflation to become negative.'],'disinflation_vs_deflation')
 ],
 boss:[
  {...spec('When money-financed government spending reduces the purchasing power of existing money balances, the burden is called:','The inflation tax.',['Crowding out.','The money multiplier.','The natural rate.'],'inflation_tax_mechanism'),tier:'easyBoss'},
  {...spec('Inflation falls from 6 percent to 3 percent while prices continue to rise. This is:','Disinflation.',['Deflation.','Hyperinflation.','Monetary neutrality.'],'disinflation_vs_deflation'),tier:'easyBoss'},
  {...spec('If the overall price level falls, the value of money generally:','Rises.',['Falls.','Becomes zero.','Equals the inflation rate.'],'deflation_debt_burden'),tier:'easyBoss'},
  {...spec('A government prints money to finance spending, expected inflation rises, and households reduce desired real cash balances. Which concern is most complete?','Inflation-tax finance can erode real balances and become harder to sustain as people avoid holding money.',['Lower money demand guarantees a stable price level despite continued money creation.','Printing money eliminates the need to consider inflation because seigniorage is a real resource.','Households holding less money automatically raises real output enough to offset the inflation-tax burden and preserve seigniorage revenue.'],'seigniorage_feedback'),tier:'finalBoss'},
  {...spec('Unexpected deflation occurs while firms and households owe large fixed nominal debts. Which distributional effect is most likely?','The real burden shifts against debtors and toward creditors.',['The real burden shifts against creditors because repayment dollars buy less.','Both sides are unaffected because nominal debt cannot have a real value.','All nominal debts automatically fall at the same rate as the price level.'],'deflation_debt_burden'),tier:'finalBoss'},
  {...spec('A stabilization program reduces inflation from 20 percent to 5 percent without making inflation negative. Which statement is correct?','The program achieved disinflation; the price level can still be rising.',['The program created deflation because any large decline in the inflation rate makes the price level fall.','The price level must have fallen 15 percent.','Disinflation requires the inflation rate to be below zero.'],'disinflation_vs_deflation'),tier:'finalBoss'}
 ],
 legendaryBoss:[
  spec('A government finances part of its budget by creating money, and the public’s existing money balances lose purchasing power as prices rise. What is the core mechanism?','Money creation transfers real purchasing power away from holders of money balances through the inflation tax.',['A statutory tax authority directly debits an inflation-tax line from every bank account.','Deflation raises the real value of balances and transfers purchasing power to debtors.','The policy can finance the same amount of real spending indefinitely without reducing the purchasing power of existing money balances held by the public.'],'inflation_tax_mechanism',{bossStage:'opening'})
 ]
};

for(const [pool,specs] of Object.entries(neutrality))specs.forEach((item,index)=>addQuestion('monetary-neutrality',pool,item,index));
for(const [pool,specs] of Object.entries(fisher))specs.forEach((item,index)=>addQuestion('fisher-effect',pool,item,index));
for(const [pool,specs] of Object.entries(costs))specs.forEach((item,index)=>addQuestion('inflation-costs',pool,item,index));
for(const [pool,specs] of Object.entries(taxdef))specs.forEach((item,index)=>addQuestion('inflation-tax-and-deflation',pool,item,index));

// Two genuine family Bridges. They are owned by target slices so QTM remains content-protected.
addBridge('monetary-neutrality',spec('The quantity theory predicts that sustained money growth faster than real output growth can raise inflation. In the long-run neutrality framework, what should a student infer about real productive capacity?','Faster money growth can raise nominal prices without permanently increasing productive capacity.',['Faster money growth must permanently raise productive capacity by the same percentage.','Higher inflation proves output per worker rose by the same amount.','Long-run neutrality requires inflation to be zero whenever money growth exceeds output growth.'] ,'monetary_neutrality',{secondaryConceptIds:['quantity-theory-of-money'],commonError:'Stops after predicting the price-level effect and does not separate nominal from real outcomes.',feedback:'Use the quantity-theory result for nominal spending and prices, then apply long-run neutrality to ask which real variables need not rise permanently.'}),0);
addBridge('fisher-effect',spec('Suppose long-run money growth raises expected inflation while real productive conditions leave the real interest rate unchanged. Which next step connects monetary neutrality to the Fisher effect?','The nominal interest rate rises to incorporate the higher expected inflation while the real-rate component stays unchanged.',['The real interest rate must rise one-for-one because all nominal variables are neutral and expected inflation cannot influence nominal contract rates.','The nominal interest rate stays fixed because expected inflation affects only the price level.','Actual inflation must be known before lenders can set any nominal interest rate.'] ,'fisher_effect',{secondaryConceptIds:['monetary-neutrality'],commonError:'Recognizes nominal neutrality but does not connect expected inflation to nominal interest rates.',feedback:'Once long-run real and nominal variables are separated, the Fisher effect explains why higher expected inflation is reflected in higher nominal interest rates.'}),0);

// Repair all 15 pre-existing F6 Legendary Boss stages. Content remains unchanged.
const stageAssignments={
 'quantity-theory-of-money':{'LG-Q-9126':'opening','LG-Q-9116':'middle','LG-Q-9118':'middle','LG-Q-9122':'final'},
 'monetary-neutrality':{'LG-Q-9115':'middle','LG-Q-9123':'final'},
 'fisher-effect':{'LG-Q-9117':'opening','LG-Q-9128':'middle','LG-Q-9127':'final'},
 'inflation-costs':{'LG-Q-9120':'opening','LG-Q-9125':'middle','LG-Q-9119':'middle','LG-Q-9129':'final'},
 'inflation-tax-and-deflation':{'LG-Q-9121':'middle','LG-Q-9124':'final'}
};
for(const [conceptId,map] of Object.entries(stageAssignments))for(const [id,stage] of Object.entries(map)){const {pool,question:q}=findQuestion(conceptId,id);if(pool!=='legendaryBoss')throw new Error(`${id} is not legendaryBoss`);const before=q.bossStage;metadataUpdate(conceptId,id,{bossStage:stage},`Assigns semantically appropriate ${stage} stage without changing question content.`,'BOSS_STAGE_FIX');const last=changes.at(-1);last.beforeBossStage=before??null;last.afterBossStage=stage;}

const afterCounts=Object.fromEntries(familyIds.map(id=>[id,countModule(library.concepts[id])]));
const expected={
 'quantity-theory-of-money':{total:81,easy:9,medium:7,hard:6,elite:12,legendary:9,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:4,repair:8,bridge:5},
 'monetary-neutrality':{total:62,easy:10,medium:5,hard:6,elite:6,legendary:7,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:3,repair:7,bridge:5},
 'fisher-effect':{total:52,easy:7,medium:4,hard:5,elite:3,legendary:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:3,repair:4,bridge:3},
 'inflation-costs':{total:58,easy:6,medium:8,hard:8,elite:6,legendary:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:4,repair:7,bridge:4},
 'inflation-tax-and-deflation':{total:48,easy:6,medium:6,hard:6,elite:6,legendary:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:3,repair:3,bridge:2}
};
for(const [conceptId,target] of Object.entries(expected))for(const [key,value] of Object.entries(target))if(afterCounts[conceptId][key]!==value)throw new Error(`Count mismatch ${conceptId} ${key}: ${afterCounts[conceptId][key]} != ${value}`);
const added=changes.filter(c=>c.action==='ADD').length;if(added!==52)throw new Error(`Expected 52 additions; got ${added}`);
const bossStageFixed=changes.filter(c=>c.action==='BOSS_STAGE_FIX').length;if(bossStageFixed!==15)throw new Error(`Expected 15 bossStage fixes; got ${bossStageFixed}`);

// Quality checks for introduced/reworked stems.
const changedContentIds=new Set(changes.filter(c=>['ADD','QUALITY_REWRITE','REPAIR_REWRITE','BRIDGE_REWRITE'].includes(c.action)).map(c=>c.questionId));
const allF6=familyIds.flatMap(conceptId=>unique(library.concepts[conceptId]).map(({pool,question})=>({conceptId,pool,question})));
const normalize=t=>String(t||'').toLowerCase().replace(/[^a-z0-9%]+/g,' ').replace(/\s+/g,' ').trim();
const stemMap=new Map(),templateMap=new Map(),introducedExact=[],introducedNumberSwaps=[];
for(const row of allF6){const id=qid(row.question),stem=normalize(row.question.q),tpl=stem.replace(/\b\d+(?:[.,]\d+)?%?\b/g,'#');if(stemMap.has(stem)&&(changedContentIds.has(id)||changedContentIds.has(stemMap.get(stem))))introducedExact.push([stemMap.get(stem),id]);else if(!stemMap.has(stem))stemMap.set(stem,id);if(templateMap.has(tpl)&&(changedContentIds.has(id)||changedContentIds.has(templateMap.get(tpl))))introducedNumberSwaps.push([templateMap.get(tpl),id]);else if(!templateMap.has(tpl))templateMap.set(tpl,id);}
if(introducedExact.length)throw new Error(`Introduced exact duplicates: ${JSON.stringify(introducedExact)}`);
if(introducedNumberSwaps.length)throw new Error(`Introduced number-swap templates: ${JSON.stringify(introducedNumberSwaps)}`);
function wordCount(text){return String(text||'').trim().split(/\s+/).filter(Boolean).length;}
const lengthIssues=[];
for(const conceptId of familyIds){const groups={};for(const {pool,question} of unique(library.concepts[conceptId]))if(changedContentIds.has(qid(question))){const group=pool==='boss'?question.difficulty:pool;const correct=(question.options||[]).find(option=>answerHash(option)===question.aHash),dist=(question.options||[]).filter(option=>option!==correct);(groups[group]||=[]).push({correct:wordCount(correct),dist:dist.map(wordCount)});}for(const [group,rows] of Object.entries(groups)){const longest=rows.filter(r=>r.dist.every(n=>r.correct>n)).length/rows.length,cm=rows.reduce((a,r)=>a+r.correct,0)/rows.length,dm=rows.reduce((a,r)=>a+r.dist.reduce((x,y)=>x+y,0)/r.dist.length,0)/rows.length,ratio=cm/dm;if(rows.length>=2&&(longest>.6||ratio>1.6))lengthIssues.push({conceptId,group,longest:Number(longest.toFixed(3)),ratio:Number(ratio.toFixed(3))});}}
if(lengthIssues.length)throw new Error(`Answer-length issue: ${JSON.stringify(lengthIssues)}`);

const protectedAfter=Object.fromEntries(protectedIds.map(id=>[id,bankHash(library.concepts[id])]));
const protectedMismatches=protectedIds.filter(id=>protectedAfter[id]!==protectedBefore[id]);if(protectedMismatches.length)throw new Error(`Protected non-F6 bank changed: ${protectedMismatches.join(', ')}`);

function calcLinked(q){return q.type==='calculation'||/calculate|solve|rate|equation|real_wage|relative_price|deflation_logic/.test(String(q.primarySkill||''))&&/\d/.test(String(q.q||''));}
function updateRegistryEntry(entry,module){const records=unique(module).map(item=>item.question),ordinary=['easy','medium','hard'].flatMap(pool=>module.questions[pool]||[]),boss=module.questions.boss||[];const roleCounts={boss:boss.length,bridge:(module.bridgeQuestions||[]).length,calculation:(module.questions.calculation||[]).length,elite:(module.questions.elite||[]).length,integration:(module.questions.integration||[]).length,legendary:(module.questions.legendary||[]).length,legendaryBoss:(module.questions.legendaryBoss||[]).length,main:ordinary.length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length};const diff={easy:(module.questions.easy||[]).length+boss.filter(q=>String(q.difficulty).toLowerCase()==='easyboss').length,medium:(module.questions.medium||[]).length+boss.filter(q=>String(q.difficulty).toLowerCase()==='mediumboss').length,hard:(module.questions.hard||[]).length+boss.filter(q=>['finalboss','hardboss'].includes(String(q.difficulty).toLowerCase())).length,elite:(module.questions.elite||[]).length,legendary:(module.questions.legendary||[]).length+(module.questions.legendaryBoss||[]).length,unknown:(module.repairQuestions||[]).length+(module.repairSeedQuestions||[]).length+(module.bridgeQuestions||[]).length};Object.assign(entry,{includedSkills:[...new Set(records.map(q=>q.primarySkill).filter(Boolean))].sort(),questionCountByRole:roleCounts,questionCountByDifficulty:diff,repairCoverage:{directSkillMatches:(module.repairQuestions||[]).length,mainWithUsableSkill:records.length},bridgeCoverage:{directSkillMatches:(module.bridgeQuestions||[]).length,mainWithUsableSkill:records.length},calculationCoverage:records.filter(calcLinked).length,instructionalClassification:'Engine-safe F6 Money Growth, Inflation, and Neutrality family slice',coverageStatus:'ready-family-slice',coverageStatusLabel:'Engine-safe alone; strongest in F6 long-run monetary sequence',coverageStatusNote:'Phase M2c-2 protects Quantity Theory content, strengthens Fisher Effect and supporting slices, repairs Legendary boss stages, and creates explicit Quantity Theory → Neutrality → Fisher → Inflation Costs → Inflation Tax/Deflation routing.',coverageFloorVersion:PHASE,notes:'Money Growth, Inflation, and Neutrality family slice. Quantity Theory content is protected; additions close structural floors and improve long-run causal reasoning.'});}
for(const conceptId of familyIds)for(const list of [library.registry.concepts,registry.concepts]){const entry=list.find(item=>item.canonicalConceptId===conceptId);if(!entry)throw new Error(`Registry entry missing ${conceptId}`);updateRegistryEntry(entry,library.concepts[conceptId]);}

library.libraryVersion=`${previousVersion}-${PHASE}`;library.sourceCurationPhase=PHASE;library.generatedAt=STAMP;library.canonicalQuestionCount=Object.values(library.concepts).reduce((sum,module)=>sum+unique(module).length,0);
Object.assign(library.registry,{libraryVersion:library.libraryVersion,generatedAt:STAMP,canonicalQuestionCount:library.canonicalQuestionCount});Object.assign(registry,{libraryVersion:library.libraryVersion,generatedAt:STAMP,canonicalQuestionCount:library.canonicalQuestionCount});delete library.librarySha256;library.librarySha256=sha(JSON.stringify(stable(library)));registry.librarySha256=library.librarySha256;Object.assign(manifest,{canonicalQuestionCount:library.canonicalQuestionCount,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,generatedAt:STAMP});
const familyBefore=Object.values(beforeCounts).reduce((out,count)=>{for(const [key,value] of Object.entries(count))out[key]=(out[key]||0)+value;return out;},{}),familyAfter=Object.values(afterCounts).reduce((out,count)=>{for(const [key,value] of Object.entries(count))out[key]=(out[key]||0)+value;return out;},{});
if(familyBefore.total!==249||familyAfter.total!==301)throw new Error(`Unexpected F6 totals ${familyBefore.total} → ${familyAfter.total}`);
const provenance={phase:PHASE,generatedAt:STAMP,scope:{family:'F6 — Money Growth, Inflation, and Neutrality',modifiedCanonicalConceptIds:modifiedIds,protectedCanonicalConceptIds:protectedIds},before:{libraryVersion:previousVersion,canonicalQuestionCount:beforeTotal,counts:beforeCounts,familyCounts:familyBefore},after:{libraryVersion:library.libraryVersion,canonicalQuestionCount:library.canonicalQuestionCount,librarySha256:library.librarySha256,counts:afterCounts,familyCounts:familyAfter},protectedSummary:{canonicalBanksChecked:protectedIds.length,nonF6Mismatches:protectedMismatches},quality:{introducedExact,introducedNumberSwaps,answerLengthIssues:lengthIssues},quantityTheoryProtection:{questionContentAdditions:0,questionContentRewrites:0,bossStageMetadataFixes:4}};
const sourceData={phase:PHASE,generatedAt:STAMP,scope:modifiedIds,changes,summary:{added,bossStageFixed,repairRewritten:4,bridgeRewritten:1,removed:0,relocated:0},authoringPolicy:{soloFloors:{easy:6,medium:6,hard:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendary:6,legendaryBoss:3,repair:1,bridge:1},targetRange:[299,305],actualFamilyTotal:familyAfter.total,noGraphExpansion:true,protectQuantityTheoryContent:true,f2Boundary:'F2 measures real-versus-nominal rates; F6 Fisher explains long-run nominal-rate response to expected inflation.'},quality:provenance.quality};
if(!dryRun){fs.writeFileSync(libraryPath,`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(library)};\n`);fs.writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(path.join(composer,`${PHASE}_questions.json`),JSON.stringify(sourceData,null,2)+'\n');fs.writeFileSync(path.join(composer,`${PHASE}.json`),JSON.stringify(provenance,null,2)+'\n');for(const file of [path.join(repo,'build','index.html'),path.join(composer,'index.html')])if(fs.existsSync(file)){const text=fs.readFileSync(file,'utf8').replaceAll('20260810-macro-m2c1-money-banking-fed-v1','20260810-macro-m2c2-money-growth-inflation-v1');fs.writeFileSync(file,text);}}
console.log(JSON.stringify({dryRun,phase:PHASE,beforeTotal,afterTotal:library.canonicalQuestionCount,added,bossStageFixed,beforeCounts,afterCounts,familyBefore,familyAfter,protectedMismatches,quality:{introducedExact,introducedNumberSwaps,lengthIssues},changeSummary:sourceData.summary},null,2));
