import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const repo=path.resolve(process.argv[2]||process.cwd()),PHASE='phaseM2b1-gdp-national-output-family-maturation-v1',STAMP='2026-08-10T22:30:00.000Z';
const composer=path.join(repo,'build','faculty-build-composer'),dataDir=path.join(composer,'data'),libraryPath=path.join(dataDir,'composer_library.js'),registryPath=path.join(dataDir,'composer_registry.json'),manifestPath=path.join(dataDir,'composer_library_manifest.json'),sourcePath=path.join(composer,`${PHASE}_questions.json`),provenancePath=path.join(composer,`${PHASE}.json`);
const sha=value=>crypto.createHash('sha256').update(value).digest('hex'),stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])])):value,answerHash=answer=>sha(String(answer).trim().replace(/\s+/g,' ').toLowerCase()),qid=q=>String(q?.canonicalId||q?.id||'');
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(libraryPath,'utf8'),sandbox);const library=sandbox.window.MQ_COMPOSER_LIBRARY,registry=JSON.parse(fs.readFileSync(registryPath,'utf8')),manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8')),sourceData=JSON.parse(fs.readFileSync(sourcePath,'utf8')),provenance=JSON.parse(fs.readFileSync(provenancePath,'utf8'));
if(!String(library.libraryVersion).endsWith(PHASE))throw new Error('M2b-1 applied library required.');
const fixes=[];
function tagged(module){return[...Object.entries(module.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(module.repairQuestions||[]).map(question=>({pool:'repair',question})),...(module.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))];}
function rotate(options,answer,index){const n=index%options.length,out=options.slice(n).concat(options.slice(0,n));if(!out.includes(answer))throw new Error(`Answer missing ${answer}`);return out;}
function fix(conceptId,questionId,answer,wrong,index=0){const row=tagged(library.concepts[conceptId]).find(({question})=>qid(question)===questionId);if(!row)throw new Error(`Missing ${questionId}`);const q=row.question,before={options:q.options,aHash:q.aHash};q.options=rotate([answer,...wrong],answer,index);q.aHash=answerHash(answer);q.sourceCurationPhase=PHASE;fixes.push({canonicalConceptId:conceptId,questionId,action:'QUALITY_FIX',oldPool:row.pool,newPool:row.pool,reason:'Removes a material answer-length or answer-position giveaway while preserving the stem and correct answer.',before,after:{options:q.options,aHash:q.aHash}});}

fix('real-versus-nominal-gdp','ECON-NL-GDP-DEFLATOR-5014','Nominal GDP to real GDP',['The GDP price index to the consumer price index','Real-GDP growth to nominal interest-rate growth','Current output quantities to base-year output quantities'],2);
fix('real-versus-nominal-gdp','ECON-NL-EASYBOSS-2013','Uses base-year prices to remove inflation',['Uses current prices to preserve every change in inflation','Uses base-year quantities instead of current output quantities','Subtracts the inflation rate directly from nominal GDP'],1);
fix('limits-of-gdp','ECON-NL-ELITE-318','GDP counts rebuilding, not the destruction’s welfare loss',['GDP excludes all construction completed after a natural disaster','Destroyed homes are recorded as current business investment spending','Rebuilding makes the original household losses irrelevant to welfare'],1);
fix('limits-of-gdp','ECON-NL-MEDIUM-118','GDP may ignore pollution, leisure loss, and unequal distribution',['GDP fails to record any final goods sold in legal markets','Every production increase automatically reduces leisure and environmental quality','Higher GDP guarantees equal gains for households across the income distribution'],1);
fix('limits-of-gdp','ECON-NL-MEDIUM-119','GDP is useful but misses nonmarket quality-of-life factors',['GDP is useless because it excludes all current market production','GDP is complete whenever nominal prices remain unchanged','GDP measures only leisure, safety, and environmental quality'],2);
fix('limits-of-gdp','ECON-NL-HARD-217','GDP may rise even when broader well-being does not clearly improve',['GDP must fall whenever pollution or illness increases after production','GDP automatically subtracts every environmental and health cost from output','Higher measured production proves that every resident became better off'],1);
fix('limits-of-gdp','ECON-NL-HARD-218','A country’s GDP doubles while its population triples',['A country’s GDP and population both double over the same period','A country’s total GDP rises while its population remains unchanged','A country’s real GDP per person rises while total GDP remains fixed'],2);
fix('limits-of-gdp','PM2B1-GDPL-H-002','GDP counts the services produced but not the full damage that made them necessary',['Medical and cleanup services are excluded whenever pollution caused the demand','GDP subtracts the environmental damage and then subtracts cleanup spending again','Any increase in measured cleanup output proves the original damage improved welfare'],1);
fix('limits-of-gdp','PM2B1-GDPL-H-003','GDP falls, but well-being could rise or fall',['Both measured GDP and total well-being must decline by the same amount','GDP stays unchanged because added leisure replaces every lost unit of production','The leisure gain is automatically valued and added to business investment'],2);
fix('limits-of-gdp','PM2B1-GDPL-L-001','GDP compares market production, but these facts do not settle overall well-being',['Country A must have higher well-being because its recorded market GDP is higher','Country B must have higher measured GDP after valuing every hour of leisure','GDP is useless because it measures neither legal market goods nor services'],1);
fix('limits-of-gdp','PM2B1-GDPL-L-002','Market spending can fall even when consumer benefit rises',['The free digital service must be recorded as an export to foreign users','Real GDP automatically measures every quality improvement in a free service','Lower recorded spending proves every user receives less benefit from translation'],2);
fix('limits-of-gdp','PM2B1-GDPL-L-003','Current production can rise while lost wealth and hardship leave welfare lower',['Rebuilding services cannot enter GDP because the storm destroyed assets first','The destroyed productive assets are added to current household consumption spending','Higher rebuilding output proves the storm created a net gain for every household'],3);
fix('limits-of-gdp','ECON-EC-EASYBOSS-17002','GDP measures production, not all well-being',['GDP measures every environmental and leisure dimension of welfare','GDP excludes all replacement investment from measured current production','GDP directly reports how national income is distributed across households'],1);
fix('limits-of-gdp','ECON-EC-EASYBOSS-17016','GDP is useful, but it does not capture every part of well-being',['Higher GDP proves every household receives exactly the same welfare gain','Pollution and longer work hours are fully deducted from real GDP already','GDP is useless because it measures no current market production at all'],2);
fix('limits-of-gdp','ECON-EC-EASYBOSS-17017','GDP can rise without well-being rising',['Rebuilding activity is excluded whenever a natural disaster occurred first','Higher construction spending guarantees that destroyed household wealth is restored','GDP automatically subtracts every hardship caused by the original disaster'],3);
fix('limits-of-gdp','ECON-NL-EASYBOSS-2016','GDP omits important welfare factors',['GDP excludes every final good produced in a legal market','GDP measures only the distribution of current household income','GDP includes complete adjustments for leisure and environmental quality'],1);
fix('limits-of-gdp','ECON-NL-EASYBOSS-2015','People generally prefer more income and output',['GDP records every environmental and leisure benefit','Higher production guarantees equal gains for each household','GDP measures only transfers rather than market output'],2);
fix('limits-of-gdp','ECON-NL-LEGENDARYBOSS-9105','GDP rises, but welfare may remain below its pre-flood level',['GDP falls because every rebuilding service is excluded after a disaster','Welfare fully recovers whenever current construction spending increases','Destroyed homes are added to current GDP as household consumption'],1);
fix('limits-of-gdp','ECON-NL-GDP-WELLBEING-LIMITS-5016','Leisure and environmental quality',['Recorded production of final market goods','Government purchases of current public services','Business investment in newly produced capital'],1);
fix('limits-of-gdp','ECON-NL-GDP-WELLBEING-LIMITS-5017','Useful for production, but incomplete for well-being',['A complete index of every household’s welfare','Useless for measuring current market production','A direct measure of leisure and environmental quality'],2);
fix('limits-of-gdp','ECON-NL-GDP-WELLBEING-LIMITS-6008','GDP counts rebuilding but not the original welfare loss',['Rebuilding services are excluded because the disaster happened first','Destroyed homes are added to GDP as current household consumption','GDP automatically subtracts every loss of wealth and personal hardship'],1);

delete library.librarySha256;library.generatedAt=STAMP;library.librarySha256=sha(JSON.stringify(stable(library)));Object.assign(library.registry,{generatedAt:STAMP,librarySha256:library.librarySha256});Object.assign(registry,{generatedAt:STAMP,librarySha256:library.librarySha256});Object.assign(manifest,{generatedAt:STAMP,librarySha256:library.librarySha256});
sourceData.postApplyQualityFixes=fixes;sourceData.generatedAt=STAMP;provenance.after.librarySha256=library.librarySha256;provenance.generatedAt=STAMP;
fs.writeFileSync(libraryPath,`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(library)};\n`);fs.writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(sourcePath,JSON.stringify(sourceData,null,2)+'\n');fs.writeFileSync(provenancePath,JSON.stringify(provenance,null,2)+'\n');
console.log(JSON.stringify({phase:PHASE,qualityFixes:fixes.length,librarySha256:library.librarySha256},null,2));
