import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const repo=path.resolve(process.argv[2]||process.cwd());
const dryRun=process.argv.includes('--dry-run');
const PHASE='phaseM2d2-fiscal-stabilization-family-maturation-v1';
const STAMP=new Date().toISOString();
const SOURCE='macro-m2d2-fiscal-stabilization-family';
const familyIds=['fiscal-policy-and-aggregate-demand','fiscal-multipliers-and-crowding-out','stabilization-policy'];
const modifiedSet=new Set(familyIds);
const composer=path.join(repo,'build','faculty-build-composer');
const dataDir=path.join(composer,'data');
const libraryPath=path.join(dataDir,'composer_library.js');
const registryPath=path.join(dataDir,'composer_registry.json');
const manifestPath=path.join(dataDir,'composer_library_manifest.json');
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const answerHash=a=>sha(String(a).trim().replace(/\s+/g,' ').toLowerCase());
const qid=q=>String(q?.canonicalId||q?.id||q?.questionId||'');
const questionHash=q=>sha(JSON.stringify(stable({q:q.q,options:q.options,aHash:q.aHash,primaryConceptId:q.primaryConceptId,primarySkill:q.primarySkill,repairSkill:q.repairSkill,difficulty:q.difficulty,secondaryConceptIds:q.secondaryConceptIds||[],bossStage:q.bossStage||null,image:q.image||null})));
const rawBefore=fs.readFileSync(libraryPath,'utf8');
const sandbox={window:{}}; vm.createContext(sandbox); vm.runInContext(rawBefore,sandbox,{filename:libraryPath});
const library=sandbox.window.MQ_COMPOSER_LIBRARY;
const registry=JSON.parse(fs.readFileSync(registryPath,'utf8'));
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
if(!String(library.libraryVersion).endsWith('phaseM2d1-ad-as-macro-equilibrium-family-maturation-v1')) throw new Error('Unexpected baseline: completed M2d-1 library required.');
for(const id of familyIds) if(!library.concepts[id]) throw new Error(`Missing F9 concept ${id}`);

function tagged(module){return [...Object.entries(module.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(module.repairQuestions||[]).map(question=>({pool:'repair',question})),...(module.repairSeedQuestions||[]).map(question=>({pool:'repairSeed',question})),...(module.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))];}
function unique(module){const seen=new Set();return tagged(module).filter(({question})=>{const id=qid(question);if(seen.has(id))return false;seen.add(id);return true;});}
function bankSnapshot(module){return unique(module).map(({pool,question})=>({pool,id:qid(question),question:stable(question)})).sort((a,b)=>a.id.localeCompare(b.id));}
function bankHash(module){return sha(JSON.stringify(stable(bankSnapshot(module))));}
function bossTier(q){const d=String(q?.difficulty||'').toLowerCase();if(d==='easyboss')return'easyBoss';if(d==='mediumboss')return'mediumBoss';if(d==='finalboss'||d==='hardboss')return'finalBoss';return'';}
function countModule(module){const boss=module.questions?.boss||[];return{easy:(module.questions?.easy||[]).length,medium:(module.questions?.medium||[]).length,hard:(module.questions?.hard||[]).length,elite:(module.questions?.elite||[]).length,legendary:(module.questions?.legendary||[]).length,calculation:(module.questions?.calculation||[]).length,integration:(module.questions?.integration||[]).length,easyBoss:boss.filter(q=>bossTier(q)==='easyBoss').length,mediumBoss:boss.filter(q=>bossTier(q)==='mediumBoss').length,finalBoss:boss.filter(q=>bossTier(q)==='finalBoss').length,legendaryBoss:(module.questions?.legendaryBoss||[]).length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length,bridge:(module.bridgeQuestions||[]).length,total:unique(module).length};}
const protectedIds=Object.keys(library.concepts).filter(id=>!modifiedSet.has(id));
const protectedBefore=Object.fromEntries(protectedIds.map(id=>[id,bankHash(library.concepts[id])]));
const beforeCounts=Object.fromEntries(familyIds.map(id=>[id,countModule(library.concepts[id])]));
const beforeTotal=library.canonicalQuestionCount, previousVersion=library.libraryVersion;
const changes=[]; let serial=9400000;

const meta={
 'fiscal-policy-and-aggregate-demand':{code:'FISCAD',tag:'fiscal_policy_ad',objective:'LO35.3',chapter:[35],cluster:'fiscal_policy'},
 'fiscal-multipliers-and-crowding-out':{code:'MULT',tag:'fiscal_multiplier',objective:'LO35.4',chapter:[35],cluster:'policy_transmission'},
 'stabilization-policy':{code:'STAB',tag:'stabilization_policy',objective:'LO35.5',chapter:[35],cluster:'stabilization_policy'}
};
const lessonMap={
 compare_fiscal_package_first_round:['Treats equal-dollar spending and tax changes as having identical direct effects on aggregate demand.','Government purchases enter AD directly, while tax changes affect AD through the share of disposable income households spend.'],
 heterogeneous_mpc_tax_effect:['Applies one MPC to the entire tax change even when recipient groups have different spending responses.','Compute each group’s first-round consumption response separately, then add them before considering later multiplier rounds.'],
 multiplier_crowding_net_comparison:['Compares gross multiplier effects without subtracting the private spending displaced by higher interest rates.','For the simplified model used here, compare each policy’s gross multiplier effect and then subtract its stated crowding-out offset.'],
 infer_crowding_out_from_net_effect:['Uses the net AD shift as if it were the gross multiplier effect.','First compute the gross multiplier effect, then infer the crowding-out offset from the difference between gross and observed net AD.'],
 delayed_policy_self_correction:['Assumes a policy designed for an old output gap remains correctly sized after self-correction has already reduced the gap.','Policy lags matter because wages, costs, expectations, and private spending can change before discretionary policy takes effect, creating overshoot risk.'],
 revised_gap_policy_overshoot:['Uses the original output-gap estimate even after newer data show a much smaller gap.','Compare the policy’s expected AD shift with the output gap that exists when the policy actually takes effect, not only the initial estimate.'],
 automatic_vs_discretionary_timing:['Assumes automatic stabilizers and discretionary fiscal programs have the same activation and phase-out timing.','Automatic stabilizers respond as income and employment change without new legislation; discretionary programs can arrive later and may outlast the original gap.'],
 stabilization_to_phillips:['Treats lower inflation pressure from contractionary demand policy as costless in the short run.','A contractionary AD policy can reduce inflation pressure while also lowering output and raising unemployment before expectations fully adjust.'],
 predict_ad_shift:['Confuses a fiscal-policy change with an aggregate-supply shift.','Government purchases and tax-induced consumption changes work primarily through aggregate demand in this Principles model.'],
 calculate_tax_cut_consumption_effect:['Treats the full tax cut as immediate consumption.','The first-round consumption effect equals the change in disposable income times MPC.'],
 identify_policy_type:['Classifies fiscal policy from the state of the economy rather than from what government purchases and taxes actually do.','Classify the package from its fiscal actions: higher purchases/lower taxes are expansionary; lower purchases/higher taxes are contractionary.'],
 explain_policy_channel:['Jumps from a tax change directly to total output without identifying the first spending channel.','A tax change first changes disposable income, then consumption according to MPC, which shifts aggregate demand.'],
 apply_policy_lag_logic:['Assumes a delayed policy has the same stabilizing effect regardless of how the economy changes before implementation.','A policy can destabilize the economy if it arrives after the original gap has already narrowed or reversed.'],
 analyze_supply_shock_tradeoff:['Treats a negative supply shock as if policymakers can simultaneously eliminate its inflation and output effects by shifting AD.','Demand stabilization during a negative supply shock involves a tradeoff: supporting output can worsen price pressure, while reducing inflation can deepen the output loss.'],
 bridge_fiscal_to_multiplier:['Stops at the first-round fiscal impulse and treats it as the full aggregate-demand effect.','After the first-round spending change, the multiplier process traces additional income-consumption rounds; crowding out can then reduce the net effect.'],
 bridge_multiplier_to_stabilization:['Carries the gross fiscal impulse into stabilization analysis even after an offset has been specified.','Stabilization analysis should use the net aggregate-demand impulse after the multiplier and stated crowding-out offset.'],
 bridge_lradj_to_stabilization:['Treats self-correction and active stabilization as the same mechanism.','Long-run adjustment describes endogenous SRAS movement; stabilization policy asks whether policymakers should deliberately change AD instead of waiting.'],
 bridge_stabilization_to_phillips:['Stops with an AD shift and does not connect the short-run output response to unemployment and inflation pressure.','A contractionary stabilization policy that lowers AD can reduce inflation pressure while raising unemployment in the short run, creating the bridge to Phillips-curve analysis.']
};
function lesson(skill){return lessonMap[skill]||['Uses a shortcut instead of tracing the fiscal-policy mechanism.','Identify the initial fiscal action, trace its first-round aggregate-demand effect, then account for multiplier, crowding-out, timing, and stabilization context only when the question calls for them.'];}
function rotate(options,answer,index){const n=index%options.length,out=options.slice(n).concat(options.slice(0,n));if(!out.includes(answer))throw new Error(`Answer missing: ${answer}`);return out;}
function setSourceHash(q){q.sourceHash=questionHash(q);if(Array.isArray(q.sourceOccurrences)&&q.sourceOccurrences.length)q.sourceOccurrences[q.sourceOccurrences.length-1].sourceHash=q.sourceHash;}
function spec(stem,answer,wrong,skill,extra={}){return{stem,answer,options:[answer,...wrong],skill,...extra};}
function addLegendary(conceptId,s,index){
 const module=library.concepts[conceptId],m=meta[conceptId];
 const id=`PM2D2-${m.code}-L-${String(index+1).padStart(3,'0')}`,[commonError,feedback]=lesson(s.skill);
 const q={id,sourceGame:SOURCE,q:s.stem,options:rotate(s.options,s.answer,index),tag:m.tag,type:s.type||'application',objective:m.objective,difficulty:'legendary',conceptCluster:m.cluster,primarySkill:s.skill,secondarySkills:s.secondarySkills||[],repairSkill:s.repairSkill||s.skill,commonError:s.commonError||commonError,feedback:s.feedback||feedback,aHash:answerHash(s.answer),canonicalId:id,sourceId:++serial,sourceChapter:m.chapter,sourcePool:'legendary',primaryConceptId:conceptId,secondaryConceptIds:s.secondaryConceptIds||[],instructionalRole:'legendary',canonicalDifficulty:'legendary',originalSourcePool:'legendary',originalBossTier:null,sourceCurationPhase:PHASE};
 if(s.image)q.image=s.image;
 q.sourceHash=questionHash(q);q.sourceOccurrences=[{sourceGame:SOURCE,sourceFile:`${PHASE}_questions.json`,sourceGlobal:'questions',sourcePool:'legendary',routeKey:q.primarySkill,sourceRecordOrder:index,sourceId:q.sourceId,sourceHash:q.sourceHash,sourceCurationPhase:PHASE}];
 module.questions.legendary.push(q);changes.push({questionId:id,canonicalConceptId:conceptId,action:'ADD',oldPool:null,newPool:'legendary',reason:s.reason||'Adds unique Legendary transfer depth to the otherwise protected F9 family.'});return q;
}
function findQuestion(conceptId,id){for(const row of tagged(library.concepts[conceptId]))if(qid(row.question)===id)return row;throw new Error(`Question not found ${conceptId}/${id}`);}
function rewrite(conceptId,id,s,reason,action){
 const {pool,question:q}=findQuestion(conceptId,id),beforeHash=questionHash(q),oldSkill=q.primarySkill,oldSecondary=[...(q.secondaryConceptIds||[])];
 q.q=s.stem;q.options=rotate(s.options,s.answer,s.rotate||0);q.aHash=answerHash(s.answer);q.primarySkill=s.skill||q.primarySkill;q.repairSkill=s.repairSkill||s.skill||q.repairSkill;q.secondaryConceptIds=s.secondaryConceptIds||[];q.secondarySkills=s.secondarySkills||[];q.type=s.type||q.type||pool;const [commonError,feedback]=lesson(q.primarySkill);q.commonError=s.commonError||commonError;q.feedback=s.feedback||feedback;if(s.image!==undefined){if(s.image)q.image=s.image;else delete q.image;}setSourceHash(q);
 changes.push({questionId:id,canonicalConceptId:conceptId,action,oldPool:pool,newPool:pool,reason,beforeHash,afterHash:questionHash(q),oldPrimarySkill:oldSkill,newPrimarySkill:q.primarySkill,oldSecondaryConceptIds:oldSecondary,newSecondaryConceptIds:q.secondaryConceptIds});
}
function fixBossStage(conceptId,id,stage,reason){const {pool,question:q}=findQuestion(conceptId,id);if(pool!=='legendaryBoss')throw new Error(`${id} not LB`);const beforeHash=questionHash(q),beforeBossStage=q.bossStage??null;q.bossStage=stage;setSourceHash(q);changes.push({questionId:id,canonicalConceptId:conceptId,action:'BOSS_STAGE_FIX',oldPool:'legendaryBoss',newPool:'legendaryBoss',reason,beforeHash,afterHash:questionHash(q),beforeBossStage,afterBossStage:stage});}

// --- Unique Legendary additions only: F9 ordinary/checkpoint banks stay protected. ---
const fiscalAdds=[
 spec('A temporary $120 billion tax credit is split equally between two household groups. One group has MPC 0.90 and the other MPC 0.40. Before multiplier rounds or crowding out, what is the first-round change in aggregate demand from consumption?','$78 billion increase.',['$120 billion increase.','$60 billion increase.','$156 billion increase.'],'heterogeneous_mpc_tax_effect',{type:'multi-step',secondaryConceptIds:['fiscal-multipliers-and-crowding-out']}),
 spec('Congress replaces $100 billion of government purchases with a $100 billion tax cut. Households have MPC 0.80. Holding other AD determinants fixed and looking only at the first round, what happens to aggregate demand?','AD falls by $20 billion.',['AD is unchanged because the two fiscal changes are equal.','AD rises by $20 billion.','AD rises by $80 billion.'],'compare_fiscal_package_first_round',{type:'policy_package_synthesis',secondaryConceptIds:['aggregate-demand']})
];
fiscalAdds.forEach((s,i)=>addLegendary('fiscal-policy-and-aggregate-demand',s,i));

const multAdds=[
 spec('Two governments each increase purchases by $60 billion. Economy A has MPC 0.80 and $100 billion of crowding out; Economy B has MPC 0.60 and $20 billion of crowding out. Using the simple multiplier and the stated offsets, which comparison is correct?','Economy A has a $200 billion net AD increase, which is $70 billion larger than Economy B.',['Economy A has a $300 billion net increase and Economy B has a $150 billion net increase because crowding out does not affect AD.','Economy B has a $200 billion net increase, which is $70 billion larger than Economy A.','Both economies have the same $180 billion net AD increase because the initial spending changes are equal.'],'multiplier_crowding_net_comparison',{type:'multi-step-policy-comparison',secondaryConceptIds:['stabilization-policy']}),
 spec('Government purchases rise by $80 billion and MPC is 0.75. The observed net increase in aggregate demand is $230 billion after crowding out. Under the simple model used in this bank, how much of the gross multiplier effect was crowded out?','$90 billion.',['$230 billion.','$320 billion.','$10 billion.'],'infer_crowding_out_from_net_effect',{type:'reverse-calculation',secondaryConceptIds:['stabilization-policy']})
];
multAdds.forEach((s,i)=>addLegendary('fiscal-multipliers-and-crowding-out',s,i));

const stabAdds=[
 spec('A recessionary gap begins closing without new policy as wage growth slows and SRAS shifts right. A large discretionary stimulus designed for the original gap is still scheduled to take effect several quarters later. What is the strongest stabilization concern?','The delayed stimulus may arrive after much of the gap has self-corrected, pushing AD too far right and creating overheating pressure.',['The stimulus becomes contractionary once SRAS begins shifting right.','Self-correction guarantees the stimulus has no effect on aggregate demand.','The delayed stimulus automatically shifts LRAS right by the amount of the original gap.'],'delayed_policy_self_correction',{type:'policy-lag-synthesis',secondaryConceptIds:['long-run-macroeconomic-adjustment','aggregate-demand']}),
 spec('Policymakers initially estimate a $300 billion recessionary gap and enact a $75 billion spending increase with a simple multiplier of 4. By the time the policy takes effect, revised data show the gap is only $100 billion. Ignoring crowding out, what is the implication?','The $300 billion AD increase overshoots the revised gap by $200 billion.',['The policy closes the revised gap exactly because it was calibrated to the original estimate.','The $75 billion initial spending increase leaves a $25 billion gap because only the first round matters.','The policy raises AD by $100 billion because stabilization automatically adjusts to revised data.'],'revised_gap_policy_overshoot',{type:'policy-lag-calculation',secondaryConceptIds:['fiscal-multipliers-and-crowding-out']}),
 spec('Inflation pressure is being driven by excessive aggregate demand. Policymakers use contractionary stabilization policy and the policy succeeds in lowering aggregate demand. Before inflation expectations fully adjust, which short-run combination is most consistent with the policy mechanism?','Lower inflation pressure together with weaker output and higher unemployment.',['Lower inflation pressure together with stronger output and lower unemployment.','Higher inflation pressure together with weaker output and higher unemployment.','No change in unemployment because stabilization policy affects only the price level.'],'stabilization_to_phillips',{type:'cross-family-transfer',secondaryConceptIds:['short-run-phillips-curve','aggregate-demand']}),
 spec('A short recession causes tax receipts to fall and unemployment-benefit payments to rise automatically. Congress also approves an infrastructure stimulus, but construction begins after the economy has already recovered. Which comparison is strongest?','The automatic stabilizers cushion the downturn and recede with conditions, while the delayed discretionary program can add demand after the original gap has faded.',['Both responses have the same implementation timing because each changes the government budget.','The automatic stabilizers become contractionary during the recession, while delayed infrastructure is always stabilizing.','The infrastructure program cannot affect aggregate demand once the recession has ended.'],'automatic_vs_discretionary_timing',{type:'policy-timing-transfer',secondaryConceptIds:['aggregate-demand']})
];
stabAdds.forEach((s,i)=>addLegendary('stabilization-policy',s,i));

// --- Repair quality: rewrite, do not expand. ---
rewrite('fiscal-policy-and-aggregate-demand','ECON-SP-FISCAL-POLICY-AD-SHIFT-5041',spec('Congress increases government purchases while taxes and other aggregate-demand determinants are unchanged. Which change should a student predict in the AD-AS model?','Aggregate demand shifts right.',['Aggregate demand shifts left.','Short-run aggregate supply shifts right.','Long-run aggregate supply shifts left.'],'predict_ad_shift'), 'Replaces a definition-like repair with direct practice on a recurring ordinary F9 skill.','REPAIR_REWRITE');
rewrite('fiscal-policy-and-aggregate-demand','ECON-SP-TAX-CUT-AD-5042',spec('A $40 billion tax cut raises disposable income and MPC is 0.75. Before later multiplier rounds, how much does consumption increase?','$30 billion.',['$40 billion.','$10 billion.','$53.3 billion.'],'calculate_tax_cut_consumption_effect'), 'Targets the recurring tax-to-consumption calculation rather than only AD direction.','REPAIR_REWRITE');
rewrite('fiscal-policy-and-aggregate-demand','LG-R-5048',spec('Congress lowers government purchases and raises taxes in the same bill to reduce excessive aggregate demand. How should the package be classified?','Contractionary fiscal policy.',['Expansionary fiscal policy.','Expansionary monetary policy.','An automatic stabilizer.'],'identify_policy_type'), 'Adds diagnostic practice on classifying a mixed fiscal package from its actual instruments.','REPAIR_REWRITE');
rewrite('fiscal-policy-and-aggregate-demand','LG-R-5051',spec('Why can a tax cut shift aggregate demand to the right in the short run?','It raises disposable income, which can raise consumption spending.',['It directly increases the money supply.','It directly lowers firms’ production costs and shifts SRAS right.','It automatically increases potential output.'],'explain_policy_channel'), 'Targets the missing causal channel from tax policy to aggregate demand.','REPAIR_REWRITE');
rewrite('stabilization-policy','LG-R-5056',spec('A stimulus is approved during a recession but takes effect only after output has returned close to potential. What problem should the student diagnose?','The delayed stimulus can push aggregate demand too far right after the original gap has faded.',['The delay automatically turns the stimulus into contractionary policy.','The policy can no longer affect aggregate demand once recovery begins.','The delay directly shifts LRAS left.'],'apply_policy_lag_logic'), 'Replaces a basic direction check with diagnostic recovery practice on policy-lag risk.','REPAIR_REWRITE');
rewrite('stabilization-policy','LG-R-5058',spec('A negative supply shock lowers real output and raises the price level. If policymakers use expansionary demand policy to support output, what tradeoff should the student remember?','It can support output while worsening inflation pressure.',['It lowers the price level and raises output with no tradeoff.','It directly shifts SRAS right and restores productive capacity.','It must reduce both output and the price level.'],'analyze_supply_shock_tradeoff'), 'Adds recovery practice for the central stabilization dilemma created by adverse supply shocks.','REPAIR_REWRITE');

// --- Genuine Bridges: connect F8 → F9 internal sequence → F10. ---
rewrite('fiscal-policy-and-aggregate-demand','LG-B-6021',spec('A tax cut produces an $80 billion first-round increase in consumption. Which next idea is needed to move from that first-round fiscal impulse to the larger total aggregate-demand effect?','The multiplier process traces additional income-and-spending rounds.',['Long-run aggregate supply shifts by the same $80 billion.','The inflation tax converts the consumption increase into government revenue.','The natural rate of unemployment determines the tax cut directly.'],'bridge_fiscal_to_multiplier',{secondaryConceptIds:['fiscal-multipliers-and-crowding-out']}), 'Creates a genuine Fiscal Policy → Multiplier bridge instead of another standalone tax calculation.','BRIDGE_REWRITE');
rewrite('fiscal-multipliers-and-crowding-out','LG-B-6022',spec('Government purchases rise $50 billion and MPC is 0.75. Which statement correctly connects the fiscal action to the multiplier concept?','The $50 billion first-round AD impulse is magnified to $200 billion before any crowding-out offset.',['The $50 billion first-round impulse remains $50 billion because later spending rounds do not affect AD.','The multiplier reduces the initial AD impulse to $37.5 billion.','The fiscal action shifts LRAS rather than aggregate demand.'],'bridge_fiscal_to_multiplier',{secondaryConceptIds:['fiscal-policy-and-aggregate-demand','aggregate-demand']}), 'Makes the connection between the originating fiscal action and the multiplier explicit.','BRIDGE_REWRITE');
rewrite('fiscal-multipliers-and-crowding-out','LG-B-6023',spec('A fiscal package generates a $300 billion gross AD increase, but crowding out reduces private investment by $80 billion in the simplified model. What AD impulse should stabilization analysis carry forward?','$220 billion net increase.',['$380 billion net increase.','$300 billion because stabilization uses only the gross multiplier effect.','$80 billion because crowding out replaces the fiscal impulse.'],'bridge_multiplier_to_stabilization',{secondaryConceptIds:['stabilization-policy','aggregate-demand']}), 'Creates a genuine Multiplier/Crowding Out → Stabilization bridge using the net policy impulse.','BRIDGE_REWRITE');
rewrite('stabilization-policy','ECON-SP-CHOOSE-STABILIZATION-RESPONSE-6054',spec('After a negative AD shock, output is below potential, but wages and input costs are already adjusting downward and SRAS is shifting right. What additional question belongs to stabilization-policy analysis?','Whether policymakers should deliberately shift AD right rather than wait for the self-correcting SRAS adjustment.',['Whether LRAS should be moved left to meet the current level of output.','Whether the multiplier should be redefined as zero during every recession.','Whether unemployment should be excluded from the labor force until recovery is complete.'],'bridge_lradj_to_stabilization',{secondaryConceptIds:['long-run-macroeconomic-adjustment','aggregate-demand']}), 'Creates the explicit Long-Run Adjustment → Stabilization choice described in the M2d blueprint.','BRIDGE_REWRITE');
rewrite('stabilization-policy','LG-B-6025',spec('Contractionary stabilization policy shifts AD left to cool an overheating economy. Which short-run labor-market effect connects this policy choice to Phillips-curve analysis?','Unemployment tends to rise as output weakens while inflation pressure falls.',['Unemployment must fall because lower AD always increases hiring.','Unemployment is unchanged because only the price level responds to AD.','The natural rate permanently falls by the size of the AD shift.'],'bridge_stabilization_to_phillips',{secondaryConceptIds:['short-run-phillips-curve','aggregate-demand']}), 'Creates a genuine Stabilization → Short-Run Phillips Curve bridge for M2d block closure.','BRIDGE_REWRITE');

// --- Repair all known F9 Legendary Boss stages semantically. ---
const stageFixes={
 'fiscal-policy-and-aggregate-demand':[
  ['P52A-FISCAD-LB-001','opening','Uses the core net first-round G/tax effect as the opening scaffold.'],
  ['P52A-FISCAD-LB-002','middle','Uses heterogeneous spending responses as the middle scaffold.'],
  ['LG-Q-9142','final','Uses tax transmission plus multiplier sequencing as the final scaffold.']
 ],
 'fiscal-multipliers-and-crowding-out':[
  ['LG-Q-9141','opening','Uses the qualitative interest-rate/crowding-out mechanism as the opening scaffold.'],
  ['LG-Q-9134','middle','Infers MPC and shift order as the middle scaffold.'],
  ['LG-Q-9133','final','Combines multiplier and crowding-out sequencing as the final scaffold.']
 ],
 'stabilization-policy':[
  ['LG-Q-9140','opening','Uses policy direction relative to an overheating gap as an opening scaffold.'],
  ['LG-Q-9144','opening','Uses the supply-shock stabilization tradeoff as a second opening-stage variant.'],
  ['LG-Q-9136','middle','Combines a contractionary graph with a remaining-gap calculation as a middle scaffold.'],
  ['LG-Q-9135','middle','Combines spending impulses and a multiplier as a second middle-stage variant.'],
  ['LG-Q-9143','final','Combines monetary contraction with fiscal expansion as a final-stage synthesis.'],
  ['LG-Q-9139','final','Combines multiplier, crowding out, and remaining-gap reasoning as a final-stage synthesis.']
 ]
};
for(const [cid,rows] of Object.entries(stageFixes))for(const [id,stage,reason] of rows)fixBossStage(cid,id,stage,reason);

// --- Accessibility metadata for every F9 graph copy, including repeated images. ---
const assetText={
 'moneymultiplier.webp':{
  imageAlt:'Aggregate-demand multiplier graph with AD1, AD2, and AD3 shifting progressively right at a fixed price level P, corresponding to output levels Y1, Y2, and Y3.',
  graphDescription:'The horizontal axis is real output Y and the vertical axis is the price level P. A horizontal line at price level P crosses three downward-sloping aggregate-demand curves. AD1 intersects at output Y1, AD2 lies to the right and intersects at Y2, and AD3 lies farther right and intersects at Y3, so Y1 is less than Y2, which is less than Y3.'
 },
 'adaslras.webp':{
  imageAlt:'AD-AS graph with LRAS at Y1, two aggregate-demand curves, two short-run aggregate-supply curves, and labeled output gaps.',
  graphDescription:'The horizontal axis is real output Y and the vertical axis is the price level. LRAS is vertical at Y1. AD1 and AD2 slope downward, with AD2 to the right of AD1. AS1 and AS2 slope upward, with AS1 above and left of AS2. Dashed guides mark Y3 left of LRAS, Y1 on LRAS, Y2 right of LRAS, and price levels P1, P2, and P3. AD1-AS2 is at Y1/P1; AD1-AS1 is at Y3/P2; AD2-AS2 is at Y2/P2; AD2-AS1 is at Y1/P3.'
 },
 'moneyd2_moneys2.webp':{
  imageAlt:'Money-market graph with two vertical money-supply curves, two downward-sloping money-demand curves, and labeled interest-rate and money-quantity points.',
  graphDescription:'The vertical axis is interest rate r and the horizontal axis is quantity of money Qm. MS1 is vertical at Qm1 and MS2 is vertical to its right at Qm2. MD1 slopes downward through e at Qm1, r2 and g at Qm2, r1. MD2 is shifted right and upward and slopes downward through a at Qm1, r4 and d at Qm2, r3. Additional labeled points are b at Qm2, r4; c at Qm1, r3; and f at Qm1, r1.'
 },
 'ad_ms_md.webp':{
  imageAlt:'Two-panel monetary-transmission graph showing a leftward money-supply shift with a higher interest rate and a leftward aggregate-demand shift with lower output.',
  graphDescription:'The left panel has interest rate r on the vertical axis and money M on the horizontal axis. A downward-sloping MD curve intersects MS1 at r1; MS2 is left of MS1 and intersects MD at the higher rate r2. The right panel has price level P on the vertical axis and output Y on the horizontal axis. AD2 lies left of AD1. At price level P1, output is Y1 on AD1 and Y2 on AD2.'
 }
};
let assetMetadataCopies=0;
for(const cid of familyIds){const module=library.concepts[cid];for(const m of module.assetMetadata||[]){const text=assetText[m.filename];if(!text)continue;m.imageAlt=text.imageAlt;m.graphDescription=text.graphDescription;assetMetadataCopies++;}}
for(const m of library.assetInventory||[]){if(!modifiedSet.has(m.conceptId))continue;const text=assetText[m.filename];if(!text)continue;m.imageAlt=text.imageAlt;m.graphDescription=text.graphDescription;}
for(const m of manifest.assets||[]){if(!modifiedSet.has(m.conceptId))continue;const text=assetText[m.filename];if(!text)continue;m.imageAlt=text.imageAlt;m.graphDescription=text.graphDescription;}
if(assetMetadataCopies!==6)throw new Error(`Expected 6 F9 asset metadata copies, got ${assetMetadataCopies}`);

// --- Static count and quality guards. ---
const afterCounts=Object.fromEntries(familyIds.map(id=>[id,countModule(library.concepts[id])]));
const expected={
 'fiscal-policy-and-aggregate-demand':{total:54,legendary:8,legendaryBoss:3,repair:6,bridge:3},
 'fiscal-multipliers-and-crowding-out':{total:76,legendary:8,legendaryBoss:3,repair:9,bridge:5},
 'stabilization-policy':{total:82,legendary:12,legendaryBoss:6,repair:8,bridge:5}
};
for(const [cid,target] of Object.entries(expected))for(const [k,v] of Object.entries(target))if(afterCounts[cid][k]!==v)throw new Error(`Count mismatch ${cid} ${k}: ${afterCounts[cid][k]} != ${v}`);
const added=changes.filter(c=>c.action==='ADD').length;if(added!==8)throw new Error(`Expected 8 additions; got ${added}`);
const bossStageFixed=changes.filter(c=>c.action==='BOSS_STAGE_FIX').length;if(bossStageFixed!==12)throw new Error(`Expected 12 bossStage fixes; got ${bossStageFixed}`);
const repairRewritten=changes.filter(c=>c.action==='REPAIR_REWRITE').length;if(repairRewritten!==6)throw new Error(`Expected 6 repair rewrites; got ${repairRewritten}`);
const bridgeRewritten=changes.filter(c=>c.action==='BRIDGE_REWRITE').length;if(bridgeRewritten!==5)throw new Error(`Expected 5 bridge rewrites; got ${bridgeRewritten}`);
for(const cid of familyIds)for(const q of library.concepts[cid].questions.legendaryBoss||[])if(!['opening','middle','final'].includes(q.bossStage))throw new Error(`Invalid F9 bossStage ${cid}/${qid(q)}=${q.bossStage}`);
for(const cid of familyIds)for(const m of library.concepts[cid].assetMetadata||[])if(!m.imageAlt||!m.graphDescription)throw new Error(`Missing F9 asset accessibility ${cid}/${m.filename}`);

const changedContentIds=new Set(changes.filter(c=>['ADD','REPAIR_REWRITE','BRIDGE_REWRITE'].includes(c.action)).map(c=>c.questionId));
const allF9=familyIds.flatMap(cid=>unique(library.concepts[cid]).map(({pool,question})=>({cid,pool,question})));
const normalize=t=>String(t||'').toLowerCase().replace(/[^a-z0-9%$]+/g,' ').replace(/\s+/g,' ').trim();
const stemMap=new Map(),tplMap=new Map(),introducedExact=[],introducedNumberSwaps=[];
for(const r of allF9){const id=qid(r.question),stem=normalize(r.question.q),tpl=stem.replace(/\b\d+(?:[.,]\d+)?%?\b/g,'#');if(stemMap.has(stem)&&(changedContentIds.has(id)||changedContentIds.has(stemMap.get(stem))))introducedExact.push([stemMap.get(stem),id]);else if(!stemMap.has(stem))stemMap.set(stem,id);if(tplMap.has(tpl)&&(changedContentIds.has(id)||changedContentIds.has(tplMap.get(tpl))))introducedNumberSwaps.push([tplMap.get(tpl),id]);else if(!tplMap.has(tpl))tplMap.set(tpl,id);}
if(introducedExact.length)throw new Error(`Introduced exact duplicate ${JSON.stringify(introducedExact)}`);if(introducedNumberSwaps.length)throw new Error(`Introduced number-swap ${JSON.stringify(introducedNumberSwaps)}`);
function wc(t){return String(t||'').trim().split(/\s+/).filter(Boolean).length;}const lengthIssues=[];
for(const cid of familyIds){const groups={};for(const {pool,question:q} of unique(library.concepts[cid]))if(changedContentIds.has(qid(q))){const correct=(q.options||[]).find(o=>answerHash(o)===q.aHash),dist=(q.options||[]).filter(o=>o!==correct),g=pool;(groups[g]||=[]).push({c:wc(correct),d:dist.map(wc)});}for(const [g,rows] of Object.entries(groups)){if(!rows.length)continue;const longest=rows.filter(r=>r.d.every(n=>r.c>n)).length/rows.length,cm=rows.reduce((a,r)=>a+r.c,0)/rows.length,dm=rows.reduce((a,r)=>a+r.d.reduce((x,y)=>x+y,0)/r.d.length,0)/rows.length,ratio=cm/dm;if(rows.length>=2&&(longest>.70||ratio>1.8))lengthIssues.push({cid,g,longest:Number(longest.toFixed(3)),ratio:Number(ratio.toFixed(3))});}}
if(lengthIssues.length)throw new Error(`Answer length issue ${JSON.stringify(lengthIssues)}`);

const protectedAfter=Object.fromEntries(protectedIds.map(id=>[id,bankHash(library.concepts[id])]));const protectedMismatches=protectedIds.filter(id=>protectedAfter[id]!==protectedBefore[id]);if(protectedMismatches.length)throw new Error(`Protected non-F9 bank changed: ${protectedMismatches.join(',')}`);

function calcLinked(q){return Boolean(q?.calculationMetadata?.present)||String(q?.type||'').toLowerCase().includes('calculation')||(/calculate|multiplier|mpc|mps|net_effect|gap|crowding/.test(String(q?.primarySkill||''))&&/\d/.test(String(q?.q||'')));}
function updateRegistryEntry(entry,module){const records=unique(module).map(x=>x.question),ordinary=['easy','medium','hard'].flatMap(pool=>module.questions[pool]||[]),boss=module.questions.boss||[];const role={boss:boss.length,bridge:(module.bridgeQuestions||[]).length,calculation:(module.questions.calculation||[]).length,elite:(module.questions.elite||[]).length,integration:(module.questions.integration||[]).length,legendary:(module.questions.legendary||[]).length,legendaryBoss:(module.questions.legendaryBoss||[]).length,main:ordinary.length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length};const diff={easy:(module.questions.easy||[]).length+boss.filter(q=>bossTier(q)==='easyBoss').length,medium:(module.questions.medium||[]).length+boss.filter(q=>bossTier(q)==='mediumBoss').length,hard:(module.questions.hard||[]).length+boss.filter(q=>bossTier(q)==='finalBoss').length,elite:(module.questions.elite||[]).length,legendary:(module.questions.legendary||[]).length+(module.questions.legendaryBoss||[]).length,unknown:(module.repairQuestions||[]).length+(module.repairSeedQuestions||[]).length+(module.bridgeQuestions||[]).length};Object.assign(entry,{includedSkills:[...new Set(records.map(q=>q.primarySkill).filter(Boolean))].sort(),questionCountByRole:role,questionCountByDifficulty:diff,repairCoverage:{directSkillMatches:(module.repairQuestions||[]).length,mainWithUsableSkill:records.length},bridgeCoverage:{directSkillMatches:(module.bridgeQuestions||[]).length,mainWithUsableSkill:records.length},calculationCoverage:records.filter(calcLinked).length,graphCoverage:records.filter(q=>Boolean(q.image)).length,instructionalClassification:'Engine-safe F9 Fiscal and Stabilization Policy family slice',coverageStatus:'ready-family-slice',coverageStatusLabel:'Engine-safe alone; strongest as Fiscal AD → Multiplier/Crowding Out → Stabilization sequence',coverageStatusNote:'Phase M2d-2 protects the robust ordinary/checkpoint inventory, adds only the eight Legendary records needed for a unique family run, repairs all F9 Legendary boss stages, strengthens diagnostic Repair and genuine cross-concept Bridges, and adds full alt text/graph descriptions to every F9 graph asset copy.',coverageFloorVersion:PHASE,notes:'Fiscal and stabilization family slice. No new graph image was added; existing fiscal, money-market, transmission, and AD-AS assets are retained with complete accessibility metadata.'});}
for(const cid of familyIds)for(const list of [library.registry.concepts,registry.concepts]){const e=list.find(x=>x.canonicalConceptId===cid);if(!e)throw new Error(`Registry missing ${cid}`);updateRegistryEntry(e,library.concepts[cid]);}

library.libraryVersion=`${previousVersion}-${PHASE}`;library.sourceCurationPhase=PHASE;library.generatedAt=STAMP;library.canonicalQuestionCount=Object.values(library.concepts).reduce((n,m)=>n+unique(m).length,0);Object.assign(library.registry,{libraryVersion:library.libraryVersion,generatedAt:STAMP,canonicalQuestionCount:library.canonicalQuestionCount});Object.assign(registry,{libraryVersion:library.libraryVersion,generatedAt:STAMP,canonicalQuestionCount:library.canonicalQuestionCount});delete library.librarySha256;library.librarySha256=sha(JSON.stringify(stable(library)));registry.librarySha256=library.librarySha256;Object.assign(manifest,{canonicalQuestionCount:library.canonicalQuestionCount,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,generatedAt:STAMP});
const familyBefore=Object.values(beforeCounts).reduce((o,r)=>{for(const [k,v] of Object.entries(r))o[k]=(o[k]||0)+v;return o;},{}),familyAfter=Object.values(afterCounts).reduce((o,r)=>{for(const [k,v] of Object.entries(r))o[k]=(o[k]||0)+v;return o;},{});if(familyBefore.total!==204||familyAfter.total!==212)throw new Error(`Unexpected F9 totals ${familyBefore.total} -> ${familyAfter.total}`);if(familyAfter.legendary!==28)throw new Error(`Expected 28 family ordinary Legendary, got ${familyAfter.legendary}`);
const provenance={phase:PHASE,generatedAt:STAMP,scope:{family:'F9 — Fiscal and Stabilization Policy',modifiedCanonicalConceptIds:familyIds,protectedCanonicalConceptIds:protectedIds},before:{libraryVersion:previousVersion,canonicalQuestionCount:beforeTotal,counts:beforeCounts,familyCounts:familyBefore},after:{libraryVersion:library.libraryVersion,canonicalQuestionCount:library.canonicalQuestionCount,librarySha256:library.librarySha256,counts:afterCounts,familyCounts:familyAfter},protectedSummary:{canonicalBanksChecked:protectedIds.length,nonF9Mismatches:protectedMismatches},quality:{introducedExact,introducedNumberSwaps,answerLengthIssues:lengthIssues},assetAccessibility:{metadataUpdatedCopies:assetMetadataCopies,newGraphAssets:0,allF9CopiesHaveAltText:true}};
const sourceData={phase:PHASE,generatedAt:STAMP,scope:familyIds,changes,summary:{added,bossStageFixed,repairRewritten,bridgeRewritten,assetMetadataCopiesUpdated:assetMetadataCopies,removed:0,relocated:0},authoringPolicy:{m1OriginalBaseline:204,liveBaseline:familyBefore.total,targetRange:[212,216],actualFamilyTotal:familyAfter.total,protectedOrdinaryAndCheckpointBanks:true,newGraphAssets:0,legendaryOrdinaryTarget:27,bridgeChain:['long-run-macroeconomic-adjustment','stabilization-policy','fiscal-policy-and-aggregate-demand','fiscal-multipliers-and-crowding-out','stabilization-policy','short-run-phillips-curve']},quality:provenance.quality};
if(!dryRun){fs.writeFileSync(libraryPath,`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(library)};\n`);fs.writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(path.join(composer,`${PHASE}_questions.json`),JSON.stringify(sourceData,null,2)+'\n');fs.writeFileSync(path.join(composer,`${PHASE}.json`),JSON.stringify(provenance,null,2)+'\n');for(const file of [path.join(repo,'build','index.html'),path.join(composer,'index.html')])if(fs.existsSync(file)){let text=fs.readFileSync(file,'utf8');text=text.replaceAll('20260810-macro-m2d1-ad-as-macro-equilibrium-v1','20260810-macro-m2d2-fiscal-stabilization-v1');fs.writeFileSync(file,text);}}
console.log(JSON.stringify({dryRun,phase:PHASE,beforeTotal,afterTotal:library.canonicalQuestionCount,added,bossStageFixed,repairRewritten,bridgeRewritten,assetMetadataCopies,beforeCounts,afterCounts,familyBefore,familyAfter,protectedMismatches,quality:{introducedExact,introducedNumberSwaps,lengthIssues},changeSummary:sourceData.summary},null,2));
