import crypto from'node:crypto';import fs from'node:fs';import path from'node:path';import vm from'node:vm';
const repoRoot=path.resolve(process.argv[2]||process.cwd()),CONCEPT='gains-from-trade',PHASE='phase7.5-comparative-advantage-gains-trade-standalone-expansion-v1',PREVIOUS='phase7.4-incentives-standalone-expansion-v1',GENERATED_AT='2026-08-10T11:00:00.000Z',SOURCE_GAME='phase7.5-comparative-advantage-gains-trade-standalone-expansion',artifactRoot=path.join(repoRoot,'validation_artifacts','comparative_advantage_gains_trade_standalone_expansion'),composerRoot=path.join(repoRoot,'build','faculty-build-composer'),libraryPath=path.join(composerRoot,'data','composer_library.js'),registryPath=path.join(composerRoot,'data','composer_registry.json'),manifestPath=path.join(composerRoot,'data','composer_library_manifest.json');fs.mkdirSync(artifactRoot,{recursive:true});
const sha256=v=>crypto.createHash('sha256').update(v).digest('hex'),stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v,idOf=q=>String(q?.id||q?.questionId||''),normalize=v=>String(v).normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase(),answerHash=v=>sha256(normalize(v)),load=raw=>{const c={window:{}};vm.createContext(c);vm.runInContext(raw,c);return c.window.MQ_COMPOSER_LIBRARY;};
const libraryRaw=fs.readFileSync(libraryPath,'utf8'),library=load(libraryRaw);if(!String(library.libraryVersion).endsWith(PREVIOUS))throw new Error(`Expected ${PREVIOUS}; found ${library.libraryVersion}`);const module=library.concepts?.[CONCEPT];if(!module)throw new Error('Gains-from-trade module missing.');const allLocations=m=>[...Object.entries(m.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(m.repairQuestions||[]).map(question=>({pool:'repair',question})),...(m.repairSeedQuestions||[]).map(question=>({pool:'repairSeed',question})),...(m.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))],unique=m=>{const seen=new Set();return allLocations(m).filter(x=>!seen.has(idOf(x.question))&&seen.add(idOf(x.question)));};if(unique(module).length!==46)throw new Error(`Expected 46 baseline records, found ${unique(module).length}.`);
const rewrites={
'ECON-MG-EASY-10':{q:'Two neighbors specialize in the chores for which each gives up less valuable alternative work, then exchange help. Why can both benefit?',options:['Specialization can raise combined output available to share','Exchange makes both neighbors completely self-sufficient','Scarcity disappears once the chores are divided','The faster neighbor must perform every chore'],answer:'Specialization can raise combined output available to share',type:'application',skill:'conceptual_gains_from_trade',depth:'CONCEPTUAL_GAINS',commonError:'Treating trade as zero-sum or assigning every task to the fastest producer.',feedback:'Different opportunity costs can make specialization and voluntary exchange beneficial.'},
'P52B-TRADE-E-001':{q:'Mira gives up 1 report to prepare a presentation; Sol gives up 3 reports. Which fact determines comparative advantage in presentations?',options:['Mira gives up fewer reports per presentation','Sol may complete more total tasks in a day','Mira charges a lower money price after exchange','Sol has a higher wage in an unrelated job'],answer:'Mira gives up fewer reports per presentation',type:'application',skill:'comparative_advantage_definition',depth:'ABSOLUTE_VS_COMPARATIVE',commonError:'Using total output, wages, or prices instead of opportunity cost.',feedback:'Comparative advantage belongs to the lower-opportunity-cost producer.'},
'P52B-TRADE-E-002':{q:'With the same resources, East Farm can harvest 12 crates while West Farm can harvest 8. What does this establish?',options:['East Farm has an absolute advantage in harvesting crates','East Farm must have comparative advantage in every crop','West Farm has the lower opportunity cost of harvesting','Both farms gain equally from every possible exchange'],answer:'East Farm has an absolute advantage in harvesting crates',type:'application',skill:'absolute_advantage_definition',depth:'ABSOLUTE_VS_COMPARATIVE',commonError:'Inferring comparative advantage from productivity alone.',feedback:'Greater output from the same resources establishes absolute, not necessarily comparative, advantage.'},
'P52B-TRADE-H-005':{q:'A region can obtain one turbine by giving up 3 tons of grain through exchange or 5 tons by producing it internally. Which reasoning supports exchange?',options:['Importing the turbine has the lower opportunity cost in grain','Producing internally must be better because it avoids trade','The money price eliminates the need to compare resources','Exchange guarantees equal gains for every resident'],answer:'Importing the turbine has the lower opportunity cost in grain',type:'application',skill:'opportunity_cost_trade',depth:'TERMS_OF_TRADE',commonError:'Preferring self-sufficiency without comparing opportunity costs.',feedback:'Exchange uses resources worth 3 tons rather than 5, freeing 2 tons for other uses.'},
'P52B-TRADE-H-006':{q:'Two firms specialize and create 40 extra units of combined output. A proposed exchange gives all 40 extra units to one firm. What is the strongest conclusion?',options:['Specialization created aggregate gains, but the proposed distribution may not benefit both firms','Comparative advantage is false whenever gains are unequal','Any increase in combined output makes every exchange mutually beneficial','Equal gains are required before specialization can raise output'],answer:'Specialization created aggregate gains, but the proposed distribution may not benefit both firms',type:'application',skill:'distribution_of_trade_gains',depth:'DISTRIBUTION_OF_GAINS',commonError:'Confusing total gains with mutual benefit under a particular exchange.',feedback:'Higher combined output creates potential gains; terms of trade determine how those gains are divided.'},
'P52B-TRADE-EL-003':{q:'A trade rate equals the exporter’s opportunity cost exactly but remains below the importer’s opportunity cost. Which evaluation is precise?',options:['The exporter is indifferent while the importer captures the modeled gain','The exporter captures every gain because it supplies the good','Both parties receive strict and exactly equal gains','Neither party can gain because the rate is on one boundary'],answer:'The exporter is indifferent while the importer captures the modeled gain',type:'application',skill:'terms_of_trade_distribution',depth:'DISTRIBUTION_OF_GAINS',commonError:'Calling a boundary rate a strict mutual gain or assuming gains divide equally.',feedback:'At its own opportunity cost the exporter is indifferent; the importer still saves resources.'}
,'P52B-TRADE-BR-001':{q:'A project lead is faster at every task but delegates data entry. Which concept explains the choice?',options:['A price ceiling that limits payment for outsourced data entry','Absolute advantage because the lead is faster at data entry','Comparative advantage based on the opportunity cost of the lead\'s time','Elimination of scarce time after the work is delegated'],answer:'Comparative advantage based on the opportunity cost of the lead\'s time',type:'bridge',skill:'comparative_advantage_application',depth:'ABSOLUTE_VS_COMPARATIVE',commonError:'Using absolute productivity instead of the opportunity cost of the lead\'s time.',feedback:'Delegation can be efficient when the lead has a higher opportunity cost of doing data entry.'},
'P52B-TRADE-BR-002':{q:'A city can buy snowplow service from a neighboring county for less than the resources required to provide it internally. What does opportunity-cost reasoning suggest?',options:['The city should remain self-sufficient even at a higher resource cost','The neighboring county cannot benefit from any voluntary contract','Money prices make the city\'s forgone alternatives irrelevant','Contracting can free city resources for other services'],answer:'Contracting can free city resources for other services',type:'bridge',skill:'opportunity_cost_trade',depth:'SIMPLE_OPPORTUNITY_COST',commonError:'Ignoring the internal resources forgone when the city provides the service itself.',feedback:'Buying the service at lower opportunity cost frees scarce city resources for other uses.'}
};
const additions={
easy:[
{id:'P75-TRADE-E-007',q:'Ana gives up 2 baskets to make one table; Bo gives up 5 baskets. Who has comparative advantage in tables?',options:['Ana, because she gives up fewer baskets','Bo, because he gives up more baskets','Ana only if she makes more of both goods','Neither, because money prices are missing'],answer:'Ana, because she gives up fewer baskets',skill:'comparative_advantage_given_costs',depth:'FOUNDATIONAL_CONCEPT'},
{id:'P75-TRADE-E-008',q:'One worker can finish more of both tasks than a coworker. Why might the coworker still specialize in one task?',options:['The coworker may have the lower opportunity cost in that task','The faster worker loses absolute advantage after delegation','Comparative advantage requires equal productivity','Specialization removes every tradeoff'],answer:'The coworker may have the lower opportunity cost in that task',skill:'absolute_vs_comparative',depth:'ABSOLUTE_VS_COMPARATIVE'},
{id:'P75-TRADE-E-009',q:'Priya gives up 1 design to write a report; Luis gives up 4 designs. If they specialize by comparative advantage, who writes reports?',options:['Priya, because her opportunity cost is lower','Luis, because his opportunity cost is higher','Both must split report writing equally','Whoever has the higher total output in both tasks'],answer:'Priya, because her opportunity cost is lower',skill:'specialization_pattern',depth:'SPECIALIZATION'},
{id:'P75-TRADE-E-010',q:'Why can specialization according to comparative advantage expand what two producers can consume?',options:['It can increase combined production available for exchange','It guarantees each producer makes every good','It makes opportunity costs identical','It removes scarcity from both producers'],answer:'It can increase combined production available for exchange',skill:'conceptual_gains_from_trade',depth:'CONCEPTUAL_GAINS'}
],
medium:[
{id:'P75-TRADE-M-007',q:'Team A can prepare 12 briefs or 6 charts daily. Team B can prepare 8 briefs or 8 charts. Who has comparative advantage in briefs?',options:['Team A; one brief costs 0.5 chart rather than 1 chart','Team B; it can make more charts','Team A; it has comparative advantage in both outputs','Neither; their maximum outputs differ'],answer:'Team A; one brief costs 0.5 chart rather than 1 chart',skill:'comparative_advantage_calculation',depth:'SIMPLE_OPPORTUNITY_COST',type:'calculation',math:{kind:'comparative',a:[12,6],b:[8,8],good:'x',winner:'A'}},
{id:'P75-TRADE-M-008',q:'Kai needs 2 hours per cabinet and 1 hour per shelf. Ren needs 3 hours per cabinet and 3 hours per shelf. Who has comparative advantage in cabinets?',options:['Kai; a cabinet costs 2 shelves rather than Ren’s 1 shelf','Ren; a cabinet costs 1 shelf rather than Kai’s 2 shelves','Kai; fewer hours always means comparative advantage in both goods','Neither; hours per unit cannot reveal opportunity cost'],answer:'Ren; a cabinet costs 1 shelf rather than Kai’s 2 shelves',skill:'hours_per_unit_opportunity_cost',depth:'SIMPLE_OPPORTUNITY_COST',type:'calculation',math:{kind:'hoursComparative',a:[2,1],b:[3,3],good:'x',winner:'B'}},
{id:'P75-TRADE-M-009',q:'If one mug costs a studio 2 bowls, what is the reciprocal opportunity cost of one bowl?',options:['One-half mug','Two mugs','Four mugs','One mug'],answer:'One-half mug',skill:'reciprocal_opportunity_cost',depth:'RECIPROCAL_OPPORTUNITY_COST',type:'calculation',math:{kind:'reciprocal',value:[2,1],expected:[1,2]}},
{id:'P75-TRADE-M-010',q:'Farm C can grow 24 corn or 12 beans; Farm D can grow 10 corn or 10 beans. Which specialization follows comparative advantage?',options:['Farm C grows corn and Farm D grows beans','Farm C grows beans and Farm D grows corn','Both farms grow only corn','Neither farm can specialize without a money price'],answer:'Farm C grows corn and Farm D grows beans',skill:'specialization_pattern',depth:'SPECIALIZATION',type:'calculation',math:{kind:'specialization',a:[24,12],b:[10,10],xWinner:'A',yWinner:'B'}},
{id:'P75-TRADE-M-011',q:'One lamp costs Ari 2 rugs and costs Bea 6 rugs. Which rate for 1 lamp could provide strict gains to both?',options:['4 rugs per lamp','2 rugs per lamp','6 rugs per lamp','8 rugs per lamp'],answer:'4 rugs per lamp',skill:'terms_of_trade',depth:'TERMS_OF_TRADE',type:'calculation',math:{kind:'strictRate',low:[2,1],high:[6,1],rate:[4,1]}},
{id:'P75-TRADE-M-012',q:'Two workshops each give up exactly 3 frames to produce one desk. What does the basic model imply?',options:['Neither has comparative advantage in desks based on these costs','The workshop with greater desk output must specialize in desks','Both receive strict gains from any desk price','One workshop must have comparative advantage in both goods'],answer:'Neither has comparative advantage in desks based on these costs',skill:'equal_opportunity_costs',depth:'SIMPLE_OPPORTUNITY_COST',math:{kind:'equalCosts',a:[3,1],b:[3,1]}}
],
elite:[
{id:'P75-TRADE-EL-005',q:'A can make 12 X or 24 Y and B can make 10 X or 10 Y. After full specialization, B sends A 4 X for 6 Y. A previously consumed 4 X and 12 Y. What is A\'s gain?',options:['The same 4 X and 6 additional Y','Four additional X and the same Y','Six additional X and 4 additional Y','No gain because A exports output'],answer:'The same 4 X and 6 additional Y',skill:'numerical_gain_one_party',depth:'NUMERICAL_GAIN_ONE_PARTY',type:'calculation',math:{kind:'gains',autarkyA:[4,12],autarkyB:[5,5],productionA:[0,24],productionB:[10,0],postA:[4,18],postB:[6,6],gainA:[0,6],gainB:[1,1]}},
{id:'P75-TRADE-EL-006',q:'C can make 16 cloth or 8 wine; D can make 6 cloth or 12 wine. They fully specialize, and C trades 4 cloth for 4 wine. Before trade, C consumed 12 cloth and 2 wine while D consumed 2 cloth and 8 wine. What are the gains?',options:['C gains 2 wine; D gains 2 cloth','C gains 4 wine; D gains 4 cloth','C gains 2 cloth; D gains 2 wine','Each gains 2 units of both goods'],answer:'C gains 2 wine; D gains 2 cloth',skill:'numerical_gain_both_parties',depth:'NUMERICAL_GAIN_BOTH_PARTIES',type:'calculation',math:{kind:'gains',autarkyA:[12,2],autarkyB:[2,8],productionA:[16,0],productionB:[0,12],postA:[12,4],postB:[4,8],gainA:[0,2],gainB:[2,0]}}
],
legendary:[
{id:'P75-TRADE-L-007',q:'Atlas can produce 18 engines or 36 batteries; Beacon can produce 12 engines or 48 batteries. In batteries per engine, which interval permits strict gains to both?',options:['More than 2 and less than 4 batteries','More than one-fourth and less than one-half battery','At least 2 and at most 4 batteries','More than 4 batteries only'],answer:'More than 2 and less than 4 batteries',skill:'terms_of_trade_range',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'strictBounds',low:[2,1],high:[4,1]}},
{id:'P75-TRADE-L-008',q:'After specialization, Vale has 20 grain and trades 8 grain for 4 cloth. Its autarky bundle was 10 grain and 3 cloth. What is Vale\'s post-trade gain?',options:['Two more grain and 1 more cloth','Eight more grain and 4 more cloth','Two more grain and 4 more cloth','Ten more grain and 1 more cloth'],answer:'Two more grain and 1 more cloth',skill:'post_trade_bundle_gain',depth:'NUMERICAL_GAIN_ONE_PARTY',type:'calculation',math:{kind:'gains',autarkyA:[10,3],autarkyB:[6,4],productionA:[20,0],productionB:[0,8],postA:[12,4],postB:[8,4],gainA:[2,1],gainB:[2,0]}},
{id:'P75-TRADE-L-009',q:'North specializes at 24 fish and South at 12 nets. North trades 8 fish for 4 nets. Their autarky bundles were North 12 fish and 3 nets, South 6 fish and 6 nets. What are their gains?',options:['North gains 4 fish and 1 net; South gains 2 fish and 2 nets','North gains 8 fish and 4 nets; South gains 8 fish and 4 nets','North gains 4 fish and 4 nets; South gains 2 fish and 6 nets','North gains 12 fish and 1 net; South gains 2 fish and 2 nets'],answer:'North gains 4 fish and 1 net; South gains 2 fish and 2 nets',skill:'numerical_gain_both_parties',depth:'NUMERICAL_GAIN_BOTH_PARTIES',type:'calculation',math:{kind:'gains',autarkyA:[12,3],autarkyB:[6,6],productionA:[24,0],productionB:[0,12],postA:[16,4],postB:[8,8],gainA:[4,1],gainB:[2,2]}},
{id:'P75-TRADE-L-010',q:'One tablet costs Red 2 speakers and Blue 5 speakers. Red proposes exporting a tablet for 6 speakers. Why does the proposal fail?',options:['The rate exceeds Blue\'s 5-speaker cost','The rate is below Red\'s 2-speaker cost','Any rate above 2 benefits both','Only integer rates are invalid'],answer:'The rate exceeds Blue\'s 5-speaker cost',skill:'invalid_terms_of_trade',depth:'TERMS_OF_TRADE',type:'calculation',math:{kind:'proposedRate',low:[2,1],high:[5,1],rate:[6,1],strict:false}},
{id:'P75-TRADE-L-011',q:'Specialization yields 14 extra units. Under one exchange, Metro gains 10 units while Harbor gains 4. Which conclusion is accurate?',options:['Both gain, but the terms divide the gain unequally','Unequal gains mean Harbor cannot benefit','Each side must gain 7 units','Only Metro has comparative advantage'],answer:'Both gain, but the terms divide the gain unequally',skill:'distribution_of_trade_gains',depth:'DISTRIBUTION_OF_GAINS',type:'calculation',math:{kind:'sumGains',a:[10,1],b:[4,1],total:[14,1]}},
{id:'P75-TRADE-L-012',q:'Oak can make 20 chairs or 10 desks; Pine can make 12 chairs or 12 desks. Tooling raises Oak\'s desk maximum to 30. What is the new specialization pattern?',options:['Oak makes desks; Pine makes chairs','Oak makes chairs; Pine makes desks','Oak has advantage in both goods','Equal costs remove specialization'],answer:'Oak makes desks; Pine makes chairs',skill:'productivity_shock_comparative_advantage',depth:'DYNAMIC_TRANSFER',type:'calculation',math:{kind:'specialization',a:[20,30],b:[12,12],xWinner:'B',yWinner:'A'}},
{id:'P75-TRADE-L-013',q:'Kite can make 16 maps or 8 models. Lake can make 12 maps or an unknown number of models. If each producer\'s cost of 1 map is 0.5 model, what is Lake\'s model maximum?',options:['6 models','8 models','12 models','24 models'],answer:'6 models',skill:'solve_missing_productivity',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'missingOutput',x:[12,1],costX:[1,2],expectedY:[6,1]}},
{id:'P75-TRADE-L-014',q:'Coast\'s cost of 1 cocoa is 3 tea. Ridge\'s is 6 tea. Expressed as cocoa per tea, which strict range is equivalent?',options:['More than one-sixth and less than one-third','More than one-third and less than one-sixth','More than 3 and less than 6','At least one-sixth and at most one-third'],answer:'More than one-sixth and less than one-third',skill:'reciprocal_terms_of_trade',depth:'RECIPROCAL_OPPORTUNITY_COST',type:'calculation',math:{kind:'reciprocalBounds',low:[3,1],high:[6,1],reciprocalLow:[1,6],reciprocalHigh:[1,3]}},
{id:'P75-TRADE-L-015',q:'Two labs each sacrifice 4 tests to complete 1 prototype. One lab can produce more of both. What does comparative advantage imply?',options:['Equal relative costs give no usual specialization basis','The faster lab has advantage in both outputs','The slower lab must make prototypes','Any exchange creates strict gains'],answer:'Equal relative costs give no usual specialization basis',skill:'equal_opportunity_cost_edge',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'equalCosts',a:[4,1],b:[4,1]}},
{id:'P75-TRADE-L-016',q:'A plan creates a gross resource gain of 18 units but requires 7 units of transport and contracting cost. What net gain remains?',options:['11 units','25 units','18 units','7 units'],answer:'11 units',skill:'transaction_cost_net_gain',depth:'NUMERICAL_GAIN_ONE_PARTY',type:'calculation',math:{kind:'net',gross:[18,1],cost:[7,1],expected:[11,1]}},
{id:'P75-TRADE-L-017',q:'A surgeon needs 1 hour for a procedure and 0.5 hour for records; an assistant needs 4 hours for a procedure and 1 hour for records. Who has comparative advantage in records?',options:['The assistant, whose record costs one-fourth procedure','The surgeon, because the surgeon is faster','The surgeon, whose record costs one-half procedure','Neither, because their hours differ'],answer:'The assistant, whose record costs one-fourth procedure',skill:'professional_task_comparative_advantage',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'hoursComparative',a:[[1,1],[1,2]],b:[[4,1],[1,1]],good:'y',winner:'B'}},
{id:'P75-TRADE-L-018',q:'Mesa specializes at 30 meals and Bay at 15 repairs. Mesa trades 10 meals for 5 repairs. Their autarky bundles were Mesa 15 meals and 4 repairs, Bay 8 meals and 7 repairs. What gains result?',options:['Mesa gains 5 meals and 1 repair; Bay gains 2 meals and 3 repairs','Mesa gains 10 meals and 5 repairs; Bay gains 10 meals and 5 repairs','Mesa gains 5 meals and 5 repairs; Bay gains 2 meals and 7 repairs','Mesa gains 15 meals and 1 repair; Bay gains 2 meals and 3 repairs'],answer:'Mesa gains 5 meals and 1 repair; Bay gains 2 meals and 3 repairs',skill:'community_trade_full_model',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'gains',autarkyA:[15,4],autarkyB:[8,7],productionA:[30,0],productionB:[0,15],postA:[20,5],postB:[10,10],gainA:[5,1],gainB:[2,3]}},
{id:'P75-TRADE-L-019',q:'One machine costs Alpha 2 kits and Beta 6 kits. Compare rates of 3 and 5 kits per machine. Which statement is true?',options:['Both work, but 5 shifts more modeled gain to Alpha','Only the 3-kit rate is between costs','Only the 5-kit rate is between costs','Both divide the gain equally'],answer:'Both work, but 5 shifts more modeled gain to Alpha',skill:'terms_distribution_comparison',depth:'DISTRIBUTION_OF_GAINS',type:'calculation',math:{kind:'twoRates',low:[2,1],high:[6,1],rates:[[3,1],[5,1]]}},
{id:'P75-TRADE-L-020',q:'A problem gives specialization output and a trading rate but no pre-trade consumption bundle. Can a unique numerical consumption gain be found?',options:['No; the autarky comparison is underdetermined','Yes; the rate fixes the autarky bundle','Yes; combined output equals each gain','No; trade gains can never be measured'],answer:'No; the autarky comparison is underdetermined',skill:'autarky_baseline_diagnostic',depth:'FULL_TRADE_MODEL'},
{id:'P75-TRADE-L-021',q:'A technology has increasing rather than constant opportunity cost. Which claim is safest?',options:['Comparative advantage can guide reallocation without universal complete specialization','Both producers must always specialize completely','Opportunity cost becomes irrelevant after exchange','Absolute advantage fixes every output'],answer:'Comparative advantage can guide reallocation without universal complete specialization',skill:'partial_specialization_model_limits',depth:'FULL_TRADE_MODEL'},
{id:'P75-TRADE-L-022',q:'Combined consumption rises by 9 units, but one party gains 11 while the other loses 2. What is the correct evaluation?',options:['Aggregate gain exists, but the trade is not mutually beneficial','Both gain because the combined change is positive','The losing party has advantage in both goods','Each gain must be reset to 4.5'],answer:'Aggregate gain exists, but the trade is not mutually beneficial',skill:'aggregate_vs_mutual_gain',depth:'DISTRIBUTION_OF_GAINS',type:'calculation',math:{kind:'sumGains',a:[11,1],b:[-2,1],total:[9,1]}},
{id:'P75-TRADE-L-023',q:'Delta can make 24 files or 8 reviews; Echo can make 15 files or 10 reviews. Delta\'s review productivity doubles. Who then has comparative advantage in reviews?',options:['Neither; both costs are 1.5 files per review','Echo, because it had the original advantage','Delta, because its productivity doubled','Delta, because it has advantage in both'],answer:'Neither; both costs are 1.5 files per review',skill:'dynamic_equal_cost_case',depth:'DYNAMIC_TRANSFER',type:'calculation',math:{kind:'equalOutputCosts',a:[24,16],b:[15,10]}},
{id:'P75-TRADE-L-024',q:'If 1 lens costs Urban 0.25 sensor and Rural 0.5 sensor, what is the equivalent strict range in lenses per sensor?',options:['More than 2 and less than 4','More than 0.25 and less than 0.5','At least 2 and at most 4','More than 4 only'],answer:'More than 2 and less than 4',skill:'ratio_orientation',depth:'RECIPROCAL_OPPORTUNITY_COST',type:'calculation',math:{kind:'reciprocalBounds',low:[1,4],high:[1,2],reciprocalLow:[2,1],reciprocalHigh:[4,1]}},
{id:'P75-TRADE-L-025',q:'Lumen specializes at 32 lamps and Shade at 16 rugs. Lumen trades 12 lamps for 6 rugs. Autarky bundles were Lumen 16 lamps and 4 rugs, Shade 8 lamps and 8 rugs. What results?',options:['Lumen gains 4 lamps and 2 rugs; Shade gains 4 lamps and 2 rugs','Lumen gains 4 lamps and 6 rugs; Shade gains 4 lamps but loses 2 rugs','Lumen loses 4 lamps and gains 2 rugs; Shade gains 12 lamps and 2 rugs','Each gains only rugs'],answer:'Lumen gains 4 lamps and 2 rugs; Shade gains 4 lamps and 2 rugs',skill:'complete_trade_solution',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'gains',autarkyA:[16,4],autarkyB:[8,8],productionA:[32,0],productionB:[0,16],postA:[20,6],postB:[12,10],gainA:[4,2],gainB:[4,2]}},
{id:'P75-TRADE-L-026',q:'Before specialization, two farms jointly produce 14 wheat and 7 fruit. After specializing, they produce 18 wheat and 9 fruit. What is the combined production change?',options:['4 more wheat and 2 more fruit','18 more wheat and 9 more fruit','4 more fruit and 2 more wheat','No change'],answer:'4 more wheat and 2 more fruit',skill:'specialization_output_change',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'outputGain',before:[14,7],after:[18,9],expected:[4,2]}},
{id:'P75-TRADE-L-027',q:'A static two-good model finds gains from specialization. Which conclusion goes beyond that result alone?',options:['Every long-run trade policy benefits every worker and industry','Lower opportunity cost identifies comparative advantage','Terms inside the bounds can create mutual gains','Specialization can raise output under the assumptions'],answer:'Every long-run trade policy benefits every worker and industry',skill:'comparative_advantage_model_limits',depth:'DYNAMIC_TRANSFER'}
],
boss:[
{id:'P75-TRADE-EB-004',tier:'easyBoss',q:'A baker makes more bread and cakes than a helper. What must be known before assigning both tasks?',options:['Their opportunity costs for bread and cakes','Only the baker\'s total output','The price of imported flour','Whether the helper likes cake'],answer:'Their opportunity costs for bread and cakes',skill:'absolute_vs_comparative',depth:'ABSOLUTE_VS_COMPARATIVE'},
{id:'P75-TRADE-EB-005',tier:'easyBoss',q:'Nia gives up 2 posters per video; Omar gives up 5. Who should specialize in videos?',options:['Nia, because her opportunity cost is lower','Omar, because he gives up more posters','Both, because gains must be equal','Neither, because totals are missing'],answer:'Nia, because her opportunity cost is lower',skill:'specialization_given_costs',depth:'SPECIALIZATION',math:{kind:'givenComparative',a:[2,1],b:[5,1],winner:'A'}},
{id:'P75-TRADE-MB-004',tier:'mediumBoss',q:'A can produce 16 apples or 8 pears; B can produce 9 apples or 9 pears. Who has comparative advantage in apples?',options:['A; one apple costs 0.5 pear','B; one apple costs 1 pear','A; it has advantage in both','Neither; only money costs count'],answer:'A; one apple costs 0.5 pear',skill:'comparative_advantage_calculation',depth:'SIMPLE_OPPORTUNITY_COST',type:'calculation',math:{kind:'comparative',a:[16,8],b:[9,9],good:'x',winner:'A'}},
{id:'P75-TRADE-MB-005',tier:'mediumBoss',q:'One file costs Town 3 reports and City 7 reports. Which rate can strictly benefit both?',options:['5 reports per file','3 reports per file','7 reports per file','9 reports per file'],answer:'5 reports per file',skill:'terms_of_trade',depth:'TERMS_OF_TRADE',type:'calculation',math:{kind:'strictRate',low:[3,1],high:[7,1],rate:[5,1]}},
{id:'P75-TRADE-FB-004',tier:'finalBoss',q:'One drone costs East 1.5 radios and West 4 radios. At 1.5 radios per drone, what happens?',options:['East is indifferent while West can gain','Both receive strict gains','West is indifferent while East can gain','The rate is strictly inside the bounds'],answer:'East is indifferent while West can gain',skill:'terms_boundary',depth:'TERMS_OF_TRADE',type:'calculation',math:{kind:'boundary',exporter:[3,2],importer:[4,1],rate:[3,2]}},
{id:'P75-TRADE-FB-005',tier:'finalBoss',q:'Two producers have equal opportunity costs for both goods. What does the basic model predict?',options:['No comparative-advantage basis for usual specialization','The higher-output producer has advantage in both','Each must specialize in a different good','Every exchange produces strict gains'],answer:'No comparative-advantage basis for usual specialization',skill:'equal_opportunity_cost_edge',depth:'SIMPLE_OPPORTUNITY_COST'}
],
legendaryBoss:[
{id:'P75-TRADE-LB-004',q:'Arbor specializes at 28 timber and Basin at 14 tools. Arbor trades 8 timber for 4 tools. Autarky bundles were Arbor 14 timber and 3 tools, Basin 6 timber and 7 tools. What gains result?',options:['Arbor gains 6 timber and 1 tool; Basin gains 2 timber and 3 tools','Arbor gains 8 timber and 4 tools; Basin gains 8 timber and 4 tools','Arbor gains 6 timber and 4 tools; Basin gains 2 timber and 7 tools','Arbor gains 14 timber and 1 tool; Basin gains 2 timber and 3 tools'],answer:'Arbor gains 6 timber and 1 tool; Basin gains 2 timber and 3 tools',skill:'complete_trade_solution',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'gains',autarkyA:[14,3],autarkyB:[6,7],productionA:[28,0],productionB:[0,14],postA:[20,4],postB:[8,10],gainA:[6,1],gainB:[2,3]},bossStage:'opening'},
{id:'P75-TRADE-LB-005',q:'A chip costs Quartz 2 screens and Sable 5 screens. Quartz offers 1 chip for 5 screens. Which result is precise?',options:['Quartz gains while Sable is indifferent','Both receive strict and equal gains','Quartz is indifferent while Sable gains','Neither can gain at an integer rate'],answer:'Quartz gains while Sable is indifferent',skill:'terms_boundary_distribution',depth:'DISTRIBUTION_OF_GAINS',type:'calculation',math:{kind:'boundary',exporter:[2,1],importer:[5,1],rate:[5,1]},bossStage:'middle'},
{id:'P75-TRADE-LB-006',q:'Cedar can make 30 boards or 10 doors; Dune can make 16 boards or 8 doors. A tool doubles Dune\'s board output. What specialization follows?',options:['Dune makes boards; Cedar makes doors','Cedar makes boards; Dune makes doors','Cedar has advantage in both','Equal costs remove specialization'],answer:'Dune makes boards; Cedar makes doors',skill:'productivity_shock_comparative_advantage',depth:'DYNAMIC_TRANSFER',type:'calculation',math:{kind:'specialization',a:[30,10],b:[32,8],xWinner:'B',yWinner:'A'},bossStage:'final'},
{id:'P75-TRADE-LB-007',q:'Orchid specializes at 36 flowers and Reed at 18 baskets. Orchid trades 12 flowers for 6 baskets. Autarky bundles were Orchid 18 flowers and 4 baskets, Reed 9 flowers and 9 baskets. What gains result?',options:['Orchid gains 6 flowers and 2 baskets; Reed gains 3 flowers and 3 baskets','Orchid gains 12 flowers and 6 baskets; Reed gains 12 flowers and 6 baskets','Orchid gains 6 flowers and 6 baskets; Reed gains 3 flowers and 9 baskets','Orchid gains 18 flowers and 2 baskets; Reed gains 3 flowers and 3 baskets'],answer:'Orchid gains 6 flowers and 2 baskets; Reed gains 3 flowers and 3 baskets',skill:'numerical_gain_both_parties',depth:'NUMERICAL_GAIN_BOTH_PARTIES',type:'calculation',math:{kind:'gains',autarkyA:[18,4],autarkyB:[9,9],productionA:[36,0],productionB:[0,18],postA:[24,6],postB:[12,12],gainA:[6,2],gainB:[3,3]},bossStage:'opening'},
{id:'P75-TRADE-LB-008',q:'One turbine costs Haven 3 grain and Isle 7 grain. Compare rates of 4 and 6 grain per turbine. Which shifts more gain toward Haven while benefiting both?',options:['The 6-grain rate','The 4-grain rate','Neither rate is inside the bounds','Both divide gains identically'],answer:'The 6-grain rate',skill:'terms_distribution_comparison',depth:'DISTRIBUTION_OF_GAINS',type:'calculation',math:{kind:'twoRates',low:[3,1],high:[7,1],rates:[[4,1],[6,1]]},bossStage:'middle'},
{id:'P75-TRADE-LB-009',q:'Peak specializes at 40 services and Glen at 20 devices. Peak trades 16 services for 8 devices. Autarky bundles were Peak 20 services and 6 devices, Glen 10 services and 10 devices. What gains result?',options:['Peak gains 4 services and 2 devices; Glen gains 6 services and 2 devices','Peak gains 16 services and 8 devices; Glen gains 16 services and 8 devices','Peak gains 4 services and 8 devices; Glen gains 6 services and 10 devices','Peak loses 4 services while Glen gains 6 services'],answer:'Peak gains 4 services and 2 devices; Glen gains 6 services and 2 devices',skill:'complete_trade_solution',depth:'FULL_TRADE_MODEL',type:'calculation',math:{kind:'gains',autarkyA:[20,6],autarkyB:[10,10],productionA:[40,0],productionB:[0,20],postA:[24,8],postB:[16,12],gainA:[4,2],gainB:[6,2]},bossStage:'final'}
],
repair:[
{id:'P75-TRADE-R-004',q:'When two producers face different tradeoffs, which one holds comparative advantage in an activity?',options:['The producer with lower opportunity cost','The producer who gives up more','The producer with the highest wage','The producer who makes most of everything'],answer:'The producer with lower opportunity cost',skill:'lower_opportunity_cost',depth:'FOUNDATIONAL_CONCEPT'},
{id:'P75-TRADE-R-005',q:'If one producer makes more of both goods, must that producer make both?',options:['No; specialization depends on relative opportunity costs','Yes; absolute advantage determines both assignments','Yes; the slower producer should never produce','No; productivity data never matter'],answer:'No; specialization depends on relative opportunity costs',skill:'absolute_vs_comparative',depth:'ABSOLUTE_VS_COMPARATIVE'},
{id:'P75-TRADE-R-006',q:'If 1 X costs 2 Y, what is the cost of 1 Y?',options:['One-half X','Two X','Four X','One X'],answer:'One-half X',skill:'reciprocal_opportunity_cost',depth:'RECIPROCAL_OPPORTUNITY_COST',type:'calculation',math:{kind:'reciprocal',value:[2,1],expected:[1,2]}},
{id:'P75-TRADE-R-007',q:'Does higher combined production make every proposed exchange beneficial?',options:['No; the trading terms still determine who gains','Yes; every exchange shares the output','Yes; gains are always equal','No; specialization cannot raise output'],answer:'No; the trading terms still determine who gains',skill:'specialization_vs_trade_gains',depth:'CONCEPTUAL_GAINS'},
{id:'P75-TRADE-R-008',q:'A trading rate equals one producer\'s opportunity cost. Is that producer strictly better off?',options:['No; that producer may be indifferent','Yes; every boundary rate gives strict gains','Yes; gains must be equal','No; both must be indifferent'],answer:'No; that producer may be indifferent',skill:'terms_boundary',depth:'TERMS_OF_TRADE'}
],
bridge:[
{id:'P75-TRADE-BR-003',q:'Scarcity forces two communities to choose how to use labor. Why can specialization help?',options:['It directs labor toward lower-opportunity-cost tasks','It removes limited resources','It guarantees equal consumption','It makes workers equally productive'],answer:'It directs labor toward lower-opportunity-cost tasks',skill:'scarcity_to_specialization',depth:'SPECIALIZATION',secondaryConceptIds:['scarcity-and-tradeoffs']},
{id:'P75-TRADE-BR-004',q:'How does a PPF help identify comparative advantage?',options:['Its tradeoff reveals opportunity cost','Its size alone identifies advantage','It removes the need to compare alternatives','It proves every trade beneficial'],answer:'Its tradeoff reveals opportunity cost',skill:'ppf_to_comparative_advantage',depth:'SIMPLE_OPPORTUNITY_COST',secondaryConceptIds:['production-possibilities']},
{id:'P75-TRADE-BR-005',q:'Opportunity cost identifies comparative advantage. What is the next textbook link?',options:['Specialize in the lower-cost activity','Assign all tasks to the faster producer','Require equal gains before producing','Replace scarcity with self-sufficiency'],answer:'Specialize in the lower-cost activity',skill:'opportunity_cost_to_specialization',depth:'SPECIALIZATION',secondaryConceptIds:['opportunity-cost']},
{id:'P75-TRADE-BR-006',q:'Why can terms of trade connect specialization to mutual gain?',options:['A rate between costs can let both sides save resources','Any rate guarantees equal gains','The rate erases tradeoffs','Only a boundary rate makes both better off'],answer:'A rate between costs can let both sides save resources',skill:'specialization_to_mutual_gain',depth:'CONCEPTUAL_GAINS'}
],
hard:[
{id:'P75-TRADE-H-007',q:'River can produce 18 X or 6 Y; Hill can produce 12 X or 8 Y. What are their reciprocal costs of 1 Y?',options:['River: 3 X; Hill: 1.5 X','River: one-third X; Hill: two-thirds X','River: 12 X; Hill: 18 X','River: 2 X; Hill: 3 X'],answer:'River: 3 X; Hill: 1.5 X',skill:'reciprocal_opportunity_cost',depth:'RECIPROCAL_OPPORTUNITY_COST',type:'calculation',math:{kind:'reciprocalOutputs',a:[18,6],b:[12,8],expectedA:[3,1],expectedB:[3,2]}},
{id:'P75-TRADE-H-008',q:'North can make 20 chips or 10 sensors; South can make 12 chips or 12 sensors. A technology change lets North make 40 sensors with unchanged chip capacity. What changes?',options:['North gains comparative advantage in sensors and South in chips','North keeps comparative advantage in chips because its chip output is unchanged','South gains comparative advantage in both goods','Equal opportunity costs eliminate specialization'],answer:'North gains comparative advantage in sensors and South in chips',skill:'dynamic_comparative_advantage',depth:'DYNAMIC_TRANSFER',type:'calculation',math:{kind:'specialization',a:[20,40],b:[12,12],xWinner:'B',yWinner:'A'}},
{id:'P75-TRADE-H-009',q:'Ava’s cost of one crate is 2 sacks; Ben’s is 5 sacks. At exactly 2 sacks per crate, which statement is correct?',options:['Ava is indifferent and Ben can gain from buying the crate','Both receive strict gains from the trade','Ben is indifferent and Ava captures every gain','The rate lies strictly between their opportunity costs'],answer:'Ava is indifferent and Ben can gain from buying the crate',skill:'terms_of_trade_boundary',depth:'TERMS_OF_TRADE',type:'calculation',math:{kind:'boundary',exporter:[2,1],importer:[5,1],rate:[2,1]}},
{id:'P75-TRADE-H-010',q:'One bolt costs East 0.5 panel and West 1.25 panels. Which interval states strict mutual-gain rates in panels per bolt?',options:['More than 0.5 but less than 1.25 panels per bolt','More than 2 but less than 4 bolts per panel','At least 0.5 and at most 1.25 panels per bolt','Less than 0.5 panels per bolt only'],answer:'More than 0.5 but less than 1.25 panels per bolt',skill:'terms_of_trade_range',depth:'TERMS_OF_TRADE',type:'calculation',math:{kind:'strictBounds',low:[1,2],high:[5,4]}},
{id:'P75-TRADE-H-011',q:'A consultant completes more audits and presentations than an associate. A manager concludes the consultant should do both. What is missing?',options:['The opportunity cost of assigning the consultant to each task','The consultant’s absolute output in both tasks','A guarantee that specialization divides gains equally','The money price of international exports'],answer:'The opportunity cost of assigning the consultant to each task',skill:'comparative_advantage_argument',depth:'ABSOLUTE_VS_COMPARATIVE'},
{id:'P75-TRADE-H-012',q:'Specialization raises combined output, but a proposed exchange rate lies above both producers’ costs for the exported good. What follows?',options:['Higher output creates potential gains, but this rate will not benefit both sides','Every feasible exchange shares the production gain','The higher-cost producer now has comparative advantage','Both sides are strictly better off because specialization occurred'],answer:'Higher output creates potential gains, but this rate will not benefit both sides',skill:'specialization_vs_trade_gains',depth:'CONCEPTUAL_GAINS'}
],
};
const teachingByDepth={FOUNDATIONAL_CONCEPT:['Confusing productivity or price with the relevant opportunity-cost rule.','Comparative advantage is determined by relative opportunity cost.'],ABSOLUTE_VS_COMPARATIVE:['Using greater output alone to assign comparative advantage.','Absolute advantage concerns productivity; comparative advantage concerns lower opportunity cost.'],SIMPLE_OPPORTUNITY_COST:['Computing or comparing the opportunity costs in the wrong direction.','Compute the forgone alternative per unit, then select the lower opportunity cost.'],RECIPROCAL_OPPORTUNITY_COST:['Repeating a ratio instead of taking its reciprocal.','Reverse both the goods and the ratio when changing opportunity-cost orientation.'],SPECIALIZATION:['Assigning every activity to the absolutely more productive producer.','In the textbook model, specialization follows comparative advantage.'],TERMS_OF_TRADE:['Including a boundary or a rate outside the two opportunity costs as a strict mutual gain.','A strict mutual-gain rate lies strictly between the relevant opportunity costs.'],CONCEPTUAL_GAINS:['Assuming higher combined output makes every possible exchange mutually beneficial.','Specialization creates potential output gains; the trading terms determine whether both sides gain.'],NUMERICAL_GAIN_ONE_PARTY:['Comparing a post-trade bundle with specialization output instead of the stated autarky bundle.','Subtract the stated autarky bundle from post-trade consumption good by good.'],NUMERICAL_GAIN_BOTH_PARTIES:['Using the wrong autarky bundle or failing to conserve the traded goods.','Derive both post-trade bundles and compare each with its stated autarky bundle.'],FULL_TRADE_MODEL:['Skipping a required link among opportunity cost, specialization, exchange, and the autarky comparison.','Work through the complete model in order and keep the ratio units fixed.'],DISTRIBUTION_OF_GAINS:['Equating positive aggregate gains with equal or universal individual gains.','Total gains and their distribution are distinct; terms of trade allocate the modeled surplus.'],DYNAMIC_TRANSFER:['Treating comparative advantage as fixed after productivity or opportunity costs change.','Recompute relative opportunity costs after a change and respect the model limits.']};
const depthById={
'ECON-MG-EASY-10':'CONCEPTUAL_GAINS','P52B-TRADE-E-001':'ABSOLUTE_VS_COMPARATIVE','P52B-TRADE-E-002':'ABSOLUTE_VS_COMPARATIVE','P52B-TRADE-E-003':'ABSOLUTE_VS_COMPARATIVE','P52B-TRADE-E-004':'SPECIALIZATION','P52B-TRADE-E-005':'CONCEPTUAL_GAINS',
'P52B-TRADE-M-001':'SIMPLE_OPPORTUNITY_COST','P52B-TRADE-M-002':'SIMPLE_OPPORTUNITY_COST','P52B-TRADE-M-003':'SPECIALIZATION','P52B-TRADE-M-004':'TERMS_OF_TRADE','P52B-TRADE-M-005':'SIMPLE_OPPORTUNITY_COST','P52B-TRADE-M-006':'CONCEPTUAL_GAINS',
'P52B-TRADE-H-001':'SPECIALIZATION','P52B-TRADE-H-002':'TERMS_OF_TRADE','P52B-TRADE-H-003':'ABSOLUTE_VS_COMPARATIVE','P52B-TRADE-H-004':'CONCEPTUAL_GAINS','P52B-TRADE-H-005':'TERMS_OF_TRADE','P52B-TRADE-H-006':'DISTRIBUTION_OF_GAINS',
'P52B-TRADE-EL-001':'SIMPLE_OPPORTUNITY_COST','P52B-TRADE-EL-002':'FULL_TRADE_MODEL','P52B-TRADE-EL-003':'DISTRIBUTION_OF_GAINS','P52B-TRADE-EL-004':'DYNAMIC_TRANSFER',
'P52B-TRADE-L-001':'FULL_TRADE_MODEL','P52B-TRADE-L-002':'ABSOLUTE_VS_COMPARATIVE','P52B-TRADE-L-003':'DISTRIBUTION_OF_GAINS','P52B-TRADE-L-004':'DYNAMIC_TRANSFER','P52B-TRADE-L-005':'NUMERICAL_GAIN_ONE_PARTY','P52B-TRADE-L-006':'NUMERICAL_GAIN_ONE_PARTY',
'P52B-TRADE-B1-001':'FOUNDATIONAL_CONCEPT','P52B-TRADE-B1-002':'CONCEPTUAL_GAINS','P52B-TRADE-B1-003':'FOUNDATIONAL_CONCEPT','P52B-TRADE-B2-001':'SIMPLE_OPPORTUNITY_COST','P52B-TRADE-B2-002':'TERMS_OF_TRADE','P52B-TRADE-B2-003':'ABSOLUTE_VS_COMPARATIVE','P52B-TRADE-B3-001':'CONCEPTUAL_GAINS','P52B-TRADE-B3-002':'DISTRIBUTION_OF_GAINS','P52B-TRADE-B3-003':'DYNAMIC_TRANSFER',
'P52B-TRADE-LB-001':'FULL_TRADE_MODEL','P52B-TRADE-LB-002':'ABSOLUTE_VS_COMPARATIVE','P52B-TRADE-LB-003':'NUMERICAL_GAIN_ONE_PARTY','P52B-TRADE-R-001':'FOUNDATIONAL_CONCEPT','P52B-TRADE-R-002':'TERMS_OF_TRADE','P52B-TRADE-R-003':'CONCEPTUAL_GAINS','ECON-MG-CORE-TRADE-30010':'CONCEPTUAL_GAINS','P52B-TRADE-BR-001':'ABSOLUTE_VS_COMPARATIVE','P52B-TRADE-BR-002':'SIMPLE_OPPORTUNITY_COST'};
const mathById={
'P52B-TRADE-E-001':{kind:'givenComparative',a:[1,1],b:[3,1],winner:'A'},'P52B-TRADE-E-002':{kind:'absolute',a:[12,1],b:[8,1],winner:'A'},'P75-TRADE-E-007':{kind:'givenComparative',a:[2,1],b:[5,1],winner:'A'},'P75-TRADE-E-009':{kind:'givenComparative',a:[1,1],b:[4,1],winner:'A'},
'P52B-TRADE-M-001':{kind:'comparative',a:[8,4],b:[6,6],good:'x',winner:'A'},'P52B-TRADE-M-002':{kind:'comparative',a:[12,3],b:[8,4],good:'y',winner:'B'},'P52B-TRADE-M-003':{kind:'specialization',a:[20,10],b:[12,12],xWinner:'A',yWinner:'B'},'P52B-TRADE-M-004':{kind:'strictRate',low:[2,1],high:[5,1],rate:[3,1]},'P52B-TRADE-M-005':{kind:'givenComparative',a:[3,1],b:[7,1],winner:'A'},
'P52B-TRADE-H-001':{kind:'specialization',a:[6,3],b:[8,8],xWinner:'A',yWinner:'B'},'P52B-TRADE-H-002':{kind:'strictBounds',low:[2,1],high:[3,1]},'P52B-TRADE-H-005':{kind:'savings',domestic:[5,1],imported:[3,1],expected:[2,1]},'P52B-TRADE-H-006':{kind:'sumGains',a:[40,1],b:[0,1],total:[40,1]},
'P52B-TRADE-EL-001':{kind:'givenComparative',a:[1,4],b:[2,5],winner:'A'},'P52B-TRADE-L-001':{kind:'strictBounds',low:[2,1],high:[4,1]},'P52B-TRADE-L-005':{kind:'net',gross:[20,1],cost:[25,1],expected:[-5,1]},'P52B-TRADE-L-006':{kind:'savings',domestic:[6,1],imported:[4,1],expected:[2,1]},'P52B-TRADE-B2-001':{kind:'givenComparative',a:[1,1],b:[3,1],winner:'A'},'P52B-TRADE-LB-001':{kind:'strictBounds',low:[2,1],high:[4,1]},'P52B-TRADE-LB-003':{kind:'net',gross:[100,1],cost:[30,1],expected:[70,1]}};
const questionHash=q=>sha256(JSON.stringify(stable({q:q.q,options:q.options,aHash:q.aHash,type:q.type,difficulty:q.difficulty,primarySkill:q.primarySkill,repairSkill:q.repairSkill,tradeDepthCategory:q.tradeDepthCategory,tradeMath:q.tradeMath}))),snapshot=q=>({id:idOf(q),q:q.q,options:[...(q.options||[])],aHash:q.aHash,type:q.type,difficulty:q.difficulty,canonicalDifficulty:q.canonicalDifficulty,primarySkill:q.primarySkill,repairSkill:q.repairSkill,commonError:q.commonError,feedback:q.feedback,tradeDepthCategory:q.tradeDepthCategory,tradeMath:q.tradeMath,sourceCurationPhase:q.sourceCurationPhase});
function balance(options,answer){const out=[...options],correct=out.indexOf(answer);if(correct<0)throw new Error(`Answer missing: ${answer}`);const n=answer.length;if(out.every((x,i)=>i===correct||x.length<n)){const i=out.findIndex((_,j)=>j!==correct);out[i]+=' under an incorrect opportunity-cost interpretation';}return out;}
function lesson(depth){return teachingByDepth[depth]||teachingByDepth.FOUNDATIONAL_CONCEPT;}
function rewrite(q,s,pool,order){const before=snapshot(q),[common,feedback]=lesson(s.depth);Object.assign(q,{q:s.q,options:balance(s.options,s.answer),aHash:answerHash(s.answer),type:s.type||q.type||'application',primarySkill:s.skill||q.primarySkill,repairSkill:s.repairSkill||s.skill||q.repairSkill,commonError:s.commonError||common,feedback:s.feedback||feedback,primaryConceptId:CONCEPT,secondaryConceptIds:[...(s.secondaryConceptIds||q.secondaryConceptIds||[])],tradeDepthCategory:s.depth,tradeMath:s.math||mathById[idOf(q)]||q.tradeMath,sourceCurationPhase:PHASE});q.sourceHash=questionHash(q);q.sourceOccurrences=(q.sourceOccurrences||[]).filter(x=>x.sourceCurationPhase!==PHASE);q.sourceOccurrences.push({sourceGame:SOURCE_GAME,sourceFile:'validation_artifacts/comparative_advantage_gains_trade_standalone_expansion/comparative_advantage_question_changes.json',sourceGlobal:pool==='bridge'?'microSkillBridgePools':'questions',sourcePool:pool,routeKey:q.repairSkill,sourceRecordOrder:order,sourceId:q.sourceId,sourceHash:q.sourceHash,sourceCurationPhase:PHASE});return{id:idOf(q),concept:CONCEPT,pool,action:'REWRITE',before,after:snapshot(q)};}
function create(s,pool,order,sourceId){const isBoss=pool==='boss',isLB=pool==='legendaryBoss',isRepair=pool==='repair',isBridge=pool==='bridge',stored=isBoss?s.tier:pool,canonical=isBoss?({easyBoss:'easy',mediumBoss:'medium',finalBoss:'hard'})[s.tier]:isLB?'legendary':isRepair||isBridge?'unknown':pool,difficulty=isBoss?s.tier:isLB?'legendaryBoss':isRepair?'microRepair':isBridge?'microBridge':pool,role=isBoss?'boss':isLB?'legendaryBoss':isRepair?'repair':isBridge?'bridge':pool==='elite'?'elite':pool==='legendary'?'legendary':'main',[common,feedback]=lesson(s.depth),options=balance(s.options,s.answer);const q={id:s.id,sourceGame:SOURCE_GAME,q:s.q,options,tag:'comparative advantage',type:s.type||({repair:'application',bridge:'bridge'}[pool]||'application'),objective:'LO1.5',difficulty,conceptCluster:'comparative_advantage_and_trade',primarySkill:s.skill,secondarySkills:[...(s.secondarySkills||[])],repairSkill:s.repairSkill||s.skill,commonError:s.commonError||common,feedback:s.feedback||feedback,aHash:answerHash(s.answer),canonicalId:s.id,sourceId,sourceChapter:[1],sourcePool:isRepair||isBridge?s.skill:stored,primaryConceptId:CONCEPT,secondaryConceptIds:[...(s.secondaryConceptIds||[])],instructionalRole:role,canonicalDifficulty:canonical,originalSourcePool:isRepair||isBridge?s.skill:stored,originalBossTier:isBoss?s.tier:isLB?'legendaryBoss':null,tradeDepthCategory:s.depth,tradeMath:s.math||mathById[s.id],sourceCurationPhase:PHASE};if(isBoss)q.boss=({easyBoss:'Checkpoint One',mediumBoss:'Checkpoint Two',finalBoss:'Final Checkpoint'})[s.tier];if(isLB)q.bossStage=s.bossStage||['opening','middle','final'][order%3];q.sourceHash=questionHash(q);q.sourceOccurrences=[{sourceGame:SOURCE_GAME,sourceFile:'validation_artifacts/comparative_advantage_gains_trade_standalone_expansion/comparative_advantage_question_changes.json',sourceGlobal:isRepair?'microSkillRepairPools':isBridge?'microSkillBridgePools':'questions',sourcePool:q.sourcePool,routeKey:q.repairSkill,sourceRecordOrder:order,sourceId,sourceHash:q.sourceHash,sourceCurationPhase:PHASE}];return q;}
const baseline=unique(module),review=baseline.map(({pool,question})=>({id:idOf(question),pool,action:rewrites[idOf(question)]?'REWRITE':'KEEP'})),changes=[];let ro=0;for(const{pool,question}of allLocations(module))if(rewrites[idOf(question)])changes.push(rewrite(question,rewrites[idOf(question)],pool,ro++));const missing=Object.keys(rewrites).filter(id=>!changes.some(c=>c.id===id));if(missing.length)throw new Error(`Missing rewrites: ${missing}`);let ordinal=0;for(const[pool,specs]of Object.entries(additions)){const target=pool==='repair'?module.repairQuestions:pool==='bridge'?module.bridgeQuestions:module.questions[pool],ids=new Set(specs.map(s=>s.id));for(let i=target.length-1;i>=0;i--)if(ids.has(idOf(target[i])))target.splice(i,1);for(const s of specs){const q=create(s,pool,ordinal,7500001+ordinal++);target.push(q);changes.push({id:q.id,concept:CONCEPT,pool:pool==='boss'?s.tier:pool,action:'ADD',before:null,after:snapshot(q)});}}
for(const{pool,question:q}of unique(module)){q.tradeDepthCategory=q.tradeDepthCategory||depthById[idOf(q)];if(!q.tradeDepthCategory)throw new Error(`No depth category: ${idOf(q)}`);q.tradeMath=q.tradeMath||mathById[idOf(q)];if(/\d/.test(q.q)&&!q.tradeMath)throw new Error(`No trade math metadata for numeric record: ${idOf(q)}`);const[newCommon,newFeedback]=lesson(q.tradeDepthCategory);q.commonError=q.commonError||newCommon;q.feedback=q.feedback||newFeedback;q.repairSkill=q.repairSkill||q.primarySkill;q.sourceHash=questionHash(q);}module.questions.legendaryBoss.forEach((q,i)=>q.bossStage=['opening','middle','final'][i%3]);
const repairIds=module.repairQuestions.map(idOf),bridgeIds=module.bridgeQuestions.map(idOf),allSkills=[...new Set(unique(module).flatMap(x=>[x.question.primarySkill,x.question.repairSkill]).filter(Boolean))];module.microSkillRepairPools=Object.fromEntries(allSkills.map(skill=>[skill,repairIds]));module.skillRepairSeedPools={core_trade:['ECON-MG-CORE-TRADE-30010']};module.microSkillBridgePools=Object.fromEntries(allSkills.map(skill=>[skill,bridgeIds]));
const expected={easy:10,medium:12,hard:12,elite:6,legendary:27,calculation:0,boss:15,legendaryBoss:9,integration:0};for(const[p,n]of Object.entries(expected))if((module.questions[p]||[]).length!==n)throw new Error(`${p}: ${module.questions[p]?.length}/${n}`);if(module.repairQuestions.length!==8||module.repairSeedQuestions.length!==1||module.bridgeQuestions.length!==6)throw new Error('Auxiliary counts mismatch.');if(unique(module).length!==106)throw new Error(`Expected 106, found ${unique(module).length}`);
const entry=library.registry.concepts.find(x=>x.canonicalConceptId===CONCEPT),main=[...module.questions.easy,...module.questions.medium,...module.questions.hard,...module.questions.elite,...module.questions.legendary,...module.questions.boss,...module.questions.legendaryBoss],includedSkills=[...new Set(unique(module).map(x=>x.question.primarySkill).filter(Boolean))].sort();Object.assign(entry,{includedSkills,sourceGames:[...new Set([...(entry.sourceGames||[]),SOURCE_GAME])].sort(),questionCountByRole:{boss:15,bridge:6,calculation:0,elite:6,integration:0,legendary:27,legendaryBoss:9,main:34,repair:8,repairSeed:1},questionCountByDifficulty:{easy:15,elite:6,hard:17,legendary:36,medium:17,unknown:15},repairCoverage:{directSkillMatches:8,mainWithUsableSkill:main.length},bridgeCoverage:{directSkillMatches:6,mainWithUsableSkill:main.length},calculationCoverage:unique(module).filter(x=>x.question.type==='calculation').length,graphCoverage:0,instructionalClassification:'Standalone-ready dual-depth',coverageStatus:'ready-focused',coverageStatusLabel:'Ready for focused use',coverageStatusNote:'Macro-safe ordinary progression with numerical gains confined to Elite, Legendary, and Legendary Boss; deep Micro-level full-model coverage; diagnostic Repair and genuine conceptual Bridges.',coverageFloorVersion:PHASE,notes:'Phase 7.5 matured the shared General/Micro/Macro Comparative Advantage and Gains from Trade bank without merging the later international-trade-and-trade-policy bank.'});
const registry=JSON.parse(fs.readFileSync(registryPath,'utf8')),fileEntry=registry.concepts.find(x=>x.canonicalConceptId===CONCEPT);Object.assign(fileEntry,JSON.parse(JSON.stringify(entry)));const previousVersion=library.libraryVersion;library.libraryVersion=`${previousVersion}-${PHASE}`;library.sourceCurationPhase=PHASE;library.generatedAt=GENERATED_AT;library.canonicalQuestionCount=6639;library.registry.generatedAt=GENERATED_AT;library.registry.libraryVersion=library.libraryVersion;library.registry.canonicalQuestionCount=6639;registry.generatedAt=GENERATED_AT;registry.libraryVersion=library.libraryVersion;registry.canonicalQuestionCount=6639;delete library.librarySha256;library.librarySha256=sha256(JSON.stringify(stable(library)));registry.librarySha256=library.librarySha256;const serialized=`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(library)};\n`;fs.writeFileSync(libraryPath,serialized,'utf8');fs.writeFileSync(registryPath,`${JSON.stringify(registry,null,2)}\n`,'utf8');const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));Object.assign(manifest,{canonicalQuestionCount:6639,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,generatedAt:GENERATED_AT});fs.writeFileSync(manifestPath,`${JSON.stringify(manifest,null,2)}\n`,'utf8');
const changeArtifact={phase:PHASE,concept:CONCEPT,reviewedBaselineRecords:review,actions:{KEEP:review.filter(x=>x.action==='KEEP').length,REWRITE:changes.filter(x=>x.action==='REWRITE').length,ADD:changes.filter(x=>x.action==='ADD').length,RELOCATE_REPAIR:0,RELOCATE_BRIDGE:0,MOVE_ELITE:0,MOVE_LEGENDARY:0,REMOVE:0},changes};fs.writeFileSync(path.join(artifactRoot,'comparative_advantage_question_changes.json'),`${JSON.stringify(changeArtifact,null,2)}\n`,'utf8');const counts={totalCanonical:106,easy:10,medium:12,hard:12,elite:6,legendary:27,easyBoss:5,mediumBoss:5,finalBoss:5,legendaryBoss:9,repair:8,repairSeed:1,bridge:6},provenance={phase:PHASE,generatedAt:GENERATED_AT,repository:repoRoot,concept:CONCEPT,before:{libraryVersion:previousVersion,librarySha256:load(libraryRaw).librarySha256,libraryFileSha256:sha256(libraryRaw),conceptCanonicalQuestions:46},after:{libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,libraryFileSha256:sha256(serialized),conceptCanonicalQuestions:106},counts,actions:{reviewed:46,kept:38,rewritten:8,added:60,relocatedRepair:0,relocatedBridge:0,movedElite:0,movedLegendary:0,removed:0},otherConceptQuestionContentChanged:false,protectedConceptIds:['scarcity-and-tradeoffs','opportunity-cost','marginal-analysis','incentives','international-trade-and-trade-policy'],graphQuestionsChanged:false,graphAssetsChanged:false};fs.writeFileSync(path.join(composerRoot,`${PHASE}.json`),`${JSON.stringify(provenance,null,2)}\n`,'utf8');for(const file of[path.join(repoRoot,'build','index.html'),path.join(composerRoot,'index.html')])fs.writeFileSync(file,fs.readFileSync(file,'utf8').replaceAll('20260810-incentives-standalone-v1','20260810-comparative-advantage-standalone-v1'),'utf8');console.log(JSON.stringify({phase:PHASE,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,libraryFileSha256:sha256(serialized),canonicalQuestionCount:6639,questionCount:106,reviewed:46,rewrites:8,additions:60,counts,cacheKey:'20260810-comparative-advantage-standalone-v1'},null,2));
