import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const repo=path.resolve(process.argv[2]||process.cwd());
const dryRun=process.argv.includes('--dry-run');
const PHASE='phaseM2c3-money-market-policy-transmission-family-maturation-v1';
const STAMP=new Date().toISOString();
const SOURCE='macro-m2c3-money-market-policy-transmission-family';
const familyIds=['liquidity-preference-and-money-market','monetary-policy-transmission'];
const modifiedSet=new Set(familyIds);
const composer=path.join(repo,'build','faculty-build-composer');
const dataDir=path.join(composer,'data');
const libraryPath=path.join(dataDir,'composer_library.js');
const registryPath=path.join(dataDir,'composer_registry.json');
const manifestPath=path.join(dataDir,'composer_library_manifest.json');
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const answerHash=a=>sha(String(a).trim().replace(/\s+/g,' ').toLowerCase());
const qid=q=>String(q?.canonicalId||q?.id||q?.questionId||'');
const questionHash=q=>sha(JSON.stringify(stable({q:q.q,options:q.options,aHash:q.aHash,primaryConceptId:q.primaryConceptId,primarySkill:q.primarySkill,repairSkill:q.repairSkill,difficulty:q.difficulty,secondaryConceptIds:q.secondaryConceptIds||[],bossStage:q.bossStage||null,image:q.image||null})));
const rawBefore=fs.readFileSync(libraryPath,'utf8');
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(rawBefore,sandbox,{filename:libraryPath});const library=sandbox.window.MQ_COMPOSER_LIBRARY;
const registry=JSON.parse(fs.readFileSync(registryPath,'utf8'));
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
if(!String(library.libraryVersion).endsWith('phaseM2c2-money-growth-inflation-neutrality-family-maturation-v1'))throw new Error('Unexpected baseline: completed M2c-2 library required.');
for(const id of familyIds)if(!library.concepts[id])throw new Error(`Missing F7 concept ${id}`);

function tagged(module){return [...Object.entries(module.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(module.repairQuestions||[]).map(question=>({pool:'repair',question})),...(module.repairSeedQuestions||[]).map(question=>({pool:'repairSeed',question})),...(module.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))];}
function unique(module){const seen=new Set();return tagged(module).filter(({question})=>{const id=qid(question);if(seen.has(id))return false;seen.add(id);return true;});}
function bankSnapshot(module){return unique(module).map(({pool,question})=>({pool,id:qid(question),question:stable(question)})).sort((a,b)=>a.id.localeCompare(b.id));}
function bankHash(module){return sha(JSON.stringify(stable(bankSnapshot(module))));}
function bossTier(q){const d=String(q?.difficulty||'').toLowerCase();if(d==='easyboss')return'easyBoss';if(d==='mediumboss')return'mediumBoss';if(d==='finalboss'||d==='hardboss')return'finalBoss';return'';}
function countModule(module){const boss=module.questions?.boss||[];return{easy:(module.questions?.easy||[]).length,medium:(module.questions?.medium||[]).length,hard:(module.questions?.hard||[]).length,elite:(module.questions?.elite||[]).length,legendary:(module.questions?.legendary||[]).length,calculation:(module.questions?.calculation||[]).length,integration:(module.questions?.integration||[]).length,easyBoss:boss.filter(q=>bossTier(q)==='easyBoss').length,mediumBoss:boss.filter(q=>bossTier(q)==='mediumBoss').length,finalBoss:boss.filter(q=>bossTier(q)==='finalBoss').length,legendaryBoss:(module.questions?.legendaryBoss||[]).length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length,bridge:(module.bridgeQuestions||[]).length,total:unique(module).length};}
const protectedIds=Object.keys(library.concepts).filter(id=>!modifiedSet.has(id));
const protectedBefore=Object.fromEntries(protectedIds.map(id=>[id,bankHash(library.concepts[id])]));
const beforeCounts=Object.fromEntries(familyIds.map(id=>[id,countModule(library.concepts[id])]));
const beforeTotal=library.canonicalQuestionCount,previousVersion=library.libraryVersion;
const changes=[]; let serial=9000000;

const meta={
 'liquidity-preference-and-money-market':{code:'LPMM',tag:'liquidity_preference',objective:'LO35.1',chapter:[35,1],cluster:'liquidity_preference'},
 'monetary-policy-transmission':{code:'MPTX',tag:'monetary_policy_transmission',objective:'LO35.2',chapter:[35,2],cluster:'monetary_policy_transmission'}
};
const lessonMap={
 simultaneous_money_shifts:['Assumes the direction of one curve shift determines the interest rate even when both money demand and money supply move.','When money demand and money supply both shift, compare the new equilibrium with the old one; the interest-rate direction depends on their relative effects.'],
 money_market_disequilibrium:['Treats a labeled point on a money-supply line as an equilibrium even when it is not on the active money-demand curve.','At an interest rate above equilibrium, money supplied exceeds money demanded and asset-market adjustment pushes the rate down; below equilibrium, excess money demand pushes it up.'],
 money_demand_shift_vs_movement:['Calls an interest-rate-induced movement along a money-demand curve a shift of the curve.','A change in the interest rate causes movement along a given money-demand curve. Income or the price level can shift the money-demand curve.'],
 stabilize_interest_rate_after_md_shift:['Uses a contractionary money-supply response to offset a rightward money-demand shift.','If money demand shifts right and the central bank wants to prevent the interest rate from rising, it must increase money supply enough to accommodate the higher demand.'],
 infer_money_supply_offset:['Ignores the opposing pressure from a money-demand increase when interpreting a falling interest rate.','If money demand rises but the equilibrium interest rate falls, money supply must have risen by enough to more than offset the upward interest-rate pressure from money demand.'],
 omitted_transmission_link:['Jumps directly from a central-bank action to aggregate demand and skips the interest-rate and spending links.','Trace the chain explicitly: money conditions change, the interest rate changes, interest-sensitive spending responds, and aggregate demand shifts.'],
 bridge_money_market_transmission:['Stops after finding the new money-market interest rate and does not carry the result into spending and aggregate demand.','After solving the money market, use the interest-rate change to infer the direction of investment and other rate-sensitive spending, then the aggregate-demand shift.'],
 transmission_strength:['Assumes a change in the policy instrument guarantees a fixed-size aggregate-demand response.','Transmission can weaken if rates respond little or if households and firms are not very responsive to the resulting borrowing-cost change.']
};
function lesson(skill){return lessonMap[skill]||['Uses a memorized direction without tracing the money-market or transmission mechanism.','Identify which curve shifts, find the interest-rate response, then trace any spending and aggregate-demand consequences.'];}
function rotate(options,answer,index){const n=index%options.length,out=options.slice(n).concat(options.slice(0,n));if(!out.includes(answer))throw new Error(`Answer missing: ${answer}`);return out;}
function spec(stem,answer,wrong,skill,extra={}){return{stem,answer,options:[answer,...wrong],skill,...extra};}
function setSourceHash(q){q.sourceHash=questionHash(q);if(Array.isArray(q.sourceOccurrences)&&q.sourceOccurrences.length)q.sourceOccurrences[q.sourceOccurrences.length-1].sourceHash=q.sourceHash;}
function addQuestion(conceptId,pool,s,index){
 const module=library.concepts[conceptId],lb=pool==='legendaryBoss',m=meta[conceptId],marker=lb?'LB':'L',id=`PM2C3-${m.code}-${marker}-${String(index+1).padStart(3,'0')}`,[commonError,feedback]=lesson(s.skill);
 const q={id,sourceGame:SOURCE,q:s.stem,options:rotate(s.options,s.answer,index),tag:m.tag,type:s.type||'application',objective:m.objective,difficulty:lb?'legendaryBoss':'legendary',conceptCluster:m.cluster,primarySkill:s.skill,secondarySkills:s.secondarySkills||[],repairSkill:s.repairSkill||s.skill,commonError:s.commonError||commonError,feedback:s.feedback||feedback,aHash:answerHash(s.answer),canonicalId:id,sourceId:++serial,sourceChapter:m.chapter,sourcePool:s.skill,primaryConceptId:conceptId,secondaryConceptIds:s.secondaryConceptIds||[],instructionalRole:lb?'legendaryBoss':'legendary',canonicalDifficulty:'legendary',originalSourcePool:s.skill,originalBossTier:lb?'legendaryBoss':null,sourceCurationPhase:PHASE};
 if(s.image)q.image=s.image;if(lb)q.bossStage=s.bossStage;
 q.sourceHash=questionHash(q);q.sourceOccurrences=[{sourceGame:SOURCE,sourceFile:`${PHASE}_questions.json`,sourceGlobal:'questions',sourcePool:q.sourcePool,routeKey:q.primarySkill,sourceRecordOrder:index,sourceId:q.sourceId,sourceHash:q.sourceHash,sourceCurationPhase:PHASE}];
 module.questions[pool].push(q);changes.push({questionId:id,canonicalConceptId:conceptId,action:'ADD',oldPool:null,newPool:pool,reason:s.reason||'Adds distinct F7 Legendary depth without expanding healthy ordinary pools.'});return q;
}
function addAux(conceptId,role,s,index){
 const module=library.concepts[conceptId],m=meta[conceptId],marker=role==='repair'?'R':'BR',id=`PM2C3-${m.code}-${marker}-${String(index+1).padStart(3,'0')}`,[commonError,feedback]=lesson(s.skill);
 const q={id,sourceGame:SOURCE,q:s.stem,options:rotate(s.options,s.answer,index),tag:m.tag,type:role==='bridge'?'bridge':'repair',objective:m.objective,difficulty:role==='bridge'?'bridge':'microRepair',conceptCluster:m.cluster,primarySkill:s.skill,secondarySkills:s.secondarySkills||[],repairSkill:s.repairSkill||s.skill,commonError:s.commonError||commonError,feedback:s.feedback||feedback,aHash:answerHash(s.answer),canonicalId:id,sourceId:++serial,sourceChapter:m.chapter,sourcePool:s.skill,primaryConceptId:conceptId,secondaryConceptIds:s.secondaryConceptIds||[],instructionalRole:role,canonicalDifficulty:'unknown',originalSourcePool:s.skill,originalBossTier:null,sourceCurationPhase:PHASE};
 q.sourceHash=questionHash(q);q.sourceOccurrences=[{sourceGame:SOURCE,sourceFile:`${PHASE}_questions.json`,sourceGlobal:role==='bridge'?'microSkillBridgePools':'microSkillRepairPools',sourcePool:q.sourcePool,routeKey:q.primarySkill,sourceRecordOrder:index,sourceId:q.sourceId,sourceHash:q.sourceHash,sourceCurationPhase:PHASE}];
 if(role==='repair'){module.repairQuestions.push(q);module.microSkillRepairPools=module.microSkillRepairPools||{};(module.microSkillRepairPools[q.primarySkill]||=[]).push(id);}else{module.bridgeQuestions.push(q);module.microSkillBridgePools=module.microSkillBridgePools||{};(module.microSkillBridgePools[q.primarySkill]||=[]).push(id);}changes.push({questionId:id,canonicalConceptId:conceptId,action:'ADD',oldPool:null,newPool:role,reason:s.reason||`Adds a targeted F7 ${role} route.`});return q;
}
function findQuestion(conceptId,id){for(const row of tagged(library.concepts[conceptId]))if(qid(row.question)===id)return row;throw new Error(`Question not found ${conceptId}/${id}`);}
function rewrite(conceptId,id,s,reason,action='QUALITY_REWRITE'){
 const {pool,question:q}=findQuestion(conceptId,id),beforeHash=questionHash(q),oldSkill=q.primarySkill,oldRepairSkill=q.repairSkill;q.q=s.stem;q.options=rotate(s.options,s.answer,0);q.aHash=answerHash(s.answer);q.primarySkill=s.skill||q.primarySkill;q.repairSkill=s.repairSkill||s.skill||q.repairSkill;q.secondaryConceptIds=s.secondaryConceptIds||[];q.secondarySkills=s.secondarySkills||[];q.type=s.type||q.type||'application';const [commonError,feedback]=lesson(q.primarySkill);q.commonError=s.commonError||commonError;q.feedback=s.feedback||feedback;if(s.image!==undefined){if(s.image)q.image=s.image;else delete q.image;}setSourceHash(q);changes.push({questionId:id,canonicalConceptId:conceptId,action,oldPool:pool,newPool:pool,reason,beforeHash,afterHash:questionHash(q),oldSkill,newSkill:q.primarySkill,oldRepairSkill,newRepairSkill:q.repairSkill});
}
function metadataUpdate(conceptId,id,patch,reason,action='METADATA_FIX'){const {pool,question:q}=findQuestion(conceptId,id),beforeHash=questionHash(q);Object.assign(q,patch);setSourceHash(q);changes.push({questionId:id,canonicalConceptId:conceptId,action,oldPool:pool,newPool:pool,reason,beforeHash,afterHash:questionHash(q)});}

// Repair the six pre-existing F7 Legendary Boss stage defects without changing question content.
const stageAssignments={
 'liquidity-preference-and-money-market':{'P52B-S3-LPMM-LB-001':'opening','LG-Q-9130':'middle','LG-Q-9137':'final'},
 'monetary-policy-transmission':{'LG-Q-9138':'opening','LG-Q-9132':'middle','LG-Q-9131':'final'}
};
for(const [conceptId,map] of Object.entries(stageAssignments))for(const [id,stage] of Object.entries(map)){const before=findQuestion(conceptId,id).question.bossStage??null;metadataUpdate(conceptId,id,{bossStage:stage},`Assigns semantically appropriate ${stage} stage without changing question content.`,'BOSS_STAGE_FIX');const last=changes.at(-1);last.beforeBossStage=before;last.afterBossStage=stage;}

// Upgrade two repetitive money-market Repairs and one weakly tagged Bridge instead of adding bulk remediation.
rewrite('liquidity-preference-and-money-market','LG-R-5040',spec('The central bank increases the money supply while income and the price level stay unchanged. The equilibrium interest rate falls. What happens to money demand in the standard diagram?','There is a movement down along the existing money-demand curve; the curve itself need not shift.',['The money-demand curve shifts left because the lower interest rate changes households’ desired money holdings at every possible interest rate, not just at the new equilibrium.','The money-demand curve shifts right because the central bank supplied more money.','Money demand becomes vertical because the money supply changed.'],'money_demand_shift_vs_movement'), 'Replaces a duplicate definition check with the core movement-versus-shift misconception.','REPAIR_REWRITE');
rewrite('liquidity-preference-and-money-market','LG-R-5041',spec('At the current interest rate, households want to hold more money than the fixed money supply provides. Which adjustment moves the market toward equilibrium?','People try to obtain money by selling interest-bearing assets, putting upward pressure on the interest rate.',['People buy interest-bearing assets, pushing the interest rate downward.','The money-demand curve automatically shifts left until it equals money supply.','The central bank must change money supply because the interest rate cannot adjust.'],'money_market_disequilibrium'), 'Replaces a second definition check with disequilibrium adjustment logic.','REPAIR_REWRITE');
rewrite('liquidity-preference-and-money-market','LG-B-6018',spec('A higher price level shifts money demand right while money supply is fixed, so the equilibrium interest rate rises. To carry that money-market result into the policy-transmission model, what happens next?','Interest-sensitive investment falls, putting downward pressure on aggregate demand.',['Investment rises because higher rates make borrowing cheaper, shifting aggregate demand right.','Aggregate demand shifts left directly because the price level changed, with no spending channel involved.','The higher interest rate shifts money demand farther right but has no effect on spending.'],'bridge_money_market_transmission',{secondaryConceptIds:['monetary-policy-transmission']}), 'Turns a same-skill bridge into an explicit Money Market → Policy Transmission connection.','BRIDGE_REWRITE');

const mm='question-assets/moneyd2_moneys2.webp';
const lpLegendary=[
 spec('Refer to the money-market graph. Starting at point e (MS1 with MD1), both money demand and money supply shift right to MD2 and MS2. The new equilibrium is point d. What does the change from r2 to r3 imply?','The rightward money-demand shift exerts more upward pressure on the interest rate than the rightward money-supply shift offsets.',['The money-supply shift must have dominated because any increase in money supply mechanically raises interest rates more than a simultaneous money-demand shift can affect them.','Both rightward shifts necessarily leave the interest rate unchanged.','The new equilibrium shows that money demand fell relative to money supply.'],'simultaneous_money_shifts',{image:mm}),
 spec('Refer to the money-market graph. With MD2 and MS2, the equilibrium is point d at r3. If the interest rate is temporarily at point b on MS2 at r4, what adjustment should occur?','There is excess money supply; people try to buy interest-bearing assets, putting downward pressure on the interest rate toward r3.',['There is excess money demand, so households sell interest-bearing assets; bond prices fall and the interest rate rises farther above r4 before the market can clear.','Point b is already the equilibrium because it lies on MS2.','Money demand must shift right again before the interest rate can change.'],'money_market_disequilibrium',{image:mm}),
 spec('Refer to the money-market graph. With MD1 and MS1, equilibrium is point e at r2. If the interest rate is temporarily at r1, what pressure moves the market back toward equilibrium?','Quantity of money demanded exceeds the fixed money supply, so attempts to raise money by selling interest-bearing assets put upward pressure on the interest rate.',['Quantity of money supplied exceeds money demanded, so asset purchases push the interest rate lower.','The market remains at r1 because a vertical money-supply curve prevents interest-rate adjustment.','The central bank must reduce the fixed money supply before households can obtain enough money balances and the interest rate can move back toward equilibrium.'],'money_market_disequilibrium',{image:mm}),
 spec('Real income rises while the overall price level falls. With money supply fixed, what can be concluded about the equilibrium interest rate from liquidity-preference theory alone?','The direction is ambiguous because higher income raises money demand while a lower price level reduces money demand.',['It must rise because every increase in real income dominates every change in the price level.','It must fall because the price-level effect always dominates the income effect.','It cannot change because income and the price level never shift money demand.'],'simultaneous_money_shifts'),
 spec('The central bank increases the money supply and the equilibrium interest rate falls while income and the price level are unchanged. A student says, “Money demand shifted left.” What is the best correction?','The fall in the interest rate is a movement along the existing money-demand curve unless a money-demand shifter also changed.',['The student is correct because any fall in interest rates shifts the entire money-demand curve left at every quantity, even when income and the price level are unchanged.','Money demand shifts right whenever money supply increases.','Money demand becomes horizontal after an expansionary money-supply change.'],'money_demand_shift_vs_movement'),
 spec('Refer to the money-market graph. The economy begins at e with MD1 and MS1. Money demand shifts to MD2, and the central bank also expands money supply to MS2. Is the increase in money supply large enough to keep the interest rate at r2?','No. The new equilibrium d is at r3, so the central bank would need a larger rightward money-supply shift to hold the rate at r2.',['Yes. Any rightward money-supply shift exactly offsets any rightward money-demand shift.','Yes. Point d lies on MS2, so the interest rate must still equal r2.','No. The central bank would need to reduce money supply to keep the interest rate from rising.'],'stabilize_interest_rate_after_md_shift',{image:mm}),
 spec('Real income rises, shifting money demand right, yet the observed equilibrium interest rate falls. Which inference is most consistent with the liquidity-preference model?','Money supply must have increased enough to more than offset the upward interest-rate pressure from higher money demand.',['Money supply must have fallen because lower supply always lowers interest rates.','Money demand could not have risen because income never affects transaction demand.','The central bank must have held money supply fixed because a fixed supply guarantees a lower rate.'],'infer_money_supply_offset')
];
lpLegendary.forEach((s,i)=>addQuestion('liquidity-preference-and-money-market','legendary',s,i));

const lbLP=[
 spec('Refer to the money-market graph. With MD2 and MS2, point b is above the equilibrium interest rate at d. Which adjustment best explains movement toward equilibrium?','An excess supply of money leads people to buy interest-bearing assets, pushing the interest rate down toward r3.',['An excess demand for money leads people to sell interest-bearing assets, lowering bond prices and pushing the interest rate farther above r4 until the central bank expands money supply.','Because MS2 is vertical, point b is an equilibrium regardless of money demand.','The central bank must shift MS2 left before any interest-rate adjustment can occur.'],'money_market_disequilibrium',{image:mm,bossStage:'middle'}),
 spec('Refer to the money-market graph. The economy moves from e to d because both money demand and money supply shift right. Which conclusion is supported by the final interest rate?','The demand shift dominates the supply shift’s interest-rate effect, because the equilibrium rate rises from r2 to r3.',['The supply shift dominates, because every increase in money supply raises the interest rate.','The two shifts exactly offset, because both curves move right.','Money demand must have shifted left, because the equilibrium quantity of money rises.'],'simultaneous_money_shifts',{image:mm,bossStage:'final'})
];
lbLP.forEach((s,i)=>addQuestion('liquidity-preference-and-money-market','legendaryBoss',s,i));

addQuestion('monetary-policy-transmission','legendaryBoss',spec('An expansionary policy clearly lowers the market interest rate, but firms expect very weak future sales and barely change investment. Where does the usual transmission chain primarily weaken?','At the link from the lower interest rate to interest-sensitive spending, so aggregate demand shifts by less than the standard chain would predict.',['At the initial money-supply link, because a lower interest rate proves money supply did not change.','At the price-level definition, because expectations about sales determine whether money is a medium of exchange.','At the long-run neutrality link, which requires aggregate demand to shift by a fixed amount immediately.'],'transmission_strength',{bossStage:'final'}),0);

addAux('monetary-policy-transmission','repair',spec('A student writes only “the central bank increases money supply, so aggregate demand rises.” Which missing links are essential to the standard short-run transmission mechanism?','The equilibrium interest rate falls and interest-sensitive spending such as investment rises before aggregate demand shifts right.',['Government purchases automatically rise and then the money supply increases.','The price level falls first, which directly forces aggregate demand to shift right.','The natural rate of unemployment falls permanently, which mechanically raises aggregate demand.'],'omitted_transmission_link'),0);
addAux('liquidity-preference-and-money-market','bridge',spec('Money demand shifts right while money supply is fixed, raising the equilibrium interest rate. What is the next step if the student is bridging from the money market to monetary-policy transmission?','Higher borrowing costs reduce interest-sensitive investment and put downward pressure on aggregate demand.',['Higher borrowing costs raise investment because firms earn more interest.','The higher interest rate directly increases government purchases.','Aggregate demand is unaffected because interest rates matter only inside the money-market graph.'],'bridge_money_market_transmission',{secondaryConceptIds:['monetary-policy-transmission']}),0);

// Add accessibility metadata to the two pre-existing F7 graph assets in both concept-scoped copies.
const assetDescriptions={
 'moneyd2_moneys2.webp':{imageAlt:'Money-market graph with two vertical money-supply curves and two downward-sloping money-demand curves.',graphDescription:'The vertical axis is interest rate r and the horizontal axis is quantity of money Qm. MS1 is vertical at Qm1 and MS2 is vertical to its right at Qm2. MD1 slopes downward through e at Qm1, r2 and g at Qm2, r1. MD2 is shifted right/up and slopes downward through a at Qm1, r4 and d at Qm2, r3. Additional labeled points are b at Qm2, r4; c at Qm1, r3; and f at Qm1, r1.'},
 'ad_ms_md.webp':{imageAlt:'Two-panel graph showing a leftward money-supply shift that raises the interest rate and a leftward aggregate-demand shift that reduces output at a fixed price level.',graphDescription:'Left panel: interest rate r is on the vertical axis and money M on the horizontal axis. A downward-sloping MD curve intersects MS1 at r1; MS2 is left of MS1 and intersects MD at the higher rate r2. Right panel: price level P is on the vertical axis and output Y on the horizontal axis. AD2 lies left of AD1. At price level P1, output is Y1 on AD1 and Y2 on AD2.'}
};
for(const cid of familyIds){const module=library.concepts[cid];for(const rec of module.assetMetadata||[]){const desc=assetDescriptions[rec.filename];if(desc)Object.assign(rec,desc);}for(const rec of library.assetInventory||[]){if(rec.conceptId===cid&&assetDescriptions[rec.filename])Object.assign(rec,assetDescriptions[rec.filename]);}for(const rec of manifest.assets||[]){if(rec.conceptId===cid&&assetDescriptions[rec.filename])Object.assign(rec,assetDescriptions[rec.filename]);}}

const afterCounts=Object.fromEntries(familyIds.map(id=>[id,countModule(library.concepts[id])]));
const expected={
 'liquidity-preference-and-money-market':{total:74,easy:7,medium:10,hard:7,elite:11,legendary:13,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:5,repair:7,bridge:5},
 'monetary-policy-transmission':{total:75,easy:11,medium:10,hard:10,elite:6,legendary:14,easyBoss:3,mediumBoss:3,finalBoss:3,legendaryBoss:4,repair:8,bridge:3}
};
for(const [cid,target] of Object.entries(expected))for(const [key,val] of Object.entries(target))if(afterCounts[cid][key]!==val)throw new Error(`Count mismatch ${cid} ${key}: ${afterCounts[cid][key]} != ${val}`);
const added=changes.filter(c=>c.action==='ADD').length;if(added!==12)throw new Error(`Expected 12 additions; got ${added}`);
const bossStageFixed=changes.filter(c=>c.action==='BOSS_STAGE_FIX').length;if(bossStageFixed!==6)throw new Error(`Expected 6 bossStage fixes; got ${bossStageFixed}`);

// Static duplication and answer-length guards on changed content.
const changedContentIds=new Set(changes.filter(c=>['ADD','REPAIR_REWRITE','BRIDGE_REWRITE','QUALITY_REWRITE'].includes(c.action)).map(c=>c.questionId));
const allF7=familyIds.flatMap(cid=>unique(library.concepts[cid]).map(({pool,question})=>({cid,pool,question})));
const normalize=t=>String(t||'').toLowerCase().replace(/[^a-z0-9%$]+/g,' ').replace(/\s+/g,' ').trim();
const stemMap=new Map(),tplMap=new Map(),introducedExact=[],introducedNumberSwaps=[];
for(const r of allF7){const id=qid(r.question),stem=normalize(r.question.q),tpl=stem.replace(/\b\d+(?:[.,]\d+)?%?\b/g,'#');if(stemMap.has(stem)&&(changedContentIds.has(id)||changedContentIds.has(stemMap.get(stem))))introducedExact.push([stemMap.get(stem),id]);else if(!stemMap.has(stem))stemMap.set(stem,id);if(tplMap.has(tpl)&&(changedContentIds.has(id)||changedContentIds.has(tplMap.get(tpl))))introducedNumberSwaps.push([tplMap.get(tpl),id]);else if(!tplMap.has(tpl))tplMap.set(tpl,id);}
if(introducedExact.length)throw new Error(`Introduced exact duplicate ${JSON.stringify(introducedExact)}`);if(introducedNumberSwaps.length)throw new Error(`Introduced number-swap ${JSON.stringify(introducedNumberSwaps)}`);
function wc(t){return String(t||'').trim().split(/\s+/).filter(Boolean).length;}const lengthIssues=[];
for(const cid of familyIds){const groups={};for(const {pool,question:q} of unique(library.concepts[cid]))if(changedContentIds.has(qid(q))){const correct=(q.options||[]).find(o=>answerHash(o)===q.aHash),dist=(q.options||[]).filter(o=>o!==correct),g=pool;(groups[g]||=[]).push({c:wc(correct),d:dist.map(wc)});}for(const [g,rows] of Object.entries(groups)){const longest=rows.filter(r=>r.d.every(n=>r.c>n)).length/rows.length,cm=rows.reduce((a,r)=>a+r.c,0)/rows.length,dm=rows.reduce((a,r)=>a+r.d.reduce((x,y)=>x+y,0)/r.d.length,0)/rows.length,ratio=cm/dm;if(rows.length>=2&&(longest>.65||ratio>1.7))lengthIssues.push({cid,g,longest:Number(longest.toFixed(3)),ratio:Number(ratio.toFixed(3))});}}
if(lengthIssues.length)throw new Error(`Answer length issue ${JSON.stringify(lengthIssues)}`);

const protectedAfter=Object.fromEntries(protectedIds.map(id=>[id,bankHash(library.concepts[id])]));const protectedMismatches=protectedIds.filter(id=>protectedAfter[id]!==protectedBefore[id]);if(protectedMismatches.length)throw new Error(`Protected non-F7 bank changed: ${protectedMismatches.join(',')}`);

function calcLinked(q){return q.type==='calculation'||(/calculate|multiplier|required_rate|ad_effect/.test(String(q.primarySkill||''))&&/\d/.test(String(q.q||'')));}
function updateRegistryEntry(entry,module){const records=unique(module).map(x=>x.question),ordinary=['easy','medium','hard'].flatMap(pool=>module.questions[pool]||[]),boss=module.questions.boss||[];const role={boss:boss.length,bridge:(module.bridgeQuestions||[]).length,calculation:(module.questions.calculation||[]).length,elite:(module.questions.elite||[]).length,integration:(module.questions.integration||[]).length,legendary:(module.questions.legendary||[]).length,legendaryBoss:(module.questions.legendaryBoss||[]).length,main:ordinary.length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length};const diff={easy:(module.questions.easy||[]).length+boss.filter(q=>bossTier(q)==='easyBoss').length,medium:(module.questions.medium||[]).length+boss.filter(q=>bossTier(q)==='mediumBoss').length,hard:(module.questions.hard||[]).length+boss.filter(q=>bossTier(q)==='finalBoss').length,elite:(module.questions.elite||[]).length,legendary:(module.questions.legendary||[]).length+(module.questions.legendaryBoss||[]).length,unknown:(module.repairQuestions||[]).length+(module.repairSeedQuestions||[]).length+(module.bridgeQuestions||[]).length};Object.assign(entry,{includedSkills:[...new Set(records.map(q=>q.primarySkill).filter(Boolean))].sort(),questionCountByRole:role,questionCountByDifficulty:diff,repairCoverage:{directSkillMatches:(module.repairQuestions||[]).length,mainWithUsableSkill:records.length},bridgeCoverage:{directSkillMatches:(module.bridgeQuestions||[]).length,mainWithUsableSkill:records.length},calculationCoverage:records.filter(calcLinked).length,graphCoverage:records.filter(q=>Boolean(q.image)).length,instructionalClassification:'Engine-safe F7 Money Market and Policy Transmission family slice',coverageStatus:'ready-family-slice',coverageStatusLabel:'Engine-safe alone; strongest as Money Market → Transmission sequence',coverageStatusNote:'Phase M2c-3 preserves healthy ordinary pools, brings family Legendary depth to one clean unique run, repairs all Legendary boss stages, strengthens diagnostic Repair and Money Market → Policy Transmission routing, and adds accessibility metadata to existing graph assets.',coverageFloorVersion:PHASE,notes:'Money Market and Policy Transmission family slice. No new graph image was added; existing money-market and two-panel transmission assets were reused for distinct cognitive tasks.'});}
for(const cid of familyIds)for(const list of [library.registry.concepts,registry.concepts]){const e=list.find(x=>x.canonicalConceptId===cid);if(!e)throw new Error(`Registry missing ${cid}`);updateRegistryEntry(e,library.concepts[cid]);}

library.libraryVersion=`${previousVersion}-${PHASE}`;library.sourceCurationPhase=PHASE;library.generatedAt=STAMP;library.canonicalQuestionCount=Object.values(library.concepts).reduce((n,m)=>n+unique(m).length,0);Object.assign(library.registry,{libraryVersion:library.libraryVersion,generatedAt:STAMP,canonicalQuestionCount:library.canonicalQuestionCount});Object.assign(registry,{libraryVersion:library.libraryVersion,generatedAt:STAMP,canonicalQuestionCount:library.canonicalQuestionCount});delete library.librarySha256;library.librarySha256=sha(JSON.stringify(stable(library)));registry.librarySha256=library.librarySha256;Object.assign(manifest,{canonicalQuestionCount:library.canonicalQuestionCount,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,generatedAt:STAMP});
const familyBefore=Object.values(beforeCounts).reduce((o,r)=>{for(const [k,v] of Object.entries(r))o[k]=(o[k]||0)+v;return o;},{}),familyAfter=Object.values(afterCounts).reduce((o,r)=>{for(const [k,v] of Object.entries(r))o[k]=(o[k]||0)+v;return o;},{});if(familyBefore.total!==137||familyAfter.total!==149)throw new Error(`Unexpected F7 totals ${familyBefore.total} -> ${familyAfter.total}`);
const provenance={phase:PHASE,generatedAt:STAMP,scope:{family:'F7 — Money Market and Policy Transmission',modifiedCanonicalConceptIds:familyIds,protectedCanonicalConceptIds:protectedIds},before:{libraryVersion:previousVersion,canonicalQuestionCount:beforeTotal,counts:beforeCounts,familyCounts:familyBefore},after:{libraryVersion:library.libraryVersion,canonicalQuestionCount:library.canonicalQuestionCount,librarySha256:library.librarySha256,counts:afterCounts,familyCounts:familyAfter},protectedSummary:{canonicalBanksChecked:protectedIds.length,nonF7Mismatches:protectedMismatches},quality:{introducedExact,introducedNumberSwaps,answerLengthIssues:lengthIssues},assetAccessibility:{metadataUpdatedCopies:4,newGraphAssets:0}};
const sourceData={phase:PHASE,generatedAt:STAMP,scope:familyIds,changes,summary:{added,bossStageFixed,repairRewritten:2,bridgeRewritten:1,assetMetadataCopiesUpdated:4,removed:0,relocated:0},authoringPolicy:{targetRange:[149,155],actualFamilyTotal:familyAfter.total,ordinaryPoolsProtected:true,newGraphAssets:0,legendaryOrdinaryTarget:27,legendaryBossTarget:9,bridgeChain:['monetary-policy-tools','liquidity-preference-and-money-market','monetary-policy-transmission','aggregate-demand']},quality:provenance.quality};
if(!dryRun){fs.writeFileSync(libraryPath,`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(library)};\n`);fs.writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(path.join(composer,`${PHASE}_questions.json`),JSON.stringify(sourceData,null,2)+'\n');fs.writeFileSync(path.join(composer,`${PHASE}.json`),JSON.stringify(provenance,null,2)+'\n');for(const file of [path.join(repo,'build','index.html'),path.join(composer,'index.html')])if(fs.existsSync(file)){let text=fs.readFileSync(file,'utf8');text=text.replaceAll('20260810-macro-m2c2-money-growth-inflation-v1','20260810-macro-m2c3-money-market-transmission-v1');fs.writeFileSync(file,text);}}
console.log(JSON.stringify({dryRun,phase:PHASE,beforeTotal,afterTotal:library.canonicalQuestionCount,added,bossStageFixed,beforeCounts,afterCounts,familyBefore,familyAfter,protectedMismatches,quality:{introducedExact,introducedNumberSwaps,lengthIssues},changeSummary:sourceData.summary},null,2));
