import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const repo=path.resolve(process.argv[2]||process.cwd());
const PHASE='phaseM2b3-growth-productivity-family-maturation-v1';
const composer=path.join(repo,'build','faculty-build-composer'),dataDir=path.join(composer,'data');
const lp=path.join(dataDir,'composer_library.js'),rp=path.join(dataDir,'composer_registry.json'),mp=path.join(dataDir,'composer_library_manifest.json'),sp=path.join(composer,`${PHASE}_questions.json`),pp=path.join(composer,`${PHASE}.json`);
const sha=v=>crypto.createHash('sha256').update(v).digest('hex'); const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v; const qid=q=>String(q?.canonicalId||q?.id||'');
const s={window:{}};vm.createContext(s);vm.runInContext(fs.readFileSync(lp,'utf8'),s);const lib=s.window.MQ_COMPOSER_LIBRARY,reg=JSON.parse(fs.readFileSync(rp)),man=JSON.parse(fs.readFileSync(mp)),src=JSON.parse(fs.readFileSync(sp)),prov=JSON.parse(fs.readFileSync(pp));
const calcIds=new Set(['PM2B3-PROD-M-002','PM2B3-PROD-H-002','PM2B3-PROD-H-004','PM2B3-PROD-L-002','PM2B3-PROD-EB-001','PM2B3-PROD-FB-005','PM2B3-PROD-FB-006','PM2B3-PROD-LB-001']);
const m=lib.concepts['productivity-measurement'];
for(const list of Object.values(m.questions||{}))for(const q of list||[])if(calcIds.has(qid(q))&&q.type!=='calculation'){q.type='calculation';src.changes.push({questionId:qid(q),canonicalConceptId:'productivity-measurement',action:'QUALITY_FIX',oldPool:q.difficulty,newPool:q.difficulty,reason:'Classifies an arithmetic productivity task as calculation for accurate coverage metadata.'});}
function all(module){const seen=new Set(),out=[];for(const list of Object.values(module.questions||{}))for(const q of list||[])if(!seen.has(qid(q))){seen.add(qid(q));out.push(q);}for(const q of module.repairQuestions||[])if(!seen.has(qid(q))){seen.add(qid(q));out.push(q);}for(const q of module.bridgeQuestions||[])if(!seen.has(qid(q))){seen.add(qid(q));out.push(q);}return out;}
function update(entry,module){const records=all(module),ordinary=['easy','medium','hard'].flatMap(pool=>module.questions[pool]||[]),boss=module.questions.boss||[];entry.questionCountByRole={boss:boss.length,bridge:(module.bridgeQuestions||[]).length,calculation:(module.questions.calculation||[]).length,elite:(module.questions.elite||[]).length,integration:(module.questions.integration||[]).length,legendary:(module.questions.legendary||[]).length,legendaryBoss:(module.questions.legendaryBoss||[]).length,main:ordinary.length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length};entry.questionCountByDifficulty={easy:(module.questions.easy||[]).length+boss.filter(q=>q.difficulty==='easyBoss').length,medium:(module.questions.medium||[]).length+boss.filter(q=>q.difficulty==='mediumBoss').length,hard:(module.questions.hard||[]).length+boss.filter(q=>q.difficulty==='finalBoss').length,elite:(module.questions.elite||[]).length,legendary:(module.questions.legendary||[]).length+(module.questions.legendaryBoss||[]).length,unknown:(module.repairQuestions||[]).length+(module.bridgeQuestions||[]).length};entry.calculationCoverage=records.filter(q=>q.type==='calculation').length;entry.graphCoverage=records.filter(q=>Boolean(q.image)).length;}
for(const cid of ['living-standards-and-growth','productivity-measurement','sources-of-productivity','economic-growth-policy'])for(const list of [lib.registry.concepts,reg.concepts])update(list.find(x=>x.canonicalConceptId===cid),lib.concepts[cid]);
src.summary.qualityFixes=(src.summary.qualityFixes||0)+calcIds.size;
delete lib.librarySha256;lib.librarySha256=sha(JSON.stringify(stable(lib)));reg.librarySha256=lib.librarySha256;man.librarySha256=lib.librarySha256;prov.after.librarySha256=lib.librarySha256;prov.finalQualityFixes={answerLength:1,secondaryConceptReference:1,calculationTypeClassification:calcIds.size};
fs.writeFileSync(lp,`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(lib)};\n`);fs.writeFileSync(rp,JSON.stringify(reg,null,2)+'\n');fs.writeFileSync(mp,JSON.stringify(man,null,2)+'\n');fs.writeFileSync(sp,JSON.stringify(src,null,2)+'\n');fs.writeFileSync(pp,JSON.stringify(prov,null,2)+'\n');
console.log(JSON.stringify({librarySha256:lib.librarySha256,calculationCoverage:Object.fromEntries(['living-standards-and-growth','productivity-measurement','sources-of-productivity','economic-growth-policy'].map(cid=>[cid,lib.registry.concepts.find(x=>x.canonicalConceptId===cid).calculationCoverage]))},null,2));
