import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import * as choice from "../build/faculty-build-composer/authoring/consumer_choice_question_pool_author.mjs";
import * as inequality from "../build/faculty-build-composer/authoring/income_inequality_question_pool_author.mjs";
import * as information from "../build/faculty-build-composer/authoring/information_behavioral_political_economy_question_pool_author.mjs";

const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,"..");
const composerDir=path.join(root,"build/faculty-build-composer"),dataDir=path.join(composerDir,"data");
const libraryPath=path.join(dataDir,"composer_library.js"),registryPath=path.join(dataDir,"composer_registry.json"),manifestPath=path.join(dataDir,"composer_library_manifest.json");
const reviewManifestPath=path.join(dataDir,"concept-reviews/manifest.json"),reviewSourcePath=path.join(dataDir,"concept-reviews/full-library-production/concept_review_source.json");
const incomingDir=path.join(dataDir,"question-assets/_incoming-remaining-graphs");
const PHASE=choice.PHASE,COMPOSER_VERSION="4.5s.3k",GENERATED_AT="2026-08-26T23:15:00.000Z";
if(inequality.PHASE!==PHASE||information.PHASE!==PHASE) throw new Error("Authoring phases disagree.");

const CONFIGS=[
  { author:choice,title:"Consumer Choice",description:"Analyze budget constraints, preferences, indifference curves, marginal rates of substitution, marginal utility per dollar, and utility-maximizing consumer choice.",sourceGame:"consumer-choice-authoring",prerequisites:["demand","opportunity-cost"],related:["price-elasticity-of-demand","income-elasticity-of-demand","consumer-and-producer-surplus","marginal-analysis"],excluded:["Demand-curve shifts remain in demand; this bank focuses on an individual consumer's feasible set and preferences.","Consumer and producer surplus remain in their welfare concepts; willingness to pay is not treated as an indifference curve.","Income inequality and poverty remain in the separate distributional concept."],notes:"Standalone 160-record consumer-choice bank with eight dedicated CHOICE assets and explicit preference, budget, MRS, tangency, and equimarginal coverage." },
  { author:inequality,title:"Income Inequality, Poverty, and Redistribution",description:"Measure and compare income distributions, read Lorenz curves and Gini coefficients, analyze poverty measures and income differences, and evaluate redistribution and antipoverty policy.",sourceGame:"income-inequality-authoring",prerequisites:["percentage-change"],related:["factor-markets","labor-market-institutions","tax-wedges-and-revenue","government-spending-and-multipliers"],excluded:["Factor-price determination remains in factor-markets.","Generic tax incidence and deadweight loss remain in tax-wedges-and-revenue.","Aggregate fiscal multipliers remain in government-spending-and-multipliers; transfers here are evaluated as distributional policy."],notes:"Standalone 160-record distribution bank with three dedicated Lorenz assets, poverty measurement, in-kind transfers, redistribution philosophy, and antipoverty design." },
  { author:information,title:"Information Asymmetry, Behavioral Economics, and Political Economy",description:"Analyze hidden information and action, signaling and screening, behavioral decision patterns, and collective-choice results from Arrow, Condorcet, and the median-voter theorem.",sourceGame:"information-behavioral-political-authoring",prerequisites:["incentives","models-and-assumptions"],related:["market-failures","insurance-and-risk","monopolistic-competition","public-goods-and-common-resources"],excluded:["Advertising and product differentiation remain in monopolistic-competition unless the task specifically concerns informational signaling.","Insurance calculations remain in insurance-and-risk; this bank distinguishes selection from post-contract hidden action.","Government externality remedies and public-good provision remain in their canonical market-failure concepts."],notes:"Standalone 180-record bank with no unrelated graph dependency; adverse selection and moral hazard are separated by information type and timing, followed by behavioral and collective-choice coverage." }
];

const EXPECTED_ASSET_METADATA=Object.freeze({
  "CHOICE-01.webp":{bytes:32824,width:1761,height:1235,sha256:"d7b214200a7437647ea5750f605f691a05cc23221f764b5fb2efb33ea461fac9"},
  "CHOICE-02.webp":{bytes:44054,width:1741,height:1223,sha256:"c6cb021f7385afdeb398f89fd7af689ce31af568992573a2c01680c1fdeb3d82"},
  "CHOICE-03.webp":{bytes:40186,width:1749,height:1219,sha256:"1d3e804836571e5960ade819b8412a1a6c1d41105562fc09b88ebe6bd263bb5c"},
  "CHOICE-04.webp":{bytes:37180,width:1740,height:1222,sha256:"b838cfd9668ccc7b621ab4e7a03c5167be53416d7b01bc269124c47fad8623e3"},
  "CHOICE-05.webp":{bytes:44208,width:1600,height:1134,sha256:"afb5ff5728a78589a6638d0b3e39b81e90fe055bab8693d5f17be40db9cf388e"},
  "CHOICE-06.webp":{bytes:59836,width:1600,height:1200,sha256:"3dd9961e41c18d7055d22ad16dc8472a1df3301ff387e8be0e7ecc76764bf93d"},
  "CHOICE-07.webp":{bytes:55378,width:1600,height:1132,sha256:"39c70b0e2895222e41303a1b70f556b7de3482756453dcc6742cf4f686a26fdd"},
  "CHOICE-08.webp":{bytes:41068,width:1600,height:1200,sha256:"0ffd1918fde88d36fd83eed3a2a285b0e985a9272c737740be2d57acd4efd86b"},
  "LORENZ-01.webp":{bytes:69044,width:1720,height:1200,sha256:"05e0f6fafaa9260da33c44507cd05dc3d52fec2c14e41805b4af6a8768ca0a35"},
  "LORENZ-02.webp":{bytes:76480,width:1720,height:1200,sha256:"40384f963cb4ce8ef26b188b2df9bda49e58edb4ed8181efa172a74baf025bb1"},
  "LORENZ-03.webp":{bytes:89188,width:1601,height:1175,sha256:"629cfd3f9fb4db171762cef199cdc0dc87c76dc75fc043ed439b2f1a41cddb5f"}
});

const sha256=value=>crypto.createHash("sha256").update(value).digest("hex");
const normalize=value=>String(value??"").trim().toLowerCase().replace(/[’‘]/g,"'").replace(/[“”]/g,'"').replace(/\s+/g," ");
function stableStringify(value){if(Array.isArray(value))return`[${value.map(stableStringify).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stableStringify(value[key])}`).join(",")}}`;return JSON.stringify(value);}
function readLibrary(){const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(libraryPath,"utf8"),sandbox,{filename:libraryPath});return sandbox.window.MQ_COMPOSER_LIBRARY;}
function conceptEntries(module,conceptId){const out=[];for(const [pool,items] of Object.entries(module?.questions||{}))for(const question of items||[])out.push({conceptId,pool,question});for(const pool of ["repairQuestions","repairSeedQuestions","bridgeQuestions"])for(const question of module?.[pool]||[])out.push({conceptId,pool,question});return out;}
function allQuestionEntries(library){return Object.entries(library.concepts||{}).flatMap(([id,module])=>conceptEntries(module,id));}
function webpDimensions(bytes){if(bytes.toString("ascii",0,4)!=="RIFF"||bytes.toString("ascii",8,12)!=="WEBP")throw new Error("Invalid WebP.");const chunk=bytes.toString("ascii",12,16);if(chunk==="VP8X")return{width:1+bytes.readUIntLE(24,3),height:1+bytes.readUIntLE(27,3)};if(chunk==="VP8 ")return{width:bytes.readUInt16LE(26)&0x3fff,height:bytes.readUInt16LE(28)&0x3fff};if(chunk==="VP8L"){const bits=bytes.readUInt32LE(21);return{width:1+(bits&0x3fff),height:1+((bits>>>14)&0x3fff)}}throw new Error(`Unsupported WebP ${chunk}.`);}
function finalDir(config){return path.join(dataDir,"question-assets",config.author.CONCEPT_ID);}
function locateAsset(config,filename){const final=path.join(finalDir(config),filename);return fs.existsSync(final)?final:path.join(incomingDir,filename);}

function validateAuthorSources(library){
  const errors=[],ids=new Set(),stems=new Set();
  const newConceptIds=new Set(CONFIGS.map(c=>c.author.CONCEPT_ID));
  const existing=allQuestionEntries(library).filter(({conceptId,question})=>!newConceptIds.has(conceptId)&&question.sourceCurationPhase!==PHASE);
  const existingIds=new Set(existing.map(({question})=>String(question.id))),existingStems=new Set(existing.map(({question})=>normalize(question.q)));
  const legalTypes=new Set(["definition","application","interpretation","calculation","integration","bridge","graph_interpretation","graph_calculation","graph_integration","graph_trap"]);
  const legalPools=new Set(["easy","medium","hard","elite","legendary","easyBoss","mediumBoss","finalBoss","legendaryBoss","repairQuestions","bridgeQuestions"]);
  for(const config of CONFIGS){const a=config.author;
    if(a.productionQuestions.length!==a.ID_LAST-a.ID_FIRST+1)errors.push(`${a.CONCEPT_ID} count mismatch.`);
    a.productionQuestions.forEach((q,index)=>{
      if(q.id!==a.ID_FIRST+index)errors.push(`Noncontiguous ID ${q.id}.`);if(ids.has(String(q.id))||existingIds.has(String(q.id)))errors.push(`ID collision ${q.id}.`);ids.add(String(q.id));
      const stem=normalize(q.q);if(stems.has(stem)||existingStems.has(stem))errors.push(`Stem collision ${q.id}.`);stems.add(stem);
      if(!legalTypes.has(q.type)||!legalPools.has(q.pool))errors.push(`Unsupported routing ${q.id}.`);
      if(q.distractors.length!==3||new Set([q.answer,...q.distractors].map(normalize)).size!==4)errors.push(`Invalid answer set ${q.id}.`);
      if(!q.feedback||q.feedback.split(/\s+/).length<8)errors.push(`Underexplained feedback ${q.id}.`);
      if(q.graphRequired&&!a.GRAPH_ASSETS[q.asset])errors.push(`Unknown asset ${q.id}.`);if(!q.graphRequired&&q.asset)errors.push(`Unexpected asset ${q.id}.`);
    });
    const supports=a.productionQuestions.reduce((o,q)=>(o[q.pool]=(o[q.pool]||0)+1,o),{});if(supports.repairQuestions!==6||supports.bridgeQuestions!==6)errors.push(`${a.CONCEPT_ID} support depth mismatch.`);
    for(const filename of Object.keys(a.GRAPH_ASSETS)){const bytes=fs.readFileSync(locateAsset(config,filename)),dims=webpDimensions(bytes),expected=EXPECTED_ASSET_METADATA[filename];if(!expected||bytes.length!==expected.bytes||sha256(bytes)!==expected.sha256||dims.width!==expected.width||dims.height!==expected.height)errors.push(`Asset identity mismatch ${filename}.`);}
  }
  if(errors.length)throw new Error(errors.join("\n"));
}

function publishAssets(){
  for(const config of CONFIGS){fs.mkdirSync(finalDir(config),{recursive:true});for(const filename of Object.keys(config.author.GRAPH_ASSETS)){const incoming=path.join(incomingDir,filename),final=path.join(finalDir(config),filename);if(fs.existsSync(final)){if(fs.existsSync(incoming)&&!fs.readFileSync(incoming).equals(fs.readFileSync(final)))throw new Error(`Filename collision ${filename}.`);if(fs.existsSync(incoming))fs.unlinkSync(incoming);}else{if(!fs.existsSync(incoming))throw new Error(`Missing staged asset ${filename}.`);fs.renameSync(incoming,final);}}}
  if(fs.existsSync(incomingDir)){const remaining=fs.readdirSync(incomingDir);if(remaining.length)throw new Error(`Unexpected staged assets: ${remaining.join(", ")}`);fs.rmdirSync(incomingDir);}
}
function rotateOptions(q){const options=[...q.distractors];options.splice(q.id%4,0,q.answer);return options;}
function publishQuestion(config,q){const a=config.author,asset=q.asset?a.GRAPH_ASSETS[q.asset]:null;const safe={id:String(q.id),sourceGame:config.sourceGame,q:q.q,options:rotateOptions(q),tag:q.tag,type:q.type,objective:q.objective,difficulty:q.difficulty,conceptCluster:a.CONCEPT_ID,primarySkill:q.primarySkill,secondarySkills:q.secondarySkills,repairSkill:q.repairSkill,commonError:q.commonError,feedback:q.feedback,sourceCurationPhase:PHASE,aHash:sha256(normalize(q.answer))};if(asset)Object.assign(safe,{image:`question-assets/${a.CONCEPT_ID}/${q.asset}`,imageAlt:asset.imageAlt,graphDescription:asset.graphDescription,graphRequired:true,graphScenario:asset.scenario});const sourceHash=sha256(stableStringify(safe)),bossTier=({easyBoss:"stageOne",mediumBoss:"stageTwo",finalBoss:"stageThree",legendaryBoss:"legendary"})[q.pool]||null,instructionalRole=q.pool==="repairQuestions"?"repair":q.pool==="bridgeQuestions"?"bridge":"main";return{...safe,canonicalId:String(q.id),sourceId:q.id,sourceChapter:[],sourcePool:q.pool,sourceHash,sourceOccurrences:[{sourceGame:config.sourceGame,sourceFile:`build/faculty-build-composer/authoring/${path.basename(new URL(a===choice?"../build/faculty-build-composer/authoring/consumer_choice_question_pool_author.mjs":a===inequality?"../build/faculty-build-composer/authoring/income_inequality_question_pool_author.mjs":"../build/faculty-build-composer/authoring/information_behavioral_political_economy_question_pool_author.mjs",import.meta.url).pathname)}`,sourceGlobal:"productionQuestions",sourcePool:q.pool,routeKey:q.objective,sourceRecordOrder:q.id-a.ID_FIRST,sourceId:q.id,sourceHash,sourceCurationPhase:PHASE}],primaryConceptId:a.CONCEPT_ID,secondaryConceptIds:[],familyConceptId:a.CONCEPT_ID,subtopicIds:[],instructionalRole,canonicalDifficulty:q.difficulty,originalSourcePool:q.pool,originalBossTier:bossTier};}
function countRecords(entries){const ordinary=entries.filter(({pool})=>!["repairQuestions","repairSeedQuestions","bridgeQuestions"].includes(pool));const difficulty=entries.reduce((o,{question})=>(o[question.canonicalDifficulty||question.difficulty||"unknown"]=(o[question.canonicalDifficulty||question.difficulty||"unknown"]||0)+1,o),{});return{ordinary,difficulty,role:{boss:entries.filter(e=>e.pool==="boss").length,bridge:entries.filter(e=>e.pool==="bridgeQuestions").length,calculation:ordinary.filter(e=>/calculation/i.test(e.question.type||"")).length,elite:entries.filter(e=>e.pool==="elite").length,integration:ordinary.filter(e=>/integration/i.test(e.question.type||"")).length,legendary:entries.filter(e=>e.pool==="legendary").length,legendaryBoss:entries.filter(e=>e.pool==="legendaryBoss").length,main:entries.filter(e=>["easy","medium","hard"].includes(e.pool)).length,repair:entries.filter(e=>e.pool==="repairQuestions").length,repairSeed:0}};}
function createModule(config){const a=config.author,module={schemaVersion:"1.0.0",canonicalConceptId:a.CONCEPT_ID,title:config.title,description:config.description,sourceChapters:[],legacyObjectives:[],objectiveLabels:{...a.OBJECTIVES},questions:{easy:[],medium:[],hard:[],elite:[],legendary:[],calculation:[],boss:[],legendaryBoss:[]},repairQuestions:[],repairSeedQuestions:[],bridgeQuestions:[],directSkillRepairRoutes:{},microSkillRepairPools:{},skillRepairSeedPools:{},microSkillBridgePools:{},assets:[],assetMetadata:[],assetPaths:[],standaloneRecommendation:"standalone-ready"};for(const authored of a.productionQuestions){const published=publishQuestion(config,authored);if(["repairQuestions","bridgeQuestions"].includes(authored.pool))module[authored.pool].push(published);else module.questions[["easyBoss","mediumBoss","finalBoss"].includes(authored.pool)?"boss":authored.pool].push(published);}for(const q of module.repairQuestions)(module.microSkillRepairPools[q.primarySkill]||=[]).push(q.id);for(const q of module.bridgeQuestions)(module.microSkillBridgePools[q.primarySkill]||=[]).push(q.id);return module;}
function registerAsset(library,module,config,filename){const runtimePath=`question-assets/${config.author.CONCEPT_ID}/${filename}`,bytes=fs.readFileSync(locateAsset(config,filename)),dims=webpDimensions(bytes),authored=config.author.GRAPH_ASSETS[filename],metadata={conceptId:config.author.CONCEPT_ID,filename,sourceAssetPath:runtimePath,sourceUrl:`data/${runtimePath}`,runtimePath,sha256:sha256(bytes),sizeBytes:bytes.length,width:dims.width,height:dims.height,imageAlt:authored.imageAlt,graphDescription:authored.graphDescription,sourceCurationPhase:PHASE};module.assets.push(runtimePath);module.assetPaths.push(runtimePath);module.assetMetadata.push(metadata);library.assetInventory.push(metadata);}
function registryRecord(module,config){const entries=conceptEntries(module,config.author.CONCEPT_ID),counts=countRecords(entries);return{canonicalConceptId:config.author.CONCEPT_ID,title:config.title,description:config.description,includedSkills:[...new Set(entries.map(e=>e.question.primarySkill).filter(Boolean))].sort(),excludedNeighboringSkills:config.excluded,prerequisiteConceptIds:config.prerequisites,relatedConceptIds:config.related,sourceChapters:[],sourceObjectives:Object.keys(config.author.OBJECTIVES),sourceGames:[config.sourceGame],questionCountByRole:counts.role,questionCountByDifficulty:counts.difficulty,repairCoverage:{directSkillMatches:counts.role.repair,mainWithUsableSkill:counts.ordinary.length},bridgeCoverage:{directSkillMatches:counts.role.bridge,mainWithUsableSkill:counts.ordinary.length},calculationCoverage:counts.role.calculation,graphCoverage:counts.ordinary.filter(e=>Boolean(e.question.image)).length,status:"active",notes:config.notes,instructionalClassification:"Standalone-ready",coverageStatus:"ready-focused",coverageStatusLabel:"Ready for focused use",coverageStatusNote:config.notes,coverageFloorVersion:config.author.SOURCE_VERSION,selectionRole:"standalone"};}
function render(){const library=readLibrary();validateAuthorSources(library);const ids=new Set(CONFIGS.map(c=>c.author.CONCEPT_ID));for(const id of ids)delete library.concepts[id];library.registry.concepts=library.registry.concepts.filter(record=>!ids.has(record.canonicalConceptId));library.assetInventory=(library.assetInventory||[]).filter(asset=>asset.sourceCurationPhase!==PHASE&&!ids.has(asset.conceptId));for(const config of CONFIGS){const module=createModule(config);library.concepts[config.author.CONCEPT_ID]=module;for(const filename of Object.keys(config.author.GRAPH_ASSETS))registerAsset(library,module,config,filename);library.registry.concepts.push(registryRecord(module,config));}
  library.composerVersion=COMPOSER_VERSION;library.libraryVersion=`${library.libraryVersion.replace(new RegExp(`-${PHASE}`,"g"),"")}-${PHASE}`;library.sourceCurationPhase=PHASE;library.sourceGeneratedAt=GENERATED_AT;library.generatedAt=GENERATED_AT;library.conceptCount=Object.keys(library.concepts).length;library.canonicalQuestionCount=new Set(allQuestionEntries(library).map(e=>String(e.question.id))).size;library.registry.generatedAt=GENERATED_AT;library.registry.libraryVersion=library.libraryVersion;library.registry.composerVersion=COMPOSER_VERSION;library.registry.canonicalQuestionCount=library.canonicalQuestionCount;delete library.librarySha256;delete library.registry.librarySha256;library.librarySha256=sha256(stableStringify(library));library.registry.librarySha256=library.librarySha256;
  const reviewManifest=JSON.parse(fs.readFileSync(reviewManifestPath,"utf8")),reviewSource=JSON.parse(fs.readFileSync(reviewSourcePath,"utf8"));const expectedReviews=new Map([["consumer-choice","MICRO-58"],["income-inequality-poverty-and-redistribution","MICRO-59"],["information-asymmetry-behavioral-and-political-economy","MICRO-60"]]);for(const [conceptId,code] of expectedReviews){const mapping=reviewManifest.concepts.find(item=>item.canonicalConceptId===conceptId);if(mapping?.diagnosable!==true||mapping?.primaryReviewCode!==code)throw new Error(`Dedicated Concept Review mapping is stale for ${conceptId}.`);if(!reviewSource.reviews.some(item=>item.code===code&&item.canonicalConceptIds?.includes(conceptId)))throw new Error(`Missing dedicated Concept Review source ${code}.`);}
  const manifest={assetCount:library.assetInventory.length,assets:library.assetInventory,conceptCount:library.conceptCount,canonicalQuestionCount:library.canonicalQuestionCount,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,generatedAt:GENERATED_AT};return{outputs:[[libraryPath,`window.MQ_COMPOSER_LIBRARY=${JSON.stringify(library)};\n`],[registryPath,`${JSON.stringify(library.registry,null,2)}\n`],[manifestPath,`${JSON.stringify(manifest,null,2)}\n`],[reviewManifestPath,`${JSON.stringify(reviewManifest,null,2)}\n`],[reviewSourcePath,`${JSON.stringify(reviewSource,null,2)}\n`]],summary:{sourceVersions:CONFIGS.map(c=>c.author.SOURCE_VERSION),questions:CONFIGS.reduce((n,c)=>n+c.author.productionQuestions.length,0),graphQuestions:CONFIGS.reduce((n,c)=>n+c.author.productionQuestions.filter(q=>q.graphRequired).length,0),assets:Object.keys(EXPECTED_ASSET_METADATA).length,canonicalQuestionCount:library.canonicalQuestionCount,assetInventoryCount:library.assetInventory.length,conceptCount:library.conceptCount,librarySha256:library.librarySha256}};}

validateAuthorSources(readLibrary());if(process.argv.includes("--write"))publishAssets();const generated=render();if(process.argv.includes("--write")){for(const [file,contents] of generated.outputs)fs.writeFileSync(file,contents,"utf8");console.log(JSON.stringify({status:"WROTE",...generated.summary},null,2));}else{const stale=generated.outputs.filter(([file,contents])=>fs.readFileSync(file,"utf8")!==contents);if(stale.length){console.error(`FAIL: stale outputs: ${stale.map(([file])=>path.relative(root,file)).join(", ")}`);process.exit(1);}console.log(JSON.stringify({status:"PASS",...generated.summary},null,2));}
