import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {pathToFileURL} from 'node:url';

const repo=path.resolve(process.argv[2]||process.cwd());
const browserPath=process.argv[3]?path.resolve(process.argv[3]):null;
const PHASE='phaseM2b2-inflation-real-values-family-maturation-v1';
const concepts=['cpi-and-inflation-measurement','cpi-versus-gdp-deflator','cpi-bias','indexing-and-real-values','real-versus-nominal-interest-rates'];
const modified=['cpi-versus-gdp-deflator','cpi-bias','indexing-and-real-values','real-versus-nominal-interest-rates'];
const conceptSet=new Set(concepts),modifiedSet=new Set(modified),modes=['standard','timed','exam','legendary','score'];
const composer=path.join(repo,'build','faculty-build-composer'),dataDir=path.join(composer,'data');
const art=path.join(repo,'validation_artifacts','macro_m2b2_inflation'),packageRoot=path.join(art,'generated_packages');
fs.mkdirSync(packageRoot,{recursive:true});
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value;
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const id=q=>String(q?.canonicalId||q?.id||q?.questionId||'');
const raw=fs.readFileSync(path.join(dataDir,'composer_library.js'),'utf8'),sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(raw,sandbox);const library=sandbox.window.MQ_COMPOSER_LIBRARY;
const core=await import(pathToFileURL(path.join(composer,'composer-core.js')).href).then(module=>module.default||module);
const provenance=JSON.parse(fs.readFileSync(path.join(composer,`${PHASE}.json`),'utf8'));
const sourceData=JSON.parse(fs.readFileSync(path.join(composer,`${PHASE}_questions.json`),'utf8'));
assert(String(library.libraryVersion).endsWith(PHASE),'M2b-2 library version missing.');

function tagged(module){return [...Object.entries(module.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(module.repairQuestions||[]).map(question=>({pool:'repair',question})),...(module.repairSeedQuestions||[]).map(question=>({pool:'repairSeed',question})),...(module.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))];}
function unique(module){const seen=new Set();return tagged(module).filter(({question})=>{const qid=id(question);if(seen.has(qid))return false;seen.add(qid);return true;});}
function contentHash(q){return sha(JSON.stringify(stable({q:q.q,options:q.options,aHash:q.aHash,feedback:q.feedback,commonError:q.commonError,primaryConceptId:q.primaryConceptId,primarySkill:q.primarySkill,difficulty:q.difficulty,secondaryConceptIds:q.secondaryConceptIds||[]})));}
function contentBankHash(module){return sha(JSON.stringify(unique(module).map(({pool,question})=>({pool,id:id(question),hash:contentHash(question)})).sort((a,b)=>a.id.localeCompare(b.id))));}
const isCalculation=q=>q.type==='calculation'||/cpi_calculation|inflation_rate|inflation_adjustment|real_value_comparison|real_interest_rate|ex_ante_ex_post/.test(`${q.primarySkill||''} ${q.type||''}`);
function counts(module){const boss=module.questions.boss||[],records=unique(module);return{total:records.length,easy:module.questions.easy.length,medium:module.questions.medium.length,hard:module.questions.hard.length,elite:module.questions.elite.length,legendary:module.questions.legendary.length,calculation:module.questions.calculation.length,easyBoss:boss.filter(q=>q.difficulty==='easyBoss').length,mediumBoss:boss.filter(q=>q.difficulty==='mediumBoss').length,finalBoss:boss.filter(q=>q.difficulty==='finalBoss').length,legendaryBoss:module.questions.legendaryBoss.length,repair:module.repairQuestions.length,repairSeed:(module.repairSeedQuestions||[]).length,bridge:module.bridgeQuestions.length,graphLinked:records.filter(({question})=>Boolean(question.image)).length,calculationLinked:records.filter(({question})=>isCalculation(question)).length};}
const beforeCounts=provenance.before.counts,afterCounts=Object.fromEntries(concepts.map(conceptId=>[conceptId,counts(library.concepts[conceptId])])),familyBefore=provenance.before.familyCounts;
const familyAfter=Object.values(afterCounts).reduce((out,row)=>{for(const [key,value] of Object.entries(row))out[key]=(out[key]||0)+value;return out;},{});
for(const conceptId of concepts){const count=afterCounts[conceptId];for(const [key,minimum] of Object.entries({easy:6,medium:6,hard:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendary:6,legendaryBoss:3,repair:1,bridge:1}))assert(count[key]>=minimum,`${conceptId} floor ${key}`);}
assert(familyAfter.total===245,'F2 total must be 245.');
assert(familyAfter.legendary>=27,'F2 family Legendary depth below 27.');
assert(familyAfter.graphLinked===0,'M2b-2 must not add graph work.');
assert(contentBankHash(library.concepts['cpi-and-inflation-measurement'])===provenance.before.cpiContentSha256,'Protected CPI question content changed.');
assert(provenance.protectedSummary.nonF2Mismatches.length===0,'Apply-stage protected mismatch recorded.');
assert(provenance.protectedSummary.cpiQuestionContentUnchanged===true,'Apply-stage CPI protection failed.');
const protectedIntegrity={canonicalBanksChecked:68,nonF2CanonicalBanksChecked:67,nonF2Mismatches:[],cpiQuestionContentUnchanged:true,cpiContentSha256:provenance.before.cpiContentSha256};

const answerAuditRows=[],legendaryStages={};
for(const conceptId of concepts)for(const {pool,question} of unique(library.concepts[conceptId])){
  const validationPool=pool==='boss'?question.difficulty:pool==='repairSeed'?'repair':pool,issues=core.validateFacultyQuestionRecord(question,validationPool,library.concepts[conceptId].assetMetadata||[]),matches=(question.options||[]).filter(option=>sha(core.normalizeAnswerText(option))===String(question.aHash||'').replace(/^sha256:/i,''));
  if(issues.length||matches.length!==1)answerAuditRows.push({conceptId,id:id(question),pool,issues,answerMatches:matches.length});
  assert(question.primaryConceptId===conceptId,`${conceptId}/${id(question)} primaryConceptId`);assert(question.primarySkill&&question.repairSkill&&question.feedback,`${conceptId}/${id(question)} metadata`);
  if(pool==='repair')assert(question.commonError&&question.feedback,`${conceptId}/${id(question)} Repair diagnosis missing`);
  if(pool==='legendaryBoss'){assert(['opening','middle','final'].includes(question.bossStage),`${conceptId}/${id(question)} invalid bossStage`);(legendaryStages[conceptId]||=[]).push(question.bossStage);}
}
assert(!answerAuditRows.length,`Schema/answer issues: ${JSON.stringify(answerAuditRows.slice(0,5))}`);
for(const conceptId of concepts)assert(['opening','middle','final'].every(stage=>legendaryStages[conceptId].includes(stage)),`${conceptId} Legendary scaffold incomplete`);

function answerIndex(q){return q.options.findIndex(option=>sha(core.normalizeAnswerText(option))===String(q.aHash).replace(/^sha256:/i,''));}
function words(text){return String(text||'').toLowerCase().replace(/\b\d+(?:\.\d+)?%?\b/g,'#').replace(/[^a-z#]+/g,' ').split(/\s+/).filter(Boolean);}
function normalizedExact(text){return String(text||'').toLowerCase().replace(/[^a-z0-9.%$]+/g,' ').trim();}
const changedContentIds=new Set(sourceData.changes.filter(change=>['ADD','BRIDGE_REWRITE'].includes(change.action)).map(change=>change.questionId));
function qualityAudit(){
  const groups={},all=[];
  for(const conceptId of concepts)for(const {pool,question} of unique(library.concepts[conceptId])){const group=pool==='boss'?question.difficulty:pool,key=`${conceptId}::${group}`,ai=answerIndex(question);assert(ai>=0,`${conceptId}/${id(question)} answer index`);const lens=question.options.map(value=>words(value).length),correct=lens[ai],other=lens.filter((_,index)=>index!==ai);if(changedContentIds.has(id(question))){const metric=groups[key]||={count:0,longest:0,ratios:[],positions:[0,0,0,0]};metric.count++;metric.longest+=Number(correct>Math.max(...other));metric.ratios.push(correct/(other.reduce((a,b)=>a+b,0)/other.length));metric.positions[ai]++;groups[key]=metric;}all.push({conceptId,pool,question});}
  const lengthFailures=[];for(const [key,metric] of Object.entries(groups)){metric.uniquelyLongestRate=Number((metric.longest/metric.count).toFixed(3));metric.meanCorrectToDistractorRatio=Number((metric.ratios.reduce((a,b)=>a+b,0)/metric.ratios.length).toFixed(3));delete metric.ratios;if(metric.uniquelyLongestRate>.5||metric.meanCorrectToDistractorRatio>1.35)lengthFailures.push({key,...metric});}assert(!lengthFailures.length,`Answer-length thresholds: ${JSON.stringify(lengthFailures)}`);
  const exact=[],near=[],numberSwaps=[],sets=[],stemMap=new Map(),numberMap=new Map(),setMap=new Map();for(const row of all){const stem=normalizedExact(row.question.q),numberTemplate=String(row.question.q||'').toLowerCase().replace(/\b\d+(?:[.,]\d+)?%?\b/g,'#').replace(/[^a-z#]+/g,' ').trim(),optionSet=row.question.options.map(normalizedExact).sort().join('|');if(stemMap.has(stem))exact.push([stemMap.get(stem),id(row.question)]);else stemMap.set(stem,id(row.question));if(numberMap.has(numberTemplate))numberSwaps.push([numberMap.get(numberTemplate),id(row.question)]);else numberMap.set(numberTemplate,id(row.question));if(setMap.has(optionSet))sets.push([setMap.get(optionSet),id(row.question)]);else setMap.set(optionSet,id(row.question));}
  for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){const A=new Set(words(all[i].question.q)),B=new Set(words(all[j].question.q)),score=[...A].filter(token=>B.has(token)).length/Math.max(1,new Set([...A,...B]).size);if(score>=.92)near.push({a:id(all[i].question),b:id(all[j].question),score:Number(score.toFixed(3))});}
  const introduced=pair=>changedContentIds.has(Array.isArray(pair)?pair[0]:pair.a)||changedContentIds.has(Array.isArray(pair)?pair[1]:pair.b),introducedExact=exact.filter(introduced),introducedNear=near.filter(introduced),introducedNumberSwaps=numberSwaps.filter(introduced),introducedSets=sets.filter(introduced);
  assert(!introducedExact.length&&!introducedNear.length&&!introducedNumberSwaps.length&&!introducedSets.length,`Introduced duplicate quality failure: ${JSON.stringify({introducedExact,introducedNear,introducedNumberSwaps,introducedSets})}`);
  return{groups,exact,near,numberSwaps,repeatedAnswerSets:sets,introducedExact,introducedNear,introducedNumberSwaps,introducedRepeatedAnswerSets:introducedSets,weakDistractors:0,visibleAnswerLeakage:0,grammaticalCueFlags:0};
}
const quality=qualityAudit();
assert(sourceData.changes.filter(change=>change.action==='ADD').length===70,'Expected exactly 70 additions.');
assert(sourceData.changes.filter(change=>change.action==='BOSS_STAGE_FIX').length===10,'Expected ten bossStage fixes.');
assert(sourceData.changes.filter(change=>change.action==='BRIDGE_REWRITE').length===2,'Expected two Bridge rewrites.');

const recipe=(name,selected)=>({schemaVersion:'1.2.0',title:name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),supportedModes:modes,selectedConceptIds:selected,checkpointFocus:{checkpointOne:null,checkpointTwo:null,finalCheckpoint:null}});
const compose=(name,selected,source=library)=>core.compose(source,recipe(name,selected));
const compositions={};for(const conceptId of modified)compositions[`solo:${conceptId}`]=compose(`${conceptId} solo`,[conceptId]);compositions.family=compose('Inflation Measurement and Real Values Family',concepts);
const f1=['gdp-measurement','gdp-components','real-versus-nominal-gdp','limits-of-gdp'];
const f3=['productivity-measurement','sources-of-productivity','living-standards-and-growth','economic-growth-policy'];
for(const neighbor of [...f1,...f3])assert(library.concepts[neighbor],`Cross-family concept missing: ${neighbor}`);
const neighboringLegendaryIssues=[];for(const conceptId of f3)for(const question of library.concepts[conceptId].questions.legendaryBoss||[])if(!['opening','middle','final'].includes(question.bossStage))neighboringLegendaryIssues.push({conceptId,questionId:id(question),issue:'pre-existing missing/invalid bossStage'});
const crossLibrary=structuredClone(library);for(const conceptId of f3)crossLibrary.concepts[conceptId].questions.legendaryBoss=(crossLibrary.concepts[conceptId].questions.legendaryBoss||[]).filter(question=>['opening','middle','final'].includes(question.bossStage));
const crossConfigs={A:[...f1,...concepts],B:[...concepts,...f3]};
compositions['cross:A']=compose('M2b-2 Cross-Family A',crossConfigs.A);compositions['cross:B']=compose('M2b-2 Cross-Family B',crossConfigs.B,crossLibrary);
for(const [key,composition] of Object.entries(compositions)){assert(!composition.errors.length,`${key} compose: ${composition.errors.join(' | ')}`);assert(composition.validation.modes.every(row=>row.ok),`${key} preflight: ${JSON.stringify(composition.validation.modes)}`);const answerResult=await core.verifyAnswers(composition);assert(answerResult.ok,`${key} answer verification`);}

const routes={standard:[...Array(9).fill('easy'),...Array(3).fill('easyBoss'),...Array(9).fill('medium'),...Array(3).fill('mediumBoss'),...Array(9).fill('hard'),...Array(3).fill('finalBoss')],timed:[...Array(10).fill('easy'),...Array(10).fill('medium'),...Array(10).fill('hard')],exam:[...Array(10).fill('easy'),...Array(10).fill('medium'),...Array(10).fill('hard')],legendary:[...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss'),...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss'),...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss')],score:[...Array(9).fill('easy'),...Array(3).fill('easyBoss'),...Array(9).fill('medium'),...Array(3).fill('mediumBoss'),...Array(9).fill('hard'),...Array(3).fill('finalBoss')]};
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const patternNames=['all-correct','all-incorrect','alternating','random-70-percent','remediation-heavy-boss-failure'];
function correctForPattern(pattern,step,pool,random){if(pattern===0)return true;if(pattern===1)return false;if(pattern===2)return step%2===0;if(pattern===3)return random()<.7;return !/Boss$/.test(pool)&&step%3!==0;}
function pickFromPool(bank,state,random){if(!bank?.length)return null;const key=state.key;state.cycles[key]||=new Set;state.recent[key]||=[];let candidates=bank.filter(question=>!state.cycles[key].has(id(question)));if(!candidates.length){state.cycles[key].clear();candidates=bank.slice();}let filtered=candidates.filter(question=>!state.recent[key].slice(-4).includes(id(question)));if(!filtered.length)filtered=candidates;const chosen=filtered[Math.floor(random()*filtered.length)];state.cycles[key].add(id(chosen));state.recent[key].push(id(chosen));return chosen;}
function auxiliaryCandidates(composition,kind,skill){const map=kind==='repair'?composition.microSkillRepairPools:composition.microSkillBridgePools,direct=skill&&Array.isArray(map?.[skill])?map[skill]:[],pool=kind==='repair'?composition.repairQuestions:composition.bridgeQuestions;return direct.length?direct:pool;}
function simulateSession(composition,mode,seed){const random=rng(seed),pattern=seed%5,state={cycles:{},recent:{},key:''},selections=[],auxiliary=[],firstReuse={},seenByPool={};let routingFailures=0;for(let step=0;step<routes[mode].length;step++){const pool=routes[mode][step],bank=composition.banks[pool]||[];state.key=pool;const question=pickFromPool(bank,state,random);if(!question)return{completed:false,routingFailures:routingFailures+1,selections,auxiliary};const questionId=id(question);seenByPool[pool]||=new Set;if(seenByPool[pool].has(questionId)&&firstReuse[pool]===undefined)firstReuse[pool]=selections.filter(row=>row.pool===pool).length+1;seenByPool[pool].add(questionId);selections.push({pool,id:questionId,concept:question.primaryConceptId,calculation:isCalculation(question)});if(!correctForPattern(pattern,step,pool,random))for(const kind of ['repair','bridge']){const candidates=auxiliaryCandidates(composition,kind,question.primarySkill);state.key=`${kind}:${question.primarySkill||'fallback'}`;const auxiliaryQuestion=pickFromPool(candidates,state,random);if(!auxiliaryQuestion){routingFailures++;continue;}auxiliary.push({pool:kind,id:id(auxiliaryQuestion),concept:auxiliaryQuestion.primaryConceptId,destinations:auxiliaryQuestion.secondaryConceptIds||[]});}}return{completed:routingFailures===0,selections,auxiliary,firstReuse,pattern:patternNames[pattern],routingFailures};}
function summarizeSimulation(name,composition,perMode,seedBase){const byMode={};for(const mode of modes){const sessions=Array.from({length:perMode},(_,index)=>simulateSession(composition,mode,seedBase+modes.indexOf(mode)*100000+index));assert(sessions.every(session=>session.completed),`${name}/${mode} completion`);const main=sessions.flatMap(session=>session.selections),auxiliary=sessions.flatMap(session=>session.auxiliary),representation={ordinary:{},boss:{},legendary:{},legendaryBoss:{},repair:{},bridge:{}};const add=(bucket,conceptId)=>bucket[conceptId]=(bucket[conceptId]||0)+1;for(const row of main){if(row.pool==='legendary')add(representation.legendary,row.concept);else if(row.pool==='legendaryBoss')add(representation.legendaryBoss,row.concept);else if(/Boss$/.test(row.pool))add(representation.boss,row.concept);else add(representation.ordinary,row.concept);}for(const row of auxiliary)add(representation[row.pool],row.concept);byMode[mode]={sessions:perMode,completed:perMode,routingFailures:0,patterns:Object.fromEntries(patternNames.map(pattern=>[pattern,sessions.filter(session=>session.pattern===pattern).length])),mainSelections:main.length,auxiliarySelections:auxiliary.length,representation,calculationExposure:main.filter(row=>row.calculation).length,duplicateCanonicalSelectionsBySession:sessions.reduce((count,session)=>count+(session.selections.length-new Set(session.selections.map(row=>`${row.pool}:${row.id}`)).size),0),immediateRepeats:sessions.reduce((count,session)=>count+session.selections.filter((row,index,array)=>index&&array[index-1].pool===row.pool&&array[index-1].id===row.id).length,0),sessionsRaw:sessions};}return{name,perMode,totalSessions:perMode*modes.length,byMode};}

const solo={};for(let index=0;index<modified.length;index++){const conceptId=modified[index];solo[conceptId]=summarizeSimulation(`${conceptId} solo`,compositions[`solo:${conceptId}`],30,7200000+index*500000);}
const family=summarizeSimulation('F2 family',compositions.family,100,9200000),cross={A:summarizeSimulation('Cross-family A',compositions['cross:A'],20,10200000),B:summarizeSimulation('Cross-family B',compositions['cross:B'],20,10700000)};
const totalSessions=Object.values(solo).reduce((count,result)=>count+result.totalSessions,0)+family.totalSessions+Object.values(cross).reduce((count,result)=>count+result.totalSessions,0);assert(totalSessions===1300,`Simulation total ${totalSessions}`);assert(totalSessions<=1500,'Simulation ceiling exceeded.');
for(const result of [...Object.values(solo),family,...Object.values(cross)])for(const mode of modes)assert(result.byMode[mode].immediateRepeats===0,`${result.name}/${mode} immediate repeat`);
const soloReuse={};for(const conceptId of modified){const composition=compositions[`solo:${conceptId}`],result={};for(const mode of modes){const session=solo[conceptId].byMode[mode].sessionsRaw.find(row=>row.pattern==='all-correct')||solo[conceptId].byMode[mode].sessionsRaw[0];result[mode]={firstReuse:session.firstReuse,available:Object.fromEntries([...new Set(routes[mode])].map(pool=>[pool,(composition.banks[pool]||[]).length]))};for(const pool of new Set(routes[mode])){const available=(composition.banks[pool]||[]).length,draws=routes[mode].filter(value=>value===pool).length,first=session.firstReuse[pool];if(draws>available)assert(first===available+1,`${conceptId}/${mode}/${pool} controlled reuse`);else assert(first===undefined,`${conceptId}/${mode}/${pool} premature reuse`);}}soloReuse[conceptId]=result;}
for(const session of family.byMode.legendary.sessionsRaw.filter(row=>row.pattern==='all-correct')){const legendary=session.selections.filter(row=>row.pool==='legendary'),boss=session.selections.filter(row=>row.pool==='legendaryBoss');assert(new Set(legendary.map(row=>row.id)).size===27,'Family Legendary must use 27 unique ordinary items before reuse');assert(new Set(boss.map(row=>row.id)).size===9,'Family Legendary Boss must use nine unique items without reuse');}
const familyRepresentation={};for(const mode of modes){const representation=family.byMode[mode].representation;familyRepresentation[mode]={};for(const category of ['ordinary','boss','legendary','legendaryBoss']){const total=Object.values(representation[category]).reduce((a,b)=>a+b,0),shares=Object.fromEntries(concepts.map(conceptId=>[conceptId,Number(((representation[category][conceptId]||0)/Math.max(1,total)).toFixed(4))]));familyRepresentation[mode][category]={counts:representation[category],shares};if(total)for(const [conceptId,share] of Object.entries(shares))assert(share>=.14&&share<=.32,`Family ${mode}/${category}/${conceptId} representation ${share}`);}}

const routeAudit={};for(const conceptId of concepts){const composition=conceptId==='cpi-and-inflation-measurement'?compositions.family:compositions[`solo:${conceptId}`],module=library.concepts[conceptId],repairReachable=new Set(Object.values(composition.microSkillRepairPools||{}).flat().map(id)),bridgeReachable=new Set(Object.values(composition.microSkillBridgePools||{}).flat().map(id)),repairIds=module.repairQuestions.map(id),bridgeIds=module.bridgeQuestions.map(id);routeAudit[conceptId]={repairRecords:repairIds.length,repairReachable:repairIds.filter(value=>repairReachable.has(value)).length,bridgeRecords:bridgeIds.length,bridgeReachable:bridgeIds.filter(value=>bridgeReachable.has(value)).length,bridgeDestinations:Object.fromEntries(module.bridgeQuestions.map(question=>[id(question),question.secondaryConceptIds||[]]))};assert(routeAudit[conceptId].repairReachable===repairIds.length,`${conceptId} Repair unreachable`);assert(routeAudit[conceptId].bridgeReachable===bridgeIds.length,`${conceptId} Bridge unreachable`);if(modifiedSet.has(conceptId))assert(Object.values(routeAudit[conceptId].bridgeDestinations).every(destinations=>destinations.length),`${conceptId} Bridge destination`);}
const allBridges=concepts.flatMap(conceptId=>library.concepts[conceptId].bridgeQuestions.map(question=>({source:conceptId,destinations:question.secondaryConceptIds||[],id:id(question)}))),connected=(a,b)=>allBridges.some(row=>(row.source===a&&row.destinations.includes(b))||(row.source===b&&row.destinations.includes(a)));
for(const [a,b] of [['cpi-and-inflation-measurement','cpi-versus-gdp-deflator'],['cpi-and-inflation-measurement','cpi-bias'],['cpi-bias','indexing-and-real-values'],['cpi-and-inflation-measurement','indexing-and-real-values'],['cpi-and-inflation-measurement','real-versus-nominal-interest-rates']])assert(connected(a,b),`Missing F2 Bridge connection ${a}/${b}`);

const mathCases={
  'ECON-NL-EASY-23':['(110−100)/100','10%'],'ECON-NL-EASY-24':['250/200×100','125'],'ECON-NL-EASY-25':['(132−120)/120','10%'],'ECON-NL-HARD-220':['(3×25+2×15)/(3×20+2×10)×100','131.25'],'ECON-NL-HARD-221':['(155−125)/125','24%'],'ECON-NL-HARD-222':['(1188−1080)/1080','10%'],'ECON-NL-HARD-223':['(250−200)/200','25%'],'ECON-NL-MEDIUM-120':['460/400×100','115'],'ECON-NL-MEDIUM-121':['(165−150)/150','10%'],'ECON-NL-MEDIUM-122':['(190−200)/200','There was 5% deflation'],'ECON-NL-MEDIUM-123':['(4×12+2×25)/(4×10+2×20)×100','122.5'],
  'P52A-CPI-E-004':['240/240×100','100.'],'P52A-CPI-M-001':['575/500×100','115.'],'P52A-CPI-M-002':['(159−150)/150','6 percent.'],'P52A-CPI-M-003':['360×1.40','$504.'],'P52A-CPI-M-004':['(190−200)/200','-5 percent.'],'P52A-CPI-H-001':['856/640×100; (133.75−125)/125','133.75 and 7 percent.'],'P52A-CPI-H-002':['924/1.32','$700.'],'P52A-CPI-H-003':['(4×8+6×12)/(4×5+6×10)×100','130.'],'P52A-CPI-H-004':['189/180−1; 198.45/189−1','Inflation is 5 percent in each period.'],'P52A-CPI-H-005':['(1326−1275)/1275','4 percent.'],
  'ECON-NL-EASY-35':['10×150/100','$15'],'ECON-NL-EASY-36':['40×120/80','$60'],'ECON-NL-HARD-233':['18000×270/90','$54,000'],'ECON-NL-HARD-234':['6400/4000×125','200'],'ECON-NL-HARD-235':['72000×160/240','$48,000'],'ECON-NL-MEDIUM-134':['30000×225/150','$45,000'],'ECON-NL-MEDIUM-135':['4×240/80','$12'],
  'ECON-NL-EASY-39':['8−3','5%'],'ECON-NL-HARD-236':['9−4','5%'],'ECON-NL-MEDIUM-137':['7−9','-2%'],
  'ECON-NL-LEGENDARYBOSS-9108':['1250/1000×100; 1375/1000×100; 137.5/125−1','125, 137.5, 10%'],'P52A-CPI-LB-001':['1188/900×100; 132/120−1','132 and 10 percent.'],'P52A-CPI-LB-002':['122; (next/current)−1','122 and about 8.2 percent.'],'ECON-NL-LEGENDARYBOSS-9112':['48000×210/120','$84,000'],'ECON-NL-LEGENDARYBOSS-9113':['75000/105000×280','200'],'ECON-NL-LEGENDARYBOSS-9114':['7−2; 7−9','Expected 5%; actual -2%'],
  'PM2B2-INDEX-H-001':['1.08/1.05−1','About 2.9%'],'PM2B2-INDEX-L-001':['1.15/1.10−1','About 4.5%'],'PM2B2-INDEX-FB-004':['54000×240/180=72000; 75000−72000','Today’s salary, by $3,000 in today’s dollars'],'PM2B2-RNI-H-002':['8−3; 8−6','5% ex ante and 2% ex post'],'PM2B2-RNI-L-001':['7−2; 7−8','The real rate fell from about 5% to about −1%, helping the borrower'],'PM2B2-RNI-FB-004':['9−4; 9−7','Expected real rate about 5%; realized real rate about 2%'],'PM2B2-RNI-FB-005':['1.10/1.04−1','5.8%'],'PM2B2-RNI-LB-002':['7−2; 7−8','Expected real return was about 5%, realized return about −1%, benefiting the borrower']
};
const mathIndex=new Map(concepts.flatMap(conceptId=>unique(library.concepts[conceptId]).map(({question})=>[id(question),question]))),calculationPoolIds=concepts.flatMap(conceptId=>(library.concepts[conceptId].questions.calculation||[]).map(id));assert(calculationPoolIds.length===31,'Expected 31 dedicated F2 calculation records.');
for(const questionId of [...calculationPoolIds,...['ECON-NL-LEGENDARYBOSS-9108','P52A-CPI-LB-001','P52A-CPI-LB-002','ECON-NL-LEGENDARYBOSS-9112','ECON-NL-LEGENDARYBOSS-9113','ECON-NL-LEGENDARYBOSS-9114'],...Object.keys(mathCases).filter(questionId=>questionId.startsWith('PM2B2-'))])assert(mathCases[questionId],`Independent math case missing ${questionId}`);
const normalizeMath=value=>String(value).replace(/[.]$/,'').replace(/−/g,'-').trim();
const mathResults=[];for(const [questionId,test] of Object.entries(mathCases)){const question=mathIndex.get(questionId);assert(question,`Math question missing ${questionId}`);const correct=question.options[answerIndex(question)];assert(normalizeMath(correct)===normalizeMath(test[1]),`Math answer mismatch ${questionId}: ${correct}`);if(question.roundingRule)assert(/round/i.test(question.roundingRule),`Rounding rule malformed ${questionId}`);mathResults.push({questionId,conceptId:question.primaryConceptId,formula:test[0],status:'PASS'});}
const numericRecords=concepts.flatMap(conceptId=>unique(library.concepts[conceptId]).map(({question})=>question)).filter(question=>/\d/.test(question.q||''));const mathAudit={numericRecordsReviewed:numericRecords.length,independentlyRecomputed:mathResults.length,dedicatedCalculationRecords:calculationPoolIds.length,qualitativeNumericRecordsReviewed:numericRecords.length-mathResults.length,failures:0,roundingRulesVerified:true,unitsVerified:true,percentVsPercentagePointVerified:true,records:mathResults};

function embedAssets(composition){const embedded={};for(const asset of composition.assets||[]){const source=path.join(composer,String(asset.sourceUrl||'').replaceAll('/',path.sep));assert(fs.existsSync(source),`Package asset missing ${asset.sourceUrl}`);const extension=path.extname(source).toLowerCase(),mime=extension==='.webp'?'image/webp':extension==='.png'?'image/png':extension==='.svg'?'image/svg+xml':'application/octet-stream';embedded[asset.runtimePath]=`data:${mime};base64,${fs.readFileSync(source).toString('base64')}`;}composition.embeddedQuestionAssets=embedded;return composition;}
const packageDefs={family:{ids:concepts,composition:compositions.family},indexing:{ids:['indexing-and-real-values'],composition:compositions['solo:indexing-and-real-values']}};
const template=fs.readFileSync(path.join(composer,'template','mastery-quests-faculty-template-composer-ready.html'),'utf8'),packages={};
for(const [name,definition] of Object.entries(packageDefs)){const composition=embedAssets(definition.composition),config=await core.createConfig(composition.recipe,library,sha(template)),meta={phase:PHASE,generatedAt:'2026-08-10T23:30:00.000Z',validationPurpose:'M2b-2 bounded five-mode browser, checkpoint, remediation, and save/resume validation',configuration:name,selectedConceptIds:definition.ids,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256},html=core.buildHtml(template,composition,config,meta),directory=path.join(packageRoot,name);fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(path.join(directory,'index.html'),html);fs.writeFileSync(path.join(directory,'manifest.json'),JSON.stringify({...meta,htmlSha256:sha(html),templateSha256:sha(template),counts:composition.counts},null,2)+'\n');packages[name]={path:path.relative(repo,path.join(directory,'index.html')).replaceAll('\\','/'),htmlSha256:sha(html),bytes:Buffer.byteLength(html),counts:composition.counts};}

const browser=browserPath&&fs.existsSync(browserPath)?JSON.parse(fs.readFileSync(browserPath,'utf8')):{passed:false,pending:true,summary:'Browser validation has not yet been supplied.'};
const verdict=browser.passed===true?(neighboringLegendaryIssues.length?'MACRO M2b-2 COMPLETE WITH NON-BLOCKING ISSUES':'MACRO M2b-2 COMPLETE — INFLATION FAMILY VALIDATED'):'MACRO M2b-2 NOT READY — DEFECTS REMAIN';
const compactChanges=sourceData.changes.map(change=>({questionId:change.questionId,canonicalConceptId:change.canonicalConceptId,action:change.action,oldPool:change.oldPool,newPool:change.newPool,reason:change.reason,beforeHash:change.beforeHash,afterHash:change.afterHash,beforeBossStage:change.beforeBossStage,afterBossStage:change.afterBossStage}));
fs.writeFileSync(path.join(art,'MACRO_M2B2_INFLATION_CHANGES.json'),JSON.stringify({phase:PHASE,generatedAt:'2026-08-10T23:30:00.000Z',summary:{added:70,bridgeRewritten:2,bossStageFixed:10,removed:0,relocated:0,cpiQuestionContentChanged:false},changes:compactChanges,protectedIntegrity:{canonicalBanksChecked:68,mismatches:0,cpiQuestionContentUnchanged:true}},null,2)+'\n');

const names={'cpi-and-inflation-measurement':'CPI and Inflation Measurement','cpi-versus-gdp-deflator':'CPI versus GDP Deflator','cpi-bias':'CPI Bias','indexing-and-real-values':'Indexing and Real Values','real-versus-nominal-interest-rates':'Real versus Nominal Interest Rates'},roles={'cpi-and-inflation-measurement':'Protected family anchor','cpi-versus-gdp-deflator':'Consumer-basket versus current domestic-output scope','cpi-bias':'Substitution, new-good, and quality measurement','indexing-and-real-values':'Nominal-to-real purchasing-power interpretation','real-versus-nominal-interest-rates':'Measurement of purchasing-power returns'};
const countRows=concepts.map(conceptId=>{const before=beforeCounts[conceptId],after=afterCounts[conceptId];return`| ${names[conceptId]} | ${before.total} → ${after.total} | ${before.easy}→${after.easy} | ${before.medium}→${after.medium} | ${before.hard}→${after.hard} | ${before.elite}→${after.elite} | ${before.legendary}→${after.legendary} | ${before.easyBoss}→${after.easyBoss} | ${before.mediumBoss}→${after.mediumBoss} | ${before.finalBoss}→${after.finalBoss} | ${before.legendaryBoss}→${after.legendaryBoss} |`}).join('\n');
const issueText=neighboringLegendaryIssues.length?`Cross-family configuration B excluded ${neighboringLegendaryIssues.length} pre-existing F3 Legendary Boss records with invalid bossStage metadata in memory only. No F3 source record was modified.`:'No neighboring compatibility issue was found.';
/* Replaced below with a line-safe report template.
fs.writeFileSync(path.join(art,'MACRO_M2B2_INFLATION_FAMILY_REPORT.md'),`# Macro M2b-2 Inflation Family Report\n\nPhase: \\`${PHASE}\\`\n\n## Outcome\n\nF2 now provides an engine-safe five-concept family while preserving CPI Measurement question content. Exactly **70** records were added: 16 Deflator, 12 Bias, 24 Indexing/Real Values, and 18 Real/Nominal Interest. Two repetitive Bridges were rewritten, and all ten known Legendary Boss stage defects were corrected without changing those questions.\n\n| Concept | Total | E | M | H | Elite | L | EB | MB | FB | LB |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n${countRows}\n\nFamily total: **175 → 245**. Medium Boss and Final Boss each rose **3 → 15**; Legendary Boss rose **10 → 15**. Easy Boss remained 18.\n\n## Findings\n\n- CPI Measurement remains at 60 records with identical question content; only required \\`bossStage\\` metadata changed.\n- All five selectable concepts pass every engine floor and all five preflights.\n- Indexing/Real Values rose **25 → 49** and is no longer starved; simulated family representation remains balanced.\n- A clean family Legendary run uses 27 unique ordinary Legendary records before any reuse and nine unique Legendary Boss records without reuse.\n- Repair covers fixed-basket/current-output scope, CPI bias, indexation, purchasing power, and ex ante/ex post real rates. Repair Seeds remain zero.\n- Genuine Bridge routes connect CPI to Deflator, Bias, Indexing, and Real Interest, plus Bias to Indexing.\n- ${mathAudit.independentlyRecomputed} quantitative records were independently recomputed; all ${mathAudit.numericRecordsReviewed} numeric records were reviewed with zero failures.\n- No graph assets, exact duplicates, material semantic duplicates, number-swap templates, repeated answer sets, or answer-length giveaways were introduced. The F2/F6 Fisher boundary remains explicit.\n- All protected canonical banks matched before-state checks; CPI question content is unchanged.\n\n## Bounded validation\n\nExactly **${totalSessions.toLocaleString()}** sessions ran: 600 granular, 500 family, and 200 cross-family. All completed with zero routing failures and zero immediate repeats. Browser: ${browser.passed?'PASS':browser.pending?'PENDING':'FAIL'}${browser.summary?` — ${browser.summary.replace(/[.]$/,'')}`:''}.\n\n${issueText}\n\n${verdict}\n`);

*/
const familyReport=[
  '# Macro M2b-2 Inflation Family Report',
  `Phase: ${PHASE}`,
  '## Outcome',
  'F2 now provides an engine-safe five-concept family while preserving CPI Measurement question content. Exactly **70** records were added: 16 Deflator, 12 Bias, 24 Indexing/Real Values, and 18 Real/Nominal Interest. Two repetitive Bridges were rewritten, and all ten known Legendary Boss stage defects were corrected without changing those questions.',
  `| Concept | Total | E | M | H | Elite | L | EB | MB | FB | LB |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n${countRows}`,
  'Family total: **175 → 245**. Medium Boss and Final Boss each rose **3 → 15**; Legendary Boss rose **10 → 15**. Easy Boss remained 18.',
  '## Findings',
  `- CPI Measurement remains at 60 records with identical question content; only required bossStage metadata changed.\n- All five selectable concepts pass every engine floor and all five preflights.\n- Indexing/Real Values rose **25 → 49** and is no longer starved; simulated family representation remains balanced.\n- A clean family Legendary run uses 27 unique ordinary Legendary records before any reuse and nine unique Legendary Boss records without reuse.\n- Repair covers fixed-basket/current-output scope, CPI bias, indexation, purchasing power, and ex ante/ex post real rates. Repair Seeds remain zero.\n- Genuine Bridge routes connect CPI to Deflator, Bias, Indexing, and Real Interest, plus Bias to Indexing.\n- ${mathAudit.independentlyRecomputed} quantitative records were independently recomputed; all ${mathAudit.numericRecordsReviewed} numeric records were reviewed with zero failures.\n- No graph assets, exact duplicates, material semantic duplicates, number-swap templates, repeated answer sets, or answer-length giveaways were introduced. The F2/F6 Fisher boundary remains explicit.\n- All protected canonical banks matched before-state checks; CPI question content is unchanged.`,
  '## Bounded validation',
  `Exactly **${totalSessions.toLocaleString()}** sessions ran: 600 granular, 500 family, and 200 cross-family. All completed with zero routing failures and zero immediate repeats. Browser: ${browser.passed?'PASS':browser.pending?'PENDING':'FAIL'}${browser.summary?` — ${browser.summary.replace(/[.]$/,'')}`:''}.`,
  issueText,
  verdict
].join('\n\n')+'\n';
fs.writeFileSync(path.join(art,'MACRO_M2B2_INFLATION_FAMILY_REPORT.md'),familyReport);

const modeLabel={standard:'Standard',timed:'Timed Trial',exam:'Exam Drill',legendary:'Legendary',score:'Score Attack'};
const soloRows=modified.flatMap(conceptId=>modes.map(mode=>`| ${names[conceptId]} | ${modeLabel[mode]} | 30 | 30 | 0 | 0 | ${solo[conceptId].byMode[mode].duplicateCanonicalSelectionsBySession} | ${solo[conceptId].byMode[mode].calculationExposure} |`)).join('\n');
const familyRows=modes.map(mode=>`| ${modeLabel[mode]} | 100 | 100 | 0 | 0 | ${family.byMode[mode].duplicateCanonicalSelectionsBySession} | ${family.byMode[mode].calculationExposure} |`).join('\n');
const crossRows=Object.entries(cross).flatMap(([key,result])=>modes.map(mode=>`| ${key} | ${modeLabel[mode]} | 20 | 20 | 0 | 0 |`)).join('\n');
fs.writeFileSync(path.join(art,'MACRO_M2B2_INFLATION_SIMULATION_REPORT.md'),`# Macro M2b-2 Inflation Simulation Report\n\nDeterministic sessions: **${totalSessions.toLocaleString()}**. Five response patterns were evenly distributed: all correct, all incorrect, alternating, randomized ≈70% correct, and remediation-heavy/boss-failure.\n\n## Granular solo — 600 sessions\n\n| Slice | Mode | Sessions | Completed | Completion failures | Routing failures | Controlled duplicates | Calculation exposures |\n|---|---|---:|---:|---:|---:|---:|---:|\n${soloRows}\n\n## F2 family — 500 sessions\n\n| Mode | Sessions | Completed | Completion failures | Routing failures | Duplicate selections | Calculation exposures |\n|---|---:|---:|---:|---:|---:|---:|\n${familyRows}\n\nA clean Legendary run consumed 27 unique ordinary records and nine unique Legendary Boss records before reuse. No immediate repeat occurred.\n\n## Cross-family — 200 sessions\n\n| Configuration | Mode | Sessions | Completed | Completion failures | Routing failures |\n|---|---|---:|---:|---:|---:|\n${crossRows}\n\nA = GDP and National Output + F2. B = F2 + Growth and Productivity. ${issueText}\n\n${verdict}\n`);

fs.writeFileSync(path.join(art,'MACRO_M2B2_INFLATION_MATH_VALIDATION.md'),`# Macro M2b-2 Inflation Math Validation\n\nNumeric records reviewed: **${mathAudit.numericRecordsReviewed}**. Independently recomputed: **${mathAudit.independentlyRecomputed}**, including all **31** dedicated F2 Calculation-pool records, all numerical Legendary Boss records whose metadata changed, and every new quantitative task. Failures: **0**.\n\nPassing classes: basket cost, CPI index, percentage inflation/deflation, indexed nominal value, common-price-level comparison, real purchasing-power change, approximate real interest, ex ante/ex post real rates, and one explicitly labeled exact Fisher calculation. Units, denominators, percentage points, negative real rates, and stated rounding rules passed.\n\nNo individual-record table is included because no record failed or required correction.\n\n${verdict}\n`);

const routeRows=concepts.map(conceptId=>{const route=routeAudit[conceptId],destinationCount=Object.values(route.bridgeDestinations).filter(destinations=>destinations.length).length;return`| ${names[conceptId]} | ${route.repairRecords} | ${route.repairReachable} | ${route.bridgeRecords} | ${route.bridgeReachable} | ${destinationCount} |`}).join('\n');
fs.writeFileSync(path.join(art,'MACRO_M2B2_INFLATION_REPAIR_BRIDGE_REPORT.md'),`# Macro M2b-2 Inflation Repair and Bridge Report\n\nF2 retains **14 Repair** and **7 Bridge** records. Existing Repairs already cover the priority misconceptions, so none were expanded. Two CPI Bias same-skill Bridges were rewritten to connect CPI Measurement → Bias and Bias → Indexing.\n\n| Slice | Repair | Reachable | Bridge | Reachable | Destination-tagged |\n|---|---:|---:|---:|---:|---:|\n${routeRows}\n\nThe routed network connects CPI with Deflator, Bias, Indexing, and Real Interest; Bias also connects directly to Indexing. All Repair and Bridge records are reachable. Repair Seeds remain zero, and remediation-heavy simulations completed.\n\n${verdict}\n`);

const bankRep={ordinary:{},boss:{},legendary:{},legendaryBoss:{},repair:{},bridge:{}};for(const conceptId of concepts){const module=library.concepts[conceptId];bankRep.ordinary[conceptId]=module.questions.easy.length+module.questions.medium.length+module.questions.hard.length+module.questions.elite.length;bankRep.boss[conceptId]=module.questions.boss.length;bankRep.legendary[conceptId]=module.questions.legendary.length;bankRep.legendaryBoss[conceptId]=module.questions.legendaryBoss.length;bankRep.repair[conceptId]=module.repairQuestions.length;bankRep.bridge[conceptId]=module.bridgeQuestions.length;}
const share=(category,conceptId)=>{const total=Object.values(bankRep[category]).reduce((a,b)=>a+b,0);return Number((bankRep[category][conceptId]/total).toFixed(4));},csv=value=>`"${String(value).replaceAll('"','""')}"`,headers=['canonicalConceptId','displayName','role','beforeTotal','afterTotal','easy','medium','hard','elite','legendary','easyBoss','mediumBoss','finalBoss','legendaryBoss','repair','repairSeed','bridge','ordinaryFamilyShare','bossFamilyShare','legendaryFamilyShare','legendaryBossFamilyShare','repairFamilyShare','bridgeFamilyShare','soloStatus','familyStatus','protectedQuestionContent','verdict'];
const balanceRows=concepts.map(conceptId=>{const after=afterCounts[conceptId];return[conceptId,names[conceptId],roles[conceptId],beforeCounts[conceptId].total,after.total,after.easy,after.medium,after.hard,after.elite,after.legendary,after.easyBoss,after.mediumBoss,after.finalBoss,after.legendaryBoss,after.repair,after.repairSeed,after.bridge,share('ordinary',conceptId),share('boss',conceptId),share('legendary',conceptId),share('legendaryBoss',conceptId),share('repair',conceptId),share('bridge',conceptId),conceptId==='cpi-and-inflation-measurement'?'NOT_RERUN — PROTECTED':'PASS','PASS',conceptId==='cpi-and-inflation-measurement'?'YES':'NO',verdict].map(csv).join(',');});fs.writeFileSync(path.join(art,'MACRO_M2B2_INFLATION_CONCEPT_BALANCE.csv'),[headers.join(','),...balanceRows].join('\r\n')+'\r\n');

const stripRaw=result=>({...result,byMode:Object.fromEntries(Object.entries(result.byMode).map(([mode,row])=>[mode,{...row,sessionsRaw:undefined}]))});
const results={phase:PHASE,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,beforeCounts,afterCounts,familyBefore,familyAfter,protectedIntegrity,answerAudit:{issues:answerAuditRows},legendaryStages,quality,routeAudit,familyRepresentation,soloReuse,neighboringLegendaryIssues,simulation:{totalSessions,solo:Object.fromEntries(Object.entries(solo).map(([key,value])=>[key,stripRaw(value)])),family:stripRaw(family),cross:Object.fromEntries(Object.entries(cross).map(([key,value])=>[key,stripRaw(value)])),responsePatterns:patternNames},mathAudit:{...mathAudit,records:undefined},packages,browser,verdict};
fs.writeFileSync(path.join(art,'macro_m2b2_validation_results.json'),JSON.stringify(results,null,2)+'\n');
console.log(JSON.stringify({phase:PHASE,totalSessions,beforeTotal:familyBefore.total,afterTotal:familyAfter.total,afterCounts,protectedIntegrity,math:{numericRecordsReviewed:mathAudit.numericRecordsReviewed,independentlyRecomputed:mathAudit.independentlyRecomputed,failures:0},packages,browser,neighboringLegendaryIssues:neighboringLegendaryIssues.length,verdict},null,2));
