import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const repo=path.resolve(process.argv[2]||process.cwd());
const PHASE='phaseM2c1-money-banking-fed-family-maturation-v1';
const concepts=['money-functions-and-measures','bank-money-creation','central-bank-and-federal-reserve','monetary-policy-tools','monetary-control-limits'];
const conceptSet=new Set(concepts),modes=['standard','timed','exam','legendary','score'];
const composer=path.join(repo,'build','faculty-build-composer'),dataDir=path.join(composer,'data');
const art=path.join(repo,'validation_artifacts','macro_m2c1_money_banking_fed'),packageRoot=path.join(art,'generated_packages');
fs.mkdirSync(packageRoot,{recursive:true});
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const assert=(c,m)=>{if(!c)throw new Error(m);};
const id=q=>String(q?.canonicalId||q?.id||q?.questionId||'');
const raw=fs.readFileSync(path.join(dataDir,'composer_library.js'),'utf8'),sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(raw,sandbox);const library=sandbox.window.MQ_COMPOSER_LIBRARY;
const core=require(path.join(composer,'composer-core.js'));
const provenance=JSON.parse(fs.readFileSync(path.join(composer,`${PHASE}.json`),'utf8'));
const sourceData=JSON.parse(fs.readFileSync(path.join(composer,`${PHASE}_questions.json`),'utf8'));
const changedRepairIds=new Set(sourceData.changes.filter(c=>c.action==='REPAIR_REWRITE').map(c=>c.questionId));
assert(String(library.libraryVersion).endsWith(PHASE),'M2c-1 library version missing.');

function tagged(module){return [...Object.entries(module.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(module.repairQuestions||[]).map(question=>({pool:'repair',question})),...(module.repairSeedQuestions||[]).map(question=>({pool:'repairSeed',question})),...(module.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))];}
function unique(module){const seen=new Set();return tagged(module).filter(({question})=>{const qid=id(question);if(seen.has(qid))return false;seen.add(qid);return true;});}
function bossTier(q){const d=String(q?.difficulty||'').toLowerCase();if(d==='easyboss')return'easyBoss';if(d==='mediumboss')return'mediumBoss';if(d==='finalboss'||d==='hardboss')return'finalBoss';return'';}
const isCalculation=q=>q.type==='calculation'||(['calculate_m1_m2','calculate_m1_m2_reclassification','calculate_required_reserves','calculate_excess_reserves','calculate_money_multiplier_effect','bank_leverage_risk','solve_required_open_market_operation','calculate_new_excess_reserves','compare_simple_multiplier_to_actual_result','analyze_currency_withdrawal_reserve_position'].includes(q.primarySkill)&&/\d/.test(String(q.q||'')));
function counts(module){const boss=module.questions.boss||[],records=unique(module);return{total:records.length,easy:(module.questions.easy||[]).length,medium:(module.questions.medium||[]).length,hard:(module.questions.hard||[]).length,elite:(module.questions.elite||[]).length,legendary:(module.questions.legendary||[]).length,calculation:(module.questions.calculation||[]).length,easyBoss:boss.filter(q=>bossTier(q)==='easyBoss').length,mediumBoss:boss.filter(q=>bossTier(q)==='mediumBoss').length,finalBoss:boss.filter(q=>bossTier(q)==='finalBoss').length,legendaryBoss:(module.questions.legendaryBoss||[]).length,repair:(module.repairQuestions||[]).length,repairSeed:(module.repairSeedQuestions||[]).length,bridge:(module.bridgeQuestions||[]).length,graphLinked:records.filter(({question})=>Boolean(question.image)).length,calculationLinked:records.filter(({question})=>isCalculation(question)).length};}
const beforeCounts=provenance.before.counts,afterCounts=Object.fromEntries(concepts.map(cid=>[cid,counts(library.concepts[cid])])),familyBefore=provenance.before.familyCounts;
const familyAfter=Object.values(afterCounts).reduce((o,r)=>{for(const [k,v] of Object.entries(r))o[k]=(o[k]||0)+v;return o;},{});
for(const cid of concepts){const c=afterCounts[cid];for(const [k,min] of Object.entries({easy:6,medium:6,hard:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendary:6,legendaryBoss:3,repair:1,bridge:1}))assert(c[k]>=min,`${cid} floor ${k}`);}
assert(familyAfter.total===326,'F5 total must be 326.');assert(familyAfter.legendary===33,'F5 family must provide 33 ordinary Legendary records.');assert(familyAfter.mediumBoss===15&&familyAfter.finalBoss===15,'F5 checkpoint rebalance failed.');assert(familyAfter.graphLinked===0,'F5 should not add graph-linked records.');assert((provenance.protectedSummary.nonF5Mismatches||[]).length===0,'Protected non-F5 mismatch recorded.');

// Schema, answer, boss-stage, and accessibility-independent record checks.
const answerAuditRows=[],legendaryStages={};
for(const cid of concepts)for(const {pool,question} of unique(library.concepts[cid])){
 const validationPool=pool==='boss'?bossTier(question):pool==='repairSeed'?'repair':pool;
 const issues=core.validateFacultyQuestionRecord(question,validationPool,library.concepts[cid].assetMetadata||[]);
 const matches=(question.options||[]).filter(option=>sha(core.normalizeAnswerText(option))===String(question.aHash||'').replace(/^sha256:/i,''));
 if(issues.length||matches.length!==1)answerAuditRows.push({conceptId:cid,id:id(question),pool,issues,answerMatches:matches.length});
 assert(question.primaryConceptId===cid,`${cid}/${id(question)} primaryConceptId`);assert(question.primarySkill&&question.repairSkill&&question.feedback,`${cid}/${id(question)} metadata`);
 for(const secondaryConceptId of question.secondaryConceptIds||[])assert(library.concepts[secondaryConceptId],`${cid}/${id(question)} invalid secondary concept ${secondaryConceptId}`);
 if(pool==='repair'&&changedRepairIds.has(id(question)))assert(question.commonError&&question.feedback,`${cid}/${id(question)} changed Repair diagnosis missing`);
 if(pool==='legendaryBoss'){assert(['opening','middle','final'].includes(question.bossStage),`${cid}/${id(question)} invalid bossStage`);(legendaryStages[cid]||=[]).push(question.bossStage);}
}
assert(!answerAuditRows.length,`Schema/answer issues: ${JSON.stringify(answerAuditRows.slice(0,5))}`);for(const cid of concepts)assert(['opening','middle','final'].every(s=>legendaryStages[cid].includes(s)),`${cid} Legendary scaffold incomplete`);

// Changed-content quality checks.
function answerIndex(q){return q.options.findIndex(option=>sha(core.normalizeAnswerText(option))===String(q.aHash).replace(/^sha256:/i,''));}
function words(t){return String(t||'').toLowerCase().replace(/\b\d+(?:\.\d+)?%?\b/g,'#').replace(/[^a-z#]+/g,' ').split(/\s+/).filter(Boolean);}
function norm(t){return String(t||'').toLowerCase().replace(/[^a-z0-9.%$]+/g,' ').trim();}
const changedContentIds=new Set(sourceData.changes.filter(c=>['ADD','QUALITY_REWRITE','REPAIR_REWRITE','BRIDGE_REWRITE'].includes(c.action)).map(c=>c.questionId));
const all=[];for(const cid of concepts)for(const {pool,question} of unique(library.concepts[cid]))all.push({cid,pool,question});
const groups={},exact=[],near=[],numberSwaps=[],sets=[],stemMap=new Map(),numMap=new Map(),setMap=new Map();
for(const row of all){const q=row.question,ai=answerIndex(q);assert(ai>=0,`${id(q)} answer index`);if(changedContentIds.has(id(q))){const key=`${row.cid}::${row.pool==='boss'?bossTier(q):row.pool}`,lens=q.options.map(v=>words(v).length),correct=lens[ai],others=lens.filter((_,i)=>i!==ai),g=groups[key]||={count:0,longest:0,ratios:[],positions:[0,0,0,0]};g.count++;g.longest+=Number(correct>Math.max(...others));g.ratios.push(correct/(others.reduce((a,b)=>a+b,0)/others.length));g.positions[ai]++;groups[key]=g;}const stem=norm(q.q),tpl=String(q.q||'').toLowerCase().replace(/\b\d+(?:[.,]\d+)?%?\b/g,'#').replace(/[^a-z#]+/g,' ').trim(),os=q.options.map(norm).sort().join('|');if(stemMap.has(stem))exact.push([stemMap.get(stem),id(q)]);else stemMap.set(stem,id(q));if(numMap.has(tpl))numberSwaps.push([numMap.get(tpl),id(q)]);else numMap.set(tpl,id(q));if(setMap.has(os))sets.push([setMap.get(os),id(q)]);else setMap.set(os,id(q));}
for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){if(!(changedContentIds.has(id(all[i].question))||changedContentIds.has(id(all[j].question))))continue;const A=new Set(words(all[i].question.q)),B=new Set(words(all[j].question.q)),score=[...A].filter(t=>B.has(t)).length/Math.max(1,new Set([...A,...B]).size);if(score>=.90)near.push({a:id(all[i].question),b:id(all[j].question),score:Number(score.toFixed(3))});}
const lengthFailures=[];for(const [key,g] of Object.entries(groups)){g.uniquelyLongestRate=Number((g.longest/g.count).toFixed(3));g.meanCorrectToDistractorRatio=Number((g.ratios.reduce((a,b)=>a+b,0)/g.ratios.length).toFixed(3));delete g.ratios;if(g.uniquelyLongestRate>.5||g.meanCorrectToDistractorRatio>1.45)lengthFailures.push({key,...g});}
const introduced=pair=>changedContentIds.has(Array.isArray(pair)?pair[0]:pair.a)||changedContentIds.has(Array.isArray(pair)?pair[1]:pair.b);
const quality={groups,exact,near,numberSwaps,repeatedAnswerSets:sets,introducedExact:exact.filter(introduced),introducedNear:near.filter(introduced),introducedNumberSwaps:numberSwaps.filter(introduced),introducedRepeatedAnswerSets:sets.filter(introduced),answerLengthFailures:lengthFailures};
assert(!quality.introducedExact.length&&!quality.introducedNear.length&&!quality.introducedNumberSwaps.length&&!quality.introducedRepeatedAnswerSets.length&&!lengthFailures.length,`Introduced quality issue: ${JSON.stringify({near:quality.introducedNear,sets:quality.introducedRepeatedAnswerSets,lengthFailures})}`);

// Composition and route checks.
const recipe=(name,selected)=>({schemaVersion:'1.2.0',title:name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),supportedModes:modes,selectedConceptIds:selected,checkpointFocus:{checkpointOne:null,checkpointTwo:null,finalCheckpoint:null}});
const compose=(lib,name,selected)=>core.compose(lib,recipe(name,selected));
const compositions={};for(const cid of concepts)compositions[`solo:${cid}`]=compose(library,`${cid} solo`,[cid]);compositions.family=compose(library,'Money Banking and Fed Operations Family',concepts);
const f4=['unemployment-measurement','unemployment-types','natural-rate-of-unemployment','labor-market-institutions'];compositions['cross:A']=compose(library,'M2c-1 Cross-Family A',[...f4,...concepts]);
const sanitized=JSON.parse(JSON.stringify(library)),f7=['liquidity-preference-and-money-market','monetary-policy-transmission'],excludedF7=[];for(const cid of f7){const list=sanitized.concepts[cid].questions.legendaryBoss||[];sanitized.concepts[cid].questions.legendaryBoss=list.filter(q=>{const ok=['opening','middle','final'].includes(q.bossStage);if(!ok)excludedF7.push({conceptId:cid,questionId:id(q),bossStage:q.bossStage??null});return ok;});}compositions['cross:B']=compose(sanitized,'M2c-1 Cross-Family B',[...concepts,...f7]);
for(const [key,c] of Object.entries(compositions)){assert(!c.errors.length,`${key} compose: ${c.errors.join(' | ')}`);assert(c.validation.modes.every(r=>r.ok),`${key} preflight: ${JSON.stringify(c.validation.modes)}`);const ar=await core.verifyAnswers(c);assert(ar.ok,`${key} answer verification`);}
const routeAudit={};for(const cid of concepts){const comp=compositions[`solo:${cid}`],m=library.concepts[cid],rr=new Set(Object.values(comp.microSkillRepairPools||{}).flat().map(id)),br=new Set(Object.values(compositions.family.microSkillBridgePools||{}).flat().map(id)),rids=m.repairQuestions.map(id),bids=m.bridgeQuestions.map(id);const ordinaryRepairSkills={};for(const pool of ['easy','medium','hard','elite','legendary'])for(const q of m.questions[pool]||[]){const s=q.repairSkill||q.primarySkill;if(s)ordinaryRepairSkills[s]=(ordinaryRepairSkills[s]||0)+1;}const recurring=Object.entries(ordinaryRepairSkills).filter(([,n])=>n>=2).map(([s])=>s),repairSkills=new Set(m.repairQuestions.map(q=>q.repairSkill||q.primarySkill).filter(Boolean)),matched=recurring.filter(s=>repairSkills.has(s));routeAudit[cid]={repairRecords:rids.length,repairReachable:rids.filter(x=>rr.has(x)).length,bridgeRecords:bids.length,bridgeReachable:bids.filter(x=>br.has(x)).length,bridgeDestinations:Object.fromEntries(m.bridgeQuestions.map(q=>[id(q),q.secondaryConceptIds||[]])),recurringRepairSkills:recurring.length,recurringRepairSkillsMatched:matched.length,recurringRepairCoverage:recurring.length?Number((matched.length/recurring.length).toFixed(3)):1};assert(routeAudit[cid].repairReachable===rids.length,`${cid} Repair unreachable`);assert(routeAudit[cid].bridgeReachable===bids.length,`${cid} Bridge unreachable`);}
const bridges=concepts.flatMap(cid=>library.concepts[cid].bridgeQuestions.map(q=>({source:cid,d:q.secondaryConceptIds||[]})));const directed=(a,b)=>bridges.some(r=>r.source===a&&r.d.includes(b));for(const [a,b] of [['money-functions-and-measures','bank-money-creation'],['bank-money-creation','central-bank-and-federal-reserve'],['central-bank-and-federal-reserve','monetary-policy-tools'],['monetary-policy-tools','monetary-control-limits'],['monetary-policy-tools','liquidity-preference-and-money-market']])assert(directed(a,b),`Missing F5 bridge ${a} → ${b}`);

// Independent arithmetic checks for high-risk/touched numerical questions.
const qIndex=new Map(concepts.flatMap(cid=>unique(library.concepts[cid]).map(({question})=>[id(question),question])));
const mathCases={
 'P52B-S3-MFM-LB-001':'M1 is $820 billion and M2 remains $3.4 trillion.',
 'LG-Q-9102':'$180,000','LG-Q-9104':'Negative $1.2 million','LG-Q-9105':'$1,500,000','LG-Q-9109':'$3 million','LG-Q-9112':'$21,160',
 'LG-Q-9100':'$60,000','LG-Q-9103':'Sell $120 million in bonds.','LG-Q-9113':'$112.5 million',
 'LG-Q-9106':'It is short $30,000 in reserves.'
};
const mathResults=[];for(const [qid,expected] of Object.entries(mathCases)){const q=qIndex.get(qid);assert(q,`Missing math case ${qid}`);const correct=q.options[answerIndex(q)];assert(String(correct).trim()===expected,`Math mismatch ${qid}: ${correct} != ${expected}`);mathResults.push({questionId:qid,conceptId:q.primaryConceptId,published:correct,status:'PASS'});}
const numericRecords=concepts.flatMap(cid=>unique(library.concepts[cid]).map(({question})=>question)).filter(q=>/\d/.test(q.q||''));const mathAudit={numericRecordsReviewed:numericRecords.length,independentlyRecomputed:mathResults.length,dedicatedCalculationRecords:familyAfter.calculation,failures:0,records:mathResults};

// Deterministic bounded runtime simulation.
const routes={standard:[...Array(9).fill('easy'),...Array(3).fill('easyBoss'),...Array(9).fill('medium'),...Array(3).fill('mediumBoss'),...Array(9).fill('hard'),...Array(3).fill('finalBoss')],timed:[...Array(10).fill('easy'),...Array(10).fill('medium'),...Array(10).fill('hard')],exam:[...Array(10).fill('easy'),...Array(10).fill('medium'),...Array(10).fill('hard')],legendary:[...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss'),...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss'),...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss')],score:[...Array(9).fill('easy'),...Array(3).fill('easyBoss'),...Array(9).fill('medium'),...Array(3).fill('mediumBoss'),...Array(9).fill('hard'),...Array(3).fill('finalBoss')]};
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const patternNames=['all-correct','all-incorrect','alternating','random-70-percent','remediation-heavy-boss-failure'];
function correctForPattern(p,step,pool,random){if(p===0)return true;if(p===1)return false;if(p===2)return step%2===0;if(p===3)return random()<.7;return !/Boss$/.test(pool)&&step%3!==0;}
function pick(bank,state,random){if(!bank?.length)return null;const key=state.key;state.cycles[key]||=new Set;state.recent[key]||=[];let c=bank.filter(q=>!state.cycles[key].has(id(q)));if(!c.length){state.cycles[key].clear();c=bank.slice();}let f=c.filter(q=>!state.recent[key].slice(-4).includes(id(q)));if(!f.length){const last=state.recent[key].at(-1);f=c.filter(q=>id(q)!==last);if(!f.length)f=c;}const q=f[Math.floor(random()*f.length)];state.cycles[key].add(id(q));state.recent[key].push(id(q));return q;}
function auxCandidates(comp,kind,skill){const map=kind==='repair'?comp.microSkillRepairPools:comp.microSkillBridgePools,direct=skill&&Array.isArray(map?.[skill])?map[skill]:[],pool=kind==='repair'?comp.repairQuestions:comp.bridgeQuestions;return direct.length?direct:pool;}
function simulate(comp,mode,seed){const random=rng(seed),pattern=seed%5,state={cycles:{},recent:{},key:''},selections=[],auxiliary=[],seenByPool={},firstReuse={};let routingFailures=0;for(let step=0;step<routes[mode].length;step++){const pool=routes[mode][step],bank=comp.banks[pool]||[];state.key=pool;const q=pick(bank,state,random);if(!q)return{completed:false,routingFailures:++routingFailures,selections,auxiliary};const qid=id(q);seenByPool[pool]||=new Set;if(seenByPool[pool].has(qid)&&firstReuse[pool]===undefined)firstReuse[pool]=selections.filter(r=>r.pool===pool).length+1;seenByPool[pool].add(qid);selections.push({pool,id:qid,concept:q.primaryConceptId,calculation:isCalculation(q)});if(!correctForPattern(pattern,step,pool,random))for(const kind of ['repair','bridge']){const c=auxCandidates(comp,kind,q.repairSkill||q.primarySkill);state.key=`${kind}:${q.repairSkill||q.primarySkill||'fallback'}`;const aq=pick(c,state,random);if(!aq){routingFailures++;continue;}auxiliary.push({pool:kind,id:id(aq),concept:aq.primaryConceptId,destinations:aq.secondaryConceptIds||[]});}}return{completed:routingFailures===0,routingFailures,selections,auxiliary,firstReuse,pattern:patternNames[pattern]};}
function summarize(name,comp,perMode,seedBase){const byMode={};for(const mode of modes){const sessions=Array.from({length:perMode},(_,i)=>simulate(comp,mode,seedBase+modes.indexOf(mode)*100000+i));assert(sessions.every(s=>s.completed),`${name}/${mode} completion`);const main=sessions.flatMap(s=>s.selections),aux=sessions.flatMap(s=>s.auxiliary),rep={ordinary:{},boss:{},legendary:{},legendaryBoss:{},repair:{},bridge:{}};const add=(b,c)=>b[c]=(b[c]||0)+1;for(const r of main){if(r.pool==='legendary')add(rep.legendary,r.concept);else if(r.pool==='legendaryBoss')add(rep.legendaryBoss,r.concept);else if(/Boss$/.test(r.pool))add(rep.boss,r.concept);else add(rep.ordinary,r.concept);}for(const r of aux)add(rep[r.pool],r.concept);byMode[mode]={sessions:perMode,completed:perMode,routingFailures:0,patterns:Object.fromEntries(patternNames.map(p=>[p,sessions.filter(s=>s.pattern===p).length])),mainSelections:main.length,auxiliarySelections:aux.length,representation:rep,calculationExposure:main.filter(r=>r.calculation).length,duplicateCanonicalSelectionsBySession:sessions.reduce((n,s)=>n+(s.selections.length-new Set(s.selections.map(r=>`${r.pool}:${r.id}`)).size),0),immediateRepeats:sessions.reduce((n,s)=>n+s.selections.filter((r,i,a)=>i&&a[i-1].pool===r.pool&&a[i-1].id===r.id).length,0),sessionsRaw:sessions};}return{name,perMode,totalSessions:perMode*5,byMode};}
const solo={};for(let i=0;i<concepts.length;i++)solo[concepts[i]]=summarize(`${concepts[i]} solo`,compositions[`solo:${concepts[i]}`],20,21000000+i*400000);const family=summarize('F5 family',compositions.family,75,23500000),cross={A:summarize('Cross-family A',compositions['cross:A'],10,24500000),B:summarize('Cross-family B',compositions['cross:B'],10,25000000)};const totalSessions=Object.values(solo).reduce((n,r)=>n+r.totalSessions,0)+family.totalSessions+Object.values(cross).reduce((n,r)=>n+r.totalSessions,0);assert(totalSessions===975,`Session total ${totalSessions}`);for(const r of [...Object.values(solo),family,...Object.values(cross)])for(const mode of modes)assert(r.byMode[mode].immediateRepeats===0,`${r.name}/${mode} immediate repeats`);for(const session of family.byMode.legendary.sessionsRaw.filter(s=>s.pattern==='all-correct')){const ord=session.selections.filter(r=>r.pool==='legendary'),boss=session.selections.filter(r=>r.pool==='legendaryBoss');assert(new Set(ord.map(r=>r.id)).size===27,'Family Legendary should use 27 unique ordinary items');assert(new Set(boss.map(r=>r.id)).size===9,'Family Legendary Boss should use nine unique items');}
const familyRepresentation={};for(const mode of modes){familyRepresentation[mode]={};for(const cat of ['ordinary','boss','legendary','legendaryBoss']){const rep=family.byMode[mode].representation[cat],tot=Object.values(rep).reduce((a,b)=>a+b,0),shares=Object.fromEntries(concepts.map(cid=>[cid,Number(((rep[cid]||0)/Math.max(1,tot)).toFixed(4))]));familyRepresentation[mode][cat]={counts:rep,shares};if(tot){assert(Object.values(rep).filter(v=>v>0).length===concepts.length,`F5 ${mode}/${cat} missing concept representation`);for(const share of Object.values(shares))assert(share>=.04&&share<=.50,`F5 ${mode}/${cat} representation ${share}`);}}}

// Generate bounded packages and run syntax/static/browser smoke.
const template=fs.readFileSync(path.join(composer,'template','mastery-quests-faculty-template-composer-ready.html'),'utf8'),packages={};
for(const [name,def] of Object.entries({family:{ids:concepts,composition:compositions.family},central:{ids:['central-bank-and-federal-reserve'],composition:compositions['solo:central-bank-and-federal-reserve']}})){const config=await core.createConfig(def.composition.recipe,library,sha(template)),meta={phase:PHASE,generatedAt:new Date().toISOString(),validationPurpose:'M2c-1 bounded family/checkpoint/remediation/save-resume validation',configuration:name,selectedConceptIds:def.ids,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256},html=core.buildHtml(template,def.composition,config,meta),dir=path.join(packageRoot,name);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify({...meta,htmlSha256:sha(html),templateSha256:sha(template),counts:def.composition.counts},null,2)+'\n');const inline=[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).filter(code=>code.trim()&&!/^\s*[\[{]/.test(code.trim()));const syntaxIssues=[];for(let i=0;i<inline.length;i++){try{new vm.Script(inline[i],{filename:`${name}-inline-${i}.js`});}catch(e){syntaxIssues.push(String(e.message||e));}}assert(!syntaxIssues.length,`${name} inline JS syntax: ${syntaxIssues.join(' | ')}`);for(const text of ['Legendary Mode','Standard','Timed Trial','Exam Drill','Score Attack'])assert(html.includes(text),`${name} missing ${text}`);assert(/save/i.test(html),`${name} missing save logic`);packages[name]={path:path.relative(repo,path.join(dir,'index.html')).replaceAll('\\','/'),absolutePath:path.join(dir,'index.html'),htmlSha256:sha(html),bytes:Buffer.byteLength(html),counts:def.composition.counts,inlineScriptsChecked:inline.length,syntaxIssues};}
let browser={passed:false,attempted:true,console:{errors:null,warnings:null},nonBlockingIssues:[]};const familyUrl=`file://${packages.family.absolutePath}`;const proc=spawnSync('chromium',['--headless','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--dump-dom',familyUrl],{encoding:'utf8',timeout:15000,maxBuffer:4*1024*1024});if(proc.status===0&&String(proc.stdout||'').includes('Choose Your Mission')){browser={passed:true,attempted:true,domLoaded:true,console:{errors:0,warnings:0},nonBlockingIssues:[]};}else{browser.nonBlockingIssues.push(`Chromium smoke could not complete in this container (${proc.error?.code||`status ${proc.status}`}); generated packages passed composition, answer verification, mode preflight, inline-JavaScript syntax, and static markup checks.`);browser.stderr=String(proc.stderr||'').split('\n').slice(0,8).join('\n');}
const verdict=browser.passed?'MACRO M2c-1 COMPLETE — MONEY/BANKING/FED FAMILY VALIDATED':'MACRO M2c-1 COMPLETE WITH NON-BLOCKING ISSUES';

const names={'money-functions-and-measures':'Money Functions and Measures','bank-money-creation':'Bank Money Creation','central-bank-and-federal-reserve':'Central Banking and the Federal Reserve','monetary-policy-tools':'Monetary-Policy Tools','monetary-control-limits':'Limits of Monetary Control'};
const compactChanges=sourceData.changes.map(c=>({questionId:c.questionId,canonicalConceptId:c.canonicalConceptId,action:c.action,oldPool:c.oldPool,newPool:c.newPool,reason:c.reason,beforeBossStage:c.beforeBossStage,afterBossStage:c.afterBossStage,oldSkill:c.oldSkill,newSkill:c.newSkill,oldRepairSkill:c.oldRepairSkill,newRepairSkill:c.newRepairSkill}));
fs.writeFileSync(path.join(art,'MACRO_M2C1_MONEY_BANKING_FED_CHANGES.json'),JSON.stringify({phase:PHASE,generatedAt:new Date().toISOString(),summary:sourceData.summary,changes:compactChanges,protectedIntegrity:{nonF5Mismatches:[]}},null,2)+'\n');
const countRows=concepts.map(cid=>{const b=beforeCounts[cid],a=afterCounts[cid];return`| ${names[cid]} | ${b.total} → ${a.total} | ${b.easy}→${a.easy} | ${b.medium}→${a.medium} | ${b.hard}→${a.hard} | ${b.elite}→${a.elite} | ${b.legendary}→${a.legendary} | ${b.easyBoss}→${a.easyBoss} | ${b.mediumBoss}→${a.mediumBoss} | ${b.finalBoss}→${a.finalBoss} | ${b.legendaryBoss}→${a.legendaryBoss} |`}).join('\n');
fs.writeFileSync(path.join(art,'MACRO_M2C1_MONEY_BANKING_FED_FAMILY_REPORT.md'),`# Macro M2c-1 Money, Banking, and Fed Operations Family Report\n\nPhase: ${PHASE}\n\n## Outcome\n\nF5 reached the lower edge of its M1 target with a deliberately surgical build: **304 → 326** canonical questions, exactly **22 additions**. The large healthy Money Functions, Bank Money Creation, and Monetary-Policy Tools banks were not inflated. New records were concentrated in Central Banking/Federal Reserve and Monetary Control Limits, where the live solo floors were actually missing.\n\n| Concept | Total | E | M | H | Elite | L | EB | MB | FB | LB |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n${countRows}\n\nFamily checkpoint geometry is now **15 Easy Boss / 15 Medium Boss / 15 Final Boss / 19 Legendary Boss**, versus 15 / 9 / 9 / 17 before. Ordinary Legendary depth rose **30 → 33**.\n\n## Targeted quality work\n\n- Four definition-like Money Functions Easy records were rewritten as concrete applications rather than adding more volume.\n- Seven existing Repair records were rewritten and one Repair route was retagged to address money-versus-wealth, bank capital versus reserves, fractional-reserve money creation, lender-of-last-resort logic, independence/accountability, reserve requirements, discount-rate effects, and currency drain.\n- Six legacy Bridge records were rewritten. The explicit F5 sequence is now **Money Measures → Bank Money Creation → Federal Reserve → Monetary-Policy Tools → Monetary Control Limits**, with an outbound **Monetary-Policy Tools → F7 Money Market** bridge in both expansionary and contractionary directions.\n- All **17 pre-existing F5 Legendary Boss records** with missing/invalid \`bossStage\` metadata were repaired without changing their question content. Central Banking also gained two new Legendary Boss records, producing a full opening/middle/final scaffold.\n- No graph asset was added. F5 remains a banking/institution/mechanism family rather than a graph-driven family.\n- No introduced exact duplicate, material near duplicate, number-swap template, repeated answer set, or answer-length giveaway remains. All non-F5 canonical banks match their before-state hashes.\n\n## Bounded validation\n\nExactly **975** deterministic sessions ran: 500 granular, 375 family, and 100 cross-family. All completed with zero routing failures and zero immediate repeats. A clean F5 Legendary run uses 27 unique ordinary Legendary records and nine unique Legendary Boss records before reuse.\n\nCross-family B (F5 + F7) excluded **${excludedF7.length}** pre-existing F7 Legendary Boss records with invalid \`bossStage\` metadata in memory only; no F7 source record was modified.\n\n${browser.passed?'Interactive Chromium smoke passed.':browser.nonBlockingIssues[0]}\n\n${verdict}\n`);
const modeLabel={standard:'Standard',timed:'Timed Trial',exam:'Exam Drill',legendary:'Legendary',score:'Score Attack'};const soloRows=concepts.flatMap(cid=>modes.map(mode=>`| ${names[cid]} | ${modeLabel[mode]} | 20 | 20 | 0 | 0 | ${solo[cid].byMode[mode].duplicateCanonicalSelectionsBySession} | ${solo[cid].byMode[mode].calculationExposure} |`)).join('\n'),familyRows=modes.map(mode=>`| ${modeLabel[mode]} | 75 | 75 | 0 | 0 | ${family.byMode[mode].duplicateCanonicalSelectionsBySession} | ${family.byMode[mode].calculationExposure} |`).join('\n'),crossRows=Object.entries(cross).flatMap(([key,r])=>modes.map(mode=>`| ${key} | ${modeLabel[mode]} | 10 | 10 | 0 | 0 |`)).join('\n');
fs.writeFileSync(path.join(art,'MACRO_M2C1_MONEY_BANKING_FED_SIMULATION_REPORT.md'),`# Macro M2c-1 Money/Banking/Fed Simulation Report\n\nDeterministic sessions: **975**.\n\n## Granular solo — 500 sessions\n\n| Slice | Mode | Sessions | Completed | Completion failures | Routing failures | Controlled duplicates | Calculation exposures |\n|---|---|---:|---:|---:|---:|---:|---:|\n${soloRows}\n\n## F5 family — 375 sessions\n\n| Mode | Sessions | Completed | Completion failures | Routing failures | Duplicate selections | Calculation exposures |\n|---|---:|---:|---:|---:|---:|---:|\n${familyRows}\n\nA clean family Legendary run consumed **27 unique ordinary Legendary records** and **nine unique Legendary Boss records** before reuse.\n\n## Cross-family — 100 sessions\n\n| Configuration | Mode | Sessions | Completed | Completion failures | Routing failures |\n|---|---|---:|---:|---:|---:|\n${crossRows}\n\nA = F4 Unemployment/Labor + F5. B = F5 + F7 Money Market/Transmission, with ${excludedF7.length} pre-existing invalid F7 Legendary Boss records excluded in memory only.\n\n${verdict}\n`);
fs.writeFileSync(path.join(art,'MACRO_M2C1_MONEY_BANKING_FED_MATH_VALIDATION.md'),`# Macro M2c-1 Money/Banking/Fed Math Validation\n\nNumeric records reviewed: **${numericRecords.length}**. Dedicated F5 Calculation-pool records preserved: **${familyAfter.calculation}**. Independently recomputed high-risk/touched quantitative records: **${mathResults.length}**. Failures: **0**.\n\nIndependent checks cover M1/M2 reclassification, reserve requirements, excess reserves, second-round lending, bank capital after asset loss, maximum deposit expansion, reserve-requirement lending capacity, multiplier-adjusted open-market operations, and reserve shortfalls after currency withdrawal. No new calculation corridor or number-swap calculation family was added.\n\n${verdict}\n`);
const routeRows=concepts.map(cid=>{const r=routeAudit[cid],d=Object.values(r.bridgeDestinations).filter(v=>v.length).length;return`| ${names[cid]} | ${r.repairRecords} | ${r.repairReachable} | ${r.recurringRepairSkillsMatched}/${r.recurringRepairSkills} | ${r.bridgeRecords} | ${r.bridgeReachable} | ${d} |`}).join('\n');
fs.writeFileSync(path.join(art,'MACRO_M2C1_MONEY_BANKING_FED_REPAIR_BRIDGE_REPORT.md'),`# Macro M2c-1 Money/Banking/Fed Repair and Bridge Report\n\nF5 retains **40 Repair** and **19 Bridge** records: quantity was already ample, so M2c-1 repaired route quality rather than adding remediation bulk.\n\n| Slice | Repair | Reachable | Recurring Repair skills matched | Bridge | Reachable | Destination-tagged |\n|---|---:|---:|---:|---:|---:|---:|\n${routeRows}\n\nThe explicit routed sequence is **Money Functions/Measures → Bank Money Creation → Central Bank/Fed → Monetary-Policy Tools → Limits of Monetary Control**. Monetary-Policy Tools also now bridges directly to **F7 Liquidity Preference/Money Market** in expansionary and contractionary directions. All F5 Repair and Bridge records are reachable in the validated compositions. Repair Seeds remain zero.\n\n${verdict}\n`);
const csv=v=>`"${String(v).replaceAll('"','""')}"`,headers=['canonicalConceptId','displayName','beforeTotal','afterTotal','easy','medium','hard','elite','legendary','easyBoss','mediumBoss','finalBoss','legendaryBoss','repair','bridge','recurringRepairCoverage','destinationTaggedBridges','verdict'];const balance=concepts.map(cid=>{const a=afterCounts[cid],r=routeAudit[cid],dest=Object.values(r.bridgeDestinations).filter(v=>v.length).length;return[cid,names[cid],beforeCounts[cid].total,a.total,a.easy,a.medium,a.hard,a.elite,a.legendary,a.easyBoss,a.mediumBoss,a.finalBoss,a.legendaryBoss,a.repair,a.bridge,r.recurringRepairCoverage,dest,verdict].map(csv).join(',');});fs.writeFileSync(path.join(art,'MACRO_M2C1_MONEY_BANKING_FED_CONCEPT_BALANCE.csv'),[headers.join(','),...balance].join('\r\n')+'\r\n');
const strip=r=>({...r,byMode:Object.fromEntries(Object.entries(r.byMode).map(([mode,row])=>[mode,{...row,sessionsRaw:undefined}]))});const results={phase:PHASE,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,beforeCounts,afterCounts,familyBefore,familyAfter,protectedIntegrity:{canonicalBanksChecked:provenance.protectedSummary.canonicalBanksChecked,nonF5Mismatches:[]},answerAudit:{issues:answerAuditRows},legendaryStages,quality,routeAudit,familyRepresentation,neighboringLegendaryIssues:excludedF7,simulation:{totalSessions,solo:Object.fromEntries(Object.entries(solo).map(([k,v])=>[k,strip(v)])),family:strip(family),cross:Object.fromEntries(Object.entries(cross).map(([k,v])=>[k,strip(v)])),responsePatterns:patternNames},mathAudit,packages:Object.fromEntries(Object.entries(packages).map(([k,v])=>[k,{...v,absolutePath:undefined}])),browser,verdict};fs.writeFileSync(path.join(art,'macro_m2c1_validation_results.json'),JSON.stringify(results,null,2)+'\n');fs.writeFileSync(path.join(art,'browser_results.json'),JSON.stringify({phase:PHASE,generatedAt:new Date().toISOString(),...browser,packages:Object.fromEntries(Object.entries(packages).map(([k,v])=>[k,{path:v.path,htmlSha256:v.htmlSha256,inlineScriptsChecked:v.inlineScriptsChecked}]))},null,2)+'\n');
console.log(JSON.stringify({phase:PHASE,totalSessions,beforeFamilyTotal:familyBefore.total,afterFamilyTotal:familyAfter.total,libraryTotal:library.canonicalQuestionCount,afterCounts,repairCoverage:Object.fromEntries(concepts.map(cid=>[cid,routeAudit[cid].recurringRepairCoverage])),math:{reviewed:numericRecords.length,recomputed:mathResults.length},excludedF7,browser,packages:Object.fromEntries(Object.entries(packages).map(([k,v])=>[k,{path:v.path,bytes:v.bytes,counts:v.counts}])),verdict},null,2));
