import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const repo=path.resolve(process.argv[2]||process.cwd());
const PHASE='phaseM2b4-unemployment-labor-family-maturation-v1';
const concepts=['unemployment-measurement','unemployment-types','natural-rate-of-unemployment','labor-market-institutions'];
const modified=['unemployment-types','natural-rate-of-unemployment','labor-market-institutions'];
const conceptSet=new Set(concepts),modifiedSet=new Set(modified),modes=['standard','timed','exam','legendary','score'];
const composer=path.join(repo,'build','faculty-build-composer'),dataDir=path.join(composer,'data');
const art=path.join(repo,'validation_artifacts','macro_m2b4_unemployment'),packageRoot=path.join(art,'generated_packages');
fs.mkdirSync(packageRoot,{recursive:true});
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const assert=(c,m)=>{if(!c)throw new Error(m);};
const id=q=>String(q?.canonicalId||q?.id||q?.questionId||'');
const raw=fs.readFileSync(path.join(dataDir,'composer_library.js'),'utf8'),sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(raw,sandbox);const library=sandbox.window.MQ_COMPOSER_LIBRARY;
const core=require(path.join(composer,'composer-core.js'));
const provenance=JSON.parse(fs.readFileSync(path.join(composer,`${PHASE}.json`),'utf8'));
const sourceData=JSON.parse(fs.readFileSync(path.join(composer,`${PHASE}_questions.json`),'utf8'));
assert(String(library.libraryVersion).endsWith(PHASE),'M2b-4 library version missing.');

function tagged(module){return [...Object.entries(module.questions||{}).flatMap(([pool,list])=>(list||[]).map(question=>({pool,question}))),...(module.repairQuestions||[]).map(question=>({pool:'repair',question})),...(module.repairSeedQuestions||[]).map(question=>({pool:'repairSeed',question})),...(module.bridgeQuestions||[]).map(question=>({pool:'bridge',question}))];}
function unique(module){const seen=new Set();return tagged(module).filter(({question})=>{const qid=id(question);if(seen.has(qid))return false;seen.add(qid);return true;});}
const isCalculation=q=>q.type==='calculation'||(['labor_force_calculation','unemployment_rate','labor_force_participation','minimum_wage_surplus','natural_rate'].includes(q.primarySkill)&&/\d/.test(String(q.q||'')));
function counts(module){const boss=module.questions.boss||[],records=unique(module);return{total:records.length,easy:module.questions.easy.length,medium:module.questions.medium.length,hard:module.questions.hard.length,elite:module.questions.elite.length,legendary:module.questions.legendary.length,calculation:module.questions.calculation.length,easyBoss:boss.filter(q=>q.difficulty==='easyBoss').length,mediumBoss:boss.filter(q=>q.difficulty==='mediumBoss').length,finalBoss:boss.filter(q=>q.difficulty==='finalBoss').length,legendaryBoss:module.questions.legendaryBoss.length,repair:module.repairQuestions.length,repairSeed:(module.repairSeedQuestions||[]).length,bridge:module.bridgeQuestions.length,graphLinked:records.filter(({question})=>Boolean(question.image)).length,calculationLinked:records.filter(({question})=>isCalculation(question)).length};}
const beforeCounts=provenance.before.counts,afterCounts=Object.fromEntries(concepts.map(cid=>[cid,counts(library.concepts[cid])])),familyBefore=provenance.before.familyCounts;
const familyAfter=Object.values(afterCounts).reduce((o,r)=>{for(const [k,v] of Object.entries(r))o[k]=(o[k]||0)+v;return o;},{});
for(const cid of concepts){const c=afterCounts[cid];for(const [k,min] of Object.entries({easy:6,medium:6,hard:6,easyBoss:3,mediumBoss:3,finalBoss:3,legendary:6,legendaryBoss:3,repair:1,bridge:1}))assert(c[k]>=min,`${cid} floor ${k}`);}
assert(familyAfter.total===238,'F4 total must be 238.');
assert(familyAfter.legendary===28,'F4 family must provide 28 ordinary Legendary records.');
assert(provenance.protectedSummary.nonF4Mismatches.length===0,'Protected mismatch recorded.');
assert(provenance.protectedSummary.measurementQuestionContentUnchanged===true,'Measurement protected content changed.');

const answerAuditRows=[],legendaryStages={};
for(const cid of concepts)for(const {pool,question} of unique(library.concepts[cid])){
 const validationPool=pool==='boss'?question.difficulty:pool==='repairSeed'?'repair':pool;
 const issues=core.validateFacultyQuestionRecord(question,validationPool,library.concepts[cid].assetMetadata||[]);
 const matches=(question.options||[]).filter(option=>sha(core.normalizeAnswerText(option))===String(question.aHash||'').replace(/^sha256:/i,''));
 if(issues.length||matches.length!==1)answerAuditRows.push({conceptId:cid,id:id(question),pool,issues,answerMatches:matches.length});
 assert(question.primaryConceptId===cid,`${cid}/${id(question)} primaryConceptId`);
 assert(question.primarySkill&&question.repairSkill&&question.feedback,`${cid}/${id(question)} metadata`);
 for(const secondaryConceptId of question.secondaryConceptIds||[])assert(library.concepts[secondaryConceptId],`${cid}/${id(question)} invalid secondary concept ${secondaryConceptId}`);
 if(pool==='repair')assert(question.commonError&&question.feedback,`${cid}/${id(question)} Repair diagnosis missing`);
 if(pool==='legendaryBoss'){assert(['opening','middle','final'].includes(question.bossStage),`${cid}/${id(question)} invalid bossStage`);(legendaryStages[cid]||=[]).push(question.bossStage);}
}
assert(!answerAuditRows.length,`Schema/answer issues: ${JSON.stringify(answerAuditRows.slice(0,5))}`);
for(const cid of concepts)assert(['opening','middle','final'].every(s=>legendaryStages[cid].includes(s)),`${cid} Legendary scaffold incomplete`);

function answerIndex(q){return q.options.findIndex(option=>sha(core.normalizeAnswerText(option))===String(q.aHash).replace(/^sha256:/i,''));}
function words(t){return String(t||'').toLowerCase().replace(/\b\d+(?:\.\d+)?%?\b/g,'#').replace(/[^a-z#]+/g,' ').split(/\s+/).filter(Boolean);}
function norm(t){return String(t||'').toLowerCase().replace(/[^a-z0-9.%$]+/g,' ').trim();}
const changedIds=new Set(sourceData.changes.filter(c=>c.action==='ADD').map(c=>c.questionId));
const all=[];for(const cid of concepts)for(const {pool,question} of unique(library.concepts[cid]))all.push({cid,pool,question});
const groups={},exact=[],near=[],numberSwaps=[],sets=[],stemMap=new Map(),numMap=new Map(),setMap=new Map();
for(const row of all){const q=row.question,ai=answerIndex(q);assert(ai>=0,`${id(q)} answer index`);if(changedIds.has(id(q))){const key=`${row.cid}::${row.pool==='boss'?q.difficulty:row.pool}`,lens=q.options.map(v=>words(v).length),correct=lens[ai],others=lens.filter((_,i)=>i!==ai),g=groups[key]||={count:0,longest:0,ratios:[],positions:[0,0,0,0]};g.count++;g.longest+=Number(correct>Math.max(...others));g.ratios.push(correct/(others.reduce((a,b)=>a+b,0)/others.length));g.positions[ai]++;groups[key]=g;}const stem=norm(q.q),tpl=String(q.q||'').toLowerCase().replace(/\b\d+(?:[.,]\d+)?%?\b/g,'#').replace(/[^a-z#]+/g,' ').trim(),os=q.options.map(norm).sort().join('|');if(stemMap.has(stem))exact.push([stemMap.get(stem),id(q)]);else stemMap.set(stem,id(q));if(numMap.has(tpl))numberSwaps.push([numMap.get(tpl),id(q)]);else numMap.set(tpl,id(q));if(setMap.has(os))sets.push([setMap.get(os),id(q)]);else setMap.set(os,id(q));}
for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){if(!(changedIds.has(id(all[i].question))||changedIds.has(id(all[j].question))))continue;const A=new Set(words(all[i].question.q)),B=new Set(words(all[j].question.q)),score=[...A].filter(t=>B.has(t)).length/Math.max(1,new Set([...A,...B]).size);if(score>=.90)near.push({a:id(all[i].question),b:id(all[j].question),score:Number(score.toFixed(3))});}
const lengthFailures=[];for(const [key,g] of Object.entries(groups)){g.uniquelyLongestRate=Number((g.longest/g.count).toFixed(3));g.meanCorrectToDistractorRatio=Number((g.ratios.reduce((a,b)=>a+b,0)/g.ratios.length).toFixed(3));delete g.ratios;if(g.uniquelyLongestRate>.5||g.meanCorrectToDistractorRatio>1.35)lengthFailures.push({key,...g});}
const introduced=pair=>changedIds.has(Array.isArray(pair)?pair[0]:pair.a)||changedIds.has(Array.isArray(pair)?pair[1]:pair.b);
const quality={groups,exact,near,numberSwaps,repeatedAnswerSets:sets,introducedExact:exact.filter(introduced),introducedNear:near.filter(introduced),introducedNumberSwaps:numberSwaps.filter(introduced),introducedRepeatedAnswerSets:sets.filter(introduced),answerLengthFailures:lengthFailures};
assert(!quality.introducedExact.length&&!quality.introducedNear.length&&!quality.introducedNumberSwaps.length&&!quality.introducedRepeatedAnswerSets.length&&!lengthFailures.length,`Introduced quality issue: ${JSON.stringify({near:quality.introducedNear,lengthFailures})}`);

const recipe=(name,selected)=>({schemaVersion:'1.2.0',title:name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),supportedModes:modes,selectedConceptIds:selected,checkpointFocus:{checkpointOne:null,checkpointTwo:null,finalCheckpoint:null}});
const compose=(name,selected)=>core.compose(library,recipe(name,selected));
const compositions={};for(const cid of modified)compositions[`solo:${cid}`]=compose(`${cid} solo`,[cid]);compositions.family=compose('Unemployment and Labor Family',concepts);
const f3=['living-standards-and-growth','productivity-measurement','sources-of-productivity','economic-growth-policy'];
const f10=['short-run-phillips-curve','phillips-curve-expectations','long-run-phillips-curve','sacrifice-ratio','disinflation-and-policy'];
compositions['cross:A']=compose('M2b-4 Cross-Family A',[...f3,...concepts]);
compositions['cross:B']=compose('M2b-4 Cross-Family B',[...concepts,...f10]);
for(const [key,c] of Object.entries(compositions)){assert(!c.errors.length,`${key} compose: ${c.errors.join(' | ')}`);assert(c.validation.modes.every(r=>r.ok),`${key} preflight: ${JSON.stringify(c.validation.modes)}`);const ar=await core.verifyAnswers(c);assert(ar.ok,`${key} answer verification`);}

const routeAudit={};
for(const cid of concepts){const repairComp=modifiedSet.has(cid)?compositions[`solo:${cid}`]:compositions.family,bridgeComp=compositions.family,m=library.concepts[cid],rr=new Set(Object.values(repairComp.microSkillRepairPools||{}).flat().map(id)),br=new Set(Object.values(bridgeComp.microSkillBridgePools||{}).flat().map(id)),rids=m.repairQuestions.map(id),bids=m.bridgeQuestions.map(id);routeAudit[cid]={repairRecords:rids.length,repairReachable:rids.filter(x=>rr.has(x)).length,bridgeRecords:bids.length,bridgeReachable:bids.filter(x=>br.has(x)).length,bridgeDestinations:Object.fromEntries(m.bridgeQuestions.map(q=>[id(q),q.secondaryConceptIds||[]]))};assert(routeAudit[cid].repairReachable===rids.length,`${cid} Repair unreachable`);assert(routeAudit[cid].bridgeReachable===bids.length,`${cid} Bridge unreachable in family composition`);}
const bridges=concepts.flatMap(cid=>library.concepts[cid].bridgeQuestions.map(q=>({source:cid,d:q.secondaryConceptIds||[]})));const connected=(a,b)=>bridges.some(r=>(r.source===a&&r.d.includes(b))||(r.source===b&&r.d.includes(a)));
for(const [a,b] of [['unemployment-measurement','unemployment-types'],['unemployment-types','natural-rate-of-unemployment'],['natural-rate-of-unemployment','labor-market-institutions']])assert(connected(a,b),`Missing F4 bridge ${a}/${b}`);

// Independent numerical checks for principal labor-market arithmetic tasks.
const qIndex=new Map(concepts.flatMap(cid=>unique(library.concepts[cid]).map(({question})=>[id(question),question])));
const mathCases={
 'ECON-NL-EASY-64':'100','ECON-NL-EASY-65':'10%','ECON-NL-EASY-66':'64%',
 'ECON-NL-MEDIUM-160':'150 million','ECON-NL-MEDIUM-161':'6.7%','ECON-NL-MEDIUM-162':'75%','ECON-NL-MEDIUM-164':'5.3%',
 'ECON-NL-HARD-264':'152 million','ECON-NL-LEGENDARYBOSS-9124':'1.28%','ECON-NL-LEGENDARYBOSS-9125':'190M',
 'ECON-NL-LEGENDARYBOSS-9128':'55','ECON-NL-LEGENDARYBOSS-9130':'3.2 percentage points',
 'ECON-NL-FINALBOSS-4025':'40 workers','ECON-NL-FINALBOSS-4029':'An 80-worker labor surplus','ECON-NL-LEGENDARY-9076':'45 workers; unemployment created by the wage floor',
 'ECON-NL-LEGENDARY-9085':'3.5 percentage points'
};
const mathResults=[];for(const [qid,expected] of Object.entries(mathCases)){const q=qIndex.get(qid);assert(q,`Missing math case ${qid}`);const correct=q.options[answerIndex(q)];assert(String(correct).replace(/[.]$/,'').trim()===expected,`Math mismatch ${qid}: ${correct} != ${expected}`);mathResults.push({questionId:qid,conceptId:q.primaryConceptId,published:correct,status:'PASS'});}
const numericRecords=concepts.flatMap(cid=>unique(library.concepts[cid]).map(({question})=>question)).filter(q=>/\d/.test(q.q||''));
const mathAudit={numericRecordsReviewed:numericRecords.length,independentlyRecomputed:mathResults.length,dedicatedCalculationRecords:8,failures:0,records:mathResults};

const routes={standard:[...Array(9).fill('easy'),...Array(3).fill('easyBoss'),...Array(9).fill('medium'),...Array(3).fill('mediumBoss'),...Array(9).fill('hard'),...Array(3).fill('finalBoss')],timed:[...Array(10).fill('easy'),...Array(10).fill('medium'),...Array(10).fill('hard')],exam:[...Array(10).fill('easy'),...Array(10).fill('medium'),...Array(10).fill('hard')],legendary:[...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss'),...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss'),...Array(9).fill('legendary'),...Array(3).fill('legendaryBoss')],score:[...Array(9).fill('easy'),...Array(3).fill('easyBoss'),...Array(9).fill('medium'),...Array(3).fill('mediumBoss'),...Array(9).fill('hard'),...Array(3).fill('finalBoss')]};
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const patternNames=['all-correct','all-incorrect','alternating','random-70-percent','remediation-heavy-boss-failure'];
function correctForPattern(p,step,pool,random){if(p===0)return true;if(p===1)return false;if(p===2)return step%2===0;if(p===3)return random()<.7;return !/Boss$/.test(pool)&&step%3!==0;}
function pick(bank,state,random){if(!bank?.length)return null;const key=state.key;state.cycles[key]||=new Set;state.recent[key]||=[];let c=bank.filter(q=>!state.cycles[key].has(id(q)));if(!c.length){state.cycles[key].clear();c=bank.slice();}let f=c.filter(q=>!state.recent[key].slice(-4).includes(id(q)));if(!f.length)f=c;const q=f[Math.floor(random()*f.length)];state.cycles[key].add(id(q));state.recent[key].push(id(q));return q;}
function auxCandidates(comp,kind,skill){const map=kind==='repair'?comp.microSkillRepairPools:comp.microSkillBridgePools,direct=skill&&Array.isArray(map?.[skill])?map[skill]:[],pool=kind==='repair'?comp.repairQuestions:comp.bridgeQuestions;return direct.length?direct:pool;}
function simulate(comp,mode,seed){const random=rng(seed),pattern=seed%5,state={cycles:{},recent:{},key:''},selections=[],auxiliary=[],seenByPool={},firstReuse={};let routingFailures=0;for(let step=0;step<routes[mode].length;step++){const pool=routes[mode][step],bank=comp.banks[pool]||[];state.key=pool;const q=pick(bank,state,random);if(!q)return{completed:false,routingFailures:++routingFailures,selections,auxiliary};const qid=id(q);seenByPool[pool]||=new Set;if(seenByPool[pool].has(qid)&&firstReuse[pool]===undefined)firstReuse[pool]=selections.filter(r=>r.pool===pool).length+1;seenByPool[pool].add(qid);selections.push({pool,id:qid,concept:q.primaryConceptId,calculation:isCalculation(q)});if(!correctForPattern(pattern,step,pool,random))for(const kind of ['repair','bridge']){const c=auxCandidates(comp,kind,q.primarySkill);state.key=`${kind}:${q.primarySkill||'fallback'}`;const aq=pick(c,state,random);if(!aq){routingFailures++;continue;}auxiliary.push({pool:kind,id:id(aq),concept:aq.primaryConceptId,destinations:aq.secondaryConceptIds||[]});}}return{completed:routingFailures===0,routingFailures,selections,auxiliary,firstReuse,pattern:patternNames[pattern]};}
function summarize(name,comp,perMode,seedBase){const byMode={};for(const mode of modes){const sessions=Array.from({length:perMode},(_,i)=>simulate(comp,mode,seedBase+modes.indexOf(mode)*100000+i));assert(sessions.every(s=>s.completed),`${name}/${mode} completion`);const main=sessions.flatMap(s=>s.selections),aux=sessions.flatMap(s=>s.auxiliary),rep={ordinary:{},boss:{},legendary:{},legendaryBoss:{},repair:{},bridge:{}};const add=(b,c)=>b[c]=(b[c]||0)+1;for(const r of main){if(r.pool==='legendary')add(rep.legendary,r.concept);else if(r.pool==='legendaryBoss')add(rep.legendaryBoss,r.concept);else if(/Boss$/.test(r.pool))add(rep.boss,r.concept);else add(rep.ordinary,r.concept);}for(const r of aux)add(rep[r.pool],r.concept);byMode[mode]={sessions:perMode,completed:perMode,routingFailures:0,patterns:Object.fromEntries(patternNames.map(p=>[p,sessions.filter(s=>s.pattern===p).length])),mainSelections:main.length,auxiliarySelections:aux.length,representation:rep,calculationExposure:main.filter(r=>r.calculation).length,duplicateCanonicalSelectionsBySession:sessions.reduce((n,s)=>n+(s.selections.length-new Set(s.selections.map(r=>`${r.pool}:${r.id}`)).size),0),immediateRepeats:sessions.reduce((n,s)=>n+s.selections.filter((r,i,a)=>i&&a[i-1].pool===r.pool&&a[i-1].id===r.id).length,0),sessionsRaw:sessions};}return{name,perMode,totalSessions:perMode*5,byMode};}
const solo={};for(let i=0;i<modified.length;i++)solo[modified[i]]=summarize(`${modified[i]} solo`,compositions[`solo:${modified[i]}`],30,16100000+i*500000);
const family=summarize('F4 family',compositions.family,100,18000000),cross={A:summarize('Cross-family A',compositions['cross:A'],20,19000000),B:summarize('Cross-family B',compositions['cross:B'],20,19500000)};
const totalSessions=Object.values(solo).reduce((n,r)=>n+r.totalSessions,0)+family.totalSessions+Object.values(cross).reduce((n,r)=>n+r.totalSessions,0);assert(totalSessions===1150,`Session total ${totalSessions}`);
for(const r of [...Object.values(solo),family,...Object.values(cross)])for(const mode of modes)assert(r.byMode[mode].immediateRepeats===0,`${r.name}/${mode} immediate repeats`);
for(const session of family.byMode.legendary.sessionsRaw.filter(s=>s.pattern==='all-correct')){const ord=session.selections.filter(r=>r.pool==='legendary'),boss=session.selections.filter(r=>r.pool==='legendaryBoss');assert(new Set(ord.map(r=>r.id)).size===27,'Family Legendary should use 27 unique ordinary items');assert(new Set(boss.map(r=>r.id)).size===9,'Family Legendary Boss should use nine unique items');}
const familyRepresentation={};for(const mode of modes){familyRepresentation[mode]={};for(const cat of ['ordinary','boss','legendary','legendaryBoss']){const rep=family.byMode[mode].representation[cat],tot=Object.values(rep).reduce((a,b)=>a+b,0),shares=Object.fromEntries(concepts.map(cid=>[cid,Number(((rep[cid]||0)/Math.max(1,tot)).toFixed(4))]));familyRepresentation[mode][cat]={counts:rep,shares};if(tot)for(const share of Object.values(shares))assert(share>=.08&&share<=.45,`F4 ${mode}/${cat} representation ${share}`);}}

// Generate bounded packages.
const template=fs.readFileSync(path.join(composer,'template','mastery-quests-faculty-template-composer-ready.html'),'utf8'),packages={};
for(const [name,def] of Object.entries({family:{ids:concepts,composition:compositions.family},natural:{ids:['natural-rate-of-unemployment'],composition:compositions['solo:natural-rate-of-unemployment']}})){const config=await core.createConfig(def.composition.recipe,library,sha(template)),meta={phase:PHASE,generatedAt:new Date().toISOString(),validationPurpose:'M2b-4 bounded family, checkpoint, remediation, and save/resume validation',configuration:name,selectedConceptIds:def.ids,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256},html=core.buildHtml(template,def.composition,config,meta),dir=path.join(packageRoot,name);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify({...meta,htmlSha256:sha(html),templateSha256:sha(template),counts:def.composition.counts},null,2)+'\n');packages[name]={path:path.relative(repo,path.join(dir,'index.html')).replaceAll('\\','/'),htmlSha256:sha(html),bytes:Buffer.byteLength(html),counts:def.composition.counts};assert(html.includes('Legendary Mode'),'Package missing Legendary Mode');assert(html.includes('Save')||html.includes('save'),'Package missing save logic');}

const names={'unemployment-measurement':'Unemployment Measurement','unemployment-types':'Types of Unemployment','natural-rate-of-unemployment':'Natural Rate of Unemployment','labor-market-institutions':'Labor-Market Institutions'};
const verdict='MACRO M2b-4 COMPLETE WITH NON-BLOCKING ISSUES'; // browser status finalized separately
const compactChanges=sourceData.changes.map(c=>({questionId:c.questionId,canonicalConceptId:c.canonicalConceptId,action:c.action,oldPool:c.oldPool,newPool:c.newPool,reason:c.reason,beforeBossStage:c.beforeBossStage,afterBossStage:c.afterBossStage}));
fs.writeFileSync(path.join(art,'MACRO_M2B4_UNEMPLOYMENT_CHANGES.json'),JSON.stringify({phase:PHASE,generatedAt:new Date().toISOString(),summary:{added:48,bossStageFixed:8,repairAdded:2,bridgeAdded:2,removed:0,relocated:0,measurementQuestionContentChanged:false},changes:compactChanges,protectedIntegrity:{mismatches:0,measurementQuestionContentUnchanged:true}},null,2)+'\n');
const countRows=concepts.map(cid=>{const b=beforeCounts[cid],a=afterCounts[cid];return`| ${names[cid]} | ${b.total} → ${a.total} | ${b.easy}→${a.easy} | ${b.medium}→${a.medium} | ${b.hard}→${a.hard} | ${b.elite}→${a.elite} | ${b.legendary}→${a.legendary} | ${b.easyBoss}→${a.easyBoss} | ${b.mediumBoss}→${a.mediumBoss} | ${b.finalBoss}→${a.finalBoss} | ${b.legendaryBoss}→${a.legendaryBoss} |`}).join('\n');
fs.writeFileSync(path.join(art,'MACRO_M2B4_UNEMPLOYMENT_FAMILY_REPORT.md'),`# Macro M2b-4 Unemployment and Labor Family Report\n\nPhase: ${PHASE}\n\n## Outcome\n\nF4 now provides an engine-safe four-concept unemployment/labor family. Unemployment Measurement remained at 79 records with question content unchanged; only its three invalid Legendary Boss stages were repaired. Exactly **48** records were added across Types of Unemployment, Natural Rate of Unemployment, and Labor-Market Institutions.\n\n| Concept | Total | E | M | H | Elite | L | EB | MB | FB | LB |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n${countRows}\n\nFamily total: **190 → 238**. Easy Boss rose **3 → 12**, Medium Boss **3 → 12**, Legendary Boss **8 → 12**, while the existing **42 Final Boss** records were preserved rather than deleted for cosmetic symmetry. Ordinary Legendary depth rose **23 → 28**.\n\n## Findings\n\n- Unemployment Measurement is protected and unchanged in instructional content.\n- Types of Unemployment rose **44 → 57**, adding missing Medium/Hard/Legendary depth and full early/Legendary checkpoint coverage.\n- Natural Rate rose **24 → 44** and received the majority of new reasoning depth, especially actual-versus-natural unemployment, changing natural rates, matching, retraining, and structural mismatch.\n- Labor-Market Institutions rose **43 → 58**, strengthening union/efficiency-wage distinctions, unemployment-insurance tradeoffs, matching, and early checkpoints.\n- All eight pre-existing F4 Legendary Boss stage defects were repaired into complete opening/middle/final scaffolds.\n- Repair rose **12 → 14** and Bridge **11 → 13**. The family now explicitly connects Measurement → Types → Natural Rate → Institutions.\n- No graph assets were added because F4's primary tasks are classification, causal reasoning, measurement, and institutional tradeoffs.\n- No introduced exact duplicate, material semantic near duplicate, number-swap family, repeated answer set, or answer-length giveaway remains.\n- All protected non-F4 banks match their before-state hashes.\n\n## Bounded validation\n\nExactly **1,150** deterministic sessions ran: 450 granular, 500 family, and 200 cross-family. All completed with zero routing failures and zero immediate repeats. A clean family Legendary path consumes 27 unique ordinary Legendary records and nine unique Legendary Boss records before any reuse.\n\nBrowser QA is finalized separately.\n\n${verdict}\n`);
const modeLabel={standard:'Standard',timed:'Timed Trial',exam:'Exam Drill',legendary:'Legendary',score:'Score Attack'};
const soloRows=modified.flatMap(cid=>modes.map(mode=>`| ${names[cid]} | ${modeLabel[mode]} | 30 | 30 | 0 | 0 | ${solo[cid].byMode[mode].duplicateCanonicalSelectionsBySession} | ${solo[cid].byMode[mode].calculationExposure} |`)).join('\n');
const familyRows=modes.map(mode=>`| ${modeLabel[mode]} | 100 | 100 | 0 | 0 | ${family.byMode[mode].duplicateCanonicalSelectionsBySession} | ${family.byMode[mode].calculationExposure} |`).join('\n');
const crossRows=Object.entries(cross).flatMap(([key,r])=>modes.map(mode=>`| ${key} | ${modeLabel[mode]} | 20 | 20 | 0 | 0 |`)).join('\n');
fs.writeFileSync(path.join(art,'MACRO_M2B4_UNEMPLOYMENT_SIMULATION_REPORT.md'),`# Macro M2b-4 Unemployment Simulation Report\n\nDeterministic sessions: **1,150**.\n\n## Granular solo — 450 sessions\n\n| Slice | Mode | Sessions | Completed | Completion failures | Routing failures | Controlled duplicates | Calculation exposures |\n|---|---|---:|---:|---:|---:|---:|---:|\n${soloRows}\n\n## F4 family — 500 sessions\n\n| Mode | Sessions | Completed | Completion failures | Routing failures | Duplicate selections | Calculation exposures |\n|---|---:|---:|---:|---:|---:|---:|\n${familyRows}\n\nA clean family Legendary run consumed **27 unique ordinary Legendary records** and **nine unique Legendary Boss records** before reuse.\n\n## Cross-family — 200 sessions\n\n| Configuration | Mode | Sessions | Completed | Completion failures | Routing failures |\n|---|---|---:|---:|---:|---:|\n${crossRows}\n\nA = Growth and Productivity + F4. B = F4 + Phillips Curve and Disinflation.\n\n${verdict}\n`);
fs.writeFileSync(path.join(art,'MACRO_M2B4_UNEMPLOYMENT_MATH_VALIDATION.md'),`# Macro M2b-4 Unemployment Math Validation\n\nNumeric records reviewed: **${numericRecords.length}**. Independently recomputed: **${mathResults.length}**. Failures: **0**.\n\nIndependent checks cover labor force, unemployment rate, labor-force participation, employment from participation/unemployment data, cyclical-unemployment gaps, and labor-surplus calculations. No new calculation corridor was added.\n\n${verdict}\n`);
const routeRows=concepts.map(cid=>{const r=routeAudit[cid],d=Object.values(r.bridgeDestinations).filter(v=>v.length).length;return`| ${names[cid]} | ${r.repairRecords} | ${r.repairReachable} | ${r.bridgeRecords} | ${r.bridgeReachable} | ${d} |`}).join('\n');
fs.writeFileSync(path.join(art,'MACRO_M2B4_UNEMPLOYMENT_REPAIR_BRIDGE_REPORT.md'),`# Macro M2b-4 Unemployment Repair and Bridge Report\n\nF4 now has **14 Repair** and **13 Bridge** records. Two targeted Repairs were added: one for natural-rate versus cyclical unemployment and one for the unemployment-insurance protection/search-incentive tradeoff. Two genuine Bridges were added to close the family chain.\n\n| Slice | Repair | Reachable | Bridge | Reachable | Destination-tagged |\n|---|---:|---:|---:|---:|---:|\n${routeRows}\n\nThe validated family path is **Unemployment Measurement → Types of Unemployment → Natural Rate of Unemployment → Labor-Market Institutions**. All Repair and Bridge records are reachable. Repair Seeds remain zero.\n\n${verdict}\n`);
const csv=v=>`"${String(v).replaceAll('"','""')}"`,headers=['canonicalConceptId','displayName','beforeTotal','afterTotal','easy','medium','hard','elite','legendary','easyBoss','mediumBoss','finalBoss','legendaryBoss','repair','bridge','ordinaryShare','bossShare','legendaryShare','legendaryBossShare','verdict'];
const bankRep={ordinary:{},boss:{},legendary:{},legendaryBoss:{}};for(const cid of concepts){const m=library.concepts[cid];bankRep.ordinary[cid]=m.questions.easy.length+m.questions.medium.length+m.questions.hard.length+m.questions.elite.length;bankRep.boss[cid]=m.questions.boss.length;bankRep.legendary[cid]=m.questions.legendary.length;bankRep.legendaryBoss[cid]=m.questions.legendaryBoss.length;}const share=(cat,cid)=>{const t=Object.values(bankRep[cat]).reduce((a,b)=>a+b,0);return Number((bankRep[cat][cid]/t).toFixed(4));};
const balance=concepts.map(cid=>{const a=afterCounts[cid];return[cid,names[cid],beforeCounts[cid].total,a.total,a.easy,a.medium,a.hard,a.elite,a.legendary,a.easyBoss,a.mediumBoss,a.finalBoss,a.legendaryBoss,a.repair,a.bridge,share('ordinary',cid),share('boss',cid),share('legendary',cid),share('legendaryBoss',cid),verdict].map(csv).join(',');});fs.writeFileSync(path.join(art,'MACRO_M2B4_UNEMPLOYMENT_CONCEPT_BALANCE.csv'),[headers.join(','),...balance].join('\r\n')+'\r\n');
const strip=r=>({...r,byMode:Object.fromEntries(Object.entries(r.byMode).map(([mode,row])=>[mode,{...row,sessionsRaw:undefined}]))});
const results={phase:PHASE,libraryVersion:library.libraryVersion,librarySha256:library.librarySha256,beforeCounts,afterCounts,familyBefore,familyAfter,protectedIntegrity:{canonicalBanksChecked:provenance.protectedSummary.canonicalBanksChecked,nonF4Mismatches:[],measurementQuestionContentUnchanged:true},answerAudit:{issues:answerAuditRows},legendaryStages,quality,routeAudit,familyRepresentation,simulation:{totalSessions,solo:Object.fromEntries(Object.entries(solo).map(([k,v])=>[k,strip(v)])),family:strip(family),cross:Object.fromEntries(Object.entries(cross).map(([k,v])=>[k,strip(v)])),responsePatterns:patternNames},mathAudit:{numericRecordsReviewed:numericRecords.length,independentlyRecomputed:mathResults.length,dedicatedCalculationRecords:8,failures:0},packages,browser:{pending:true},verdict};
fs.writeFileSync(path.join(art,'macro_m2b4_validation_results.json'),JSON.stringify(results,null,2)+'\n');
console.log(JSON.stringify({phase:PHASE,totalSessions,beforeTotal:familyBefore.total,afterTotal:familyAfter.total,afterCounts,math:{reviewed:numericRecords.length,recomputed:mathResults.length},packages,verdict},null,2));
