add(nl('LEGENDARY-9045'),'At the start, real GDP per person is $32,000 in Alder and $8,000 in Birch. Their persistent growth rates are 1.75% and 7%. Using the Rule of 70, which comparison follows after 40 years?',
 ['Alder is near $64,000 and Birch near $128,000; matching Alder’s initial level earlier was not yet catching its moving level','Both are near $64,000 because Birch began at one-quarter of Alder’s level','Alder is near $64,000 and Birch near $32,000; count only one doubling for Birch','Birch stays poorer because a lower starting level cannot be overcome'],
 'Approximate doubling times are 40 years for Alder and 10 for Birch. Over 40 years Alder doubles once to 64,000, while Birch doubles four times to 128,000. Reaching a rival’s initial level is distinct from catching a rival that also grows.','C/D: connect multiple doublings with a moving comparison target.', [('A time','70/1.75',40),('B time','70/7',10),('A final','32000*2',64000),('B final','8000*2**4',128000)])
add(nl('LEGENDARY-9046'),'Over a decade, real GDP rises 12%, population rises 5%, and total labor hours rise 20%. Which pair best evaluates average material output and hourly productivity, to one decimal place?',
 ['Real GDP per person rises 6.7%; output per hour falls 6.7%','Both rise 12% because total real GDP rose','Real GDP per person rises 7%; output per hour falls exactly 8%','Real GDP per person falls 6.7%; output per hour rises 6.7%'],
 'Per-person output changes by 1.12/1.05 - 1 ≈ 6.7%; hourly output changes by 1.12/1.20 - 1 ≈ -6.7%. More total hours can raise average output even while productivity per hour falls.','C/D: distinguish two labor/population denominators and opposing inferences.', [('per person','(1.12/1.05-1)*100',6.666666666666667),('per hour','(1.12/1.2-1)*100',-6.666666666666667)])
add(nl('LEGENDARY-9047'),'Cedar reports nominal GDP of $960 billion, a deflator of 120, and 32 million residents. Delta reports $1,320 billion, a deflator of 150, and 44 million residents. Which current real-GDP-per-person comparison is supported using comparable base prices?',
 ['Cedar $25,000; Delta $20,000, so higher nominal total does not imply higher average real output','Cedar $30,000; Delta $30,000, so average real output is equal','Cedar $25,000; Delta $30,000, because only Cedar needs deflation','Cedar $20,000; Delta $25,000, because the larger deflator raises real output'],
 'Real GDP is 960/1.20 = 800 billion for Cedar and 1,320/1.50 = 880 billion for Delta. Divide by populations: 25,000 and 20,000 per person. The larger nominal aggregate does not settle the living-standard comparison.','C/D: combine deflation, scale conversion and per-person comparison.', [('Cedar','960/1.2/32*1000',25000),('Delta','1320/1.5/44*1000',20000)])
add(nl('LEGENDARY-9049'),'Real output per hour rises 10%, annual hours per employed person fall 5%, and the employed share of the population falls from 60% to 58%. Which conclusion about real GDP per person follows, assuming these cover all production?',
 ['It rises about 1.0%; the other two factors offset much of the productivity gain','It rises 10%; hourly productivity alone determines the exact change','It falls 7%; add the percentage and percentage-point declines','It rises 5%; the employed share does not enter output per person'],
 'Output per person equals output/hour × hours/worker × workers/person. Its factor is 1.10 × 0.95 × (58/60) ≈ 1.01017. Average output rises about 1.0%, much less than the hourly-productivity increase.','C/D: reconstruct the sources of per-person growth without conflating workers and residents.', [('growth','(1.1*.95*(58/60)-1)*100',1.0166666666666666)])
add(nl('ELITE-344'),'Two economies have equally scarce capital and similar access to technology. One has reliable electricity and trained operators; the other has frequent outages and little training. Which evidence best limits a claim that both must catch up equally fast?',
 ['The complementary inputs differ, so equal capital scarcity does not imply equal realized gains','Scarce capital has a low marginal product in both, regardless of complementary inputs','Technology access proves training and infrastructure no longer matter','A country’s current income ranking fixes its future growth ranking'],
 'Capital scarcity can create high-return opportunities, but skilled workers and usable infrastructure help realize them. Catch-up is conditional; equal starting capital alone does not establish equal productivity growth.','C: evaluate a conditional catch-up inference instead of recognizing a poor country.')
add(nl('LEGENDARY-9050'),'A plant initially produces 24,000 units using 20 workers who each work 100 hours. Next period, 24 workers each work 80 hours and produce 25,344 units. Which comparison is correct?',
 ['Output per worker falls 12%; output per hour rises 10%','Both productivity measures rise 5.6%, matching total output','Output per worker rises 10%; output per hour falls 12%','Output per hour is unchanged because the plant hired more workers'],
 'Per-worker output falls from 1,200 to 1,056, or 12%. Total hours fall from 2,000 to 1,920; hourly output rises from 12 to 13.2, or 10%. Changes in hours per worker make the productivity measures diverge.','C/D: reconstruct total hours and compare opposing worker/hour measures.', [('initial hourly','24000/(20*100)',12),('final hourly','25344/(24*80)',13.2),('worker growth','((25344/24)/(24000/20)-1)*100',-12),('hour growth','(13.2/12-1)*100',10)])
add(nl('LEGENDARY-9051'),'An economy initially produces $90 billion using 3 billion labor hours. A plan targets $108 billion while limiting total hours to 3.2 billion. What hourly productivity and increase over the initial level are required?',
 ['$33.75 per hour, a 12.5% increase','$36 per hour, a 20% increase','$30 per hour, with no productivity gain','$28.125 per hour, a 6.25% decline'],
 'Initial productivity is 90/3 = 30 dollars per hour. The target requires 108/3.2 = 33.75, or 12.5% more. Output growth alone overstates the needed productivity increase because hours also expand.','C/D: reverse a resource-constrained output target and interpret the required productivity gain.', [('target','108/3.2',33.75),('growth','((108/3.2)/(90/3)-1)*100',12.5)])
add(nl('LEGENDARY-9053'),'A country’s real GDP rises 6% while employment rises 10%. Population is unchanged. Which assessment separates average material output from output per worker?',
 ['Output per person rises 6%; output per worker falls about 3.6%','Both fall about 3.6% because productivity declined','Both rise 6% because GDP increased','Output per person falls 4%; subtract employment growth from GDP growth'],
 'With population fixed, GDP per person rises 6%. Output per worker changes by 1.06/1.10 - 1 ≈ -3.6%. A productivity decline does not imply that average output per resident also declined.','B/C/D: correct the unsupported living-standard implication in the former keyed wording.', [('worker growth','(1.06/1.1-1)*100',-3.6363636363636362)])
add(nl('LEGENDARY-9066'),'Output per worker rises from $50,000 to $55,000, but real GDP per resident stays at $30,000. What must happen to the employed share of residents, assuming the measures cover the same output?',
 ['It falls from 60% to about 54.5%, offsetting the productivity rise','It rises from 60% to 66%, reinforcing the productivity rise','It stays at 60% because output per resident is unchanged','It falls from 50% to 45%, because wages determine employment shares'],
 'Workers/residents equals output/resident divided by output/worker. The share changes from 30,000/50,000 = 60% to 30,000/55,000 ≈ 54.5%. This accounting result does not identify why the employment share fell.','C/D: reverse two productivity measures and distinguish accounting from causation.', [('initial share','30000/50000*100',60),('final share','30000/55000*100',54.54545454545455)])
add('PM2B3-PROD-FB-004','Use the displayed GROWTH-01 coordinates. Moving from A to B doubles capital per worker. Approximately how much does output per worker rise, and what is consistent with the curve’s shape?',
 ['27.5%; the same further capital increase would add less output','7.84%; the numerical output increase is already a percentage','100%; doubling capital must double output','27.5%; each further equal capital increase must add more output'],
 'The graph gives output 28.53 at A and 36.37 at B. The increase is 7.84/28.53 × 100 ≈ 27.5%. The flattening curve shows diminishing marginal gains from equal additional capital, holding other inputs fixed.','E/D: remove all-answer coordinates from the stem and require the approved image for calculation and inference.', [('output growth','(36.37-28.53)/28.53*100',27.479845776375745)])
add(nl('LEGENDARY-9054'),'A factory adds machinery but productivity barely changes. After operator training, output rises with the same machines and labor hours. A manager concludes that machines have no productive value. Which interpretation best fits both stages?',
 ['Training helped realize the value of complementary capital; the first stage did not show that machines were useless','Training proves all earlier spending on machines should be subtracted from GDP','The later gain must be more physical capital because worker skills are unchanged by training','The data prove training raises output equally in every factory, regardless of equipment'],
 'The second stage changes human capital while holding physical inputs fixed. Its effect can reflect complementarity between skills and machinery. A weak result before training does not identify a zero contribution from capital.','C: evaluate staged evidence and an overbroad causal conclusion.')
add(nl('LEGENDARY-9056'),'Two plants initially use the same machines and hours. Plant A adopts a freely available scheduling method and raises output 8%. Plant B trains operators without changing its method and raises output 8%. What can be inferred about productivity sources?',
 ['A changed technological knowledge and B human capital; equal output gains do not make the mechanisms identical','Both added physical capital because output rose without more labor hours','Both changed natural resources because the gain has the same size','A’s gain is human capital and B’s is technology solely because both involve information'],
 'A new production method is technological knowledge; skills acquired by workers are human capital. Equal measured gains do not identify a common mechanism or prove the two interventions would have equal effects elsewhere.','C: separate productivity sources under a matched outcome.')
add(nl('LEGENDARY-9058'),'With labor, skills and technology fixed, output at 10, 20 and 30 identical machines is 100, 160 and 200 units. A planner predicts that 40 machines must yield 260. Which assessment follows from the observed pattern?',
 ['The successive gains are 60 and 40; continued diminishing marginal returns would put the next gain below 40','The observed average gain is 50, so 40 machines must yield exactly 250','The capital stock doubled once, proving output must double at 40 machines','The last gain was 40, so every later ten machines must add exactly 40'],
 'Equal capital increments add 60 then 40 units while other inputs are fixed. If the diminishing-returns pattern continues, the next increment adds less than 40; the table alone does not supply an exact future output level.','B/C/D: state controlled inputs and distinguish marginal evidence from unsupported extrapolation.', [('first gain','160-100',60),('second gain','200-160',40)])
add(nl('LEGENDARYBOSS-9120'),'Two equal additions to capital per worker produce output gains of 9 and 6 with skills and technology fixed. A later 9-unit gain occurs after a new production method is introduced. Does that last observation refute diminishing returns to capital?',
 ['No; the first two gains compare capital with other inputs fixed, while technology changed in the third','Yes; any later larger gain refutes diminishing returns regardless of other changes','No; diminishing returns means total output must fall after adding capital','Yes; introducing technology changes physical capital into a natural resource'],
 'Diminishing marginal returns concerns additional capital with other determinants held fixed. The first two gains fit that pattern. A technology improvement changes the production relationship, so the larger third gain is not a comparable capital-only experiment.','B/C: add the missing fixed-input condition and test a competing explanation.')
add(nl('LEGENDARY-9060'),'A country raises saving incentives, yet surveyed firms postpone equipment purchases because contracts are often unenforceable. A proposed response doubles the saving subsidy without changing courts. Which recommendation is best supported?',
 ['Address enforcement risk alongside finance; more saving alone may not make productive investment attractive','Double the subsidy because every extra saved dollar necessarily becomes domestic machinery','Reduce worker training because courts and skills are substitute measures of the same input','Infer that physical capital has zero marginal product because investment is currently weak'],
 'The evidence identifies insecure returns as a barrier between available funds and investment. Predictable enforcement can complement financing. The survey does not establish an optimal subsidy or prove capital has no productive value.','C: evaluate a proposed policy against the mechanism in the evidence.')
add(nl('LEGENDARY-9062'),'A region has trained engineers and funds for new equipment, but a rule prevents firms from using improved production methods. A review proposes more of the same training while keeping that rule. Which response best addresses the stated constraint?',
 ['Permit useful method adoption while maintaining skills and investment; training alone may not release the constraint','Purchase equipment alone because methods cannot affect output with machines fixed','Keep the rule because a stock of trained workers guarantees continuing productivity growth','Stop all training because technological knowledge makes human capital unproductive'],
 'The constrained margin is adopting better methods. Technology, skills and equipment can complement one another; repeating one input policy while blocking another can limit the gain. This is a conditional recommendation from the stated evidence.','C: replace a general complements slogan with an evaluated policy response.')
add(nl('LEGENDARY-9063'),'A policy package improves contract enforcement, funds technical training, and supports research trials. After two years, capital and skill measures rise but output growth remains modest. Which assessment best separates a coherent strategy from a guaranteed result?',
 ['The package targets productivity determinants; implementation, diffusion and time still matter for realized growth','The package failed in principle because research must raise output immediately','The capital increase proves the research trials caused all future growth','The modest output change proves institutions cannot affect investment incentives'],
 'The instruments address institutions, human capital and technological knowledge. These are plausible growth channels, but observed short-run output alone neither guarantees eventual success nor disproves the channels. Implementation and technology diffusion must be evaluated.','C: assess evidence and timing behind an established growth-policy package.')
add(nl('ELITE-359'),'A country wants continuing productivity growth after a one-time equipment grant has raised capital per worker. Which package best addresses the limitation imposed by diminishing returns?',
 ['Maintain useful investment while improving skills, research and adoption of better methods','Repeat equal equipment grants and assume each creates a larger marginal output gain','Increase working hours and treat all additional output as higher hourly productivity','Replace training with equipment because physical and human capital cannot complement each other'],
 'Additional capital can still raise output, but its marginal contribution may diminish with other inputs fixed. Skills and technological progress complement capital and support productivity growth beyond a single level increase.','C: apply a policy package to an explicit growth constraint.')
