add(nl('LEGENDARY-9067'),'A labor survey starts with 132 employed, 12 unemployed and 56 other adults. Then 4 unemployed find jobs, 3 stop searching, 5 outsiders start searching without finding work, and 2 employed retire. All job seekers are available. What are the new unemployment and participation rates?',
 ['About 6.9% unemployment and 72% participation','About 5% unemployment and 72% participation','About 6.9% unemployment and 75.5% participation','About 8.3% unemployment and 72% participation'],
 'Employment becomes 132 + 4 - 2 = 134 and unemployment 12 - 4 - 3 + 5 = 10. The labor force is 144 of 200 adults, so participation is 72% and unemployment is 10/144 ≈ 6.9%. The entering and leaving flows happen to offset in total participation.','C/D: reconcile several worker flows and both denominators.', [('employed','132+4-2',134),('unemployed','12-4-3+5',10),('u rate','10/144*100',6.944444444444445),('LFPR','144/200*100',72)])
add(nl('LEGENDARY-9068'),'There are 200 adults, labor-force participation is 75%, and unemployment is 8%. Next month 6 unemployed stop searching, 6 employed retire, and 4 outsiders start searching without finding work. With everyone otherwise unchanged and seekers available, which final account is correct?',
 ['132 employed; about 7.0% unemployment; 71% participation','138 employed; 4% unemployment; 75% participation','132 employed; 5% unemployment; 71% participation','144 employed; about 6.5% unemployment; 77% participation'],
 'Initially LF = 150, U = 12 and E = 138. After the flows E = 132, U = 12 - 6 + 4 = 10 and LF = 142. Thus U/LF ≈ 7.0% and LF/adults = 71%. A lower unemployment rate coexists with fewer people employed.','C/D: reverse starting stocks from rates and then reconcile transitions.', [('initial LF','200*.75',150),('initial U','150*.08',12),('final E','150-12-6',132),('final U','12-6+4',10),('u rate','10/142*100',7.042253521126761),('LFPR','142/200*100',71)])
add(nl('LEGENDARY-9070'),'A population of 200 adults is unchanged. The unemployment rate stays at 6%, while participation falls from 75% to 70%. Which employment change and interpretation follow?',
 ['Employment falls by 9.4; a stable unemployment rate does not imply a stable number of jobs','Employment stays at 141; a stable rate fixes employment','Employment falls by 10; every labor-force exit must be an employed worker','Employment rises by 9.4; lower participation indicates more jobs'],
 'The labor force falls from 150 to 140. Employment is 94% of each total: 141 initially and 131.6 afterward, a decline of 9.4. The unchanged unemployment rate is a ratio, not an unchanged employment count.','C/D: infer employment from simultaneous rate observations and challenge a misleading summary.', [('initial E','200*.75*.94',141),('final E','200*.70*.94',131.6),('E decline','200*(.75-.70)*.94',9.4)])
add(nl('LEGENDARY-9081'),'A report says unemployment fell from 20 to 12 while employment rose from 180 to 184. Adult population is fixed at 250, and the only flows were unemployed people finding jobs or stopping search. Which decomposition and participation change are implied?',
 ['4 found jobs and 4 left search; participation fell from 80% to 78.4%','8 found jobs; participation stayed at 80%','4 found jobs and 8 left search; participation fell to 76.8%','4 left search and none found jobs; the employment rise is unrelated'],
 'The employment rise identifies 4 job findings. Of the 8-person unemployment decline, the remaining 4 are exits. LF falls from 200 to 196, so participation falls from 80% to 78.4%. Both hiring and withdrawal contributed to the lower headline rate.','C/D: reverse worker flows instead of accepting a lower unemployment total as sufficient evidence.', [('hires','184-180',4),('exits','20-12-(184-180)',4),('initial LFPR','200/250*100',80),('final LFPR','(184+12)/250*100',78.4)])
add(nl('LEGENDARY-9084'),'Two districts have the same unemployment rate and population. One has lower participation and a larger share of employed people working part time because full-time work is unavailable. Which additional comparison is best before calling their labor markets equally strong?',
 ['Compare employment per adult and desired versus actual hours; the headline rate omits both differences','Compare only total unemployment; equal unemployment rates guarantee equal counts','Count all involuntary part-time workers as unemployed before applying the official definition','Exclude discouraged workers from every indicator because they are outside the labor force'],
 'Unemployment divides job seekers by the labor force. Lower participation can lower employment per adult even at the same rate, while involuntary part-time workers remain employed. Additional participation and hours evidence is needed for the broader assessment.','C: evaluate what information is needed beyond headline classification.')
add(nl('ELITE-366'),'A survey has 84 adults working for pay, including 14 seeking more hours; 6 available jobless adults applied last week; 30 jobless adults are not searching. Which official count and limitation are correct?',
 ['Labor force 90 and unemployment about 6.7%; underemployment among paid workers is not in that rate','Labor force 104 and unemployment about 19.2%; add those seeking more hours to unemployment','Labor force 120 and unemployment 5%; use every adult in the denominator','Labor force 76 and unemployment about 7.9%; exclude part-time paid workers'],
 'All 84 paid workers are employed, including those wanting more hours. Add the 6 active, available seekers for LF = 90; 6/90 ≈ 6.7%. The rate does not measure all of the part-time workers’ unmet demand for hours.','C/D: apply classifications to a rate and its limitation.', [('LF','84+6',90),('rate','6/90*100',6.666666666666667)])
add(nl('FINALBOSS-4003'),'A survey records 126 employed adults, 14 available jobless adults actively searching, and 60 adults outside the labor force. Which participation calculation is correct, and how does it differ from unemployment?',
 ['70% participation; unemployment uses 14 divided by 140','63% participation; unemployment uses 14 divided by 200','90% participation; unemployment uses 14 divided by 126','7% participation; unemployment and participation are the same ratio'],
 'Participation is (126 + 14)/(126 + 14 + 60) = 70%. Unemployment instead divides the 14 unemployed by the labor force of 140, yielding 10%. The denominators answer different questions.','C/D: replace a final-checkpoint definition with ordinary exam measurement.', [('LFPR','(126+14)/(126+14+60)*100',70),('u rate','14/140*100',10)])
add(nl('FINALBOSS-4006'),'A jobless adult who had stopped searching accepts a paid part-time job but still wants full-time work. With other adults unchanged, which immediate changes follow?',
 ['Employment and the labor force rise; involuntary part-time work can remain','Unemployment rises because the worker still wants a full-time job','Employment rises but the labor force stays fixed because the job is part time','Participation falls because part-time employment is outside the labor force'],
 'The worker moves from outside the labor force to employed. Both employment and the labor force rise, while wanting more hours does not change the official employed classification. The hours shortfall remains relevant to labor-market well-being.','C: replace checkpoint label recall with a status transition and interpretation.')
add(nl('LEGENDARY-9074'),'After a regional downturn ends, one group has suitable job offers but needs time to choose; another cannot meet credentials for expanding occupations. A third group has already accepted paid part-time work while seeking full-time jobs. Which diagnosis respects both cause and official status?',
 ['The first group is frictionally unemployed, the second structurally unemployed, and the third employed','All three are structurally unemployed because each wants a different job','The first is cyclical, the second frictional, and the third outside the labor force','All three are unemployed until they obtain their preferred full-time jobs'],
 'Normal matching among suitable jobs is frictional; a persistent credential mismatch is structural. A paid part-time job makes the third group employed under the official measure, even though underemployment may remain.','C: integrate causes of unemployment with the separate employment-status classification.')
add(nl('LEGENDARY-9080'),'Spending and total vacancies recover after a downturn, but vacancies concentrate in licensed occupations while displaced workers lack the credentials. Which evidence would most directly strengthen a structural diagnosis over a purely cyclical one?',
 ['Credential training is followed by placements into the unfilled occupations while overall spending changes little','All vacancies disappear when spending weakens again','Workers have suitable offers and are briefly choosing among them','Unemployment falls only when economy-wide spending rises sharply, with no change in skills'],
 'The mismatch between expanding occupations and worker credentials points to a structural barrier. Placements after relevant training, with demand broadly unchanged, strengthen that mechanism rather than a claim based only on weak spending or ordinary search.','C: choose discriminating evidence among plausible unemployment mechanisms.')
add('PM2B4-UTYPE-L-002','A city’s jobless population includes skilled movers choosing among local openings and workers whose occupation disappeared. A single faster job-listing service is proposed for both. Which prediction is best supported?',
 ['It can shorten matching for the first group; the second may also need retraining or mobility support','It must eliminate both groups’ unemployment because each can read the same vacancies','It affects only cyclical unemployment because information is part of total spending','It turns structurally unemployed workers into employed people as soon as listings are viewed'],
 'The first group faces search frictions among suitable jobs. The second faces a durable mismatch that information alone may not remove. Diagnosis should guide the intervention without assuming guaranteed placement.','C: distinguish unemployment mechanisms through a conditional remedy.')
add(nl('LEGENDARY-9076'),'In a competitive labor market, employment is 100 at the clearing wage. A binding wage floor produces labor supply of 140 and demand of 95. Assuming everyone seeking work is available and active, which comparison is correct?',
 ['Employment falls by 5, while the labor surplus is 45; these are different quantities','Employment falls by 45 because every person in the surplus previously had a job','Employment falls by 40, matching the increase in labor supply','There is no surplus because 95 people remain employed'],
 'Employment changes from 100 to 95, a loss of 5. The new excess of labor supplied over labor demanded is 140 - 95 = 45, including the effect of increased job seeking as well as reduced hiring. The surplus is not the number of pre-existing jobs lost.','B/C/D: distinguish a wage-floor labor surplus from employment loss.', [('lost jobs','100-95',5),('surplus','140-95',45)])
add(nl('LEGENDARY-9077'),'A benefit extension lowers the cost of continued search. A simultaneous placement program improves matching. Average unemployment duration then falls. Which conclusion is warranted from these facts alone?',
 ['The combined outcome improved duration; it does not show that the benefit extension by itself shortened search','The fall proves benefit extensions always shorten search','The extension must have been ineffective at protecting income because duration fell','The placement program cannot matter because benefits determine every search decision'],
 'Income support can reduce search urgency while better matching shortens search. Their combined result does not isolate either effect; a credible separate comparison would be needed. The duration result also does not measure the value of income protection.','C: evaluate competing institutional channels and causal limits.')
add(nl('LEGENDARY-9078'),'A negotiated wage rises from $20 to $24 while employment falls from 100 to 90, with hours per worker fixed. What happens to the total wage bill, and what distributional claim is justified?',
 ['The wage bill rises 8%; retained workers gain hourly pay while some workers lose jobs','The wage bill falls 10%; no workers gain from the contract','The wage bill rises 20%; the employment change is irrelevant','The wage bill rises 8%; this proves every original worker is better off'],
 'The wage bill changes from 20 × 100 = 2,000 to 24 × 90 = 2,160 per common unit of hours, an 8% rise. The aggregate increase does not erase the job losses; gains to retained workers and losses to displaced workers differ.','C/D: integrate a union wage/employment account and insider-outsider interpretation.', [('bill growth','((24*90)/(20*100)-1)*100',8)])
add(nl('LEGENDARY-9079'),'A firm considers raising wages from $18 to $21 per hour. Output per hour is expected to rise from 6 to 7 units through better retention and effort, with other unit costs unchanged. Which cost calculation and caution are correct?',
 ['Wage cost stays $3 per unit if the productivity forecast holds; the forecast still needs evidence','$3.50 per unit is certain because productivity cannot respond to wages','$2.57 per unit is certain because the old wage applies to the new output','$3 per unit proves the wage policy eliminates unemployment throughout the economy'],
 'The old wage cost is 18/6 = 3 per unit; the proposed cost is 21/7 = 3 if the effort/retention forecast occurs. This makes an efficiency-wage rationale possible, but does not prove the forecast or settle economy-wide unemployment.','C/D: test an efficiency-wage calculation with a conditional rather than guaranteed conclusion.', [('old unit cost','18/6',3),('new unit cost','21/7',3)])
add(nl('ELITE-375'),'A wage floor is $16. At that wage, 112 workers seek jobs and firms hire 88. A demand increase raises desired hiring to 100 while the wage and labor supply stay fixed. What happens to the labor surplus?',
 ['It falls from 24 to 12; higher labor demand reduces the excess supply','It stays at 24 because the statutory wage did not change','It rises from 24 to 36 because firms want more labor','It disappears because any increase in demand makes a floor nonbinding'],
 'Initially the surplus is 112 - 88 = 24. With hiring demand of 100, it is 112 - 100 = 12. The wage floor can remain binding even as the size of the labor surplus changes.','C/D: compare labor-market outcomes under an unchanged institution.', [('old surplus','112-88',24),('new surplus','112-100',12)])
add(nl('LEGENDARY-9075'),'An economy has 2% frictional, 3% structural and 2% cyclical unemployment. A recovery eliminates the cyclical component. At the same time, better matching lowers frictional unemployment to 1.5%, with structural unemployment unchanged. What actual and natural rates remain?',
 ['Both are 4.5%; recovery removed the cyclical component and matching lowered the natural rate','Both are 5%; recovery cannot change any observed unemployment rate','Actual is 2.5% and natural is 4.5%; subtract the cyclical decline again','Both are zero because the recession has ended'],
 'After recovery, cyclical unemployment is zero. The remaining natural rate is 1.5 + 3 = 4.5%, also the actual rate. Ending the downturn and improving normal matching are distinct channels.','C/D: decompose a changing natural rate and a disappearing cyclical gap.', [('new natural','1.5+3',4.5)])
add(nl('LEGENDARY-9085'),'Actual unemployment falls from 9% to 7%. Over the same interval, an estimate of the natural rate falls from 6% to 4%. What happens to the cyclical gap, and what claim would overstate the evidence?',
 ['The gap stays at 3 points; the lower actual rate alone does not show cyclical weakness diminished','The gap falls 2 points; actual unemployment determines the gap by itself','The gap rises 2 points; a lower natural rate always raises the gap by that amount','The gap becomes zero because both rates fell equally'],
 'Initially the gap is 9 - 6 = 3 points; finally it is 7 - 4 = 3. Actual unemployment fell with the estimated natural benchmark, so these numbers do not show a smaller cyclical component.','C/D: compare moving actual and natural rates rather than one subtraction.', [('old gap','9-6',3),('new gap','7-4',3)])
add('PM2B4-NRU-L-002','A retraining reform is expected to lower structural unemployment by 1 percentage point, but longer voluntary search raises frictional unemployment by 0.4 point. Cyclical unemployment is unchanged. Which natural-rate prediction follows, conditional on both estimates?',
 ['It falls 0.6 point; the policy effects partly offset','It falls 1.4 points; both changes reduce unemployment','It rises 0.4 point; structural mismatch is outside the natural rate','It stays unchanged; only recessions can move the natural rate'],
 'The natural rate includes both structural and frictional unemployment. Its predicted change is -1 + 0.4 = -0.6 percentage point. The net estimate is conditional on the two stated mechanisms, not a guarantee about every retraining policy.','C/D: conditional natural-rate recommendation with competing components.', [('change','-1+.4',-.6)])
add(nl('ELITE-379'),'Two economies each have 5% natural unemployment. One combines 1% frictional and 4% structural unemployment; the other combines 3% frictional and 2% structural. Which policy comparison fits these equal totals?',
 ['The first has more mismatch to address; the second has more scope for faster matching, holding effectiveness comparable','The same natural rate proves their underlying labor-market problems are identical','Only the second has natural unemployment because frictional unemployment is the sole component','Both can reach zero unemployment simply by ending a recession'],
 'Both totals equal 5%, but the components differ. A common aggregate benchmark does not establish identical barriers or identical policy priorities. Relevant retraining and matching interventions target different components.','C: infer differing policy needs from the same natural-rate total.')
