import json,hashlib,unicodedata
from pathlib import Path
W=Path(__file__).resolve().parent;b=json.loads((W/'inventory-before.json').read_text('utf8'))['records'];s={}
def norm(x):return ' '.join(unicodedata.normalize('NFKC',x).lower().split())
def opts(i):
 q=b[i];a=next(o for o in q['options'] if hashlib.sha256(norm(o).encode()).hexdigest()==q['aHash']);return [a]+[o for o in q['options'] if o!=a]
def put(i,q,o,f,r,n=False):
 assert i in b and i not in s;s[i]=dict(q=q,options=o,feedback=f,reason=r,numeric=n)
def tweak(i,q,f,r,n=False):put(i,q,opts(i),f,r,n)
put('P52B-S1-LRPC-EL-001','Assume a fixed natural rate, no supply shocks, and an unchanged Phillips slope. Each year expected inflation equals the previous year’s actual inflation. Policy keeps unemployment the same fixed distance below natural. What must happen to actual inflation and the inflation surprise?',
 ['Actual inflation rises each year, but the required positive surprise can remain constant.','Both actual inflation and the size of the positive surprise must rise each year.','Actual inflation stays fixed while expected inflation falls each year.','Actual and expected inflation can remain equal while unemployment stays below natural.'],
 'With an unchanged slope and unemployment gap, the required actual-minus-expected inflation gap is constant. Because expectations catch up to the previous actual rate, actual inflation must rise again by that same amount. Ever-higher inflation does not require ever-larger forecast errors.',
 'Correct confusion between rising inflation levels and an increasing inflation-surprise gap.')
tweak('PM2A-LRPC-L-009',b['PM2A-LRPC-L-009']['q'].replace('Which path is consistent','The repeated expansions then stop and actual inflation stabilizes at its higher rate. Which subsequent path is consistent'),b['PM2A-LRPC-L-009']['feedback']+' Return to natural is conditional on ending the repeated effort to maintain a surprise.','State the policy change needed for the asserted natural-rate endpoint.')
put('PM2A-SRPC-LB-015','A government maintains a fixed unemployment gap below the natural rate through successive demand expansions. Expectations adapt to observed inflation, the Phillips slope is unchanged, and no supply or structural shock occurs. Which distinction explains why a permanently higher but stable inflation rate is insufficient?',
 ['Maintaining the gap requires continuing positive inflation surprises; once inflation stabilizes and expectations catch up, unemployment returns toward natural.','Maintaining the gap requires only a one-time increase in inflation; expectations adjustment then preserves the lower unemployment.','Maintaining the gap shifts LRPC left even though the prompt holds labor-market structure fixed.','Maintaining the gap requires falling actual inflation while expected inflation rises.'],
 'A fixed below-natural unemployment gap requires a positive actual-minus-expected inflation gap. Adaptive expectations catch up to a stable inflation rate, eliminating that gap. Continued surprises and a return to natural are alternative policy paths, not simultaneous endpoints.',
 'Resolve the contradiction between a continuously maintained unemployment target and unconditional natural-rate return.')
for i in ['ECON-SP-EASY-70','ECON-SP-MEDIUM-162']:
 tweak(i,b[i]['q'].replace('Refer to the SRPC graph.','Refer to the SRPC graph. Assume supply conditions and the natural rate are unchanged; only expected inflation can shift the curve.'),b[i]['feedback']+' With other shifters explicitly excluded, the upward shift identifies higher expected inflation.','Exclude other SRPC shifters before identifying expectations from graph position.')
tweak('PM2A-EXP-LB-013',b['PM2A-EXP-LB-013']['q'],'The supply shock first shifts SRPC upward even with expectations unchanged. Incorporating the higher observed inflation into contracts adds an expectations-driven upward shift. This reinforces inflation pressure rather than describing the disappearance of a demand-created unemployment gain.','Replace borrowed demand-boom feedback with the actual two-stage adverse-supply mechanism.')
put('ECON-SP-LEGENDARY-9008','Refer to the LRPC graph. Compare two disinflations from b to the lower sustained inflation rate I1 with supply conditions and natural unemployment unchanged. In one, existing contracts keep expected inflation at I2 initially. In the other, a credible announcement and immediate contract adjustment lower expected inflation to I1 before spending adjusts. Which pair of paths is consistent with these assumptions?',
 ['The first can pass through d before c; the second can reach c without the same initial unemployment excursion.','Both must pass through d because credibility cannot change expected inflation before actual inflation falls.','The first reaches c immediately; the second must shift LRPC right before inflation can fall.','Both finish at a because lower inflation permanently lowers natural unemployment.'],
 'With old expectations, lower actual inflation moves b to d along SRPC2 before expectations shift the curve down toward c. If expectations and contracts already incorporate I1, the lower SRPC can support c without that initial gap. Credibility alone would not guarantee this outcome without the stated contract adjustment.',
 'Specify the timing assumptions and compare delayed versus immediate expectations adjustment instead of forcing one path from credibility alone.')
for i,expansion in [('PG5-PC-H-016',True),('PG5-PC-H-022',False)]:
 put(i,'Refer to the graph with points A and B on SRPC0. The natural rate and supply conditions are unchanged, and inflation expectations have not yet adjusted. '+('Consumer spending unexpectedly strengthens.' if expansion else 'Planned investment unexpectedly contracts.')+' Which interpretation links the demand event to the graph and distinguishes current unemployment from its natural rate?',
 [ ('The economy moves A to B along SRPC0; unemployment is 2 percentage points below natural while inflation is 1 percentage point higher.' if expansion else 'The economy moves A to B along SRPC0; unemployment is 2 percentage points above natural while inflation is 1 percentage point lower.'),
 'The economy shifts to a different SRPC because any change in actual inflation changes expectations immediately.',
 ('LRPC shifts left to 3 percent unemployment because stronger demand permanently improves matching.' if expansion else 'LRPC shifts right to 7 percent unemployment because weaker demand permanently worsens matching.'),
 ('The economy moves B to A because stronger demand reduces inflation and raises unemployment.' if expansion else 'The economy moves B to A because weaker demand raises inflation and reduces unemployment.')],
 ('A is (5,2.5) and B is (3,3.5).' if expansion else 'A is (5,2.5) and B is (7,1.5).')+' A demand change with expectations and supply fixed moves along SRPC0. Compare the unemployment coordinate with LRPC at 5, and compare inflation with A; the cyclical gap does not move natural unemployment.',
 'Strengthen an existing Hard graph recognition item with supplied AD transfer, coordinate differences and natural-rate distinction.',True)
for i,high in [('PG5-PC-L-018',True),('PG5-PC-L-024',False)]:
 put(i,'Refer to the graph with A and B on SRPC0. Initially expected inflation is the inflation rate at A, and the economy is at B. Next period expected inflation equals this period’s actual inflation. Hold the natural rate and supply conditions fixed; each one-point expectations change shifts the SRPC vertically by one point with slope unchanged. Compare keeping unemployment at B’s rate with instead keeping actual inflation at B’s current rate. Which next-period outcome follows?',
 [ ('Keeping unemployment at 3 percent requires 4.5 percent inflation; holding inflation at 3.5 percent instead returns unemployment to 5 percent.' if high else 'Keeping unemployment at 7 percent requires 0.5 percent inflation; holding inflation at 1.5 percent instead returns unemployment to 5 percent.'),
 ('Keeping unemployment at 3 percent requires unchanged 3.5 percent inflation; holding inflation fixed shifts LRPC to 3 percent.' if high else 'Keeping unemployment at 7 percent requires unchanged 1.5 percent inflation; holding inflation fixed shifts LRPC to 7 percent.'),
 ('Keeping unemployment at 3 percent requires 2.5 percent inflation; holding inflation at 3.5 percent raises unemployment to 7 percent.' if high else 'Keeping unemployment at 7 percent requires 2.5 percent inflation; holding inflation at 1.5 percent lowers unemployment to 3 percent.'),
 'Both targets give the same unchanged point B because adaptive expectations cannot shift an SRPC.'],
 ('Expectations rise from 2.5 to 3.5, shifting the curve up one point. At unemployment 3, inflation therefore rises from 3.5 to 4.5.' if high else 'Expectations fall from 2.5 to 1.5, shifting the curve down one point. At unemployment 7, inflation therefore falls from 1.5 to 0.5.')+' Alternatively, actual inflation equal to the new expectation gives natural unemployment at 5. A fixed unemployment target and a fixed inflation target are different continuations.',
 'Replace inconsistent fixed-point/return feedback with a two-policy adaptive-expectations comparison.',True)
put('PG5-PC-L-006','Refer to the graph with SRPC0, SRPC1, A and B. Use the model inflation = expected inflation − 0.6 × (unemployment − 5) + supply offset, with all rates in percent and differences in percentage points. At B the separately measured supply offset is +1.1 points. What expected inflation is consistent with B, and could the graph alone identify that expectation if the supply offset were unknown?',
 ['Expected inflation is 5.5 percent; without the supply-offset measurement, only expected inflation plus the offset is identified.','Expected inflation is 6 percent; actual inflation equals expectations at every point on an SRPC.','Expected inflation is 6.6 percent; the supply offset can be ignored even though it is positive.','Expected inflation is 4.3 percent; both the unemployment gap and the supply offset must be subtracted from actual inflation.'],
 'B has unemployment 6 and actual inflation 6. Thus 6 = expected inflation − 0.6 + 1.1, implying expected inflation 5.5. Without the offset measurement the graph identifies only expected inflation + offset = 6.6. The higher curve does not by itself isolate an expectations change.',
 'Deepen a simple upper graph reading into reverse expectations inference and an identification limit.',True)
put('PG5-PC-L-012','Refer to the graph with A on SRPC0 and LRPC. Later observations show unemployment at A’s rate but persistently higher inflation. One analyst says the SRPC must have become vertical; another says the same vertical LRPC can coexist with a higher SRPC after contracts adjust. Which additional evidence would support the second interpretation?',
 ['Wage-setting expectations have risen to match the sustained inflation while labor-market structure and supply conditions are unchanged.','Inflation rose once, which by itself proves that expectations already adjusted fully.','Current unemployment equals the natural rate, which requires every SRPC to be vertical.','The price level is higher, which proves that the natural unemployment rate permanently fell.'],
 'An unchanged natural rate locates the same LRPC. Evidence that expected inflation caught up, with other shifters held fixed, supports a higher SRPC crossing it. Equal unemployment and a higher inflation observation alone do not establish the expectations mechanism.',
 'Replace curve-name recognition with a conditional evidence test within the same primary Phillips skill.')
put('P52B-S1-LRPC-L-002','A matching reform lowers the natural unemployment rate from 6.4 percent to 5.6 percent. At the same time, an unexpected demand expansion lowers actual unemployment to 4.9 percent. Later inflation expectations fully adjust while the reform remains in place and no new surprises occur. Which decomposition separates the durable change from the initial cyclical change?',
 ['LRPC shifts left by 0.8 percentage point; the initial gap is 0.7 point below the new natural rate, and long-run unemployment returns to 5.6 percent.','LRPC shifts left by 1.5 percentage points; actual unemployment at 4.9 percent is the new permanent natural rate.','LRPC stays at 6.4 percent; both the reform and demand expansion are temporary movements along SRPC.','LRPC shifts to 5.6 percent, but expectations adjustment permanently fixes unemployment at 4.9 percent.'],
 'The structural shift is 6.4 − 5.6 = 0.8 percentage point. Actual unemployment is temporarily 5.6 − 4.9 = 0.7 point below the new natural rate. Once the demand surprise disappears, the long-run anchor is 5.6, not the old 6.4 or temporary 4.9.',
 'Add simultaneous structural and demand effects with distinct long-run and cyclical components; no exam demographic scenario is reused.',True)
put('PM2A-EXP-FB-008','Under rational expectations, wage setters use available information, including credible policy announcements; forecasts can still be wrong when new information arrives. A credible lower-inflation target changes their forecasts before much demand contraction occurs, but some contracts remain fixed. Which assessment follows?',
 ['The SRPC can shift downward sooner, reducing the transition cost, while fixed contracts can leave some temporary unemployment increase.','Rational expectations guarantee exact forecasts and eliminate every unemployment cost even with fixed contracts.','Expected inflation must wait for past inflation to decline because announcements cannot enter a forecast.','A credible nominal target permanently shifts LRPC left even when labor-market structure is unchanged.'],
 'Available-information forecasting can incorporate credible policy news before actual inflation falls. It does not imply perfect foresight or instantly flexible contracts. Earlier expectations adjustment can reduce disinflation costs without guaranteeing zero costs.',
 'Apply the selected credibility skill at Hard using accurate rational-expectations and contract assumptions.')
put('PM2A-EXP-L-002','A temporary supply disruption raises inflation. Wage setters update forecasts using the observed inflation, but the disruption ends before the new contracts take effect. Expected inflation nevertheless remains above its original level. With natural unemployment unchanged, what can be concluded about the final SRPC relative to its original position and its position during the disruption?',
 ['It remains above its original position, but its position relative to the disruption-period curve depends on the expectations rise versus the removed supply offset.','It must return exactly to its original position because the physical disruption ended.','It must lie above the disruption-period curve because any expectations rise exceeds any removed supply offset.','It must lie below the original curve because the original supply shock was temporary.'],
 'The original curve has neither the supply offset nor the higher expectation. The final curve retains only the expectation increase, so it is above the original. Comparing it with the disruption-period curve requires the two offset magnitudes. Observed inflation alone does not identify their relative sizes.',
 'Deepen repeated expectations recognition into supply reversal and residual expectations identification.')
put('ECON-SP-LEGENDARY-9047','Refer to the LRPC graph. The economy has moved b to d during disinflation. Inflation is then held at I1, the natural rate stays U2, and the adverse-supply offset is unchanged. A forecast shows unemployment returning to U2. Which evidence is necessary to reconcile this forecast with the diagram?',
 ['Expected inflation must fall enough to place an SRPC through c; contraction along unchanged SRPC2 would leave unemployment at d.','Expected inflation must rise enough to place an SRPC above SRPC2 while actual inflation remains I1.','The return requires moving from d to b along unchanged SRPC2 while inflation remains I1.','The return requires LRPC to shift right to U3 even though the natural rate stays U2.'],
 'At I1 the original SRPC2 locates d, not c. With natural unemployment and the supply offset fixed, a lower expected-inflation schedule is needed to reach c at U2. A forecast of unemployment recovery is therefore conditional on the expected-inflation adjustment, not just continued contraction.',
 'Make a repeated graph endpoint into a forecast-consistency test with confounding shifters excluded.')
for i,oldtext,newtext in [
 ('PM2A-SAC-H-010','Potential GDP is $500 billion.','Potential GDP remains $500 billion in each of the three years.'),
 ('PM2A-SAC-LB-025','Potential output is $800 billion. A policy creates gaps of 1.5% for two years and 0.5% for one year','Potential output remains $800 billion each year. Actual output is below potential by 1.5% for two years and 0.5% for one year'),
 ('ECON-SP-ELITE-331','If output loss is 14 percent','If cumulative output loss is 14 percent of one year’s potential GDP'),
 ('PM2A-SAC-FB-020','Annual output gaps are','Use the sum of annual percentage output shortfalls as the cumulative-loss convention. Annual output gaps are')]:
 tweak(i,b[i]['q'].replace(oldtext,newtext),b[i]['feedback'],'Clarify the cumulative-loss, below-potential or constant-output benchmark needed for numerical interpretation.',True)
put('ECON-SP-LEGENDARY-9020','A disinflation lowers inflation from 10 percent to 6 percent. Cumulative output loss is 18 percent of one year’s potential GDP, of which 11 percent occurred before the final year. An analyst reports a sacrifice ratio using only the final-year loss. Which audit correction is needed?',
 ['Use all 18 percent: the ratio is 4.5; using only the final year would understate it as 1.75.','Use only 7 percent: the ratio is 1.75 because earlier output losses are already over.','Use the final inflation rate: the ratio is 3 because the target is 6 percent.','Add initial and final inflation: the ratio is 1.125 because the full window contains both rates.'],
 'The inflation reduction is 4 percentage points. Cumulative loss gives 18/4 = 4.5. Final-year loss is 18 − 11 = 7, giving 7/4 = 1.75 if earlier losses are wrongly omitted. Returning toward potential does not erase earlier lost production.',
 'Replace one division and an unsupported costly label with a time-window audit and cumulative-loss reconciliation.',True)
put('ECON-SP-LEGENDARY-9049','A disinflation lowers inflation from 9 percent to 5 percent with cumulative output loss of 10 percent of one year’s potential GDP. A second plan is projected to lower inflation by only 2.5 percentage points with loss of 7 percent on the same output benchmark. Which comparison avoids confusing a smaller total loss with a lower loss per inflation point?',
 ['The completed plan has ratio 2.5 versus 2.8 for the second; the second has less total loss but a higher loss per point.','The second plan has the lower ratio because 7 is less than 10, regardless of the inflation reductions.','Both have ratio 2.5 because the second plan’s inflation reduction is its denominator and also its ratio.','The completed plan has ratio 0.4 and therefore no output cost; the second has ratio 2.8.'],
 'The completed reduction is 9 − 5 = 4 points, so 10/4 = 2.5. The second ratio is 7/2.5 = 2.8. A lower cumulative cost can accompany a higher per-point cost when the inflation reductions differ; neither statistic alone proves a universally better policy.',
 'Remove the unbenchmarked not-extreme judgment and compare total versus normalized costs.',True)
put('ECON-SP-LEGENDARY-9021','A plan must reduce inflation by 5 percentage points with cumulative output loss no greater than 14 percent of one year’s potential GDP. Its first stage has already reduced inflation by 2 percentage points at a cumulative loss of 7 percent. What maximum sacrifice ratio can the remaining stage have if the full plan is to meet both targets?',
 ['About 2.33 percent of one year’s output per remaining inflation point.','2.8 percent of one year’s output per remaining inflation point.','3.5 percent of one year’s output per remaining inflation point.','7 percent of one year’s output per remaining inflation point.'],
 'There are 3 inflation points and 7 percent of output-loss allowance remaining. The remaining-stage ceiling is 7/3 = 2.333..., about 2.33. Applying the overall allowance ratio 14/5 = 2.8 to the remaining stage would exceed the total loss limit because the first stage used more loss per point.',
 'Deepen forward multiplication into an inverse remaining-stage constraint.',True)
put('ECON-SP-LEGENDARY-9050','Two stages jointly reduce inflation by 6 percentage points with a combined sacrifice ratio of 1.75. The first stage loses 3 percent of one year’s potential GDP while reducing inflation by 2 percentage points. Use the same output benchmark for both stages. What is the second-stage ratio, and how does it compare with the first?',
 ['1.875 for the second versus 1.5 for the first; the second has the higher loss per point.','1.75 for both stages, because a combined ratio must equal each stage’s ratio.','3.75 for the second versus 1.5 for the first, using only 2 remaining inflation points.','0.533 for the second versus 0.667 for the first, using inflation reduction divided by loss.'],
 'Total loss is 6 × 1.75 = 10.5 percent. The second stage accounts for 10.5 − 3 = 7.5 percent loss and 6 − 2 = 4 inflation points, giving 1.875. The first-stage ratio is 3/2 = 1.5. The combined ratio is weighted by the reductions, not a mandate for equal stage ratios.',
 'Replace simple multiplication with a reverse stage decomposition and ratio comparison.',True)
s['PM2A-EXP-L-002']['q']=s['PM2A-EXP-L-002']['q'].replace('A temporary supply disruption raises inflation.','A temporary supply disruption raises inflation while existing contracts still reflect the original expected inflation.')
s['PG5-PC-L-024']['q']='Refer to the graph with B to the right of A on SRPC0. Initially actual inflation is B’s rate and expected inflation is A’s rate. Each period expectations equal the previous period’s actual inflation; each one-point expectations change shifts SRPC vertically by one point with slope unchanged. Natural unemployment and supply conditions stay fixed. Policy holds unemployment at B’s rate for one additional period, then requires inflation to be nonnegative in the following period. What inflation occurs in the additional period, and what is the highest unemployment rate compatible with that later inflation constraint?'
s['PG5-PC-L-024']['options']=['Inflation is 0.5 percent, then unemployment can be at most 6 percent.','Inflation stays 1.5 percent, then unemployment can remain at 7 percent.','Inflation is 0.5 percent, then unemployment can remain at 7 percent without deflation.','Inflation is 2.5 percent, then unemployment can be at most 5 percent.']
s['PG5-PC-L-024']['feedback']='The plotted slope is (1.5 − 2.5)/(7 − 5) = −0.5. Expectations first fall from 2.5 to 1.5, so holding unemployment at 7 gives inflation 0.5. Next expectations are 0.5; nonnegative inflation requires 0.5 − 0.5 × (unemployment − 5) ≥ 0, or unemployment no greater than 6. Maintaining 7 would instead produce −0.5 percent inflation.'
s['PG5-PC-L-024']['reason']='Replace fixed-unemployment/return inconsistency with a multi-period adaptive-expectations path and a no-deflation constraint.'
tweak('ECON-SP-HARD-246','In the standard expectations-augmented Phillips model with no supply-shock offset, actual inflation equals expected inflation. What does the equation imply about unemployment?',b['ECON-SP-HARD-246']['feedback']+' The no-offset assumption matters: an independent supply shock can also affect the relationship.','State the zero-supply-offset condition needed to infer natural unemployment from zero inflation surprise.')
for i,rises in [('ECON-SP-HARD-263',True),('ECON-SP-HARD-264',False)]:
 tweak(i,'Initially actual inflation equals expected inflation and unemployment is at its natural rate. Supply conditions and the natural rate stay unchanged. If expected inflation '+('rises' if rises else 'falls')+' while actual inflation is held at its original rate, what happens to unemployment?',b[i]['feedback']+' The stated initial equality makes the new inflation surprise '+('negative' if rises else 'positive')+'.','Supply the missing initial position before asserting that an expectations change crosses the natural unemployment rate.')
(W/'revisions.json').write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n','utf8');print(len(s),'content revisions;',sum(x['numeric'] for x in s.values()),'quantitative')
