import json
from pathlib import Path
W=Path(__file__).resolve().parent;b=json.loads((W/'inventory-before.json').read_text('utf8'));rows=[]
findings={
'short-run-phillips-curve':('B,F','Basic axes and demand movement are well covered. Some ordinary Hard graph records repeat Easy/Medium comparisons; strengthen two existing Hard applications without retagging. Full demand/expectations sequences already occur by Hard elsewhere in the five-concept selection. Upper recognition and repeated expansion endpoints need targeted depth and explicit policy assumptions.'),
'long-run-phillips-curve':('D,F','Vertical LRPC, matching and structural natural-rate changes are covered by Hard. P52B-S1-LRPC-EL-001 incorrectly requires ever-larger inflation surprises: with a fixed unemployment gap and adaptive last-period expectations, a constant positive surprise implies ever-higher inflation. Some prompts hold unemployment below natural indefinitely but then assert a natural-rate endpoint without a policy change. Upper natural-rate/graph recognition can be strengthened.'),
'phillips-curve-expectations':('D,F','Hard already traces graph expectation adjustment and distinguishes adverse supply from demand movement. Two graph prompts infer expectations alone without excluding other SRPC shifters. Supply-shock feedback PM2A-EXP-LB-013 incorrectly borrows a temporary unemployment-gain explanation. Credibility is well covered; explicit rational-expectations terminology is absent, while adaptive expectations appears in a Hard checkpoint. Apply available-information reasoning within the selected credibility skill, without assuming perfect forecasting or adding a separate objective. Upper graph tasks often repeat simple readings.'),
'disinflation-and-policy':('D,F','Hard already includes b-to-d-to-c, credibility/contract lags, cumulative-cost comparison and eventual adjustment. A credible-announcement Legendary prompt forces delayed adjustment without stating contract timing; clarify and compare alternatives. Repeated upper graph sequences and one-step cost comparisons can support inverse or conditional analysis.'),
'sacrifice-ratio':('D,F','Medium/Hard already contain straightforward, reverse, cumulative, currency-conversion and path-comparison arithmetic. No calibration or coverage deficit: independently verify every numerical sacrifice-ratio item. Clarify cumulative output units, constant potential GDP and positive loss magnitudes where missing. Selected upper single-division items need inverse time-window, budget or comparison reasoning; avoid unsupported labels such as not extreme without a benchmark.')}
for c,m in b['views'].items():
 for o,n in b['byConcept'][c]['objectives'].items():
  codes,why=findings[c];qs=[q for q in b['records'].values() if q['primaryConceptId']==c and q['objective']==o]
  rows.append(dict(concept=c,objective=o,label=m['objectiveLabels'].get(o,o),count=n,classifications=codes.split(','),finding=why,coverageGap=False,evidenceIds=[q['id'] for q in qs if q.get('canonicalDifficulty') in ['hard','elite','legendary']][:8]))
(W/'objective-findings-before.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n','utf8')
(W/'OBJECTIVE_FINDINGS_BEFORE.md').write_text('# Objective findings before authorship\n\nAll 262 records have been read. All six distinct registered images were visually inspected; eleven registrations match those files. All 42 legacy failures map to existing assets. No production edits have been made.\n\n'+ '\n\n'.join(f"## {r['concept']} / {r['objective']}\n\n{r['count']} records; {','.join(r['classifications'])}. {r['finding']}" for r in rows)+'\n\nNo A, C or E gap is asserted. Local shallow Hard graph variants justify targeted robustness improvement; whole-selection Hard already provides exam-level chains.\n','utf8')
print(len(rows),'objective findings saved')
