import json,hashlib,copy,re,unicodedata
from pathlib import Path
from collections import Counter
W=Path(__file__).resolve().parent;R=Path(r'C:\Users\Jennings\Documents\GitHub\masteryquests-website\build\faculty-build-composer');REPO=R.parent.parent
def rd(n):return json.loads((W/n).read_text('utf8'))
def wr(n,x):(W/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n','utf8')
def sha(x):return hashlib.sha256(x).hexdigest()
def norm(s):return ' '.join(unicodedata.normalize('NFKC',s).lower().split())
def key(q):return next(o for o in q['options'] if sha(norm(o).encode())==q['aHash'])
def loc(m):return [(p,q) for p,qs in m['questions'].items() for q in qs]+[(p,q) for p in ['repairQuestions','repairSeedQuestions','bridgeQuestions'] for q in m.get(p,[])]
b=rd('inventory-before.json');a=rd('inventory-after.json');old=rd('library-baseline.json');new=rd('library-after.json');cs=rd('concepts.json');s=rd('revisions.json');v=rd('validation.json');acc=rd('accounting.json');actions=rd('record-actions.json');browser=rd('browser-validation.json');before=rd('quality-before.json');after=rd('quality-after.json');obj=rd('objective-findings-before.json');mask=rd('overlap-mask.json')
for c in old['concepts']:
 if c not in cs:assert old['concepts'][c]==new['concepts'][c],c
allowed={'concepts','assetInventory','registry','librarySha256'};assert {k:x for k,x in old.items() if k not in allowed}=={k:x for k,x in new.items() if k not in allowed}
assert {k:x for k,x in old['registry'].items() if k!='librarySha256'}=={k:x for k,x in new['registry'].items() if k!='librarySha256'}
def strip(x):return [{k:v for k,v in q.items() if k not in ['imageAlt','graphDescription']} for q in x]
assert strip(old['assetInventory'])==strip(new['assetInventory'])
for name in ['composer_registry.json','composer_library_manifest.json']:
 x=json.loads((R/'data'/name).read_text('utf8'));y=rd('staged/'+name)
 for z in [x,y]:
  z.pop('librarySha256')
  if 'assets' in z:z['assets']=strip(z['assets'])
 assert x==y,name
n=copy.deepcopy(new);del n['librarySha256'];del n['registry']['librarySha256'];semantic=sha(json.dumps(n,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode());assert semantic==new['librarySha256']
wr('semantic-validation.json',dict(before=old['librarySha256'],after=semantic,independentlyRecomputed=True,sidecarsSynchronized=True))
reviews=[]
for x in b['conceptReview']['assets']:
 assert sha((R/x['sourcePath']).read_bytes())==x['sha256'];reviews.append({**x,'bytesVerified':True})
for p,h in b['sourceFiles'].items():assert sha((R/p).read_bytes())==h,'Source changed since snapshot '+p
arch=dict(all262RecordsStructurallyChecked=True,all144UnselectedDefinitionsUnchanged=True,allIdsDifficultyObjectivesSkillsTagsProvenanceAndAliasesPreserved=True,orderedPoolsRepairBridgeCheckpointsRetestAndEligibilityPreserved=True,reviewRoutesPreserved=True,reviewAssets=reviews,reviewRuntimeIndex=b['conceptReview']['runtimeIndex'],reviewGlobalWarnings=b['conceptReview']['warnings'],parentPresetValidation=rd('parent-preset-validation.json'),priorAuditArtifactFilesBeforeApply={},baselineSourceFiles=b['sourceFiles'],finalSourceFiles=a['sourceFiles'])
for folder,x in mask['priorAudits'].items():
 assert not x['sharedIds'];assert all(old['concepts'][c]==new['concepts'][c] for c in x['concepts']);p=REPO/'validation_artifacts'/folder
 arch['priorAuditArtifactFilesBeforeApply'][folder]={str(f.relative_to(p)):sha(f.read_bytes()) for f in p.rglob('*') if f.is_file()}
wr('architecture-validation.json',arch)
graphs=browser['graphChecks'];assert len(graphs)==66 and all(all(x[k] for k in ['loaded','zoomOK','description','text','embeddedImages']) for x in graphs)
checks={x['id']:x for x in graphs};paths=[]
for x in rd('known-graph-failures-before.json'):
 i=x['id'];q=a['records'][i];assert q['image']==x['registeredRuntimePath'];assert sha((R/'data'/q['image']).read_bytes())==x['assetSha256'];assert checks[i]['loaded'] and checks[i]['zoomOK'] and checks[i]['description']
 paths.append({**x,'status':'fixed','finalImage':q['image'],'fileExists':True,'originalImageBytesPreserved':True,'imageLoaded':True,'enlargementWorks':True,'descriptionDelivered':True})
assert len(paths)==42 and len({x['id'] for x in paths})==42
wr('path-repair-validation.json',dict(previouslyKnown=42,fixed=42,notActuallyBroken=0,unresolved=0,items=paths))
wr('graph-validation.json',dict(registeredAssetsInspected=11,distinctImagesInspected=6,all66RecordsRenderedAndEnlarged=True,imageBytesChanged=0,newImages=0,trialGraphBeforeAfter=[24,24],graphLinkedBeforeAfter=[66,66],checks=graphs,accessibilityInspection=rd('accessibility-inspection.json'),limitation='Local generated-game rendering and enlargement test with external requests blocked; no remote CDN or full gameplay-branch claim.'))
bf={(x['questionId'],x['rule']):x for x in before['findings']};af={(x['questionId'],x['rule']):x for x in after['findings']};dispositions=[]
for pair in sorted(bf.keys()|af.keys()):
 i,rule=pair;f=af.get(pair,bf.get(pair));q=a['records'][i];status='retained' if pair in bf and pair in af else 'newly-reported' if pair in af else 'no-longer-reported'
 if rule=='graph-accessibility-insufficient':reason='Fixed: legacy image path now resolves to the existing registered asset and its complete verified evidence description. Browser confirms image, enlargement and description delivery.'
 elif status=='no-longer-reported':reason=s.get(i,{}).get('reason','The corrected contract or reference removes the flagged condition.')
 elif rule=='image-without-graph-required':reason='The existing graphRequired/eligibility flag remains false. The image now renders and its description is delivered; conservative Trial-by-Graph membership is intentionally preserved. This is not an unresolved file or description failure.'
 elif rule=='repeated-feedback':reason='The shared feedback is economically applicable to this record, but often gives the family mechanism rather than a tailored worked explanation. Retain the support structure and disclose limited feedback specificity. All numerical instances are separately recomputed.'
 elif rule=='graph-prompt-missing-cue':reason='The attached graph and named points/curves identify the evidence, but an explicit refer-to-graph cue would improve wording. Retained nonblocking clarity limitation; image and evidence delivery pass.'
 elif rule=='near-duplicate-stem':reason='These expectations questions deliberately compare opposite changes from the same stated initial equilibrium: higher expected inflation creates a negative surprise and unemployment above natural, while lower expected inflation reverses both. The shared controlled setup makes them close practice variants; this limited variety is retained, not disguised with cosmetic wording.'
 elif rule=='weak-absolute-distractors':reason='Alternatives encode permanent-versus-temporary effects, omitted expectations, wrong curves or reversed measurement. Some absolute wording is an easy elimination cue; this residual weakness is acknowledged, not declared a false positive.'
 elif rule=='possible-difficulty-overstatement':
  reason='Retained calibration limitation: this is a direct recognition or short graph/mechanism item for its tier. Stronger existing Hard chains and selected upper revisions supply additional demand; no retagging was used to suppress the flag.'
  if i=='PM2A-SAC-H-010':reason='Heuristic false positive: the Hard item aggregates three years of percentage shortfalls, converts using the fixed GDP benchmark and divides by the inflation reduction. Independent computation gives 20 billion cumulative loss and 5 billion per point.'
  if i=='PM2A-SAC-LB-025':reason='Arithmetic is valid and multi-year, but this Legendary checkpoint is still mostly forward aggregation/conversion. Retained at the existing tier with the calibration limitation disclosed; constant GDP and below-potential signs are now explicit.'
 else:raise AssertionError(pair)
 dispositions.append(dict(questionId=i,rule=rule,severity=f['severity'],status=status,reason=reason,stem=q['q'],keyedOption=key(q),options=q['options'],feedback=q['feedback'],auditorMessage=f['message']))
wr('quality-dispositions.json',dict(before=before['counts'],after=after['counts'],method='Unmodified repository auditor over all five direct concepts and every pool. Every original/final record-rule pair has a disposition; warnings are not automatically treated as defects.',findings=dispositions))
es=rd('exam-source.json');assert sha(Path(es['path']).read_bytes())==es['sha256'];exam=(W.parent/'.money-work/exam-text.txt').read_text('utf8')
def grams(x):
 words=re.findall(r'[a-z]+',x.lower());return {' '.join(words[i:i+12]) for i in range(len(words)-11)}
eg=grams(exam);originality=[]
for i,sp in s.items():
 oldtext=' '.join([b['records'][i]['q'],*b['records'][i]['options'],b['records'][i]['feedback']]);newtext=' '.join([sp['q'],*sp['options'],sp['feedback']]);hits=grams(newtext)&eg;novel=hits-grams(oldtext);assert not novel,(i,novel)
 originality.append(dict(id=i,new12WordExamOverlap=0,inheritedOverlap=len(hits),humanTaskComparison='Uses existing library evidence with original identification, stage-budget, adaptive forecast, structural matching or timing constraints; no exam scenario, image or answer pattern was imported.'))
wr('originality-validation.json',dict(exam=es,calibration='Q31–40: temporary tradeoff, LRPC, short/long-run graph chains, rational/adaptive expectations, structural shifts, sacrifice ratio and surprises. Existing exam text/media were reused after byte verification; they are source material, not instructions.',newImages=0,copiedExamImages=0,lexicalMethod='New 12-word overlap screen on all revised stems, choices and feedback plus human task comparison; not a proof of originality.',items=originality))
members={}
for c,m in b['views'].items():
 for p,q in loc(m):members.setdefault(q['id'],[]).append(c+':'+p)
wr('pool-memberships.json',dict(sourceMembershipCount=sum(map(len,members.values())),uniqueCount=262,orderedSourcePools={c:{p:[q['id'] for pp,q in loc(m) if pp==p] for p in dict(loc(m))} for c,m in b['views'].items()},multipleMemberships={i:x for i,x in members.items() if len(x)>1},composedCounts=b['composedCounts'],trialGraphIds=b['routes']['trialGraph']))
hard=[i for i,q in b['records'].items() if q.get('canonicalDifficulty')=='hard' and i not in s];wr('retained-hard.json',[dict(id=i,concept=b['records'][i]['primaryConceptId'],stem=b['records'][i]['q'],keyedOption=key(b['records'][i]),contentUnchanged=True) for i in hard])
wr('logical-validation.json',dict(all262NonemptyStemsFeedback=True,allFourDistinctNormalizedOptions=True,allOneAnswerHashMatch=True,revisedStemsUniqueAcrossLibrary=True,contentRevisions=[dict(id=i,reason=sp['reason'],stem=sp['q'],correct=sp['options'][0],distractors=sp['options'][1:],economicReview='Checked for movement/shift, actual/expected inflation, source of supply shifts, natural-rate versus cyclical outcomes, explicit policy continuation and loss-window/unit consistency.') for i,sp in s.items()]))
acc.setdefault('path-only',0);wr('accounting.json',acc)
def table(headers,rows):return ['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(str(x).replace('|','/').replace('\n',' ') for x in r)+' |' for r in rows]
def section(n,title,*p):return ['',f'## {n}. {title}','',*sum(([x,''] for x in p),[])]
lines=['# Phillips Curve, Expectations & Disinflation — production assessment-quality audit','',
f'The verified scope contains **262 records in five direct concepts**. The bank already has substantial ordinary exam reasoning at Hard. This audit makes **{len(s)} content revisions and 56 accessibility-only revisions**, leaves **178 records unchanged**, and adds or removes none. Path-only records: **0**; all **42 legacy image references** are repaired alongside evidence/content changes.','',
f'All **66 scoped graphs** render, enlarge and deliver descriptions. All **14 revised quantitative records** and **37 sacrifice-ratio items containing numerical information** were independently checked. The auditor reports **{after["counts"]["errors"]} errors, {after["counts"]["warnings"]} warnings and {after["counts"]["reviews"]} review flags**, individually dispositioned. Adaptive architecture and all previously audited modules remain intact. Changes are local; no commit, push, merge or deployment was performed.']
lines+=section(1,'Exact live preset','The current parent quick start remains **`stabilization-policy` — “AD-AS, Fiscal Policy & Stabilization.”** Its full 14-concept selection is preserved in `live-preset.json`. This audit selects only its five Phillips concepts; no new preset is created. The current library, core, sidecars, graph registrations and review routes were verified against the prior completed audit before authorship.')
lines+=section(2,'Exact five selected concepts','All five are direct definitions; no derived parent projection is needed. Legacy objective aliases remain distinct and are not silently renumbered.')
lines+=table(['Concept','Records','Objectives / counts'],[(c,x['unique'],', '.join(f'{o}: {n}' for o,n in x['objectives'].items())) for c,x in b['byConcept'].items()])
lines+=section(3,'Actual record count',f'Expected and independently verified: **262 unique authoritative IDs**. Raw source memberships: **{sum(map(len,members.values()))}**. Calculation records are routed into canonical difficulty banks during composition and are not additional unique items. All five definitions matched the prior deferred snapshot exactly before this audit. Initial semantic hash: `{old["librarySha256"]}`.')
lines+=section(4,'Curricular boundary','Selected skills cover SRPC movement/shift, vertical LRPC, natural-rate changes, actual/expected/unexpected inflation, adaptive updating, credibility, contract adjustment, disinflation paths, sacrifice ratios and AD-AS transfer. Rational-expectations reasoning was present through credibility/information effects but not explicitly named; a targeted existing Hard credibility question now states the available-information framework without equating it to perfect forecasting.','The live selected skills define scope. Underlying monetary tools/transmission, AD-AS/fiscal mechanisms, loanable funds, Open Economy, Micro and Managerial modules are protected. No hysteresis, new monetary machinery or advanced estimation objective was imported.')
lines+=section(5,'Prior-audit protections','All 144 nonselected concept definitions remain identical. This includes the 466 core AD-AS/fiscal records in nine modules, the 818 Money/Banking records in 13 modules and the 268 Saving/Investment records in seven modules. Each mask has zero shared authoritative IDs with these five concepts. Current modules matched the completed prior snapshots; all three prior artifact directories are hash-guarded. No cross-model exception outside Phillips scope was needed.')
lines+=section(6,'Before/after accounting','The mutually exclusive dispositions below sum to 262. A content revision may also repair an image and accessibility. A legacy reference plus evidence correction is counted as accessibility-only if the stem/key/options/feedback are unchanged; it is not also counted as path-only. `record-actions.json` dispositions every ID; `accounting.json` supplies all grouped counts.')
lines+=table(['Disposition','Count'],[('Before / after','262 / 262'),('Added / removed','0 / 0'),('Content revised',28),('Accessibility only',56),('Path only',0),('Unchanged',178),('Image references repaired',42),('Unresolved image references',0)])
lines+=['']+table(['Concept','Content','Accessibility only','Path only','Unchanged'],[(c,x['content-revised'],x['accessibility-only'],x['path-only'],x['unchanged']) for c,x in acc['byConcept'].items()])
lines+=section(7,'Difficulty counts','Source and canonical difficulty values, including capitalization and support roles, remain unchanged. Thirty-one repair/bridge records have no canonical difficulty and remain “unknown”; no artificial tier assignment was made. Ordinary Hard contains 41 records; checkpoint canonical-Hard records are counted separately in the canonical distribution below.')
lines+=table(['Canonical difficulty','Before = after','Content changes'],[(d,n,acc['byCanonicalDifficulty'][d]['content-revised']) for d,n in b['difficulty'].items()])
lines+=['']+table(['Source difficulty','Before = after'],b['sourceDifficulty'].items())
lines+=section(8,'Types and pools','Ordinary banks total 171 records; ordinary checkpoints total 45; Legendary checkpoints 15; repair 15; bridge 16. Four calculation-pool records are routed into their existing ordinary tiers. Repair seeds, integration and challenge pools are empty, a structural boundary rather than a missing-content finding.')
lines+=table(['Composed pool','Before = after'],[(p,b['composedCounts'][p]) for p in ['easy','medium','hard','elite','legendary','easyBoss','mediumBoss','finalBoss','legendaryBoss','repair','repairSeed','bridge','calculation','integration','challengeTotal']])
lines+=['']+table(['Type','Before = after','Content changes'],[(t,n,acc['byType'][t]['content-revised']) for t,n in b['types'].items()])
lines+=section(9,'Objective-by-objective findings','All 15 concept/objective pairs are recorded below with actual labels (the code itself where a descriptive label is absent). A coverage; B robustness; C calibration; D calculation/integration; E graph-use; F upper synthesis; G no material gap. These immutable BEFORE findings preceded content authoring. Subsequent checks also identified the need for explicit initial equilibrium/zero-supply-offset assumptions in three expectations items.')
lines+=table(['Concept / objective — label','Count','BEFORE classes','Finding','Content changes'],[(x['concept']+' / '+x['objective']+' — '+x['label'],x['count'],','.join(x['classifications']),x['finding'],sum(z['action']=='content-revised' and z['concept']==x['concept'] and z['objective']==x['objective'] for z in actions)) for x in obj])
lines+=section(10,'Coverage gaps','No selected objective was materially absent; no A gap or new record was justified. Rational expectations lacked the name, but its selected credibility/information application already existed. Clarifying that framework in an existing Hard question does not add a new objective. Absent advanced extensions are boundaries.')
lines+=section(11,'Robustness gaps','Some Hard SRPC graph items merely duplicated easier coordinate comparisons. Two are strengthened with a supplied demand determinant, curve classification, percentage-point differences and the natural-rate distinction. Repeated upper expectations and single-arithmetic forms receive selective inverse/conditional tasks. Simpler retained variants and repeated feedback remain disclosed.')
lines+=section(12,'Calibration gaps','No whole-selection C gap was found: Hard already contains expansion/disinflation graph sequences, expectation adjustment, credibility constraints, structural unemployment and cumulative sacrifice arithmetic. Eight canonical-Hard records are revised for precision or stronger application; none changes tier. The two ordinary graph improvements address local robustness, not a claim that normal exam reasoning was absent from the bank.')
lines+=section(13,'Calculation/integration gaps','The numerical review covers all 37 sacrifice-ratio records containing numerical information, including unchanged calculations, denominators, unit interpretations and a growth-versus-level distinction. Their underlying arithmetic was sound; some assumptions and upper-tier demand needed improvement. Six additional revised graph/natural-rate calculations are independently checked, giving 43 numerical/measurement validation entries in total; all 14 revised quantitative items are included.','Derivations use final-stem inputs and exact fractions or independently transcribed image coordinates, then compare with answers. Hash checks are separate structural checks. Constant potential output, positive loss magnitudes, annual versus cumulative windows and percentage points are explicitly distinguished where needed.')
lines+=section(14,'SRPC findings','With expectations, supply conditions and natural unemployment fixed, demand expansion moves up-left along SRPC; contraction reverses that movement. Supplied demand events are transferred into Phillips reasoning without reopening monetary mechanics. New Hard applications distinguish actual unemployment from the unchanged natural rate and use both axis changes.')
lines+=section(15,'LRPC findings','The vertical LRPC is correctly located at natural unemployment. Demand surprises do not permanently move it; labor-market matching changes can. The accelerationist correction distinguishes a constant required surprise from an ever-higher inflation rate under last-period adaptive expectations. Prompts predicting a return to natural now state when repeated efforts to maintain the below-natural gap stop.')
lines+=section(16,'Expectations findings','Actual inflation alone does not identify expected inflation. Two graph prompts now exclude supply/natural-rate shifts before attributing a curve shift to expectations. Hard 263/264 specify an initial equality of actual and expected inflation before concluding that unemployment crosses the natural rate; Hard 246 explicitly excludes a supply offset.','PG5-PC-L-006 uses B=(6,6), a stated Phillips equation and a measured +1.1 supply offset to infer expected inflation of 5.5. Without that independent measurement, only expected inflation plus the supply offset is identified. The graph does not supply a unique causal diagnosis on its own.')
lines+=section(17,'Adaptive and rational expectations','Adaptive tasks use observed inflation or forecast errors; the new numerical graph continuations explicitly specify one-period updating rather than treating it as a universal adjustment speed. They compare holding unemployment fixed with holding inflation fixed, or impose a later no-deflation constraint.','The revised Hard credibility item states that rational expectations use available information, including credible policy announcements. Forecast errors can occur with new information, and nominal contracts can still delay adjustment. Neither rational expectations nor an announcement alone guarantees perfect forecasting or zero output cost.')
lines+=section(18,'Disinflation findings','The existing Hard b-to-d-to-c sequence already distinguishes movement along SRPC2 from a subsequent downward SRPC shift. The revised Legendary comparison contrasts contracts that retain old expectations with immediate expectations/contract adjustment, making the different transition paths conditional. Another upper item requires a forecast of natural-rate return at fixed inflation to be reconciled with an appropriate lower SRPC. Disinflation remains slower price growth, not necessarily falling prices.')
lines+=section(19,'Sacrifice-ratio findings','The course convention is cumulative output loss relative to potential, expressed as a percentage of an annual output benchmark or a sum of annual percentage shortfalls, divided by the percentage-point inflation reduction. Dollar-loss-per-point tasks remain explicitly dollar-valued, not dimensionless ratios. Different denominators and annual benchmarks are not mixed.','New upper tasks reconcile omitted earlier losses, compare total versus per-point cost, solve a remaining-stage loss ceiling, and infer stage-specific ratios from the combined ratio. Unsupported judgments such as “not extreme” are removed in favor of explicit comparisons. No valid legacy numerical key was reversed solely to increase revisions.')
lines+=section(20,'AD-AS to Phillips integration','Demand-driven output gains map to lower cyclical unemployment and inflation pressure along a fixed SRPC; adverse supply can raise both inflation and unemployment and shift the relationship. The supply-shock feedback correction now describes an initial adverse shift followed by expectations reinforcement, not the disappearance of a demand-created unemployment gain. All underlying AD-AS and fiscal definitions remain unchanged.')
lines+=section(21,'Supply-shock findings','The bank already distinguishes stagflation from movement along a fixed downward SRPC. An upper revision separates a temporary supply offset that disappears from higher expectations that persist after contracts reset. The final curve is above the original, while its position relative to the disruption-period curve needs the relative magnitudes; no unique explanation is inferred from inflation alone.')
lines+=section(22,'Natural-rate findings','The revised matching-reform item separates a 0.8-point structural natural-rate decline from a 0.7-point cyclical gap below the new rate. Long-run unemployment returns to 5.6 percent after the demand surprise ends. It uses an original matching-reform task, not the exam’s demographic scenario. Cyclical recession is not treated as an automatic permanent LRPC shift.')
lines+=section(23,'Graph-use findings','All six distinct image files across 11 selected registrations were visually inspected against current file hashes. Symbolic lrpc.webp and srpc.webp have correct point mappings and detailed descriptions; their metadata was preserved. SRPC-01 through SRPC-04 receive fuller axes, line-coordinate, point and guide evidence. No image byte changed or new graph was created.','All 66 graph-linked records render, enlarge and deliver descriptions in the generated quest. Trial by Graph remains at 24 eligible records: 4 Easy, 8 Medium, 4 Hard, 4 Elite and 4 Legendary. Forty-two graph-linked records retain their existing non-required flags; repairing delivery does not silently expand eligibility.')
lines+=section(24,'Disposition of all 42 known failures','Every prior failure is fixed using its existing per-concept registered asset. No record was dismissed as not actually broken; none remains unresolved. Each final file hash matches the original image bytes and each browser check passes. Full source/final references and tests appear in `path-repair-validation.json`.')
lines+=table(['Question ID','Registered final image','Disposition'],[(x['id'],x['finalImage'],'Fixed; image, enlargement, description pass') for x in paths])
lines+=section(25,'Upper-tier synthesis findings','Selective revisions add: constant-surprise versus rising-inflation reasoning; structural/cyclical decomposition; graph-based reverse expectations with a measured supply offset; multi-period adaptive constraints; temporary supply reversal; two credibility/contract paths; cumulative-window reconciliation; remaining-stage ceilings; and stage-ratio decomposition.','Some retained upper items remain direct, including PG5-PC-X-011, ECON-SP-ELITE-348 and PM2A-SRPC-LB-013. PM2A-SAC-LB-025 remains forward multi-year arithmetic despite clarified assumptions. A mature audit need not replace every usable variant, and this report does not claim uniformly deep upper tiers.')
lines+=section(26,'Strong existing Hard questions retained',f'{len(hard)} canonical-Hard records retain their question content. The complete list is in `retained-hard.json`; some graph records receive evidence/path changes only.')
examples={'ECON-SP-HARD-236':'Expansion followed by expectations adjustment on a graph.','ECON-SP-HARD-237':'Disinflation movement followed by SRPC shift and natural-rate return.','PM2A-LRPC-H-008':'Separate structural matching changes from short-run positioning.','PM2A-EXP-FB-009':'Apply adaptive expectations over repeated forecast errors.','PM2A-EXP-FB-010':'Distinguish a supply shock from expectations-only diagnosis.','PM2A-DIS-H-008':'Compare cumulative transition losses across alternative speeds.','PM2A-SAC-H-011':'Invert sacrifice ratio to recover the inflation reduction.','PM2A-SAC-H-012':'Distinguish GDP growth slowdown from cumulative level shortfall.'};assert all(i in hard for i in examples)
lines+=table(['ID','Why retained'],examples.items())
lines+=section(27,'Specific revisions and reasons','Exact changed fields, before and after, are in `changes.json`. All content revisions are listed below; every other record has a disposition in `record-actions.json`.')
lines+=table(['ID','Objective / canonical difficulty','Reason'],[(i,b['records'][i]['objective']+' / '+b['records'][i].get('canonicalDifficulty','unknown'),sp['reason']) for i,sp in s.items()])
lines+=section(28,'Economic/numerical defects corrected','Corrected the “ever-larger surprises” assertion, incompatible continuous-target/natural-return endpoints, expectations-only graph diagnosis without exclusions, demand-boom feedback on a supply-shock sequence, and missing initial-equilibrium/zero-offset conditions. Credible disinflation now has explicit contract-timing assumptions.','Measurement clarifications establish constant annual potential output, below-potential loss signs and cumulative rather than single-year percentages. Upper numerical replacements are original inverse/comparison tasks; they are not allegations that all prior arithmetic was wrong. Every final quantitative revision has an independent derivation.')
lines+=section(29,'Accessibility and path defects corrected','All 42 legacy references now point to registered per-concept images and receive their correct detailed evidence. Four distinct numerical-graph contracts are expanded across ten concept-level metadata entries. Fifty-six records are accessibility-only, including path repairs; ten graph records also have content revisions. Thus path-only accounting is zero even though 42 paths were corrected.','Descriptions supply axes, labels, coordinates, curve membership and guides, not the expected-inflation or policy conclusion. Existing correct detailed symbolic contracts are preserved. No source image was edited, and no accessibility was weakened to increase difficulty.')
lines+=section(30,'Final-exam calibration','The verified ECO 2251 Final Exam provides reasoning standards: no permanent tradeoff, vertical LRPC, short/long-run graph transitions, rational/adaptive expectations, structural shifts, sacrifice arithmetic and demand surprises. These already appear by Hard in the bank. Selected Hard and upper revisions improve application rather than shifting tiers.','No exam diagram, B/C/D/E/F arrangement, demographic scenario, sacrifice-ratio example, answer pattern or cosmetic rewrite was created. Existing library graphs are retained. All revised stems/options/feedback passed a new 12-word overlap screen plus human task comparison; lexical screening is not treated as proof of originality.')
lines+=section(31,'Mode readiness','All ten modes retain identical readiness for both the five-concept audit selection and the complete 14-concept parent preset. The scoped composition has no errors, 262 verified answer hashes, 24 Trial-by-Graph records, and 171 records eligible for each of Fading Fortune and Risk & Reward. The parent preset remains 728 records with unchanged counts.')
lines+=table(['Mode','Before / after'],[(x['label'],'Ready / ready') for x in v['modeValidation']['modes']])
lines+=['','The Edge smoke test verifies all 84 changed payloads, all 66 graphs and the visible revised Legendary example. External requests were blocked. This is not an all-mode gameplay or telemetry test.']
lines+=section(32,'Concept Review and routing integrity','All five selected review routes and local PDF hashes are unchanged. Protected IDs, source/canonical difficulty, tags, objectives, skills, provenance/source hashes, aliases, ordering, ordinary/checkpoint/calculation pools, repair/bridge routes, retest-related fields and eligibility remain exact. No engine, UI, telemetry, Worker or access change was made.')
lines+=table(['Concept','Review code','Runtime route'],[(c,x['primaryReviewCode'],', '.join(y['path'] for y in x['assets'])) for c,x in b['conceptReview']['runtimeIndex']['concepts'].items()])
lines+=['',f"The resolver retains {len(b['conceptReview']['warnings'])} preexisting global diagnostics. Exact objects and PDF byte checks are in `architecture-validation.json`; no new missing selected review route was found. Remote endpoints were not fetched."]
lines+=section(33,'Remaining warnings and review flags',f"Unmodified auditor BEFORE: {before['counts']}; AFTER: {after['counts']}. Every original/final record-rule pair is dispositioned. All 42 insufficient-accessibility warnings disappear after the real path/evidence repairs; no rule or eligibility flag was changed to reduce counts.")
lines+=table(['Severity','Rule','Final count'],[(x['severity'],x['rule'],x['count']) for x in after['ruleCounts']])
lines+=['','The 115 repeated-feedback warnings represent valid but often generic explanations. Forty-two image/non-required warnings reflect preserved eligibility, not delivery failure. Two prompts still lack an explicit graph cue. Twenty-three absolute-distractor reviews and several tier-depth reviews are genuine residual limitations. The Hard multi-year dollar-loss calculation is a heuristic difficulty false positive; its full computation is independently documented.']
lines+=section(34,'Remaining limitations','No scoped graph-reference failure remains. Some questions retain generic feedback, simple distractors, direct upper-tier reasoning and terse graph cues. This audit checks content/model consistency and delivery, not empirical student discrimination or every game branch.','The sacrifice-ratio convention sums annual percentage losses where stated; changing output benchmarks would require a different dollar aggregation. The adaptive numerical exercises prescribe a particular updating rule for the task, not a universal claim about expectation formation. No revised item promises costless disinflation from credibility alone. Validation is local and does not establish remote CDN or telemetry behavior.')
lines+=section(35,'Final semantic library hash',f'**`{semantic}`**',f'BEFORE: `{old["librarySha256"]}`. The sorted semantic JSON hash was independently recomputed with its two self-referential hash fields excluded. Library, registry and manifest agree. Only `build/faculty-build-composer/data/composer_library.js`, `composer_registry.json` and `composer_library_manifest.json` change in production; sidecars synchronize hashes and accessibility metadata. No commit, push, merge or deployment occurred.')
(W/'FINAL_REPORT.md').write_text('\n'.join(lines)+'\n','utf8')
files=['FINAL_REPORT.md','BEFORE.md','OBJECTIVE_FINDINGS_BEFORE.md','inventory-before.json','inventory-after.json','summary-before.json','live-preset.json','objective-findings-before.json','scope-boundary.json','overlap-mask.json','known-graph-failures-before.json','audit-projection-provenance.json','exam-source.json','changes.json','record-actions.json','accounting.json','revisions.json','accessibility-spec.json','accessibility-inspection.json','asset-accessibility-changes.json','path-repair-validation.json','graph-validation.json','numerical-validation.json','architecture-validation.json','semantic-validation.json','originality-validation.json','logical-validation.json','pool-memberships.json','retained-hard.json','quality-before.json','quality-before.md','quality-after.json','quality-after.md','quality-dispositions.json','validation.json','parent-preset-validation.json','browser-validation.json','browser-smoke.png','recipe.json','concepts.json','sources.json','author.py','accessibility.py','findings.py','stage.mjs','verify.py','browser.cjs','finish.py']
assert all((W/f).is_file() for f in files);wr('deliverables.json',files+['deliverables.json'])
print(json.dumps(dict(sections=len(re.findall(r'^## \d+\.',(W/'FINAL_REPORT.md').read_text('utf8'),re.M)),artifacts=len(files)+1,content=len(s),accessibilityOnly=56,pathOnly=0,unchanged=178,hardRetained=len(hard),graphFailuresRepaired=len(paths),quality=after['counts'],flagDispositions=len(dispositions),semanticHash=semantic)))
