// Physical clue content and its presentation stay independent of puzzle state.
import { DOCUMENTS, EVIDENCE, FINAL_EVENTS, INVOICES, JOBS, DATES, BROADCASTS } from './content.js';
import { solved, need, policyGauges } from './engine.js';
import { BUDGET_SLIPS, PAPER_COPY, PAY_STUBS, GROCERY_RECEIPTS, HOUSEHOLD_BILLS } from './physical-content.js';
export { BUDGET_SLIPS } from './physical-content.js';
const button=(label,action,id='',attrs='')=>`<button data-action="${action}" data-id="${id}" ${attrs}>${label}</button>`;
const cash=n=>'$'+n.toLocaleString('en-US');
const eventTile=id=>`<span class="causal-event"><strong>${FINAL_EVENTS[id].title}</strong><small>${FINAL_EVENTS[id].source}</small></span>`;
const table=rows=>`<table class="paper-table"><tbody>${rows.map(([a,b])=>`<tr><th scope="row">${a}</th><td>${b}</td></tr>`).join('')}</tbody></table>`;
const heading=(id,title)=>`<h2 class="object-title" data-heading>${title||DOCUMENTS[id]?.title||id}</h2>`;
function invoice(inv){const input=inv.id==='early'?9:18;return `<article class="paper invoice"><div class="company-mark">N<span>F</span></div><header><strong>NORTHLINE FREIGHT</strong><small>Delivered inputs · Alder district</small></header><div class="document-meta"><span>INV-${{early:'0312',middle:'0316',late:'0321'}[inv.id]}</span><time>${inv.name}</time></div><h3>Supplier invoice</h3>${table([['Energy / input, per unit',cash(input)],['Other variable costs',cash(9)]])}<div class="paper-total"><span>Unit production cost</span><strong>${cash(input+9)}</strong></div><div class="ink-stamp">${inv.stamp}</div></article>`;}
function receipts(){return `<div class="receipt-pair">${GROCERY_RECEIPTS.map((receipt,i)=>`<article class="paper thermal"><h3>ALDER GROCER</h3><small>41 Market Lane<br>Monthly account · ${receipt.date}</small><div class="receipt-rule"></div><p class="receipt-caption">QTY / SAME HOUSEHOLD BASKET</p>${table(receipt.items.map(([label,value])=>[label,cash(value)]))}<div class="paper-total"><span>TOTAL</span><strong>${cash(receipt.total)}</strong></div><div class="barcode" aria-hidden="true"></div><small>Thank you. Keep for your records.</small></article>`).join('')}</div>`;}
function pay(){return `<div class="envelope-pair">${PAY_STUBS.map((stub,i)=>`<div class="pay-envelope"><div class="envelope-flap"></div><article class="paper pay-stub"><header><strong>ALDER WORKS</strong><small>Payroll office · Employee 047</small></header><div class="document-meta"><span>${stub.month} ${stub.day} / MONTHLY</span><span>HOURS: ${stub.hours}</span></div><h3>Statement of earnings</h3>${table([['Regular pay',cash(stub.gross)],['Deductions','−'+cash(stub.deductions)]])}<div class="paper-total"><span>NET PAY</span><strong>${cash(stub.net)}</strong></div><small>${stub.note}</small></article><div class="envelope-pocket"><span>PRIVATE · EMPLOYEE 047</span></div></div>`).join('')}</div>`;}
function bills(){return `<div class="bill-pair">${HOUSEHOLD_BILLS.map(bill=>`<article class="paper folded ${bill.kind}"><strong>${bill.brand}</strong><small>${bill.account}</small><h3>${bill.title}</h3>${table(bill.rows)}<div class="ink-stamp">${bill.stamp}</div><p class="handwritten">${bill.note}</p></article>`).join('')}</div>`;}
export function renderDocument(id){let content='';
 if(id==='pay')content=pay();
 else if(id==='food')content=receipts();
 else if(id==='bills')content=bills();
 else if(id==='invoices')content=`<div class="invoice-stack">${INVOICES.map(invoice).join('')}</div><p class="paper pencil-note">March 14 · regular delivery failed.<br>Emergency stock arranged. — Stores</p>`;
 else if(id==='notebook')content=`<article class="paper handwritten-note"><span class="paper-pin"></span><h3>The envelope method</h3><p>Pay in.<br>Rent, food, utilities out.</p><p>Leave the rest for everything else.</p><p class="scribble">March on the left.<br>April on the right.</p><p>The drawer latch is wired to these pages.</p>${button('Open the notebook','open','budget','class="paper-link"')}</article>`;
 else if(id==='mandate')content=`<div class="bill-pair"><article class="paper mandate"><span class="seal-imprint">I</span><h3>Protect living costs</h3><p>Relieve inflation pressure.</p></article><article class="paper mandate"><span class="seal-imprint">II</span><h3>Protect work & output</h3><p>Support production and employment.</p></article></div>`;
 else if(id==='memo')content=`<article class="paper handwritten-note"><h3>Operator’s notebook</h3><p>This lever changes spending.</p><p>It cannot repair the input network.</p><p class="scribble">Try both directions.<br>Watch both needles.</p><small>Gauges: illustrative indices, not forecasts.</small></article>`;
 else {const d=DOCUMENTS[id],copy=PAPER_COPY[id];content=`<article class="paper ${id==='index'?'index-card':id==='national'?'register-sheet':'operational-sheet'}"><header><strong>${copy.brand}</strong><small>${copy.number}</small></header><h3>${d.title}</h3>${table(id==='index'?[['Station','10 × latest unit cost'],['First date','Employee interruption notice'],['Next dates','Emergency invoices']]:d.rows)}<p class="paper-foot">${copy.foot}</p>${id==='production'?'<div class="signature">Dispatch supervisor</div>':''}</article>`;}
 return heading(id)+`<div class="document-object doc-${id}">${content}</div>`;
}
export function tinyArtifact(id){const marks={household:'LEDGER',date:'14',costs:'INVOICE',staffing:'SHIFTS',indicators:'↓ ↑ ↑',broadcast:'THE ALDER POST',tradeoff:'I · II',badge:'047',access:'KEY'};return `<span class="artifact-thumb artifact-${id}" aria-hidden="true"><b>${marks[id]||id}</b><i></i><i></i><i></i></span>`;}
export function renderItem(id){return heading(id,id==='badge'?'Employee badge 047':'Utility cabinet key')+`<article class="physical-badge"><div class="badge-slot"></div><div class="badge-portrait" aria-hidden="true">${id==='badge'?'◉':'✧'}</div><strong>${id==='badge'?'ALDER WORKS':'CABINET KEY'}</strong><h3>${id==='badge'?'EMPLOYEE 047':'UTILITY CABINET'}</h3><small>${id==='badge'?'Invoice cabinet authorization':'Radio compartment · authorized entry'}</small><div class="barcode"></div></article>`;}
export function renderEvidence(id){const title=EVIDENCE[id].title;let object;
 if(id==='costs')object=`<div class="invoice-stack">${[...INVOICES].sort((a,b)=>({early:0,middle:1,late:2}[a.id]-{early:0,middle:1,late:2}[b.id])).map(invoice).join('')}</div>`;
 if(id==='household')object=`<article class="paper ledger-record"><h3>Household accounts</h3>${table([['MONTH','MARCH / APRIL'],['Pay','$3,000 / $3,200'],['Essentials','$2,200 / $2,800'],['Remaining','$800 / $400']])}<span class="ink-stamp">RECONCILED</span></article>`;
 if(id==='date')object=`<article class="paper folded interruption"><header><strong>ALDER WORKS</strong><small>EMPLOYEE 047 / PERSONAL COPY</small></header><h3>Interruption notice</h3><time class="big-date">MARCH 14</time><p>Regular input delivery interrupted today.</p><p class="paper-foot">Retain for later shift revisions.</p><div class="archive-symbol">◉ ARCHIVE RADIO</div></article>`;
 if(id==='staffing')object=`<article class="paper operational-sheet"><header><strong>ALDER WORKS / SHIFT OFFICE</strong><small>REVISION · MARCH 21</small></header><h3>Revised shift sheet</h3>${table([['Monthly production','1,200 → 900 units'],['Required workers','120 → 90'],['Workers seeking new jobs','30'],['Jobs released','A + C'],['Input returned to store','2 measures']])}<span class="ink-stamp">PLAN RELEASED</span></article>`;
 if(id==='indicators')object=`<article class="physical-plate"><h3>Matched bulletins</h3>${table([['Real output','200 → 184'],['Unemployment','5% → 8%'],['Price index','100 → 108'],['Monthly inflation','2% → 8%']])}<div class="plate-arrows">↓ &nbsp; ↑ &nbsp; ↑</div></article>`;
 if(id==='broadcast')object=`<div class="news-stack">${[['March 14','Terminal closed','Storm damage stops deliveries at the country’s main energy-input terminal.'],['March 16','Emergency routes cost more','Delivered input prices double. Earlier factory orders are still being completed.'],['March 21','Shifts cut','Manufacturers reduce production. Customer orders remain unfilled. More workers seek jobs.']].map(([date,head,body])=>`<article class="paper newspaper"><header>THE ALDER POST</header><small>ARCHIVE WIRE / ${date}</small><h3>${head}</h3><p>${body}</p></article>`).join('')}</div>`;
 if(id==='tradeoff')object=`<article class="paper policy-record"><h3>Policy trial record</h3>${table([['Tighter spending','Inflation pressure ↓ / work & output ↓'],['Looser spending','Work & output ↑ / inflation pressure ↑']])}<div class="record-seals"><span class="wax-seal">I</span><span class="wax-seal">II</span></div><p class="handwritten">Both objectives remain.</p></article>`;
 return heading(id,title)+`<div class="document-object evidence-${id}">${object}</div>`;
}
const titles={budget:'Household notebook',cost:'Invoice cabinet',orders:'Work-order press',indicators:'Record clasp',radio:'Wooden radio',policy:'Policy machine',exit:'Exit mechanism'};
const reorders=(kind,i,length)=>`<div class="object-reorder">${button('‹','reorder',`${kind}:${i}:-1`,`aria-label="Move position ${i+1} earlier" ${i===0?'disabled':''}`)}${button('›','reorder',`${kind}:${i}:1`,`aria-label="Move position ${i+1} later" ${i===length-1?'disabled':''}`)}</div>`;
export function renderMechanism(id,s,selection={}){
 const done=solved(s,id);
 if(done&&id==='budget')return heading(id,'The open drawer')+`<div class="drawer-interior"><div class="drawer-contents">${selection.freshReward==='budget'?button(tinyArtifact('badge')+'Employee 047','item','badge','class="found-object"')+button(tinyArtifact('date')+'Interruption notice','evidence','date','class="found-object"')+button(tinyArtifact('household')+'Reconciled accounts','evidence','household','class="found-object"'):'<div class="drawer-impressions" aria-label="Empty felt lining; the recovered contents are in your satchel"><i></i><i></i></div>'}</div><div class="drawer-front"><span></span></div></div>`;
 if(done&&['cost','orders','indicators','radio'].includes(id))return heading(id,titles[id])+`<div class="completed-object ${id}-complete"><div class="mechanism-seal">${id==='radio'?'RADIO ONLINE':id==='indicators'?'↓ &nbsp; ↑ &nbsp; ↑':'RELEASED'}</div>${button(tinyArtifact({cost:'costs',orders:'staffing',indicators:'indicators',radio:'broadcast'}[id])+'Inspect the record','evidence',{cost:'costs',orders:'staffing',indicators:'indicators',radio:'broadcast'}[id],'class="found-object"')}</div>`;
 let html='';
 if(id==='budget'){
  html=`<div class="open-ledger">${['march','april'].map(month=>`<section class="ledger-page"><h3>${month==='march'?'March':'April'}</h3><small>HOUSEHOLD ACCOUNTS</small>${['Pay','Rent','Groceries','Utilities'].map((label,i)=>{const value=s.budget[month][i],blank=value===[2600,1000,400,100][i];return `<div class="ledger-entry"><span>${label}</span>${button(blank?'······':cash(value),'place-budget',`${month}:${i}`,`class="entry-slot ${blank?'empty':''}" data-drop="budget" data-slot="${month}:${i}" aria-label="${month} ${label}: ${blank?'empty':value}. Place selected slip"`)}</div>`;}).join('')}<div class="ledger-balance"><span>Left for everything else</span><strong>${s.budget[month].some((v,i)=>v===[2600,1000,400,100][i])?'—':cash(s.budget[month][0]-s.budget[month].slice(1).reduce((a,b)=>a+b,0))}</strong></div><div class="pencil-line"></div></section>`).join('')}</div><p class="object-instruction">${selection.budget?'Place the selected slip on its notebook entry.':'Take a slip. Set it into the notebook.'}</p><div class="loose-slips">${BUDGET_SLIPS.filter(slip=>s.inspectedObjects.includes(slip.source)).map(slip=>button(`<small>${slip.month} / ${slip.label}</small><strong>${cash(slip.value)}</strong>`,'select-slip',slip.id,`class="paper amount-slip ${selection.budget===slip.id?'selected':''}" draggable="true" data-drag="budget" aria-pressed="${selection.budget===slip.id}"`)).join('')||'<p class="paper pencil-note">The loose slips are still with the pay envelopes, receipts, and bills.</p>'}</div>${button('Release drawer latch','solve','budget','class="brass-latch"')}`;
 }
 if(id==='cost'){
  const badge=s.inspectedObjects.includes('badge-used');
  html=`<div class="invoice-cabinet"><div class="employee-slot">${badge?'<span class="badge-inserted">047</span>':button('047 · Insert badge','use-badge','',`class="badge-receptacle" ${s.inventory.includes('badge')?'':'disabled'}`)}</div><div class="invoice-rails">${s.invoices.map((invId,i)=>`<section class="invoice-rail" data-drop="invoices" data-slot="${i}"><div class="rail-label">${['MARCH 12 · 1,200 UNITS','MARCH 16 · 1,200 UNITS','MARCH 21 · 900 UNITS'][i]}</div><div class="movable-invoice" draggable="true" data-drag="invoices" data-id="${i}">${invoice(INVOICES.find(x=>x.id===invId))}</div>${reorders('invoices',i,3)}</section>`).join('')}</div>${button('Seal cost record','solve','cost',`class="brass-latch" ${badge?'':'disabled'}`)}</div>`;
 }
 if(id==='orders'){
  html=`<div class="workbench"><div class="material-store"><span>INPUT STORE</span><div class="material-pieces">${Array.from({length:6-s.jobs.length*2},()=>'<i class="material-token"></i>').join('')}</div><small>${6-s.jobs.length*2} measures remain · 2 per job</small></div><div class="work-orders">${JOBS.map(job=>`<article class="paper work-order"><small>ALDER WORKS / ORDER ${job.id}</small><h3>${job.name.slice(4)}</h3>${table([['Added revenue',cash(job.revenue)],['Added cost',cash(job.cost)]])}<small>2 × $18 input + $18 other</small>${button(`<span class="allocation-sockets">${s.jobs.includes(job.id)?'<i class="material-token"></i><i class="material-token"></i>':'<i></i><i></i>'}</span><small>${s.jobs.includes(job.id)?'Return material':'Place two measures'}</small>`,'job',job.id,`class="allocation" aria-pressed="${s.jobs.includes(job.id)}" aria-label="${s.jobs.includes(job.id)?'Return material from':'Allocate two measures to'} job ${job.id}" ${need(s,'orders').length?'disabled':''}`)}</article>`).join('')}</div>${need(s,'orders').length?'<p class="pencil-note paper">Press locked. Release the invoice cabinet.</p>':''}${button('Pull the press lever','solve','orders',`class="press-lever" ${need(s,'orders').length?'disabled':''}`)}</div>`;
 }
 if(id==='indicators')html=`<div class="instrument-panel"><div class="dial-row">${['Real output','Unemployment','Prices'].map((label,i)=>`<div class="instrument"><span class="engraving">${label}</span>${button(`<span class="dial-face"><span class="dial-labels">↓ &nbsp; — &nbsp; ↑</span><i class="dial-needle" style="--angle:${s.indicators[i]*55}deg"></i><b class="dial-cap"></b></span><span class="dial-value">${s.indicators[i]===0?'—':s.indicators[i]===1?'↑':'↓'}</span>`,'gauge',`indicators:${i}`,`class="dial-control" aria-label="${label}: ${s.indicators[i]===0?'unchanged':s.indicators[i]===1?'up':'down'}. Rotate direction"`)}</div>`).join('')}</div><div class="record-sockets">${['household','costs','staffing'].map(rec=>button(s.connected.includes(rec)?tinyArtifact(rec):'<span class="slot-mouth"></span><small>'+EVIDENCE[rec].short+'</small>','connect',rec,`class="record-socket ${s.connected.includes(rec)?'inserted':''}" aria-label="Insert ${EVIDENCE[rec].short}" ${s.evidence.includes(rec)?'':'disabled'}`)).join('')}</div>${button('Engage the clasp','solve','indicators','class="brass-latch"')}</div>`;
 if(id==='radio'){
  const powered=solved(s,'indicators'),valid=s.frequency===270&&BROADCASTS[s.date],heard=powered&&s.tuned;
  html=`<div class="radio-set ${powered?'powered':''}"><div class="radio-maker">N O R T H L I N E &nbsp; / &nbsp; A R C H I V E</div><div class="radio-face"><div class="speaker-grille" aria-hidden="true"></div><div class="radio-controls"><div class="frequency-window"><div class="frequency-scale"><span>240</span><span>260</span><span>280</span><span>300</span></div><i class="radio-needle" style="left:${8+(s.frequency-240)/60*84}%"></i><output id="frequency-readout">${s.frequency} kHz</output></div><div class="knob-assembly"><button class="tuning-knob" data-knob="frequency" role="slider" aria-label="Station tuning knob" aria-valuemin="240" aria-valuemax="300" aria-valuenow="${s.frequency}" aria-valuetext="${s.frequency} kilohertz" ${powered?'':'disabled'}><span style="transform:rotate(${(s.frequency-270)*4}deg)"></span></button><label class="date-window"><span>DISPATCH</span><select id="date" data-input="date" data-focus="date" ${powered?'':'disabled'}>${DATES.map(date=>`<option ${date===s.date?'selected':''}>${date}</option>`).join('')}</select></label></div>${button('Listen','tune','',`class="radio-switch" ${powered?'':'disabled'}`)}<small class="radio-power">${powered?'● POWER':'○ NO POWER'}</small></div></div></div>
   <div class="radio-desk"><article class="paper wire-transcript"><small>WIRE COPY / ${heard?s.date:'RADIO'}</small><p>${!powered?'A cable runs to the record clasp.':!heard?'Turn the station knob. Select the dispatch date.':valid?BROADCASTS[s.date]:s.frequency===270?'Routine bulletin. No interruption report.':'Weather and shipping chatter.'}</p>${heard&&valid?button('Keep this dispatch','record-dispatch','',`class="paper-link" ${s.broadcastSequence.length>=3?'disabled':''}`):''}</article><div class="dispatch-clips">${Array.from({length:3},(_,i)=>`<div class="dispatch-clip ${s.broadcastSequence[i]?'filled':''}">${s.broadcastSequence[i]?`<small>270 kHz</small><strong>${s.broadcastSequence[i]}</strong>`:'<span class="clip-spring"></span>'}</div>`).join('')}</div><div class="object-actions">${s.broadcastSequence.length?button('Clear clips','clear-dispatches','','class="quiet"'):''}${button('Compile dispatches','solve','radio',`class="brass-latch" ${s.broadcastSequence.length===3?'':'disabled'}`)}</div></div>`;
 }
 if(id==='policy'){
  const g=policyGauges(s.policyValue);
  html=`<div class="policy-console"><div class="policy-dials">${[['inflation','Inflation pressure'],['conditions','Work & output']].map(([key,label])=>`<section class="instrument"><span class="engraving">${label}</span><div class="dial-face"><span class="dial-labels">0 &nbsp; &nbsp; 5 &nbsp; &nbsp; 10</span><i class="dial-needle" id="${key}-needle" style="--angle:${(g[key]-5)*12}deg"></i><b class="dial-cap"></b></div><output class="dial-value" id="${key}-reading">${g[key]} / 10</output></section>`).join('')}</div><div class="lever-mechanism"><label for="policy-lever" class="engraving">Demand-side policy</label><input id="policy-lever" type="range" min="-3" max="3" step="1" value="${s.policyValue}" data-input="policy" data-focus="policy" aria-label="Demand-side policy: tighter to looser"><div class="lever-labels"><span>TIGHTER</span><output id="policy-label">${s.policyValue<0?'Tighter':s.policyValue>0?'Looser':'Center'}</output><span>LOOSER</span></div></div><p id="policy-observation" class="console-readout">${policyObservation(s.policyValue)}</p><div class="trial-lights" id="trials"><span class="${s.policyTried.includes('tight')?'lit':''}">Tighter trial</span><span class="${s.policyTried.includes('loose')?'lit':''}">Looser trial</span></div>${done?'<div class="record-seals"><span class="wax-seal">I</span><span class="wax-seal">II</span></div>':`<div class="seal-sockets">${['prices','work'].map((seal,i)=>button(`<span class="wax-seal ${s.seals.includes(seal)?'seated':''}">${i+1===1?'I':'II'}</span><small>${i?'PROTECT WORK & OUTPUT':'PROTECT LIVING COSTS'}</small>`,'seal',seal,`class="seal-socket" aria-pressed="${s.seals.includes(seal)}" aria-label="Place ${seal==='prices'?'living costs':'work and output'} objective seal"`)).join('')}</div>${button('Acknowledge the tradeoff','solve','policy','class="brass-latch"')}`}</div>`;
 }
 if(id==='exit')html=`<p class="object-instruction causal-instruction">Arrange the events from cause to consequences.<br><small>The captions name the records that support each event.</small></p><div class="exit-lock"><div class="evidence-positions">${Array.from({length:5},(_,i)=>{const rec=s.finalSequence[i];return `<div class="evidence-position" data-drop="finalSequence" data-slot="${i}"><span class="event-position-number">${i+1}</span>${rec?`<div draggable="true" data-drag="finalSequence" data-id="${i}">${eventTile(rec)}</div>${reorders('finalSequence',i,s.finalSequence.length)}${button('×','remove-final',rec,`class="remove-pin" aria-label="Remove event: ${FINAL_EVENTS[rec].title}"`)}`:'<span class="empty-pin"></span>'}</div>`;}).join('')}</div>${button('<span class="lock-wheel" aria-hidden="true">✧</span><span>Turn mechanism</span>','solve','exit','class="turn-lock"')}</div><div class="exit-artifacts">${['costs','indicators','tradeoff','broadcast','staffing'].filter(rec=>s.evidence.includes(rec)&&!s.finalSequence.includes(rec)).map(rec=>button(eventTile(rec),'place-final',rec,`class="loose-artifact" aria-label="Place event: ${FINAL_EVENTS[rec].title}"`)).join('')}</div>`;
 return heading(id,titles[id])+html;
}
export function policyObservation(value){return value<0?'Pressure eases · work & output weaken':value>0?'Work & output improve · pressure rises':'Both pressures remain';}
