import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
import {games,publicRoot} from './sync.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=process.env.MQ_EVIDENCE_DIR||path.join(root,'validation_artifacts/published_managerial_parity/browser');fs.mkdirSync(out,{recursive:true});
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const results=[],examples=[],errors=[],badAssets=[],network=[];
const server=http.createServer((req,res)=>{const p0=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!p0.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const p=fs.statSync(p0).isDirectory()?path.join(p0,'index.html'):p0;res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.mp3':'audio/mpeg','.mp4':'video/mp4'})[path.extname(p)]||'application/octet-stream');fs.createReadStream(p).pipe(res);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({channel:'msedge',headless:true});
let currentTest='';
async function check(name,fn){if(process.env.MQ_TEST_FILTER&&!name.includes(process.env.MQ_TEST_FILTER)&&!name.startsWith('No browser'))return;currentTest=name;try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',detail:e.stack});}console.log(name+': '+results.at(-1).status);}
async function start(page,mode='standard'){await page.evaluate(mode=>startSelectedMode(mode,{quizConfirmed:true,fadingFortuneConfirmed:true,riskRewardConfirmed:true,trialGraphConfirmed:true}),mode);if(await page.locator('#guideIntroProceed').isVisible().catch(()=>false))await page.locator('#guideIntroProceed').click();await page.waitForFunction(()=>Boolean(currentQuestion));if(mode==='riskReward')await page.evaluate(()=>lockRiskRewardWager(.1));await page.waitForFunction(()=>document.getElementById('answers')?.querySelector('button'));await page.waitForTimeout(60);}
async function answer(page){await page.evaluate(async()=>{questionStartTime=Date.now()-6000;for(let i=0;i<currentQuestion.options.length;i++)if(await isQuestionAnswerCorrect(currentQuestion,i)){await answer(i);return;}throw Error('No correct option');});}
async function select(page){await page.locator('#question').evaluate(n=>{const r=document.createRange();r.selectNodeContents(n);getSelection().removeAllRanges();getSelection().addRange(r);});await page.waitForTimeout(280);}
async function hide(page,hidden){await page.evaluate(hidden=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>hidden});Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>hidden?'hidden':'visible'});document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event(hidden?'blur':'focus'));},hidden);}
async function next(page){await page.evaluate(()=>{closeGameModal();getSelection().removeAllRanges();room++;loadQuestion();});await page.waitForTimeout(70);}
const responses=page=>page.evaluate(()=>readLocalTelemetry().filter(e=>['question','rapid_guessing','exam_answer_initial','exam_answer_revision'].includes(e.event)));
function parse(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],value='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){value+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(value);value='';}else if((c==='\r'||c==='\n')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);rows.push(row);row=[];value='';}else value+=c;}if(value||row.length){row.push(value);rows.push(row);}assert(!quote);return rows;}
async function download(page,name){if(await page.locator('#bossRevealProceed').isVisible().catch(()=>false))await page.locator('#bossRevealProceed').click();await page.evaluate(()=>{beginRunSession();runEnding=true;stopTimedModeClock();return showMasteryReportScreen();});const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download Game Data',exact:true}).last().click()]);const dest=path.join(out,name+'.csv');await file.saveAs(dest);const text=fs.readFileSync(dest,'utf8');assert.equal(text.charCodeAt(0),0xFEFF);const rows=parse(text),header=rows.shift();assert.equal(header.length,75);assert.equal(new Set(header).size,75);assert(rows.every(r=>r.length===75));const columns=await page.evaluate(()=>TELEMETRY_COLUMNS);assert.deepEqual(header,columns);const data=rows.map(r=>Object.fromEntries(header.map((k,i)=>[k,r[i]])));assert.equal(data.length,await page.evaluate(()=>readLocalTelemetry().length));assert(!/selectedText|copiedText|clipboardContents|studentName|userAgent|anonymousClientId/.test(header.join(',')));const stem=await page.evaluate(()=>currentQuestion?.q||'');if(stem.length>20)assert(!text.includes(stem));return data;}
async function fresh(game,fn){const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await context.route('**/*',r=>{if(['fetch','xhr','websocket','eventsource','ping'].includes(r.request().resourceType()))network.push(r.request().url());return new URL(r.request().url()).origin===origin?r.continue():r.abort();});const page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push({game,test:currentTest,message:e.message,stack:e.stack}));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(origin))badAssets.push(r.url().replace(origin,''));});try{await page.goto(`${origin}/${publicRoot}/${game}/`);await fn(page);}finally{await context.close();}}
try{
for(const game of games){
 for(const scenario of ['normal','slow-visible','one-switch','multiple-switches','selection','copy-only','copy-leave','return-wait','next-question','save-resume','incomplete','legacy','duplicate-script'])await check(`${game}/${scenario}`,()=>fresh(game,async page=>{
  await start(page);if(scenario==='duplicate-script')await page.addScriptTag({url:origin+'/'+publicRoot+'/local-telemetry.js'});
  if(['selection','copy-leave','next-question','save-resume','duplicate-script'].includes(scenario))await select(page);
  if(scenario==='copy-only'){await page.locator('#question').evaluate(n=>{const r=document.createRange();r.selectNodeContents(n);getSelection().removeAllRanges();getSelection().addRange(r);document.dispatchEvent(new ClipboardEvent('copy'));});}
  if(['copy-leave','next-question','save-resume','duplicate-script'].includes(scenario))await page.evaluate(()=>document.dispatchEvent(new ClipboardEvent('copy')));
  if(['one-switch','multiple-switches','copy-leave','return-wait'].includes(scenario)){const n=scenario==='multiple-switches'?3:1;for(let i=0;i<n;i++){await hide(page,true);await page.evaluate(()=>{document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event('blur'));});await page.waitForTimeout(100);await hide(page,false);await page.waitForTimeout(60);}if(scenario==='return-wait')await page.waitForTimeout(220);}
  if(scenario==='slow-visible')await page.waitForTimeout(700);
  if(scenario==='next-question'){await answer(page);await next(page);}
  if(scenario==='save-resume'){const previous=await page.evaluate(()=>{const savedRun=runID;saveGameState();returnToModeSelectFromRun();return savedRun;});await hide(page,true);await page.waitForTimeout(80);await page.reload();await page.evaluate(()=>continueSavedRun());assert.equal(await page.evaluate(()=>runID),previous);await page.waitForTimeout(70);}
  if(scenario==='legacy')await page.evaluate(()=>{const rows=readLocalTelemetry();rows.unshift({eventID:'legacy',runID,event:'legacy',responseTimeMs:777,tag:'Comma, "quote"\nΩ'});localStorage.setItem(getTelemetryKey(),JSON.stringify(rows));});
  if(scenario!=='incomplete')await answer(page);
  const measured=await responses(page),last=measured.at(-1);
  if(scenario==='incomplete')assert.equal(measured.length,0);else{assert(last);assert(last.responseTimeMs>0);assert.equal(last.responseTimeMs,last.activeResponseTimeMs+last.hiddenTimeMs);assert(last.gameplayResponseTimeMs>=6000);assert(last.responseTimeMs<6000,'Independent gameplay clock');if(['normal','slow-visible','next-question','save-resume','legacy'].includes(scenario)){for(const k of ['hiddenTimeMs','tabSwitchCount','focusLossCount','selectionCount','copyCount'])assert.equal(last[k],0,k);assert.equal(last.timeAfterReturnMs,null);}if(scenario==='slow-visible')assert(last.activeResponseTimeMs>=700);if(['one-switch','multiple-switches','copy-leave','return-wait'].includes(scenario)){assert(last.hiddenTimeMs>0);assert.equal(last.tabSwitchCount,scenario==='multiple-switches'?3:1);assert.equal(last.focusLossCount,last.tabSwitchCount);assert(last.timeAfterReturnMs>=0);}if(scenario==='return-wait')assert(last.timeAfterReturnMs>=220);if(['selection','copy-leave','duplicate-script'].includes(scenario)){assert(last.selectionCount>0);assert(last.maxSelectedChars>0);assert.equal(last.questionSelected,1);}if(scenario==='selection')assert.equal(last.copyCount,0);if(['copy-only','copy-leave','duplicate-script'].includes(scenario)){assert.equal(last.copyCount,1);assert.equal(last.questionCopied,1);}if(scenario==='copy-leave'){assert.notEqual(last.timeCopyToHideMs,null);assert.notEqual(last.timeCopyToBlurMs,null);}assert.equal(measured.length,scenario==='next-question'?2:1,'No duplicate accepted row');}
  const data=await download(page,`${game}-${scenario}`);const row=data.filter(r=>r.event==='question').at(-1);if(last){for(const k of ['responseTimeMs','activeResponseTimeMs','hiddenTimeMs','tabSwitchCount','copyCount','timeCopyToHideMs','gameplayResponseTimeMs'])assert.equal(row[k],String(last[k]??''));examples.push({game,scenario,measurements:last});}else assert(data.every(r=>r.copyCount===''));
  if(scenario==='legacy'){const old=data.find(r=>r.event==='legacy');assert.equal(old.tag,'Comma, "quote"\nΩ');assert.equal(old.responseTimeMs,'777');assert.equal(old.copyCount,'');assert.equal(old.gameplayResponseTimeMs,'');}
  assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage).filter(k=>/anonymousTelemetry/.test(k))),[]);
 }));
 for(const mode of ['timed','exam','quiz','unlimited','legendary','score','fadingFortune','riskReward',...(['market-signal','strategy-desk'].includes(game)?['trialGraph']:[])])await check(`${game}/mode-${mode}`,()=>fresh(game,async page=>{
  await start(page,mode);await answer(page);const rows=await responses(page);const row=rows.at(-1);assert(row);assert.equal(row.event,mode==='exam'?'exam_answer_initial':'question');assert(row.activeResponseTimeMs>0);assert.equal(row.hiddenTimeMs,0);assert.equal(row.copyCount,0);assert.equal(await page.evaluate(()=>gameMode),mode);assert.equal(await page.evaluate(()=>totalAttempts),mode==='exam'?0:1);await download(page,`${game}-${mode}`);
 }));
 await check(`${game}/exam-revision-commit`,()=>fresh(game,async page=>{await start(page,'exam');await select(page);await page.evaluate(()=>document.dispatchEvent(new ClipboardEvent('copy')));await hide(page,true);await page.waitForTimeout(80);await hide(page,false);await answer(page);await page.evaluate(()=>navigateExamRoom(2));await page.waitForTimeout(60);await answer(page);await page.evaluate(()=>navigateExamRoom(1));await page.waitForTimeout(90);await page.evaluate(async()=>{const prior=getExamRoomState(1).selectedIndex;questionStartTime=Date.now()-6000;await answer((prior+1)%currentQuestion.options.length);});for(let n=3;n<=9;n++){await page.evaluate(n=>navigateExamRoom(n),n);await page.waitForTimeout(35);await answer(page);}await page.evaluate(()=>commitExamSection(getExamSectionState(1)));const rows=await responses(page),commits=rows.filter(r=>r.event==='question');assert.equal(commits.length,9);assert.equal(rows.filter(r=>r.event==='exam_answer_revision').length,1);assert.equal(new Set(commits.map(r=>r.room)).size,9);const first=commits.find(r=>r.room===1);assert.equal(first.copyCount,1);assert.equal(first.tabSwitchCount,1);assert(first.responseTimeMs>first.hiddenTimeMs);assert(commits.filter(r=>r.room!==1).every(r=>r.copyCount===0));await page.evaluate(()=>commitExamSection(getExamSectionState(1)));assert.equal((await responses(page)).filter(r=>r.event==='question').length,9);await download(page,`${game}-exam-commit`);}));
 await check(`${game}/repair-bridge-retest-boss-reset`,()=>fresh(game,async page=>{await start(page);for(const stage of ['repair','bridge','retest']){await page.evaluate(stage=>{closeGameModal();remediationState.active=true;remediationState.stage=stage;displayQuestion();},stage);await page.waitForTimeout(70);await answer(page);const r=(await responses(page)).at(-1);assert(r.activeResponseTimeMs>0);assert.equal(r.remediationStage,stage);assert.equal(r.copyCount,0);}await page.evaluate(()=>{remediationState.active=false;closeGameModal();room=10;bossHealth=3;bossPool=[];loadQuestion();});if(await page.locator('#bossRevealProceed').isVisible())await page.locator('#bossRevealProceed').click();await page.waitForTimeout(70);await answer(page);assert.equal((await responses(page)).at(-1).room,10);assert((await responses(page)).at(-1).activeResponseTimeMs>0);}));
 await check(`${game}/completion-new-run`,()=>fresh(game,async page=>{await start(page,'quiz');await answer(page);await page.evaluate(()=>handlePracticeModeComplete());const rows=await page.evaluate(()=>readLocalTelemetry());assert(rows.some(r=>/_complete$/.test(r.event)));const count=rows.length;await hide(page,true);await hide(page,false);assert.equal(await page.evaluate(()=>readLocalTelemetry().length),count);await download(page,`${game}-completed`);await page.evaluate(()=>returnToModeSelectFromRun());await start(page);await answer(page);assert.equal((await responses(page)).length,1);assert.equal((await responses(page))[0].copyCount,0);}));
 await check(`${game}/focus-pause-readiness`,()=>fresh(game,async page=>{
  await start(page);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(120);await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForTimeout(60);await answer(page);let r=(await responses(page)).at(-1);assert.equal(r.hiddenTimeMs,0);assert.equal(r.focusLossCount,1);assert(r.unfocusedTimeMs>=120);assert(r.timeAfterFocusMs>=60);
  await page.evaluate(()=>returnToModeSelectFromRun());await page.evaluate(()=>startSelectedMode('riskReward',{riskRewardConfirmed:true}));await page.waitForFunction(()=>Boolean(currentQuestion));await page.waitForTimeout(600);assert.equal((await responses(page)).length,0);await page.evaluate(()=>lockRiskRewardWager(.1));await page.waitForTimeout(80);await answer(page);r=(await responses(page)).at(-1);assert(r.responseTimeMs>=80&&r.responseTimeMs<600,'Wager wait excluded');
  await page.evaluate(()=>returnToModeSelectFromRun());await start(page,'fadingFortune');await page.evaluate(()=>pauseFadingFortune('qa-visible-modal'));await page.waitForTimeout(240);await page.evaluate(()=>resumeFadingFortune('qa-visible-modal'));await answer(page);r=(await responses(page)).at(-1);assert(r.responseTimeMs>=240,'Visible pause included');assert.equal(r.hiddenTimeMs,0);assert(r.fadingFortunePausedDurationMs>=240,'Gameplay pause retained');
  await download(page,`${game}-timing-boundaries`);
 }));
}
await check('No browser exceptions, broken requested assets, or telemetry network requests',()=>{assert.deepEqual(errors,[]);assert.deepEqual([...new Set(badAssets)],[]);assert.deepEqual(network,[]);});
}finally{await browser.close();server.closeAllConnections();server.close();}
const report={passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,results,errors,badAssets,network,examples};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:results.filter(r=>r.status==='FAIL')}));if(report.failed)process.exitCode=1;




