import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE),root=path.resolve('dist'),out=path.resolve('validation_artifacts/public_site_cleanup_lms_ai');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const p=fs.statSync(file).isDirectory()?path.join(file,'index.html'):file;res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json','.woff2':'font/woff2'})[path.extname(p)]||'application/octet-stream');fs.createReadStream(p).pipe(res);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'msedge',headless:true}),results=[],errors=[];
try{for(const width of [1440,390]){const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
 for(const [name,url] of [['home','/'],['about','/about/'],['resources','/resources/'],['build','/build/'],['validator','/tools/question-bank-validator/']]){await page.goto(origin+url);await page.waitForTimeout(200);assert(!(await page.locator('body').innerText()).match(/quiz converter|\bQTI\b/i));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),name+' overflow '+width);
 if(name==='home'&&width===390){await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');}if(name==='about'){await page.getByRole('heading',{name:'AI as a co-creator',exact:true}).scrollIntoViewIfNeeded();assert((await page.locator('body').innerText()).includes('final responsibility remain human'));}
 if(name==='build'){const option=page.locator('input[value="validate"]');await option.check();assert(await page.locator('#question-validation').isVisible());assert.equal(await page.locator('input[value="quiz"]').count(),0);}
 if(name==='validator'){await page.locator('#example').click();await page.locator('#validate').click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('No structural errors'));}
 await page.screenshot({path:path.join(out,`${name}-${width}.png`),fullPage:false});const nav=page.locator('a[href="/resources/"]').first();if(await nav.isVisible()){await nav.click();await page.waitForURL('**/resources/');}results.push({page:name,width,status:'PASS'});
 }await context.close();}
 const response=await fetch(origin+'/tools/canvas-quiz-converter/');assert.equal(response.status,404);assert.deepEqual(errors,[]);
}finally{await browser.close();server.close();fs.writeFileSync(out+'/browser.json',JSON.stringify({results,errors},null,2));}
console.log(JSON.stringify({status:'PASS',viewports:results.length,errors}));
