from common import *
p=paired
p('P62G-MON-H-031','At the profit-maximizing output in the graph, how far does price exceed MR, and why?',
 '$18; selling an additional unit requires lowering the single price on earlier units.',
 '$12; selling an additional unit requires lowering the single price on earlier units.',
 '$18; the demand price is the extra revenue from the last unit without any price effect on earlier units.',
 '$12; the demand price is the extra revenue from the last unit without any price effect on earlier units.',
 'MR=MC at Q=36. Demand gives price42 while MR is24, a gap18. The extra unit adds its sale revenue but lowering price also reduces receipts on prior units, so MR is below price.',
 'Q36,P42,MR24.','Explain the price effect that separates monopoly MR from price.','42-24=18')
for i,q,start,end in [('P62G-MON-H-032',36,36,60),('P62G-MON-H-036',40,40,67)]:
 p(i,'A manager proposes expanding monopoly output to the demand–MC intersection in the graph. Which profit-maximizing output and diagnosis of that proposal are correct?',
 f'{q} units; expanding beyond MR=MC adds units whose marginal cost exceeds marginal revenue.',
 f'{q-6} units; expanding beyond MR=MC adds units whose marginal cost exceeds marginal revenue.',
 f'{q} units; demand=MC must maximize monopoly profit because it is socially efficient.',
 f'{q-6} units; demand=MC must maximize monopoly profit because it is socially efficient.',
 f'MR=MC gives Q={q}; demand meets MC near Q={end}. Between them MC exceeds MR, so expanding to the social benchmark lowers private profit even though the extra units have value above resource cost.',
 f'MR–MC crossing{q}; D–MC crossing about{end}.','Distinguish the monopoly profit rule from the allocative benchmark.')
p('P62G-MON-H-041','Refer to the graph. Which change in ATC between the monopoly and efficient quantities supports the natural-monopoly interpretation?',
 'About $24 to $22; declining average cost over the relevant range indicates economies of scale.',
 'About $30 to $28; declining average cost over the relevant range indicates economies of scale.',
 'About $24 to $22; natural monopoly is established by a falling demand curve alone.',
 'About $30 to $28; natural monopoly is established by a falling demand curve alone.',
 'At Q=45, ATC is24; near Q=90 it is about22. Falling average cost over this market’s relevant output range supports economies of scale and the natural-monopoly interpretation. Downward demand alone does not establish it.',
 'ATC(45)=24,ATC(90)≈22.','Interpret declining long-run cost as economies of scale supporting natural monopoly.')
p('P62G-MON-H-043','Which approximate fair-return price and cost relationship in the graph imply zero economic profit?',
 '$16; price equals average total cost.','$20; price equals average total cost.',
 '$16; price equals marginal cost.','$20; price equals marginal cost.',
 'Demand meets ATC near Q=116 and P=16. With price equal to cost per unit, revenue covers all economic costs. MC is10, so average-cost pricing does not also give P=MC.',
 'D–ATC intersection nearQ116,P16; MC10.','Distinguish break-even average-cost regulation from marginal-cost regulation.')
for i,q,p0,qe,pe in [('P62G-MON-H-034',36,42,60,30),('P62G-MON-EL-037',45,47,90,20),('P62G-MON-B3-057',45,47,90,20)]:
 p(i,'Which monopoly and allocatively efficient outcomes are shown, and which decision rules distinguish them?',
 f'Monopoly Q={q},P=${p0}; efficient Q={qe},P=${pe}. Monopoly uses MR=MC; efficiency uses demand=MC.',
 f'Monopoly Q={q-5},P=${p0+2}; efficient Q={qe-10},P=${pe+2}. Monopoly uses MR=MC; efficiency uses demand=MC.',
 f'Monopoly Q={q},P=${p0}; efficient Q={qe},P=${pe}. Monopoly uses demand=MC; efficiency uses MR=MC.',
 f'Monopoly Q={q-5},P=${p0+2}; efficient Q={qe-10},P=${pe+2}. Monopoly uses demand=MC; efficiency uses MR=MC.',
 f'The MR–MC crossing gives monopoly output{q}; demand there gives price{p0}. Demand meetsMC at Q={qe},P={pe}, where marginal willingness to pay equals marginal resource cost. The monopoly’s marginal revenue rule restricts quantity below that benchmark.',
 f'MR–MC Q{q},D({q})={p0};D–MC Q{qe},P{pe}.','Compare private profit maximization with allocative efficiency.')
p('P62G-MON-EL-031','Fixed cost rises $360 while demand, MR and MC stay unchanged. The firm remains active. Which resulting profit and decision assessment follow from the graph?',
 '$180 profit; output and price stay unchanged because their marginal determinants have not changed.',
 '$240 profit; output and price stay unchanged because their marginal determinants have not changed.',
 '$180 profit; a fixed-cost increase must enter MC and change the profit-maximizing output.',
 '$240 profit; a fixed-cost increase must enter MC and change the profit-maximizing output.',
 'The graph givesQ36,P42 and ATC27, so initial profit=(42−27)×36=540. The fixed-cost increase reduces it to180. MR=MC remains at36 and demand still gives42.',
 'Q36,P42,ATC27.','Separate fixed-cost effects on profit from the marginal output decision.','(42-27)*36-360=180')
for i,start,end,alternative in [('P62G-MON-EL-032',36,60,54),('P62G-MON-EL-034',40,67,60)]:
 p(i,'How many additional units lie between the monopoly and demand–MC quantities shown, and why would producing those units reduce allocative inefficiency?',
 f'About {end-start} units; willingness to pay exceeds marginal resource cost for the omitted trades.',
 f'About {alternative-start} units; willingness to pay exceeds marginal resource cost for the omitted trades.',
 f'About {end-start} units; the buyers’ payments themselves are additional net social benefits.',
 f'About {alternative-start} units; the buyers’ payments themselves are additional net social benefits.',
 f'The monopoly quantity is{start}, and demand meetsMC near{end}, leaving about{end-start} units. Over that interval demand exceedsMC, so the omitted trades have positive net resource benefits. Payments redistribute surplus rather than create those benefits.',
 f'MonopolyQ{start},D–MC Q≈{end};D aboveMC between them.','Identify forgone gains from trade rather than transfers.','%s-%s=%s'%(end,start,end-start))
p('P62G-MON-EL-033','Suppose a fixed-cost reduction lowers ATC at the graph’s profit-maximizing output to $35 without changing demand, MR or MC. Which profit and output decision result?',
 '$200 profit; retain the output chosen by unchanged MR and MC.',
 '$150 profit; retain the output chosen by unchanged MR and MC.',
 '$200 profit; choose a new output solely because ATC changed, despite unchanged marginal curves.',
 '$150 profit; choose a new output solely because ATC changed, despite unchanged marginal curves.',
 'MR=MC givesQ40 and demand givesP40. With ATC35, profit=(40−35)×40=200. Changing a fixed cost alters the profit level but does not move the marginal optimum.',
 'MR–MC Q40;D(40)=40.','Distinguish improved cost recovery from a changed marginal output incentive.','(40-35)*40=200')
p('P62G-MON-L-093','Which output, profit/loss and decision sequence correctly interpret the monopoly graph? Assume the firm can cover variable cost at its optimum.',
 'Q=40, loss$200; choose MR=MC, price from demand, compare price with ATC, and use demand=MC as the separate efficiency benchmark.',
 'Q=30, loss$150; choose MR=MC, price from demand, compare price with ATC, and use demand=MC as the separate efficiency benchmark.',
 'Q=40, loss$200; choose output at minimum ATC and use MR as the selling price.',
 'Q=30, loss$150; choose output at minimum ATC and use MR as the selling price.',
 'MR=MC at40, demand gives price40, and ATC is45. Profit=(40−45)×40=−200. Demand meetsMC near67, the allocative benchmark. These are distinct steps, and the loss alone does not identify the shutdown decision.',
 'Q40,P40,ATC45;D–MC near67.','Apply the monopoly output, price, profit and efficiency comparisons without confusing their roles.','(40-45)*40=-200')
for i in ['P62G-MON-L-094','P62G-MON-EL-036']:
 p(i,'Under marginal-cost pricing in the graph, what regulated price and financing issue arise?',
 '$20; ATC remains above that price, so efficient output may require financial support to cover costs.',
 '$15; ATC remains above that price, so efficient output may require financial support to cover costs.',
 '$20; matching price to MC necessarily covers total economic cost, so no financing gap can exist.',
 '$15; matching price to MC necessarily covers total economic cost, so no financing gap can exist.',
 'Demand meetsMC atQ90 and price20. ATC there remains around22, above the price. A marginal-efficiency rule does not guarantee recovery of fixed and total costs under scale economies.',
 'D–MC Q90,P20;ATC about22.','Explain the cost-recovery tradeoff under efficient natural-monopoly pricing.')
p('P62G-MON-EL-038','Which price sequence in the graph corresponds to monopoly, fair-return regulation and marginal-cost regulation, and what distinguishes the two regulatory rules?',
 '$27, about$16, $10; fair return covers ATC while marginal-cost pricing targets allocative efficiency.',
 '$30, about$20, $12; fair return covers ATC while marginal-cost pricing targets allocative efficiency.',
 '$27, about$16, $10; fair return sets P=MC while marginal-cost pricing sets P=ATC.',
 '$30, about$20, $12; fair return sets P=MC while marginal-cost pricing sets P=ATC.',
 'The monopoly reads price27 atQ70. Demand meetsATC nearQ116,P16 andMC atQ140,P10. Average-cost pricing covers costs; marginal-cost pricing expands further to the marginal-efficiency benchmark but may not coverATC.',
 'Monopoly(70,27),D–ATC≈(116,16),D–MC(140,10).','Compare monopoly and two regulatory rules without conflating efficiency and break-even.')
p('P62G-MON-EL-039','How many additional units separate the approximate fair-return outcome from marginal-cost pricing, and why does fair return leave allocative inefficiency?',
 'About24 units; price still exceeds MC at the fair-return output.',
 'About18 units; price still exceeds MC at the fair-return output.',
 'About24 units; P=ATC automatically makes marginal willingness to pay equal MC.',
 'About18 units; P=ATC automatically makes marginal willingness to pay equal MC.',
 'Fair return occurs nearQ116 and P16; marginal-cost pricing givesQ140,P10. The remaining24 units have willingness to pay aboveMC. CoveringATC does not eliminate the marginal gap.',
 'D–ATC≈Q116,P16;D–MC Q140,P10.','Distinguish break-even regulation from full allocative efficiency.','140-116=24')
p('P62G-MON-EL-040','What total financing gap arises at the graph’s marginal-cost-pricing output, and why might a subsidy be needed?',
 '$700; price equalsMC but fails to coverATC.',
 '$560; price equalsMC but fails to coverATC.',
 '$700; price equalingMC is sufficient to cover all economic costs.',
 '$560; price equalingMC is sufficient to cover all economic costs.',
 'AtQ140, regulated price isMC10 whileATC15. The cost-recovery gap is(15−10)×140=700. Efficient marginal pricing alone does not finance total costs.',
 'Q140,P=MC10,ATC15.','Measure and interpret a subsidy requirement under marginal-cost pricing.','(15-10)*140=700')
p('P62G-MON-B3-058','Which regulated quantities and cost-recovery comparison are supported by the graph?',
 'Fair return about116, marginal-cost pricing140; the former breaks even while the latter has a loss.',
 'Fair return about100, marginal-cost pricing120; the former breaks even while the latter has a loss.',
 'Fair return about116, marginal-cost pricing140; both must break even because each is a regulatory rule.',
 'Fair return about100, marginal-cost pricing120; both must break even because each is a regulatory rule.',
 'Demand meetsATC near116, whereP≈ATC≈16. At the demand–MC quantity140, P10 lies belowATC15. One rule recovers costs; the other achieves marginal efficiency with a financing gap.',
 'D–ATC≈116;D–MC140 withP10<ATC15.','Compare break-even and allocative-efficiency tradeoffs.')
p('P62G-MON-H-002','At Q1, which approximate price range and profit test are supported by the graph?',
 'Price is between$70 and$80; comparing it with lowerATC establishes positive economic profit.',
 'Price is between$60 and$70; comparing it with lowerATC establishes positive economic profit.',
 'Price is between$70 and$80; the entire gap between price andMC is economic profit per unit.',
 'Price is between$60 and$70; the entire gap between price andMC is economic profit per unit.',
 'AtQ1, the demand price is in the70–80 range andATC is just above40. Profit per unit isP−ATC, notP−MC. MC determines the marginal output decision.',
 'AtQ1 price70–80;ATC about42;MC around26.','Use average total cost to evaluate economic profit.')
p('P62G-MON-H-003','At Q1, which price reading and explanation of price exceedingMR are correct?',
 'Price is between$55 and$60; an extra sale lowers revenue on earlier units under single-price selling.',
 'Price is between$65 and$70; an extra sale lowers revenue on earlier units under single-price selling.',
 'Price is between$55 and$60; marginal revenue ignores the price reduction on earlier units.',
 'Price is between$65 and$70; marginal revenue ignores the price reduction on earlier units.',
 'AtQ1, the demand price is just below60 whileMR is below30. Selling another unit along downward-sloping demand requires lowering the common price, reducing revenue on prior sales. MR includes both effects.',
 'P1 between55 and60;MR below30.','Explain monopoly marginal revenue using both output and price effects.')
p('P62G-MON-H-004','Fixed cost rises while the firm remains active and demand,MR andMC are unchanged. Which price range and short-run decision are supported by the graph?',
 'Price stays between$65 and$75; the same marginal optimum is chosen but profit falls.',
 'Price stays between$55 and$65; the same marginal optimum is chosen but profit falls.',
 'Price stays between$65 and$75; a fixed-cost increase leaves economic profit unchanged.',
 'Price stays between$55 and$65; a fixed-cost increase leaves economic profit unchanged.',
 'The current demand price atQ1 is near70. UnchangedMR andMC preserve the output and therefore its demand price. Higher fixed cost raises total cost and lowers profit dollar for dollar.',
 'P1 near70 at unchangedMR–MC output.','Separate fixed-cost effects on profit from output and price.')
p('P62G-MON-H-005','A fixed-cost increase raisesATC exactly to the demand price atQ1 without changing demand,MR orMC. Which newATC range and profit interpretation follow from the graph?',
 'Between$55 and$65; economic profit is zero while all opportunity costs are covered.',
 'Between$65 and$75; economic profit is zero while all opportunity costs are covered.',
 'Between$55 and$65; zero economic profit means the owner’s opportunity cost is uncovered.',
 'Between$65 and$75; zero economic profit means the owner’s opportunity cost is uncovered.',
 'P1 is a little above60, soATC must rise into the55–65 range to equal it. The output decision is unchanged. P=ATC means revenue covers explicit and implicit costs, including normal return.',
 'P1 approximately62 atQ1.','Interpret zero economic profit after a fixed-cost increase as full opportunity-cost recovery.')
p('P62G-MON-H-006','Which price range atQ1 and short-run operating decision are supported by the graph?',
 'Between$55 and$65; produceQ1 because price coversAVC despite being belowATC.',
 'Between$65 and$75; produceQ1 because price coversAVC despite being belowATC.',
 'Between$55 and$65; shut down solely because price is belowATC.',
 'Between$65 and$75; shut down solely because price is belowATC.',
 'AtQ1 the price is near59, belowATC but well aboveAVC near25. Production pays avoidable costs and part of fixed cost. Shutting down would forgo that contribution and leave the full fixed cost.',
 'AtQ1 P≈59,AVC≈25,ATC≈79.','Distinguish loss minimization from shutdown using avoidable costs.')
p('P62G-MON-H-007','Let L be the dollar gap betweenATC and the demand price atQ1. Based on the graph’s output scale, which total-loss range and interpretation are correct?',
 'Between10L and20L dollars; multiply loss per unit by output.',
 'Between20L and30L dollars; multiply loss per unit by output.',
 'Between10L and20L dollars; the per-unit gap alone is the total loss regardless of output.',
 'Between20L and30L dollars; the per-unit gap alone is the total loss regardless of output.',
 'Q1 lies between10 and20 units. Each unit losesL dollars, so total lossL×Q1 lies between10L and20L. A vertical price-cost gap is a per-unit loss, not the whole rectangle.',
 'Q1 between10 and20.','Convert a per-unit loss into total loss using the actual output scale.')
p('P62G-MON-H-008','Which price range at the markedMR–MC output and explanation show why the marginal rule remains relevant despite a loss?',
 'Between$50 and$60; price coversAVC, so this output minimizes the short-run loss.',
 'Between$60 and$70; price coversAVC, so this output minimizes the short-run loss.',
 'Between$50 and$60; anMR–MC intersection guarantees positive economic profit.',
 'Between$60 and$70; anMR–MC intersection guarantees positive economic profit.',
 'AtQ1 the price is near56, belowATC but aboveAVC. MR=MC identifies the best positive output, and coveringAVC makes production preferable to shutdown. The marginal rule does not guarantee positive profit.',
 'AtQ1 P50–60,ATC aboveP,AVC belowP.','Apply marginal analysis to loss minimization subject to the shutdown condition.')
p('P62G-MON-H-009','Which maximum demand price and short-run decision are supported by the graph?',
 '$40; shut down because the entire demand curve lies belowAVC.',
 '$35; shut down because the entire demand curve lies belowAVC.',
 '$40; produce because a positive selling price necessarily covers avoidable cost.',
 '$35; produce because a positive selling price necessarily covers avoidable cost.',
 'Demand intercepts at40 whileAVC starts near45 and remains above demand. At every positive output, revenue fails to cover variable costs. Producing zero minimizes the short-run loss.',
 'Demand maximum40;AVC≥45.','Apply the avoidable-cost shutdown rule across feasible positive outputs.')
p('P62G-MON-H-010','The firm in the graph shuts down in the short run. Which comparison supports shutdown, and which cost remains unavoidable?',
 'Demand starts at$45 belowAVC of about$52; fixed cost remains.',
 'Demand starts at$40 belowAVC of about$48; fixed cost remains.',
 'Demand starts at$45 belowAVC of about$52; variable cost remains while all fixed cost disappears.',
 'Demand starts at$40 belowAVC of about$48; variable cost remains while all fixed cost disappears.',
 'The highest demand price is45, belowAVC starting near52; demand stays belowAVC. Shutdown avoids variable expenditures, but short-run fixed commitments remain.',
 'Demand intercept45;AVC starts52 and stays above demand.','Distinguish costs avoided by shutdown from unavoidable fixed costs.')
p('P62G-MON-H-011','AtQ=30, which demand andMC readings and interpretation of the omitted trade are correct?',
 'Value is about$40 andMC about$26; the omitted unit would add to total surplus.',
 'Value is about$50 andMC about$30; the omitted unit would add to total surplus.',
 'Value is about$40 andMC about$26; the gap measures only a transfer from buyers to sellers.',
 'Value is about$50 andMC about$30; the gap measures only a transfer from buyers to sellers.',
 'Q30 lies between monopolyQ1 and the demand–MC benchmarkQ2. Demand there is about40 andMC26. Producing the omitted unit creates value above resource cost, a real gain rather than a transfer.',
 'AtQ30,D≈40,MC≈26;Q1<30<Q2.','Identify positive marginal gains from trades restricted by monopoly.')
p('P62G-MON-H-012','The graph shows output restricted fromQ2 toQ1. Which approximate width and interpretation of the area between demand andMC over that interval are correct?',
 '18 units; the area is lost gains from mutually beneficial trades.',
 '12 units; the area is lost gains from mutually beneficial trades.',
 '18 units; the area is solely a transfer of existing surplus to the monopolist.',
 '12 units; the area is solely a transfer of existing surplus to the monopolist.',
 'Q1 is near21 andQ2 near39, a width about18. Between them demand lies aboveMC. Restricting those units removes net benefits, creating deadweight loss rather than merely transferring surplus on sales that still occur.',
 'Q1≈21,Q2≈39;demand aboveMC in interval.','Distinguish monopoly deadweight loss from redistribution of existing gains.','39-21≈18')
save();print('Graph proposals prepared:',len(R))
