from author import *

replace('42727','Refer to the Lorenz curve. Treat each segment between adjacent marked points as straight. With population and income shares written as fractions, calculate the area B under the Lorenz curve by adding trapezoids: width × (left height + right height)/2. The Gini coefficient is 1 − 2B. What is the Gini coefficient?', ['0.15','0.31','0.62','0.38'],3,'Using the plotted shares 0, .05, .15, .30, .55, 1 at population fractions 0, .2, .4, .6, .8, 1, B = .1 × [.05 + .20 + .45 + .85 + 1.55] = .31. Gini = 1 − 2(.31) = .38.','Replace the ambiguous graph-readability question with a multi-step Gini calculation; supply the formula and use exact labeled graph points.')
stem('P62D-ITP-M-001','In Arden’s market for solar panels, the no-trade equilibrium price is $50 and the world price is $30. With free trade and no transport costs, which outcome is likely?')
replace('P62D-ITP-M-002','Bellora is a small competitive country with free trade and no transport costs. Its no-trade coffee price is $60 and the world price is $75. What will Bellora do?', ['Import coffee because the world price is higher.','Have no net trade because the prices differ.','Export coffee because the world price is higher.','Import coffee because domestic supply rises.'],2,'The $75 world price exceeds the $60 no-trade price. Domestic production rises and consumption falls, leaving coffee to export.','Follow the faculty’s proposed price and wording and update all dependent text.')
replace('P62D-ITP-M-003','Caspia is a small competitive economy with free trade and no transport costs. Its no-trade bicycle price and the world price are both $42. With unchanged demand and supply, what net trade is likely?', ['Net exports because producers can sell abroad.','Net imports because consumers can buy abroad.','Net exports equal to all domestic production.','No net trade because domestic demand equals supply.'],3,B['P62D-ITP-M-003']['q']['feedback'],'Apply the faculty wording while retaining the assumptions needed for a unique answer.')
replace('P62D-ITP-M-009','At the world price, Ilyria’s residents consume 70 paper rolls and its domestic firms supply 45. With free trade and no inventory change, what will Ilyria do?', ['Import 25 rolls to meet the excess domestic demand.','Import all 70 rolls consumed domestically.','Export 25 rolls to meet the excess domestic demand.','Import 25 rolls to absorb excess domestic supply.'],0,'Imports = domestic consumption − domestic production = 70 − 45 = 25 rolls.','Use the faculty-proposed alternatives with precise excess-demand terminology.')
trade_data=[('Arden','solar panels',30,50,10,50),('Bellora','coffee beans',42,52,16,60),('Caspia','bicycles',20,52,8,42),('Demer','tablets',40,64,16,64),('Estara','wool blankets',30,62,16,53),('Arden','solar panels',70,50,10,50),('Bellora','coffee beans',76,50,18,60),('Caspia','bicycles',60,48,12,42),('Demer','tablets',90,66,14,64),('Estara','wool blankets',72,58,20,53)]
for n,(country,good,price,large,small,oldprice) in enumerate(trade_data,11):
    id=f'P62D-ITP-M-{n:03}'; imp=n<16; kind='imported' if imp else 'exported'
    supply=small if imp else large; demand=large if imp else small; oldq=(supply+demand)//2
    q=f'Before trade, {country} produces and consumes {oldq} units of {good} at ${oldprice}. After free trade opens at the world price of ${price}, domestic production is {supply} units and consumption is {demand} units. With no inventory change, how many units are {kind}?'
    edit(id,'Add economically relevant autarky information so the student must select the current production and consumption values; preserve the numeric answer.',q=q,feedback=f'Use the quantities after trade opens, not the autarky quantity. {"Imports = consumption − production" if imp else "Exports = production − consumption"} = {large} − {small} = {large-small} units.')
stem('PMA-ITP-M-010','After an importing market opens, domestic consumers gain $90 of surplus while domestic producers lose $55. Which statement best describes the national welfare effect?')
for n,kind in [(4,'consumer'),(5,'producer'),(6,'producer'),(7,'consumer'),(32,'consumer'),(34,'producer')]: stem(f'P62D-ITP-H-{n:03}',f'Refer to the graph. What is {kind} surplus at the world price, Pw?')
for n in range(9,15):
    id=f'P62D-ITP-C-{n:03}'; q=B[id]['q']['q']
    q=q.replace('In Arden\'s linear market,','In Arden,').replace('In Bellora\'s linear market,','In Bellora,').replace('In Caspia\'s linear market,','In Caspia,').replace('no-trade','before-trade').replace('consumer surplus with imports','consumer surplus after trade opens').replace('producer surplus with imports','producer surplus after trade opens').replace('Calculate the consumer-surplus change.','What is the change in consumer surplus?').replace('Calculate the producer-surplus change.','What is the change in producer surplus?')
    stem(id,q); difficulty(id,'easy')
# Linear markets preserve the existing answers, now derived from P and Q.
markets=[('Arden',80,20,50,30,70,10,50,30),('Bellora',94,26,60,34,76,18,50,42),('Caspia',72,12,42,30,60,12,48,20)]
for j,(country,di,si,pa,qa,pw,qd,qs,pimp) in enumerate(markets):
    for base,kind,intercept,qtrade in [(15,'consumer',di,qd),(18,'producer',si,qs)]:
        id=f'P62D-ITP-C-{base+j:03}'
        if kind=='consumer': old=.5*(di-pa)*qa; new=.5*(di-pw)*qtrade; expr=f'Before: ½ × ({di} − {pa}) × {qa} = ${old:g}. After: ½ × ({di} − {pw}) × {qtrade} = ${new:g}.'
        else: old=.5*(pa-si)*qa; new=.5*(pw-si)*qtrade; expr=f'Before: ½ × ({pa} − {si}) × {qa} = ${old:g}. After: ½ × ({pw} − {si}) × {qtrade} = ${new:g}.'
        q=f'{country} has a straight {"demand" if kind=="consumer" else "supply"} curve with a price-axis intercept of ${intercept}. Before trade, price is ${pa} and quantity is {qa}. With exports, price rises to ${pw} and domestic {"consumption" if kind=="consumer" else "production"} becomes {qtrade}. What is the change in {kind} surplus?'
        edit(id,'Replace supplied surplus answers with the prices, intercept, and quantities needed to calculate the areas.',q=q,feedback=expr+f' {kind.title()} surplus {"rises" if new>old else "falls"} by ${abs(new-old):g}.')
    id=f'P62D-ITP-C-{21+j:03}'; qim=di-pimp; sim=pimp-si
    cs=.5*(di-pimp)*qim; ps=.5*(pimp-si)*sim; old=.5*(di-si)*qa
    edit(id,'Require calculation of consumer and producer surplus before comparing total surplus across trade regimes.',q=f'{country} has straight demand and supply curves with price-axis intercepts of ${di} and ${si}. Without trade, price is ${pa} and quantity is {qa}. Free trade lowers price to ${pimp}; consumption becomes {qim} and domestic production {sim}. What is the gain in total surplus from trade?',feedback=f'Before trade, CS + PS = ½ × ({di} − {si}) × {qa} = ${old:g}. With trade, CS = ½ × ({di} − {pimp}) × {qim} = ${cs:g}; PS = ½ × ({pimp} − {si}) × {sim} = ${ps:g}. Gain = ${cs+ps:g} − ${old:g} = ${cs+ps-old:g}.')
replace('P62D-ITP-C-030','A small importing country imposes a $5 per-unit tariff. Domestic production rises from 20 to 38 units and domestic consumption falls from 70 to 48 units. Demand and supply are linear. What is total deadweight loss?', ['$45','$100','$55','$155'],1,'Production distortion = ½ × $5 × (38 − 20) = $45. Consumption distortion = ½ × $5 × (70 − 48) = $55. Total DWL = $100.','Replace supplied distortion losses with the tariff and quantity changes required to compute both triangles.')
for n,kind in [(36,'production-side'),(37,'consumption-side'),(38,'total')]: stem(f'P62D-ITP-H-{n:03}',f'Refer to the graph. What is the {kind} deadweight loss due to the tariff?')
for id,text in {'P62D-ITP-M-029':'Credible learning benefits that exceed temporary protection costs','P62D-ITP-M-030':'Aggregate gains can coexist with a case for adjustment assistance.','PMA-ITP-M-033':'Credible learning savings exceed the temporary protection costs.','PMA-ITP-M-034':'A critical product faces a specific supply vulnerability.','P62D-ITP-EL-004':'Gains can fund compensation, but policy must deliver it.'}.items(): key(id,text)

labor=[('bakery','loaves',7,6),('orchard','crates',5,9),('warehouse','orders',8,7),('cabinet shop','doors',3,24),('greenhouse','plant flats',10,4),('repair garage','repairs',2,45),('coffee roastery','batches',6,11),('printing company','jobs',9,5),('delivery hub','routes',12,4),('furniture plant','chairs',4,18),('landscaping firm','yards',3,20),('bottling line','cases',15,3),('seafood processor','boxes',8,8),('solar crew','panels',2,40),('laundry','loads',11,5),('catering kitchen','orders',5,13),('machine shop','parts',4,22),('farm stand','baskets',9,7)]
for j,(firm,unit,mp,price) in enumerate(labor):
    id=str(42424+j); prior=30+2*j; wage=mp*price-8
    if j%3==0:
        q=f'A {firm} produces {prior} {unit} per hour with its current staff and {prior+mp} after hiring one more worker. It sells each unit for ${price} and pays the new worker ${wage} per hour. Holding other inputs fixed, what is the new worker’s value of marginal product?'
        fb=f'MPL = {prior+mp} − {prior} = {mp} units per hour. VMP = ${price} × {mp} = ${mp*price} per hour. The wage is a cost, not part of VMP.'
    elif j%3==1:
        q=f'A {firm} sells each unit for ${price}. The next worker adds {mp} {unit} per hour, while average output per existing worker is {mp+3}. The wage is ${wage} per hour. What is the next worker’s value of marginal product?'
        fb=f'Use marginal, not average, product: VMP = ${price} × {mp} = ${mp*price} per hour. Neither the average output nor the wage belongs in that product.'
    else:
        q=f'A {firm} previously sold its output for ${price+2} per unit. The current competitive price is ${price}. The next worker adds {mp} {unit} per hour and earns ${wage} per hour. What is the worker’s current value of marginal product?'
        fb=f'Use the current price: VMP = ${price} × {mp} = ${mp*price} per hour. The former price and the wage do not measure the current value added.'
    edit(id,'Add a relevant competing quantity, price, or wage and require selection of the marginal contribution; retain the Medium task and numeric key.',q=q.replace('A orchard','An orchard'),feedback=fb)

if __name__=='__main__': save()
