"""Bounded consistency sweep: only demonstrated wrapper/duplicate families.

Faculty precedents: adverse-selection42901/42908/42916, behavioral42970–43032,
and the explicit instruction to replace repeated wrappers with distinct tasks.
No PASS, ECON-MG, repair, bridge or retest record is changed here.
"""
from author import *
U={}
def revise(id,q,correct,wrong,feedback):
    assert M[id]['state']=='UNREVIEWED' and not id.startswith('ECON-MG')
    assert B[id]['q'].get('instructionalRole') not in {'repair','bridge','retest'}
    a=B[id]['answer'];opts=wrong.copy();opts.insert(a,correct)
    reason='High-confidence unreviewed sibling: identical causal task repeated under interchangeable introductory wrappers. Apply the faculty standard demonstrated by42901/42908/42916 and42970–43032; retain concept, cognitive tier, role, skills and routes.'
    P[id]={'q':q,'options':opts,'feedback':feedback,'correct_index':a,'rationale':[reason]}
    U[id]={'reason':reason,'faculty_precedents':['42901','42908','42916','42970','43032'],'scope':'unreviewed repeated information-asymmetry family'}

revise('42924','Why can requiring an insured customer to pay a deductible reduce moral hazard?','The customer bears part of the loss caused by less care.',['The insurer learns every customer’s preexisting risk.','The deductible makes prevention physically unnecessary.','The customer no longer faces any uncertainty.'],'A deductible leaves some cost of risky behavior with the insured, increasing the incentive to take care.')
revise('42928','A deductible reduces claims, but some customers also stop buying insurance. Which observation directly supports a reduction in moral hazard?','Customers who remain insured take more care.',['Only low-risk customers leave the insurance pool.','The insurer collects fewer premiums.','The number of insured customers falls.'],'Moral hazard concerns behavior after coverage. Changes in who purchases coverage concern selection and do not by themselves establish greater care.')
revise('42932','An insurer adds a deductible, but a separate employer plan reimburses that deductible in full. What happens to its incentive for the customer to prevent losses?','Reimbursement weakens the incentive created by the deductible.',['Reimbursement makes the customer bear more of each loss.','Reimbursement reveals the customer’s inherited risk.','Reimbursement necessarily eliminates all accidents.'],'If another party fully repays the deductible, the customer does not bear that marginal loss and the intended incentive is weakened.')
revise('42936','A customer can avoid a $100 loss by spending $10 on care. Full insurance repays the loss. If the policy instead leaves the first $20 of the loss uninsured, how does the private incentive change?','Avoiding the deductible can make the $10 precaution worthwhile.',['The customer still bears none of the preventable loss.','Care becomes worthwhile only if it costs more than $20.','The deductible changes the physical loss to $20.'],'Without care the customer now bears $20; spending $10 to avoid it is privately worthwhile. The physical loss remains $100.')
revise('42940','An insurer wants fewer preventable losses, but a higher deductible also exposes customers to more financial risk. Which statement captures the tradeoff?','Stronger incentives for care come with less complete risk protection.',['Higher deductibles necessarily provide more complete insurance.','A deductible can reduce losses only by revealing inherited risk.','Care and financial risk cannot both be affected by a deductible.'],'Cost sharing can discourage risky behavior while reducing the amount of risk transferred to the insurer.')
revise('42922','A driver takes less care after obtaining broad insurance coverage. Which information problem does this illustrate?','Moral hazard',['Adverse selection before coverage','A credible quality signal','Perfectly observed contracting'],'Coverage changes the incentive for an action taken after the contract; this is moral hazard.')
revise('42926','Drivers with high preexisting accident risk are more likely to buy insurance, but no driver changes behavior after buying it. Which conclusion follows?','The pattern is adverse selection, not evidence of moral hazard.',['Every accident after purchase establishes moral hazard.','Insurance has necessarily reduced every driver’s care.','The insurer has eliminated private information.'],'Selection into coverage depends on privately known risk. Moral hazard would require a change in behavior caused by the contract.')
revise('42930','Insured drivers have more accidents than uninsured drivers. What additional comparison helps test whether insurance caused moral hazard?','Compare how otherwise similar drivers change care when coverage changes.',['Compare only the total number of drivers in each group.','Assume all drivers had identical risk before insurance.','Treat each accident as direct evidence of less care.'],'A raw difference may reflect preexisting risk. A credible comparison of behavior under different coverage helps identify the incentive effect.')
revise('42934','A driver’s coverage expands while accident risk and driving conditions remain unchanged. Which response would be inconsistent with the claim that broader coverage reduced care in this case?','The driver maintains exactly the same safety behavior.',['The driver stops paying for a useful safety precaution.','The driver begins leaving the vehicle unlocked.','The driver increases risky driving because losses are covered.'],'Unchanged care does not support the specified behavioral mechanism. Coverage creates an incentive possibility, not proof that every person responds.')
revise('42938','An insurer can verify installation of a theft-prevention device and offers a premium discount for using it. Which problem does the incentive most directly address?','Hidden action after coverage',['Unobserved product quality sold by a car dealer','The absence of risk before coverage','A market-wide shortage of vehicles'],'The contract rewards a verifiable precaution and can reduce insured customers’ incentive to neglect prevention.')
revise('42942','A driver conceals careless behavior after buying insurance. The insurer raises premiums for every customer. Why might that response fail to target the source of moral hazard?','The premium increase need not reward the individual driver for greater care.',['Any higher premium makes all future actions observable.','A uniform premium necessarily eliminates hidden action.','Carelessness must have occurred before the insurance contract.'],'An incentive contract must connect an individual’s action or outcome to a consequence. A uniform price rise alone may leave the relevant marginal incentive unchanged.')
revise('42946','A seller voluntarily offers a warranty that low-quality sellers would find costly to honor. Which mechanism can convey quality?','Signaling by the informed seller',['Screening by an uninformed buyer','Hidden action by the buyer after purchase','A binding legal price ceiling'],'The informed seller takes a credible action whose cost differs with quality, potentially revealing its type.')
revise('42950','A seller advertises a generous warranty but cannot be required to honor it. Why might the promise fail to signal quality?','Low-quality sellers can imitate the promise at little cost.',['Every written promise necessarily reveals quality.','Buyers already observe all product defects.','A warranty can never affect buyers’ beliefs.'],'A signal needs credible incentives or costs. An unenforceable promise may be cheap for every seller to imitate.')
revise('42954','A buyer requires every seller to pass a quality test before making a purchase. Who initiates the information-revealing action?','The less-informed buyer conducts screening.',['The informed seller independently sends a signal.','The buyer creates hidden action after purchase.','The seller eliminates the buyer’s need for information.'],'An uninformed party’s test or contract is screening. It differs from a voluntary action initiated by the informed party.')
revise('42958','A warranty becomes equally cheap for high- and low-quality sellers to honor. What weakens its usefulness as a signal?','Both types can imitate the same warranty at the same cost.',['High-quality sellers become the only firms able to offer it.','The warranty’s name changes product quality automatically.','Buyers must now observe quality perfectly.'],'If costs no longer differ by type, a warranty may no longer separate high- and low-quality sellers.')
revise('42962','A warranty reveals product quality only if low-quality sellers prefer not to copy it. Which fact supports that condition?','Expected repair costs exceed the price premium for low-quality sellers.',['Both types earn the same net gain from offering it.','Low-quality sellers pay no repair claims.','The promise is free and unenforceable for every seller.'],'A separating signal requires imitation to be unattractive for the type it is meant to distinguish.')
revise('42966','A seller offers a credible warranty and then reduces quality because repairs are reimbursed by someone else. Which additional problem has appeared?','Moral hazard in the seller’s later quality choice',['Screening initiated by the buyer before purchase','The disappearance of all hidden actions','Proof that the original quality signal was costless'],'A signal can coexist with later hidden action. Insulation from repair costs may weaken the seller’s incentive to maintain quality.')
revise('42948','Why can a credential reveal productivity when it is more costly for low-productivity workers to obtain?','Different net benefits can lead the two types to choose differently.',['The credential must physically raise every worker’s productivity.','All workers must find it equally attractive to obtain.','Employers must observe productivity before seeing the credential.'],'A cost difference can support separation if high-productivity workers want the credential and low-productivity workers do not.')
revise('42952','A credential costs both worker types $2,000 and gives each a $5,000 wage premium. Can these payoffs alone separate the types?','No; both types gain by obtaining it.',['Yes; only high-productivity workers gain.','Yes; neither worker type gains.','No; the credential must reduce wages.'],'Each type gains $3,000. Equal incentives to obtain the credential do not separate the types.')
revise('42956','A credential has no effect on productive skill but is harder for low-productivity workers to earn. Could it still convey information?','Yes, if the different costs induce different choices by type.',['No, because only training can affect employers’ beliefs.','Yes, because every worker must obtain it.','No, because signaling requires identical costs for both types.'],'A signal can reveal an existing characteristic without causing that characteristic; credibility depends on incentives to imitate.')
revise('42960','A credential raises productive skill equally for all workers. Does that benefit alone establish that the credential separates workers by their prior productivity?','No; skill formation alone does not establish separation by prior type.',['Yes; all training is necessarily a separating signal.','Yes; equal skill gains imply different credential costs.','No; credentials can never both teach and signal.'],'Human-capital formation and signaling are distinct mechanisms. Evidence of one does not, by itself, demonstrate the other.')
revise('42964','High-productivity workers gain $8,000 from a credential and pay $2,000 to earn it. Low-productivity workers gain $3,000 and pay $5,000. Which outcome is supported?','Only high-productivity workers choose the credential.',['Both types choose the credential.','Only low-productivity workers choose the credential.','Neither type chooses the credential.'],'The high type has a positive net benefit of $6,000; the low type has a net cost of $2,000. These payoffs support separation.')

# Natural direct wording is justified for these isolated wrappers; substantive
# distinct questions and all remedial items are preserved.
for id in ['42923','42925','42939','42947','42949','42963','43052','ECON-EC-MEDIUMBOSS-18018']:
    q=B[id]['q'];s=re.sub(r'^(In this setting, |An economist observes that |Evidence indicates that )','',q['q']);s=s[0].upper()+s[1:]
    assert M[id]['state']=='UNREVIEWED'
    P[id]={'q':s,'correct_index':B[id]['answer'],'rationale':['Remove the demonstrated empty attribution wrapper; retain the existing distinct causal task and structural role.']}
    U[id]={'reason':P[id]['rationale'][0],'faculty_precedents':['43006','42980','42987'],'scope':'unreviewed direct wording'}
(HERE/'unreviewed_scope.json').write_text(json.dumps(U,ensure_ascii=False,indent=2),encoding='utf-8')
