from author import *

monopoly_variants={
'P62G-MON-L-024':('Timberline Software faces unchanged downward-sloping demand and rising marginal cost. A production innovation lowers marginal cost by $6 at every output. Assuming an interior profit maximum, how will its output and price change?', ['Both remain unchanged because demand is unchanged.','Output falls and price rises.','Output rises and price rises.','Output rises and price falls.'],3,'Lower MC moves MR = MC to a larger quantity; demand then determines a lower price.'),
'P62G-MON-L-027':('Union Transit faces unchanged demand and marginal cost. Its unavoidable fixed license fee rises by $500. The firm continues operating. What happens to its profit-maximizing price and output?', ['Both rise to cover the fee.','Price rises and output falls.','Both remain unchanged, while profit falls by $500.','Output rises until total revenue covers the fee.'],2,'An unavoidable fixed fee does not change MR or MC. The operating optimum is unchanged and profit falls by the fee increase.'),
'P62G-MON-L-030':('Valley Minerals receives a $4 subsidy for each unit it sells. Demand and production costs are unchanged. At an interior optimum, how should it account for the subsidy?', ['Add $4 to marginal cost and reduce output.','Add $4 to marginal revenue and expand output.','Add $4 to fixed cost without changing output.','Raise the customer price by exactly $4.'],1,'The subsidy increases revenue from each additional unit. MR + $4 = MC occurs at a larger output under the usual downward MR and upward MC curves.'),
'P62G-MON-L-033':('Westbridge Media faces P = 60 − Q and MR = 60 − 2Q, with constant MC = $12. A $6 per-unit tax is introduced. What happens to output and the price paid by customers?', ['Output falls from 24 to 21; price rises from $36 to $39.','Output falls from 24 to 18; price rises from $36 to $42.','Output stays at 24; price rises from $36 to $42.','Output rises from 24 to 27; price falls from $36 to $33.'],0,'Initially 60 − 2Q = 12 gives Q = 24 and P = $36. With the tax, effective MC = $18, so Q = 21 and P = $39. The monopolist does not pass through the full $6 tax.'),
'P62G-MON-L-036':('Xenon Medical Patent faces a new $9 per-unit production tax. Demand is unchanged, MR slopes downward, and MC slopes upward. A manager proposes keeping output unchanged and raising price by $9. What is wrong with that plan?', ['A monopolist can never change its price.','The tax changes only fixed cost.','Higher MC makes profit-maximizing output increase.','Price and quantity must stay on demand; the new MR = MC output is lower.'],3,'The monopolist cannot independently choose price and quantity. Higher effective MC reduces the optimal quantity, and the demand curve determines the new price.'),
'P62G-MON-L-039':('Yellowstone Fiber can choose either a $1,000 unavoidable annual license fee or a $5 fee per unit. It operates under either option. Which policy directly changes its MR = MC output condition?', ['Only the annual fee, because it is the larger dollar amount.','Both fees shift marginal cost by their stated amounts.','Only the per-unit fee, because it raises the cost of an additional unit.','Neither fee, because monopoly output ignores cost.'],2,'The annual fee affects fixed cost and profit. The per-unit fee raises effective marginal cost and therefore changes output incentives.'),
'P62G-MON-L-042':('Zenith Waterworks reduces marginal cost by $7 at every output, but its demand curve also shifts inward. Can the direction of its profit-maximizing output change be determined from this information alone?', ['Yes; output must rise because cost fell.','No; the cost reduction and demand decline have opposing output effects.','Yes; output must fall because demand declined.','No; marginal cost never affects monopoly output.'],1,'Lower MC tends to increase output while lower demand and MR tend to reduce it. Their relative sizes are needed to determine the net output change.')}
for id,(q,o,a,f) in monopoly_variants.items(): replace(id,q,o,a,f,'Diversify the faculty-flagged repeated cost-shift family using fixed costs, subsidies, tax incidence, error diagnosis, and competing shifts.')
for n in [15,17,19]:
    id=f'P62G-MON-H-{n:03}'; stem(id,B[id]['q']['q'].replace('Which sequence correctly solves the problem?','Which sequence determines the monopolist’s profit or loss?'))
id='P62G-MON-H-007'; opts=B[id]['q']['options'].copy(); opts[1]='$200; the gap between ATC and AVC, multiplied by output.'; edit(id,'Add the faculty-requested competing $200 option so the value alone does not reveal the key.',options=opts)
for n in range(2,36,3):
    id=f'P62G-MON-LB-{n:03}'; stem(id,B[id]['q']['q'].replace(' Keep full precision until rounding profit or loss to cents.',''),'Remove the faculty-identified final sentence; the data and keyed rounded result are unchanged.')
stem('P62G-MON-M-024','A monopolist charges $66.19, compared with a competitive benchmark price of $26.36 in the same market. With no external costs or benefits, which statement about welfare is correct?')
stem('P62G-MON-H-014','The competitive benchmark quantity is 40 units, while a single-price monopolist with the same costs produces 20. Why are these quantities different?')
replace('P62G-MON-H-016','A single-price monopolist produces 17 units. At that output, MR equals MC, but price is above MC. With no external costs or benefits, would a small increase in output create a gain for society?', ['No; maximizing monopoly profit also maximizes total surplus.','No; a price above MC shows that buyers value the unit too little.','Yes; any increase in production is socially beneficial.','Yes; marginal willingness to pay exceeds marginal cost.'],3,'The demand price measures marginal willingness to pay. When P > MC, a small increase in output has a positive marginal social gain, even though selling it may not increase the monopolist’s profit.','Replace the repeated rule comparison with a welfare inference and remove unused equations.')
replace('P62G-MON-H-018','A manager tells a single-price monopolist to expand until price equals marginal cost. Why would this generally exceed the profit-maximizing quantity when demand slopes downward?', ['Price equals marginal revenue at every output.','At that quantity, marginal revenue is below marginal cost.','Average total cost must be zero at that quantity.','A monopolist maximizes profit by serving every willing buyer.'],1,'Selling more requires lowering price on existing sales, so MR < P. At P = MC, MR < MC; the firm could raise profit by reducing output.','Replace the duplicated comparison with diagnosis of an incorrect production rule.')
replace('P62G-MON-H-020','A regulator wants a monopoly with no externalities to produce the competitive benchmark quantity. Which condition identifies that quantity, and what additional information is needed to know whether the regulated firm covers total cost?', ['MR = MC; only the number of customers.','P = ATC; only the elasticity of supply.','Minimum ATC; only the firm’s fixed cost.','P = MC; average total cost at that output.'],3,'P = MC identifies the efficient quantity without externalities. Comparing that price with ATC reveals whether total revenue covers total cost.','Use the competitive benchmark in a regulation task instead of repeating the same comparison.')
stem('P62G-MON-H-039','Refer to the graph. How much output is withheld by the unregulated monopoly relative to the competitive outcome?')
for n in [3,4,5]:
    id=f'P62I-OLI-H-{n:03}'; s=re.sub(r'market-share chart (?:for market )?\d','market-share chart',B[id]['q']['q']); stem(id,s,'Remove the internal chart number only.')
for n in [5,6,7]:
    id=f'P62I-OLI-C-{n:03}'; stem(id,re.sub(r'market C\d','this market',B[id]['q']['q']),'Remove the internal market label.')
stem('PM8-OLI-BR-026','Each cell in the payoff matrix gives (Row payoff, Column payoff). Which outcomes are pure-strategy Nash equilibria?<table><caption>Payoffs by strategy</caption><thead><tr><th scope="col">Row strategy</th><th scope="col">Column X</th><th scope="col">Column Y</th></tr></thead><tbody><tr><th scope="row">A</th><td>(4, 3)</td><td>(1, 1)</td></tr><tr><th scope="row">B</th><td>(2, 0)</td><td>(3, 2)</td></tr></tbody></table>','Use a semantic HTML table with caption and scoped headers; retain both mutual best responses.')
for id in ['P62I-OLI-EL-002','P62I-OLI-EL-004','P62I-OLI-EL-006','P62I-OLI-LB-006']:
    stem(id,'Refer to the payoff matrix. Which outcome is the pure-strategy Nash equilibrium, and which outcome maximizes the firms’ combined payoff?','Honor the request for direct wording while retaining joint-payoff terminology: a Pareto-efficient outcome need not be an equilibrium or uniquely maximize combined payoff.')
edit('PM8-OLI-H-046','Shorten the key and give a competing causal explanation comparable detail.',options=['Matching fare increases prove that the airlines reached an agreement.','Each airline must have the same dominant strategy in every market.','Independent firms cannot raise fares at the same time.','A shared fuel-cost increase can explain matching fares without collusion.'])
edit('PM8-OLI-M-064','Use parallel assessments of the competing merger effects.',options=['Research spending lowers concentration even with fewer competitors.','Weigh innovation gains against the cost of weaker competition.','A larger research budget proves consumers will benefit overall.','Possible innovation gains eliminate any cost of reduced rivalry.'])
stem('P62F-PC-R-003','In a perfectly competitive market, which of these curves slopes downward?','Preserve the distinction between market demand and the individual firm’s horizontal demand; the suggested phrase “for the firm” would obscure that distinction.')
stem('P62F-PC-E-003','Which option can a price-taking firm pursue?')
stem('P62F-PC-H-036','Refer to the graph. What is the firm’s total revenue at the loss-minimizing output?')
stem('P62F-PC-H-040','Refer to the graph. What is the representative firm’s total revenue?')
replace('P62F-PC-C-004','A competitive firm begins the week with 4 units in inventory, produces 30 more, and ends with 8 unsold units. It sells at the market price of $31 per unit. A separate $50 refund from a supplier reduces last month’s costs. This week’s fixed cost is $120 and variable production cost is $450. What is this week’s revenue from product sales?', ['$1,054','$930','$856','$806'],3,'Units sold = 4 + 30 − 8 = 26. Sales revenue = 26 × $31 = $806. Production is not the same as sales, and neither cost figures nor a supplier refund are product sales revenue.','Require inventory reconciliation before calculating revenue, with relevant competing cost and cash-flow information.')

if __name__=='__main__': save()
