from author import *

stem('ECON-MG-LEGENDARY-9017','Refer to the graph and compare two changes. First, the market starts at D1 and S1 and changes to D2 and S1. Second, it starts at D1 and S1 and changes to D1 and S2. Which statement classifies both changes and the ending equilibria?')
difficulty('ECON-MG-LEGENDARY-9017','elite')
stem('42334',B['42334']['q']['q'].replace('At the old wage,','The initial equilibrium wage is $20. At that wage,'),'Supply the missing initial wage explicitly.')
replace('P62B-ELAS-H-034','Refer to the graph. Using the midpoint method, compare demand over the entire interval from C to A. Which conclusion follows? Use elasticity = |percentage change in quantity ÷ percentage change in price|, with average quantity and price as the bases.', ['Elasticity is 3; total revenue must rise between the endpoints.','Elasticity is 1; the endpoints have equal total revenue.','Elasticity is 1/3; total revenue must fall between the endpoints.','Elasticity is 1; demand has the same point elasticity everywhere.'],1,'At C, P = $12 and Q = 30; at A, P = $4 and Q = 90. Midpoint elasticity = |(60/60)/(−8/8)| = 1. Both endpoint revenues are $360. This interval result does not imply constant point elasticity.','Replace the duplicated point-elasticity task with an interval calculation and interpretation.')
key('P62B-ELAS-L-046','Prices and quantities are needed to compare elasticities.')
key('P62B-ELAS-L-071','Elasticity can change over a large price range.')
stem('P62B-ELAS-BR-013','A good’s price changes, causing its quantity demanded to change. Which elasticity measures this proportional response?')
replace('P62B-ELAS-L-073','A good’s price rises from $8 to $12 and quantity demanded falls from 120 to 80. Which expression correctly calculates the absolute value of midpoint price elasticity?', ['|(12 − 8)/10| ÷ |(80 − 120)/100|','|(80 − 120)/120| ÷ |(12 − 8)/8|','|(80 − 120)/100| ÷ |(12 − 8)/10|','|(80 − 120)/(12 − 8)|'],2,'Use average quantity (120 + 80)/2 = 100 and average price (8 + 12)/2 = 10. Midpoint elasticity is |−40/100| ÷ |4/10| = 1.','Replace derivative notation with the midpoint method appropriate to Principles.')
midpoints={'P62B-ELAS-H-002':(18,21,800,680),'P62B-ELAS-H-003':(14,11,500,650),'P62B-ELAS-H-005':(35,40,900,765),'P62B-ELAS-H-006':(50,44,600,720),'P62B-ELAS-H-007':(60,66,1000,850),'P62B-ELAS-H-008':(16,20,1500,1170),'P62B-ELAS-H-009':(250,225,400,480),'P62B-ELAS-B2-005':(50,45,800,960),'P62B-ELAS-B2-006':(100,115,900,720),'P62B-ELAS-C-010':(140,126,800,1000)}
for id,(p1,p2,q1,q2) in midpoints.items():
    e=abs(((q2-q1)/((q1+q2)/2))/((p2-p1)/((p1+p2)/2)))
    assert abs(float(B[id]['q']['options'][B[id]['answer']])-e)<.006
    edit(id,'Honor the Fix Feedback instruction over the less-specific issue category; recompute the midpoint result independently.',feedback=f'The elasticity of demand is determined by the midpoint formula: |[(Q2 − Q1)/((Q1 + Q2)/2)] ÷ [(P2 − P1)/((P1 + P2)/2)]|. Substituting: |[({q2} − {q1})/{(q1+q2)/2:g}] ÷ [({p2} − {p1})/{(p1+p2)/2:g}]| ≈ {e:.2f}. Demand is elastic over this interval.')
key('P62B-ELAS-B3-019','Elasticity is zero, but selling the same quantity at a higher price raises revenue.')
edit('P62B-ELAS-LB-011','Use parallel causal conditions instead of an unrelated tax-law distractor.',options=['Demand is unchanged, so the supply shift traces movement along it.','Demand shifts too, so both curves determine the observed movement.','Demand alone shifts, so the observations trace the supply curve.','Income changes demand while the supply curve stays fixed.'])
stem('P62B-ELAS-M-033','Refer to the graph. As price falls from C to B, how responsive is quantity demanded in percentage terms? Classify demand over this interval.')
stem('P62B-ELAS-EL-031','Refer to the graph. As you move from C to B, how is demand best classified?')
edit('P62B-ELAS-EL-031','Use parallel elasticity classifications.',options=['Inelastic over C–B','Perfectly inelastic over C–B','Elastic over C–B','Unit elastic over C–B'])
stem('P62B-ELAS-EL-035','Refer to the two marked points on D2. When price falls between these points, does the change in total revenue indicate elastic, inelastic, or unit-elastic demand?')
key('P62B-ELAS-B3-004','Revenue rises about 2.6%; the price increase outweighs the quantity decrease.')
replace('P62B-ELAS-L-076','Supply is Q = 10 + 3P. Price rises from $8 to $12. Use the midpoint method to calculate supply elasticity: percentage change in quantity divided by percentage change in price, using average values.', ['1.33','0.75','3.00','4.00'],1,'Q rises from 34 to 46. Midpoint elasticity = [(46 − 34)/40] ÷ [(12 − 8)/10] = 0.30/0.40 = 0.75.','Replace calculus-based point elasticity with a midpoint calculation.')
replace('P62B-ELAS-L-077','Supply is Q = −20 + 4P. Price rises from $8 to $12. What is midpoint supply elasticity, using average quantity and average price as the percentage-change bases?', ['0.50','4.00','2.00','0.25'],2,'Quantity rises from 12 to 28. Midpoint elasticity = [(28 − 12)/20] ÷ [(12 − 8)/10] = 0.80/0.40 = 2.','Replace calculus-based point elasticity with a midpoint calculation.')
replace('P62B-ELAS-L-078','A linear supply curve passes through the origin: Q = 5P. Compare price increases from $4 to $8 and from $8 to $12 using the midpoint method. What are the two supply elasticities?', ['0 for both intervals','2 for the first and 0.5 for the second','0.5 for the first and 2 for the second','1 for both intervals'],3,'For $4 to $8: Q rises 20 to 40, so (20/30)/(4/6) = 1. For $8 to $12: Q rises 40 to 60, so (20/50)/(4/10) = 1. A linear supply curve through the origin is unit elastic.','Replace point-elasticity calculus with two midpoint comparisons.')
for id,r in M.items():
    if r['state']=='FACULTY FLAG' and 'dev tools' in r['note']:
        disposition(id,'NO CHANGE — FACULTY INTENT CONFLICT','Faculty raises a concern about pre-answer developer-tools access, without proposing replacement teaching content. The controlling remediation instruction explicitly prohibits degrading explanatory feedback to conceal the key. Existing feedback correctly explains the answer; preserve it and record the client-side disclosure concern separately.')
stem('ECON-MG-MEDIUM-170','Refer to the graph. What are the equilibrium price and quantity?')
replace('40028','Refer to the graph. What does the $15 minimum wage create in this labor market?', ['A surplus of 100 thousand workers','A shortage of 50 thousand workers','A surplus of 150 thousand workers','A shortage of 250 thousand workers'],0,'At $15, labor supplied is 250 thousand and labor demanded is 150 thousand. The difference is a surplus of 100 thousand workers.','Ask for both the direction and size of the labor-market imbalance.')
replace('42790','An economy’s Gini coefficient falls from 0.34 to 0.26 while mean income stays unchanged. What can be concluded from these figures?', ['Every household’s income rose.','The poverty rate fell by eight percentage points.','Relative income inequality decreased.','The source of every income gap has been identified.'],2,'A lower Gini indicates less relative inequality. It does not by itself identify poverty incidence, individual income changes, or causes.')
replace('42792','Two economies both have a Gini coefficient of 0.34, but one has twice the mean income of the other. Which claim is supported?', ['They have the same Gini measure of relative inequality.','They have the same mean income.','They have the same fraction of residents below every poverty line.','They must have identical income distributions in dollars.'],0,'The Gini summarizes relative inequality and is independent of the average income level. Equal Ginis do not imply identical distributions.')
replace('42793','A report states that a Gini coefficient of 0.38 means 38% of households are poor. What is the error?', ['The Gini must be expressed as mean income.','The Gini measures relative inequality, not the poverty rate.','A positive Gini means everyone has the same income.','The Gini identifies the policy that caused poverty.'],1,'Poverty requires an income threshold. The Gini measures dispersion relative to equality, not the percentage below that threshold.')
for id,opts in {
'42845':['The voucher can be spent entirely on rent.','The voucher excludes the preferred $40-food bundle.','The voucher reduces all prices by 60%.','The voucher offers more options than equal cash.'],
'42847':['Every restriction must reduce welfare.','The voucher raises cash income by $200.','The voucher limits food spending to $100.','The preferred cash bundle remains affordable.'],
'42849':['The spillover guarantees recipients prefer tutoring.','Cash allows more choice; spillovers may justify targeting.','More private choice guarantees greater social benefit.','Equal fiscal costs eliminate the spillover issue.']}.items(): edit(id,'Shorten the key and make alternatives structurally parallel.',options=opts)
for id,text in {'42886':'Quality and effort are verifiable; private valuations can still differ.','42887':'Verified quality lets reliable sellers distinguish their products.','42894':'Contingent payment links verified effort to enforceable incentives.'}.items(): key(id,text)

# Vary the requested shares and the operation, not only the economy label.
income_tasks={
'42762':('Income shares from the poorest to richest quintile are 3%, 8%, 14%, 25%, and 50%. What share belongs to the richest 20%?', ['25%','80%','50%','75%'],2,'The richest quintile is the highest-income fifth of the population, whose share is 50%.'),
'42766':('The poorest 80% receive 54% of total income. What share goes to the richest quintile?', ['20%','54%','46%','80%'],2,'Income shares total 100%, so the richest quintile receives 100% − 54% = 46%.'),
'42770':('The richest quintile receives 42% of total income. A student labels that group as the richest 42% of people. What is the correct interpretation?', ['42% of people receive 20% of income.','20% of people receive 20% of income.','20% of people receive 42% of income.','42% of people receive 42% of income.'],2,'A quintile is 20% of the population. Its income share need not equal its population share.'),
'42774':('Income shares from poorest to richest are 7%, 12%, 17%, 25%, and 39%. Does the richest quintile receive more income than the poorest two quintiles combined?', ['No; 39% is less than 40%.','No; 25% exceeds 19%.','Yes; 39% exceeds 19%.','Yes; 39% exceeds 7% but not 19%.'],2,'The poorest two quintiles receive 7% + 12% = 19%; the richest receives 39%.'),
'42778':('The richest quintile receives 44% of an economy’s $500 million total income. How much income does it receive?', ['$100 million','$280 million','$220 million','$440 million'],2,'0.44 × $500 million = $220 million.'),
'42782':('The richest quintile’s share falls from 48% to 43%, with total income unchanged. By how many percentage points does the combined share of the other four quintiles rise?', ['43','10.4','5','48'],2,'The remaining share rises from 52% to 57%, an increase of 5 percentage points.'),
'42763':('Income shares from poorest to richest are 4%, 11%, 18%, 27%, and 40%. What cumulative income share belongs to the poorest 40%?', ['11%','40%','29%','15%'],3,'The bottom 40% comprises two quintiles: 4% + 11% = 15%.'),
'42767':('The bottom quintile receives 6% of income and the bottom 40% receive 19%. What share belongs to the second quintile alone?', ['19%','25%','40%','13%'],3,'Subtract the first quintile from the cumulative share: 19% − 6% = 13%.'),
'42771':('Quintile income shares from poorest to richest are 2%, 9%, 16%, 28%, and 45%. Which point belongs on the Lorenz curve at a population share of 60%?', ['(60%, 16%)','(60%, 60%)','(60%, 45%)','(60%, 27%)'],3,'The poorest three quintiles receive 2% + 9% + 16% = 27%.'),
'42775':('Quintile income shares from poorest to richest are 5%, 12%, 18%, 25%, and 40%. A student uses 12% as the cumulative share of the bottom 40%. What was omitted?', ['The richest quintile’s 40% share.','The third quintile’s 18% share.','The population share of 40%.','The poorest quintile’s 5% share.'],3,'The cumulative bottom-40% share includes the first two quintiles: 5% + 12% = 17%.'),
'42779':('The bottom 40% receive 18% of total income, while the bottom 60% receive 36%. What share belongs to the middle quintile?', ['36%','54%','20%','18%'],3,'The middle quintile is the additional population from 40% to 60%: 36% − 18% = 18%.'),
'42783':('Quintile shares are 6%, 13%, 18%, 26%, and 37%, from poorest to richest. The total income is $200 million. How much goes to the bottom 40%?', ['$26 million','$40 million','$74 million','$38 million'],3,'The bottom 40% receive 6% + 13% = 19%; 0.19 × $200 million = $38 million.'),
'42764':('The bottom four quintiles receive 4%, 10%, 17%, and 24% of income. What share belongs to the richest quintile?', ['45%','55%','24%','76%'],0,'The listed shares total 55%; the remaining share is 100% − 55% = 45%.'),
'42768':('The richest quintile receives 38% of income. What share is received by the other four quintiles combined?', ['62%','38%','80%','20%'],0,'All income shares sum to 100%; 100% − 38% = 62%.'),
'42772':('An income table lists quintile shares of 3%, 9%, 16%, 27%, and 42%. The first four entries are correct. What should the last entry be?', ['45%','42%','55%','58%'],0,'The first four shares sum to 55%; the last must be 45% to make the total 100%.'),
'42776':('The bottom four quintiles together receive 57% of total income. Does the richest quintile receive a majority of all income?', ['No; its share is 43%.','Yes; its share is 57%.','Yes; its population share is 20%.','No; its income share must be 20%.'],0,'The richest quintile receives 100% − 57% = 43%, below one-half.'),
'42780':('The bottom four quintiles receive 8%, 13%, 18%, and 26% of income. Their economy earns $400 million in total. How much income belongs to the richest quintile?', ['$140 million','$260 million','$104 million','$80 million'],0,'The listed shares sum to 65%, leaving 35%; 0.35 × $400 million = $140 million.'),
'42769':('The richest quintile receives 48% of income and the poorest receives 8%. How many times as large is the richest quintile’s share?', ['Four','Six','Forty','Fifty-six'],1,'48% ÷ 8% = 6.'),
'42773':('The richest quintile receives seven times the poorest quintile’s share. If the poorest receives 6%, what share does the richest receive?', ['13%','42%','7%','36%'],1,'7 × 6% = 42%.'),
'42781':('The richest quintile receives 40% of income and the poorest receives 4%. A transfer changes these shares to 36% and 6%, respectively. What happens to their share ratio?', ['It falls from 10 to 9.','It falls from 10 to 6.','It rises from 10 to 12.','It stays at 10.'],1,'The initial ratio is 40/4 = 10; the new ratio is 36/6 = 6.')}
for id,(q,opts,a,fb) in income_tasks.items(): replace(id,q,opts,a,fb,'Implement faculty numerical variety with distinct interpretation, calculation, reverse-calculation, and error-diagnosis tasks; independently recompute shares.')

if __name__=='__main__': save()
