import json
from pathlib import Path
W=Path(__file__).resolve().parent
assets=json.loads((W/'assets.json').read_text('utf8'));spec={};inspection=[]
new={
'ad_ms_md.webp':('Two panels with vertical MS1 and MS2, downward MD, and downward AD1 and AD2.',None),
'MONEY-02.webp':('Money-market diagram with MD0 and vertical MS0 and MS1.','The horizontal axis is quantity of money and the vertical axis is nominal interest rate. The straight downward MD0 line runs from (0,12) to (150,0). Solid MS0 is vertical at quantity 100; its MD0 intersection is at rate 4. Dashed MS1 is vertical at quantity 125; its MD0 intersection is at rate 2. Horizontal dashed guides mark rates 4 and 2.'),
'MONEY-03.webp':('Money-market diagram with MD0 and vertical MS0 and MS1.','The horizontal axis is quantity of money and the vertical axis is nominal interest rate. The straight downward MD0 line runs from (0,12) to (150,0). Solid MS0 is vertical at quantity 100; its MD0 intersection is at rate 4. Dashed MS1 is vertical at quantity 75; its MD0 intersection is at rate 6. Horizontal dashed guides mark rates 4 and 6.'),
'MONEY-04.webp':('Money-market diagram with two vertical MS lines, two downward MD lines and labeled points A, B, C and D.','The horizontal axis is quantity of money; the vertical axis is nominal interest rate. Solid MS0 is vertical at 75 and dashed MS1 at 100. Solid MD0 is the lower straight downward line, through B (75,3) and D (100,1). Dashed MD1 is the upper parallel line, through A (75,6) and C (100,4). MD1 crosses the vertical axis at 12 and the horizontal axis at 150. MD0 crosses the vertical axis at 9. All four points are marked with black dots.'),
'MONEY-AD-03.webp':('Two panels with MS0, MD0 and MD1 on the left and AD0, AD1 and SRAS on the right.','Left panel axes: quantity of money horizontally and nominal interest rate (%) vertically. MS0 is vertical at 75. Solid downward MD0 passes through A (75,2); upper dashed MD1 passes through B (75,4). Right panel axes: real GDP horizontally and price level vertically. Solid AD0 and lower dashed AD1 slope downward; red SRAS slopes upward. AD0 and SRAS meet at A (150,55); AD1 and SRAS meet at B (105,45). Dashed guides identify the point coordinates.'),
'MONEY-AD-01.webp':('Two panels with MD0 and vertical MS0 and MS1 on the left and AD0, AD1 and SRAS on the right.','Left panel axes: quantity of money horizontally and nominal interest rate (%) vertically. Downward MD0 meets solid MS0 at A (100,6) and dashed MS1 at B (150,4). Right panel axes: real GDP horizontally and price level vertically. Solid AD0 and upper dashed AD1 slope downward; red SRAS slopes upward. AD0 meets SRAS at A (100,50); AD1 meets SRAS at B (125,56.25). Dashed horizontal and vertical guides mark those coordinates.'),
'MONEY-AD-02.webp':('Two panels with MD0 and vertical MS0 and MS1 on the left and AD0, AD1 and SRAS on the right.','Left panel axes: quantity of money horizontally and nominal interest rate (%) vertically. Downward MD0 meets solid MS0 at A (125,2.75) and dashed MS1 at B (100,4). Right panel axes: real GDP horizontally and price level vertically. Solid AD0 and lower dashed AD1 slope downward; red SRAS slopes upward. AD0 meets SRAS at A (125,50); AD1 meets SRAS at B (100,45). Dashed horizontal and vertical guides mark those coordinates.')}
for a in assets:
 alt,desc=new.get(a['filename'],(a['imageAlt'],a['graphDescription']));desc=desc or a['graphDescription']
 spec[a['runtimePath']]={'imageAlt':alt,'graphDescription':desc}
 # Shared filenames have equivalent geometry and contracts; source paths remain intact.
 spec[a['filename']]={'imageAlt':alt,'graphDescription':desc}
 changed=(alt!=a['imageAlt'] or desc!=a['graphDescription'])
 inspection.append({'runtimePath':a['runtimePath'],'sha256':a['sha256'],'visuallyInspected':True,'uniqueImageSha256':a['sha256'],'contractCorrected':changed,'reason':'Remove economic conclusions from alt/description while retaining visible axes, labels, intersections, coordinates and guides.' if changed else 'Existing detailed description agrees with visible geometry; retain it unchanged.','imageBytesChanged':False})
(W/'accessibility-spec.json').write_text(json.dumps(spec,indent=2)+'\n','utf8');(W/'accessibility-inspection.json').write_text(json.dumps(inspection,indent=2)+'\n','utf8')
print(len(assets),'inspected;',sum(a['contractCorrected'] for a in inspection),'corrected')
