import json,hashlib,re,copy
from pathlib import Path
W=Path(__file__).resolve().parent
def rd(n):return json.loads((W/n).read_text('utf8'))
def wr(n,x):(W/n).write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n','utf8')
B=rd('inventory-before.json')['records'];S={}
def key(q):return next(o for o in q['options'] if hashlib.sha256(' '.join(o.lower().split()).encode()).hexdigest()==q['aHash'])
def put(id,q,opts,fb,reason,numeric=False):
 assert id in B,id
 S[id]=dict(q=q,options=opts,feedback=fb,reason=reason,numeric=numeric)
def clarify(id,prefix='',suffix='',reason='',numeric=False):
 b=B[id];put(id,prefix+b['q'].strip()+suffix,[key(b)]+[o for o in b['options'] if o!=key(b)],b['feedback'],reason,numeric)
historical='Use U.S. monetary-aggregate definitions in effect before May 2020. '
for id in ['ECON-SP-EASY-5','LG-Q-6','LG-Q-7','LG-Q-103','LG-Q-300','LG-Q-9011','LG-Q-9012','LG-Q-105','LG-Q-202','LG-Q-2002','ECON-SP-DISTINGUISH-M1-M2-5003','LG-R-5005','LG-B-6001']:
 clarify(id,historical,reason='State the historical aggregate convention; current U.S. M1 includes savings deposits, so an unqualified legacy exclusion is ambiguous.',numeric=id in ['LG-Q-300','LG-Q-9011','LG-Q-9012','LG-Q-105','LG-Q-202','LG-Q-2002','LG-B-6001'])
clarify('LG-Q-104',suffix=' Assume these are the only M1 components with nonzero balances.',reason='Make the incomplete component list an explicit closed calculation.',numeric=True)
S['LG-Q-104']['q']='Currency held by the public is $800 billion and checkable deposits are $1,200 billion. Assume these are the only M1 components with nonzero balances. What is M1?'
put('LG-Q-9110','Use current U.S. definitions, in which savings deposits are part of M1. A household shifts $75,000 from checking to savings at the same bank. Later the bank originates a $12,000 loan by crediting another customer’s checking account; no loan is repaid and no other balance changes. Relative to the starting totals, how do M1 and M2 change?',
 ['Both rise by $12,000.','M1 falls by $63,000; M2 rises by $12,000.','Both rise by $87,000.','Both remain unchanged.'],
 'The checking-to-savings transfer changes neither aggregate and does not release reserves. The new loan adds a $12,000 deposit, raising both M1 and M2 by that amount.',
 'Remove the false freed-liquidity claim and link account reclassification to actual loan-created deposits.',True)
put('LG-Q-222','A bank originates a loan by crediting its borrower’s checking account. The borrower then pays a supplier at a different bank, and the payment settles in reserves. Which comparison correctly separates origination from settlement?',
 ['Origination adds a loan and a deposit; settlement reduces the originating bank’s reserves and its borrower’s deposit.','Origination reduces reserves; settlement creates the loan and increases bank capital.','Origination adds reserves and a deposit; settlement leaves both banks’ reserves unchanged.','Origination reduces deposits; settlement cancels the originating bank’s loan asset.'],
 'Crediting the account initially adds a loan asset and a deposit liability. The later outgoing payment reduces reserves and the deposit liability; the loan remains an asset.',
 'Correct conflation of loan origination with reserve settlement.')
clarify('LG-Q-207',prefix='Use the textbook reserve-constrained model, with no other changes. ',suffix=' Assume the borrower immediately pays someone at another bank and the entire payment settles in reserves.',reason='The keyed reserve fall occurs after external settlement, not at origination.',numeric=True)
clarify('LG-Q-301',prefix='Assume the bank cannot obtain extra reserves, sell assets, or retain any new loan proceeds as deposits; every new loan payment would leave the bank. ',reason='Make inability to expand a stated constraint rather than a general prohibition on bank lending.',numeric=True)
simple='Use a hypothetical banking system initially holding exactly its required reserves. The stated reserve ratio stays fixed, banks lend all excess reserves, every loan payment is fully redeposited, and there is no currency drain or other lending constraint. '
for id in ['LG-Q-303','LG-Q-224','LG-Q-2008','P52A-BANK-B3-003','LG-B-6005','LG-Q-314','LG-Q-9019']:
 b=B[id];q=b['q'].strip().replace('a new $','a public cash deposit of $').replace('A new $','A public cash deposit of $')
 # Other legacy wording is clarified by a common explicit source statement.
 q=re.sub(r'(public cash deposit of \$[\d,]+) deposit',r'\1',q)
 q=simple+'The initial deposit comes from currency previously held by the public, and total deposit expansion includes that initial deposit. '+q
 put(id,q,[key(b)]+[o for o in b['options'] if o!=key(b)],b['feedback']+' The initial cash deposit itself replaces public currency with deposits; it is not net new money.', 'Specify source, model assumptions and gross deposit measure without changing the calculation or routing.',True)
put('LG-Q-205','In a hypothetical system, a household deposits $10,000 of currency previously held outside banks. Banks initially meet a fixed 20 percent reserve ratio exactly, lend every new excess reserve dollar, and all loan payments are redeposited without currency drain. No other constraint binds. What are the first bank’s loan and the eventual net increase in currency plus checking deposits?',
 ['First loan $8,000; net money increase $40,000.','First loan $8,000; net money increase $50,000.','First loan $2,000; net money increase $40,000.','First loan $10,000; net money increase $50,000.'],
 'Required reserves on the initial deposit are $2,000, leaving an $8,000 first loan. Total deposits rise by $10,000/0.20 = $50,000, but public currency falls by $10,000. Net money creation is $40,000.',
 'Correct total deposits versus newly created money; retain ordinary Hard reserve arithmetic.',True)
for id in ['LG-Q-9018','LG-Q-9109']:
 clarify(id,prefix='Use a hypothetical fixed-ratio reserve model with no currency drain: every loan payment is fully redeposited, credit demand is sufficient, and no other constraint binds. ',reason='State the assumptions supporting maximum expansion of preexisting excess reserves.',numeric=True)
put('LG-Q-9000','In a hypothetical system with a fixed 12.5 percent reserve ratio, a household deposits $28,000 of existing public currency. Banks initially have no excess reserves. Every bank lends all new excess reserves, all loan payments are redeposited, and no other constraint binds. An analyst counts the first deposit as new money and reports the full deposit increase as money creation. Which set of results diagnoses the error?',
 ['First loan $24,500; deposit increase $224,000; net money increase $196,000.','First loan $24,500; deposit increase $196,000; net money increase $224,000.','First loan $3,500; deposit increase $224,000; net money increase $224,000.','First loan $28,000; deposit increase $196,000; net money increase $168,000.'],
 'The first loan is $28,000 × 0.875 = $24,500. Deposits rise by $28,000/0.125 = $224,000. Subtract the $28,000 decline in public currency to obtain $196,000 of net money creation.',
 'Replace repeated paired arithmetic with linked first-round, system and aggregate reconciliation.',True)
put('LG-Q-9008','In two hypothetical steady states, the public holds no currency and banks have a fixed required-reserve ratio of 10 percent. The observed deposit-to-reserve ratio falls from 8 to 5. Assume all reserves are either required or deliberately held as excess reserves. Which diagnosis fits both observations?',
 ['The excess-reserve share of deposits rose from 2.5 to 10 percent.','The required-reserve ratio rose from 12.5 to 20 percent.','The excess-reserve share of deposits fell from 10 to 2.5 percent.','The public currency-to-deposit ratio rose from 2.5 to 10 percent.'],
 'Total reserves/deposits are the reciprocal of deposits/reserves: 12.5 percent, then 20 percent. Subtract the unchanged 10 percent requirement to infer excess-reserve shares of 2.5 and 10 percent.',
 'Separate observed effective reserve behavior from the legally fixed reserve requirement.',True)
put('LG-Q-9112','A hypothetical system starts with no excess reserves. A public cash deposit of $25,000 enters the first bank. Each bank keeps the fixed 8 percent required reserve and lends the remainder. After each loan, 25 percent of its proceeds stays as public currency and 75 percent is deposited at the next bank. What is the second bank’s loan, and how much smaller is it than under full redepositing?',
 ['$15,870; $5,290 smaller.','$21,160; no reduction.','$17,250; $3,910 smaller.','$5,290; $15,870 smaller.'],
 'The first loan is $23,000. The next deposit is $23,000 × 0.75 = $17,250, of which 92 percent can be lent: $15,870. Full redepositing would permit $21,160, a difference of $5,290.',
 'Require multi-bank propagation with an explicit currency leak instead of repeated unqualified second-round arithmetic.',True)
clarify('LG-Q-209',reason='Replace an at-most target with an exact target so smaller policy operations are not also valid.',numeric=True)
S['LG-Q-209']['q']=S['LG-Q-209']['q'].replace('at most','exactly')
put('LG-Q-9003','In a hypothetical steady-state banking model, the required-reserve ratio is 10 percent, banks hold excess reserves equal to 5 percent of deposits, and the public holds currency equal to 25 percent of deposits. These ratios remain fixed. Money is currency plus deposits; the monetary base is currency plus total reserves. What base increase is needed for a $250 million money increase, and why is the simple 1/required-ratio estimate too small?',
 ['$80 million; both currency holdings and excess reserves absorb base money.','$25 million; every base dollar supports ten dollars of money.','$100 million; currency is excluded from the money measure.','$62.5 million; retaining a fixed fraction once describes every lending round.'],
 'With deposits D, money is 1.25D and the base is (0.25 + 0.10 + 0.05)D = 0.40D. The money/base ratio is 3.125, so the base must rise $250/3.125 = $80 million. The simple multiplier ignores both leakages.',
 'Replace the incoherent one-time 80-percent scalar with a fully specified currency/excess-reserve model and reverse policy target.',True)
put('LG-Q-9010','A hypothetical bank has $600,000 in deposits and $90,000 in reserves. The required-reserve ratio rises from 10 to 15 percent. The bank cannot obtain new reserves, and any additional loan payment would settle at another bank. Which conclusion distinguishes its reserve position from its ability to expand?',
 ['It meets the new requirement exactly, but has no excess reserves for an outgoing loan.','It has a $30,000 reserve deficit and must obtain reserves just to comply.','It retains $30,000 of excess reserves because deposits have not changed.','It must shrink deposits by $90,000 even if it makes no new loan.'],
 'Required reserves rise from $60,000 to $90,000, exactly equal to actual reserves. The bank is compliant but the specified settlement constraint prevents further outgoing lending without adjustment.',
 'Correct the implication that a fully compliant bank must acquire reserves; distinguish compliance from expansion.',True)
put('LG-Q-9114','A policy memo claims that supplying more reserves guarantees the full textbook deposit expansion, even when creditworthy firms postpone borrowing and banks retain excess reserves. Which correction addresses both breaks in the argument?',
 ['Banks must be willing to lend and borrowers willing to borrow; unused reserves do not guarantee new deposits.','Only the reserve requirement matters; banks and borrowers cannot alter the predicted expansion.','Borrower caution raises the multiplier because fewer loans consume fewer reserves.','Excess reserves are already customer deposits, so the predicted expansion has occurred.'],
 'The reserve injection is an input to a conditional model. Both bank decisions and credit demand can prevent the lending and redepositing needed to reach its maximum.',
 'Restore the missing claim and require diagnosis of two distinct private-behavior constraints.')
put('LG-Q-9108','In a hypothetical banking system initially without excess reserves, the public deposits $56,000 of existing currency. The required-reserve ratio stays at 20 percent. Each bank lends all excess reserves; after every loan, 25 percent stays as currency and 75 percent reaches the next bank. No other constraint binds. Including the initial deposit, what is the eventual deposit increase, and what is the net increase in currency plus deposits?',
 ['Deposits rise $140,000; net money rises $112,000.','Deposits rise $280,000; net money rises $224,000.','Deposits rise $140,000; net money rises $140,000.','Deposits rise $112,000; net money rises $84,000.'],
 'Successive deposits have ratio 0.80 × 0.75 = 0.60, so their sum is $56,000/(1 − 0.60) = $140,000. Total loans are 0.80 × $140,000 = $112,000; $28,000 returns to public currency. Currency changes by −$56,000 + $28,000, so net money rises $112,000.',
 'Replace a qualitative upper checkpoint with a complete repeated-leakage reconciliation.',True)
put('LG-Q-9006','In a hypothetical fully loaned-up system with a fixed 10 percent reserve ratio and no excess reserves, the public permanently switches $36 million from deposits to currency. The monetary base stays fixed. Banks restore their reserve ratios through loan repayments that destroy deposits; there are no defaults or other changes. What are the final changes in deposits and in currency plus deposits?',
 ['Deposits fall $360 million; money falls $324 million.','Deposits fall $36 million; money is unchanged.','Deposits fall $360 million; money falls $396 million.','Deposits fall $324 million; money falls $360 million.'],
 'Currency rises $36 million and reserves fall $36 million. At reserves/deposits = 0.10, deposits must fall $360 million in total. Money changes by +$36 million − $360 million = −$324 million.',
 'Make contraction mechanics and public currency accounting explicit rather than implying that withdrawal itself destroys money.',True)
put('ECON-SP-MEDIUM-142','Refer to the money-market graph. With MD1 unchanged, money supply increases from MS1 to MS2. Which equilibrium movement follows?',
 ['e to g','g to e','a to d','c to f'],
 'MD1 intersects MS1 at e and MS2 at g. Increasing supply moves equilibrium from e to g and lowers the nominal interest rate.',
 'Correct a reversed answer key and feedback using visible MS1/MS2 intersections.')
put('PG4-MM-L-004','Refer to the graph. The economy starts at B with MD0 and MS0. Money demand changes to MD1. The central bank increases money supply to MS1, but wants to restore B’s original nominal interest rate. If the straight MD1 line continues as drawn, approximately how much additional money beyond MS1 is needed?',
 ['12.5 units; a total money quantity of 112.5.','25 units; a total money quantity of 125.','No additional money; C already restores the original rate.','75 units; a total money quantity of 175.'],
 'B’s rate is 3. MD1 passes through A at (75,6) and C at (100,4), a fall of 2 rate points per 25 money units. A further 1-point fall requires 12.5 additional units, beyond MS1 at 100.',
 'Use actual graph slope and a reverse policy target to strengthen a repeated upper-tier offset prompt.',True)
put('LG-Q-336','Refer to the value-of-money graph. The economy moves from a to b. In a long-run comparison, a nominal wage rises by the same proportion as the price level inferred from those points, and technology and labor supplies are unchanged. Which comparison fits monetary neutrality?',
 ['The price level and nominal wage rise by one-third; the real wage need not change.','The price level falls by one-quarter; the real wage must rise.','The price level doubles; unchanged real resources require output to double.','The price level rises by one-third; the real wage must also rise by one-third.'],
 'The graph gives value of money 2 at a and 1.5 at b. Their reciprocal price levels are 1/2 and 2/3, a one-third increase. Proportional nominal wage growth leaves the real wage unchanged; nominal changes alone do not raise real productive capacity.',
 'Replace graph-inconsistent price levels with actual reciprocal readings and linked nominal/real inference.',True)
put('LG-Q-9115','Refer to the value-of-money graph. A worker earns $24 at point a and $30 at point b. Treat each point’s price level as the reciprocal of its displayed value of money. What happens to the worker’s real wage, and what nominal wage at b would instead preserve the original purchasing power?',
 ['Real wage falls from 48 to 45 output units; $32 would preserve it.','Real wage rises from 12 to 20 output units; $18 would preserve it.','Real wage rises from 48 to 60 output units; $24 would preserve it.','Real wage falls from 48 to 45 output units; $36 would preserve it.'],
 'P is 1/2 at a and 2/3 at b. Real wages are 24/(1/2) = 48 and 30/(2/3) = 45. To retain 48 units at b requires 48 × 2/3 = $32.',
 'Correct attached graph values and require both forward comparison and reverse wage compensation.',True)
put('LG-Q-9029','Refer to the graph. An analyst describes the move from a to b as a rightward shift of money demand and says that doubling the money quantity proves a doubling of the price level. Which diagnosis uses both curve evidence and the vertical-axis scale?',
 ['MD is unchanged; the price level rises by one-third, so constant output would require velocity to fall.','MD shifts right; the price level doubles, so velocity can remain fixed.','MD is unchanged; the price level falls by one-quarter, so velocity must rise.','MD shifts left; the price level is unchanged because the money supply is vertical.'],
 'The same MD contains both a and b. Money doubles from 2,500 to 5,000, while P rises from 1/2 to 2/3, a factor of 4/3. With Y fixed, MV = PY requires velocity to change by (4/3)/2 = 2/3, so it falls.',
 'Turn a repeated shift correction into diagnosis of two competing claims using actual image geometry.',True)
put('LG-Q-9031','An economy plans for real output to grow 4 percent and the price level to grow 2 percent over one year. A payments change is expected to reduce velocity by 3 percent. Using the exact multiplicative quantity equation, approximately what money-growth rate meets both targets, and why would simply adding 2 and 4 be insufficient?',
 ['9.36 percent; money must also offset the velocity decline.','6 percent; velocity has no effect when output growth is given.','3 percent; declining velocity reduces the money needed.','9 percent exactly; percentage growth rates always add exactly.'],
 'The required money growth factor is (1.02 × 1.04)/0.97 = 1.093608..., so growth is about 9.36 percent. The sum approximation gives 9 percent, but is not the exact multiplicative result.',
 'Strengthen a one-step Legendary growth calculation with reverse inference and an explicit exact-versus-approximate distinction.',True)
put('LG-Q-9035','A lender’s one-year fixed nominal contract pays 12 percent. Expected inflation when written was 5 percent, but actual inflation is 9 percent. Use exact gross returns. What are the expected and realized real returns, and what nominal rate on a new loan would preserve the original expected real return if expected inflation is now 9 percent?',
 ['About 6.67 percent, 2.75 percent, and 16.27 percent.','7 percent, 3 percent, and 16 percent exactly.','About 2.75 percent, 6.67 percent, and 12 percent.','About 6.67 percent, 2.75 percent, and 12 percent.'],
 'Expected real return is 1.12/1.05 − 1 = 6.67 percent; realized is 1.12/1.09 − 1 = 2.75 percent. Preserving the original gross real return on a new loan requires (1.12/1.05) × 1.09 − 1 = 16.27 percent nominal.',
 'Differentiate a Legendary contract reconstruction from ordinary Fisher subtraction already covered at Hard.',True)
put('LG-Q-9047','A one-time monetary expansion lowers the value of money today. Credible guidance says the money-growth rate will then return to its previous path. The long-run real interest rate is unchanged. An analyst concludes that nominal interest rates must remain permanently higher. Which evaluation is strongest?',
 ['A one-time price-level rise does not establish permanently higher expected inflation, so the lasting nominal-rate claim is unsupported.','The higher price level guarantees permanently higher inflation, so the nominal-rate claim follows.','The lower value of money proves the real interest rate falls permanently, so nominal rates must fall.','Monetary neutrality makes expected inflation irrelevant to nominal rates, so the Fisher relationship does not apply.'],
 'The Fisher effect relates nominal rates to expected inflation over the loan horizon. A level adjustment alone does not establish a continuing inflation-rate increase. The real-rate assumption therefore does not complete the analyst’s argument.',
 'Separate a price-level movement from a sustained expected-inflation change; avoid causal inference unsupported by the graph-like scenario.')
put('LG-Q-9128','A country’s nominal loan rate falls from 16 to 9 percent while expected inflation falls from 12 to 4 percent. Using the Fisher approximation, what happens to the expected real rate, and by how much would the new nominal rate have had to fall further to preserve its original expected real rate?',
 ['The expected real rate rises from 4 to 5 percent; a further 1-point nominal cut was needed.','The expected real rate falls from 4 to 3 percent; a further 1-point nominal cut was needed.','The expected real rate stays at 4 percent; no further nominal change was needed.','The expected real rate rises from 4 to 5 percent; a further 5-point nominal cut was needed.'],
 'Subtract expected inflation: 16 − 12 = 4 initially and 9 − 4 = 5 later. Preserving a real rate of 4 with expected inflation of 4 requires a nominal rate of 8, one point below 9.',
 'Make the inflation expectation explicit and add reverse inference to repeated upper-tier subtraction.',True)
put('LG-Q-9129','All long-term debt is fully price-indexed, wage contracts adjust correctly, and inflation is perfectly anticipated. Firms still reprice at different times and households spend time moving funds out of non-interest-bearing cash. Which evaluation separates what indexation resolves from what it leaves?',
 ['Debt indexation limits surprise redistribution; asynchronous prices and cash management can still consume resources or distort signals.','Debt indexation eliminates all inflation costs because every relative price must adjust at the same instant.','The remaining cash-management costs transfer wealth from borrowers to lenders without using real resources.','Perfect anticipation eliminates repricing costs but creates unexpected redistribution on the indexed debt.'],
 'Indexation protects the real value of the specified debt. It does not make repricing instantaneous or eliminate the effort spent economizing on non-interest-bearing cash.',
 'Strengthen a repeated Legendary misconception correction through comparison of protected contracts and remaining resource costs.')
put('LG-Q-249','A household keeps a fixed $720 cash balance while the price level rises from 1.2 to 1.5 during money-financed government spending. How much purchasing power, measured in units of the composite good, does this unchanged balance lose?',
 ['120 units.','180 units.','144 units.','No units, because the nominal balance is fixed.'],
 'The cash initially buys 720/1.2 = 600 units and later buys 720/1.5 = 480 units. The loss is 120 units; an unchanged dollar balance need not preserve purchasing power.',
 'Give an existing Hard inflation-tax item substantive real-balance arithmetic rather than another burden-identification question.',True)
put('LG-Q-9041','Unexpected deflation reduces the price level from 1.25 to 1.00. A firm’s fixed nominal debt is $48,000. Its sales volume is unchanged, and its $12,000 nominal operating cash flow falls in the same proportion as the price level. Which pair describes the debt burden and the cash-flow pressure?',
 ['Real debt rises from 38,400 to 48,000 units; debt/cash flow rises from 4 to 5.','Real debt falls from 48,000 to 38,400 units; debt/cash flow falls from 5 to 4.','Real debt rises from 38,400 to 48,000 units; debt/cash flow stays at 4.','Real debt stays at 48,000 units; debt/cash flow rises from 4 to 5.'],
 'Real debt rises from 48,000/1.25 = 38,400 to 48,000/1 = 48,000. Nominal cash flow becomes 12,000 × 1/1.25 = 9,600. Debt/cash flow therefore rises from 4 to 5, despite unchanged sales volume.',
 'Replace a repetitive directional Legendary prompt with linked real-debt and repayment-capacity analysis.',True)
put('PG4-MPT-L-001','Refer to the two-panel graph. Between A and B, the central bank expands money supply while SRAS stays fixed. A commentator says output and prices rose by the same percentage because they both rose. Which numerical comparison and inference are supported?',
 ['Output rises 25 percent and the price level 12.5 percent; their responses need not be proportional.','Output rises 12.5 percent and the price level 25 percent; their responses must be proportional.','Both rise 25 percent; equal directions establish equal percentage changes.','Both rise 6.25 percent; a common point label establishes a common percentage change.'],
 'Read output 100 to 125 and P 50 to 56.25. Their percentage changes are 25/100 = 25 percent and 6.25/50 = 12.5 percent. The diagram supplies distinct responses along fixed SRAS.',
 'Use both panels’ numerical evidence to evaluate a claim rather than repeat the Hard direction chain.',True)
put('LG-Q-9131','Refer to the graph showing MS1 to MS2. In a fixed-price spending model, the resulting investment loss is $90 billion, while an independent recovery in business expectations adds $30 billion of autonomous investment. MPC is 0.6; there are no taxes, imports or further interest-rate feedbacks. What is the net shift in aggregate demand, and what independent investment recovery would exactly cancel the monetary effect?',
 ['AD shifts left $150 billion; a $90 billion recovery would cancel it.','AD shifts left $225 billion; a $30 billion recovery would cancel it.','AD shifts left $60 billion; a $150 billion recovery would cancel it.','AD shifts right $150 billion; a $90 billion recovery would cancel it.'],
 'The graph supplies contractionary direction. Net autonomous investment is −90 + 30 = −60. With multiplier 1/(1 − 0.6) = 2.5, AD shifts left $150 billion. Exact cancellation requires a $90 billion independent recovery, before multiplication.',
 'Remove ambiguous fiscal-offset units, retain the selected investment channel, and add a reverse cancellation condition.',True)
# Explicit approximations for legacy numerical Fisher statements that otherwise read as exact identities.
for id in ['LG-Q-242','LG-Q-243','LG-Q-341','LG-Q-342','LG-Q-9036','LG-Q-3008','LG-Q-9117','LG-Q-9127','ECON-SP-MEDIUM-115','ECON-SP-HARD-209','LG-R-5033','ECON-SP-FISHER-EFFECT-6015','LG-B-6013','LG-Q-343','LG-Q-344','LG-Q-9037','LG-Q-9038','LG-Q-3011','LG-Q-9119']:
 clarify(id,prefix='Use the Fisher approximation. ',reason='State that percentage-point addition/subtraction is approximate, not the exact gross-return identity.',numeric=True)
clarify('LG-Q-3013',prefix='Use the quantity-equation growth approximation. ',reason='Make the approximate growth-rate calculation explicit.',numeric=True)
wr('revisions.json',S)
print('Authored',len(S),'targeted revisions; numerical',sum(s['numeric'] for s in S.values()))
