import json,hashlib,datetime
from pathlib import Path
W=Path(__file__).resolve().parent
def rd(n):return json.loads((W/n).read_text('utf8'))
def wr(n,x):(W/n).write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n','utf8')
inv=rd('inventory-before.json');summ=rd('summary-before.json')
notes={
'money-functions-and-measures':(['B','F'],'Functions, fiat/commodity money, liquidity and aggregates are represented at ordinary levels. Historical M1 exclusion of savings is unstated in several legacy records. Repeated upper-tier classification warrants focused linked classification, not added objectives.','P52B-S3-MFM-H-001'),
'central-bank-and-federal-reserve':(['G'],'Institutional authority, instrument versus goal, liquidity versus solvency and balance-sheet mechanics have strong existing Hard coverage. Some upper-tier recognition remains, but the module as a whole has no material coverage or calibration deficit.','P52B-S1-FED-H-001'),
'bank-balance-sheets-reserves-and-capital':(['D'],'Required/excess reserves, balance sheets and leverage are well represented. Loan origination must be separated from later interbank settlement in legacy balance-sheet questions. Hard arithmetic is already plentiful.','PM2C1-BANK-H-001'),
'deposit-creation-and-money-multiplier':(['D','F'],'No absent objective. Legacy initial cash deposit questions need explicit simple-model assumptions and gross-deposit versus net-money distinctions; repeated one-bank arithmetic in upper tiers can support reverse inference or propagation instead.','LG-Q-224'),
'monetary-policy-tools':(['D','F'],'OMO, reserve requirements, discount lending and interest on reserves are selected. An at-most target has multiple feasible answers; an upper-tier reserve-retention calculation lacks a coherent model. Existing Hard operational mechanisms are sufficient.','LG-Q-209'),
'monetary-control-limits':(['D','F'],'Currency drain, excess reserves, weak borrowing and bank risk are all present. LO31.4 in this module is actual selected bank-capital content despite its historical code. Missing claim in LG-Q-9114 and repeated qualitative upper-tier leakage prompts warrant targeted fixes.','PM2C1-MCL-FB-004'),
'liquidity-preference-and-money-market':(['B','E','F'],'Extensive graph and Hard reasoning exists; this is not missing graph coverage. ECON-SP-MEDIUM-142 reverses the money-supply movement. Some Legendary items merely name a point or repeat Hard chains. Correct visual contracts and strengthen selected upper-tier reverse inference.','PG4-MM-H-004'),
'monetary-policy-transmission':(['B','F'],'The live preset explicitly includes the interest-rate/investment/AD chain, liquidity-trap limits and existing numerical spending-multiplier examples. Retain that boundary; no new fiscal-policy objectives. Repeated upper-tier graph-plus-multiplier grammar merits selective reverse/constraint analysis.','PG4-MPT-H-001'),
'quantity-theory-of-money':(['D','E','F'],'MV=PY, velocity, approximate growth accounting and inverse value-of-money reasoning are present at Hard. Several attached graph prompts give incompatible fractions or impose fixed velocity on a graph that does not imply it. Preserve the accurate asset and correct question evidence.','LG-Q-9030'),
'monetary-neutrality':(['D','E','F'],'Hard applies real wages, relative prices and short-run versus long-run distinctions. Upper-tier repetition and graph-supplied values inconsistent with the actual image warrant targeted correction and linked nominal/real comparison.','PM2C2-NEUT-H-001'),
'fisher-effect':(['B','F'],'Strong Hard coverage already separates ex ante from ex post returns and changing real-rate components. Some legacy arithmetic silently uses the Fisher approximation; upper-tier graph prompts must not infer expected future inflation solely from a one-time price-level change.','PM2C2-FISH-H-005'),
'inflation-costs':(['B','E','F'],'Hard covers anticipated costs, redistribution and relative-price signals. Upper graph items often identify a named cost without using evidence, and some price levels contradict the attached graph. Target links between real repayment, surprise and resource costs.','PM2C2-ICOST-H-001'),
'inflation-tax-and-deflation':(['B','D','E','F'],'All selected concepts exist. Several Hard and Legendary prompts repeat recognition. Strengthen an existing Hard real-balance calculation and upper-tier debt-burden/seigniorage feedback analysis; correct graph numbers.','PM2C2-ITAX-FB-004')}
find=[]
for c,m in inv['views'].items():
 qs={q['id']:q for a in m['questions'].values() for q in a}
 for p in ['repairQuestions','repairSeedQuestions','bridgeQuestions']:
  for q in m.get(p,[]):qs[q['id']]=q
 for obj in summ['byConcept'][c]['objectives']:
  rows=[q for q in qs.values() if q['objective']==obj]; cats,note,e=notes[c]
  if c=='monetary-control-limits' and obj=='LO31.4':cats=['G'];note='Selected leverage/capital subset has direct recognition, arithmetic at Medium/Hard, and repair/bridge support. No material gap; preserve all seven records.'
  find.append({'selectedConcept':c,'objective':obj,'objectiveLabel':m.get('objectiveLabels',{}).get(obj,obj),'count':len(rows),'canonicalDifficultyCounts':{d:sum(q.get('canonicalDifficulty','unknown')==d for q in rows) for d in ['easy','medium','hard','elite','legendary','unknown']},'classifications':cats,'finding':note,'coverageGap':False,'normalExamReasoningPrimarilyTrappedInUpperTiers':False,'evidenceIds':[q['id'] for q in rows if q.get('canonicalDifficulty')=='hard'][:5],'upperTierEvidenceIds':[q['id'] for q in rows if q.get('canonicalDifficulty')=='legendary'][:5]})
wr('objective-findings-before.json',{'recordedAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'beforeAnyContentAuthoring':True,'baselineLibrarySha256':rd('library-baseline.json')['librarySha256'],'findings':find,'overall':'No A coverage gaps and no systemic C calibration gap. Target economic precision, evidence mismatch and selected B/D/E/F deficits. G findings include institutional coverage and capital subset. No target change count.'})
wr('scope-boundary.json',{'preset':summ['preset'],'selections':[{'conceptId':c,'kind':'direct','parent':None} for c in inv['views']],'included':['Money functions, fiat/commodity, liquidity, M1/M2','Bank balance sheets, reserves, capital, deposit creation and multiplier limits','Central-bank roles, OMO, discount lending, reserve requirements and interest on reserves','Nominal-interest money market and value-of-money diagrams','Selected monetary-policy transmission, investment and AD; retain existing spending-multiplier integrations','MV=PY, velocity, neutrality, Fisher effect, inflation costs, inflation tax and deflation'],'boundaries':['No new saving/national-accounting/loanable-funds or fiscal-policy coverage','No new full AD-AS shock/output-gap curriculum beyond the existing selected transmission records','No Phillips curves, sacrifice ratios or disinflation-policy models','No exchange-rate, FX, NCO or international-capital-flow coverage'],'objectiveCodesAreRuntimeMetadata':True,'note':'LO31.4 in monetary-control-limits is selected capital/leverage content. Objective codes and historical source chapters are preserved, not used to redefine selection.'})
wr('audit-projection-provenance.json',{'officialAuditorUsesAuthoritativeLibrary':True,'all13SelectionsDirect':True,'projectionRequired':False})
print(len(find),'objective/concept findings recorded before content authoring')
