const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('C:/Users/Jennings/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.cwd(),out=path.join(root,'validation_artifacts/updates_page');
const server=http.createServer((req,res)=>{try{let p=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(p!==root&&!p.startsWith(root+path.sep))throw Error();if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.png':'image/png','.svg':'image/svg+xml'})[path.extname(p)]||'application/octet-stream');fs.createReadStream(p).pipe(res);}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'msedge',headless:true}),results=[],errors=[];
try{for(const width of [1440,390,320]){const ctx=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});await ctx.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
for(const [name,url] of [['updates','/about/updates/'],['about','/about/'],['faculty','/how-to/'],['games','/games/']]){assert.equal((await page.goto(origin+url)).status(),200);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name} overflow at ${width}`);
if(name==='updates'){assert.deepEqual(await page.locator('main h1, main h2, main h3').evaluateAll(els=>els.map(e=>e.tagName)),['H1','H2','H3','H3','H3']);assert.equal(await page.locator('.update-entry').count(),3);
await page.keyboard.press('Tab');assert(await page.locator('.skip-link').evaluate(e=>e===document.activeElement));await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'main-content');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('href')),'/about/');assert.equal(await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle),'solid');
if(width<760){await page.locator('.menu-toggle').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');assert(await page.locator('.menu-toggle').evaluate(e=>e===document.activeElement));}
await page.locator('body').click({position:{x:2,y:300}});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,`updates-${width}.png`),fullPage:true});
const links=await page.locator('a').evaluateAll(els=>els.map(e=>e.getAttribute('href')).filter(h=>h.startsWith('/')));for(const link of new Set(links))assert.equal((await ctx.request.get(origin+link)).status(),200,link);
}
if(name==='about'){await page.getByRole('link',{name:'Read Mastery Quests Updates'}).click();assert.equal(new URL(page.url()).pathname,'/about/updates/');}
if(name==='faculty'){assert(await page.evaluate(()=>document.querySelector('.updates-crosslink').compareDocumentPosition(document.querySelector('a[href="/build/"]')) & Node.DOCUMENT_POSITION_PRECEDING));await page.locator('.updates-crosslink').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`faculty-${width}.png`)});await page.getByRole('link',{name:'View Updates',exact:true}).click();assert.equal(new URL(page.url()).pathname,'/about/updates/');}
if(name==='games'){assert(await page.locator('a[href="/games/econnections/"]').count()>0);assert.equal((await ctx.request.get(origin+'/games/econnections/')).status(),200);}
results.push({page:name,width,status:'PASS'});
}await ctx.close();}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify({results,errors},null,2));console.log('PASS: 12 page/viewport checks; navigation, headings, keyboard, focus and Games route.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});

