// All amounts are fictional billions for an aggregate domestic economy.
const entry = (id, phase, prompt, amount, postings, feedback, concept) => ({ id, phase,
  difficulty: { basic: 1, traps: 2, multi: 3 }[phase], prompt, amount, postings, feedback, concept, tags: [concept, phase] });
const post = (account, amount) => ({ account, amount });
export const SCENARIOS = [
  entry('basic-cars', 'basic', 'Households purchase $12 billion of newly produced domestic automobiles.', 12, [post('C', 12)], 'Households bought newly produced domestic final goods. Their spending enters consumption.', 'consumption'),
  entry('basic-meals', 'basic', 'Households spend $6 billion on meals prepared by domestic restaurants this period.', 6, [post('C', 6)], 'Restaurant meals are current services purchased by households, so they enter consumption.', 'consumption'),
  entry('basic-machinery', 'basic', 'Domestic businesses buy $9 billion of newly produced domestic machinery for their factories.', 9, [post('I', 9)], 'New productive equipment is business fixed investment, not household consumption.', 'capital-investment'),
  entry('basic-inventory', 'basic', 'A domestic manufacturer produces $7 billion of finished vehicles that remain unsold in its inventory this period.', 7, [post('I', 7)], 'The vehicles were produced this period. Unsold additions to inventory enter investment even before a customer buys them.', 'inventory'),
  entry('basic-housing', 'basic', 'Builders complete $11 billion of new domestic residential housing this period.', 11, [post('I', 11)], 'New residential construction is investment because it adds to the housing capital stock.', 'residential-investment'),
  entry('basic-government', 'basic', 'The national government purchases $8 billion of newly produced domestic computers for public offices.', 8, [post('G', 8)], 'The government bought newly produced final goods for public use, so the purchase enters G.', 'government-purchases'),
  entry('basic-export', 'basic', 'Foreign buyers purchase $10 billion of newly produced aircraft made in the domestic economy.', 10, [post('X', 10)], 'The aircraft were produced domestically and sold abroad. Exports add to domestic GDP.', 'exports'),
  entry('trap-transfer', 'traps', 'The government distributes $9 billion in Social Security retirement benefits. Record the transfer itself.', 9, [], 'A transfer redistributes income; it is not a government purchase of current goods or services. Any later spending is a separate transaction.', 'transfers'),
  entry('trap-benefits', 'traps', 'The government pays $4 billion in unemployment benefits. Record the benefit payment itself.', 4, [], 'Unemployment benefits are transfers, not purchases of current production. The payment itself is not counted.', 'transfers'),
  entry('trap-stock', 'traps', 'Investors buy $14 billion of existing corporate shares from other investors. No broker fees are involved.', 14, [], 'Existing shares change ownership. This financial transaction does not itself produce a current good or service.', 'financial-assets'),
  entry('trap-used', 'traps', 'Households buy $10 billion of used cars directly from other households, with no current dealer services.', 10, [], 'The cars were counted when first produced. Reselling existing goods does not create current production.', 'used-goods'),
  entry('trap-steel', 'traps', 'An automaker buys $5 billion of domestic steel and uses all of it in new cars completed this period. The final cars are accounted for separately.', 5, [], 'Steel used in those cars is an intermediate input. Its value is included in the final cars; a separate post would double count it.', 'intermediate-goods'),
  entry('trap-house', 'traps', 'Households purchase $13 billion of newly built domestic homes completed this period. There are no separate transaction fees.', 13, [post('I', 13)], 'New homes are residential investment even when households buy them. They are not consumption spending.', 'residential-investment'),
  entry('trap-inventory', 'traps', 'A domestic appliance maker produces $6 billion of finished appliances that are added to inventory, with none sold yet.', 6, [post('I', 6)], 'Current production counts even when unsold. The inventory increase enters investment.', 'inventory'),
  entry('trap-used-service', 'traps', 'Households buy used cars worth $10 billion and pay domestic dealers $1 billion for current commissions and services.', 11, [post('C', 1)], 'Only the $1 billion of newly supplied dealer services enters consumption. The $10 billion used-car value is not current production.', 'used-good-services'),
  entry('import-phones', 'multi', 'Households purchase $5 billion of newly produced imported smartphones. Ignore any separate domestic distribution services.', 5, [post('C', 5), post('M', 5)], 'The final household purchase enters consumption. Imports rise by the same amount because the phones were produced abroad. These entries offset in domestic GDP.', 'consumer-imports'),
  entry('import-capital', 'multi', 'A domestic business buys $4 billion of newly produced equipment from a foreign manufacturer, with no separate domestic service charge.', 4, [post('I', 4), post('M', 4)], 'The equipment purchase enters investment. Because it was produced abroad, imports rise by the same amount, offsetting the investment entry in domestic GDP.', 'capital-imports'),
  entry('import-government', 'multi', 'A government agency purchases $3 billion of newly produced imported equipment, with no separate domestic service charge.', 3, [post('G', 3), post('M', 3)], 'The equipment enters government purchases and imports. The offset removes foreign production from domestic GDP without treating the purchase as a loss of domestic production.', 'government-imports'),
];
export const BY_ID = Object.fromEntries(SCENARIOS.map(s => [s.id, s]));

const auditRow = (id, prompt, correctPostings, posted) => ({ id, prompt, correctPostings, posted });
const cleanRows = () => [
  auditRow('meals', 'Households buy $2B of current domestic restaurant services.', [post('C', 2)], [post('C', 2)]),
  auditRow('exports', 'Foreign buyers purchase $3B of newly produced domestic goods.', [post('X', 3)], [post('X', 3)]),
];
export const AUDITS = [
  { id: 'audit-transfer', badID: 'bad', explanation: 'The benefit is a transfer, not a government purchase of current production. Remove the erroneous G entry.', rows: [...cleanRows(), auditRow('bad', 'Government distributes $6B of Social Security benefits; record the transfer itself.', [], [post('G', 6)])] },
  { id: 'audit-import', badID: 'bad', explanation: 'The imported household purchase needs both C and M. Add the missing consumption entry; foreign production then has zero net effect.', rows: [...cleanRows(), auditRow('bad', 'Households buy $5B of imported final goods, with no separate domestic services.', [post('C', 5), post('M', 5)], [post('M', 5)])] },
  { id: 'audit-inventory', badID: 'bad', explanation: 'Unsold goods produced this period enter inventory investment. Add I; a sale is not required for production to count.', rows: [...cleanRows(), auditRow('bad', 'A manufacturer adds $7B of this period’s finished domestic goods to inventory.', [post('I', 7)], [])] },
  { id: 'audit-housing', badID: 'bad', explanation: 'New residential construction belongs in I, not C. GDP stays the same in this repair, but the component accounts must still be correct.', rows: [...cleanRows(), auditRow('bad', 'Households buy $9B of newly built domestic homes completed this period.', [post('I', 9)], [post('C', 9)])] },
  { id: 'audit-used', badID: 'bad', explanation: 'A household-to-household sale of used goods is not current production. Remove the full erroneous consumption entry.', rows: [...cleanRows(), auditRow('bad', 'Households buy $10B of used cars directly from other households, with no current services.', [], [post('C', 10)])] },
];
