import { CONFIG, ACCOUNTS, COMPONENTS, PHASES } from './config.js';
import { currentScenario, currentAudit, gdp, nx, deltaOf } from './engine.js';
export const number = n => n.toLocaleString('en-US');
export const signed = n => `${n > 0 ? '+' : n < 0 ? '−' : ''}${number(Math.abs(n))}`;
export const money = n => `${n < 0 ? '−' : n > 0 ? '+' : ''}$${number(Math.abs(n))}B`;
export const postingsText = postings => postings.length ? postings.map(p => `${p.account} ${money(p.amount)}`).join(' · ') : 'Not Counted · $0B';
const action = (id, label) => `<button type="button" class="primary" data-action="${id}">${label}</button>`;
function accounts(state, label = 'POST TRANSACTION') {
  return `<fieldset class="posting-controls"><legend>WHERE DOES IT POST?</legend><p class="muted selection-help">Select all accounts that apply. Not Counted stands alone.</p><div class="account-buttons">${Object.entries(ACCOUNTS).map(([id, name]) => `<button type="button" data-account="${id}" aria-pressed="${state.selection.includes(id)}"><strong>${id === 'NC' ? '—' : id}</strong><span>${name}</span></button>`).join('')}</div><button class="primary post-button" data-action="${state.stage === 'audit_repair' ? 'repair' : 'post'}" ${state.selection.length ? '' : 'disabled'}>${label}</button></fieldset>`;
}
function receipt(state) {
  return `<div class="receipt"><ul>${state.lastPostings.length ? state.lastPostings.map(p => `<li><span>${ACCOUNTS[p.account]}</span><strong>${money(p.amount)}</strong></li>`).join('') : '<li>Not Counted <strong>$0B</strong></li>'}</ul><p class="net-change">NET GDP CHANGE <strong>${money(state.lastDelta)}</strong></p></div>`;
}
export function componentBoard(state, changes = {}) {
  return `<dl class="components">${[...COMPONENTS, 'NX'].map(k => `<div class="component ${changes[k] ? 'account-changed' : ''}" data-component="${k}"><dt><b>${k}</b> ${k === 'NX' ? 'Net Exports' : ACCOUNTS[k]}</dt><dd>${number(k === 'NX' ? nx(state.accounts) : state.accounts[k])}</dd><span class="component-delta">${changes[k] ? money(changes[k]) : '&nbsp;'}</span></div>`).join('')}</dl>`;
}
export function ledgerView(state, open) {
  return `<details id="ledger" ${open ? 'open' : ''}><summary>National ledger <span>${state.ledger.length} entries</span></summary>${state.ledger.length ? `<table><caption>Posted activity · all amounts in billions</caption><thead><tr><th scope="col">Transaction</th><th scope="col">Postings</th><th scope="col">GDP change</th></tr></thead><tbody>${state.ledger.map((row, i) => `<tr><th scope="row"><span class="ledger-number">${i + 1}${row.source ? ` · ${row.source}` : ''}</span>${row.prompt}</th><td>${postingsText(row.postings)}</td><td>${money(row.gdpDelta)}</td></tr>`).join('')}</tbody></table>` : '<p class="muted">Your accepted postings will appear here.</p>'}</details>`;
}
function auditTable(state) {
  return `<table class="audit-table"><caption>New draft batch · one bad posting${state.auditCorrected ? ' repaired' : ''}</caption><thead><tr><th scope="col">Entry</th><th scope="col">Currently posted</th><th scope="col">${state.stage === 'audit_find' ? 'Inspect' : 'Status'}</th></tr></thead><tbody>${state.auditRows.map((row, i) => `<tr><th scope="row"><span class="ledger-number">Entry ${i + 1}</span>${row.prompt}</th><td>${postingsText(row.posted)}</td><td>${state.stage === 'audit_find' ? `<button data-audit="${row.id}">Inspect <span class="sr-only">entry </span>${i + 1}</button>` : row.id === currentAudit(state).badID ? (state.auditCorrected ? 'Repaired' : 'Repair this entry') : 'Verified'}</td></tr>`).join('')}</tbody></table>`;
}
export function renderWork(state) {
  if (state.stage === 'intro') return `<p class="eyebrow">National accounts desk</p><h2 id="stage-title" tabindex="-1">Keep the economy on the record.</h2><p>Route each transaction to its account. Watch the components move, check the ledger, and repair a bad posting.</p><p class="muted">No timer. You can correct every entry.</p>${action('start', 'OPEN THE ACCOUNTS')}`;
  if (['posting', 'posted'].includes(state.stage)) {
    const s = currentScenario(state);
    return `<div class="phase-line"><span>${PHASES[s.phase]}</span><span>${state.index + 1} / ${state.deck.length}</span></div><p class="eyebrow">News flash</p><h2 id="stage-title" tabindex="-1" class="news">${s.prompt}</h2>${state.stage === 'posting' ? `${accounts(state)}${state.feedback ? `<div class="feedback">${state.feedback}</div>` : ''}` : `${receipt(state)}<div class="feedback">${state.feedback}</div>${action('next', state.index + 1 === state.deck.length ? 'RECONCILE THE RECORD' : 'NEXT TRANSACTION')}`}`;
  }
  if (state.stage === 'identity') return `<p class="eyebrow">From postings to a principle</p><h2 id="stage-title" tabindex="-1">YOU’VE BEEN BUILDING GDP</h2><p class="identity">GDP = C + I + G + X − M</p><p>Consumption, investment, government purchases, and exports record spending on final production. Imports remove the foreign production included in that spending.</p><div class="insight"><h3>Two entries. Zero net change.</h3><p>A $5B imported household purchase enters C +5 and M +5. It changes both accounts, but contributes $0B to domestic GDP.</p></div>${action('audit', 'AUDIT THE COUNTER')}`;
  if (['audit_find', 'audit_repair', 'audit_done'].includes(state.stage)) {
    const bad = state.auditRows.find(r => r.id === currentAudit(state).badID);
    return `<p class="eyebrow">${state.auditCorrected ? 'Audit reconciled' : 'Find the bad post'}</p><h2 id="stage-title" tabindex="-1">${state.auditCorrected ? 'THE RECORD IS REPAIRED.' : 'THE COUNTER IS OFF.'}</h2><p>${state.auditCorrected ? 'The corrected batch is now in the national ledger.' : 'A new draft batch has already entered the accounts. Exactly one entry is wrong. Some errors change the components even when headline GDP stays the same.'}</p>${auditTable(state)}${state.stage === 'audit_find' ? '<p>Which entry is corrupting the national accounts?</p>' : state.stage === 'audit_repair' ? `<p class="repair-prompt">${bad.prompt}</p>${accounts(state, 'REPAIR POSTING')}` : receipt(state)}${state.feedback ? `<div class="feedback">${state.feedback}</div>` : ''}${state.auditCorrected ? action('shock', 'THE ECONOMY MOVES AT ONCE') : ''}`;
  }
  if (state.stage === 'shock') return `<p class="eyebrow">All accounts. One counter.</p><h2 id="stage-title" tabindex="-1">THE ECONOMY MOVES AT ONCE.</h2><p>These simultaneous changes are waiting to post.</p><dl class="shock-changes">${COMPONENTS.map(k => `<div><dt>${ACCOUNTS[k]}</dt><dd>${money(CONFIG.shock[k])}</dd></div>`).join('')}</dl><form id="shock-form"><label for="shock-value">What is the net change in GDP?</label><div class="numeric-entry"><input id="shock-value" name="shock-value" type="text" inputmode="text" autocomplete="off" required aria-describedby="shock-help"><button class="primary" type="submit">UPDATE THE COUNTER</button></div><p id="shock-help" class="muted">Amount in billions. A plus sign, dollar sign, or B suffix is optional.</p></form>${state.feedback ? `<div class="feedback">${state.feedback}</div>` : ''}`;
  const accuracy = Math.round(100 * state.firstCorrect / state.deck.length);
  return `<p class="eyebrow">National accounts reconciled</p><h2 id="stage-title" tabindex="-1">THE ACCOUNTS BALANCE.</h2><p class="completion-delta">Final change: ${money(deltaOf(COMPONENTS.map(account => ({ account, amount: CONFIG.shock[account] }))))}</p><p>Final simulated GDP: <strong>$${number(gdp(state.accounts))} billion</strong>. Every component above matches the national ledger.</p><dl class="results"><div><dt>Transactions posted</dt><dd>${state.deck.length}</dd></div><div><dt>First-attempt accuracy</dt><dd>${accuracy}% <small>(${state.firstCorrect}/${state.deck.length})</small></dd></div><div><dt>Additional posting attempts</dt><dd>${state.postAttempts - state.deck.length}</dd></div><div><dt>Audit</dt><dd>Repaired <small>${state.auditFindAttempts} inspection(s), ${state.auditRepairAttempts} repair attempt(s)</small></dd></div><div><dt>Final changes</dt><dd>Reconciled <small>${state.shockAttempts === 1 ? 'First attempt' : `After ${state.shockAttempts} attempts`}</small></dd></div></dl><div class="actions">${action('replay', 'PLAY AGAIN')}<a class="button" href="../">RETURN TO GAMES</a></div>`;
}
