"""Faculty-facing dispositions for the reviewed source changes."""
SUMMARIES={
'GEN-ECON-02':'Clarified that other trip costs are already deducted before comparing the $4 fee with remaining benefits.',
'GEN-ECON-05':'Removed duplicated core wording and replaced the self-check with classification of a national retailer\'s own pricing decision.',
'GEN-ECON-08':'Removed repeated PPF wording while preserving the opportunity-cost graph and calculation.',
'GEN-ECON-09':'Added a production/opportunity-cost table and a mutually beneficial four-rugs-per-lamp trade.',
'GEN-ECON-10':'Made the self-check ask which travel-alternative assumption matters when transferring a city estimate to a rural area.',
'GEN-ECON-16':'Replaced simultaneous shifts with one demand/supply intersection at price 5 and quantity 150 thousand.',
'GEN-ECON-17':'Removed repeated core wording and made the self-check calculate a surplus and price pressure.',
'GEN-ECON-22':'Replaced equal tax incidence with a $6 wedge: buyers bear $4 and sellers $2. Distinguished elasticity interpretation from MICRO-02 revenue.',
'GEN-ECON-25':'Made the self-check retrieve the $3 quota rent and why license ownership matters.',
'MICRO-01':'Replaced the ambiguous nonmonetary example with a shortage and the coordinating response of money prices.',
'MICRO-02':'Removed the unexplained $46/$34, 420-unit case. Retained the correct $6 times 80 = $480 calculation.',
'MICRO-03':'Removed repeated core prose about public goods and external costs.',
'MICRO-07':'Changed the worked heading to complements and set a clear self-check: -0.7 times a -5% printer-price change implies ink demand rises 3.5%.',
'MICRO-08':'Replaced an option-like self-check with an explicit midpoint-elasticity and total-revenue calculation.',
'MICRO-09':'Rewrote the warning around economic versus legal tax burden. Preserved the owner decision against another tax-incidence graph.',
'MICRO-11':'Replaced unclear shorthand in the producer-surplus warning with a per-unit versus total-revenue distinction.',
'MICRO-12':'Removed the disconnected warning dataset and clarified surplus distribution versus lost gains from trade.',
'MICRO-13':'Replaced disconnected warning numbers and made the self-check identify the efficient number of trades from stated values and costs.',
'MICRO-14':'Aligned the heading and explanation with consumer surplus rising from $32 to $72. Added distinct area patterns; explicitly withheld unsupported transfer/DWL claims.',
'MICRO-15':'Added the genuine Policy A/B surplus table and removed the unrelated $150/$140 dataset.',
'MICRO-16':'Corrected imports to exports: 250 minus 100 = 150 thousand. Removed the unsupported tariff/$144 deadweight-loss warning.',
'MICRO-20':'Added successive-worker total/marginal-product rows and simplified diminishing-product language. The sixth-worker self-check retrieves the next marginal addition.',
'MICRO-21':'Added a completed cost-schedule table at Q=120 with all totals and averages; marked cents rounding.',
'MICRO-22':'Kept worked AFC=$8, replaced blended cost cases with a conceptual warning, and used clean self-check values yielding fixed cost $300.',
'MICRO-23':'Replaced the repeated average-cost treatment with a wage/marginal-product table: $120/12=$10 and $120/10=$12.',
'MICRO-24':'Replaced the graph with two ATC curves for different fixed costs and unchanged AVC/MC. Distinguished fixed-output cost changes from spreading fixed cost over output.',
'MICRO-27':'Added an actual flat LRAC minimum from output 60 through 90, making MES=60 visible and distinct from MICRO-26.',
'MICRO-28':'Added quantity, price, total revenue, and marginal revenue rows for a price taker.',
'MICRO-32':'Corrected point B to approximately 36 and renamed the example as reading short-run supply along MC.',
'MICRO-33':'Explained entry/exit adjustment before the displayed endpoint P=MC=min ATC instead of merely reading the final intersection.',
'MICRO-36':'Removed the repeated natural-monopoly graph and replaced its worked example with an exclusive legal license as an entry barrier.',
'MICRO-38':'Removed the unnecessary assumption that MC must always rise; retained the displayed interior MR/MC choice.',
'MICRO-40':'Changed the heading from measuring to identifying monopoly deadweight loss, consistent with the qualitative graph reading.',
'MICRO-42':'Used a student/adult theater example and an explicit resale-prevention self-check.',
'MICRO-44':'Distinguished short-run loss/shutdown reasoning with a clearly labeled $108 fixed-cost increase from the displayed zero-profit baseline.',
'MICRO-45':'Focused the repeated baseline graph on entry, demand/ATC tangency, zero economic profit, and excess capacity.',
'MICRO-46':'Removed unexplained signaling formalism and kept informative versus persuasive advertising intuition.',
'MICRO-47':'Removed the redundant zero-profit graph and used a bakery-variety versus production-cost tradeoff.',
'MICRO-48':'Corrected HHI: named shares contribute 2,693; the unspecified 9% fringe adds at most 81. 2,774 is an upper bound.',
'MICRO-50':'Added a semantic cartel payoff table and demonstrated each firm\'s unilateral undercutting incentive.',
'MICRO-51':'Removed unexplained present-value figures, retained 7>3 and 6>0 backward induction, and aligned the self-check with the tree.',
'MICRO-52':'Replaced the inconsistent kinked-demand/MR graph. Demand kinks at (20,50); MR has a 20-to-40 gap containing MC=36. Kept the explanation introductory.',
'MICRO-57':'Explained MPL versus VMP using $5 times 4=$20, then linked the wage to the existing 4,000-worker graph.',
'MICRO-58':'Replaced unexplained MRS language with the best affordable bundle and preference-ranking intuition while retaining useful tangency.',
'MICRO-66':'Added a three-voter ranking table and showed the 2-to-1 majority cycle.',
'MICRO-67':'Added plain-language meanings for Arrow\'s conditions, especially independence, and reduced the lesson to incompatible guarantees.',
'MICRO-68':'Added an ordered policy-axis graph showing the median and the two majority coalitions.',
'MACRO-02':'Completed the GDP-component example with $2m investment plus $80m government purchases = $82m; the transfer is excluded when sent.',
'MACRO-03':'Added base/current quantity, price, nominal-GDP, and real-GDP comparison rows.',
'MACRO-04':'Made the self-check identify omitted disaster losses instead of relying on absent answer options.',
'MACRO-05':'Added fixed-basket item quantities, prices, and costs ($80 to $98), and separated that CPI=122.5 example from the 125-to-150 index change.',
'MACRO-06':'Removed repeated CPI-bias prose and retained substitution, quality, and new-goods intuition.',
'MACRO-07':'Added a CPI/GDP-deflator coverage table for imported consumer goods, domestic investment goods, and exports.',
'MACRO-08':'Removed the core\'s repeated worked answer; retained the $40,000 to $64,000 index conversion.',
'MACRO-10':'Replaced a repeated self-check with a comparison of 2% and 4% growth doubling times.',
'MACRO-11':'Removed the production-function graph. Direct productivity rises from 2,400/300=8 to 2,700/300=9 units per hour, a 12.5% gain.',
'MACRO-13':'Removed the production-function graph. Compared a temporary rebate with worker training and reliable electricity for long-run productivity.',
'MACRO-14':'Added labor-force classification counts and the 60+5=65 labor-force subtotal.',
'MACRO-15':'Made the self-check distinguish lasting skill mismatch from ordinary job search.',
'MACRO-16':'Added the owner-approved labor-market graph with equilibrium, a binding wage floor, QD=90, QS=120, and surplus=30 workers.',
'MACRO-18':'Added the money-component classification table using the stated post-May-2020 definition; clarified the checking-to-retail-money-fund transfer.',
'MACRO-19':'Removed repeated core language while retaining central-bank versus Treasury roles.',
'MACRO-20':'Added the full before/after bank balance sheet. Assets fall 1,000 to 975 and capital 60 to 35; liabilities remain 940.',
'MACRO-21':'Added a monetary-policy tools/effects table and replaced the duplicated multiplier worked example with policy transmission.',
'MACRO-22':'Reduced repeated statements and explicitly connected thin bank capital, risk, and lending constraints.',
'MACRO-23':'Retained the quantity-theory graph and made the self-check apply 10% money growth with velocity and real output fixed.',
'MACRO-24':'Replaced the repeated money graph with a nominal/real before-and-after table, showing unchanged real wages and output.',
'MACRO-26':'Removed repeated core wording and labeled the expected/realized real-return subtraction as approximate.',
'MACRO-30':'Replaced three AD curves with a clear AD1-to-AD2 fiscal shift at a fixed price level. Reserved gross/net offsets for MACRO-31.',
'MACRO-37':'Explained movement up/left or down/right from the displayed SRPC point rather than only reading that point.',
'MACRO-38':'Added the final C endpoint at 5% unemployment and 5% inflation on both LRPC and the new SRPC; prose follows A to B to C.',
'MACRO-39':'Made the self-check distinguish an expected-inflation curve shift from movement along a curve at unemployment U2.',
'MACRO-41':'Added annual potential/actual-output rows and cumulative loss before calculating sacrifice ratio 6/3=2.',
'MACRO-42':'Added private/public/national-saving and investment/NCO rows, preserving the open-economy identity.',
'MACRO-47':'Rewrote the debt warning to prevent double-counting interest already included in total outlays.',
'MACRO-48':'Added before/after debt, GDP, and debt/GDP rows showing the level rising while the ratio falls.',
'MACRO-49':'Added successive deposit/reserve/loan rounds and the theoretical totals under the restrictive 10% reserve model.',
'MACRO-52':'Added separate goods and asset transaction rows yielding NX=NCO=-60.',
'MACRO-55':'Distinguished capital-flow interpretation from MACRO-52 accounting using a higher-real-rate illustration lowering NCO from 50 to 30.',
'MACRO-57':'Simplified the core to one fiscal-to-interest-to-NCO-to-FX chain and retained the explicit fixed-price, vertical-dollar-supply assumptions.'}

CLUSTERS={
'GEN-ECON-16 / GEN-ECON-18':'16 now finds a single equilibrium; 18 retains simultaneous shifts.',
'GEN-ECON-21 / GEN-ECON-22 / MICRO-02 / MICRO-09':'21 retains its tax graphic; 22 now shows unequal incidence; 02 computes revenue; 09 remains graph-free application.',
'MICRO-22 / MICRO-23':'22 reads average costs; 23 uses worker increments to calculate marginal cost.',
'MICRO-26 / MICRO-27':'26 retains the general scale-cost curve; 27 shows a flat range and the first minimum-cost output.',
'MICRO-36 / MICRO-41':'36 identifies legal barriers without a regulatory-cost graph; 41 retains natural-monopoly regulation.',
'MICRO-44 / MICRO-45 / MICRO-47':'44 considers a short-run fixed-cost loss; 45 uses tangency for entry/exit equilibrium; 47 evaluates variety without the repeated graph.',
'MICRO-48 / MICRO-49 / MICRO-50 / MICRO-51 / MICRO-52':'Concentration bound, unique best responses, cartel defection, sequential credibility, and introductory rigidity each perform a different task.',
'MACRO-11 / MACRO-12 / MACRO-13':'Direct productivity measurement, retained capital-deepening graph, and long-run policy evaluation now have distinct examples.',
'MACRO-18 / MACRO-20 / MACRO-21 / MACRO-49':'Tables classify money components, balance a bank, compare tools, and trace deposit rounds respectively.',
'MACRO-23 / MACRO-24':'23 retains the quantity-theory graph; 24 compares nominal and real values in a table.',
'MACRO-30 / MACRO-31':'30 isolates the fiscal AD shift. 31 intentionally retains the three-curve gross/net-offset diagram.',
'MACRO-37 / MACRO-38 / MACRO-39 / MACRO-40 / MACRO-41':'Movement, natural-rate return, expectations shift, disinflation path, and sacrifice calculation remain distinct. 40 intentionally retains its shared diagram for a different path.',
'MACRO-52 / MACRO-55 / MACRO-56 / MACRO-57':'Transaction accounting, interest-sensitive asset flows, gross-flow FX, and the explicitly different NCO-supply policy model remain separated.'}
