import { COSTS } from './config.js';
import { autoIngredients, minimumPlan, perService, equipmentLabel, marginalSchedule } from './engine.js';
import { acceptedTrials, ROUND_TITLES, TARGETS } from './gameplay.js';
export const money = (value, digits = 0) => value === null || value === undefined ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value);
export const crewText = n => `${n} worker${n === 1 ? '' : 's'}`;
export function challenge(state) {
  if (state.round === 1) return { title: ROUND_TITLES[0], text: 'You’ve opened Takeout Taco. The truck is ready, but nobody has ordered yet. The bills, however, have already arrived.', question: 'Open the shutters or wait?', action: 'Make the call', note: 'The truck and grill are already committed. No workers or ingredients yet.' };
  if (state.round < 8) {
    const stories = ['', '', 'The first customers want 8 tacos. One worker can handle this small order.', 'The line is growing. Two workers can make 18 tacos, but your current crew can stay.', 'Tasks can now be divided between cooking, filling and serving. Three workers can make 31 tacos.', 'A larger order arrives. Four workers can make 42 tacos in the same kitchen.', 'The crowded kitchen faces 50 orders. A fifth worker adds capacity, but how much?', 'Customers want 53 tacos. A sixth worker may help, but there is little room left.'];
    return { title: ROUND_TITLES[state.round - 1], text: stories[state.round], question: state.experiment ? 'Try another crew for the same order?' : 'Keep your crew or hire?', action: 'Run lunch service', note: `${TARGETS[state.round]} tacos ordered. Ingredients match actual production automatically. A shortfall is a valid choice.` };
  }
  if (state.step === 'commitment') return { title: ROUND_TITLES[7], text: 'The campus wants a larger order. Decide how much to promise before choosing your equipment.', question: 'How many tacos will you promise?', action: 'Commit to this order', note: 'Choose equipment next. No production is recorded until service runs.' };
  if (state.step === 'equipment') return { title: 'One kitchen or two?', text: `You promised ${state.target} tacos. Keep your previous crew and truck, or equip a second kitchen and schedule six workers.`, question: 'Choose your operation.', action: 'Set up the operation', note: 'Expanding adds a fixed obligation. It is not automatically the least-cost choice.' };
  return { title: 'Divide the crew', text: `Two equipped trucks are ready for your ${state.target}-taco promise. Six workers are available.`, question: 'Where will the six workers work?', action: 'Run the expanded service', note: 'Each crew has its own grill and prep space. Allocation changes capacity.' };
}
export function consequence(state) {
  const trial = state.trials.at(-1), r = perService(trial);
  let why, insight = null;
  let headline = `Your crew made ${r.output} of ${r.plan.target} tacos. ${r.shortfall ? `${r.shortfall} orders remain unfilled.` : 'Order fulfilled.'}`;
  if (state.round === 1) {
    headline = state.opening === 'delay' ? 'The shutters stayed down. The equipment bill stayed.' : 'You opened, but no tacos were made yet.';
    why = `The truck and grill cost ${money(r.FC)} per lunch even at zero output. Variable cost is zero; waiting does not erase the existing fixed obligation.`;
  } else if (state.round === 2) {
    why = `${r.workers ? 'Hiring brings wages and ingredients into variable cost.' : 'Without a worker, you cannot produce; variable cost remains zero.'} Fixed cost stays ${money(r.FC)} whether you serve the order or miss it.`;
  } else if (state.round === 3) {
    why = `Your crew’s capacity is ${r.capacity} tacos, while the target is ${r.plan.target}. Actual output is the smaller of the order and capacity; hiring adds wage expense even if some capacity goes unused.`;
  } else if (state.round === 4) {
    why = 'Specialization raises the third worker’s potential contribution to 13 tacos, compared with 10 for the second. At full capacity, this lowers marginal cost to $6.62 per additional taco.';
    insight = `Calculated staffing reference: 2 → 3 workers, 18 → 31 tacos. Your actual crew: ${r.workers}; output: ${r.output}.`;
  } else if (state.round === 5) {
    why = 'The fourth worker adds 11 tacos of capacity, fewer than the third worker’s 13: diminishing marginal returns have begun. Total product still rises to 42; this is not automatically a bad hire.';
    insight = `Calculated staffing reference: 3 → 4 workers costs $82 for 11 extra tacos, or $7.45 each. Your actual crew: ${r.workers}.`;
  } else if (state.round === 6) {
    why = 'The fifth worker adds 8 tacos at full capacity. An extra $60 wage plus $16 in ingredients costs $76 for that increment: $9.50 per additional taco.';
    insight = `Calculated staffing reference: 4 → 5 workers, 42 → 50 tacos. Your actual crew: ${r.workers}; output: ${r.output}.`;
  } else if (state.round === 7) {
    const prior = state.trials.at(-2);
    const comparable = r.workers === 6 && r.output === 53 && prior?.workers === 5 && prior.output === 50 && prior.key === trial.key;
    why = comparable ? 'You hired another worker, but the crew produced only three additional tacos. The $66 increase makes each extra taco cost $22.' : 'Full-capacity reference: a sixth worker adds only 3 tacos beyond five workers. The $60 wage plus $6 of ingredients costs $66, or $22 per additional taco.';
    insight = 'When wages stay constant and marginal product falls, marginal cost rises. Extra output can still be worthwhile if its benefit exceeds that cost.';
  } else {
    const one = perService(autoIngredients({ trucks: 1, grills: [true, false], workers: [6, 0], target: r.plan.target }));
    why = r.plan.trucks === 2 ? `Your second kitchen raises fixed cost from $60 to $120 per lunch; the ${r.plan.workers.join(' + ')} allocation has capacity for ${r.capacity} tacos. ${r.plan.target <= 53 ? 'One truck can physically meet this target; expansion is not automatically cheaper.' : r.shortfall ? 'This allocation still leaves a shortfall.' : 'Your expanded crew met the larger order.'}` : `Your ${r.workers}-person crew has capacity for ${r.capacity} tacos; fixed cost stays $60. ${r.shortfall ? 'You saved the second fixed payment but left orders unfilled.' : 'You met this order using the existing equipment.'}`;
    insight = `Calculated comparison: six workers on one truck can make ${one.output} of this order for ${money(one.TC)}. Your choice made ${r.output} for ${money(r.TC)}. Different equipment starts a separate cost schedule; this comparison is not short-run MC.`;
  }
  return { headline, why, insight, cost: money(r.TC), output: `${r.output} / ${r.plan.target}`, feasible: r.feasible, title: state.round === 1 ? 'A bill before the first taco' : `${ROUND_TITLES[state.round - 1]} · Results` };
}
export function changeExplanation(trial) {
  const d = trial.change;
  if (!d) return 'This is your first recorded observation.';
  const direction = n => `${n >= 0 ? '+' : '−'}${Math.abs(n)}`;
  return `Since your previous trial: ${direction(d.deltaOutput)} tacos and ${d.deltaCost >= 0 ? '+' : '−'}${money(Math.abs(d.deltaCost))} per lunch. ${d.sameEquipment && d.costPerExtra !== null ? `This particular change cost ${money(d.costPerExtra, 2)} per extra taco.` : ''} ${d.sameEquipment ? 'That observed change can reflect order limits or idle labor; it is not the full-capacity staffing MC reference.' : 'Equipment changed, so do not interpret this difference as short-run MC.'}`;
}
export function review(state) {
  const accepted = acceptedTrials(state), last = state.trials.at(-1), r = perService(last);
  const met = accepted.filter(t => t.round > 1 && t.feasible).length;
  const costly = state.trials.filter(t => t.avoidable > 0);
  const testedCrew = [...new Set(state.trials.filter(t => t.round > 1 && t.plan.trucks === 1).map(t => t.workers))].sort((a, b) => a - b);
  const positive = state.trials.find(t => t.output > 0), p = positive ? perService(positive) : null;
  const refs = marginalSchedule({ trucks: 1, grills: [true, false] });
  const minOne = minimumPlan({ trucks: 1, grills: [true, false] }, last.plan.target);
  const minTwo = minimumPlan({ trucks: 2, grills: [true, true] }, last.plan.target);
  return `<section><h3>What happened?</h3><p>You ${state.opening === 'delay' ? 'delayed opening' : 'opened for orders'}, then chose ${accepted.slice(1).map(t => t.plan.target).join(', ')}-taco commitments. You met ${met} of the seven production-round targets in your final choices. ${state.trials.length - 8} additional experiment${state.trials.length - 8 === 1 ? '' : 's'} gave you extra evidence.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Your final round choices"><table><caption>Your final choice in each round · costs per lunch service</caption><thead><tr><th scope="col">Round</th><th scope="col">Crew A + B</th><th scope="col">Capacity</th><th scope="col">Made / promised</th><th scope="col">Total cost</th></tr></thead><tbody>${accepted.map(t => `<tr><th scope="row">${t.round}. ${ROUND_TITLES[t.round - 1]}</th><td>${t.plan.workers.slice(0, t.plan.trucks).join(' + ')}</td><td>${t.capacity}</td><td>${t.output} / ${t.plan.target}</td><td>${money(perService(t).TC)}</td></tr>`).join('')}</tbody></table></div><p>You ended with ${equipmentLabel(last.plan)}. ${last.shortfall ? `Your final promise exceeded actual production by ${last.shortfall} tacos.` : 'You fulfilled your final promise.'} ${p ? `Your first producing lunch cost ${money(p.TC)}; the final one cost ${money(r.TC)}.` : 'You chose not to produce in any round. Each fixed bill still applied.'} From opening to your final plan, total cost changed by ${money(r.TC - perService(accepted[0]).TC)} per lunch. ${costly.length ? `In ${costly.length} trial${costly.length === 1 ? '' : 's'}, paid inputs exceeded the minimum for actual output. For example, Trial ${costly[0].id} spent ${money(perService(costly[0]).avoidable)} extra per lunch with the same equipment.` : 'Each recorded plan attained minimum cost for its actual output with its own equipment. That does not mean each target was met, or that every equipment choice was cheapest.'}</p></section>
    <section><h3>Why did it happen economically?</h3><p><strong>Fixed costs and variable costs:</strong> your opening produced zero tacos but still cost ${money(perService(accepted[0]).FC)} per service. In your final plan, fixed cost was ${money(r.FC)}, labor ${money(r.labor)}, and ingredients ${money(r.ingredients)}. FC + VC = ${money(r.FC)} + ${money(r.VC)} = ${money(r.TC)}. Ingredients were bought only for completed tacos, so no hidden waste was charged.</p><p><strong>Capacity and marginal cost — calculated references:</strong> You tested one-truck crews of ${testedCrew.join(", ")} workers. Specialization makes the first three workers increasingly productive (8, 10, then 13 extra tacos). The fourth adds 11, the fifth 8, and the sixth 3. Output still rises even as marginal product falls. At full-capacity staffing endpoints, MC = ΔTC/ΔQ: ${money(refs[3].MC, 2)} for Worker 3, ${money(refs[4].MC, 2)} for Worker 4, ${money(refs[5].MC, 2)} for Worker 5 and ${money(refs[6].MC, 2)} for Worker 6. Hiring is worthwhile if the benefit of extra output exceeds its cost; diminishing returns alone cannot settle that decision.</p><p><strong>Order limits matter:</strong> increasing a 20-taco order from two to three workers makes 2 additional tacos and adds ${money(COSTS.wage + 2 * COSTS.kit)} per lunch: ${money(COSTS.wage / 2 + COSTS.kit)} per extra taco for that particular decision. The third worker’s full-capacity MC is still ${money(refs[3].MC, 2)}, based on 13 extra tacos. These are different comparisons. Making another taco using already staffed idle capacity adds only a ${money(COSTS.kit)} ingredient kit.</p><p><strong>Average costs:</strong> AFC = FC/Q, AVC = VC/Q, and ATC = TC/Q. For your last ${r.output}-taco lunch, these were ${money(r.AFC, 2)}, ${money(r.AVC, 2)} and ${money(r.ATC, 2)} per taco. The fixed bill spread over more tacos makes AFC fall; AVC and ATC also depend on productivity and idle labor. Averages at zero output are undefined, not zero.</p><p><strong>Changing capital:</strong> in each short-run plan, trucks, grills and prep space are fixed. Adding a truck changes the production technology and starts a separate short-run cost relationship. Comparing equipment choices is a long-run planning decision. At your final ${last.plan.target}-taco target, the calculated minimum is ${minOne ? money(perService(minOne).TC) + ' per lunch with one equipped truck' : 'infeasible with one truck'} and ${minTwo ? money(perService(minTwo).TC) + ' with two' : 'infeasible even with two'}. ${last.plan.target > 53 ? 'Expansion may be necessary for the target, but a poor allocation can still leave a shortage.' : 'A smaller order does not automatically justify a second fixed payment.'} These calculated alternatives are not additional student observations.</p></section>
    <section><h3>Where else does this apply?</h3><p>A bakery pays $45 per service for an oven. Two bakers can make 30 loaves; three can make 42. Each baker earns $60, and ingredients cost $1 per loaf. A 40-loaf promise needs three bakers: cost is $45 + $180 + $40 = $265 per service. Two bakers miss the target, even with plenty of ingredients.</p><p>The oven bill remains at zero output. The third baker’s full-capacity increment costs ($60 + 12 × $1)/12 = $6 per additional loaf. A second oven changes the fixed inputs. The same questions apply: can the plan deliver, what does it cost, and are the extra units worth producing?</p></section>`;
}
