import { money } from './content.js';
import { perService } from './engine.js';
import { curvesView } from './graphs.js';
import { labGraphState } from './gameplay.js';

export function labView(state, curves) {
  const p = state.lab.plan, last = state.lab.trials.at(-1), r = last && perService(last);
  const number = (id, label, value, max) => `<label for="lab-${id}">${label}<input id="lab-${id}" name="${id}" type="number" min="0" max="${max}" step="1" value="${value}" required></label>`;
  return `<section class="review lab"><p class="eyebrow">Optional · after the eight-round story</p><h2 id="stage-title" tabindex="-1">Free Play / Cost Lab</h2><p>Try a different operation. Lab trials have their own graph and history; your story review stays unchanged. Ingredients match actual output automatically.</p><form id="lab-form"><div class="lab-controls">${number('target', 'Tacos ordered', p.target, 200)}<label for="lab-trucks">Trucks<select id="lab-trucks" name="trucks"><option value="1" ${p.trucks === 1 ? 'selected' : ''}>One truck</option><option value="2" ${p.trucks === 2 ? 'selected' : ''}>Two trucks</option></select></label>${number('workers-a', 'Truck A workers', p.workers[0], 6)}${number('workers-b', 'Truck B workers (two trucks only)', p.workers[1], 6)}<label class="check"><input name="grill-a" type="checkbox" ${p.grills[0] ? 'checked' : ''}>Equip Truck A with a grill</label><label class="check"><input name="grill-b" type="checkbox" ${p.grills[1] ? 'checked' : ''}>Equip Truck B with a grill (two trucks only)</label></div><p class="small">A crew needs a grill to produce. Workers still earn wages when equipment or orders leave them idle. One-truck plans use only Truck A.</p><button class="primary" type="submit">Run lab service →</button></form>${r ? `<section aria-label="Lab result"><h3>Lab trial ${last.id}</h3><p>${r.output} / ${r.plan.target} tacos · capacity ${r.capacity} · total cost ${money(r.TC)} per lunch.</p><p>${r.shortfall ? `${r.shortfall} orders unfilled.` : 'Order fulfilled.'} ${r.avoidable ? `${money(r.avoidable)} above the minimum for this actual output and equipment.` : 'Minimum cost for this actual output with this equipment.'} Fixed cost ${money(r.FC)}; variable cost ${money(r.VC)}.</p><div id="lab-curves-content">${curvesView(labGraphState(state), curves)}</div><button data-action="report">Open Lab Cost Report</button></section>` : '<p class="empty-graph">Run a lab service to record your first lab observation.</p>'}<div class="actions"><button data-action="lab-exit">← Back to my eight-round review</button></div></section>`;
}
