import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import gate from '../../server/classroom-access/worker.mjs';
const root=path.resolve(process.argv[2]||'.'),out=path.join(root,'validation_artifacts/classroom_access'),results=[];
const base='/play/managerial-directorate-classroom';
// Ephemeral synthetic fixtures exist in memory only and are never printed.
const code=crypto.randomBytes(18).toString('base64url'),secret=crypto.randomBytes(48).toString('base64url');
let attempts=0,assets=0;
const env={CLASSROOM_ACCESS_CODE:code,CLASSROOM_SESSION_SECRET:secret,CLASSROOM_LOGIN_LIMIT:{async limit(){return{success:++attempts<=120};}},ASSETS:{async fetch(req){assets++;return new Response('STATIC '+new URL(req.url).pathname,{headers:{'content-type':'text/plain','cache-control':'public,max-age=60'}});}}};
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',detail:e.message.replaceAll(code,'[redacted fixture]').replaceAll(secret,'[redacted fixture]')});}}
const request=(p=base+'/',options={})=>new Request('https://classroom.test'+p,options);
const login=(p=base+'/',value=code,extra={})=>request(p,{method:'POST',headers:{origin:'https://classroom.test','content-type':'application/x-www-form-urlencoded',...extra},body:new URLSearchParams({accessCode:value})});
let cookie;
for(const p of [base+'/',...['cost-directive','market-signal','strategy-desk','agency-protocol'].flatMap(g=>[`${base}/${g}/`,`${base}/${g}/index.html`]),base+'/telemetry-client.js',base+'/telemetry-storage-isolation.js',base+'/anything'])await check('Unauthenticated subtree '+p,async()=>{const before=assets,r=await gate.fetch(request(p),env);assert.equal(r.status,200);assert.ok((await r.text()).includes('Enter the class access code'));assert.equal(assets,before);assert.equal(r.headers.get('set-cookie'),null);assert.match(r.headers.get('cache-control'),/no-store/);});
await check('Slashless entry canonicalizes without exposing static content',async()=>{const r=await gate.fetch(request(base),env);assert.equal(r.status,303);assert.equal(r.headers.get('location'),base+'/');});
// Test the fallback with only ASSETS configured: no gate dependency outside its boundary.
await check('Public pages, shared assets, POC and API pass directly to original assets handler',async()=>{for(const p of ['/','/play/managerial-intelligence-directorate/cost-directive/','/play/managerial-intelligence-directorate/managerial-parity.css','/play/managerial-directorate-telemetry-poc/','/play/economic-realm/','/build/','/api/anonymous-telemetry-poc/v1/events',base+'-other/']){const r=await gate.fetch(request(p),{ASSETS:env.ASSETS});assert.equal(await r.text(),'STATIC '+p);assert.equal(r.headers.get('cache-control'),'public,max-age=60');}});
await check('Wrong code is generic, unreflected, and issues no cookie',async()=>{const wrong=crypto.randomBytes(20).toString('hex'),r=await gate.fetch(login(base+'/',wrong),env);assert.equal(r.status,403);const html=await r.text();assert.ok(html.includes('That access code is not valid.'));assert.ok(!html.includes(wrong));assert.equal(r.headers.get('set-cookie'),null);});
await check('Correct code returns original child path with narrow signed 10-hour cookie',async()=>{const r=await gate.fetch(login(base+'/cost-directive/'),env);assert.equal(r.status,303);assert.equal(r.headers.get('location'),base+'/cost-directive/');cookie=r.headers.get('set-cookie');assert.ok(cookie&&!cookie.includes(code)&&!cookie.includes(secret));for(const flag of ['HttpOnly','Secure','SameSite=Lax','Max-Age=36000','Path='+base+'/'])assert.ok(cookie.includes(flag));assert.ok(!cookie.includes('Domain='));cookie=cookie.split(';')[0];const payload=JSON.parse(Buffer.from(cookie.split('=')[1].split('.')[0],'base64url'));assert.deepEqual(Object.keys(payload).sort(),['exp','iat','v']);assert.equal(payload.exp-payload.iat,36000);});
await check('Authenticated navigation covers all games and client assets with no-store',async()=>{for(const p of ['cost-directive/','market-signal/','strategy-desk/','agency-protocol/','telemetry-client.js']){const r=await gate.fetch(request(base+'/'+p,{headers:{cookie}}),env);assert.equal(await r.text(),'STATIC '+base+'/'+p);assert.match(r.headers.get('cache-control'),/no-store/);}});
await check('Tampered, malformed and duplicate cookies are rejected',async()=>{for(const value of [cookie.slice(0,-3)+'xxx','__Secure-MQClassroom=not.signed',cookie+'; '+cookie,'__Secure-MQClassroom='+('x'.repeat(600))]){const r=await gate.fetch(request(base+'/',{headers:{cookie:value}}),env);assert.ok((await r.text()).includes('Enter the class access code'));}});
async function token(data){const payload=Buffer.from(JSON.stringify(data)).toString('base64url');const sig=crypto.createHmac('sha256',secret).update('classroom-session:'+payload).digest('base64url');return'__Secure-MQClassroom='+payload+'.'+sig;}
await check('Expired, future-dated, overlong and extra-field signed sessions fail validation',async()=>{const now=Math.floor(Date.now()/1000);for(const data of [{v:1,iat:now-36001,exp:now-1},{v:1,iat:now+60,exp:now+36060},{v:1,iat:now,exp:now+999999},{v:1,iat:now,exp:now+36000,anonymousClientId:'disallowed'}]){const r=await gate.fetch(request(base+'/',{headers:{cookie:await token(data)}}),env);assert.ok((await r.text()).includes('Enter the class access code'));}});
await check('Code rotation preserves sessions; signing-secret rotation invalidates them',async()=>{let r=await gate.fetch(request(base+'/',{headers:{cookie}}),{...env,CLASSROOM_ACCESS_CODE:crypto.randomBytes(18).toString('hex')});assert.ok((await r.text()).startsWith('STATIC'));r=await gate.fetch(request(base+'/',{headers:{cookie}}),{...env,CLASSROOM_SESSION_SECRET:crypto.randomBytes(48).toString('hex')});assert.ok((await r.text()).includes('Enter the class access code'));});
await check('Missing secrets and pilot closure fail closed even for existing sessions',async()=>{for(const overrides of [{CLASSROOM_ACCESS_CODE:''},{CLASSROOM_SESSION_SECRET:''},{CLASSROOM_CLOSED:'true'}]){const r=await gate.fetch(request(base+'/',{headers:{cookie}}),{...env,...overrides});assert.equal(r.status,503);assert.ok((await r.text()).includes('currently closed'));}});
await check('Cross-origin POST, extra redirect fields and oversized bodies are denied',async()=>{let r=await gate.fetch(login(base+'/',code,{origin:'https://other.test'}),env);assert.equal(r.status,403);for(const body of [new URLSearchParams({accessCode:code,next:'https://other.test'}),'x'.repeat(3000)]){r=await gate.fetch(request(base+'/',{method:'POST',headers:{origin:'https://classroom.test','content-type':'application/x-www-form-urlencoded'},body}),env);assert.equal(r.status,400);assert.equal(r.headers.get('set-cookie'),null);}});
await check('Encoded and repeated-slash classroom paths cannot bypass authorization or redirect externally',async()=>{for(const p of ['/%70lay/managerial-directorate-classroom/cost-directive/','/play/%6danagerial-directorate-classroom/index.html','//play//managerial-directorate-classroom/cost-directive/','/play/managerial-directorate-classroom%2fcost-directive/','/play/managerial-directorate-classroom/%2e/cost-directive/']){const r=await gate.fetch(request(p),env);assert.ok((await r.text()).includes('Enter the class access code'));}const r=await gate.fetch(login('//play//managerial-directorate-classroom/cost-directive/'),env);assert.equal(r.headers.get('location'),base+'/cost-directive/');});
await check('Shared rate limit rejects guessing and expires without affecting valid sessions',async()=>{attempts=0;for(let i=0;i<120;i++)assert.equal((await gate.fetch(login(base+'/','incorrect'),env)).status,403);let r=await gate.fetch(login(),env);assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'60');r=await gate.fetch(request(base+'/',{headers:{cookie}}),env);assert.ok((await r.text()).startsWith('STATIC'));attempts=0;assert.equal((await gate.fetch(login(),env)).status,303);});
await check('Rate-limit binding absence/failure cannot accidentally authorize',async()=>{for(const binding of [undefined,{async limit(){throw Error('unavailable');}}]){const r=await gate.fetch(login(),{...env,CLASSROOM_LOGIN_LIMIT:binding});assert.ok([429,503].includes(r.status));assert.equal(r.headers.get('set-cookie'),null);}});
await check('All prior tracked files except approved root config remain byte-identical',async()=>{const hashes=JSON.parse(fs.readFileSync(path.join(out,'baseline_hashes.json')));for(const [p,hash]of Object.entries(hashes))if(p!=='wrangler.jsonc')assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex'),hash,p);});
await check('Root config preserves original asset directory and Worker; no route or backend changes',async()=>{const config=JSON.parse(fs.readFileSync(path.join(root,'wrangler.jsonc')));assert.equal(config.name,'masteryquests-website');assert.equal(config.assets.directory,'./dist');assert.deepEqual(config.assets.run_worker_first,[base,base+'/*']);assert.equal(config.assets.binding,'ASSETS');assert.equal(config.main,'server/classroom-access/worker.mjs');assert.equal(config.routes,undefined);assert.equal(config.vars,undefined);assert.equal(config.ratelimits[0].simple.limit,120);});
const failed=results.filter(r=>r.status==='FAIL');const report={passed:results.length-failed.length,failed:failed.length,total:results.length,results};fs.writeFileSync(path.join(out,'validation_results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(failed.length)process.exitCode=1;
