export const PHASE2B_SOURCE_VERSION = "National-Ledger-2026.08.24-phase2b";

// These ranges belong only to the supplemental Phase 2B source. Expanding the
// batch requires updating both the range and expected count deliberately.
export const PHASE2B_OWNERSHIP = {
  ordinary: { start: 42000, end: 42011, expected: 12 },
  repair: { start: 43000, end: 43004, expected: 5 },
  bridge: { start: 44000, end: 44007, expected: 8 }
};

const defaults = {
  labor_force_calculation: { objective: "LO29.1", cluster: "labor_market", tag: "labor_force_stats", commonError: "Including people outside the labor force or omitting active job seekers from the labor-force total." },
  discouraged_workers: { objective: "LO29.2", cluster: "labor_market", tag: "employment_categories", commonError: "Counting discouraged workers as unemployed even though they are not actively searching." },
  technological_knowledge: { objective: "LO26.3", cluster: "growth_productivity", tag: "productivity_factors", commonError: "Confusing improved production know-how with more machines or more worker training." },
  human_capital: { objective: "LO26.3", cluster: "growth_productivity", tag: "productivity_factors", commonError: "Treating schooling or equipment as proof of productive worker knowledge and skills." },
  natural_resources: { objective: "LO26.3", cluster: "growth_productivity", tag: "productivity_factors", commonError: "Assuming natural-resource abundance is necessary or sufficient for high productivity." },
  nominal_vs_real_gdp: { objective: "LO24.4", cluster: "real_nominal_gdp", tag: "real_nominal_gdp", commonError: "Treating nominal spending growth as real output growth without adjusting for prices." }
};

const Q = (id, pool, skill, type, q, answer, distractors, feedback, extra = {}) => ({
  id, pool, skill, type, q, answer, distractors, feedback,
  objective: extra.objective || defaults[skill].objective,
  conceptCluster: extra.conceptCluster || defaults[skill].cluster,
  tag: extra.tag || defaults[skill].tag,
  secondarySkills: extra.secondarySkills || [],
  commonError: extra.commonError || defaults[skill].commonError
});

export const ordinaryQuestions = [
  Q(42000, "hard", "labor_force_calculation", "multi-step", "An economy has 142 million employed adults, 8 million jobless adults who searched recently, 5 million discouraged workers, and 45 million other adults outside the labor force. What is the labor force, and whom does it include?", "150 million; employed adults plus active job seekers", ["155 million; employed adults, active job seekers, and discouraged workers", "200 million; every adult in the economy", "147 million; employed adults plus discouraged workers"], "The labor force is employed plus unemployed people who are actively searching: 142 + 8 = 150 million."),
  Q(42001, "elite", "labor_force_calculation", "multi-step", "An economy begins with 120 million employed and 10 million unemployed. During the month, 4 million unemployed people find jobs, 3 million stop searching, and 5 million people outside the labor force begin searching without finding work. What is the new labor force?", "132 million; 124 million employed plus 8 million unemployed", ["134 million; 124 million employed plus the original 10 million unemployed", "129 million; everyone who stopped searching remains in the labor force", "137 million; all five new searchers are counted twice"], "Employment becomes 124 million and unemployment becomes 10 - 4 - 3 + 5 = 8 million, so the labor force is 132 million."),
  Q(42002, "legendary", "labor_force_calculation", "integration", "An economy has 250 million adults, with 150 million employed and 10 million unemployed. Then 6 million unemployed people find jobs, 4 million stop searching, 8 million people outside the labor force begin searching, and 3 million employed people retire. What are the new labor force and participation rate?", "161 million and 64.4%", ["158 million and 63.2%", "165 million and 66.0%", "169 million and 67.6%"], "Employment becomes 153 million and unemployment becomes 8 million. The labor force is 161 million, and 161 / 250 = 64.4%."),
  Q(42003, "hard", "technological_knowledge", "multi-step", "A plant produces 800 units with 100 worker-hours. It adopts a new workflow algorithm, using the same workers and machines, and produces 1,000 units. What changed most directly?", "Technological knowledge improved, raising productivity from 8 to 10 units per hour", ["Physical capital rose by 25%, raising productivity to 8 units per hour", "Human capital fell because the plant used an algorithm", "Natural resources increased because output rose by 200 units"], "The production method changed while measured labor and machines stayed fixed. Output per hour rose from 8 to 10, a 25% productivity gain."),
  Q(42004, "elite", "technological_knowledge", "integration", "Two factories start with identical workers and machines. Factory A trains its workers; Factory B licenses a more efficient production process. Both raise output. Which comparison is economically correct?", "A primarily adds human capital, while B primarily adds technological knowledge", ["Both changes are physical capital because both raise output", "A adds natural resources, while B adds human capital", "Both changes prove technological knowledge rose by the same amount"], "Training develops worker skills; a licensed production method changes know-how. Both can raise productivity through different channels."),
  Q(42005, "legendary", "technological_knowledge", "integration", "A country spreads one nonrival production formula across many firms while capital per worker, formal schooling, and natural resources remain unchanged. Output per worker rises, but later licensing barriers slow further adoption. What is the strongest conclusion?", "Technological knowledge raised productivity, and barriers to diffusion limited later gains", ["Physical capital caused the gain because every firm used the formula", "Human capital must have risen because output per worker increased", "Natural resources caused the gain, and licensing protected those resources"], "Production know-how can be reused broadly without being used up. Restrictions on diffusion can prevent firms from adopting that knowledge."),
  Q(42006, "elite", "human_capital", "integration", "A firm installs better machines and trains workers at the same time. Output per hour then rises 30%. What can the evidence establish about human capital?", "Training increased human capital, but the 30% gain cannot be attributed to training alone", ["The full 30% productivity gain proves human capital alone rose by exactly 30%", "Human capital did not change because physical capital was installed at the same time", "The entire productivity gain must come from technological knowledge rather than training"], "Training builds human capital, but two inputs changed together, so the observed productivity gain cannot identify training's separate effect."),
  Q(42007, "legendary", "human_capital", "integration", "Two countries report the same increase in average years of schooling. In Country A, literacy, numeracy, and job skills rise sharply; in Country B, attendance rises but measured learning does not. Which inference is most defensible?", "Country A shows stronger evidence of human-capital growth; schooling years alone do not prove it", ["Both countries gained equal human capital because schooling years are equal", "Country B gained more human capital because learning stayed constant", "Neither country can gain human capital without adding machines"], "Human capital is productive knowledge and skill. Time in school is an input, but learning evidence better establishes whether productive capacity improved."),
  Q(42008, "elite", "natural_resources", "multi-step", "A country discovers oil. Real GDP rises 8%, population rises 10%, and non-oil productivity is unchanged. What is the most careful conclusion?", "Natural-resource output rose, but real GDP per person may have fallen", ["The discovery guarantees higher living standards because total GDP rose", "Technological knowledge rose 10% because population increased", "Human capital necessarily fell because non-oil productivity was unchanged"], "Resource extraction can raise total output without guaranteeing higher output per person; population grew faster than real GDP."),
  Q(42009, "legendary", "natural_resources", "integration", "Resource-rich Country R relies on extraction and invests little in skills or production methods. Resource-poor Country S imports raw materials and develops strong human capital and technology. Country S eventually has higher output per worker. What does this comparison establish?", "Natural resources are neither necessary nor sufficient for high productivity", ["Natural resources always reduce productivity through diminishing returns", "Imported resources count as technological knowledge", "Country R must have higher real GDP per person because it owns more resources"], "Resources can support production, but productivity also depends on capital, skills, technology, and institutions. Resource ownership alone does not determine the outcome."),
  Q(42010, "elite", "nominal_vs_real_gdp", "multi-step", "Using the growth-rate approximation, nominal GDP rises 18%, the GDP deflator rises 12%, and population rises 3%. About how much does real GDP per person rise?", "3%", ["6%", "15%", "33%"], "Approximate real GDP growth is 18% - 12% = 6%. Subtracting 3% population growth gives about 3% real GDP-per-person growth."),
  Q(42011, "legendary", "discouraged_workers", "integration", "An economy begins with 180 million employed and 12 million unemployed. Four million unemployed people find jobs, five million stop searching, and three million people outside the labor force begin searching without finding work. Which interpretation is best?", "Employment rises, but labor-force exit also makes the measured unemployment rate fall", ["Every decline in unemployment represents a new job", "The labor force rises because discouraged workers remain unemployed", "Employment falls because new job seekers are counted as unemployed"], "Employment rises to 184 million, while unemployment falls to 6 million partly because five million people leave the labor force. The lower rate is not solely job creation.")
];

export const repairQuestions = [
  Q(43000, "repair", "labor_force_calculation", "repair", "Repair: An economy has 80 employed people, 5 jobless people actively seeking work, and 4 discouraged workers. What is the labor force?", "85", ["89", "84", "80"], "The labor force includes the 80 employed and 5 active job seekers; discouraged workers are outside it."),
  Q(43001, "repair", "technological_knowledge", "repair", "Repair: Which example is technological knowledge?", "Knowing a more efficient way to combine inputs", ["Owning an additional delivery truck for the firm", "Finding a new mineral deposit for production", "Adding another hour of worker labor"], "Technological knowledge is know-how about production methods."),
  Q(43002, "repair", "human_capital", "repair", "Repair: Which change most directly increases human capital?", "Workers learn job-relevant skills in training", ["The firm purchases additional production machinery", "The country discovers a new oil field", "The price level rises across the economy"], "Education and training increase the productive knowledge and skills workers carry into production."),
  Q(43003, "repair", "natural_resources", "repair", "Repair: A farm uses fertile soil, a tractor, worker training, and a new planting method. Which input is supplied by nature?", "The fertile soil", ["The tractor used by workers", "The workers' training", "The new planting method"], "Soil is supplied by nature; the other inputs are physical capital, human capital, and technological knowledge."),
  Q(43004, "repair", "discouraged_workers", "repair", "Repair: A jobless person wants work but has stopped actively searching because no jobs seem available. How is the person classified?", "Not in the labor force", ["Employed in the labor force", "Unemployed in the labor force", "Frictionally unemployed in the labor force"], "Without active job search, a discouraged worker is outside the measured labor force.")
];

export const bridgeQuestions = [
  Q(44000, "bridge", "labor_force_calculation", "bridge", "Bridge: An economy has 95 employed people, 5 jobless people who applied for work this month, and 10 jobless people who stopped searching. What is the labor force?", "100", ["110", "105", "95"], "The labor force is 95 employed plus 5 active job seekers, or 100."),
  Q(44001, "bridge", "technological_knowledge", "bridge", "Bridge: A bakery uses the same ovens, ingredients, and worker-hours but adopts a better scheduling method and produces more bread. Which factor improved?", "Technological knowledge", ["Physical capital", "Natural resources", "Labor-force participation"], "A better method for combining unchanged inputs is an improvement in technological knowledge."),
  Q(44002, "bridge", "human_capital", "bridge", "Bridge: Workers learn to diagnose equipment failures, while the factory's machines remain unchanged. Which productivity factor rises?", "Human capital", ["Physical capital", "Natural resources", "Net exports"], "The workers gained productive knowledge and skill, which is human capital."),
  Q(44003, "bridge", "human_capital", "bridge", "Bridge: A training program raises test scores and lets workers produce more with the same equipment. What evidence connects the program to human capital?", "Worker skills and output per worker both increased", ["The number of machines increased", "The country discovered more minerals", "The price of the firm's output increased"], "The learning measure and higher output with unchanged equipment both support a human-capital channel."),
  Q(44004, "bridge", "natural_resources", "bridge", "Bridge: A region discovers a new freshwater source used by farms, with worker skills and machinery unchanged. Which productivity input increased?", "Natural resources", ["Human capital", "Physical capital", "Technological knowledge"], "Water supplied by nature is a natural resource used in production."),
  Q(44005, "bridge", "discouraged_workers", "bridge", "Bridge: Four discouraged workers resume active job searches, but none finds a job. What happens immediately to the measured labor force and unemployment?", "Both rise by four while employment is unchanged", ["Both fall by four while employment is unchanged", "The labor force rises by four and unemployment falls by four", "Only employment rises because active search counts as work"], "Active search moves all four people into the labor force as unemployed; it does not make them employed."),
  Q(44006, "bridge", "nominal_vs_real_gdp", "bridge", "Bridge: Nominal GDP grows 10% while the GDP deflator grows 6%. Using the growth-rate approximation, how much does real GDP grow?", "About 4%", ["About 16%", "About 10%", "About 6%"], "Approximate real GDP growth equals nominal GDP growth minus price growth: 10% - 6% = 4%."),
  Q(44007, "bridge", "nominal_vs_real_gdp", "bridge", "Bridge: Prices rise while the quantities of all final goods stay unchanged. Which GDP measure isolates the unchanged production?", "Real GDP", ["Nominal GDP", "Net exports", "The consumer price index"], "Real GDP values output at constant prices, so it isolates changes in quantities rather than current prices.")
];
