from checkpoint_support import *
SPECIAL={'ECON-SP-EASYBOSS-2002','ECON-SP-EASYBOSS-2005','ECON-SP-EASYBOSS-2008','ECON-SP-EASYBOSS-2011','ECON-SP-EASYBOSS-2014'}
for id in SPECIAL:
 patch(id,'MAA-0113 integrated-task complaint is not applicable after explicit instructor-directed specialist routing; preserve specialist checkpoint scope.')
for j,id in enumerate(i for i in candidates('integrated-macroeconomic-analysis') if i not in SPECIAL):
    a=20+10*j;mode=j%12
    if mode==0:
        stem=f'A negative demand shock creates a ${4*a} recessionary gap with falling inflation; capacity is unchanged. In a fixed-price planning model MPC is 0.75. A purchases increase of ${a} can arrive immediately, or the same program can arrive after the gap is forecast to close. Which assessment combines diagnosis, size and timing?'
        ans=[f'The immediate program matches the current gap; the delayed one risks excess demand after recovery',f'Both programs match every future gap because the multiplier makes timing irrelevant',f'The immediate program is contractionary; the delayed program becomes expansionary solely because time passes',f'The shock is adverse supply, so immediate purchases necessarily reduce inflation while restoring output']
        fb=f'Falling output and inflation under the stated demand shock justify demand support. The immediate simple effect is {a}/.25={4*a}, matching the current gap. A correct initial size does not make the same arrival-time demand injection appropriate after recovery.';p=proof((f'{a}/.25',4*a))
    elif mode==1:
        stem=f'An adverse supply shock lowers output ${a} below potential and raises inflation. Two plans each move AD by ${a} in opposite directions while the supply constraint persists. Which comparison correctly distinguishes their short-run objectives?'
        ans=['Expansion supports output but adds price pressure; contraction reduces price pressure but deepens the output loss','Expansion supports output and reduces price pressure; contraction reduces both output and inflation','Both plans repair the supply constraint and restore potential without a tradeoff','Contraction raises output by lowering aggregate demand; expansion lowers output by raising it']
        fb='The supplied shock worsens the supply tradeoff. Changing AD moves along the constrained supply relation: it does not restore the lost supply capability. Price stabilization and output stabilization therefore pull demand policy in opposite directions.';p=None
    elif mode==2:
        stem=f'Monetary easing lowers rates and raises investment ${a}. MPC is 0.5 in a fixed-price model. A foreign recession separately reduces AD by a total ${3*a} after induced effects. Which net conclusion distinguishes a working monetary channel from the economy-wide result?'
        ans=[f'The monetary channel adds ${2*a}, but net AD falls ${a}; a working channel can coexist with contraction',f'Net AD rises ${2*a}; a working monetary channel makes the foreign effect irrelevant',f'Net AD falls ${2*a}; multiply the already-total foreign effect again',f'Net AD rises ${4*a}; combine both shocks as if both increased spending']
        fb=f'Investment contributes {a}/(1−.5)={2*a}; subtract the total foreign-demand reduction {3*a}, giving −{a}. Policy transmission can operate as expected while a larger countershock dominates the net outcome.';p=proof((f'{a}/.5-{3*a}',-a))
    elif mode==3:
        stem=f'A fixed-price fiscal plan raises purchases ${a} with MPC 0.75. The resulting rate increase produces a total AD crowding-out offset ${2*a}, already including induced effects. Monetary accommodation could remove half that offset without changing the direct spending impulse. Which comparison is correct?'
        ans=[f'Net AD rises ${2*a} without accommodation and ${3*a} with it; the change comes from a smaller offset',f'Net AD rises ${4*a} under either plan because the gross multiplier is unchanged',f'Net AD is negative under both plans because the total offset must be multiplied again',f'Accommodation doubles the purchases impulse and therefore doubles the gross multiplier effect']
        fb=f'Gross effect=4×{a}={4*a}. Without accommodation subtract {2*a}, leaving {2*a}; with half the offset subtract {a}, leaving {3*a}. Compare total offsets at the same stage.';p=proof((f'4*{a}-{2*a}',2*a),(f'4*{a}-{a}',3*a))
    elif mode==4:
        stem=f'A government finances ${a} of spending through money creation. In the subsequent long-run comparison, money grows 9%, velocity falls 2%, and real output grows 3%. Use the growth-rate approximation; expected inflation adjusts to that result while the expected real rate stays 2%. Which inflation/interest interpretation is supported?'
        ans=['Inflation is approximately 4% and the nominal rate approximately 6%; neither follows from money growth alone','Inflation is approximately 9% and the nominal rate 11%; velocity and real output are irrelevant','Inflation is approximately 10% and the nominal rate 8%; subtract the real rate from inflation','Inflation is approximately 4% and the nominal rate 2%; expected inflation never affects nominal rates']
        fb='Approximate inflation is gM+gV−gY=9−2−3=4%. With expected inflation adapting and real rate fixed at 2%, Fisher gives nominal interest≈2+4=6%. Money financing can affect both real balances and nominal returns through these specified channels.';p=proof(('9-2-3',4),('2+4',6))
    elif mode==5:
        stem=f'Use inflation = expected inflation − (unemployment−5) + supply offset. A temporary supply offset of +2 yields inflation 6% at unemployment 6% in an economy with output ${a}. Before the offset disappears, forecasts rise one point and persist. Which initial expectation and final natural-rate inflation follow?'
        ans=['Initial expected inflation is 5%; final inflation at natural unemployment is 6% after the offset ends','Initial expected inflation is 6%; final natural-rate inflation is 9% because the temporary offset persists','Initial expected inflation is 3%; final natural-rate inflation is 4% because the unemployment gap is subtracted twice','Initial expected inflation is 5%; final natural-rate inflation is 8% because the removed offset is added again']
        fb='Initially 6=πe−1+2, so πe=5. Forecasts then become6. After the supply offset ends and unemployment is5, inflation equals expected inflation6. Supply relief does not necessarily restore the original expectation.';p=proof(('6+(6-5)-2',5),('5+1-(5-5)',6))
    elif mode==6:
        stem=f'A four-point disinflation in an economy with annual output ${a} has an expected cumulative loss of 8% of annual output. Faster expectation adjustment reduces the predicted loss to 5%, with the same final natural unemployment and inflation target. Which assessment separates transition cost from endpoint?'
        ans=['The ratio falls from 2 to 1.25; the lower transition cost does not require a different natural-rate endpoint','The ratio rises from 1.25 to 2; better credibility must increase transition cost','The natural rate falls by three points because cumulative loss falls three points','The two ratios are equal because both programs end at the same inflation rate']
        fb='Ratios are loss/inflation reduction:8/4=2 and5/4=1.25. Faster expectation adjustment can change the route and cost while leaving the same long-run unemployment benchmark.';p=proof(('8/4',2),('5/4',1.25))
    elif mode==7:
        stem=f'Nominal GDP grows 6% while the deflator grows 8%, from an initial real-output level ${a}. The unemployment rate also rises, but population and participation data are not supplied. Which combined conclusion and limit are supported?'
        ans=['Real output falls about 1.9%; the unemployment rise is consistent with weakness but does not by itself identify labor-force flows','Real output rises 6%; higher nominal spending proves real expansion despite prices','Real output falls exactly 2%; the unemployment rise proves every additional unemployed person lost a job','Real output rises 14%; combine nominal and price growth, and infer a lower natural unemployment rate']
        fb='Exact real growth is1.06/1.08−1≈−1.85%. Labor-market rates can also change with entry/exit, so the rate observation does not identify all underlying flows. The two indicators should be reconciled without inventing missing employment data.';p=proof(('(1.06/1.08-1)*100',-1.851851852))
    elif mode==8:
        stem=f'Productivity improves and potential output rises from {5*a} to {6*a}. Separately, temporary demand expansion raises actual output to {7*a}. Which policy diagnosis avoids mistaking all actual growth for capacity growth?'
        ans=[f'Capacity rose {a}, but actual output is still {a} above the new potential; both supply growth and excess demand are present',f'All {2*a} of actual growth is new capacity because observed output defines potential',f'Capacity is unchanged at {5*a}; productivity affects only nominal demand',f'The new potential must be {7*a}; a demand boom permanently moves LRAS']
        fb=f'Compare actual output with the updated productive benchmark, not the old one: {7*a}−{6*a}={a}. A real capacity improvement and a temporary positive demand gap can coexist.';p=proof((f'{6*a}-{5*a}',a),(f'{7*a}-{6*a}',a))
    elif mode==9:
        stem=f'A banking system receives ${a} of reserves. With rr=10%, a simple maximum suggests deposits of ${10*a}; actual deposits grow ${4*a}. Rates fall, but firms also cut expected project returns. Which assessment combines banking and spending constraints?'
        ans=['Leakages can explain a multiplier below ten, and weaker expected returns can further limit investment despite lower rates','The lower deposit expansion proves rates cannot have fallen, so the reported observations are impossible','Lower rates guarantee the full predicted investment expansion even when expected returns deteriorate','The reserve injection raises real productive capacity immediately by the textbook deposit maximum']
        fb=f'Observed multiplier={4*a}/{a}=4, below the restrictive simple maximum10. Even if rates fall, the rate-to-investment link can weaken when expected profitability falls. These are distinct constraints at successive stages.';p=proof((f'{4*a}/{a}',4))
    elif mode==10:
        stem=f'An economy initially has output {a} above potential and unemployment below natural after a demand boom. Demand then stabilizes while wage setters revise expected inflation upward. A proposal treats the initial low unemployment as a new permanent benchmark. Which joint AD-AS/Phillips correction is needed?'
        ans=['Higher wage expectations shift SRAS left and SRPC up; output and unemployment tend toward their unchanged natural benchmarks','Higher expectations shift both SRAS and SRPC right, permanently preserving the demand-driven employment gain','Higher expectations shift LRAS right and LRPC left, so the proposal is correct without real structural change','Expected inflation changes only nominal labels and cannot affect the short-run supply or Phillips relation']
        fb='Higher expected prices incorporated in wages reduce short-run supply at a given actual price; higher expected inflation raises the short-run Phillips relation. Without real structural changes, the initial demand-induced gain does not establish new natural benchmarks.';p=None
    else:
        stem=f'A program intended to close a ${2*a} demand gap arrives after recovery. At arrival, a separate adverse supply shock raises inflation. Which policy evaluation recognizes why the original direction need not remain appropriate?'
        ans=['The demand-gap rationale is stale, and extra demand now faces a worse supply tradeoff; timing and shock diagnosis both need reassessment','The original recession diagnosis guarantees expansion lowers inflation even after the shock changes','The supply shock guarantees contraction immediately restores output without a price-output tradeoff','The program\'s delay changes only accounting labels, not its effect relative to current capacity']
        fb='A rule based on an earlier demand shortfall is not a complete assessment after recovery and a new supply shock. The action can add inflation pressure at a changed starting point; reassess both current utilization and the source of inflation.';p=None
    emit(id,stem,ans,fb,tier='legendary' if mode in (4,5,6,8,9,10,11) else 'elite',error='Stops at one macro channel and ignores the specified second mechanism, timing condition or changed benchmark.',proof=p,operation='integration')

emit('PMOE-NCO-B3-001',
 'A country reports NCO = −$120 billion and resident purchases of foreign assets of $200 billion. A second ledger reports foreign purchases of domestic assets of $300 billion. Keeping the first two figures fixed, what correction and trade-balance implication follow under NX=NCO?',
 ['Foreign purchases must be $320 billion; NX is −$120 billion, a trade deficit','Foreign purchases must be $80 billion; NX is +$120 billion, a trade surplus','Foreign purchases remain $300 billion; NX must be −$100 billion despite the fixed NCO figure','Foreign purchases must be $320 billion; NX is +$120 billion because a capital inflow is an export'],
 'NCO = resident foreign purchases − foreign domestic purchases. Thus −120=200−F implies F=320. With NX=NCO, NX=−120; the inflow finances a trade deficit rather than changing its sign.',error='Reverses the gross-flow subtraction or the NX=NCO sign.',proof=proof(('200-(-120)',320)))
emit('PMOE-NER-B3-002',
 'The quotation rises from 1.60 to 1.84 foreign units per domestic unit. A domestic exporter keeps its domestic-currency price fixed. Which percentage comparison and foreign-buyer consequence are correct?',
 ['Domestic currency appreciates 15%; its reciprocal foreign-currency value falls about 13.0%, and the exporter\'s foreign price rises 15%','Domestic currency appreciates 15%; the reciprocal falls exactly 15%, and the foreign export price falls 15%','Domestic currency depreciates about 13.0%; the reciprocal rises 15%, and the foreign export price falls 13.0%','Domestic currency appreciates about 13.0%; the reciprocal falls 15%, and the foreign export price is unchanged'],
 'The quoted rate rises1.84/1.60−1=15%. The reciprocal changes1.60/1.84−1≈−13.04%. A fixed domestic price costs foreign buyers proportionately more when multiplied by the higher foreign-per-domestic rate.',error='Assumes a reciprocal percentage change has the same magnitude or reverses the buyer-price consequence.',proof=proof(('(1.84/1.6-1)*100',15),('(1.6/1.84-1)*100',-13.04347826)))
emit('PMOE-RER-B3-001',
 'Quote e as foreign units per domestic unit and define the real rate ε=eP/P*. The nominal rate falls4%, domestic inflation is7%, and foreign inflation2%. A report calls the nominal depreciation proof of improved price competitiveness. Using the growth-rate approximation, which correction follows?',
 ['The real rate rises about1%; domestic goods become relatively dearer despite nominal depreciation','The real rate falls about1%; every nominal depreciation guarantees improved competitiveness','The real rate falls about9%; subtract domestic inflation rather than add it','The real rate rises about13%; add every rate change regardless of quotation'],
 'Approximate real-rate growth is −4+7−2=+1%. Under this quotation an increased real rate makes domestic goods relatively dearer. Nominal depreciation is outweighed by domestic inflation relative to foreign inflation.',error='Uses nominal depreciation alone to sign the real exchange-rate change.',proof=proof(('-4+7-2',1)))
emit('PMOE-TX-B3-001',
 'Private saving rises$40 billion, public saving falls$15 billion, and domestic investment rises$10 billion. A trade ledger reports exports up$20 billion and imports up$10 billion. Under S−I=NX, with no statistical discrepancy and all saving/investment figures held fixed, which correction reconciles the ledgers?',
 ['NX must rise$15 billion; with exports up$20 billion, imports must rise$5 billion','NX must rise$10 billion; revise saving down$5 billion despite the instruction to hold it fixed','NX must rise$35 billion; with exports up$20 billion, imports must fall$15 billion','NX must fall$15 billion; with exports up$20 billion, imports must rise$35 billion'],
 'National saving rises40−15=25; subtract investment growth10 to obtain NX growth15. Since ΔNX=ΔX−ΔM, 15=20−ΔM implies imports rise5. The original trade ledger\'s10-point NX increase fails the identity under the stated constraints.',error='Does not reconcile saving-investment and trade ledgers using the same net balance.',proof=proof(('40-15-10',15),('20-(40-15-10)',5)))
save()
