from checkpoint_support import *

for concept in ['unemployment-measurement','unemployment-types','natural-rate-of-unemployment','labor-market-institutions']:
 for j,id in enumerate(candidates(concept)):
    n=100+10*j;mode=j%5
    if concept=='unemployment-measurement':
      cases=[
       (f'In an adult population of {2*n}, employment is {n} and active-search unemployment is {n//10}. A survey also finds {n//10} people who want work but have stopped searching. Which correction to a report counting all jobless people as unemployed is needed?',
        [f'Exclude discouraged workers from unemployment and the labor force; UR is about 9.1% and LFPR is 55%',f'Include discouraged workers in unemployment; UR is about 16.7% and LFPR is 60%',f'Include discouraged workers only in the labor force; UR is about 8.3% and LFPR is 60%',f'Exclude discouraged workers but divide unemployment by adult population; UR is 5% and LFPR is 50%'],
        f'The labor force is {n}+{n//10} = {1.1*n:g}. The discouraged are not active searchers. UR = 0.1/1.1 ≈ 9.1%; LFPR = 1.1/2 = 55%.',proof(('.1/1.1*100',9.09090909),('1.1/2*100',55))),
       (f'Employment is {n} and unemployment is {n//10}. Then {n//20} previously inactive adults begin actively searching; nobody finds or loses a job. Which interpretation reconciles the rate change with employment?',
        ['Employment is unchanged while unemployment and participation rise; the rate increase does not show job destruction','Employment falls while unemployment rises; every new searcher must have left a job','Employment rises and unemployment falls; entering the labor force counts as finding work','Employment is unchanged and both rates are unchanged; inactive adults cannot affect the denominator'],
        'Active searchers without jobs enter both unemployment and the labor force. Employment is unchanged; unemployment rises relative to the larger labor force, and participation rises. A higher unemployment rate need not mean jobs were lost.',None),
       (f'An economy has {n} employed and {n//10} unemployed adults. Two separate policy evaluations observe the same fall in unemployed people. In A, they find jobs; in B, they stop searching. With adult population fixed, which extra indicator distinguishes the cases?',
        ['Employment rises with unchanged participation in A; employment is unchanged and participation falls in B','Employment is unchanged and participation falls in A; employment rises with unchanged participation in B','Employment and participation rise in both because measured unemployment falls','Employment and participation fall in both because fewer people are unemployed'],
        'Job finding moves people within the labor force from unemployed to employed. Discouragement moves people out of unemployment and the labor force without raising employment. The same unemployment change can conceal different labor outcomes.',None),
       (f'Of {n} employed workers, ten full-time workers lose half their hours but retain paid jobs. No one enters or leaves the labor force. Which observation would reveal the deterioration that the official unemployment rate misses?',
        ['Total hours or involuntary part-time work changes while unemployment and participation can remain unchanged','The unemployment rate must rise because any lost hour makes a worker unemployed','Participation must fall because part-time workers are outside the labor force','Employment must fall by five people because two half-time workers count as one employed person'],
        'A paid part-time worker is employed. Head-count employment, UR and LFPR can stay constant while hours and underemployment worsen; hours-based evidence supplies the missing margin.',None),
       (f'Initially {n} adults are employed and {n//10} unemployed. A recession causes {n//20} employed workers to lose jobs and actively search, while an equal number of previously unemployed people stop searching. Which joint result can occur?',
        ['Employment and labor-force participation fall; unemployment head count stays fixed and its rate rises','Employment falls but participation is fixed; unemployment head count doubles','Employment is fixed because layoffs and exits cancel; the unemployment rate is fixed','Employment falls and unemployment head count falls; the unemployment rate necessarily falls'],
        'Layoffs move employed people to unemployment; discouraged exits remove an equal number from unemployment. U is unchanged, E and the labor force fall, so U/LF rises. Equal flows do not cancel employment or participation effects.',None)]
    elif concept=='unemployment-types':
      cases=[
       (f'A regional study follows {n} jobless workers after national demand recovers. Former miners still lack skills for local health-care vacancies, while new graduates are interviewing for matching jobs. Which diagnosis and response pair is appropriate?',
        ['Miners face structural mismatch suited to retraining; graduates face frictional search suited to matching assistance','Miners face cyclical unemployment suited only to demand stimulus; graduates face structural unemployment suited to changing industries','Both groups face cyclical unemployment because neither is currently employed','Both groups face structural unemployment because job search always requires new skills'],
        'The persistence of a skill mismatch after demand recovers identifies a structural problem. Graduates searching for suitable existing matches illustrate frictional unemployment. Each remedy should address its actual mechanism.',None),
       (f'A recession idles {n} workers in otherwise viable firms. A separate group loses jobs permanently to automation and lacks the skills sought by expanding firms. Which policy comparison recognizes the two causes?',
        ['Demand recovery can restore recession jobs; retraining may still be needed for the automation-displaced group','Demand recovery necessarily restores both groups to their original jobs without adjustment','Retraining alone restores demand for the recession firms\' unchanged products','Both groups are outside the labor force until a firm makes an offer'],
        'Weak aggregate demand creates cyclical unemployment; a changed pattern of skill demand creates structural unemployment. Recovery need not reverse a permanent mismatch.',None),
       (f'Job vacancies and active job seekers both remain high in a region with {n} displaced workers, even after aggregate sales return to normal. Which added evidence best distinguishes persistent mismatch from ordinary search?',
        ['Whether the workers\' skills and locations fit the available vacancies','Whether job seekers want higher real incomes than before','Whether every unemployed worker has zero current earnings','Whether the statistical agency counts the employed in the labor force'],
        'Vacancies alongside unemployment can reflect search or mismatch. Evidence about skill/location fit addresses that distinction; the other facts do not identify its source.',None),
       (f'A matching service shortens unemployment spells among {n} otherwise qualified job seekers. At the same time, an industry closes permanently and displaced workers need new qualifications. Which conclusion is defensible?',
        ['Frictional unemployment can fall while structural unemployment rises; the net natural-rate effect needs magnitudes','Both changes reduce frictional unemployment, so the natural rate must fall','The matching service changes cyclical unemployment and the closure changes only measured participation','Structural unemployment disappears whenever search becomes faster, so the closure cannot raise it'],
        'Better matching reduces search friction, while a durable skills mismatch raises structural unemployment. Natural unemployment includes both, so opposing changes do not determine the net effect.',None),
       (f'A worker leaves a job voluntarily to search for a better match, one is laid off during falling economy-wide sales, and another cannot qualify for new vacancies after a permanent technology change. In a study of {n} similar cases, which full classification should be used?',
        ['Frictional; cyclical; structural','Structural; frictional; cyclical','Cyclical; structural; frictional','Frictional; structural; cyclical'],
        'The first is normal matching/search; the second reflects weak aggregate demand; the third reflects a lasting mismatch. Being unemployed alone does not identify the mechanism.',None)]
    elif concept=='natural-rate-of-unemployment':
      cases=[
       (f'Actual unemployment in an economy of {n} workers is 8%. An estimate puts frictional unemployment at 2% and structural unemployment at 3%. Which decomposition and policy limit are consistent?',
        ['Natural unemployment is 5% and cyclical unemployment 3 points; removing weak demand need not remove the remaining 5%','Natural unemployment is 8% and cyclical unemployment zero; every observed rate is the natural rate','Natural unemployment is 3% and cyclical unemployment 5 points; frictional search is excluded','Natural unemployment is zero and cyclical unemployment 8 points; full employment requires everyone to have a job'],
        'The natural benchmark is frictional plus structural: 2+3=5%. Actual minus natural is 8−5=3 points. Eliminating the cyclical gap does not eliminate matching or structural unemployment.',proof(('2+3',5),('8-(2+3)',3))),
       (f'A recovery reduces actual unemployment among {n} workers while job-matching institutions and skill mismatch are unchanged. An analyst says the natural rate must have fallen by the same amount. Which evidence corrects the inference?',
        ['The cyclical gap may shrink with an unchanged natural rate; changes in frictional/structural conditions are separate evidence','Any fall in actual unemployment mechanically lowers the natural rate, regardless of institutions','The natural rate rises whenever actual unemployment falls because the two rates sum to a constant','The natural rate equals zero once a recession ends, regardless of persistent job search'],
        'Actual unemployment reflects both the natural benchmark and cyclical conditions. Recovery can reduce the latter without changing the former.',None),
       (f'A reform improves matching for {n} job seekers but rapid technology change creates new skill mismatches. What can be inferred about the natural rate before their magnitudes are known?',
        ['Better matching lowers its frictional component while mismatch raises its structural component; net change is uncertain','Both changes lower the natural rate because all technology improves job matching','Only actual unemployment can change; the natural benchmark is fixed by definition','The natural rate must rise because structural changes always dominate frictional changes'],
        'The natural rate is not immutable. It combines frictional and structural components, and opposing component changes require magnitudes to sign their sum.',None),
       (f'Actual unemployment is 4% and the estimated natural rate is 5% in a labor market with {n} workers. Expected inflation has not yet adapted. Which interpretation and longer-run caution follow?',
        ['A temporary negative cyclical gap is possible; it does not establish a permanently lower natural rate','The data are impossible because actual unemployment can never fall below its natural rate','The natural rate must immediately become 4% because it is defined as actual unemployment','Unemployment must become zero as expectations adjust because the gap is negative'],
        'Actual unemployment can temporarily be below the natural benchmark during strong demand. Expectations and wages can adjust; without changed labor-market structure, that does not prove a lower natural rate.',None),
       (f'In a workforce of {n}, retraining reduces structural unemployment while a recession increases cyclical unemployment. The measured rate is unchanged. Which inference is valid?',
        ['The natural rate can fall even with unchanged actual unemployment because the cyclical gap increased','The natural rate is unchanged because every structural change must appear in the measured rate','The natural rate rises because a recession changes only structural unemployment','Retraining had no effect because actual unemployment did not fall'],
        'Actual unemployment can be unchanged when a lower structural/natural component is offset by a larger cyclical gap. An unchanged total does not prove unchanged components.',None)]
    else:
      cases=[
       (f'A binding wage floor raises pay for retained workers in a competitive labor market, but firms offer fewer jobs and {n} people seek work at the higher wage. Which evaluation addresses both margins?',
        ['Retained workers can gain wage income while some willing workers face rationed jobs; total earnings need quantities','All workers necessarily gain equal income because the legal wage is higher','All workers necessarily lose income because employment falls','The higher wage proves labor demand shifted right, so rationing cannot occur'],
        'A binding floor changes the wage paid and the quantity employed along demand. Winners among retained workers do not establish an aggregate earnings gain; employment quantities matter.',None),
       (f'A firm voluntarily pays above the market wage to reduce turnover and improve effort among {n} workers. Which comparison distinguishes an efficiency wage from a union-negotiated wage without denying either employment tradeoff?',
        ['The firm chooses a wage to improve productivity/retention; a union bargains for members, and either can sustain an above-clearing wage','The union must have imposed the voluntary wage; above-market pay cannot benefit a firm','The wage is a government price ceiling; it increases labor demand by legal requirement','Efficiency wages lower pay below equilibrium; union wages raise it above equilibrium'],
        'Efficiency wages arise from employer incentives such as effort and turnover; union wages arise from bargaining. They differ in mechanism even if both can leave job seekers unmatched at the wage.',None),
       (f'A benefit reform gives {n} unemployed workers more time to search for good matches. Search duration rises, while later job retention also improves. Which policy assessment recognizes the tradeoff?',
        ['Longer search can raise frictional unemployment while better matches improve retention; the net welfare effect needs both margins','Longer search proves the reform reduced job-match quality despite better observed retention','Better retention proves the reform eliminated every increase in search unemployment','Both observations imply cyclical unemployment rose because matching institutions affect only demand'],
        'Search incentives and match quality can move in opposite evaluative directions. A longer spell need not mean the eventual match is worse; welfare assessment needs both costs and benefits.',None),
       (f'Job-search assistance speeds matching for {n} applicants, while reduced search pressure permits others to wait longer for suitable offers. Which unemployment prediction requires more evidence?',
        ['The net frictional-unemployment change, because faster matching and longer chosen searches oppose','Whether either channel concerns frictional unemployment; all search is structural by definition','Whether faster matching reduces a spell, because matching can affect only wages','Whether weaker search pressure raises the natural rate permanently regardless of matching gains'],
        'Faster matching shortens spells; waiting longer can lengthen them. Both involve the search component, so relative magnitudes are needed for the net rate.',None),
       (f'Above-market wages improve effort among {n} retained employees. A proposal predicts that productivity gains must exactly offset reduced hiring. Which missing comparison is essential?',
        ['The size of the productivity/turnover benefit relative to the higher labor cost and hiring response','Whether retained employees are classified as unemployed when the wage is above equilibrium','Whether the statutory unemployment denominator should exclude workers receiving higher wages','Whether every firm uses identical technology, which alone guarantees an exact offset'],
        'The efficiency mechanism can benefit the employer, but it does not algebraically guarantee a particular employment or cost offset. Relative magnitudes determine the net result.',None)]
    stem,answers,feedback,p=cases[mode]
    emit(id,stem,answers,feedback,tier='elite' if mode in (2,3,4) else 'hard',error='Infers the total labor-market outcome from one component while ignoring the specified second margin.',proof=p)

for concept in ['productivity-measurement','living-standards-and-growth','sources-of-productivity','economic-growth-policy']:
 for j,id in enumerate(candidates(concept)):
    x=100+10*j;mode=j%5
    if concept=='productivity-measurement':
      cases=[
       (f'A plant initially produces {10*x} units in {x} labor hours. Output later rises 20% while hours rise 25%. Which finding corrects the manager\'s claim that output growth proves higher labor productivity?',
        ['Total output rises, but output per hour falls 4%','Both total output and output per hour rise 20%','Output per hour rises 5% because hours grow faster than output','Output per hour falls 25% because the output increase is irrelevant'],
        'Productivity is output/hours. Its change factor is 1.20/1.25 = 0.96, a 4% decline despite more output.',proof(('1.2/1.25-1',-.04))),
       (f'A firm produces {10*x} units at 10 units per labor hour. After training, productivity is 12 units per hour and required output rises to {12*x}. Which conclusion follows about labor hours and its limit?',
        [f'Hours remain {x}; higher output exactly matches the proportional productivity gain',f'Hours rise to {1.2*x:g}; output growth alone sets required hours',f'Hours fall to {x/1.2:.1f}; apply the productivity gain but ignore higher required output',f'Hours are zero; higher productivity replaces all labor'],
        f'Initial hours = {10*x}/10 = {x}; new hours = {12*x}/12 = {x}. Productivity gains do not necessarily reduce total hours when output demand changes too.',proof((f'{12*x}/12',x))),
       (f'Two plants produce the same {10*x} units. Plant A uses {x} hours and B uses {2*x} hours. B then cuts hours by 40% without changing output. Which comparison is correct?',
        ['B\'s productivity rises about 66.7%, but remains below A\'s 10 units per hour','B\'s productivity rises 40% and equals A\'s productivity','B\'s productivity falls 40% because fewer hours imply fewer units per hour','B\'s productivity doubles and exceeds A\'s productivity'],
        'B initially produces 5 units/hour; after hours fall to 60%, productivity is 5/0.6≈8.33, a 66.7% gain but still below A\'s 10.',proof(('5/.6',8.333333333),('(1/.6-1)*100',66.66666667))),
       (f'An economy has {x} workers. Output per hour rises 5%, average hours per worker falls 5%, and employment is unchanged. Which distinction matters for total output?',
        ['Hourly productivity rises, but output falls slightly because 1.05×0.95 is below one','Output rises exactly 5% because productivity alone determines total output','Output is exactly unchanged because opposite percentage changes cancel','Hourly productivity falls because workers supply fewer hours'],
        'Total output is output/hour × hours/worker × workers. The change factor is 1.05×0.95 = 0.9975, a 0.25% decline. Equal opposite percentages do not cancel multiplicatively.',proof(('(1.05*.95-1)*100',-.25))),
       (f'Output per worker rises in a firm with {x} employees, but average hours per worker also rises. Which additional evidence is needed to infer output-per-hour growth?',
        ['Compare the percentage output-per-worker change with the percentage hours-per-worker change','Compare only employee head count; longer hours never affect hourly productivity','Observe that nominal wages rose; that establishes output per hour rose','Observe that total output rose; that establishes output per hour rose'],
        'Output/hour equals output/worker divided by hours/worker. A higher per-worker figure can come from longer work rather than greater hourly efficiency.',None)]
    elif concept=='living-standards-and-growth':
      cases=[
       (f'Real GDP is initially ${x} billion. It grows 6%, while population grows 8%. Which statement reconciles aggregate growth and average output?',
        ['Aggregate real output rises, but real GDP per person falls about 1.9%','Both aggregate and per-person real output rise 6%','Per-person output rises 14% because output and population growth add','Aggregate output falls because population growth exceeds GDP growth'],
        'Per-person output changes by 1.06/1.08−1≈−1.85%. A larger economy can have lower average output if population grows faster.',proof(('(1.06/1.08-1)*100',-1.851851852))),
       (f'Country A begins at ${40000+x} real GDP per person and grows 2% annually; B begins at half that level and grows 7%. Using the Rule of 70, which warning corrects the claim that B catches A in ten years?',
        ['B doubles its starting level in about ten years, but A also grows, so doubling alone does not establish catch-up','B doubles in about thirty-five years, while A doubles in ten, so catch-up is immediate','A\'s higher initial level means its percentage growth must exceed B\'s','The Rule of 70 implies A stops growing when B starts doubling'],
        '70/7≈10 years doubles B\'s starting level; 70/2≈35 years doubles A\'s. A is a moving target, so B reaching A\'s initial level is not the same as reaching A\'s contemporaneous level.',proof(('70/7',10),('70/2',35))),
       (f'Two countries each report ${x} billion GDP. One has twice the population and a 20% higher price level. The GDP figures are nominal. Which comparison is justified before a living-standard ranking?',
        ['Adjust for prices and population; equal nominal totals do not imply equal real output per person','Adjust only for population; price differences cannot affect nominal comparisons','Adjust only for prices; population cannot affect per-person output','Use equal totals as proof of equal average living standards'],
        'A nominal aggregate combines scale and prices. A per-person real comparison must remove both; even real GDP per person remains incomplete welfare evidence.',None),
       (f'Real GDP per person rises from ${x} to ${1.1*x:g}, but gains accrue mainly to a small group. Which inference distinguishes an average from individual outcomes?',
        ['Average real output rises 10%; the typical person\'s gain requires distributional evidence','Every person\'s real income rises 10% because the average rises 10%','No real output grew because not everyone gained equally','Average real output falls if the largest gains go to high-income people'],
        'The aggregate per-capita ratio rises 10%, but that does not identify every person\'s income or the median. Distribution is additional evidence, not part of the arithmetic average.',proof(('(1.1-1)*100',10))),
       (f'A country with initial real GDP per person ${x} sustains 4% growth instead of 2%. Another policy raises the level once by 4% but leaves later growth at 2%. Which comparison recognizes the long-run distinction?',
        ['The sustained growth change compounds each year; the one-time level gain does not by itself change later doubling time','Both policies create identical future paths because each mentions a 4% change','The one-time gain permanently doubles the growth rate by arithmetic identity','The sustained change affects only the initial level and cannot compound'],
        'A growth-rate change repeatedly changes the path, whereas a one-time level gain shifts the starting point. Under Rule of 70, sustained 4% growth implies roughly 17.5-year doubling versus 35 at 2%.',proof(('70/4',17.5),('70/2',35)))]
    elif concept=='sources-of-productivity':
      cases=[
       (f'A factory with {x} workers buys more machines, while another trains workers to maintain its existing machines. Which distinction and implication are sound?',
        ['The first adds physical capital and the second human capital; either can raise output per worker without increasing worker count','Both add physical capital because all productivity improvements are machines','The first adds human capital and the second physical capital; their labels depend on who pays','Training changes only labor quantity and cannot improve output per worker'],
        'Equipment is physical capital; skills are human capital. Both can raise productive ability per worker, though their returns and implementation differ.',None),
       (f'A fixed technology gives an extra {x} units of output from the first additional machine and only {x//2} from the second. A proposal assumes each later machine adds the first machine\'s amount. What is the flaw?',
        ['It ignores diminishing marginal returns; output can still rise while each added machine contributes less','It confuses diminishing returns with falling total output; the second machine necessarily destroys output','It assumes a fixed workforce; adding capital always requires fewer workers by definition','It ignores that capital accumulation automatically raises the technology growth rate permanently'],
        'With other inputs and technology fixed, added capital can increase total output at a decreasing rate. A smaller positive increment is not a fall in total output.',None),
       (f'Two economies each employ {x} workers. One has little capital per worker and the other much more, with similar technology and institutions. Which qualification should accompany a catch-up prediction?',
        ['The capital-poor economy may earn higher marginal returns, but investment and effective use of capital are still required','The capital-poor economy must grow faster regardless of investment, institutions or technology access','The capital-rich economy must have higher percentage growth because its output level is higher','Equal worker counts require equal output per worker regardless of capital'],
        'Diminishing returns can create catch-up potential when conditions are comparable. Potential is not an automatic growth guarantee without investment and productive use.',None),
       (f'A discovery increases available mineral resources for {x} workers, but extraction technology and transport remain inadequate. Which policy diagnosis best connects resources to productivity?',
        ['The resource expands potential opportunities, but complementary technology/infrastructure can be the binding constraint','The resource alone guarantees an immediate proportional increase in output per worker','Transport affects consumption only and cannot limit production from resources','Resource abundance makes worker skills and institutions irrelevant to long-run output'],
        'Natural resources can support production, but usable technology, skills and infrastructure determine whether they can be exploited productively. More resources alone need not raise current output.',None),
       (f'A new production method lets the same {x} workers and machines produce more output. A capital-only explanation predicts no gain because the machine stock did not rise. Which correction is right?',
        ['Technological knowledge raises productivity with existing inputs; it differs from simply accumulating more machines','The gain must be more labor because technology is not an input to productive capacity','The machine stock must have risen by the same percentage as output by accounting identity','The gain can only be higher prices because unchanged machines imply unchanged real output'],
        'Better methods change what existing inputs can produce. Physical-capital accumulation and technological knowledge are distinct channels, and either can affect productivity.',None)]
    else:
      cases=[
       (f'A country with {x} workers has idle capacity after a recession and weak long-run research incentives. Which policy pairing addresses the two different problems?',
        ['Demand stabilization can use idle capacity; stronger research incentives can improve future productive capacity','Demand stabilization permanently raises technology by the same amount as spending, making research incentives unnecessary','Research incentives instantly eliminate every current demand shortfall without a timing lag','Both problems require only more nominal money because all real output is money-determined'],
        'Closing a demand gap and shifting the long-run productive frontier are different objectives. Research has a capacity channel and timing; a temporary demand boost is not a substitute for it.',None),
       (f'Firms serving {x} workers underinvest in training because employees may leave with their new skills. Which proposal targets that mechanism while recognizing a resource tradeoff?',
        ['Co-finance transferable training where spillovers justify it, while evaluating its cost against other uses','Increase current consumption subsidies and assume human capital rises automatically','Protect existing jobs from every technology change and assume learning accelerates','Mandate a higher nominal GDP target and infer that skills must improve'],
        'Training can create spillovers that private firms do not fully capture. Co-financing may address that incentive, but training uses resources and its social return must justify the cost.',None),
       (f'An economy with {x} workers raises saving to finance new capital but temporarily consumes less. Under diminishing returns with unchanged technology, which comparison is defensible?',
        ['Future output per worker may rise, while current consumption falls; capital deepening alone need not permanently raise its growth rate','Current consumption and future output both necessarily rise immediately because saving uses no resources','Higher saving permanently raises growth at an unchanged rate for every additional machine','Diminishing returns mean any new capital must reduce future output'],
        'Saving reallocates resources from present consumption toward investment. Capital deepening can raise the level of output per worker, with diminishing increments absent continuing technological progress.',None),
       (f'A region of {x} workers has reliable electricity but weak contract enforcement and frequent asset seizure. Which growth policy most directly addresses the stated binding constraint?',
        ['Strengthen predictable property/contract enforcement to improve investment incentives, while retaining useful infrastructure','Build identical spare power plants and infer that institutional risk has disappeared','Increase nominal wages by decree and infer a matching increase in labor productivity','Restrict all new firms to preserve incumbent returns and infer faster innovation'],
        'The stated constraint is insecurity of returns, not an electricity shortage. Predictable institutions can encourage investment and exchange; nominal changes alone do not establish real productivity gains.',None),
       (f'A technology policy raises potential output for {x} workers but displaces some workers whose skills no longer match vacancies. Which package recognizes both the growth benefit and transition cost?',
        ['Support productive innovation and targeted retraining; higher potential output does not instantly rematch displaced workers','Stop measuring displaced workers so productivity and employment both improve by definition','Use only demand stimulus and assume it reverses every permanent skill change','Block every productivity improvement because any displacement proves long-run output must fall'],
        'Innovation can expand productive capacity while creating structural transition costs. Retraining/mobility address the mismatch; aggregate growth alone does not guarantee immediate employment for each displaced worker.',None)]
    stem,ans,fb,p=cases[mode]
    emit(id,stem,ans,fb,tier='elite' if mode in (1,3,4) else 'hard',error='Infers productivity, growth or welfare from a single aggregate while ignoring the stated comparison or constraint.',proof=p)
save()
