from checkpoint_support import *

def graph(id, stem, options, feedback, tier='hard', p=None):
    task(id,stem,options,feedback,'analysis',proof=p,keep_image=True)
    patch(id,canonicalDifficulty=tier,difficulty=tier)

graph('ECON-SP-FINALBOSS-4006',
 'In the AD-AS graph, demand expands from AD1-AS2 to AD2-AS2. An analyst calls Y2 the new potential output. Which evidence corrects the claim and predicts adjustment if demand then stays fixed?',
 ['LRAS remains at Y1; rising wage expectations shift AS2 toward AS1, returning output to Y1 at a higher price level','LRAS moves to Y2; falling wage expectations shift AS2 toward AS1 and preserve output at Y2','LRAS remains at Y1; wage adjustment shifts AD2 back to AD1 and restores the original price level','LRAS moves to Y3; rising wage expectations shift AS1 toward AS2 and reduce the price level'],
 'The initial expansion raises actual output to Y2 without moving LRAS. Above-potential activity raises expected prices and nominal costs. With AD2 fixed, AS2 shifts left to AS1, ending at Y1 and P3.', 'elite')
graph('ECON-SP-FINALBOSS-4007',
 'The graph starts at AD2-AS2 after a demand boom. Compare leaving AD2 fixed while wages adjust with immediately returning demand to AD1 before wages adjust. Which endpoints follow, assuming unchanged LRAS?',
 ['Both restore Y1; wage adjustment ends at P3, while immediate demand reversal ends at P1','Both restore Y1; wage adjustment ends at P1, while immediate demand reversal ends at P3','Only wage adjustment restores Y1; demand reversal permanently lowers potential to Y3','Only demand reversal restores Y1; wage adjustment permanently preserves output at Y2'],
 'With fixed AD2, rising expected prices move AS2 to AS1, yielding Y1/P3. Reversing demand while AS2 is unchanged yields AD1-AS2, Y1/P1. Same real endpoint does not imply the same price-level endpoint.','legendary')

pc=[
 ('ECON-SP-FINALBOSS-4009','Starting at c in the LRPC graph, an unexpected demand expansion moves the economy to a. Compare that initial gain with the endpoint if the higher inflation persists and expectations catch up.',
 ['Unemployment first falls to U1, then returns to U2 at b; persistent inflation does not preserve the initial gain','Unemployment first falls to U1, then remains at a; expectations leave the SRPC fixed','Unemployment first rises to U3, then returns to U2 at c; the initial shock is contractionary','Unemployment first falls to U1, then returns to U2 at c while inflation stays at I2'],
 'The surprise is a movement c→a on SRPC1. Higher expected inflation shifts the short-run relation to SRPC2; at unchanged natural unemployment U2 the new endpoint is b.','elite'),
 ('ECON-SP-FINALBOSS-4010','In the LRPC graph, an economy has moved from c to a through a demand surprise. A proposal promises to keep unemployment at U1 with the same inflation I2 indefinitely. What fails as expectations catch up?',
 ['The fixed-inflation promise: expectations shift SRPC upward, so holding U1 requires renewed inflation surprises','The natural-rate assumption: expected inflation alone permanently shifts LRPC left to U1','The initial demand mechanism: moving c to a requires higher unemployment rather than lower','The price adjustment: expectations shift SRPC downward, so holding U1 requires steadily lower inflation'],
 'Once I2 is expected, b rather than a is the natural-rate equilibrium. Repeatedly holding unemployment below U2 requires inflation above the newly adjusted expectation, not simply maintaining the original higher rate.','legendary'),
 ('ECON-SP-FINALBOSS-4012','Starting at b in the LRPC graph, policymakers reduce inflation to I1 before expectations change. Compare the first location with the eventual location if expectations adapt to I1 and the natural rate stays fixed.',
 ['First d, eventually c; the temporary unemployment rise disappears as SRPC shifts down','First c, eventually d; expectations initially change fully and later rise again','First a, eventually b; the policy first raises inflation above expectations','First d, eventually a; lower expected inflation permanently lowers natural unemployment to U1'],
 'At the old expectation, lower inflation moves b→d on SRPC2. As expected inflation falls, SRPC shifts to SRPC1; the endpoint is c at U2.','elite'),
 ('ECON-SP-FINALBOSS-4013','At d in the LRPC graph after disinflation, compare a credible commitment that lowers expected inflation with a loss of credibility that leaves it at the old level. Actual inflation is held at I1. Which comparison follows?',
 ['Credible adjustment permits movement toward c at U2; unchanged expectations leave unemployment at U3 on SRPC2','Credible adjustment moves toward a at U1; unchanged expectations also restore U2 automatically','Credible adjustment raises expected inflation and moves toward b; unchanged expectations move toward c','Both paths immediately reach c because holding actual inflation at I1 by itself shifts expectations'],
 'At I1, the old SRPC2 implies d/U3. Lowering expected inflation shifts the curve down, allowing c/U2 at the same actual inflation. Holding the target is not identical to having the target believed.','legendary'),
 ('ECON-SP-LEGENDARYBOSS-9107','The LRPC graph shows c→a after surprise demand expansion. Compare repeating that surprise to keep U1 with accepting b once I2 is expected. What is the dynamic tradeoff?',
 ['Holding U1 requires renewed surprises as forecasts rise; accepting b stabilizes inflation but restores U2','Holding U1 stabilizes inflation automatically; accepting b permanently reduces natural unemployment','Holding U1 requires falling inflation surprises; accepting b keeps unemployment below natural','Both strategies keep U1 because the original surprise permanently shifts the LRPC'],
 'a is below natural unemployment on the original expectations curve. As forecasts rise, sustaining that unemployment requires inflation above the updated forecasts. Accepting the higher-inflation natural-rate point b ends that repeated-surprise strategy.','legendary'),
 ('ECON-SP-LEGENDARYBOSS-9108','The graph shows disinflation b→d. Suppose a credible announcement immediately lowers expectations, but existing wage contracts adjust only gradually. Which claim about d→c is justified?',
 ['The same U2/I1 endpoint remains possible, but credibility alone does not prove a costless or immediate transition','The endpoint must be U1/I1 because credibility permanently lowers the natural rate','The endpoint remains d because expected inflation cannot affect the short-run curve','The endpoint must be b because sticky contracts prevent any eventual disinflation'],
 'Lower expectations support a downward SRPC shift and eventual c. Existing contracts can delay cost adjustment, leaving a temporary unemployment/output cost; neither a changed natural rate nor zero sacrifice follows from credibility alone.','legendary')]
for i,s,a,f,t in pc:graph(i,s,a,f,t)
graph('ECON-SP-LEGENDARYBOSS-9102','In the AD-AS graph, an adverse supply shock moves AS2 to AS1 from AD1-AS2. Compare keeping AD1 fixed with expanding demand to AD2 while AS1 persists. Which policy claim survives both comparisons?',
 ['Expansion restores Y1 at P3 instead of Y3 at P2, but does not restore the original P1 price level','Expansion restores both Y1 and P1 because any output recovery reverses the supply shock','Keeping AD1 fixed preserves Y1 while expansion creates Y2 at the same P2','Both policies produce Y3 because aggregate demand cannot affect output under unchanged LRAS'],
 'At unchanged demand the supply shock gives AD1-AS1, Y3/P2. Accommodation gives AD2-AS1, Y1/P3. It offsets the output loss through greater demand, paying a further price-level increase rather than undoing the supply constraint.','legendary')
graph('ECON-SP-LEGENDARYBOSS-9103','At AD2-AS2 in the graph, officials describe Y2 as permanent capacity growth. Assume no technology/resource change, fixed AD2 and rising expected prices. Which joint AD-AS/Phillips interpretation corrects them?',
 ['AS shifts left toward AS1 and output returns to Y1; on the Phillips side rising expectations erase the temporary below-natural unemployment gain','LRAS shifts to Y2 and SRPC shifts down; both models make the initial employment gain permanent','AD shifts back to AD1 and LRPC shifts left; both models predict a permanently lower price level','AS shifts right and SRPC shifts down; expected inflation increases productive capacity in both models'],
 'The graph keeps LRAS at Y1. Expected-price/wage adjustment moves AS2 toward AS1 with AD2 fixed. Correspondingly, rising expected inflation shifts SRPC up and unemployment returns to its unchanged natural rate.','legendary')
graph('ECON-SP-LEGENDARYBOSS-9104','At AD1-AS1 in the graph, wage expectations gradually fall while AD1 stays fixed. Officials alternatively propose increasing AD to AD2 before wages adjust. Which comparison distinguishes self-correction from immediate demand support?',
 ['Self-correction reaches Y1/P1; immediate demand support reaches Y1/P3, so equal output recovery need not mean equal price outcomes','Self-correction reaches Y1/P3; demand support reaches Y1/P1, so demand expansion lowers the price level','Both reach Y2/P2 because recovery shifts LRAS to the right','Both remain at Y3/P2 because only a technology change can close a recessionary gap'],
 'Falling wage/price expectations shift AS1 toward AS2: AD1-AS2 is Y1/P1. Before that adjustment, AD2-AS1 is Y1/P3. Both close the gap under the stated alternatives, with different price levels and timing.','legendary')
graph('ECON-SP-LEGENDARYBOSS-9109','In the SRPC graph, compare b→c on SRPC1 with c→f from SRPC1 to SRPC2. A report calls both changes consequences of weaker aggregate demand with unchanged expectations. Which correction is necessary?',
 ['b→c fits weaker demand; c→f raises inflation at unchanged unemployment and requires a shifted short-run relation','Both fit weaker demand because every higher point denotes higher unemployment','Only c→f fits weaker demand; b→c requires a supply shock at fixed unemployment','Neither can reflect demand because demand changes always shift SRPC rather than move along it'],
 'b→c moves right/down along a given expectations curve. c and f share U3 but differ in inflation: that is a shift of the short-run relation, consistent with changed expectations or a supply shock, not the claimed fixed-curve demand movement.','legendary')
graph('ECON-SP-LEGENDARYBOSS-9114','The two-panel graph traces MS1→MS2 in an economy already below potential. Investment falls $40 billion with MPC=0.75. A timely fiscal program adds a total $100 billion to AD after induced effects. What net result and policy limit follow?',
 ['AD still falls $60 billion; the fiscal offset softens but does not reverse the contractionary monetary chain','AD rises $60 billion; any positive fiscal offset reverses the money-market contraction','AD rises $240 billion; multiply the already-total fiscal offset by four again','AD falls $160 billion; a fiscal offset cannot affect the same AD curve'],
 'Monetary contraction reduces investment and AD: −40/(1−.75)=−160. Adding the total fiscal effect100 gives−60. The diagram indicates the monetary channel, while the stated fiscal countershock determines the net result.','elite',proof(('-40/.25+100',-60)))
graph('ECON-SP-LEGENDARYBOSS-9115','In the money-market graph, compare e→d (MD1→MD2 together with MS1→MS2) with g→a (MD1→MD2 together with MS2→MS1). Why can one not infer the same rate response from higher money demand in both cases?',
 ['The first combines opposing rate pressures; the second combines two upward pressures, so supply direction matters','The first combines two upward pressures; the second combines two downward pressures, so demand is irrelevant','Both changes must lower rates because money demand rises','Both changes leave rates unchanged because all simultaneous shifts cancel'],
 'e→d raises both money demand and money supply: their separate rate effects oppose, with this drawing showing r2→r3. g→a raises demand while reducing supply, reinforcing the rate increase r1→r4. The graph-specific net result of opposing shifts is not a universal sign rule.','legendary')

graph('ECON-SP-MEDIUMBOSS-3004','The LRPC graph marks U2 as natural unemployment. A demand boom moves c→a, while a separate reform would reduce structural unemployment. Which change could move the long-run benchmark itself?',
 ['The reform could move LRPC left; c→a alone changes actual unemployment relative to the fixed benchmark','The demand boom moves LRPC left; the reform only changes inflation along it','Both must move LRPC right because lower unemployment requires higher inflation','Neither can move LRPC because the natural rate is fixed by the price level'],
 'Demand surprises move actual unemployment around natural unemployment. A persistent change in structural unemployment can change the natural rate and hence the position of LRPC.')
graph('ECON-SP-MEDIUMBOSS-3007','In the LRPC graph c→a follows a demand surprise. If actual inflation stays at I2, compare full expectation adjustment with no expectation adjustment.',
 ['Full adjustment leads toward b/U2; unchanged expectations keep the economy on SRPC1 at a/U1','Full adjustment leads toward c/U2; unchanged expectations move it to d/U3','Full adjustment leaves it at a/U1; unchanged expectations shift LRPC left','Both lead to b immediately because actual inflation alone determines expected inflation'],
 'At I2, a is on the original SRPC1 and b is on the higher-expectation SRPC2. The unemployment endpoint depends on expectation adjustment, not solely the maintained actual rate.')
graph('ECON-SP-MEDIUMBOSS-3010','Starting at b, a disinflation moves to d in the LRPC graph. A forecast instead predicts c immediately. What extra assumption could justify that forecast?',
 ['Expectations and relevant wages adjust promptly to lower inflation, shifting SRPC down','Expected inflation remains fixed at its old level throughout the contraction','Natural unemployment rises to U3 when aggregate demand falls','Actual inflation falls while expected inflation rises by the same amount'],
 'd is the short-run result with old expectations. Immediate c would require the lower short-run curve to apply immediately, an additional adjustment assumption rather than a result of demand contraction alone.')
graph('LG-Q-9138','The two-panel graph shows a rate change and an investment-led AD change following a money-supply shift. Now suppose rates still respond but firms no longer change investment. Which stage fails, and does the original graph demonstrate a liquidity trap?',
 ['The rate-to-investment link fails; the original responsive money-demand graph does not demonstrate a liquidity trap','The supply-to-rate link fails; the original graph already shows a flat zero-rate money-demand segment','The reserve-accounting identity fails; the original graph proves deposits cannot change','The AD-to-price link fails; the original graph proves all prices remain fixed'],
 'Separate supply→interest from interest→investment. The counterfactual leaves the first working but removes the second. The original graph has responsive interest rates and is not the flat near-zero-rate case usually used to illustrate a liquidity trap.','elite')
graph('LG-Q-9142','Use the multiplier graph to distinguish the first AD shift from the induced shift. A $60 billion tax cut has MPC=.75; an alternative purchases increase is $45 billion. With the same multiplier and no crowding out, which comparison is correct?',
 ['Both first-round impulses are $45 billion and total shifts $180 billion, although the budget costs differ','The tax cut first adds $60 billion and ultimately $240 billion, while purchases add only $180 billion','Both first-round impulses are $60 billion and total shifts $240 billion, because taxes and purchases are identical','The tax cut adds only $45 billion in total, while purchases receive induced spending'],
 'Tax-induced first-round consumption=.75×60=45; direct purchases also add45. The spending multiplier is4, so both total180. Equal demand impulses do not mean equal changes in the government budget.','elite',proof(('.75*60',45),('45/(1-.75)',180)))

growth=[
 ('PM2B3-PROD-EB-002','In GROWTH-01, A has output per worker about28.53 and B about36.37. If employment is identical, a report says doubling capital per worker from20 to40 doubles total output. Which correction uses both the graph and the fixed-employment condition?',
 ['Output rises about27.5%, not100%; fixed employment makes total output grow by that same percentage','Output rises100%; doubling capital always doubles output even on a flattening curve','Output rises about7.84%; subtracting productivity levels directly gives a percentage','Output falls about21.6%; use the higher productivity as the initial value'],
 'With identical employment, total-output growth equals output-per-worker growth: (36.37/28.53−1)×100≈27.5%. The flattening curve does not support proportional doubling.','hard'),
 ('PM2B3-PROD-LB-002','The GROWTH-01 curve shows productivity rising from A to B. Employment could rise or fall during that move. Which part of a claim that both productivity and total output must rise is established by the graph alone?',
 ['Productivity rises; total output also depends on employment, so a sufficiently large employment fall can offset it','Both must rise; an increase in output per worker rules out falling total output','Only total output rises; the graph measures aggregate output rather than output per worker','Neither can rise; diminishing returns mean each extra unit of capital reduces output'],
 'Output per worker rises from28.53 to36.37, but total output is productivity×workers. A workforce ratio below28.53/36.37≈.7844 would more than offset that gain. Diminishing positive returns do not mean falling productivity.','elite'),
 ('PM2B3-SRC-EB-002','GROWTH-01 is steeper near A than B. Compare an equal small addition to capital per worker at each point, holding technology and other inputs per worker fixed. Which forecast is supported?',
 ['A larger productivity gain near A, but positive gains at both points','Equal productivity gains at both points because capital additions are equal','A larger gain near B because its initial productivity is higher','A gain near A and a loss near B because diminishing returns turn output negative'],
 'The slope measures the marginal productivity effect of capital deepening. The curve is positive but flatter near B: the marginal gain is smaller, not negative.','hard'),
 ('PM2B3-SRC-FB-004','In GROWTH-01, capital deepening takes the economy A→B on one curve. A later observation lies above that curve at the same capital per worker as B. Which explanation distinguishes the two changes?',
 ['A→B is capital deepening; the later gain requires another productive factor or technology to improve','Both are movements along the same curve caused only by more capital per worker','A→B is a technology shift; the later gain is diminishing returns to unchanged capital','Both show falling marginal productivity means falling total productivity'],
 'Moving along the curve changes capital with the other determinants held fixed. Higher output at the same capital requires a changed productive condition, such as technology or human capital.','elite'),
 ('PM2B3-POL-FB-006','The graph suggests high marginal returns near A, but a country at A has unreliable contract enforcement that deters investment. Compare subsidizing machines alone with improving enforcement plus investment. Which inference respects the difference between potential and realized catch-up?',
 ['The combined policy addresses the constraint on realizing high returns; curve shape alone does not guarantee investment occurs','Machine subsidies alone guarantee catch-up regardless of whether investors can retain returns','Enforcement alone mechanically moves the country to B without any change in investment or production','The flatness near B proves institutions cannot influence investment decisions near A'],
 'The curve describes productive potential under maintained conditions. Weak enforcement can stop capital accumulation despite high physical returns. Addressing incentives complements capital deepening; it does not mechanically manufacture the required capital.','elite'),
 ('PM2B3-POL-LB-001','GROWTH-01 suggests catch-up through A→B. A planner proposes ever larger capital investment to maintain the initial growth rate indefinitely, with technology and all other productivity determinants fixed. Which alternative distinguishes a higher level from sustained growth?',
 ['Capital deepening raises the level with diminishing gains; sustained productivity growth requires continuing improvements beyond capital alone','Capital deepening preserves the initial marginal return indefinitely; research would only change nominal output','Diminishing returns imply no gain from A→B, so reducing capital is the growth strategy','Reaching B guarantees permanent growth even if all productive inputs and technology then stop changing'],
 'Diminishing returns make successive capital additions less productive. A finite catch-up level gain is not a permanent growth mechanism. Continuing technology/human-capital improvements can change the productive relation instead of relying only on movement along it.','legendary')]
for i,s,a,f,t in growth:graph(i,s,a,f,t)
PROOFS['PM2B3-PROD-EB-002']=proof(('(36.37/28.53-1)*100',27.479845776))
PROOFS['PM2B3-PROD-LB-002']=proof(('28.53/36.37',.78443772))
graph('PM2C3-LPMM-LB-001','With MD2 and MS2, point b is above equilibrium d. Compare the initial asset-market adjustment with a counterfactual central-bank sale that reduces supply to MS1 before rates adjust. Which two conclusions follow?',
 ['Initially excess money prompts bond purchases and lower rates; the sale makes a the new equilibrium at the original higher rate','Initially excess money prompts bond sales and higher rates; the sale makes g the new equilibrium at a lower rate','Initially a money shortage prompts bond sales and higher rates; the sale makes e the new equilibrium on MD1','Initially a money shortage prompts bond purchases and lower rates; the sale leaves d unchanged'],
 'At b under MS2/MD2, money supplied exceeds desired balances, inducing bond purchases and downward rate pressure toward d. Reducing supply to MS1 changes the relevant equilibrium to a on MD2 at r4. The policy changes the equilibrium, rather than reversing the asset adjustment at the original curves.','legendary')
adj=[
 ('PM2D1-LRADJ-EB-002','At AD1-AS1 the graph places output at Y3 below potential Y1. Demand stays fixed. Which wage adjustment and output movement would close this gap?', ['Falling expected wages/costs shift AS1 toward AS2 and raise output toward Y1','Rising expected wages/costs shift AS2 toward AS1 and raise output toward Y1','Falling expected wages/costs shift AD1 toward AD2 and lower output toward Y3','Rising expected wages/costs shift LRAS toward Y3 and increase productive capacity'], 'A recessionary gap puts downward pressure on expected wages/costs. With demand fixed, supply shifts right toward AS2, returning output toward Y1.','hard'),
 ('PM2D1-LRADJ-MB-004','At AD1-AS1/Y3, nominal wages are fixed by contracts for one year. Officials predict immediate self-correction to Y1 solely through lower wages. Which part of that prediction conflicts with the stated constraint?', ['The direction is appropriate but the claimed timing is not: wage-based AS adjustment must wait for contracts','The timing is appropriate but the direction is not: lower wages shift AS left','Both are appropriate because contracts cannot affect short-run supply adjustment','Neither is appropriate because returning to Y1 requires LRAS to move left'], 'Lower wages would shift AS1 toward AS2, but fixed contracts prevent that wage mechanism from completing immediately. Distinguish eventual direction from adjustment speed.','hard'),
 ('PM2D1-LRADJ-FB-006','Demand has moved AD1→AD2 while supply remains AS2. Compare fixed AD2 with a policy that reverses demand to AD1 before expected wages rise. Which final price/output pairs follow?', ['Fixed AD2 with wage adjustment gives P3/Y1; quick reversal with AS2 unchanged gives P1/Y1','Fixed AD2 gives P1/Y1; quick reversal gives P3/Y1','Both give P2/Y2 because demand permanently raises potential','Both give P2/Y3 because all adjustment is contractionary'], 'The first path moves AS2→AS1 with AD2 fixed. The second returns to AD1-AS2 before the supply response. Both recover potential, but at different price levels.','elite'),
 ('PM2D1-LRADJ-LB-002','At AD1-AS1/Y3, wages start falling. Before adjustment ends, demand falls further left of AD1. Which conclusion can still be drawn without the sizes of the two shifts?', ['Falling wages support recovery, but the new demand loss can offset it; the original path to Y1 is no longer guaranteed','Output must reach Y1 immediately because any rightward supply shift dominates demand','Output must fall because any leftward demand shift dominates supply','Potential output must fall because simultaneous AD and SRAS shifts automatically move LRAS'], 'Rightward AS adjustment raises output relative to unchanged demand, while a new demand contraction lowers it. Relative magnitudes determine the net output path; LRAS need not move.','legendary')]
for i,s,a,f,t in adj:graph(i,s,a,f,t)
graph('PMOE-FX-B3-003','In FX-03, supply expands and the foreign-units-per-domestic-unit rate falls from1 to0.8 while quantity rises100→150. An importer faces an unchanged foreign price. Which rate, quantity and home-currency import-cost comparison is correct?',
 ['Domestic currency depreciates20%, traded quantity rises50%, and the home cost of the import rises25%','Domestic currency depreciates20%, quantity rises50%, and the home import cost rises20%','Domestic currency appreciates25%, quantity rises50%, and the home import cost falls20%','Domestic currency depreciates20%, quantity rises33.3%, and the home import cost falls25%'],
 'Rate change=.8/1−1=−20%; quantity change=150/100−1=50%. Home currency per foreign unit rises from1 to1/.8=1.25, increasing a fixed foreign-price import cost25%. Reciprocal percentage changes are not symmetric.','elite',proof(('(.8-1)*100',-20),('(150/100-1)*100',50),('(1/.8-1)*100',25)))

# One routine representative remains; the other five diagnose distinct channels.
patch('LG-Q-9052','MAA-0130: retained routine representative; final demand is linked graph plus multiplier application.',canonicalDifficulty='hard',difficulty='hard')
graph('LG-Q-9053','The graph shows MS1→MS2, followed by AD falling $240 billion. MPC=.75 and only investment changes autonomously. Which reverse inference identifies the investment change and its place in the chain?',
 ['Investment fell $60 billion after rates rose; the multiplier converts that impulse to the total AD loss','Investment fell $240 billion before rates changed; the AD loss is the autonomous impulse','Investment rose $60 billion after rates fell; the money shift is expansionary','Investment fell $960 billion after rates rose; divide the total loss by MPC'],
 'The multiplier is4, so the autonomous investment reduction is240/4=60. In the graph a supply contraction raises rates, reducing investment before the induced spending response.','hard',proof(('240*(1-.75)',60)))
graph('LG-Q-9055','Read the graph in reverse: policy moves MS2→MS1, lowering rates and raising investment $40 billion. A separate confidence loss reduces investment $25 billion. MPC=.5. Which net AD change follows?',
 ['Right $30 billion: multiply the net $15 billion autonomous investment rise','Right $80 billion: ignore the confidence loss because rates fell','Left $30 billion: reverse the effect of a net investment increase','Right $15 billion: include both impulses but omit induced spending'],
 'Reversing the displayed contraction gives expansion. Net autonomous investment changes40−25=15; with multiplier2, AD rises30. The rate response alone does not determine the size after a confidence countershock.','elite',proof(('(40-25)/.5',30)))
graph('LG-Q-9056','The graph shows the same rate rise in two economies. Investment falls $20 billion in A and $5 billion in B; both have MPC=.8 and no other shocks. Which inference compares transmission strength rather than reserve accounting?',
 ['AD falls $100 billion in A and $25 billion in B; B has weaker investment sensitivity to the rate change','AD falls $20 billion in A and $5 billion in B; the multiplier is irrelevant to rate-induced spending','AD falls $25 billion in A and $100 billion in B; weaker investment sensitivity magnifies the effect','AD falls $100 billion in both; identical rate changes guarantee identical spending changes'],
 'The multiplier is5, giving losses100 and25. The divergence arises at interest→investment, even though the preceding observed rate change and subsequent multiplier are identical.','hard',proof(('20/.2',100),('5/.2',25)))
graph('LG-Q-9059','MS1→MS2 in the graph reduces investment $40 billion with MPC=.8. An immediate fiscal program adds $200 billion to AD in total after induced effects. If that fiscal program instead arrives after the monetary contraction has ended, which comparison is justified?',
 ['Immediate effects offset; the delayed program can create excess demand after the original gap closes','Both timings offset exactly because equal dollar effects guarantee equal stabilization','Immediate AD rises $800 billion because the total fiscal effect must be multiplied again','Immediate AD falls $200 billion because fiscal and monetary shifts cannot offset'],
 'The investment effect is−40/.2=−200 and the immediate total fiscal effect+200 offsets it. Equal magnitudes do not ensure stabilization if the countershock arrives at a different point in the cycle.','elite',proof(('-40/.2+200',0)))
graph('LG-Q-9072','The graph holds money demand fixed while MS1→MS2 raises rates. Now suppose money demand also falls. Without relative shift sizes, which part of the displayed rate→investment→AD prediction is still certain?',
 ['The supply reduction alone puts upward pressure on rates, but the net rate, investment and AD effects are not determined','The net rate must rise because supply reductions dominate all demand changes','The net rate must fall because demand reductions dominate all supply changes','The net rate is unchanged because every pair of leftward money-market shifts cancels'],
 'Less supply raises the equilibrium rate holding demand fixed; lower demand reduces it holding supply fixed. Without magnitudes the combined rate direction, and hence the interest-sensitive spending chain, cannot be signed.','elite')
task('LG-Q-9119','Compare two $100 one-year loans using the Fisher approximation. Loan A fixes nominal interest at10%; Loan B promises a6% real return through full inflation indexation. Inflation was expected to be4% but is11%. Which realized lender return and redistribution comparison is correct?',
 ['A yields about−1% real, B6%; unexpected inflation transfers purchasing power from A’s lender to borrower but not through B’s indexed rate','A yields6% real, B−1%; indexation exposes only B’s lender to the inflation surprise','Both yield−1% real; a fixed real promise changes no inflation exposure','Both yield6% real; expected inflation determines realized purchasing power even when actual inflation differs'],
 'A’s expected real rate was10−4=6%, but its realized approximate rate is10−11=−1%. Full indexation preserves B’s promised real6%. The7-point surprise redistributes on the fixed nominal contract, not through the indexed real-rate promise.','analysis','Confuses expected and realized real returns or treats an indexed real contract as fixed nominal.',proof(('10-11',-1),('10-4',6)))
patch('LG-Q-9119',canonicalDifficulty='elite',difficulty='elite')
save()
