from checkpoint_support import *

for concept in ['short-run-phillips-curve','long-run-phillips-curve','phillips-curve-expectations','disinflation-and-policy','sacrifice-ratio']:
 for j,id in enumerate(candidates(concept)):
    a=100+20*j;mode=j%4
    if concept=='short-run-phillips-curve':
      cases=[
       (f'An economy with {a} workers starts at natural unemployment. Unexpected demand expansion raises inflation and lowers unemployment; expected inflation and supply conditions initially stay fixed. Which first-stage and later-stage account is consistent?',
        ['Initially move along SRPC; if expectations catch up, SRPC shifts up and unemployment returns toward natural','Initially shift SRPC up; later move to permanently lower natural unemployment','Initially move along LRPC; expectations then rotate LRPC downward','Initially shift SRPC down; higher inflation requires lower inflation expectations'],
        'A demand shock with fixed expectations moves along a given SRPC. When higher inflation enters expectations, the curve shifts up; the initial unemployment gain need not persist.',None),
       (f'Use inflation = expected inflation − 0.5×(unemployment−5), with rates in percent. Expected inflation is 3%. A policy moves unemployment from 5% to 3% in a workforce of {a}. Which result and condition matter?',
        ['Inflation becomes 4%; this is a movement along the given curve only while expected inflation stays fixed','Inflation becomes 2%; lower unemployment lowers inflation along the given curve','Inflation remains 3%; natural unemployment forces actual unemployment to stay at 5%','Inflation becomes 4%; the calculation establishes a permanent unemployment gain after expectations adjust'],
        'Substitution gives 3−.5×(3−5)=4%. That is a conditional short-run relation. A later expectations change shifts the relation and invalidates a permanent-tradeoff inference.',proof(('3-.5*(3-5)',4))),
       (f'Inflation and unemployment both rise in a country with {a} workers. Expected inflation or supply conditions may have changed. Which diagnosis avoids calling every observation a movement along the same SRPC?',
        ['A worsened supply/expectations relation can shift SRPC up; the two rising variables do not fit a pure movement along an unchanged downward curve','A pure positive demand shock along an unchanged SRPC raises both variables','The higher unemployment proves expected inflation must have fallen, shifting SRPC down','The observations prove the LRPC slopes upward because every pair of data points defines the long-run relation'],
        'Along a fixed downward SRPC, inflation and unemployment move in opposite directions. A shifted short-run relation can produce simultaneous increases; more evidence is needed to isolate supply from expectations.',None),
       (f'Two countries each employ {a} workers and have identical natural unemployment. Both reduce demand, but one begins with higher expected inflation. Under parallel SRPCs and unchanged expectations during the adjustment, which comparison is supported?',
        ['At a common unemployment rate, the high-expectations country retains higher inflation; equal unemployment does not identify one common SRPC','At a common unemployment rate, inflation must be equal because natural unemployment is equal','The high-expectations country has lower inflation at every unemployment rate because expectations reverse the tradeoff','Reducing demand necessarily shifts both LRPCs right by the same amount'],
        'Expected inflation shifts the SRPC vertically. A common natural rate fixes the long-run unemployment benchmark, not the short-run inflation intercept. Compare the curves rather than treating both observations as points on one curve.',None)]
    elif concept=='long-run-phillips-curve':
      cases=[
       (f'A government seeks permanently lower unemployment in a workforce of {a} by repeatedly surprising workers with higher inflation. Expected inflation eventually adapts, and labor-market structure is unchanged. Which long-run assessment is justified?',
        ['Unemployment returns toward its natural rate at higher inflation; a lasting reduction needs changed real labor-market conditions','Unemployment stays permanently lower because the downward SRPC is also the long-run policy menu','The natural rate rises one-for-one with each price-level increase by definition','The price level must return to its original value when unemployment returns to natural'],
        'With expectations adjusting and the natural rate unchanged, the long-run curve is vertical. Repeated monetary surprises do not establish a permanently lower unemployment benchmark.',None),
       (f'Matching reform reduces natural unemployment from 6% to 5% in a labor force of {a}. Aggregate-demand policy separately raises sustained inflation after expectations adjust. Which graph distinction is correct?',
        ['The reform shifts LRPC left; the inflation change is a different long-run point on the new vertical curve','The reform moves along a fixed LRPC; demand policy shifts LRPC left','Both effects are movements along a downward-sloping LRPC','Higher sustained inflation shifts LRPC right and necessarily reverses the reform'],
        'Structural changes in matching affect the natural rate and shift LRPC. A different sustained inflation rate with expectations adjusted does not itself determine natural unemployment.',None),
       (f'Actual unemployment is 4% when the natural rate is 5% in a workforce of {a}. Inflation expectations are temporarily below actual inflation. Which future comparison is conditional on unchanged real labor-market structure?',
        ['As expectations catch up, unemployment can return to 5%; the initial 4% does not prove LRPC shifted left','As expectations catch up, unemployment must stay 4%; observed unemployment defines the natural rate','As expectations catch up, LRPC becomes horizontal because monetary policy determines all employment','As expectations catch up, unemployment must become zero because the initial gap was negative'],
        'A temporary below-natural unemployment rate can be a demand/expectations gap. Without a structural change, adjustment does not require a new natural rate.',None),
       (f'Two economies with {a} workers each end a disinflation at different sustained inflation rates but the same natural unemployment rate. Both have fully adjusted expectations and identical labor-market structure. Which inference is consistent?',
        ['Different long-run inflation rates can coexist with the same unemployment benchmark; their transition costs may still differ','The economy with lower inflation must have lower natural unemployment','The economy with higher inflation must have permanently lower unemployment because SRPC slopes down','Equal natural rates imply equal cumulative output losses during every disinflation'],
        'LRPC fixes the long-run unemployment benchmark under these assumptions, not inflation or the route taken. Different expectations/timing paths can produce different transition costs.',None)]
    elif concept=='phillips-curve-expectations':
      cases=[
       (f'Use inflation = expected inflation − (unemployment−5) + supply offset. Unemployment is 6%, actual inflation 4%, and an independently measured temporary supply offset is +2 points in an economy with {a} workers. What is identified?',
        ['Expected inflation is 3%; without the offset measurement the data identify only expected inflation plus the offset','Expected inflation is 5%; without the offset measurement expectations are still separately identified','Expected inflation is 1%; subtract the unemployment gap and offset from actual inflation','Expected inflation is 4%; actual inflation equals expected inflation away from natural unemployment'],
        '4=πe−1+2 gives πe=3. Without a measured offset, only πe+offset=5 is identified. Observed inflation and unemployment alone cannot separate these two vertical-shift mechanisms.',proof(('4+(6-5)-2',3),('4+(6-5)',5))),
       (f'In an economy with {a} workers, an oil-price shock raises inflation while contracts reflect old expectations. The oil shock later ends, but expected inflation has risen and remains above its original level. What can be concluded about the final SRPC?',
        ['It remains above the original curve; its position relative to the shock-period curve depends on the expectation rise versus the removed supply offset','It returns exactly to the original curve because ending the physical shock removes every source of inflation persistence','It must lie above the shock-period curve because any expectation increase exceeds any removed supply offset','It lies below the original curve because the physical shock was temporary'],
        'The final curve retains the expectation increase but loses the temporary supply offset. It is above the original; comparison with the shock period needs both magnitudes.',None),
       (f'Wage contracts in an economy with {a} workers were written for 5% inflation. A credible announcement lowers forecasts to 2%, but those contracts cannot reset this year. Which qualification prevents overstating the announcement\'s immediate effect?',
        ['Lower forecasts can help future adjustment, but existing contracts can still create a short-run cost when demand slows','Credibility guarantees every nominal contract instantly resets even though the stem rules it out','Unchanged contracts mean expectations can never change in any later period','Lower expected inflation shifts LRPC left and permanently reduces natural unemployment'],
        'Credibility may affect expectations, but fixed contracts delay the associated nominal adjustment. The timing assumption matters; a forecast change alone does not guarantee a costless immediate disinflation.',None),
       (f'Workers in an economy of {a} repeatedly observe inflation above their forecasts. Supply conditions and natural unemployment are unchanged. Which adaptation and policy implication follow?',
        ['Higher forecasts shift SRPC up; repeating the same actual inflation no longer produces the original surprise-driven unemployment reduction','Higher forecasts shift SRPC down; repeating inflation permanently lowers unemployment further','Higher forecasts move the economy along an unchanged SRPC rather than changing its intercept','Higher forecasts shift LRPC left by the same number of points as the forecast revision'],
        'Once higher inflation is expected, the short-run curve shifts upward. Maintaining an old actual inflation rate then produces less surprise, so the original temporary unemployment benefit fades.',None)]
    elif concept=='disinflation-and-policy':
      cases=[
       (f'A country with output ${a} reduces inflation from 8% to 3% through demand restraint. Prices keep rising, and unemployment temporarily exceeds natural. Which diagnosis includes all three observations?',
        ['This is disinflation, not deflation; positive inflation raises prices while demand restraint can impose temporary real costs','This is deflation because any lower inflation rate means falling prices; unemployment must therefore fall','This is disinflation with no real cost because prices continue to rise','The observations are inconsistent because lower inflation always requires permanently lower natural unemployment'],
        'Disinflation lowers the inflation rate, not necessarily the price level. With sticky expectations or contracts, demand restraint can temporarily lower output and raise unemployment.',None),
       (f'Two plans each lower inflation four points in an economy with annual output ${a}. A rapid plan loses 8% of one year\'s output cumulatively; a gradual plan loses 6%. Which comparison is supported, and what is not established?',
        ['The gradual plan has a lower measured sacrifice ratio (1.5 versus 2); those totals alone do not prove it is preferable under every timing constraint','The rapid plan has the lower sacrifice ratio because fewer calendar years always lower cumulative cost','Both plans have ratio 4 because the inflation reduction is identical','The gradual plan is costless because spreading losses across years removes them from the sum'],
        'Using the stated cumulative-loss convention: rapid 8/4=2, gradual 6/4=1.5. Timing, uncertainty and other constraints are additional evaluation margins.',proof(('8/4',2),('6/4',1.5))),
       (f'A credible disinflation announcement in an economy of {a} workers lowers expectations before demand falls; contracts can reset immediately. Compare this with identical demand restraint under fixed old expectations.',
        ['Earlier expectations/contract adjustment can reduce the initial unemployment excursion; the conclusion depends on those adjustment assumptions','Earlier adjustment must raise the unemployment excursion because lower expected inflation shifts SRPC up','Both paths must have identical initial unemployment because credibility can never affect wage setting','Earlier adjustment permanently lowers natural unemployment even though labor-market structure is unchanged'],
        'Lower expectations shift SRPC down before the contraction moves the economy along it. This can reduce the short-run output/employment cost, but is conditional on the explicitly rapid contract adjustment.',None),
       (f'After disinflation, unemployment returns to its original natural rate and the inflation rate stabilizes at 2%. The price index is now {a+20}, compared with {a} before. Which claim is supported?',
        ['The temporary labor-market cost can have unwound even though the price level is permanently higher','Returning to natural unemployment requires the price index to return to its original level','A higher price index proves disinflation failed regardless of the lower inflation rate','A 2% inflation rate means the price index now falls two points each year'],
        'A successful reduction in positive inflation need not undo earlier price increases. Longer-run labor adjustment and the cumulative price-level path are different outcomes.',None)]
    else:
      cases=[
       (f'Use the sum of annual output-gap losses, measured as percentages of one year\'s output ${a}. Gaps are −2%, −1%, and −1%; inflation falls from 7% to 5%. An analyst divides by final inflation. Which correction is right?',
        ['The ratio is 4/2=2; divide cumulative loss by the two-point inflation reduction','The ratio is 4/5=0.8; divide by the final inflation rate','The ratio is 4/7; divide by the initial inflation rate','The ratio is 1/2=0.5; only the final year\'s loss matters'],
        'Cumulative loss is 2+1+1=4% of one year\'s output. The denominator is 7−5=2 percentage points, so the sacrifice ratio is 2, not loss divided by either inflation level.',proof(('(2+1+1)/(7-5)',2))),
       (f'A policy in an economy with annual output ${a} has a sacrifice ratio of 2.5 and a maximum allowed cumulative loss of 5% of one year\'s output. Under a constant-ratio planning assumption, what inflation reduction fits the constraint?',
        ['At most 2 percentage points; divide the loss budget by the ratio','At most 12.5 percentage points; multiply the loss budget by the ratio','At most 5 percentage points; the loss percentage and inflation reduction have the same units','At most 0.5 percentage points; divide the ratio by the loss budget'],
        'Loss = ratio × inflation reduction, so the maximum reduction is 5/2.5=2 points. This is conditional on the stated constant ratio; it is not a universal policy law.',proof(('5/2.5',2))),
       (f'Policy A loses 6% of annual output ${a} to cut inflation 3 points. Policy B loses 5% to cut inflation 2 points. Which policy comparison separates total loss from loss per point?',
        ['A has the larger total loss but the smaller ratio: 2 versus 2.5','B has the smaller ratio because its total loss is smaller','Both ratios equal 3 because total losses differ by one point','A has ratio 18 and B ratio 10; multiply loss by inflation reduction'],
        'A:6/3=2. B:5/2=2.5. Smaller total loss does not necessarily mean lower cost per unit of inflation reduction; the size of the achieved reduction matters.',proof(('6/3',2),('5/2',2.5))),
       (f'A three-point disinflation in an economy with annual output ${a} has an overall sacrifice ratio of 2. The first point already cost 3% of annual output. What ratio applies to the remaining two points, and how does it compare with the first?',
        ['Remaining loss is 3% and its ratio 1.5, below the first-point ratio of 3','Remaining loss is 6% and its ratio 3, equal to the first-point ratio','Remaining loss is 3% and its ratio 3, because every stage must match the first','Remaining loss is 9% and its ratio 4.5, because previous loss is added again'],
        'Total planned loss is 3×2=6%. Subtract the 3% already incurred, leaving 3% for two points:3/2=1.5. A whole-program average need not equal every stage\'s marginal ratio.',proof(('3*2-3',3),('(3*2-3)/2',1.5)))]
    stem,ans,fb,p=cases[mode];emit(id,stem,ans,fb,tier='legendary' if concept=='phillips-curve-expectations' and mode in (0,1,2) else 'elite' if mode==3 else 'hard',error='Confuses a fixed short-run relation with an expectations/supply shift, or divides disinflation costs by the wrong quantity.',proof=p)
save()
