from checkpoint_support import *

for concept in ['quantity-theory-of-money','monetary-neutrality','fisher-effect','inflation-costs','inflation-tax-and-deflation']:
 for j,id in enumerate(candidates(concept)):
    a=100+20*j;mode=j%4
    if concept=='quantity-theory-of-money':
      cases=[
       (f'Money is initially ${a}, velocity 4 and real output {2*a}. Money rises 10%, velocity falls 10%, and real output is unchanged. Which conclusion corrects the claim that prices must rise 10%?',
        ['The price level falls 1%; the opposing percentage changes in M and V combine multiplicatively','The price level rises 10%; money growth alone determines prices without a velocity assumption','The price level is unchanged; equal opposite percentage changes exactly cancel','The price level falls 10%; ignore the simultaneous money increase'],
        'MV=PY. With Y fixed, P changes by the product of M and V factors: 1.10×0.90=.99, a 1% fall. A constant-velocity shortcut is not valid here.',proof(('(1.1*.9-1)*100',-1))),
       (f'Money is ${a}, velocity is 5, and the price level is 2. A report gives real output as {5*a}. Which corrected output and interpretation are consistent with MV=PY?',
        [f'Real output is {2.5*a:g}; {5*a} is nominal spending, which must be divided by the price level',f'Real output is {10*a}; multiply nominal spending by the price level',f'Real output is {5*a}; the price level does not enter real output',f'Real output is {a/10:g}; divide money by both velocity and the price level'],
        f'MV={a}×5={5*a}, a nominal-spending measure. Real output is MV/P={5*a}/2={2.5*a:g}.',proof((f'{a}*5/2',2.5*a))),
       (f'An economy begins with money ${a}. Money and real output each rise 5%, while velocity is unchanged. A commentator predicts 5% inflation solely from money growth. Which condition makes that conclusion incorrect?',
        ['The equal real-output growth absorbs the nominal-spending growth; the price level is unchanged','The fixed velocity requires real output to remain unchanged, making the stated output growth impossible','Equal money and output growth doubles the inflation rate to 10%','Money growth affects only real output, so prices are always fixed regardless of velocity'],
        'The exact price factor is 1.05×1/1.05=1. Money growth alone cannot determine inflation when real output changes too.',proof(('1.05/1.05',1))),
       (f'A country has nominal spending ${4*a}. It aims for a 3% price-level increase with real output up 2% and velocity down 1%. What money-growth factor is required, and why is adding 3% and 2% incomplete?',
        ['About 6.1% money growth; falling velocity also has to be offset','Exactly 5% money growth; velocity does not affect the target','About 4.0% money growth; falling velocity amplifies the desired spending increase','Exactly 1% money growth; subtract real growth from the price target'],
        'Solve M factor = P factor × Y factor / V factor = 1.03×1.02/.99≈1.06121, or 6.1%. The velocity decline reduces spending per dollar and requires additional money growth.',proof(('(1.03*1.02/.99-1)*100',6.121212121)))]
    elif concept=='monetary-neutrality':
      cases=[
       (f'A worker initially earns ${a} while the consumption-price index is 100. In a long-run monetary-neutrality comparison, nominal wages and all prices double while real technology and resources are unchanged. Which conclusion respects both nominal and real measures?',
        ['Nominal pay doubles while the real wage and long-run productive capacity can remain unchanged','The real wage doubles because its numerator doubles, even though prices also double','Productive capacity doubles because a larger money stock is itself more real capital','Nominal pay is unchanged because neutrality freezes every monetary variable'],
        'A real wage is nominal wage divided by prices; doubling both preserves the ratio. Long-run neutrality permits nominal changes without corresponding changes in real productive capacity.',proof(('2/2',1))),
       (f'A one-time increase in money causes temporary output above potential in an economy with {a} workers. Over time wages and expected prices adjust. Which comparison avoids confusing long-run neutrality with immediate neutrality?',
        ['Short-run real effects can occur; long-run output can return to its real-factor-determined level at a higher price level','Long-run neutrality requires output to remain at potential at every instant after the monetary change','Temporary output growth establishes that potential output permanently rose by the same amount','Expected-price adjustment must lower the price level back to its original value for neutrality to hold'],
        'Sticky wages/prices allow short-run real effects. Longer-run adjustment can return output to potential while nominal prices stay higher; neutrality does not require no transitional effect.',None),
       (f'Nominal wages rise 6% in a workforce of {a}, while prices rise 4%. A claim that these changes demonstrate complete monetary neutrality is made. Which assessment follows from the real-wage evidence?',
        ['The real wage rises about 1.9%; these unequal proportional changes do not by themselves demonstrate unchanged real wages','The real wage is unchanged because any simultaneous nominal wage and price rise is neutral','The real wage rises 10%; nominal wage and price growth should be added','The real wage falls about 1.9%; the price factor belongs in the numerator'],
        'The real-wage factor is 1.06/1.04≈1.01923. Equal proportional nominal changes would leave the ratio unchanged; these are not equal. The calculation alone also does not identify what caused the changes.',proof(('(1.06/1.04-1)*100',1.923076923))),
       (f'Money growth rises permanently in an economy whose real productive resources remain {a} index units. Under the stated long-run quantity-theory/neutrality assumptions with stable velocity, which distinction is correct?',
        ['A higher sustained money-growth rate can raise sustained inflation; a one-time money-level increase instead need not imply permanently higher inflation','A one-time money-level increase and permanently faster money growth necessarily create the same inflation path','Faster money growth permanently raises real productive capacity at the same rate','Neutrality requires every monetary change to leave both the price level and inflation unchanged'],
        'Levels and growth rates differ: a lasting growth-rate change can sustain inflation, whereas a one-time level change is not ongoing faster money growth. Real capacity remains determined by the stated real factors.',None)]
    elif concept=='fisher-effect':
      cases=[
       (f'For a ${a} loan, expected inflation rises from 2% to 5% while the required expected real return falls from 4% to 3%. Under the Fisher approximation, which nominal-rate comparison is correct?',
        ['The nominal rate rises from 6% to 8%; the real-rate decline partly offsets the inflation-expectation increase','The nominal rate rises from 6% to 9%; the real rate must be held fixed despite the supplied change','The nominal rate falls from 6% to 5%; subtract expected inflation from the required real return','The nominal rate remains 6%; opposite movements in components must cancel exactly'],
        'Initially i≈r+πe=4+2=6. Later i≈3+5=8. A one-for-one response to expected inflation requires a fixed real rate, which is not the case here.',proof(('4+2',6),('3+5',8))),
       (f'A ${a} fixed-rate loan has nominal interest 7% when expected inflation is 3%. Actual inflation later turns out to be 6%. Which pair separates the rate-setting prediction from the realized outcome?',
        ['The expected real return was about 4%; the realized real return is about 1%, without changing the signed nominal rate','The expected real return was about 1%; the nominal contract automatically resets to 10% after inflation is observed','Both expected and realized real returns are 4% because the lender chose a fixed nominal rate','The nominal rate becomes 6% because actual inflation replaces the contractual rate'],
        'Fisher rate setting uses expected inflation at agreement; ex post purchasing power uses actual inflation. Thus 7−3=4% expected and 7−6=1% realized; the nominal contract remains 7%.',proof(('7-3',4),('7-6',1))),
       (f'In a loan market financing ${a} of projects, nominal rates fall 2 percentage points while the expected real rate is unchanged. Within the Fisher approximation, what inference follows and what remains unproved?',
        ['Expected inflation fell 2 points; actual future inflation need not equal that forecast','Expected inflation rose 2 points; actual future inflation must rise equally','Actual inflation already fell 2 points; no expectation assumption is needed','The real rate fell 2 points despite the stated fixed-real-rate condition'],
        'With Δr=0, Δi≈Δπe. A two-point nominal decline implies a two-point expectation decline in this model, but forecasts are not necessarily realized.',None),
       (f'Expected inflation rises 4 points in a credit market of size ${a}, but the nominal rate rises only 1 point. If the Fisher approximation applies, which reconciliation is correct?',
        ['The expected real rate fell 3 points; a changing real rate explains the less-than-one-for-one nominal response','The expected real rate rose 3 points; subtract the nominal change from inflation expectations','The approximation proves the data impossible because the real rate cannot change','The actual inflation rate must have fallen 3 points because expected and actual inflation are interchangeable'],
        'Δi=Δr+Δπe implies Δr=1−4=−3 points. A changing real component is compatible with the identity; actual inflation is a separate outcome.',proof(('1-4',-3)))]
    elif concept=='inflation-costs':
      cases=[
       (f'A firm spends ${a} repeatedly updating posted prices, and households make extra account transfers to avoid idle cash. Inflation is perfectly anticipated. Which comparison identifies costs that need not disappear with correct forecasts?',
        ['Repricing uses menu-cost resources and cash management uses shoeleather resources; both can remain without surprise redistribution','Both are surprise debtor-creditor redistribution and vanish whenever inflation is forecast correctly','Repricing is a transfer to borrowers and cash management is a transfer to lenders','Both are nominal changes with no possible use of real time or resources'],
        'Menu and shoeleather costs concern resources spent adapting to inflation. Correct forecasts can reduce unexpected contract redistribution without eliminating these costs.',None),
       (f'A ${a} fixed nominal debt was agreed with expected inflation 2%, but actual inflation is 7%. At the same time, firms incur real repricing costs. Which combined assessment is correct?',
        ['Unexpected inflation benefits the borrower relative to the lender, while repricing consumes real resources','Unexpected inflation benefits the lender relative to the borrower, while repricing consumes real resources','Borrower gains exactly equal a social resource gain, so repricing cannot reduce welfare','Repricing redistributes debt obligations but uses no real resources, so it is the same as surprise inflation'],
        'A lower-than-expected real repayment transfers purchasing power toward borrowers. Repricing is a resource cost, so redistribution and efficiency costs are conceptually different.',None),
       (f'Two economies each have ${a} in fixed nominal contracts. One unexpectedly raises inflation; the other credibly announces the same inflation before new contracts are written. Which difference is supported?',
        ['The surprise creates more unexpected redistribution on existing contracts; the anticipated path can still create resource costs','The anticipated path must be economically costless because contracts can price every resource cost away','The surprise benefits all borrowers and lenders equally because the price level rises for both','Both paths must have identical redistribution regardless of contract timing and indexation'],
        'Contract timing and expectations determine surprise redistribution. Anticipation allows adjustment but does not generally remove repricing, cash-management or tax-distortion costs.',None),
       (f'A saver earns a nominal ${a} return that only compensates for inflation. The tax system taxes the entire nominal return without inflation adjustment. Which inference follows?',
        ['Tax can reduce real principal despite a zero pre-tax real gain; nominal income and real income differ','No tax distortion is possible because a zero real gain implies a zero nominal tax base','The tax increases the saver\'s real return because it is charged in nominal dollars','The nominal return is all a real gain because inflation compensation counts as extra purchasing power'],
        'A tax on nominal interest can tax inflation compensation as though it were real income. After-tax purchasing power can therefore fall even when the pre-tax real return is zero.',None)]
    else:
      cases=[
       (f'A household holds ${a} in currency while the price level rises 25%. No interest is paid. Which loss and interpretation fit the inflation-tax mechanism?',
        ['The currency buys 20% less of the old basket; its real value falls without a separate statutory tax bill','The currency buys 25% less exactly; use the price rise itself as the reciprocal purchasing-power fall','The nominal currency balance falls 25%; inflation removes printed dollars from the wallet','Purchasing power is unchanged because currency is a nominal asset'],
        'Real balances are M/P. With nominal currency fixed and prices multiplied by 1.25, purchasing power becomes 1/1.25=.8 of its original level, a 20% loss.',proof(('(1/1.25-1)*100',-20))),
       (f'Inflation falls from 8% to 3% in an economy with price index {a}. A report calls this a fall in the price level and predicts a lower real burden of fixed nominal debt. Which correction is needed?',
        ['Prices still rise, just more slowly; this is disinflation, and the stated rates alone do not imply actual deflation','Prices fall 5%; this is deflation, and fixed nominal debt automatically loses real value','Prices are unchanged; any reduction in inflation stops price increases immediately','Prices rise faster; a lower positive inflation rate means accelerating prices'],
        'A positive inflation rate still raises the price level. A slower rise is disinflation, whereas deflation is a falling price level; fixed-debt effects also depend on the relevant price comparison.',None),
       (f'A household owes a fixed nominal ${a}. Prices fall 10% while its nominal debt is unchanged. Which debt-burden comparison is correct?',
        ['The real burden rises about 11.1%; the same nominal repayment buys more goods','The real burden falls 10%; cheaper goods make every nominal debt smaller in real terms','The real burden rises exactly 10%; reciprocal percentage changes are equal','The real burden is unchanged because a fixed nominal debt is also fixed in real terms'],
        'The real-debt factor is 1/.90≈1.1111. Falling prices increase, rather than decrease, the purchasing power needed to repay a fixed nominal amount.',proof(('(1/.9-1)*100',11.11111111))),
       (f'Government finances ${a} of purchases by creating money. Under stable velocity and fixed long-run real output, which accounting-versus-burden distinction is appropriate?',
        ['Nominal financing provides purchasing power to government, while resulting inflation can reduce existing holders\' real money balances','Money creation produces real resources directly, so existing holders face no possible purchasing-power effect','Every money-financed purchase requires an equal statutory tax payment from each money holder','The inflation-tax burden is identical for people regardless of how many non-interest-bearing balances they hold'],
        'Money financing changes claims on real goods, not productive resources themselves. Under the stated assumptions, higher prices erode real balances; exposure depends on money holdings and timing.',None)]
    stem,ans,fb,p=cases[mode];emit(id,stem,ans,fb,tier='elite' if mode==3 else 'hard',error='Confuses nominal and real quantities, expected and actual inflation, or a price level with its growth rate.',proof=p)
save()
