"""Remove exact repetitions introduced while authoring the scoped F families."""
from checkpoint_support import *
def revise(id,s,a,f,t='elite',checks=()):
    emit(id,s,a,f,tier=t,proof=proof(*checks) if checks else None)

revise('ECON-NL-FINALBOSS-4011','Demand has recovered, yet displaced factory workers remain unemployed while hospitals advertise vacancies requiring different credentials. Which observation changes the diagnosis and policy emphasis?',
 ['Unfilled jobs with incompatible skills point to structural mismatch and retraining, beyond demand support','Recovered demand proves the remaining unemployment is cyclical and requires only more spending','Vacancies prove the workers are already employed, so no labor-market issue remains','Different credentials show purely frictional search that cannot be helped by training'],
 'Recovery removes the original demand explanation as a sufficient account. Simultaneous vacancies and missing credentials identify a mismatch that demand stimulus alone need not solve.')
revise('ECON-NL-FINALBOSS-4018','A matching platform shortens job searches, but a recession simultaneously reduces vacancies. Which prediction distinguishes the affected components without assuming their sizes?',
 ['Frictional unemployment may fall while cyclical unemployment rises; total unemployment is ambiguous','Both changes reduce cyclical unemployment, so total unemployment must fall','Both changes raise structural unemployment, so total unemployment must rise','Matching changes only participation, so the unemployment components cannot change'],
 'Faster matching reduces normal search duration, while weaker demand creates cyclical joblessness. The net change cannot be signed without magnitudes.')
revise('ECON-NL-LEGENDARYBOSS-9127','An initially cyclical recession lasts long enough that displaced workers lose relevant skills. Demand later recovers fully. A forecast assumes the old natural rate must immediately return. Which counterfactual best reveals the forecast’s weakness?',
 ['With identical recovered demand, an economy that preserved skills can have lower structural unemployment than one that lost them','With identical recovered demand, both economies must have the same natural rate regardless of skills','With identical recovered demand, the economy with lost skills must have lower frictional unemployment and lower total unemployment','With identical recovered demand, neither economy can have any unemployment'],
 'Demand recovery can remove cyclical weakness while skill loss leaves a structural legacy. Comparing otherwise similar recoveries isolates that mechanism; the old natural rate is not assured.','legendary')
revise('PM2B4-UTYPE-LB-002','Two plans address unemployed workers after a recession and permanent automation. Plan A restores spending immediately; Plan B retrains workers but starts next year. A report calls either plan sufficient for every worker immediately. Which correction recognizes mechanism and timing?',
 ['A can help demand-related layoffs but not directly supply missing skills; B can address mismatch only after training takes effect','A and B both immediately eliminate all joblessness because both increase spending','A repairs skill mismatch immediately, while B directly restores current aggregate demand','Neither can affect unemployment because cyclical and structural causes cannot coexist'],
 'The plans operate through different channels and on different schedules. A demand response and a delayed skill response are complements for the mixed case, not interchangeable immediate cures.','legendary')
revise('ECON-NL-FINALBOSS-4026','At a binding wage floor,120 workers seek jobs and firms hire90. A productivity gain raises hiring to110 with the wage and labor supply unchanged. Which claim about the labor surplus is correct?',
 ['It falls from30 to10; the demand improvement reduces but does not remove the surplus','It rises from10 to30 because productivity displaces every worker','It remains30 because a fixed wage implies fixed employment','It disappears because any increase in hiring eliminates a binding wage floor'],
 'Surplus initially120−90=30, later120−110=10. The fixed wage does not prevent labor demand changing; the remaining positive surplus still matters.','hard',(('120-90',30),('120-110',10)))
revise('ECON-NL-FINALBOSS-4031','A firm voluntarily raises wages above market rates. Its wage bill rises$12,000, turnover costs fall$8,000 and improved effort adds$7,000 to revenue. Which evaluation goes beyond looking only at wages?',
 ['Profit rises$3,000 under these estimates; the efficiency gains exceed the wage cost','Profit falls$12,000 because only payroll affects profitability','Profit rises$15,000 because higher payroll is not a cost','Profit falls$3,000 because cost savings reduce revenue'],
 'Net profit change=−12000+8000+7000=3000. The stated efficiency-wage channels can justify higher pay; that is conditional on the estimates.','hard',(('-12000+8000+7000',3000),))
revise('PM2B4-LMI-EB-001','A union agreement raises members’ wages while firms reduce hiring. A report measures only the wage gain of those still employed. Which additional evidence is needed to evaluate the employment tradeoff?',
 ['How many workers lose or cannot obtain jobs under the higher wage','Only the price level, because hiring cannot change at an agreed wage','Only the union’s name, because unemployment is unrelated to the contract','Whether the wage is nominal, because real wages cannot affect labor demand'],
 'The report conditions on remaining employed and omits workers excluded from jobs. Assessing the tradeoff requires both wage gains and the employment margin.','hard')
revise('PM2B4-LMI-MB-005','A minimum wage of$12 is proposed where the competitive equilibrium wage is$15. A forecast predicts a labor surplus solely because a legal minimum exists. Which condition is missing?',
 ['The floor must bind; a$12 minimum does not constrain the stated$15 equilibrium','Any wage floor binds because it is set by law','The floor must be below equilibrium to create excess labor supply','A wage floor creates excess labor demand even when it does not bind'],
 'The usual surplus prediction requires a wage above equilibrium. This floor does not prevent the competitive equilibrium, so the claimed effect does not follow.','hard')
revise('ECON-NL-LEGENDARYBOSS-9131','Actual unemployment falls from8% to5%. During the same period retraining lowers structural unemployment from3% to2%, while frictional unemployment stays2%. Which decomposition avoids crediting the whole decline to demand recovery?',
 ['Natural unemployment falls5%→4%; cyclical unemployment falls3%→1%, so both structural reform and recovery contribute','Natural unemployment stays5%; all3 points are cyclical recovery','Natural unemployment falls3%→1%; all remaining joblessness is frictional','Natural unemployment rises4%→5%; recovery is larger than the observed decline'],
 'Before: natural2+3=5 and cyclical8−5=3. After: natural2+2=4 and cyclical5−4=1. One point comes from the natural-rate change and two from the cyclical decline.','elite',(('2+3',5),('8-5',3),('2+2',4),('5-4',1)))
revise('PM2B4-NRU-MB-004','An economy has frictional unemployment2%, structural3% and actual6%. If a demand recovery removes the cyclical component without changing matching or skills, which rate remains and why?',
 ['5%; frictional and structural unemployment remain after the1-point cyclical gap closes','0%; eliminating cyclical unemployment eliminates every component','3%; frictional unemployment is also purely cyclical','6%; demand recovery cannot affect any unemployment component'],
 'Natural unemployment=2+3=5; the initial cyclical component is6−5=1. Recovery alone does not remove search and structural mismatch.','hard',(('2+3',5),('6-5',1)))
revise('ECON-SP-FINALBOSS-4023','Use approximate growth accounting. Money growth is10%, output growth3%, and inflation4%. A report assumes stable velocity and predicts a nominal interest rate of9% with a2% real rate. Which pair corrects both steps when expected inflation equals actual inflation?',
 ['Velocity growth is−3%; the nominal rate is6%','Velocity growth is+3%; the nominal rate is9%','Velocity growth is0%; the nominal rate is12%','Velocity growth is−9%; the nominal rate is2%'],
 'From π=gM+gV−gY,4=10+gV−3 gives gV=−3. With expected inflation4 and real interest2, Fisher gives nominal6.','elite',(('4-10+3',-3),('4+2',6)))
revise('ECON-SP-LEGENDARYBOSS-9119','Compare two long-run money-growth cuts of4 points. In A, output and velocity growth stay fixed and expectations fully adjust. In B, velocity growth rises4 points while output growth stays fixed. Real interest rates are unchanged. Which comparison follows under the growth and Fisher approximations?',
 ['A’s inflation and nominal interest fall4 points; B’s velocity offset leaves both unchanged','Both inflation and nominal interest fall4 points in both economies because money growth alone determines them','A’s real interest falls4 points; B’s nominal interest falls8 points','Both economies’ real output growth must fall4 points to absorb the policy'],
 'In A, Δπ=−4, so the expected-inflation component of nominal interest falls4. In B, ΔgM+ΔgV=−4+4=0; unchanged inflation expectations imply unchanged nominal rates at the fixed real rate.','legendary',(('-4+4',0),))
revise('ECON-SP-LEGENDARYBOSS-9100','Use π=πe−(u−5)+s. A supply shock raises s from0 to2 while policymakers hold u=5. Expectations later rise from3 to5. If the shock then disappears but expectations remain5, can inflation return to its original3% without an unemployment gap?',
 ['No; at natural unemployment inflation is5%, and achieving3% with those expectations requires u=7%','Yes; removing the supply shock automatically restores original expectations and inflation','No; inflation stays7% even after the2-point supply offset disappears','Yes; holding u=3% offsets the still-high expectations'],
 'At the final s=0 and u=5, π=πe=5. To target3 with πe=5 requires3=5−(u−5), hence u=7. Supply relief need not undo the induced expectations change.','legendary',(('5+(5-3)',7),))
revise('ECON-SP-LEGENDARYBOSS-9120','In π=πe−(u−5)+s, actual inflation is6% and unemployment5%. One analyst attributes the result to πe=6,s=0; another to πe=4,s=2. Which observation would distinguish the implied next-year inflation after the supply offset disappears, if unemployment remains natural?',
 ['An independent expectation estimate: the first case predicts6%, the second4% after supply relief','The current inflation rate alone: it already proves both cases predict4%','The current unemployment rate alone: natural unemployment proves s=0','The two cases are identical because expectations and supply shocks have the same persistence by definition'],
 'Both initial decompositions satisfy6=πe+s at u=5. When a temporary s ends, persistent πe determines natural-rate inflation. Additional expectation evidence is necessary to choose between6 and4.','legendary')
revise('ECON-SP-LEGENDARYBOSS-9101','Two disinflation plans reach the same final inflation and natural unemployment. Plan A has output losses4%,2%,0%; Plan B has2%,2%,2%. A commentator says A is cheaper because it reaches zero loss sooner. Which comparison is established?',
 ['Both cumulative losses are6%; earlier recovery does not by itself establish a lower cumulative sacrifice ratio','A’s cumulative loss is0%, because only its final year counts','B’s cumulative loss is2%, because repeated losses count once','A’s cumulative loss is greater than B’s because its first loss is greater'],
 'Sum the transition losses:4+2+0=6 and2+2+2=6. With the same inflation reduction their sacrifice ratios match, although the time paths and distribution of costs differ.','elite',(('4+2+0',6),('2+2+2',6)))
revise('ECON-SP-MEDIUMBOSS-3002','A planned3-point disinflation has sacrifice ratio2. After credibility improves, the projected cumulative loss falls from6% to3% with the same target. Which updated ratio should be used?',
 ['1; the cost per inflation point has halved','2; the original ratio is fixed by definition','3; cumulative loss itself is the ratio','6; divide the original loss by the new loss and multiply the target'],
 'The revised ratio is3/3=1, compared with6/3=2 before the forecast change. Fixed targets do not imply fixed transition costs.','hard',(('3/3',1),))
revise('ECON-SP-LEGENDARYBOSS-9105','Nominal GDP rises10% and the deflator rises10%. Employment rises2% while hours per worker fall2%. Which conclusion distinguishes what is exactly established from what requires a ratio?',
 ['Real GDP is unchanged; total hours fall0.04%, so output per hour rises slightly despite higher employment','Real GDP rises10%; higher employment proves output per hour rises10%','Real GDP is unchanged and total hours exactly unchanged because the two labor percentages cancel','Real GDP falls0.04%; nominal output and labor input are the same measure'],
 'Real growth=1.10/1.10−1=0. Hours factor=1.02×.98=.9996, so hours fall.04%. With fixed real output, productivity per hour rises1/.9996−1≈.0400%. Different indicators need their own denominators.','elite',(('1.1/1.1-1',0),('(1.02*.98-1)*100',-.04)))
revise('ECON-SP-MEDIUMBOSS-3005','Nominal GDP rises5% while the deflator rises7%. A report calls this a real expansion because total dollar spending increased. Which corrected output signal should a stabilization discussion use?',
 ['Real output fell about1.9%, so the nominal increase alone does not show real expansion','Real output rose5%, because nominal spending measures production volume','Real output rose12%, because inflation adds to real growth','Real output fell7%, because the deflator alone determines production'],
 'Real growth=1.05/1.07−1≈−1.87%. The nominal increase is more than explained by prices.','hard',(('(1.05/1.07-1)*100',-1.869158879),))
revise('PM2A-EXP-EB-007','Use π=πe−(u−5)+s. Actual inflation is4% at unemployment6%. Without information about s, a student reports expected inflation as exactly5%. Which qualification is necessary?',
 ['5% follows only if s=0; a positive supply offset implies a lower expectation estimate','5% is exact for every supply offset because actual inflation is given','Expected inflation is exactly4% whenever actual inflation is4%','A positive supply offset implies a higher expectation estimate at the same inflation and unemployment'],
 'Rearrange to πe=4+(6−5)−s=5−s. Ignoring an unknown supply offset treats an assumption as an observed fact.','elite')
revise('PM2A-SAC-FB-020','A disinflation must fit a cumulative loss budget6% of annual output. Plan A’s ratio is3 and Plan B’s2. Both estimates are treated as constant. Which plan can deliver a3-point reduction within that budget?',
 ['B only: its loss is6%, versus A’s9%','A only: its larger ratio means more inflation reduction per unit loss','Both: a3-point target always costs3%','Neither: each ratio itself exceeds the target'],
 'Multiply cost per point by the3-point target: A9%, B6%. Only B meets the loss ceiling.','hard',(('3*3',9),('2*3',6)))
revise('PM2A-SAC-LB-024','A3-point disinflation was planned at sacrifice ratio2, exhausting a6% loss budget. The first point unexpectedly costs4%. If remaining disinflation costs2% per point, which claim about the original target and budget survives?',
 ['Only one further point fits the remaining2% budget; achieving all3 points would require total loss8%','All remaining2 points fit because the original average ratio remains2 by assumption','No further point can be achieved because the first loss exceeded its forecast','The target can increase because a larger first loss lowers all later losses mechanically'],
 'The unspent budget is6−4=2. At2% per point it buys one further point. Finishing the remaining two would cost4 more and total8; the original joint promises are no longer compatible.','legendary',(('6-4',2),('4+2*2',8)))
revise('PM2C2-NEUT-EB-002','In a long-run comparison, money doubles and all nominal prices double, but a temporary output increase occurred during adjustment. Which claim is inconsistent with neutrality as a long-run proposition?',
 ['That neutrality requires real output to be unchanged at every intermediate date','That proportional nominal adjustments can leave relative prices unchanged','That real output can return to its original long-run level','That temporary real effects can coexist with an unchanged long-run level'],
 'The long-run proposition concerns the endpoint, not the absence of short-run effects while prices and wages adjust.','hard')
revise('PM2C2-NEUT-LB-001','Compare two economies after identical one-time money increases. A resets wages immediately; B has fixed contracts for a year. Productive resources and technology are unchanged in both. Which counterfactual separates short-run adjustment from long-run neutrality?',
 ['Their temporary output paths can differ while both eventually return to unchanged potential output','Their long-run potential must differ because any temporary wage rigidity permanently changes technology','Both must have identical output at every date because neutrality rules out adjustment lags','Only B can experience a price-level change because flexible wages prevent nominal adjustment'],
 'Different nominal rigidities can produce different transition paths. With unchanged real productive conditions, those paths need not imply different long-run real output endpoints.','legendary')
revise('PM2C2-ITAX-EB-001','The price index is100. Inflation falls from8% last year to3% this year. A fixed nominal debt remains$103. At the end of this year, what initial-price purchasing-power value does that debt represent?',
 ['$100; prices rose to103 despite disinflation','$103; a slower inflation rate leaves prices fixed','$106.19; multiply nominal debt by the new price factor','$95; subtract the five-point decline in inflation from the debt'],
 'This year’s3% inflation takes the index100→103. Deflating the103 debt by1.03 gives100. Disinflation is slower price growth, not a falling price level.','hard',(('103/1.03',100),))
revise('PM2C2-ITAX-FB-006','A borrower owes a fixed$1,000. Compare a10% price-level increase with a10% price-level decrease, from an initial index100. Which real-debt comparison uses the correct denominators?',
 ['About$909 after inflation and$1,111 after deflation; equal opposite price percentages have asymmetric real-debt effects','Exactly$900 and$1,100; subtract the percentage directly from the debt','About$1,111 and$909; inflation increases the real debt burden','Exactly$1,000 in both; a fixed nominal contract is also fixed in real terms'],
 'Real debt is1000/1.1≈909 and1000/.9≈1111. A fixed nominal promise changes purchasing-power value when the price level changes.','elite',(('1000/1.1',909.090909091),('1000/.9',1111.111111111)))
revise('PM2A-DIS-FB-016','A rapid disinflation loses5% of annual output and cuts inflation2 points. A gradual plan loses6% and cuts inflation3 points. Which plan has the lower cost per inflation point?',
 ['Gradual:2 versus rapid2.5, despite greater total loss','Rapid:2.5 versus gradual2, because a larger ratio is more efficient','Rapid:5 versus gradual6; the inflation reductions are irrelevant','Both have ratio1 because each plan reduces inflation'],
 'Rapid5/2=2.5, gradual6/3=2. Different targets require comparison per point rather than total loss alone.','hard',(('5/2',2.5),('6/3',2)))
revise('PM2A-DIS-MB-015','A plan reduces inflation from7% to4% at sacrifice ratio2. Another estimate assumes the same ratio but targets3%. How much additional cumulative output loss does the more ambitious target imply?',
 ['2% of annual output','1% of annual output','6% of annual output','8% of annual output'],
 'The second target adds one percentage point of disinflation. At2% output per point, it adds2% cumulative loss (8% rather than6%).','hard',(('2*((7-3)-(7-4))',2),))
revise('PM2A-DIS-FB-017','Two countries announce identical demand restraint. In A, expectations fall promptly and wages can reset; in B, expectations remain high. What can be predicted about transition costs, without a numerical Phillips slope?',
 ['A can face a smaller output cost, but an exact sacrifice-ratio difference is not identified','A must have exactly zero output cost because any credible announcement is costless','B must have the lower cost because higher expectations shift SRPC down','Both must have identical costs because the announced demand restraint is identical'],
 'Faster downward expectations adjustment shifts A’s short-run tradeoff favorably. Without the relevant response sizes, that directional advantage does not identify an exact cost or prove zero cost.','elite')
revise('PM2A-EXP-LB-011','A credible target lowers expectations immediately, but nominal wages cannot reset for one year. Officials propose an equally immediate, large demand contraction and promise no output loss. Which sequencing change would most directly address the stated conflict?',
 ['Coordinate the restraint with contract adjustment; credibility alone does not instantly change locked-in nominal costs','Increase the contraction before wages reset because credibility removes every nominal rigidity','Raise expected inflation back to its old level to shift SRPC down immediately','Treat the old contracts as lower natural unemployment and use the new natural rate as the target'],
 'A belief change and a contract-cost change can occur at different times. The no-loss promise overlooks that timing mismatch; coordinating adjustment addresses it without assuming an altered natural rate.','legendary')
revise('PM2A-EXP-LB-012','A government repeatedly uses surprise demand expansion to hold unemployment below natural. Wage setters begin anticipating the next expansion. Compare continuing the same actual inflation rate with generating a fresh surprise.',
 ['The same anticipated inflation cannot preserve the original unemployment gain; a fresh surprise requires inflation above the updated expectation','The same anticipated inflation permanently lowers natural unemployment; a new surprise is unnecessary','Fresh surprises lower inflation while preserving unemployment below natural','Both choices permanently shift LRPC left because forecasting improves'],
 'Once the higher rate is expected, the short-run surprise disappears. Repeating the gain requires exceeding the updated expectation; under repeated adjustment this can mean accelerating inflation rather than a stable long-run tradeoff.','legendary')
revise('PM2A-SAC-FB-021','A country can accept at most4% cumulative output loss. The proposed2-point disinflation has ratio2.5. How much must the ratio fall for the target to fit the constraint?',
 ['To2, a reduction of0.5','To4, an increase of1.5','To1.25, a reduction of1.25','No reduction is needed because2.5 is less than4'],
 'Maximum affordable ratio=4/2=2; compared with2.5 the required improvement is.5 output-percent per inflation point.','hard',(('4/2',2),('2.5-4/2',.5)))
revise('PM2A-SAC-LB-025','Plan A cuts inflation4 points with losses3%,3%,2%. Plan B cuts2 points with losses1%,3%. A report recommends B as twice as efficient because its total loss is half as large. Which qualification is needed?',
 ['Both ratios are2; B costs less in total because it achieves half the disinflation, not because its measured cost per point is lower','B’s ratio is1 and A’s2; halving total loss always halves the ratio','A’s ratio is4 and B’s8; divide inflation reduction into only the last-year loss','B dominates every objective because a smaller total loss proves the larger target is unnecessary'],
 'A:(3+3+2)/4=2. B:(1+3)/2=2. Efficiency per inflation point is equal, while targets and loss timing differ; a policy choice also depends on the desired reduction.','elite',(('(3+3+2)/4',2),('(1+3)/2',2)))
revise('PM2A-SAC-FB-022','A two-stage plan cuts inflation4 points with a forecast total loss8%. Stage one cuts1 point at a loss3%. To keep the original total-loss forecast, what ratio must the remaining stage achieve?',
 ['5/3≈1.67','8/4=2','3/1=3','5/4=1.25'],
 'Remaining loss allowance=8−3=5; remaining reduction=4−1=3. Thus the second stage must average5/3≈1.67, below the first stage’s3.','hard',(('(8-3)/(4-1)',1.666666667),))
revise('PM2A-SAC-MB-019','A disinflation cuts inflation2 points in year one and1 point in year two. Output losses are2% and4% respectively. Which year has the lower loss per inflation point?',
 ['Year one:1 versus year two:4','Year two:0.25 versus year one:1','Both:2 because annual losses should be averaged first','Year one:2 versus year two:1 because only inflation changes matter'],
 'Calculate each year’s ratio with its own reduction:2/2=1 and4/1=4. A larger output loss accompanying a smaller inflation drop is more costly per point.','hard',(('2/2',1),('4/1',4)))
save()
