from author import *
groups=[
 ('43063 43094 43095 43101 43188 43202','Reverses revenues minus spending, giving public saving or the budget balance the wrong sign.'),
 ('43065','Reports the signed negative budget balance when the question asks for the positive deficit magnitude.'),
 ('43081 43152','Subtracts deficit-financed borrowing from the initial debt stock instead of accumulating it.'),
 ('43108','Counts borrowing proceeds as tax revenue rather than financing of the revenue shortfall.'),
 ('43116','Subtracts intragovernmental holdings from debt held by the public instead of adding them to obtain gross debt.'),
 ('43125','Subtracts debt from GDP and labels the difference a percentage instead of dividing debt by GDP.'),
 ('43138','Reports the complement of the debt-to-GDP share rather than debt divided by GDP.'),
 ('43142 43148','Converts the stated interest percentage to a decimal ten times too large when multiplying by the debt stock.'),
 ('43143','Uses total outlays as a percentage label rather than dividing interest outlays by total outlays.'),
 ('43192','Uses the magnitude of public dissaving alone instead of adding private and public saving.'),
 ('43212','Reports government purchases as investment instead of subtracting consumption and government purchases from output.'),
 ('43218 43250 43294 43306 PMOE-FX-E-004','Reads quantity from a different labeled location instead of the specified demand-supply intersection.'),
 ('43254 43279','Misreads the distance between the two equilibrium quantities on the horizontal axis.'),
 ('43256 43268 43274 43286 PMOE-FX-E-003','Uses a rate at a different location instead of reading the specified equilibrium intersection.'),
 ('PM2A-DIS-MB-015','Reports the additional inflation-point target without multiplying by the output cost per inflation point.'),
 ('PM2A-SAC-FB-022','Uses the completed first-stage sacrifice ratio for the remaining stage instead of its remaining loss and target.'),
 ('PMOE-NCO-B2-001 PMOE-TX-M-004','Reverses resident purchases of foreign assets minus foreign purchases of domestic assets.'),
 ('PMOE-NCO-H-004 PMOE-TX-LB-001','Rearranges NCO = resident foreign-asset purchases minus foreign domestic-asset purchases with the wrong sign.'),
 ('PMOE-NCO-L-001','Keeps only the upper foreign-purchase-growth threshold and omits the lower threshold required for a net inflow.'),
 ('PMOE-NCO-M-001','Reports the gross inward asset flow instead of subtracting it from the gross outward flow.'),
 ('PMOE-NER-B1-002 PMOE-NER-M-001','Does not multiply the dollar amount by the stated yen-per-dollar quotation.'),
 ('PMOE-NER-B2-001 PMOE-NER-M-006','Uses the ending exchange rate rather than the initial rate as the percentage-change denominator.'),
 ('PMOE-NER-B2-002','Treats the foreign-currency quantity alone as the reciprocal rate instead of dividing domestic units by foreign units.'),
 ('PMOE-NER-B3-003','Assumes reciprocal exchange-rate percentage changes have equal absolute magnitudes.'),
 ('PMOE-NER-E-001','Inverts the supplied euros-per-dollar quote even though the question already asks for euros per dollar.'),
 ('PMOE-NER-E-004 PMOE-NER-M-005','Fails to take the reciprocal when reversing the currencies in an exchange-rate quotation.'),
 ('PMOE-NER-H-002','Confuses a decimal rate of change with percentage units while reversing the currency quotation.'),
 ('PMOE-NER-L-001','Uses the package’s price-inflation percentage as the affordable exchange-rate decline, ignoring the initial budget margin.'),
 ('PMOE-NER-L-002','Treats a fall in home currency per foreign unit as an appreciation of the foreign asset’s currency, multiplying by1.05 rather than0.95.'),
 ('PMOE-NER-L-003','Adds the two percentage changes and treats that approximate shortfall as the exact volume increase needed to restore revenue.'),
 ('PMOE-NER-L-006','Uses an incorrect conversion/fee denominator instead of applying the fee to the converted dollar charge and comparing total dollar costs.'),
 ('PMOE-NER-M-003','Multiplies a euro price by euros per dollar instead of dividing to obtain dollars.'),
 ('PMOE-RER-B2-001','Omits the nominal exchange-rate factor and uses only the domestic-to-foreign price ratio.'),
 ('PMOE-RER-B2-002','Adds equal domestic and foreign inflation rather than using their difference under relative PPP.'),
 ('PMOE-RER-H-002','Adds domestic and foreign price growth instead of subtracting foreign inflation in the real exchange-rate comparison.'),
 ('PMOE-RER-H-003','Adds the domestic inflation differential to nominal depreciation instead of recognizing that it offsets real depreciation.'),
 ('PMOE-RER-L-003','Uses the inflation-difference approximation as an exact PPP adjustment and misclassifies the smaller nominal decline.'),
 ('PMOE-RER-M-001','Uses the reciprocal price ratio and omits the nominal conversion factor in the real exchange-rate formula.'),
 ('PMOE-TX-B1-001 PMOE-TX-M-003','Reverses the sign of exports minus imports or of the identity NX=NCO.'),
 ('PMOE-TX-H-005','Subtracts a trade surplus from investment instead of using national saving = investment + net exports.'),
 ('PMOE-TX-M-001','Adds exports and imports and assigns a negative sign instead of subtracting imports from exports.'),
 ('PMOE-TX-M-002','Adds saving and investment instead of subtracting investment from saving to obtain NCO.')
]
for ids,reason in groups:
 for id in ids.split():patch(id,commonError=reason)
save()
