import json,hashlib,re
from pathlib import Path
W=Path(__file__).resolve().parent
b=json.loads((W/'inventory-before.json').read_text('utf8'))['records'];s={}
def add(id,q,options,feedback,reason,numeric=False):
 assert len(options)==4
 s[str(id)]=dict(q=q,options=options,feedback=feedback,reason=reason,numeric=numeric)
def edit(id,replacements,reason,numeric=False,feedback=None):
 x=b[str(id)];q=x['q']
 for a,z in replacements:
  assert a in q,(id,a);q=q.replace(a,z)
 opts=x['options'];key=next(o for o in opts if hashlib.sha256(re.sub(r'\s+',' ',o.strip()).lower().encode()).hexdigest()==x['aHash'])
 add(id,q,[key]+[o for o in opts if o!=key],feedback or x['feedback'],reason,numeric)
add(43205,'In a closed economy, output is $1,240 billion, consumption is $790 billion and government purchases are $230 billion. Firms planned $250 billion of investment, including planned inventory accumulation. Output and final purchases are realized as stated. Which reconciliation is consistent with national accounting?',
 ['$220 billion of realized saving and investment, including a $30 billion unplanned inventory reduction','$220 billion of saving and $250 billion of realized investment, leaving a $30 billion accounting gap','$250 billion of realized saving and investment, with consumption automatically $30 billion lower','$220 billion of realized investment, including a $30 billion unplanned inventory increase'],
 'Realized saving is Y − C − G = 1,240 − 790 − 230 = $220 billion. Realized investment includes inventories, so it is also $220 billion. Relative to planned investment of $250 billion, unplanned inventory investment is −$30 billion. Equality of realized aggregates does not require equality of plans at every interest rate.',
 'Correct the equilibrium-only interpretation of S=I and require planned/realized reconciliation.',True)
add(43217,'Refer to the graph above. Treat the displayed curves as straight lines. At a temporary real interest rate of 10 percent, how large is the planned imbalance, and what adjustment returns this market toward A?',
 ['An 80-unit excess supply; a falling rate reduces saving supplied and increases investment demanded','A 40-unit excess supply; a falling rate shifts both curves toward A','An 80-unit excess demand; a rising rate reduces investment demanded and increases saving supplied','A 40-unit excess demand; a rising rate shifts saving supply right'],
 'At 10 percent, S0 supplies 180 units and D0 demands 100, leaving excess supply of 80. A lower rate moves down along S0 and D0 toward their intersection at 140 units and 8 percent; neither curve must shift.',
 'Replace repeated upper directional recognition with two actual-graph readings and adjustment logic.',True)
add(43219,'Refer to the graph above. Treat the lines as straight. Starting at A, a technology change shifts D0 horizontally right while S0 stays fixed. The new equilibrium real rate is 10 percent, although the new demand curve is not drawn. What can be inferred about the shift and the quantity response?',
 ['Demand shifted right by 80 units; equilibrium investment rose by 40 through movement along S0','Demand shifted right by 40 units; equilibrium investment rose by 40 through a rightward shift of S0','Demand shifted right by 80 units; equilibrium investment rose by 80 because saving must match the shift','Demand shifted right by 40 units; equilibrium investment rose by 80 through movement along D0'],
 'On S0, a 10 percent rate corresponds to 180 units. Old D0 demands 100 units at that rate, so the new demand schedule must be 80 units to the right. Equilibrium investment rises from 140 to 180, or 40 units. The unchanged saving schedule accommodates that quantity through a rate-induced movement; an accounting identity does not force a saving-supply shift.',
 'Add reverse shift reconstruction while separating equilibrium quantity, curve shift and accounting equality.',True)
add(43231,'At a real interest rate below equilibrium, desired investment exceeds desired saving. A student claims this disproves S = I in a closed economy. Which response correctly separates the accounting statement from the market adjustment?',
 ['Realized investment, including unplanned inventories, equals realized saving; excess demand for funds puts upward pressure on the rate','Realized saving exceeds realized investment until the rate rises; inventory changes are excluded from investment','Realized investment equals desired investment at every rate; the saving identity applies only after the rate adjusts','Realized saving includes the financing gap as foreign saving; the rate rises until that gap disappears'],
 'S = I is an ex-post closed-economy accounting identity, including inventory investment. Planned quantities can disagree at a posted rate; that behavioral imbalance creates upward pressure on the real rate. Market clearing explains compatible plans, not the validity of the identity.',
 'State the always-valid realized identity instead of implying that interest-rate adjustment creates accounting equality.')
add(43245,'Initially, desired investment is I = 300 − 10r, with I in billions of dollars and r measured in percentage points. Technology changes only the intercept. The real rate rises from 4 to 7 percent, and equilibrium investment rises by $20 billion. What happened to investment demand, and what would investment have been at the original rate after the technology change?',
 ['Demand shifted right by $50 billion; investment at 4 percent would be $310 billion','Demand shifted right by $20 billion; investment at 4 percent would be $280 billion','Demand shifted right by $30 billion; investment at 4 percent would be $290 billion','Demand shifted right by $50 billion; investment at 4 percent would be $280 billion'],
 'Initial investment is 300 − 10(4) = $260 billion, so the new equilibrium quantity is $280 billion. The 3-point rate increase reduces quantity demanded by $30 billion along the new schedule. Technology therefore raises demand by $50 billion at every rate, making investment $310 billion at 4 percent.',
 'Replace duplicate technology/rate-offset recognition with reverse decomposition and a counterfactual.',True)
add(43257,'Refer to the graph above. Each quantity unit represents $1 billion, and the lines are straight. A fiscal change lowers public saving by $55 billion at every real rate, while a separate incentive raises planned private saving by $15 billion at every rate. Investment demand does not shift. Which comparison correctly connects the policy shifts with A and B?',
 ['Saving supply shifts left by $40 billion, but equilibrium investment falls by $20 billion','Saving supply shifts left by $20 billion, and equilibrium investment falls by $40 billion','Saving supply shifts left by $70 billion, but equilibrium investment falls by $20 billion','Saving supply shifts left by $40 billion, and equilibrium investment falls by $40 billion'],
 'At any given rate, the saving-supply change is −55 + 15 = −$40 billion, matching the horizontal distance between S0 and S1. The marked equilibria move from 100 to 80, so investment falls by $20 billion. The higher rate partly offsets the supply reduction by inducing additional saving along the shifted schedule.',
 'Give graph quantities an explicit scale and distinguish fixed-rate fiscal offsets from the final equilibrium response.',True)
add(43259,'Refer to the graph above. Each quantity unit represents $1 billion. The straight S0 and S1 curves capture a fiscal change, with the private-saving schedule unchanged and D0 fixed. Starting from B, a second policy raises planned private saving by $15 billion at every real rate. How much must public saving rise from its level at B to restore A?',
 ['$25 billion; together the two changes restore the original saving schedule','$40 billion; the private-saving incentive cannot change national saving','$5 billion; the required saving shift equals the 20-unit equilibrium-quantity gap','$55 billion; the private-saving increase must be added to the original supply shortfall'],
 'At any given rate, S1 lies 40 units left of S0. Restoring S0 therefore requires $40 billion of additional planned national saving, not merely the 20-unit difference in equilibrium quantity. Private saving supplies $15 billion of that shift, leaving $25 billion of public saving. With D0 fixed, restoring S0 restores A.',
 'Replace missing-curve recognition with reverse fiscal reconstruction from actual horizontal shift geometry.',True)
add(43297,'Refer to the graph above. Each quantity unit represents $1 billion, and the curves are straight. A budget improvement shifts S0 to S1; the private-saving schedule and investment demand are unchanged. What does the graph imply about the rise in public saving and the induced change in private saving between A and B?',
 ['Public saving rises $80 billion; private saving falls $40 billion as the rate declines','Public saving rises $40 billion; private saving is unchanged because its schedule is fixed','Public saving rises $80 billion; private saving rises $40 billion as investment expands','Public saving rises $40 billion; private saving falls $80 billion because D0 does not shift'],
 'The horizontal supply shift is 80 units: at an 8 percent rate S0 is at 60 and S1 is at 140. With the private-saving schedule unchanged, that shift is the $80 billion public-saving increase. Final national saving and investment rise only from 60 to 100, or $40 billion. Private saving consequently changes by 40 − 80 = −$40 billion through movement along its schedule as the rate falls.',
 'Add reverse fiscal inference and distinguish a fixed private-saving schedule from its changing equilibrium quantity.',True)
add(43309,'Refer to the graph above. Each quantity unit represents $1 billion, and the straight-line shifts summarize all changes in saving and investment behavior. Public saving falls by $10 billion at every real rate, while technology raises investment demand. What private-saving shift is required to reconcile the graph with that fiscal change?',
 ['A $50 billion increase at every rate; net saving supply and investment demand each move right by $40 billion','A $30 billion increase at every rate; subtracting the public-saving decline gives the $40 billion supply increase','A $10 billion increase at every rate; an unchanged interest rate means national saving is unchanged','A $40 billion increase at every rate; public saving is excluded when constructing the saving-supply curve'],
 'At 6 percent, S0 and D0 each have quantity 40, while S1 and D1 each have quantity 80. Each schedule shifts right by $40 billion. Since national saving combines private and public saving, the private shift must satisfy private change − 10 = 40, giving +$50 billion. The two shifts leave the depicted equilibrium rate at 6 percent.',
 'Replace loosely scaled accounting/graph recognition with reverse component reconstruction using actual image quantities.',True)
add(43317,'A saving incentive raises planned national saving at every real rate, while weaker expected sales reduce desired investment at every real rate. With upward-sloping saving supply and downward-sloping investment demand, which conclusion and information requirement are correct?',
 ['The real rate falls; the relative shift magnitudes are needed to determine the investment-quantity change','The real rate falls; investment quantity must fall because only the demand shift affects quantity','Investment quantity rises; the relative shift magnitudes are needed to determine the real-rate change','The real rate rises; investment quantity must rise because the saving incentive finances more projects'],
 'More saving shifts supply right, while weaker sales shift demand left. Both changes lower the real rate. The supply change raises equilibrium quantity and the demand change lowers it, so their relative magnitudes determine the net investment response.',
 'Separate Hard from the near-duplicate one-direction Medium grammar by requiring partial identification.')
add(43069,'A budget worksheet reports $920 billion of cash inflows, including $180 billion from issuing new debt, and $870 billion of total outlays. All remaining inflows are revenues; there are no other financing adjustments. What are the budget balance and the amount of new borrowing left to increase cash balances?',
 ['A $130 billion deficit and a $50 billion cash increase','A $50 billion surplus and no borrowing needed for the outlays','A $130 billion deficit and a $180 billion cash increase','A $310 billion deficit and a $130 billion cash decrease'],
 'Revenues exclude borrowing: 920 − 180 = $740 billion. Revenues minus outlays equal 740 − 870 = −$130 billion. Of the $180 billion borrowed, $130 billion finances the deficit and $50 billion increases cash balances.',
 'Replace one-addition upper arithmetic with inflow classification and financing reconciliation.',True)
add(43070,'A government starts the year with $3,600 billion of debt. Revenues are $760 billion and outlays are $940 billion. It issues $500 billion of debt, including debt used to repay $270 billion of maturing principal; remaining financing may change cash balances. With no other debt or financing adjustments, which reconciliation is correct?',
 ['A $180 billion deficit, ending debt of $3,830 billion, and a $50 billion increase in cash','A $180 billion deficit, ending debt of $4,100 billion, and a $320 billion increase in cash','A $320 billion surplus, ending debt of $3,830 billion, and a $50 billion increase in cash','A $450 billion deficit, ending debt of $3,780 billion, and unchanged cash'],
 'The deficit is 940 − 760 = $180 billion; debt issuance is financing, not revenue. Net issuance is 500 − 270 = $230 billion, so ending debt is $3,830 billion. Net financing exceeds the deficit by $50 billion, increasing cash. Principal repayment is not counted again as a budget outlay.',
 'Replace borrowing-is-not-revenue recall with linked budget, rollover, debt-stock and cash reconciliation.',True)
add(43087,'At year-end a government owes $2,400 billion. During the final month its deficit was $20 billion. An analyst divides 2,400 by 20 and calls the result a 120 percent annual debt-growth rate. If the monthly deficit instead remained constant for a full future year, all deficits were borrowed, and no other debt adjustments occurred, what would the calculation establish?',
 ['The original quotient is 120 months of deficits; the stated future scenario implies 10 percent annual debt growth','The original quotient is a 120 percent growth rate; annualizing the deficit leaves that rate unchanged','The original quotient is 120 years of deficits; the stated future scenario implies 1 percent annual debt growth','The original quotient is a 10 percent growth rate; dividing it by 12 gives annual debt growth'],
 'A stock of $2,400 billion divided by a flow of $20 billion per month gives 120 months, not a percent growth rate. Under the explicit future assumption, twelve monthly deficits add $240 billion to debt; 240 / 2,400 = 10 percent. One observed month alone does not establish that future path.',
 'Strengthen stock/flow time-basis critique with a conditional annualization and growth reconciliation.',True)
add(43098,'A simplified fiscal account reports gross tax receipts of $900 billion, transfers of $180 billion, government purchases of $660 billion and interest payments of $70 billion. These are all revenues and outlays. For this exercise define T as gross taxes minus transfers, excluding interest. Which pair gives textbook public saving T − G and the full budget balance?',
 ['Public saving is $60 billion; the full budget has a $10 billion deficit','Public saving is $240 billion; the full budget has a $60 billion surplus','Public saving is −$10 billion; the full budget also has a $10 billion deficit','Public saving is $60 billion; the full budget has a $60 billion surplus'],
 'Under the stated convention, T = 900 − 180 = $720 billion and T − G = $60 billion. Total outlays are 180 + 660 + 70 = $910 billion, giving a $10 billion deficit. The $70 billion difference is interest, which this exercise excludes from net taxes. Transfers are already deducted in T and must not be deducted a second time.',
 'Repair an underspecified reconciliation by making gross/net tax, transfer and interest conventions explicit.',True)
add(43111,'A simplified government has only three outlay categories: purchases of current domestic goods and services, transfers, and interest. Purchases rise from $400 billion to $430 billion, transfers from $300 billion to $350 billion, and interest from $50 billion to $70 billion. Revenues rise by $60 billion. Which comparison is correct?',
 ['The deficit widens by $40 billion, while the direct increase in GDP government purchases is $30 billion','The deficit widens by $40 billion, while the direct increase in GDP government purchases is $100 billion','The deficit narrows by $30 billion, while the direct increase in GDP government purchases is $40 billion','The deficit widens by $100 billion, while the direct increase in GDP government purchases is $30 billion'],
 'Outlays rise by 30 + 50 + 20 = $100 billion. With revenues up $60 billion, the deficit widens $40 billion. Only the $30 billion increase in current purchases directly increases G; transfers and interest are budget outlays without being current government purchases. No induced output response is being calculated.',
 'Replace upper category recall with the different consequences of budget and national-income classifications.',True)
add(43134,'A government begins with debt equal to 80 percent of nominal GDP. During the year it borrows an amount equal to 4 percent of initial GDP to finance its deficit, with no other debt adjustments. Nominal GDP grows 8 percent. Which result reconciles the deficit, the debt stock and the debt ratio?',
 ['Debt rises 5 percent, but debt-to-GDP falls to about 77.8 percent','Debt rises 4 percent, and debt-to-GDP falls to exactly 76 percent','Debt falls 4 percent, so debt-to-GDP falls to about 77.8 percent','Debt rises 5 percent, so debt-to-GDP rises to 84 percent'],
 'Normalize initial GDP to 100: debt starts at 80, borrowing adds 4 and GDP rises to 108. Debt growth is 4 / 80 = 5 percent; the new ratio is 84 / 108 ≈ 77.8 percent. Faster denominator growth lowers the ratio despite the borrowing-financed deficit.',
 'State financing assumptions and replace qualitative reconciliation with linked ratio and stock-growth reasoning.',True)
add(43135,'Debt-to-GDP rises from 80 percent to 88 percent while nominal GDP rises 5 percent. The debt measure and accounting dates are comparable. Which comparison correctly separates the ratio change from the change in nominal debt?',
 ['The ratio rises 8 percentage points, or 10 percent; nominal debt rises 15.5 percent','The ratio rises 8 percentage points, or 10 percent; nominal debt rises 10 percent','The ratio rises 8 percent, or 10 percentage points; nominal debt rises 13 percent','The ratio rises 8 percentage points, or 10 percent; nominal debt rises 5 percent'],
 'The ratio increases by 8 points and by 8 / 80 = 10 percent relative to its initial level. Nominal debt changes by the ratio factor times the GDP factor: (88 / 80)(1.05) = 1.155, or 15.5 percent. The ratio growth rate is not the numerator growth rate when GDP also changes.',
 'Replace one-step upper percentage-point arithmetic with denominator-aware reconstruction.',True)
add(43137,'CBO’s February 2026 baseline projects debt held by the public at 101 percent of GDP in 2026 and 120 percent in 2036. An analyst claims that nominal debt would therefore rise 19 percent. For that nominal-debt growth claim to be consistent with these displayed ratios, what would nominal GDP have to do?',
 ['Rise by about 0.16 percent; the 19-percentage-point ratio increase is not itself nominal-debt growth','Rise by 19 percent; debt and GDP must grow at the same rate when the ratio increases','Remain exactly unchanged; subtracting the two ratios gives the percent growth in debt','Fall by about 15.8 percent; a higher debt ratio necessarily implies a smaller economy'],
 'Let GDP growth have factor g. The nominal-debt factor would be (120 / 101)g. Setting it to 1.19 gives g = 1.19(101 / 120) ≈ 1.001583, a 0.16 percent increase. This is a conditional consistency calculation using displayed rounded ratios, not CBO’s GDP projection.',
 'Deepen the existing projected-ratio checkpoint through reverse consistency rather than a repeated subtraction.',True)
add(43145,'In a simplified debt portfolio, $600 billion remains at a fixed 2 percent annual rate and $400 billion is refinanced from 2 to 5 percent at the start of the year. Principal stays constant; rates apply for the full year and there are no interest receipts. Revenues and noninterest outlays are unchanged. How do interest outlays and the deficit change?',
 ['Interest outlays become $32 billion and the deficit widens $12 billion','Interest outlays become $50 billion and the deficit widens $30 billion','Interest outlays become $20 billion and the deficit is unchanged','Interest outlays become $32 billion and the deficit widens $32 billion'],
 'Initial interest is (600 + 400)(0.02) = $20 billion. New interest is 600(0.02) + 400(0.05) = 12 + 20 = $32 billion. The $12 billion increase widens the deficit by the same amount. The current refinancing rate applies only to the repriced portion, not the whole portfolio.',
 'Turn a generic portfolio caveat into integrated refinancing arithmetic and budget feedback.',True)
add(43156,'Two packages require the same additional borrowing, leave public saving equally lower, and face the same unchanged private-saving and investment-demand schedules. Package A finances productive public infrastructure; Package B finances transfers. What evidence is needed to decide whether A leaves more total productive capital than before the policy?',
 ['Whether the public-capital addition exceeds the private-capital formation displaced by the higher real rate','Whether A issues less debt than B, even though their additional borrowing is stated to be equal','Whether transfers count as current public-capital formation at the moment they are paid','Whether a decline in public saving is itself a one-for-one measure of lost private capital'],
 'Both packages create the same initial loanable-funds pressure under the stated schedules. A also adds public productive capital. Its net capital effect depends on that addition relative to displaced private capital formation; borrowing alone does not establish the sign. No project-valuation or AD-AS model is needed for this comparison.',
 'Replace a broad all-borrowing-harmful rebuttal with a constrained public/private capital comparison.')
add(43158,'A deficit reduces public saving at every real rate. A separate household incentive exactly offsets that reduction in planned private saving at every rate, while an investment tax credit also raises desired investment. In the closed-economy loanable-funds model, what can be concluded relative to the initial equilibrium?',
 ['The saving curve is unchanged; the real rate and equilibrium private investment rise','The saving curve shifts left; the real rate rises and private investment must fall','Both curves are unchanged; exact private-saving offset also cancels the investment tax credit','The saving curve shifts right; private investment rises but the real rate must fall'],
 'The public- and private-saving shifts cancel at every rate, leaving national-saving supply unchanged. The tax credit separately shifts investment demand right. With an upward-sloping saving curve, the new equilibrium has a higher real rate and more private investment. A higher rate alone does not prove crowding out when investment demand also changes.',
 'Replace a generic borrowing/rate claim with offsetting policies and a separate investment incentive.')
add(43167,'CBO’s February 2026 baseline gives projected debt-held-by-the-public ratios of 101 percent of GDP in 2026 and 120 percent in 2036. Using only these displayed ratios, when would nominal debt in 2036 exceed nominal debt in 2026?',
 ['When nominal GDP in 2036 exceeds about 84.2 percent of its 2026 level; the ratios alone do not establish GDP’s change','When nominal GDP in 2036 exceeds 120 percent of its 2026 level; a smaller GDP increase implies falling debt','Only when nominal GDP is unchanged; otherwise the two debt ratios cannot be compared','For every possible positive GDP level in 2036; a higher ratio proves a larger nominal debt stock'],
 'Debt is its GDP share times nominal GDP. Thus 1.20 × GDP2036 must exceed 1.01 × GDP2026, requiring GDP2036 / GDP2026 > 101 / 120 ≈ 0.8417. A higher ratio alone does not identify nominal-debt growth without denominator evidence. This threshold uses the displayed rounded ratios and is not a forecast of GDP.',
 'Replace repeated projected-ratio recognition with partial identification and a reverse denominator threshold.',True)
edit(43203,[('private saving rises by $20 billion while public saving falls by $35 billion','at every given real interest rate, planned private saving rises by $20 billion while public saving falls by $35 billion')], 'Distinguish fixed-rate schedule shifts from realized saving changes before inferring ambiguous final quantity.',True)
edit(43210,[('with output and consumption fixed in a closed economy','in a closed economy with output fixed and the consumption schedule unchanged at each given real rate')], 'Avoid holding realized consumption fixed while relying on an upward-sloping saving schedule and an ambiguous final rate.',True)
edit(43189,[('Private saving','At every given real interest rate, planned private saving')], 'Make the private/public changes schedule shifts rather than an unstated final equilibrium constraint.',True)
edit(43227,[('private saving','private-saving behavior')], 'Hold private-saving behavior fixed rather than its final quantity in the deficit mechanism.')
edit(43252,[('output and consumption remain fixed','output remains fixed and the consumption schedule is unchanged at each given real rate')], 'Make the fiscal graph shift consistent with a rate-responsive private-saving schedule.')
edit(43264,[('Public saving falls','At every given real interest rate, public saving falls'),('private saving rises','planned private saving rises')], 'Specify the fixed-rate fiscal and private-saving changes underlying the supply shift.',True)
edit(43154,[('Which sequence stays within the intended Principles-level boundary?','A government raises purchases with net taxes unchanged. Private-saving behavior is unchanged. Which sequence describes the fiscal consequence?')], 'Replace a curriculum-boundary prompt with a student-facing fiscal application.')
edit(43162,[(', last updated August 26, 2026','')], 'Remove a moving dataset-update claim while preserving the dated-observation skill.')
s['43162']['q']=s['43162']['q'].replace('dataset, reports','dataset reports')
s['43203']['q']=s['43203']['q'].replace('without shift magnitudes','without knowing the investment-demand shift magnitude')
s['43203']['feedback']='At each given real rate, planned national saving falls by $15 billion, shifting supply left. Technology shifts investment demand right. Both shifts raise the real rate, but their quantity effects oppose one another; the final change in realized saving and investment is therefore not fixed at −$15 billion.'
s['43210']['feedback']='At each given real rate, lower purchases raise planned national saving by $25 billion and shift supply right. Stronger sales expectations shift investment demand right. Both raise equilibrium quantity, but their opposing rate pressures make the rate depend on relative shift magnitudes.'
s['43154']['options']=['Public saving falls and the budget moves toward deficit, increasing borrowing needs if the shortfall is debt-financed','Private saving falls but public saving is unchanged, because government purchases are household consumption','Public saving rises and the budget moves toward surplus, reducing the need to issue government debt','Public saving falls but issuing debt counts as revenue, so borrowing restores the budget balance']
s['43154']['feedback']='With net taxes unchanged, higher government purchases reduce public saving T − G and move the budget toward deficit. Borrowing can finance the shortfall, but debt issuance does not count as revenue or reverse the decline in public saving.'
(W/'revisions.json').write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n','utf8')
print(f'{len(s)} targeted content revisions, {sum(x["numeric"] for x in s.values())} numeric.')
