import json,hashlib,copy,re
from pathlib import Path
from collections import Counter
W=Path(__file__).resolve().parent;R=Path(r'C:\Users\Jennings\Documents\GitHub\masteryquests-website\build\faculty-build-composer');REPO=R.parent.parent
def rd(n):return json.loads((W/n).read_text('utf8'))
def wr(n,x):(W/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n','utf8')
def sha(x):return hashlib.sha256(x).hexdigest()
def loc(m):return [(p,q) for p,qs in m['questions'].items() for q in qs]+[(p,q) for p in ['repairQuestions','repairSeedQuestions','bridgeQuestions'] for q in m.get(p,[])]
b=rd('inventory-before.json');a=rd('inventory-after.json');v=rd('validation.json');acc=rd('accounting.json');s=rd('revisions.json');ch=rd('changes.json');before=rd('quality-before.json');after=rd('quality-after.json');browser=rd('browser-validation.json');obj=rd('objective-findings-before.json');old=rd('library-baseline.json');new=rd('library-after.json');overlap=rd('overlap-mask.json')
for c in old['concepts']:
 if c not in b['views']:assert old['concepts'][c]==new['concepts'][c],c
permittedGlobal={'concepts','assetInventory','librarySha256','registry'}
assert {k:x for k,x in old.items() if k not in permittedGlobal}=={k:x for k,x in new.items() if k not in permittedGlobal}
assert {k:v for k,v in old['registry'].items() if k!='librarySha256'}=={k:v for k,v in new['registry'].items() if k!='librarySha256'}
def stripAccess(x):return [{k:v for k,v in a.items() if k not in ['imageAlt','graphDescription']} for a in x]
assert stripAccess(old['assetInventory'])==stripAccess(new['assetInventory'])
for name in ['composer_registry.json','composer_library_manifest.json']:
 x=json.loads((R/'data'/name).read_text('utf8'));y=rd('staged/'+name)
 for z in [x,y]:
  z.pop('librarySha256')
  if 'assets' in z:z['assets']=stripAccess(z['assets'])
 assert x==y,name
nohash=copy.deepcopy(new);del nohash['librarySha256'];del nohash['registry']['librarySha256'];semantic=sha(json.dumps(nohash,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode());assert semantic==new['librarySha256']
wr('semantic-validation.json',{'before':old['librarySha256'],'after':semantic,'independentlyRecomputed':True,'sidecarsSynchronized':True,'unrelatedGlobalDataUnchanged':True})
arch=rd('architecture-validation.json');review=[]
for x in b['conceptReview']['assets']:
 actual=sha((R/x['sourcePath']).read_bytes());assert actual==x['sha256'];review.append({**x,'bytesVerified':True})
arch.update(reviewAssets=review,reviewRuntimeIndex=b['conceptReview']['runtimeIndex'],reviewGlobalWarningsRetained=b['conceptReview']['warnings'])
for p,h in b['sourceFiles'].items():assert sha((R/p).read_bytes())==h,'Changed since baseline: '+p
prior=REPO/'validation_artifacts/money_banking_monetary_system_assessment_audit_2026_09_08'
arch['priorAuditArtifactFilesBeforeApply']={str(x.relative_to(prior)):sha(x.read_bytes()) for x in prior.rglob('*') if x.is_file()}
arch['priorAuditAll13ModulesPreserved']=all(old['concepts'][c]==new['concepts'][c] for c in overlap['protectedPriorConceptIds']);assert arch['priorAuditAll13ModulesPreserved'];assert not overlap['sharedAuthoritativeIds']
wr('architecture-validation.json',arch)
assert len(browser['graphChecks'])==60 and all(x['loaded'] and x['zoomOK'] and x['description'] for x in browser['graphChecks'])
wr('graph-validation.json',{'registeredAssetsInspected':rd('accessibility-inspection.json'),'all60GraphRecordsRenderedAndEnlarged':True,'graphEligibilityBeforeAfter':{'linked':[60,60],'trialGraph':[59,59]},'imagePathsCorrected':0,'imageBytesChanged':0,'newAssets':0,'checks':browser['graphChecks'],'limitation':'The local generated-game smoke test verifies image delivery and enlargement; it does not test deployed CDN delivery or all gameplay branches.'})
# Every quality flag gets a record-specific disposition, including flags removed after revision.
specific={
'43098':'The original vague public-saving/budget distinction was replaced with explicitly defined taxes, transfers and interest plus a numerical reconciliation. The original absolute-distractor flag is no longer reported.',
'43093':'The alternatives confuse net-tax accounting with fiscal neutrality; public saving remains T−G. Absolute language is an elimination cue, retained as a nonblocking distractor weakness.',
'43320':'The key says investment can enlarge physical capital; distractors overstate guaranteed growth or confuse flows and stocks. Appropriate introductory conditionality is preserved.',
'43323':'The core Hard inference is lower-than-counterfactual capital versus an absolute decline. Absolute alternatives encode that precise error; some remain easier to eliminate.',
'43325':'The item distinguishes lower capital formation from a necessary fall in output or the existing stock. The conditional key is sound; distractor wording remains simple.',
'43117':'Different debt definitions can produce different values. Absolutes deny measurement or collapse measures; retain the useful Medium definition boundary while disclosing the cue.',
'43118':'The two supplied debt totals imply intragovernmental holdings. Distractors confuse that stock difference with a deficit or a different measure; some categorical wording remains.',
'43120':'Same-date releases with different measure labels need not conflict. The task remains direct for Elite; retained as a residual upper-tier/distractor limitation, not declared fully remediated.',
'43166':'Measure, date, projected/observed status and units all matter. The surviving Legendary item is a fairly direct checklist and its only/nothing alternatives are weak; retained without claiming every upper item is equally deep.',
'43082':'A debt-stock headline can coexist with a smaller annual deficit. The key is correct but this Hard item is more direct than the stronger retained stock/flow applications.',
'43083':'Debt changes can differ from deficits because of financing adjustments. Alternatives deny the difference or confuse aggregates; the accounting caveat is valuable despite absolute wording.',
'43158':'The revised item requires exact saving-shift cancellation plus an independent demand shift. Unchanged/must distractors encode the offset and rate-direction errors; the heuristic flag is retained.',
'43219':'False positive from the SIMPLE_READING / REASONING_CUE regex test: inferred is not the regex token infer. The undrawn new demand curve must be reconstructed at a new rate, then its horizontal shift distinguished from the equilibrium change. Independent proof gives 80 versus 40 units. Do not rewrite to game the cue regex.',
'43241':'Both rightward shifts imply a quantity increase and an ambiguous rate. Absolute alternatives are misconceptions about simultaneous shifts; the Hard causal comparison is retained.',
'43249':'The student must reject an investment-demand determinant as an explanation for a supply-only graph. This is a modest inverse application at the easier edge of Hard; retain alongside deeper Hard items, with the calibration flag disclosed.',
'43285':'Both leftward shifts lower quantity but oppose each other on the rate. Absolute direction/unchanged-rate alternatives test that distinction; still a relatively short Legendary task.',
'43305':'The Hard item distinguishes general theoretical ambiguity from the particular plotted result. Necessity language in the alternatives is part of that misconception, though it gives an elimination cue.',
'43308':'An Easy graph-recognition item identifies both changed schedules. Only/both alternatives are appropriate basic contrasts but easy to eliminate once both dashed lines are noticed.',
'43313':'The marked B intersection resolves this particular rate outcome. Distractors improperly generalize to all simultaneous shifts or treat axes as causal; their absolutes remain disclosed.',
'43317':'The revised Hard task combines two determinants, a common rate effect and an ambiguous quantity. Only/must alternatives test which shift affects quantity; retained without changing metadata to silence the flag.',
'43181':'The key rejects one-saver/one-project matching. Absolute distractors encode the aggregation error; this support/checkpoint grammar is retained.',
'43182':'The bridge links household saving to financing and capital formation. Its absolute distractors are simple; preserve the bridge and routing rather than inflate its difficulty.',
'43203':'The revised fixed-rate saving shifts and independent technology shock imply an unambiguous rate but ambiguous final quantity. Only/must distractors encode omitted-curve reasoning; keep the honest flag.',
'43208':'Easy aggregate identity correction rejects one-to-one saver/investor matching. The literal absolutes make alternatives weak but the introductory key remains appropriate.',
'43210':'The revised Hard scenario shifts both curves right. Only/must distractors omit a shock or reverse its effect; retain the complete application and disclose the cue.',
'43213':'The given components imply 300 of planned supply versus 340 desired investment at the current rate. The upward-rate key is sound; categorical distractors remain a limitation.',
'43205':'The original equilibrium-only identity key was replaced with realized/plan inventory reconciliation; the old absolute-distractor flag is no longer reported.',
'43309':'The original loosely scaled component example was replaced with a reverse private-saving shift calculation using a stated graph scale; the old flag is no longer reported.',
'43318':'The old near-duplicate pair was separated by revising Hard 43317 to ask for both the rate direction and the information needed to identify quantity. Medium 43318 remains unchanged.',
'43231':'The revised response explicitly separates realized accounting from planned-market adjustment and uses substantive alternatives.',
'43087':'The revision now requires dimensional analysis and a conditional annual debt-growth calculation, replacing a largely definitional response.'}
bf={(x['questionId'],x['rule']):x for x in before['findings']};af={(x['questionId'],x['rule']):x for x in after['findings']};disp=[]
for k in sorted(bf.keys()|af.keys()):
 f=af.get(k,bf.get(k));status='retained' if k in bf and k in af else 'newly-reported' if k in af else 'no-longer-reported'
 assert k[0] in specific,k
 disp.append({'questionId':k[0],'rule':k[1],'severity':f['severity'],'status':status,'contentRevised':k[0] in s,'reason':specific[k[0]],'auditorMessage':f['message']})
wr('quality-dispositions.json',{'before':before['counts'],'after':after['counts'],'beforeScope':268,'afterScope':268,'method':'Unmodified existing question_quality_auditor.mjs against actual authoritative baseline and staged library, all seven direct concepts and every pool. No derived projection needed. Every original/final question-rule pair is individually dispositioned.','findings':disp})
examSource=rd('exam-source.json');assert sha(Path(examSource['path']).read_bytes())==examSource['sha256']
exam=(W.parent/'.money-work/exam-text.txt').read_text('utf8')
def grams(x,n=12):
 t=re.findall(r'[a-z]+',x.lower());return {' '.join(t[i:i+n]) for i in range(len(t)-n+1)}
examGrams=grams(exam);originality=[]
for id,sp in s.items():
 oldText=b['records'][id]['q']+' '+' '.join(b['records'][id]['options'])+' '+b['records'][id]['feedback'];newText=sp['q']+' '+' '.join(sp['options'])+' '+sp['feedback'];hits=grams(newText)&examGrams;novel=hits-grams(oldText)
 assert not novel,(id,novel)
 originality.append({'id':id,'new12WordExamOverlap':len(novel),'inherited12WordOverlap':len(hits),'humanComparison':'Uses current bank accounting, original constraints or existing library graph geometry; no exam item was used as a rewrite template.'})
wr('originality-validation.json',{'examSource':examSource,'method':'Reused the previously read full exam and visually inspected seven exam figures after verifying the identical document SHA-256. Screened final stems, options and feedback for new 12-word overlap, then compared cognitive tasks. Q23 supplies causal-mechanism calibration; Q30 is only an interest-sensitive-investment boundary cue.','limitation':'Text overlap is a screen, not a proof of originality. Generic textbook terminology and retained preexisting content are not evidence of new copying.','newImageAssets':0,'examImagesCopied':0,'items':originality})
wr('logical-validation.json',{'scope':268,'allScopedOptionsNormalizedDistinct':True,'allScopedOneHashMatch':True,'allScopedNonemptyStemFeedback':True,'revisedStemsUniqueAcrossLibrary':True,'revisedRecords':[{'id':id,'reason':sp['reason'],'finalStem':sp['q'],'correctOption':sp['options'][0],'distractors':sp['options'][1:],'economicReview':'Key follows the explicit accounting convention, behavioral assumptions or actual image evidence. Alternatives were reviewed for omitted components, wrong signs, stock/flow or measure confusion, reversed curve effects and unjustified identification. Independent arithmetic is separately recorded for every revised numerical item.'} for id,sp in s.items()]})
members={}
for c,m in b['views'].items():
 for p,q in loc(m):members.setdefault(q['id'],[]).append(c+':'+p)
wr('pool-memberships.json',{'allOrderedSourcePools':{c:{p:[q['id'] for pp,q in loc(m) if pp==p] for p in dict(loc(m))} for c,m in b['views'].items()},'multipleMemberships':{i:x for i,x in members.items() if len(x)>1},'sourceMembershipCount':sum(map(len,members.values())),'uniqueCount':len(members),'composedCounts':b['composedCounts'],'trialGraphIds':b['routes']['trialGraph'],'calculationNote':'There are 23 calculation-typed records but zero records in a separate calculation pool. Preserve ordinary canonical-difficulty placement and all checkpoint routing.'})
hard=[i for i,q in b['records'].items() if q['canonicalDifficulty']=='hard' and i not in s]
wr('retained-hard.json',[{'id':i,'concept':b['records'][i]['primaryConceptId'],'objective':b['records'][i]['objective'],'stem':b['records'][i]['q'],'contentUnchanged':True,'accessibilityOnly':any(c['id']==i for c in ch)} for i in hard])
assert len(hard)==52
def table(headers,rows):return ['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(str(x).replace('|','/') for x in row)+' |' for row in rows]
def sect(n,title,*paras):return ['',f'## {n}. {title}','',*sum(([p,''] for p in paras),[])]
lines=['# Saving, Investment, Budgets & Debt — production assessment-quality audit','',
'The existing bank is strong: **268 unique records and 19 selected objectives**, with substantial ordinary exam reasoning already at Hard. This audit makes **30 content revisions and 53 accessibility-only record changes**, leaves **185 records unchanged**, and adds or removes no records. Path-only changes: **0**. All 22 revised numerical items were independently recomputed. All 60 graph records render and enlarge, all ten modes remain ready, and the existing auditor reports **0 errors, 0 warnings and 25 review flags**.','',
'Only the canonical library and its required registry/manifest sidecars change in production. The preceding Money/Banking audit is preserved. No commit, push, merge or deployment is part of this task.']
lines+=sect(1,'Exact live preset','Discovered in `build/faculty-build-composer/composer.js`: **`macro-saving-investment-budgets-debt` — “Saving, Investment, Budgets & Debt.”** The working label was not treated as a preset or curricular definition. Composer core, source library, registry, manifest, direct definitions, graph contracts, Concept Review routing and mode eligibility were inspected. The BEFORE inventory and objective findings were recorded in the canonical artifact directory before authoring content.')
lines+=sect(2,'Selected concepts and views','All seven selections are direct. There are no derived parents in this preset. Current runtime membership defines scope; historical source occurrences do not. Exact IDs, source and canonical difficulty, type, tag, objectives, skills, subtopics, sourceChapter, provenance, aliases and ordered memberships appear in the before/after JSON inventories.')
lines+=table(['Direct concept ID','Before = after','Source objective counts'],[(c,x['unique'],', '.join(f'{k}: {n}' for k,n in x['objectives'].items())) for c,x in b['byConcept'].items()])
lines+=sect(3,'Actual curricular boundary','Selected: private/public/national saving; real versus financial investment; the closed-economy identity; real-interest loanable-funds equilibrium; saving/investment incentives; movements and shifts; crowding out and capital formation; budgets, revenues, outlays, borrowing, debt measures, debt/GDP, interest costs and fiscal-data interpretation.','The bank uses **national saving as supply and private investment as demand**. Fiscal deficits reduce public saving and shift supply left, other things equal. No government-borrowing-demand convention was imposed. Financial-system references help distinguish saving from real investment, but there are no separately selected stock/bond taxonomy, intermediary, present/future-value, compounding, risk, diversification, valuation or efficient-market objectives. Those absences are scope boundaries. AD-AS stabilization, money-demand/supply and Fisher-effect work are outside this audit.')
lines+=sect(4,'Prior Money/Banking overlap mask','The preceding `money-banking-inflation` preset contains 818 records in 13 modules. The current 268-record preset shares **zero authoritative question IDs** with it. All 13 previous modules matched the completed prior-audit baseline and are unchanged in the final library. All 142 nonselected concept definitions remain identical. No prior monetary content was re-authored merely because interest rates appear in both topics. See `overlap-mask.json` and `architecture-validation.json`.')
lines+=sect(5,'Before/after accounting','Mutually exclusive record dispositions sum to 268. Asset contracts are counted separately from question records. `record-actions.json` dispositions every ID; `accounting.json` supplies added, removed, content, accessibility, path-only and unchanged counts for every concept, objective, canonical difficulty and type.')
lines+=table(['Disposition','Count'],[('Before / after','268 / 268'),('Added / removed','0 / 0'),('Content revised',30),('Accessibility-only',53),('Path-only',0),('Unchanged',185),('Revised numerical records',22),('Graph contracts corrected',8)])
lines+=['']+table(['Concept','Content','Accessibility only','Path only','Unchanged'],[(c,x['content-revised'],x['accessibility-only'],x['path-only'],x['unchanged']) for c,x in acc['byConcept'].items()])
lines+=sect(6,'Difficulty counts','Canonical and source difficulty, including checkpoint difficulty and every repair/bridge classification, remain unchanged. There are no unknown canonical-difficulty records in this selected bank.')
lines+=table(['Canonical difficulty','Before = after','Content revised','Accessibility only','Unchanged'],[(d,n,acc['byCanonicalDifficulty'][d]['content-revised'],acc['byCanonicalDifficulty'][d]['accessibility-only'],acc['byCanonicalDifficulty'][d]['unchanged']) for d,n in b['difficulty'].items()])
lines+=sect(7,'Types and pools',f"There are {sum(map(len,members.values()))} raw source memberships across 268 unique IDs. Exact ordered source and composed collections are recorded in `pool-memberships.json` and both inventories. No pool was rebuilt or reclassified.")
lines+=table(['Source type','Before = after','Content revised','Accessibility only','Unchanged'],[(t,n,acc['byType'][t]['content-revised'],acc['byType'][t]['accessibility-only'],acc['byType'][t]['unchanged']) for t,n in b['types'].items()])
lines+=['']+table(['Composed pool','Before = after'],[(p,b['composedCounts'][p]) for p in ['easy','medium','hard','elite','legendary','easyBoss','mediumBoss','finalBoss','legendaryBoss','repair','repairSeed','bridge','calculation','integration','challengeTotal']])
lines+=['','Ordinary banks total 200 records. The three ordinary checkpoint tiers total 30, Legendary checkpoints 10, repair 14 and bridge 14. Calculation-typed questions remain in their existing difficulty banks; the separate calculation pool is empty. All repair/bridge mappings, retest-related metadata and checkpoint ordering are preserved.']
lines+=sect(8,'Objective-by-objective findings','A = missing coverage; B = robustness; C = ordinary application placed too high; D = calculation/integration precision; E = missing meaningful graph use; F = upper-tier depth; G = no material gap. The table summarizes the immutable pre-authoring findings; revisions resolve selected issues without asserting that every question is equally demanding.')
lines+=table(['Objective and label','Records','BEFORE classification','Finding','Content changes'],[(x['objective']+' — '+x['label'],x['count'],', '.join(x['classifications']),x['finding'],v['contentByObjective'].get(x['objective'],0)) for x in obj])
lines+=sect(9,'True coverage gaps','No selected objective was materially absent. No questions or graph assets were added. Financial valuation, diversification and monetary/AD-AS topics absent from the live selection are boundaries rather than gaps.')
lines+=sect(10,'Robustness findings','Repetition is concentrated in upper-tier grammars: technology versus rate effects, budget financing recognition, and simple subtraction of projected debt ratios. These are chiefly classified F because strong Hard coverage already exists. Targeted inverse, conditional and reconciliation tasks replace selected repeated forms. The near-duplicate Medium/Hard pair 43318/43317 is separated by retaining the Medium direction question and giving Hard a quantity-identification requirement. Some direct upper items and simple distractors remain; a mature-bank audit does not justify rewriting every usable variant.')
lines+=sect(11,'Calibration findings','No systemic C gap was found. The 58 canonical Hard records already include multi-transaction classification, component arithmetic, planned-market disequilibrium, graph causation, fiscal chains and denominator comparisons. **52 retain their question content**; six receive corrections or a more substantive application. Elite/Legendary revisions account for 23 of the 30 content changes. No difficulty metadata or pool tier changed.')
lines+=sect(12,'Numerical and integration findings','Twenty-two revised numerical records were independently recomputed from final staged stems with rational arithmetic. Graph interpolation uses coordinates transcribed from the inspected images, not old answers. The verifier covers all revised numerical items, including changes limited to assumptions. Every selected record has four distinct normalized options and exactly one matching answer hash; revised alternatives were also reviewed for economic uniqueness.','Representative results: 43205 has realized saving/investment of 220 and unplanned inventory investment of −30; 43070 reconciles a 180 deficit, 230 net issuance, 3,830 ending debt and 50 cash growth; 43098 gives textbook public saving of 60 versus a full-budget deficit of 10 under the explicitly stated interest convention; 43145 gives 32 interest outlays and a 12 increase in the deficit. Full final inputs, derivations and keyed alternatives are in `numerical-validation.json`.')
lines+=sect(13,'Graph-use findings','Meaningful graph use was already present; no E coverage gap was found. All **8 registered image files** were visually inspected. All **60 graph-linked records** remain linked; **59** remain Trial-by-Graph eligible (15 Easy, 19 Medium, 16 Hard, 5 Elite, 4 Legendary). Eligibility flags were not changed to improve audit counts.','The revised graph problems distinguish the full horizontal curve shift from the smaller equilibrium-quantity response, infer an undrawn demand curve, and reconstruct fiscal/private-saving offsets. Every graph byte and registered path remains unchanged. The generated-game browser check renders all 60 images, opens every enlargement and verifies description delivery. Eight contracts have corrected or expanded visual evidence. No new graphs were needed.')
lines+=sect(14,'Upper-tier synthesis findings','Selective Elite/Legendary improvements require inventory reconciliation, reverse demand reconstruction, fixed-rate versus realized saving decomposition, debt issuance versus principal rollover and cash balances, budget versus GDP classification, refinancing exposure, and denominator thresholds. These tasks use introductory selected models without importing corporate valuation or monetary stabilization.','Not every retained upper record now exceeds ordinary exam demand: 43120 and 43166 remain direct measure-comparison/checklist items; 43285 remains a compact simultaneous-shift application. These are residual calibration limitations disclosed rather than hidden through retagging or wholesale replacement.')
lines+=sect(15,'Strong existing Hard questions retained','Examples below retain stems, options, feedback and answer keys. Graph examples may receive accessibility-only changes. The complete 52-ID retained-content list is in `retained-hard.json`.')
examples={'43170':'Distinguishes a secondary-market share purchase, new financing and actual factory investment.','43173':'Separates production, inventory investment and sale across periods.','43199':'Combines a fixed fiscal balance with a private-saving change.','43207':'Uses a technology shock to distinguish investment-demand behavior from an accounting identity.','43213':'Combines private/public saving and compares planned supply with desired investment at a posted rate.','43241':'Combines saving and technology incentives and identifies the ambiguous rate.','43261':'Distinguishes equilibrium-quantity change from horizontal supply displacement.','43269':'Infers a demand determinant from joint rate/quantity increases with supply fixed.','43275':'Diagnoses weaker investment demand from falling rate and quantity.','43290':'Explains a movement along investment demand after a fiscal saving shock.','43323':'Distinguishes lower-than-counterfactual capital from a necessary absolute stock decline.','43081':'Accumulates two deficits into debt under explicit financing assumptions.','43083':'Recognizes that financing adjustments separate deficits from debt changes.','43130':'Recomputes a ratio while both nominal debt and GDP rise.','43136':'Compares two economies using relative numerator/denominator growth.'}
for i in examples:assert i in hard
lines+=table(['ID','Why retain'],examples.items())
lines+=sect(16,'Specific revisions and reasons','`changes.json` gives exact before/after fields for all changed records. All 30 content changes are listed here; accessibility-only records are separately dispositioned.')
lines+=table(['ID','Canonical difficulty','Objective','Reason'],[(i,b['records'][i]['canonicalDifficulty'],b['records'][i]['objective'],x['reason']) for i,x in s.items()])
lines+=sect(17,'Economic and numerical defects corrected','43205 no longer describes S=I as merely an equilibrium relationship; 43231 explicitly separates always-valid realized accounting, including inventories, from planned imbalances. 43203 and 43210 now distinguish changes in schedules at a given rate from final realized saving, avoiding a false fixed-quantity inference in simultaneous-shift scenarios.','43098 defines gross taxes, transfers, purchases and interest before comparing public saving with the full budget. 43134 states the borrowing-finance assumption before connecting a deficit to the debt stock. The graph reconstructions give an explicit currency scale when dollar magnitudes matter and derive shift sizes from the actual straight lines. 43162 removes an unstable dataset “last updated” claim while retaining its dated-stock interpretation. No reversed graph key or image-byte defect was found in this pool.','The February 2026 CBO figures remain explicitly historical projections: revenues/outlays of 5.6/7.4 trillion, a separately rounded 1.9 trillion deficit, debt ratios of 101/120 percent, and rising interest outlays. The report itself warns that rounded components may not sum to totals; retained rounded-value questions are not erroneous for that reason. New ratio exercises use displayed values and label their conditional calculations. [CBO February 2026 baseline](https://www.cbo.gov/publication/62105).','Debt measures and dated stock observations retain their distinct Treasury meanings. No live debt amount was substituted into the bank. Treasury’s official reporting pages distinguish debt held by the public, intragovernmental holdings and debt-limit measures, and provide dated debt history. [Treasury debt reporting](https://www.treasurydirect.gov/government/public-debt-reports/debt-position-and-activity-report/), [Treasury debt history](https://www.treasurydirect.gov/mobile/).')
lines+=sect(18,'Accessibility and paths','All eight shared contracts now describe axes, the actual printed curve labels, straight-line coordinates, marked intersections and applicable guides/grid. Only LOANABLE-01 visibly prints saving/investment parentheticals; other contracts use their actual S/D labels. LOANABLE-06 no longer names the crowding-out conclusion. LOANABLE-08 no longer performs the quantity-change subtraction. Evidence permits reconstruction without supplying the assessed economic inference.','All 60 inline graph contracts are synchronized: seven coincide with content changes and 53 are accessibility-only. There are **zero path fixes, zero path-only records and zero new or altered image files**. The initial intersection evidence on LOANABLE-01 was accurate and was retained with additional line coordinates needed for the revised calculations. Detailed metadata was not shortened merely because of length.')
lines+=sect(19,'Final-exam calibration','The supplied ECO 2251 Final Exam was used only for cognitive/style calibration. Its bytes match the previously inspected exam. Q23 supports ordinary causal reasoning from a fiscal change through financing conditions to private investment at Hard. Q30 supplies only the boundary reminder that investment responds to rates; its AD-AS/stabilization chain was not imported.','The exam does not define selected objectives or supply templates. New records use independent budget constraints, inventory accounting, actual existing library graphs and reverse ratio tests. No exam question, answer pattern or image was copied, renamed or revalued. A 12-word screening comparison of revised stems, options and feedback finds no new overlap; this supplements human task comparison and is not treated as proof of originality. See `originality-validation.json`.')
lines+=sect(20,'Mode readiness','All ten modes retain identical readiness and eligibility before and after. Composer returns no errors; core answer verification passes for all 268 records.')
lines+=table(['Mode','Before','After'],[(x['label'],'ready','ready') for x in v['modeValidation']['modes']])
lines+=['','Trial by Graph retains 59 eligible records; Fading Fortune and Risk & Reward each retain 200. The local Edge smoke test verifies all 83 changed payloads and all 60 graph records. It is not an all-mode gameplay or telemetry test. External requests were blocked during the generated-game test.']
lines+=sect(21,'Concept Review and architecture integrity','All seven selected review routes and local PDF SHA-256 values are unchanged. Central HTTPS runtime routes remain as listed below. The engine, template, UI, mode logic, telemetry, classroom access, Workers and unrelated content were not modified. Record IDs, source/canonical difficulty, skills, provenance including sourceHash/sourceOccurrences, pool order, repair/bridge maps and checkpoint/retest metadata are unchanged.')
lines+=table(['Concept','Review code','Runtime route'],[(c,x['primaryReviewCode'],x['assets'][0]['path']) for c,x in b['conceptReview']['runtimeIndex']['concepts'].items()])
lines+=['','The resolver still emits 11 preexisting global diagnostics: eight parent-covered-by-children notices, one no-sheet meta-concept notice, and orphan/unreachable notices for MICRO-03. None concerns a missing selected review sheet. Exact diagnostic objects and checked local PDF hashes are preserved in `architecture-validation.json`. Deployed PDF endpoints were not fetched during the local browser smoke test.']
lines+=sect(22,'Remaining warnings and review flags',f"Existing auditor: before **{before['counts']['errors']} errors / {before['counts']['warnings']} warnings / {before['counts']['reviews']} reviews**; after **{after['counts']['errors']} errors / {after['counts']['warnings']} warnings / {after['counts']['reviews']} reviews**. The final 25 reviews comprise 23 absolute-distractor flags and two difficulty-overstatement flags. Every before/final record-rule pair has an individual disposition in `quality-dispositions.json`; no rules were disabled or edited.",'43219 is a regex false positive: the task requires inverse line reconstruction, despite the checker not recognizing “inferred” as its “infer” cue. 43249 is a modest inverse graph application at the easier edge of Hard and remains flagged. Some absolute alternatives meaningfully express misconceptions; others remain weak elimination cues. The report does not equate zero errors with perfect distractors or uniformly deep upper tiers.')
lines+=table(['ID','Rule','Disposition'],[(x['questionId'],x['rule'],x['reason']) for x in disp if x['status']!='no-longer-reported'])
lines+=sect(23,'Remaining limitations','This is a content and delivery audit, not an empirical item-discrimination or student-performance study. Some retained direct upper-tier questions, similar introductory grammars and easy-to-eliminate alternatives remain. Adequate Hard applications were preserved rather than rewritten for stylistic uniformity.','The existing linear loanable-funds and simplified fiscal accounting models are instructional assumptions. Other valid textbook conventions were not imposed. Detailed graph evidence can legitimately make basic coordinate questions easy for any learner; accessibility was not weakened to make them harder. Direct Fiscal Data pages returned access errors during this session, so official Treasury reporting/history pages supplied the accessible cross-check; no current daily amount is claimed.','Validation is local: all-mode composition readiness, unchanged routing, independent revised arithmetic, complete graph rendering/enlargement and generated payload checks. No claim is made about untested full gameplay branches or remote CDN state. Production changes remain local and require no deployment, commit, merge or push in this task.')
lines+=sect(24,'Final semantic library hash',f"**`{semantic}`**",f"BEFORE: `{old['librarySha256']}`. The semantic SHA-256 was independently recomputed using sorted canonical JSON with the two self-referential hash fields excluded. Library, registry and manifest agree. Only `build/faculty-build-composer/data/composer_library.js`, `composer_registry.json` and `composer_library_manifest.json` are changed for this audit; the sidecars synchronize required hashes and existing asset-accessibility metadata.")
(W/'FINAL_REPORT.md').write_text('\n'.join(lines)+'\n','utf8')
files=['FINAL_REPORT.md','BEFORE.md','OBJECTIVE_FINDINGS_BEFORE.md','inventory-before.json','inventory-after.json','summary-before.json','objective-findings-before.json','scope-boundary.json','overlap-mask.json','audit-projection-provenance.json','exam-source.json','record-actions.json','accounting.json','changes.json','revisions.json','asset-accessibility-changes.json','accessibility-spec.json','accessibility-inspection.json','quality-before.json','quality-before.md','quality-after.json','quality-after.md','quality-dispositions.json','numerical-validation.json','graph-validation.json','architecture-validation.json','semantic-validation.json','originality-validation.json','logical-validation.json','pool-memberships.json','retained-hard.json','validation.json','browser-validation.json','browser-smoke.png','recipe.json','concepts.json','sources.json','stage.mjs','verify.py','browser.cjs','finish.py','author.py','accessibility.py','findings.py']
for p in files:assert (W/p).is_file(),p
wr('deliverables.json',files+['deliverables.json'])
print(json.dumps({'reportSections':len(re.findall(r'^## \d+\.',(W/'FINAL_REPORT.md').read_text('utf8'),re.M)),'artifacts':len(files)+1,'quality':after['counts'],'dispositionPairs':len(disp),'independentHash':semantic,'originalityRecords':len(originality)}))
